function build_rasterplot_DF( ...
        data, ...
        gcamp_output_folders, ...
        gcamp_root_folders, ...
        animal_path, ...
        current_line, ...
        current_animal, ...
        current_dates, ...
        current_ages, ...
        sampling_rate, ...
        automatic_selection, ...
        output_folder)

    numFolders = numel(gcamp_output_folders);

    animal_file_name = strrep( ...
        char(string(current_animal)), ...
        ' ', ...
        '_');

    line_file_name = strrep( ...
        char(string(current_line)), ...
        ' ', ...
        '_');
    
    if isempty(strtrim(line_file_name))
        line_prefix = '';
    else
        line_prefix = [line_file_name '_'];
    end

    %==============================================================
    % Chemin de la figure globale de l'animal
    %==============================================================
    fig_save_animal = fullfile( ...
        animal_path, ...
        sprintf( ...
            '%s_%s_all_dates_all_ages_concat_rasters.png', ...
            line_prefix, ...
            animal_file_name));

    for m = 1:numFolders

        %==========================================================
        % Vérifier le dossier GCaMP de la date
        %==========================================================
        if isempty(gcamp_output_folders{m}) || ...
                ~iscell(gcamp_output_folders{m}) || ...
                isempty(gcamp_output_folders{m}{1})

            fprintf( ...
                'Group %d: gcamp_output_folders vide, skip.\n', ...
                m);

            continue;
        end

        %==========================================================
        % Vérifier le sampling rate
        %==========================================================
        current_sampling_rate = double(sampling_rate{m}(1));

        if ~isfinite(current_sampling_rate) || current_sampling_rate <= 0
        
            fprintf( ...
                'Group %d: sampling rate invalide, skip.\n', ...
                m);
        
            continue;
        end
        nPlanes = numel(gcamp_output_folders{m});

        %==========================================================
        % Texte de l'âge utilisé dans les noms de fichiers
        %==========================================================
        if numel(current_ages) >= m && ...
                ~isempty(current_ages{m})

            current_age_text = char(string( ...
                current_ages{m}));

        else

            current_age_text = sprintf('Age_%d', m);
        end

        age_file_name = strrep( ...
            current_age_text, ...
            ' ', ...
            '_');

        %==========================================================
        % Texte de la date utilisé dans les noms de fichiers
        %==========================================================
        if numel(current_dates) >= m && ...
                ~isempty(current_dates{m})

            current_date_text = char(string( ...
                current_dates{m}));

        else

            current_date_text = sprintf('Date_%d', m);
        end

        date_file_name = strrep( ...
            current_date_text, ...
            ' ', ...
            '_');

        %==========================================================
        % Motion branch
        %==========================================================
        
        %----------------------------------------------------------
        % Speed active
        %----------------------------------------------------------
        speed_active = [];
        
        if isfield(data, 'motion') && ...
                isstruct(data.motion) && ...
                isfield(data.motion, 'speed_active_group') && ...
                iscell(data.motion.speed_active_group) && ...
                numel(data.motion.speed_active_group) >= m && ...
                ~isempty(data.motion.speed_active_group{m})
        
            speed_active = ...
                data.motion.speed_active_group{m};
        end
        
        %----------------------------------------------------------
        % Motion energy
        %----------------------------------------------------------
        motion_energy = [];
        
        if isfield(data, 'motion') && ...
                isstruct(data.motion) && ...
                isfield(data.motion, 'motion_energy_group') && ...
                iscell(data.motion.motion_energy_group) && ...
                numel(data.motion.motion_energy_group) >= m && ...
                ~isempty(data.motion.motion_energy_group{m})
        
            motion_energy = ...
                data.motion.motion_energy_group{m};
        end
        
        %----------------------------------------------------------
        % Flags
        %----------------------------------------------------------
        has_motion_energy = ...
            ~isempty(motion_energy);
        
        line_width_trace = ...
            1.5;

        %==========================================================
        % 1) RASTERS PAR PLAN
        %==========================================================
        for p = 1:nPlanes
        
            fig = [];
        
            try
                %--------------------------------------------------
                % Vérifier le dossier du plan
                %--------------------------------------------------
                current_plane_folder = ...
                    gcamp_output_folders{m}{p};
        
                if isempty(current_plane_folder) || ...
                        exist(current_plane_folder, 'dir') ~= 7
        
                    fprintf( ...
                        ['Group %d plane %d: dossier de sortie ' ...
                         'invalide, skip.\n'], ...
                        m, p-1);
        
                    continue;
                end
        
                %--------------------------------------------------
                % Construire le chemin local
                %--------------------------------------------------
                fig_save_path = fullfile( ...
                    current_plane_folder, ...
                    sprintf( ...
                        '%s%s_%s_%s_plane%d_rastermap.png', ...
                        line_prefix, ...
                        animal_file_name, ...
                        date_file_name, ...
                        age_file_name, ...
                        p-1));
        
                %--------------------------------------------------
                % Construire le chemin de copie automatic_selection
                %
                % Age <= 15  -> output_folder\Development\
                % Age >  15  -> output_folder\Adult\
                %--------------------------------------------------
                fig_save_output = '';
                
                if automatic_selection && ~isempty(output_folder)
                
                    %--------------------------------------------------
                    % Récupérer l'âge numérique
                    %--------------------------------------------------
                    current_age_value = NaN;
                
                    if numel(current_ages) >= m && ...
                            ~isempty(current_ages{m})
                
                        current_age_value = ...
                            str2double( ...
                                regexprep( ...
                                    char(string(current_ages{m})), ...
                                    '[^\d\.]', ...
                                    ''));
                    end
                
                    %--------------------------------------------------
                    % Choisir development ou adult
                    %--------------------------------------------------
                    if isfinite(current_age_value) && ...
                            current_age_value <= 15
                
                        current_output_folder = fullfile( ...
                            output_folder, ...
                            'Development');
                
                    else
                
                        current_output_folder = fullfile( ...
                            output_folder, ...
                            'Adult');
                    end
                
                    %--------------------------------------------------
                    % Créer le dossier si nécessaire
                    %--------------------------------------------------
                    if exist(current_output_folder, 'dir') ~= 7
                        mkdir(current_output_folder);
                    end
                
                    %--------------------------------------------------
                    % Construire le chemin de sauvegarde
                    %--------------------------------------------------
                    fig_save_output = fullfile( ...
                        current_output_folder, ...
                        sprintf( ...
                            '%s%s_%s_%s_plane%d_rastermap.png', ...
                            line_prefix, ...
                            animal_file_name, ...
                            date_file_name, ...
                            age_file_name, ...
                            p-1));
                end

                %--------------------------------------------------
                % Vérifier indépendamment les deux destinations
                %--------------------------------------------------
                plane_raster_exists = ...
                    exist(fig_save_path, 'file') == 2;
                
                output_raster_exists = false;
                
                if automatic_selection && ~isempty(fig_save_output)
                    output_raster_exists = ...
                        exist(fig_save_output, 'file') == 2;
                end
                
                %--------------------------------------------------
                % DEBUG : afficher exactement ce qui est testé
                %--------------------------------------------------
                % fprintf('\n--- Raster existence check ---\n');
                % fprintf('Plane %d\n', p-1);
                % fprintf('automatic_selection = %d\n', logical(automatic_selection));
                % fprintf('fig_save_path:\n%s\n', fig_save_path);
                % fprintf('plane_raster_exists = %d\n', plane_raster_exists);
                % 
                % if automatic_selection
                %     fprintf('fig_save_output:\n%s\n', fig_save_output);
                %     fprintf('output_raster_exists = %d\n', output_raster_exists);
                % end
                
                %--------------------------------------------------
                % Déterminer si une génération est nécessaire
                %--------------------------------------------------
                need_local_raster = ~plane_raster_exists;
                
                need_output_raster = ...
                    automatic_selection ; %&& ...
                    %~output_raster_exists;
                
                %--------------------------------------------------
                % Skip seulement si absolument rien n'est à créer
                %--------------------------------------------------
                if ~need_local_raster && ~need_output_raster
                
                    fprintf([ ...
                        'Plane raster already exists in all required ' ...
                        'locations, processing skipped.\n']);
                
                    continue;
                end
                %--------------------------------------------------
                % Charger les données seulement si nécessaire
                %--------------------------------------------------
                [DFp, isort_p, MAct_p] = ...
                    get_plane_data(data, m, p);

                if isempty(DFp)

                    fprintf( ...
                        ['Group %d plane %d: DF vide, ' ...
                         'skip raster plan.\n'], ...
                        m, p-1);

                    continue;
                end

                [NCell, Nz] = size(DFp);

                if NCell == 0 || Nz == 0

                    fprintf( ...
                        'Group %d plane %d: DF vide, skip.\n', ...
                        m, p-1);

                    continue;
                end

                isort_p = sanitize_isort( ...
                    isort_p, ...
                    NCell);

                MAct_p = resize_MAct( ...
                    MAct_p, ...
                    Nz);

                prop_MAct_p = ...
                    MAct_p / max(NCell, 1);

                total_time = Nz / current_sampling_rate;
                t_sec = (0:Nz-1) / current_sampling_rate;

                activity_segs_sec = ...
                    build_activity_segments( ...
                        speed_active, ...
                        total_time);

                %==========================================================
                % Toujours 3 axes :
                % 1 = raster
                % 2 = proportion active
                % 3 = motion energy
                %==========================================================
                subplot_count = 3;
                
                fig = figure( ...
                    'Color', 'w');
                
                set( ...
                    fig, ...
                    'Position', ...
                    get(0, 'ScreenSize'));
                
                %--------------------------------------------------
                % AXE 1 : Raster
                %--------------------------------------------------
                ax1 = subplot( ...
                    subplot_count, ...
                    1, ...
                    1);
                
                A = double(DFp(isort_p, :));
                A_z = robust_zscore_rows(A);
                
                imagesc( ...
                    ax1, ...
                    t_sec, ...
                    1:NCell, ...
                    A_z);
                
                axis(ax1, 'tight');
                
                set( ...
                    ax1, ...
                    'TickLength', [0 0], ...
                    'YDir', 'normal');
                
                ylabel( ...
                    ax1, ...
                    'Neurons', ...
                    'FontSize', 18);
                
                colormap(ax1, parula);
                clim(ax1, [0.1 2]);
                
                title( ...
                    ax1, ...
                    sprintf( ...
                        'Sorted raster of GCaMP cells activity - Plane %d', ...
                        p-1), ...
                    'FontSize', 20, ...
                    'FontWeight', 'bold');
                
                xlim(ax1, [0 total_time]);
                
                %--------------------------------------------------
                % AXE 2 : Proportion de cellules actives
                %--------------------------------------------------
                ax2 = subplot( ...
                    subplot_count, ...
                    1, ...
                    2);
                
                plot( ...
                    ax2, ...
                    t_sec, ...
                    prop_MAct_p, ...
                    'LineWidth', ...
                    line_width_trace);
                
                ylabel( ...
                    ax2, ...
                    'Proportion (0-1)', ...
                    'FontSize', 18);
                
                title( ...
                    ax2, ...
                    sprintf( ...
                        'Proportion of Active GCaMP Cells - Plane %d', ...
                        p-1), ...
                    'FontSize', 20, ...
                    'FontWeight', 'bold');
                
                grid(ax2, 'off');
                box(ax2, 'off');
                
                xlim(ax2, [0 total_time]);
                
                % Afficher les périodes de mouvement
                plot_activity_bands( ...
                    ax2, ...
                    activity_segs_sec);
                
                %--------------------------------------------------
                % AXE 3 : Motion energy
                %--------------------------------------------------
                ax3 = subplot( ...
                    subplot_count, ...
                    1, ...
                    3);
                
                if has_motion_energy
                
                    t_motion = linspace( ...
                        0, ...
                        total_time, ...
                        numel(motion_energy));
                
                    plot( ...
                        ax3, ...
                        t_motion, ...
                        motion_energy, ...
                        'LineWidth', ...
                        line_width_trace);
                
                    ylabel( ...
                        ax3, ...
                        'Motion energy', ...
                        'FontSize', 18);
                
                    title( ...
                        ax3, ...
                        'Motion Energy', ...
                        'FontSize', 20, ...
                        'FontWeight', 'bold');
                
                    plot_activity_bands( ...
                        ax3, ...
                        activity_segs_sec);
                
                else
                
                    text( ...
                        ax3, ...
                        0.5, ...
                        0.5, ...
                        'No motion energy available', ...
                        'Units', 'normalized', ...
                        'HorizontalAlignment', 'center', ...
                        'FontSize', 14);
                
                    ylabel( ...
                        ax3, ...
                        'Motion energy', ...
                        'FontSize', 18);
                
                    title( ...
                        ax3, ...
                        'Motion Energy', ...
                        'FontSize', 20, ...
                        'FontWeight', 'bold');
                
                    xlim(ax3, [0 total_time]);
                end
                
                box(ax3, 'off');
                grid(ax3, 'off');
                
                xlabel( ...
                    ax3, ...
                    'Time (s)', ...
                    'FontSize', 18);
                
                xlim(ax3, [0 total_time]);
                
                %--------------------------------------------------
                % Synchroniser les 3 axes temporels
                %--------------------------------------------------
                linkaxes( ...
                    [ax1 ax2 ax3], ...
                    'x');

                %--------------------------------------------------
                % Sauvegarde locale uniquement si nécessaire
                %--------------------------------------------------
                if need_local_raster
                
                    saveas(fig, fig_save_path);
                
                    fprintf( ...
                        'Raster plot saved in:\n%s\n', ...
                        fig_save_path);
                
                else
                
                    fprintf( ...
                        'Local raster already exists, not overwritten:\n%s\n', ...
                        fig_save_path);
                end
                
                %--------------------------------------------------
                % Copie automatic_selection uniquement si nécessaire
                %--------------------------------------------------
                if need_output_raster
                
                    saveas(fig, fig_save_output);
                
                    fprintf( ...
                        'Automatic-selection raster copy saved in:\n%s\n', ...
                        fig_save_output);
                end
                
                %--------------------------------------------------
                % Copie dans output_folder uniquement si nécessaire
                %--------------------------------------------------
                if automatic_selection && ~output_raster_exists
                
                    saveas(fig, fig_save_output);
                
                    fprintf( ...
                        'Automatic-selection raster copy saved in:\n%s\n', ...
                        fig_save_output);
                
                end
                
                close(fig);
                fig = [];
            catch ME

                fprintf( ...
                    '\nError for group %d plane %d: %s\n', ...
                    m, p-1, ME.message);

                if ~isempty(fig) && ishghandle(fig)
                    close(fig);
                end
            end
        end

        %==========================================================
        % 2) RASTER CONCATÉNÉ
        %==========================================================
        if nPlanes > 1

            fig = [];

            try
                %--------------------------------------------------
                % Construire le chemin avant la concaténation
                %--------------------------------------------------
                fig_save_path = fullfile( ...
                    gcamp_root_folders{m}, ...
                    sprintf( ...
                        '%s_%s_%s_%s_rastermap_concat.png', ...
                        line_prefix, ...
                        animal_file_name, ...
                        date_file_name, ...
                        age_file_name));

                %--------------------------------------------------
                % Ne pas concaténer ou trier si la figure existe
                %--------------------------------------------------
                if exist(fig_save_path, 'file') == 2

                    fprintf([ ...
                        'Concatenated raster already exists, ' ...
                        'all processing skipped:\n%s\n'], ...
                        fig_save_path);

                else

                    [DF_concat, isort_concat, MAct_concat] = ...
                        get_concat_data(data, m);

                    if isempty(DF_concat)

                        fprintf( ...
                            ['Group %d: DF concaténé vide, ' ...
                             'skip raster concat.\n'], ...
                            m);

                    else

                        [NCell, Nz] = size(DF_concat);

                        if NCell == 0 || Nz == 0

                            fprintf( ...
                                ['Group %d: DF concaténé vide, ' ...
                                 'skip raster concat.\n'], ...
                                m);

                        else

                            isort_concat = sanitize_isort( ...
                                isort_concat, ...
                                NCell);

                            MAct_concat = resize_MAct( ...
                                MAct_concat, ...
                                Nz);

                            prop_MAct = ...
                                MAct_concat / max(NCell, 1);

                            total_time = Nz / current_sampling_rate;
                            t_sec = (0:Nz-1) / current_sampling_rate;

                            activity_segs_sec = ...
                                build_activity_segments( ...
                                    speed_active, ...
                                    total_time);

                            subplot_count = ...
                                2 + has_motion_energy;

                            fig = figure( ...
                                'Color', 'w');

                            set( ...
                                fig, ...
                                'Position', ...
                                get(0, 'ScreenSize'));

                            %--------------------------------------
                            % Raster concaténé
                            %--------------------------------------
                            ax1 = subplot( ...
                                subplot_count, ...
                                1, ...
                                1);

                            A = double( ...
                                DF_concat(isort_concat, :));

                            A_z = robust_zscore_rows(A);

                            imagesc( ...
                                ax1, ...
                                t_sec, ...
                                1:NCell, ...
                                A_z);

                            axis(ax1, 'tight');

                            set( ...
                                ax1, ...
                                'TickLength', [0 0], ...
                                'YDir', 'normal');

                            xlabel(ax1, 'Time (s)');
                            ylabel(ax1, 'Neurons');

                            colormap(ax1, parula);
                            clim(ax1, [0.1 2]);

                            title( ...
                                ax1, ...
                                'Raster plot concaténé (z-score)');

                            xlim(ax1, [0 total_time]);

                            %--------------------------------------
                            % Activité concaténée
                            %--------------------------------------
                            ax2 = subplot( ...
                                subplot_count, ...
                                1, ...
                                2);

                            plot( ...
                                ax2, ...
                                t_sec, ...
                                prop_MAct, ...
                                'LineWidth', ...
                                line_width_trace);

                            ylabel( ...
                                ax2, ...
                                'Prop. Active Cells');

                            title( ...
                                ax2, ...
                                ['Proportion of Active Cells ' ...
                                 '- concaténé']);

                            grid(ax2, 'off');
                            box(ax2, 'off');

                            xlim(ax2, [0 total_time]);

                            plot_activity_bands( ...
                                ax2, ...
                                activity_segs_sec);

                            axes_list = [ax1 ax2];

                            %--------------------------------------
                            % Motion energy
                            %--------------------------------------
                            if has_motion_energy

                                ax3 = subplot( ...
                                    subplot_count, ...
                                    1, ...
                                    3);

                                x_stretched = linspace( ...
                                    0, ...
                                    total_time, ...
                                    numel(motion_energy));

                                plot( ...
                                    ax3, ...
                                    x_stretched, ...
                                    motion_energy, ...
                                    'LineWidth', ...
                                    line_width_trace);

                                xlabel(ax3, 'Time (s)');
                                ylabel(ax3, 'Motion energy');
                                title(ax3, 'Motion Energy');

                                box(ax3, 'off');
                                grid(ax3, 'off');

                                xlim(ax3, [0 total_time]);

                                plot_activity_bands( ...
                                    ax3, ...
                                    activity_segs_sec);

                                axes_list = ...
                                    [axes_list ax3]; %#ok<AGROW>
                            end

                            linkaxes(axes_list, 'x');

                            saveas(fig, fig_save_path);

                            fprintf( ...
                                ['Concatenated raster plot ' ...
                                 'saved in:\n%s\n'], ...
                                fig_save_path);

                            close(fig);
                            fig = [];
                        end
                    end
                end

            catch ME

                fprintf( ...
                    ['\nError for concatenated raster ' ...
                     'group %d: %s\n'], ...
                    m, ME.message);

                if ~isempty(fig) && ishghandle(fig)
                    close(fig);
                end
            end

            %======================================================
            % 3) SUMMARY DATE : PLANS + CONCATÉNÉ + MOTION
            %======================================================
            fig = [];

            try
                %--------------------------------------------------
                % Construire et vérifier le chemin avant les données
                %--------------------------------------------------
                fig_save_summary = fullfile( ...
                    gcamp_root_folders{m}, ...
                    sprintf( ...
                        '%s_%s_%s_%s_rastermap_summary.png', ...
                        line_prefix, ...
                        animal_file_name, ...
                        date_file_name, ...
                        age_file_name));

                if exist(fig_save_summary, 'file') == 2

                    fprintf([ ...
                        'Summary raster already exists, ' ...
                        'all processing skipped:\n%s\n'], ...
                        fig_save_summary);

                else

                    valid_plane_idx = [];

                    for p = 1:nPlanes

                        [DFp, ~, ~] = ...
                            get_plane_data(data, m, p);

                        if ~isempty(DFp)
                            valid_plane_idx(end+1) = p; %#ok<AGROW>
                        end
                    end

                    [DF_concat, isort_concat, MAct_concat] = ...
                        get_concat_data(data, m);

                    has_concat = ~isempty(DF_concat);

                    has_summary_motion = ...
                        has_motion_energy;

                    if isempty(valid_plane_idx) && ...
                            ~has_concat

                        fprintf( ...
                            ['Group %d: no valid planes for ' ...
                             'summary figure.\n'], ...
                            m);

                    else

                        nValidPlanes = ...
                            numel(valid_plane_idx);

                        nRows_main = ...
                            nValidPlanes + double(has_concat);

                        nRows = ...
                            nRows_main + ...
                            double(has_summary_motion);

                        nCols = 2;

                        fig = figure( ...
                            'Color', 'w');

                        set( ...
                            fig, ...
                            'Position', ...
                            get(0, 'ScreenSize'));

                        row_counter = 0;

                        %------------------------------------------
                        % Plans individuels
                        %------------------------------------------
                        for idx = 1:nValidPlanes

                            p = valid_plane_idx(idx);

                            [DFp, isort_p, MAct_p] = ...
                                get_plane_data(data, m, p);

                            [NCell_p, Nz_p] = size(DFp);

                            if NCell_p == 0 || Nz_p == 0
                                continue;
                            end

                            row_counter = row_counter + 1;

                            isort_p = sanitize_isort( ...
                                isort_p, ...
                                NCell_p);

                            MAct_p = resize_MAct( ...
                                MAct_p, ...
                                Nz_p);

                            prop_MAct_p = ...
                                MAct_p / max(NCell_p, 1);

                            total_time_p = ...
                                Nz_p / current_sampling_rate;

                            t_sec_p = ...
                                (0:Nz_p-1) / current_sampling_rate;

                            activity_segs_sec_p = ...
                                build_activity_segments( ...
                                    speed_active, ...
                                    total_time_p);

                            % Raster du plan
                            ax_r = subplot( ...
                                nRows, ...
                                nCols, ...
                                (row_counter-1)*nCols + 1);

                            A = double( ...
                                DFp(isort_p, :));

                            A_z = robust_zscore_rows(A);

                            imagesc( ...
                                ax_r, ...
                                t_sec_p, ...
                                1:NCell_p, ...
                                A_z);

                            axis(ax_r, 'tight');

                            set( ...
                                ax_r, ...
                                'TickLength', [0 0], ...
                                'YDir', 'normal');

                            colormap(ax_r, parula);
                            clim(ax_r, [0 2]);

                            xlim( ...
                                ax_r, ...
                                [0 total_time_p]);

                            ylabel( ...
                                ax_r, ...
                                sprintf( ...
                                    'Plane %d\nNeurons', ...
                                    p-1));

                            title( ...
                                ax_r, ...
                                sprintf( ...
                                    'Raster plane %d', ...
                                    p-1));

                            % Cellules actives du plan
                            ax_a = subplot( ...
                                nRows, ...
                                nCols, ...
                                (row_counter-1)*nCols + 2);

                            plot( ...
                                ax_a, ...
                                t_sec_p, ...
                                prop_MAct_p, ...
                                'LineWidth', ...
                                line_width_trace);

                            box(ax_a, 'off');
                            grid(ax_a, 'off');

                            xlim( ...
                                ax_a, ...
                                [0 total_time_p]);

                            ylabel( ...
                                ax_a, ...
                                'Prop. active');

                            title( ...
                                ax_a, ...
                                sprintf( ...
                                    'Active cells plane %d', ...
                                    p-1));

                            plot_activity_bands( ...
                                ax_a, ...
                                activity_segs_sec_p);
                        end

                        %------------------------------------------
                        % Concaténation
                        %------------------------------------------
                        if has_concat

                            [NCell_c, Nz_c] = ...
                                size(DF_concat);

                            if NCell_c > 0 && Nz_c > 0

                                row_counter = row_counter + 1;

                                isort_concat = ...
                                    sanitize_isort( ...
                                        isort_concat, ...
                                        NCell_c);

                                MAct_concat = ...
                                    resize_MAct( ...
                                        MAct_concat, ...
                                        Nz_c);

                                prop_MAct_c = ...
                                    MAct_concat / ...
                                    max(NCell_c, 1);

                                total_time_c = ...
                                    Nz_c / current_sampling_rate;

                                t_sec_c = ...
                                    (0:Nz_c-1) / ...
                                    current_sampling_rate;

                                activity_segs_sec_c = ...
                                    build_activity_segments( ...
                                        speed_active, ...
                                        total_time_c);

                                % Raster concaténé
                                ax_r = subplot( ...
                                    nRows, ...
                                    nCols, ...
                                    (row_counter-1)*nCols + 1);

                                A = double( ...
                                    DF_concat( ...
                                        isort_concat, :));

                                A_z = robust_zscore_rows(A);

                                imagesc( ...
                                    ax_r, ...
                                    t_sec_c, ...
                                    1:NCell_c, ...
                                    A_z);

                                axis(ax_r, 'tight');

                                set( ...
                                    ax_r, ...
                                    'TickLength', [0 0], ...
                                    'YDir', 'normal');

                                colormap(ax_r, parula);
                                clim(ax_r, [0 2]);

                                xlim( ...
                                    ax_r, ...
                                    [0 total_time_c]);

                                ylabel( ...
                                    ax_r, ...
                                    sprintf( ...
                                        'Concat\nNeurons'));

                                title( ...
                                    ax_r, ...
                                    'Raster concaténé');

                                % Activité concaténée
                                ax_a = subplot( ...
                                    nRows, ...
                                    nCols, ...
                                    (row_counter-1)*nCols + 2);

                                plot( ...
                                    ax_a, ...
                                    t_sec_c, ...
                                    prop_MAct_c, ...
                                    'LineWidth', ...
                                    line_width_trace);

                                box(ax_a, 'off');
                                grid(ax_a, 'off');

                                xlim( ...
                                    ax_a, ...
                                    [0 total_time_c]);

                                ylabel( ...
                                    ax_a, ...
                                    'Prop. active');

                                title( ...
                                    ax_a, ...
                                    'Active cells concaténé');

                                plot_activity_bands( ...
                                    ax_a, ...
                                    activity_segs_sec_c);
                            end
                        end

                        %------------------------------------------
                        % Motion
                        %------------------------------------------
                        if has_summary_motion

                            row_counter = row_counter + 1;

                            if has_concat

                                total_time_motion = ...
                                    size(DF_concat, 2) / ...
                                    current_sampling_rate;

                            elseif ~isempty(valid_plane_idx)

                                p0 = valid_plane_idx(1);

                                [DF0, ~, ~] = ...
                                    get_plane_data( ...
                                        data, ...
                                        m, ...
                                        p0);

                                total_time_motion = ...
                                    size(DF0, 2) / ...
                                    current_sampling_rate;

                            else

                                total_time_motion = ...
                                    numel(motion_energy);
                            end

                            t_motion = linspace( ...
                                0, ...
                                total_time_motion, ...
                                numel(motion_energy));

                            activity_segs_sec_m = ...
                                build_activity_segments( ...
                                    speed_active, ...
                                    total_time_motion);

                            ax_m1 = subplot( ...
                                nRows, ...
                                nCols, ...
                                (row_counter-1)*nCols + 1);

                            plot( ...
                                ax_m1, ...
                                t_motion, ...
                                motion_energy, ...
                                'LineWidth', ...
                                line_width_trace);

                            box(ax_m1, 'off');
                            grid(ax_m1, 'off');

                            xlim( ...
                                ax_m1, ...
                                [0 total_time_motion]);

                            xlabel(ax_m1, 'Time (s)');
                            ylabel(ax_m1, 'Motion');
                            title(ax_m1, 'Motion energy');

                            plot_activity_bands( ...
                                ax_m1, ...
                                activity_segs_sec_m);

                            ax_m2 = subplot( ...
                                nRows, ...
                                nCols, ...
                                (row_counter-1)*nCols + 2);

                            plot( ...
                                ax_m2, ...
                                t_motion, ...
                                motion_energy, ...
                                'LineWidth', ...
                                line_width_trace);

                            box(ax_m2, 'off');
                            grid(ax_m2, 'off');

                            xlim( ...
                                ax_m2, ...
                                [0 total_time_motion]);

                            xlabel(ax_m2, 'Time (s)');
                            ylabel(ax_m2, 'Motion');
                            title(ax_m2, 'Motion energy');

                            plot_activity_bands( ...
                                ax_m2, ...
                                activity_segs_sec_m);

                        else

                            for c = 1:nCols

                                ax_last = subplot( ...
                                    nRows, ...
                                    nCols, ...
                                    (row_counter-1)*nCols + c);

                                xlabel( ...
                                    ax_last, ...
                                    'Time (s)');
                            end
                        end

                        sgtitle( ...
                            sprintf( ...
                                '%s - %s - Raster summary', ...
                                strrep( ...
                                    current_animal, ...
                                    '_', ...
                                    '\_'), ...
                                strrep( ...
                                    current_age_text, ...
                                    '_', ...
                                    '\_')));

                        saveas( ...
                            fig, ...
                            fig_save_summary);

                        fprintf( ...
                            ['Summary raster plot ' ...
                             'saved in:\n%s\n'], ...
                            fig_save_summary);

                        close(fig);
                        fig = [];
                    end
                end

            catch ME

                fprintf( ...
                    ['\nError for summary raster ' ...
                     'group %d: %s\n'], ...
                    m, ME.message);

                if ~isempty(fig) && ishghandle(fig)
                    close(fig);
                end
            end

        else

            fprintf( ...
                ['Summary root folder skipped: ' ...
                 'nPlanes = %d <= 1.\n'], ...
                nPlanes);
        end

        %==========================================================
        % 4) SUMMARY ANIMAL : TOUS LES RASTERS CONCATÉNÉS
        %==========================================================
        if m == numFolders

            fig = [];

            try
                %--------------------------------------------------
                % Test avant tout appel à get_concat_data
                %--------------------------------------------------
                if exist(fig_save_animal, 'file') == 2

                    fprintf([ ...
                        'Animal concat raster summary already ' ...
                        'exists, all processing skipped:\n%s\n'], ...
                        fig_save_animal);

                else

                    valid_dates = [];

                    %----------------------------------------------
                    % Rechercher les dates uniquement si nécessaire
                    %----------------------------------------------
                    for mm = 1:numFolders

                        [DF_concat_mm, ~, ~] = ...
                            get_concat_data(data, mm);

                        if ~isempty(DF_concat_mm)

                            valid_dates(end+1) = ...
                                mm; %#ok<AGROW>
                        end
                    end

                    if isempty(valid_dates)

                        fprintf( ...
                            ['Animal summary: aucun raster ' ...
                             'concaténé valide.\n']);

                    elseif numel(valid_dates) < 2

                        fprintf( ...
                            ['Animal summary: une seule date ' ...
                             'valide, figure non générée.\n']);

                    else

                        %------------------------------------------
                        % Trier les dates selon l'âge
                        %------------------------------------------
                        ages_valid = nan( ...
                            numel(valid_dates), ...
                            1);

                        for ii = 1:numel(valid_dates)

                            mm = valid_dates(ii);

                            if numel(current_ages) >= mm

                                ages_valid(ii) = ...
                                    extract_age_number( ...
                                        current_ages{mm});
                            end
                        end

                        [~, order_age] = sort( ...
                            ages_valid, ...
                            'ascend', ...
                            'MissingPlacement', ...
                            'last');

                        valid_dates = ...
                            valid_dates(order_age);

                        nRows = numel(valid_dates);

                        fig = figure( ...
                            'Color', 'w');

                        set( ...
                            fig, ...
                            'Position', ...
                            get(0, 'ScreenSize'));

                        for idx = 1:nRows

                            mm = valid_dates(idx);

                            [DF_concat, ...
                             isort_concat, ...
                             ~] = ...
                                get_concat_data(data, mm);

                            if isempty(DF_concat)
                                continue;
                            end

                            if numel(current_sampling_rate) < mm || ...
                                    isempty( ...
                                        current_sampling_rate{mm})

                                continue;
                            end

                            current_sampling_rate_mm = double( ...
                                current_sampling_rate{mm}(1));

                            if ~isfinite(current_sampling_rate_mm) || ...
                                    current_sampling_rate_mm <= 0

                                continue;
                            end

                            [NCell, Nz] = ...
                                size(DF_concat);

                            if NCell == 0 || Nz == 0
                                continue;
                            end

                            isort_concat = ...
                                sanitize_isort( ...
                                    isort_concat, ...
                                    NCell);

                            total_time = ...
                                Nz / current_sampling_rate_mm;

                            t_sec = ...
                                (0:Nz-1) / ...
                                current_sampling_rate_mm;

                            ax = subplot( ...
                                nRows, ...
                                1, ...
                                idx);

                            A = double( ...
                                DF_concat( ...
                                    isort_concat, :));

                            A_z = ...
                                robust_zscore_rows(A);

                            imagesc( ...
                                ax, ...
                                t_sec, ...
                                1:NCell, ...
                                A_z);

                            axis(ax, 'tight');

                            set( ...
                                ax, ...
                                'YDir', 'normal', ...
                                'TickLength', [0 0]);

                            colormap(ax, parula);
                            clim(ax, [0 2]);

                            xlim( ...
                                ax, ...
                                [0 total_time]);

                            ylabel( ...
                                ax, ...
                                sprintf( ...
                                    '%d neurons', ...
                                    NCell));

                            %--------------------------------------
                            % Date
                            %--------------------------------------
                            if numel(current_dates) >= mm && ...
                                    ~isempty(current_dates{mm})
                            
                                date_text = char(string( ...
                                    current_dates{mm}));
                            
                            else
                            
                                date_text = sprintf( ...
                                    'Date_%d', ...
                                    mm);
                            end

                            %--------------------------------------
                            % Âge
                            %--------------------------------------
                            age_text_mm = ...
                                sprintf('Age_%d', mm);

                            if numel(current_ages) >= mm && ...
                                    ~isempty( ...
                                        current_ages{mm})

                                age_text_mm = char(string( ...
                                    current_ages{mm}));
                            end

                            title( ...
                                ax, ...
                                sprintf( ...
                                    '%s - %s', ...
                                    date_text, ...
                                    age_text_mm), ...
                                'Interpreter', ...
                                'none');

                            if idx == nRows

                                xlabel( ...
                                    ax, ...
                                    'Time (s)');
                            end
                        end

                        sgtitle( ...
                            sprintf( ...
                                '%s - all dates concat rasters', ...
                                strrep( ...
                                    current_animal, ...
                                    '_', ...
                                    '\_')));

                        saveas( ...
                            fig, ...
                            fig_save_animal);

                        fprintf( ...
                            ['Animal concat raster summary ' ...
                             'saved in:\n%s\n'], ...
                            fig_save_animal);

                        close(fig);
                        fig = [];
                    end
                end

            catch ME

                fprintf( ...
                    ['\nError for animal concat raster ' ...
                     'summary: %s\n'], ...
                    ME.message);

                if ~isempty(fig) && ishghandle(fig)
                    close(fig);
                end
            end
        end
    end
end

%==========================================================
% HELPERS
%==========================================================

function [DFp, isort_p, MAct_p] = get_plane_data(data, m, p)

    DFp = [];
    isort_p = [];
    MAct_p = [];

    if isfield(data, 'gcamp_plane') && isstruct(data.gcamp_plane)

        if isfield(data.gcamp_plane, 'DF_gcamp_by_plane') && ...
           numel(data.gcamp_plane.DF_gcamp_by_plane) >= m && ...
           ~isempty(data.gcamp_plane.DF_gcamp_by_plane{m}) && ...
           numel(data.gcamp_plane.DF_gcamp_by_plane{m}) >= p
            DFp = data.gcamp_plane.DF_gcamp_by_plane{m}{p};
        end

        if isfield(data.gcamp_plane, 'isort1_gcamp_by_plane') && ...
           numel(data.gcamp_plane.isort1_gcamp_by_plane) >= m && ...
           ~isempty(data.gcamp_plane.isort1_gcamp_by_plane{m}) && ...
           numel(data.gcamp_plane.isort1_gcamp_by_plane{m}) >= p
            isort_p = data.gcamp_plane.isort1_gcamp_by_plane{m}{p};
        end

        if isfield(data.gcamp_plane, 'MAct_gcamp_by_plane') && ...
           numel(data.gcamp_plane.MAct_gcamp_by_plane) >= m && ...
           ~isempty(data.gcamp_plane.MAct_gcamp_by_plane{m}) && ...
           numel(data.gcamp_plane.MAct_gcamp_by_plane{m}) >= p
            MAct_p = data.gcamp_plane.MAct_gcamp_by_plane{m}{p};
        end
    end
end

function [DF_concat, isort_concat, MAct_concat] = get_concat_data(data, m)

    DF_concat = [];
    isort_concat = [];
    MAct_concat = [];

    if isfield(data, 'gcamp_plane') && isstruct(data.gcamp_plane)

        if isfield(data.gcamp_plane, 'DF_gcamp_by_plane') && ...
           numel(data.gcamp_plane.DF_gcamp_by_plane) >= m && ...
           ~isempty(data.gcamp_plane.DF_gcamp_by_plane{m})

            DF_concat = concat_planes(data.gcamp_plane, m, 'DF_gcamp_by_plane');

        elseif isfield(data.gcamp_plane, 'DF_gcamp') && ...
               numel(data.gcamp_plane.DF_gcamp) >= m

            DF_concat = data.gcamp_plane.DF_gcamp{m};
        end

        if ~isempty(DF_concat)
            ops_concat = [];
            
            if isfield(data.gcamp_plane,'ops_suite2p_by_plane') && ...
               numel(data.gcamp_plane.ops_suite2p_by_plane) >= m && ...
               ~isempty(data.gcamp_plane.ops_suite2p_by_plane{m})
            
                ops_concat = data.gcamp_plane.ops_suite2p_by_plane{m}{1};
            end
            if ~isempty(ops_concat)
        
                [isort_concat, ~, ~] = ...
                    compute_sort_outputs_from_df( ...
                        DF_concat, ...
                        ops_concat);        
            end
        end

        if isfield(data.gcamp_plane, 'MAct_gcamp_by_plane') && ...
           numel(data.gcamp_plane.MAct_gcamp_by_plane) >= m && ...
           ~isempty(data.gcamp_plane.MAct_gcamp_by_plane{m})

            MAct_concat = merge_MAct_planes(data.gcamp_plane, m, 'MAct_gcamp_by_plane');

        elseif isfield(data.gcamp_plane, 'MAct_gcamp') && ...
               numel(data.gcamp_plane.MAct_gcamp) >= m

            MAct_concat = data.gcamp_plane.MAct_gcamp{m};
        end
    end
end

function Xcat = concat_planes(branch, m, fieldName)

    Xcat = [];

    if ~isfield(branch, fieldName) || ...
       numel(branch.(fieldName)) < m || ...
       isempty(branch.(fieldName){m})
        return;
    end

    Xcell = branch.(fieldName){m};

    if isempty(Xcell)
        return;
    end

    valid = ~cellfun(@isempty, Xcell);
    Xcell = Xcell(valid);

    if isempty(Xcell)
        return;
    end

    nCols = cellfun(@(x) size(x, 2), Xcell);
    Nz = min(nCols);

    for k = 1:numel(Xcell)
        Xcell{k} = Xcell{k}(:, 1:Nz);
    end

    Xcat = cat(1, Xcell{:});
end

function MAct_sum = merge_MAct_planes(branch, m, fieldName)

    MAct_sum = [];

    if ~isfield(branch, fieldName) || ...
       numel(branch.(fieldName)) < m || ...
       isempty(branch.(fieldName){m})
        return;
    end

    MAct_cell = branch.(fieldName){m};

    if isempty(MAct_cell)
        return;
    end

    valid = ~cellfun(@isempty, MAct_cell);
    MAct_cell = MAct_cell(valid);

    if isempty(MAct_cell)
        return;
    end

    lengths = cellfun(@numel, MAct_cell);
    Nz = min(lengths);

    MAct_sum = zeros(1, Nz);

    for p = 1:numel(MAct_cell)
        M_p = MAct_cell{p};
        M_p = resize_MAct(M_p, Nz);
        MAct_sum = MAct_sum + M_p;
    end
end

function [isort1_out, isort2_out, Sm_out] = compute_sort_outputs_from_df(DF_in, ops_in)
    isort1_out = [];
    isort2_out = [];
    Sm_out     = [];

    if isempty(DF_in)
        return;
    end

    try
        [isort1_out, isort2_out, Sm_out] = ...
            raster_processing(double(DF_in), ops_in);
    catch ME
        warning('compute_sort_outputs_from_df:raster_processing', ...
            'raster_processing failed (%s).', ME.message);
        isort1_out = [];
        isort2_out = [];
        Sm_out     = [];
    end
end

function isort = sanitize_isort(isort, NCell)

    if isempty(isort)
        isort = (1:NCell)';
        return;
    end

    isort = isort(:);
    bad = isort < 1 | isort > NCell | isnan(isort);
    isort(bad) = [];

    if numel(isort) ~= NCell || numel(unique(isort)) ~= numel(isort)
        isort = (1:NCell)';
    end
end

function Z = robust_zscore_rows(A)

    Z = nan(size(A));

    for i = 1:size(A, 1)

        x = A(i, :);
        mu = median(x, 'omitnan');
        sig = 1.4826 * mad(x, 1);

        if isfinite(sig) && sig > eps
            Z(i, :) = (x - mu) / sig;
        else
            Z(i, :) = x - mu;
        end
    end
end

function apply_percentile_clim(ax, A)

    v = A(isfinite(A));

    if isempty(v)
        return;
    end

    lo = prctile(v, 2);
    hi = prctile(v, 98);

    if isfinite(lo) && isfinite(hi) && hi > lo
        clim(ax, [lo hi]);
    end
end

function MAct_out = resize_MAct(MAct_in, Nz)

    if isempty(MAct_in)
        MAct_out = zeros(1, Nz);
        return;
    end

    MAct_in = MAct_in(:)';

    if numel(MAct_in) > Nz
        MAct_out = MAct_in(1:Nz);
    elseif numel(MAct_in) < Nz
        MAct_out = [MAct_in, zeros(1, Nz - numel(MAct_in))];
    else
        MAct_out = MAct_in;
    end
end

function segs_sec = build_activity_segments(speed_active, total_time)

    segs_sec = [];

    if isempty(speed_active)
        return;
    end

    L = numel(speed_active);
    t_speed = linspace(0, total_time, L);

    segs_sec = mask_to_segments_time(t_speed, speed_active > 0);
end

function segs_sec = mask_to_segments_time(t, mask)

    mask = mask(:)';
    t = t(:)';

    if isempty(mask)
        segs_sec = [];
        return;
    end

    d = diff([false, mask, false]);
    starts = find(d == 1);
    ends = find(d == -1) - 1;

    segs_sec = [t(starts(:))', t(ends(:))'];
end

function plot_activity_bands(ax, segs_sec)

    if isempty(segs_sec)
        return;
    end

    yl = ylim(ax);
    hold(ax, 'on');

    for k = 1:size(segs_sec, 1)

        x1 = segs_sec(k, 1);
        x2 = segs_sec(k, 2);

        patch(ax, ...
            [x1 x2 x2 x1], ...
            [yl(1) yl(1) yl(2) yl(2)], ...
            [1 0.8 0.8], ...
            'EdgeColor', 'none', ...
            'FaceAlpha', 0.18);
    end

    ylim(ax, yl);
    hold(ax, 'off');
end

function age_num = extract_age_number(age_value)

    age_num = NaN;

    if isempty(age_value)
        return;
    end

    txt = char(string(age_value));

    token = regexp(txt, '\d+(\.\d+)?', 'match', 'once');

    if ~isempty(token)
        age_num = str2double(token);
    end
end