function build_all_selected_DF_raster_summary( ...
        selected_groups, ...
        automatic_selection, ...
        output_folders, ...
        include_blue_cells)

    %==============================================================%
    % Vérification de selected_groups
    %==============================================================%
    if nargin < 1 || isempty(selected_groups)

        fprintf( ...
            'Global DF summary: selected_groups vide.\n');

        return;
    end

    if ~isstruct(selected_groups)

        error( ...
            'build_all_selected_DF_raster_summary:InvalidSelectedGroups', ...
            'selected_groups doit être une structure.');
    end


    %==============================================================%
    % Vérification de automatic_selection
    %==============================================================%
    if nargin < 2 || isempty(automatic_selection)

        automatic_selection = false;
    end

    automatic_selection = ...
        parse_logical_scalar_DF( ...
            automatic_selection, ...
            false);


    %==============================================================%
    % Seulement en sélection automatique
    %==============================================================%
    if ~automatic_selection

        fprintf( ...
            ['Global DF raster summary: manual selection, ' ...
             'generation skipped.\n']);

        return;
    end


    %==============================================================%
    % Types
    %==============================================================%
    type_names = ...
        fieldnames(selected_groups);

    n_types = ...
        numel(type_names);

    if n_types == 0

        fprintf( ...
            'Global DF summary: aucun type trouvé.\n');

        return;
    end


    %==============================================================%
    % Vérification de output_folders
    %==============================================================%
    if nargin < 3 || isempty(output_folders)

        error( ...
            'build_all_selected_DF_raster_summary:MissingOutputFolders', ...
            ['output_folders doit être fourni. Utiliser ', ...
             'build_output_folders avant cette fonction.']);
    end

    output_folders = ...
        normalize_output_folders_DF( ...
            output_folders, ...
            n_types);


    %==============================================================%
    % Vérification de include_blue_cells
    %==============================================================%
    if nargin < 4 || isempty(include_blue_cells)

        include_blue_cells = false;
    end

    include_blue_cells = ...
        parse_logical_scalar_DF( ...
            include_blue_cells, ...
            false);


    %==============================================================%
    % Une figure par type
    %==============================================================%
    for t = 1:n_types

        current_type = ...
            type_names{t};

        current_animals = ...
            selected_groups.(current_type);

        current_output_folder = ...
            output_folders{t};


        %==========================================================%
        % Création du dossier de sortie
        %==========================================================%
        if exist(current_output_folder, 'dir') ~= 7

            [mkdir_success, mkdir_message] = ...
                mkdir(current_output_folder);

            if ~mkdir_success

                warning( ...
                    'build_all_selected_DF_raster_summary:FolderCreationFailed', ...
                    ['Impossible de créer le dossier pour le type %s :\n', ...
                     '%s\n%s'], ...
                    current_type, ...
                    current_output_folder, ...
                    mkdir_message);

                continue;
            end
        end


        fprintf('\n');
        fprintf('============================================\n');
        fprintf('GLOBAL DF RASTER SUMMARY\n');
        fprintf('Type: %s\n', current_type);
        fprintf('Output folder: %s\n', current_output_folder);
        fprintf( ...
            'Include electroporated cells: %d\n', ...
            include_blue_cells);
        fprintf('============================================\n');


        if isempty(current_animals)

            fprintf( ...
                'Aucun animal pour le type %s.\n', ...
                current_type);

            continue;
        end


        %==========================================================%
        % Vérifier si la figure existe avant tout recalcul
        %==========================================================%
        safe_type = ...
            sanitize_filename_DF(current_type);

        figure_save_path = ...
            fullfile( ...
                current_output_folder, ...
                sprintf( ...
                    '%s_all_animals_all_dates_DF_rasters.png', ...
                    safe_type));

        if exist(figure_save_path, 'file') == 2

            fprintf([ ...
                'Global DF raster summary already exists, ', ...
                'all processing skipped:\n%s\n'], ...
                figure_save_path);

            continue;
        end


        %==========================================================%
        % Collecter les données uniquement si la figure manque
        %==========================================================%
        records = ...
            collect_DF_records( ...
                current_animals, ...
                current_type);

        if isempty(records)

            fprintf( ...
                'Aucun raster DF valide pour le type %s.\n', ...
                current_type);

            continue;
        end


        plot_DF_records( ...
            records, ...
            current_type, ...
            current_output_folder);
    end
end


%==============================================================
% CONVERTIR UNE VALEUR EN LOGIQUE SCALAIRE
%==============================================================
function flag = parse_logical_scalar_DF( ...
        value, default_value)

    if nargin < 2
        default_value = false;
    end

    if isempty(value)

        flag = logical(default_value);
        return;
    end

    if islogical(value)

        flag = value(1);
        return;
    end

    if isnumeric(value)

        flag = value(1) ~= 0;
        return;
    end

    value = ...
        lower( ...
            strtrim( ...
                char(string(value))));

    flag = ...
        ismember( ...
            value, ...
            { ...
                '1', ...
                'true', ...
                'yes', ...
                'oui', ...
                'on' ...
            });
end


%==============================================================
% COLLECTER TOUS LES RASTERS DF
%==============================================================
function records = collect_DF_records( ...
        current_animals, ...
        current_type)

    records = struct( ...
        'type', {}, ...
        'animal', {}, ...
        'animal_index', {}, ...
        'date_index', {}, ...
        'date_name', {}, ...
        'age_text', {}, ...
        'age_number', {}, ...
        'sampling_rate', {}, ...
        'DF', {}, ...
        'isort', {});

    record_counter = 0;


    for k = 1:numel(current_animals)

        animal_struct = ...
            current_animals(k);


        %----------------------------------------------------------%
        % Nom de l'animal courant
        %----------------------------------------------------------%
        animal_name = ...
            sprintf('Animal_%d', k);

        if isfield(animal_struct, 'animal') && ...
                ~isempty(animal_struct.animal)

            animal_name = ...
                char(string(animal_struct.animal));

        elseif isfield(animal_struct, 'animal_group') && ...
                ~isempty(animal_struct.animal_group)

            animal_name = ...
                char(string(animal_struct.animal_group));
        end


        %----------------------------------------------------------%
        % Ligne de l'animal courant
        % Exemple : mtor17_ani1
        %----------------------------------------------------------%
        line_name = '';

        if isfield(animal_struct, 'line') && ...
                ~isempty(animal_struct.line)

            line_name = ...
                char(string(animal_struct.line));
        end


        if ~isempty(line_name)

            animal_display_name = ...
                sprintf( ...
                    '%s_%s', ...
                    line_name, ...
                    animal_name);

        else

            animal_display_name = ...
                animal_name;
        end


        %----------------------------------------------------------%
        % Data
        %----------------------------------------------------------%
        if ~isfield(animal_struct, 'data') || ...
                isempty(animal_struct.data)

            fprintf( ...
                'Animal %s: data vide, skip.\n', ...
                animal_name);

            continue;
        end

        data = ...
            animal_struct.data;


        %----------------------------------------------------------%
        % Variables courantes
        %
        % Même logique que dans visualize_data :
        % current_dates, current_ages, etc.
        %----------------------------------------------------------%
        current_dates = ...
            animal_struct.dates;

        current_ages = ...
            animal_struct.ages;

        current_sampling_rates = ...
            animal_struct.metadata. ...
                gcamp_plane. ...
                SamplingRatePlane;


        %----------------------------------------------------------%
        % Nombre de recordings
        %----------------------------------------------------------%
        num_dates = ...
            determine_number_of_dates_DF( ...
                data, ...
                current_dates, ...
                current_ages, ...
                current_sampling_rates);


        %----------------------------------------------------------%
        % Boucle recordings
        %----------------------------------------------------------%
        for m = 1:num_dates

            sampling_rate = ...
                current_sampling_rates{m};

            date_name = ...
                current_dates{m};

            age_text = ...
                current_ages{m};

            age_number = ...
                extract_age_number_DF( ...
                    age_text);


            [ ...
                DF_concat, ...
                isort_concat ...
            ] = ...
                get_concat_DF_global( ...
                    data, ...
                    m);


            if isempty(DF_concat)
                continue;
            end


            record_counter = ...
                record_counter + 1;


            records(record_counter).type = ...
                current_type;

            records(record_counter).animal = ...
                animal_display_name;

            records(record_counter).animal_index = ...
                k;

            records(record_counter).date_index = ...
                m;

            records(record_counter).date_name = ...
                char(string(date_name));

            records(record_counter).age_text = ...
                char(string(age_text));

            records(record_counter).age_number = ...
                age_number;

            records(record_counter).sampling_rate = ...
                sampling_rate;

            records(record_counter).DF = ...
                DF_concat;

            records(record_counter).isort = ...
                isort_concat;
        end
    end


    if isempty(records)
        return;
    end


    %--------------------------------------------------------------
    % Trier d'abord par âge, puis date, puis animal
    %--------------------------------------------------------------
    animal_values = ...
        string({records.animal})';

    age_values = ...
        [records.age_number]';

    date_values = ...
        string({records.date_name})';

    original_indices = ...
        (1:numel(records))';


    age_values(~isfinite(age_values)) = ...
        inf;


    sorting_table = ...
        table( ...
            animal_values, ...
            age_values, ...
            date_values, ...
            original_indices, ...
            'VariableNames', { ...
                'Animal', ...
                'Age', ...
                'Date', ...
                'OriginalIndex'});


    sorting_table = ...
        sortrows( ...
            sorting_table, ...
            {'Age', 'Date', 'Animal'}, ...
            {'ascend', 'ascend', 'ascend'});


    records = ...
        records( ...
            sorting_table.OriginalIndex);
end


%==============================================================
% PLOT GLOBAL DF
%==============================================================
function plot_DF_records( ...
        records, ...
        current_type, ...
        output_folder)

    nRows = ...
        numel(records);

    if nRows == 0
        return;
    end


    safe_type = ...
        sanitize_filename_DF(current_type);


    figure_save_path = ...
        fullfile( ...
            output_folder, ...
            sprintf( ...
                '%s_all_animals_all_dates_DF_rasters.png', ...
                safe_type));


    if exist(figure_save_path, 'file') == 2

        fprintf( ...
            'Global DF raster summary already exists, skipped:\n%s\n', ...
            figure_save_path);

        return;
    end


    fig = [];


    try

        row_height = ...
            220;

        figure_height = ...
            max( ...
                700, ...
                row_height * nRows);


        fig = ...
            figure( ...
                'Color', 'w', ...
                'Units', 'pixels', ...
                'Position', ...
                [50 50 1800 figure_height]);


        layout = ...
            tiledlayout( ...
                fig, ...
                nRows, ...
                1, ...
                'TileSpacing', ...
                'compact', ...
                'Padding', ...
                'compact');


        for idx = 1:nRows

            current_record = ...
                records(idx);


            DF_concat = ...
                double( ...
                    current_record.DF);


            if isempty(DF_concat)
                continue;
            end


            [NCell, Nz] = ...
                size(DF_concat);


            if NCell == 0 || Nz == 0
                continue;
            end


            isort_concat = ...
                sanitize_isort_DF( ...
                    current_record.isort, ...
                    NCell);


            sampling_rate = ...
                current_record.sampling_rate;


            total_time = ...
                Nz / sampling_rate;


            t_sec = ...
                (0:Nz-1) / sampling_rate;


            A = ...
                DF_concat( ...
                    isort_concat, ...
                    :);


            A_z = ...
                robust_zscore_rows_DF(A);


            ax = ...
                nexttile(layout);


            imagesc( ...
                ax, ...
                t_sec, ...
                1:NCell, ...
                A_z);


            axis( ...
                ax, ...
                'tight');


            set( ...
                ax, ...
                'YDir', ...
                'normal', ...
                'TickLength', ...
                [0 0], ...
                'FontSize', ...
                11);


            colormap( ...
                ax, ...
                parula);


            clim( ...
                ax, ...
                [0 2]);


            xlim( ...
                ax, ...
                [0 total_time]);


            ylabel( ...
                ax, ...
                sprintf( ...
                    '%d neurons', ...
                    NCell));


            title( ...
                ax, ...
                sprintf( ...
                    '%s | %s | %s', ...
                    current_record.animal, ...
                    current_record.date_name, ...
                    current_record.age_text), ...
                'Interpreter', ...
                'none', ...
                'FontSize', ...
                13, ...
                'FontWeight', ...
                'bold');


            if idx == nRows

                xlabel( ...
                    ax, ...
                    'Time (s)', ...
                    'FontSize', ...
                    13);

            else

                set( ...
                    ax, ...
                    'XTickLabel', ...
                    []);
            end
        end


        title( ...
            layout, ...
            sprintf( ...
                '%s - all selected animals and dates - DF rasters', ...
                current_type), ...
            'Interpreter', ...
            'none', ...
            'FontSize', ...
            18, ...
            'FontWeight', ...
            'bold');


        exportgraphics( ...
            fig, ...
            figure_save_path, ...
            'Resolution', ...
            200);


        fprintf( ...
            'Global DF raster summary saved in:\n%s\n', ...
            figure_save_path);


        close(fig);

        fig = [];


    catch ME

        fprintf( ...
            '\nError for global DF raster summary (%s):\n%s\n', ...
            current_type, ...
            ME.message);


        if ~isempty(fig) && ...
                ishghandle(fig)

            close(fig);
        end
    end
end


%==============================================================
% RÉCUPÉRER ET CONCATÉNER LES DF DES PLANS
%==============================================================
function [DF_concat, isort_concat] = ...
        get_concat_DF_global( ...
            data, ...
            m)

    DF_concat = [];
    isort_concat = [];


    if ~isfield(data, 'gcamp_plane') || ...
            ~isstruct(data.gcamp_plane)

        return;
    end


    branch = ...
        data.gcamp_plane;


    if isfield(branch, 'DF_gcamp_by_plane') && ...
            numel(branch.DF_gcamp_by_plane) >= m && ...
            ~isempty(branch.DF_gcamp_by_plane{m})

        DF_concat = ...
            concat_DF_planes( ...
                branch.DF_gcamp_by_plane{m});


    elseif isfield(branch, 'DF_gcamp') && ...
            numel(branch.DF_gcamp) >= m

        DF_concat = ...
            branch.DF_gcamp{m};
    end


    if isempty(DF_concat)
        return;
    end


    ops_concat = [];


    if isfield(branch, 'ops_suite2p_by_plane') && ...
            numel(branch.ops_suite2p_by_plane) >= m && ...
            ~isempty(branch.ops_suite2p_by_plane{m})

        current_ops = ...
            branch.ops_suite2p_by_plane{m};


        if iscell(current_ops) && ...
                ~isempty(current_ops)

            ops_concat = ...
                current_ops{1};

        elseif isstruct(current_ops)

            ops_concat = ...
                current_ops;
        end
    end


    if ~isempty(ops_concat)

        try

            [ ...
                isort_concat, ...
                ~, ...
                ~ ...
            ] = ...
                raster_processing( ...
                    double(DF_concat), ...
                    ops_concat);


        catch ME

            warning( ...
                'GlobalDFSummary:RasterProcessing', ...
                'Raster sorting failed for date %d: %s', ...
                m, ...
                ME.message);


            isort_concat = [];
        end
    end


    isort_concat = ...
        sanitize_isort_DF( ...
            isort_concat, ...
            size(DF_concat, 1));
end


%==============================================================
% CONCATÉNER LES DF DES PLANS
%==============================================================
function DF_concat = ...
        concat_DF_planes( ...
            DF_planes)

    DF_concat = [];


    if isempty(DF_planes)
        return;
    end


    if ~iscell(DF_planes)

        if isnumeric(DF_planes)

            DF_concat = ...
                DF_planes;
        end

        return;
    end


    valid_planes = ...
        ~cellfun( ...
            @isempty, ...
            DF_planes);


    DF_planes = ...
        DF_planes(valid_planes);


    if isempty(DF_planes)
        return;
    end


    valid_numeric = ...
        cellfun( ...
            @(x) ...
                isnumeric(x) && ...
                ismatrix(x), ...
            DF_planes);


    DF_planes = ...
        DF_planes(valid_numeric);


    if isempty(DF_planes)
        return;
    end


    frame_counts = ...
        cellfun( ...
            @(x) ...
                size(x, 2), ...
            DF_planes);


    minimum_frame_count = ...
        min(frame_counts);


    if minimum_frame_count < 1
        return;
    end


    for p = 1:numel(DF_planes)

        DF_planes{p} = ...
            DF_planes{p}( ...
                :, ...
                1:minimum_frame_count);
    end


    DF_concat = ...
        cat( ...
            1, ...
            DF_planes{:});
end


%==============================================================
% NORMALISER LES DOSSIERS DE SORTIE
%==============================================================
function output_folders = ...
        normalize_output_folders_DF( ...
            output_folders, ...
            n_types)

    %----------------------------------------------------------%
    % Convertir l'entrée en cellule colonne
    %----------------------------------------------------------%
    if ischar(output_folders) || ...
            (isstring(output_folders) && ...
             isscalar(output_folders))

        output_folders = ...
            {char(string(output_folders))};


    elseif isstring(output_folders)

        output_folders = ...
            cellstr( ...
                output_folders(:));


    elseif iscell(output_folders)

        output_folders = ...
            output_folders(:);


    else

        error( ...
            'build_all_selected_DF_raster_summary:InvalidOutputFolders', ...
            ['output_folders doit être un chemin texte, un tableau ', ...
             'de chaînes ou une cellule de chemins.']);
    end


    %----------------------------------------------------------%
    % Un même dossier peut être utilisé pour tous les types
    %----------------------------------------------------------%
    if numel(output_folders) == 1 && ...
            n_types > 1

        output_folders = ...
            repmat( ...
                output_folders, ...
                n_types, ...
                1);
    end


    %----------------------------------------------------------%
    % Vérifier le nombre de dossiers
    %----------------------------------------------------------%
    if numel(output_folders) ~= n_types

        error( ...
            'build_all_selected_DF_raster_summary:OutputFolderCountMismatch', ...
            ['Le nombre de dossiers de sortie (%d) doit correspondre ', ...
             'au nombre de types présents dans selected_groups (%d).'], ...
            numel(output_folders), ...
            n_types);
    end


    %----------------------------------------------------------%
    % Nettoyer et valider chaque chemin
    %----------------------------------------------------------%
    for i = 1:n_types

        current_folder = ...
            output_folders{i};


        while iscell(current_folder) && ...
                numel(current_folder) == 1

            current_folder = ...
                current_folder{1};
        end


        if isempty(current_folder)

            error( ...
                'build_all_selected_DF_raster_summary:EmptyOutputFolder', ...
                'Le dossier de sortie du type %d est vide.', ...
                i);
        end


        if ~( ...
                ischar(current_folder) || ...
                ( ...
                    isstring(current_folder) && ...
                    isscalar(current_folder) ...
                ) ...
            )

            error( ...
                'build_all_selected_DF_raster_summary:InvalidOutputFolder', ...
                ['Le dossier de sortie du type %d doit être un chemin ', ...
                 'texte. Type reçu : %s.'], ...
                i, ...
                class(current_folder));
        end


        current_folder = ...
            strtrim( ...
                char(string(current_folder)));


        if isempty(current_folder)

            error( ...
                'build_all_selected_DF_raster_summary:EmptyOutputFolder', ...
                'Le dossier de sortie du type %d est vide.', ...
                i);
        end


        output_folders{i} = ...
            current_folder;
    end
end


%==============================================================
% DÉTERMINER LE NOMBRE DE RECORDINGS
%==============================================================
function num_dates = ...
        determine_number_of_dates_DF( ...
            data, ...
            current_dates, ...
            current_ages, ...
            current_sampling_rates)

    candidates = [];


    if ~isempty(current_dates)

        candidates(end+1) = ...
            numel(current_dates);
    end


    if ~isempty(current_ages)

        candidates(end+1) = ...
            numel(current_ages);
    end


    if ~isempty(current_sampling_rates)

        candidates(end+1) = ...
            numel(current_sampling_rates);
    end


    if isfield(data, 'gcamp_plane') && ...
            isstruct(data.gcamp_plane)

        if isfield( ...
                data.gcamp_plane, ...
                'DF_gcamp_by_plane')

            candidates(end+1) = ...
                numel( ...
                    data.gcamp_plane. ...
                        DF_gcamp_by_plane);
        end


        if isfield( ...
                data.gcamp_plane, ...
                'DF_gcamp')

            candidates(end+1) = ...
                numel( ...
                    data.gcamp_plane. ...
                        DF_gcamp);
        end
    end


    if isempty(candidates)

        num_dates = 0;

    else

        num_dates = ...
            max(candidates);
    end
end


%==============================================================
% EXTRAIRE L'ÂGE NUMÉRIQUE
%==============================================================
function age_number = ...
        extract_age_number_DF( ...
            age_value)

    age_number = NaN;


    if isempty(age_value)
        return;
    end


    age_text = ...
        char(string(age_value));


    token = ...
        regexp( ...
            age_text, ...
            '\d+(\.\d+)?', ...
            'match', ...
            'once');


    if ~isempty(token)

        age_number = ...
            str2double(token);
    end
end


%==============================================================
% SANITIZE ISORT
%==============================================================
function isort = ...
        sanitize_isort_DF( ...
            isort, ...
            NCell)

    if isempty(isort)

        isort = ...
            (1:NCell)';

        return;
    end


    isort = ...
        double( ...
            isort(:));


    invalid_values = ...
        ~isfinite(isort) | ...
        isort < 1 | ...
        isort > NCell;


    isort(invalid_values) = [];


    if numel(isort) ~= NCell || ...
            numel(unique(isort)) ~= NCell

        isort = ...
            (1:NCell)';
    end
end


%==============================================================
% ROBUST Z-SCORE
%==============================================================
function Z = ...
        robust_zscore_rows_DF(A)

    Z = ...
        nan(size(A));


    for i = 1:size(A, 1)

        x = ...
            A(i, :);


        center_value = ...
            median( ...
                x, ...
                'omitnan');


        scale_value = ...
            1.4826 * ...
            mad( ...
                x, ...
                1);


        if isfinite(scale_value) && ...
                scale_value > eps

            Z(i, :) = ...
                (x - center_value) / ...
                scale_value;

        else

            Z(i, :) = ...
                x - center_value;
        end
    end
end


%==============================================================
% SANITIZE NOM DE FICHIER
%==============================================================
function safe_name = ...
        sanitize_filename_DF( ...
            input_name)

    safe_name = ...
        char(string(input_name));


    safe_name = ...
        regexprep( ...
            safe_name, ...
            '[<>:"/\\|?*]', ...
            '_');


    safe_name = ...
        strrep( ...
            safe_name, ...
            ' ', ...
            '_');
end