function create_random_peak_preview( ...
        valid_cells, ...
        DF, ...
        Acttmp2, ...
        thresholds, ...
        electroporated_indices, ...
        sampling_rate, ...
        use_combined_this_plane, ...
        include_electroporated, ...
        gcamp_current_output_folder, ...
        automatic_selection, ...
        current_output_folder, ...
        line, ...
        animal, ...
        date, ...
        age, ...
        plane_number)

%CREATE_PEAK_DETECTION_FIGURES
%
% Crée les figures associées à une nouvelle détection.
%
% 1) RANDOM PEAK PREVIEW
%
%    Toujours créée :
%       - jusqu'à 10 cellules aléatoires
%       - traces noires
%       - pics détectés
%       - seuil de détection
%
% 2) REPRESENTATIVE SINGLE-CELL TRACES
%
%    Créée uniquement si :
%
%       include_electroporated == 1
%
%    ET
%
%       use_combined_this_plane == true
%
% Sauvegarde :
%
%   - toujours dans gcamp_current_output_folder
%
%   - si automatic_selection :
%
%       current_output_folder/
%           Development|Adult/
%               line/
%                   animal/
%                       date/
%                           planeX/
%
% Nomenclature :
%
%   line_animal_date_age_planeX_random_peak_preview.png
%
%   line_animal_date_age_planeX_...
%       representative_single_cell_traces.png


    % =============================================================
    % Defaults
    % =============================================================

    if nargin < 4 || isempty(thresholds)
        thresholds = [];
    end

    if nargin < 5 || isempty(electroporated_indices)
        electroporated_indices = [];
    end

    if nargin < 6
        sampling_rate = [];
    end

    if nargin < 7 || isempty(use_combined_this_plane)
        use_combined_this_plane = false;
    end

    if nargin < 8 || isempty(include_electroporated)
        include_electroporated = 0;
    end

    if nargin < 9 || isempty(gcamp_current_output_folder)
        gcamp_current_output_folder = '';
    end

    if nargin < 10 || isempty(automatic_selection)
        automatic_selection = 0;
    end

    if nargin < 11 || isempty(current_output_folder)
        current_output_folder = '';
    end

    if nargin < 12 || isempty(line)
        line = '';
    end

    if nargin < 13 || isempty(animal)
        animal = '';
    end

    if nargin < 14 || isempty(date)
        date = '';
    end

    if nargin < 15 || isempty(age)
        age = '';
    end

    if nargin < 16
        plane_number = [];
    end


    % =============================================================
    % Normalize options
    % =============================================================

    if ischar(include_electroporated) || ...
            isstring(include_electroporated)

        include_electroporated = ...
            str2double( ...
                char(string(include_electroporated)));
    end

    if isempty(include_electroporated) || ...
            ~isnumeric(include_electroporated) || ...
            ~isfinite(include_electroporated(1))

        include_electroporated = 0;

    else

        include_electroporated = ...
            double(include_electroporated(1));
    end


    automatic_selection = ...
        logical(automatic_selection(1));

    use_combined_this_plane = ...
        logical(use_combined_this_plane(1));


    % =============================================================
    % Vérification données
    % =============================================================

    if isempty(valid_cells) || ...
            isempty(DF)

        warning( ...
            'No valid peak-detection data available for figures.');

        return;
    end


    [nCells, nFrames] = ...
        size(DF);


    if nCells == 0 || ...
            nFrames == 0

        warning( ...
            'DF is empty, peak-detection figures skipped.');

        return;
    end


    valid_cells = ...
        round(double(valid_cells(:)));


    if numel(valid_cells) ~= nCells

        warning( ...
            ['valid_cells and DF have incompatible sizes: ' ...
             '%d versus %d cells.'], ...
            numel(valid_cells), ...
            nCells);

        return;
    end


    % =============================================================
    % Paths
    % =============================================================

    gcamp_current_output_folder = ...
        normalize_peak_figure_text( ...
            gcamp_current_output_folder);

    current_output_folder = ...
        normalize_peak_figure_text( ...
            current_output_folder);


    % =============================================================
    % Filename components
    % =============================================================

    line = ...
        sanitize_peak_figure_filename( ...
            line);

    animal = ...
        sanitize_peak_figure_filename( ...
            animal);

    date = ...
        sanitize_peak_figure_filename( ...
            date);

    age = ...
        sanitize_peak_figure_filename( ...
            age);


    % =============================================================
    % Plane
    % =============================================================

    plane_name = '';

    if ~isempty(plane_number)

        if isnumeric(plane_number)

            plane_number = ...
                double(plane_number(1));

            if isfinite(plane_number)

                plane_name = ...
                    sprintf( ...
                        'plane%d', ...
                        round(plane_number));
            end

        else

            plane_name = ...
                sanitize_peak_figure_filename( ...
                    plane_number);

            if ~isempty(plane_name) && ...
                    ~startsWith( ...
                        lower(plane_name), ...
                        'plane')

                plane_name = ...
                    [ ...
                        'plane', ...
                        plane_name ...
                    ];
            end
        end
    end


    name_parts = { ...
        line, ...
        animal, ...
        date, ...
        age, ...
        plane_name};


    name_parts = ...
        name_parts( ...
            ~cellfun( ...
                @isempty, ...
                name_parts));


    % =============================================================
    % Local output folder
    % =============================================================

    if ~isempty(gcamp_current_output_folder) && ...
            exist(gcamp_current_output_folder, 'dir') ~= 7

        mkdir(gcamp_current_output_folder);
    end


    % =============================================================
    % Summary folder
    %
    % Seulement si automatic_selection.
    %
    % current_output_folder/
    %   Development|Adult/
    %     line/
    %       animal/
    %         date/
    % =============================================================
    
    summary_folder = '';
    summary_recording_folder = '';
    
    if automatic_selection && ...
            ~isempty(current_output_folder)
    
        current_age_value = ...
            str2double( ...
                regexprep( ...
                    char(string(age)), ...
                    '[^\d\.]', ...
                    ''));
    
        if isfinite(current_age_value) && ...
                current_age_value <= 15
    
            summary_folder = ...
                fullfile( ...
                    current_output_folder, ...
                    'Development');
    
        else
    
            summary_folder = ...
                fullfile( ...
                    current_output_folder, ...
                    'Adult');
        end
    
        if exist(summary_folder, 'dir') ~= 7
            mkdir(summary_folder);
        end
    
        summary_recording_folder = ...
            fullfile( ...
                summary_folder, ...
                char(string(line)), ...
                char(string(animal)), ...
                char(string(date)));
    
        if exist(summary_recording_folder, 'dir') ~= 7
            mkdir(summary_recording_folder);
        end
    end


    % =============================================================
    %
    % 1) RANDOM PEAK PREVIEW
    %
    % =============================================================

    if isempty(name_parts)

        preview_base_name = ...
            'random_peak_preview';

    else

        preview_base_name = ...
            [ ...
                strjoin( ...
                    name_parts, ...
                    '_'), ...
                '_random_peak_preview' ...
            ];
    end


    % =============================================================
    % Preview paths
    % =============================================================

    preview_local_path = '';

    if ~isempty(gcamp_current_output_folder)

        preview_local_path = ...
            fullfile( ...
                gcamp_current_output_folder, ...
                [preview_base_name '.png']);
    end


    preview_summary_path = '';

    if ~isempty(summary_recording_folder)

        preview_summary_path = ...
            fullfile( ...
                summary_recording_folder, ...
                [preview_base_name '.png']);
    end


    % =============================================================
    % Preview existing files
    % =============================================================

    preview_local_exists = ...
        ~isempty(preview_local_path) && ...
        exist(preview_local_path, 'file') == 2;


    preview_summary_exists = ...
        ~isempty(preview_summary_path) && ...
        exist(preview_summary_path, 'file') == 2;


    preview_local_needed = ...
        ~isempty(preview_local_path) && ...
        ~preview_local_exists;


    preview_summary_needed = ...
        ~isempty(preview_summary_path) && ...
        ~preview_summary_exists;


    % =============================================================
    % Create preview if needed
    % =============================================================

    if preview_local_needed || ...
            preview_summary_needed

        nShow = ...
            min( ...
                10, ...
                nCells);


        rng('shuffle');


        idx_show = ...
            randperm( ...
                nCells, ...
                nShow);


        figPreview = ...
            figure( ...
                'Name', preview_base_name, ...
                'NumberTitle', 'off', ...
                'Color', 'w', ...
                'Position', [150 80 1200 900], ...
                'Visible', 'off');


        nColumns = 2;

        nRows = ...
            ceil( ...
                nShow / ...
                nColumns);


        layout = ...
            tiledlayout( ...
                figPreview, ...
                nRows, ...
                nColumns, ...
                'TileSpacing', 'compact', ...
                'Padding', 'compact');


        % =========================================================
        % Preview cells
        % =========================================================

        for k = 1:nShow

            ii = ...
                idx_show(k);


            cid_orig = ...
                valid_cells(ii);


            x = ...
                DF(ii,:);


            frames = ...
                1:nFrames;


            ax = ...
                nexttile(layout);


            hold(ax, 'on');

            box(ax, 'off');


            set( ...
                ax, ...
                'LineWidth', 0.8, ...
                'TickDir', 'out');


            % -----------------------------------------------------
            % Trace
            % -----------------------------------------------------

            plot( ...
                ax, ...
                frames, ...
                x, ...
                'k-', ...
                'LineWidth', 1);


            % -----------------------------------------------------
            % Peaks
            % -----------------------------------------------------

            pk = ...
                get_peak_figure_indices( ...
                    Acttmp2, ...
                    ii, ...
                    nFrames);


            if ~isempty(pk)

                plot( ...
                    ax, ...
                    pk, ...
                    x(pk), ...
                    '*', ...
                    'Color', [0.85 0.1 0.1], ...
                    'MarkerSize', 3.5, ...
                    'LineWidth', 0.7);
            end


            % -----------------------------------------------------
            % Threshold
            % -----------------------------------------------------

            current_threshold = ...
                get_peak_figure_threshold( ...
                    thresholds, ...
                    ii);


            if isfinite(current_threshold)

                yline( ...
                    ax, ...
                    current_threshold, ...
                    '--', ...
                    'LineWidth', 1);
            end


            % -----------------------------------------------------
            % Labels
            % -----------------------------------------------------

            title( ...
                ax, ...
                sprintf( ...
                    'Cell %g | final %d | n=%d peaks', ...
                    cid_orig, ...
                    ii, ...
                    numel(pk)), ...
                'FontWeight', 'bold', ...
                'Interpreter', 'none');


            xlabel( ...
                ax, ...
                'Frames');


            ylabel( ...
                ax, ...
                '\DeltaF/F');


            xlim( ...
                ax, ...
                [ ...
                    1, ...
                    max(1,nFrames) ...
                ]);


            hold(ax, 'off');
        end


        % =========================================================
        % Save preview locally
        % =========================================================

        if preview_local_needed

            save_peak_figure( ...
                figPreview, ...
                preview_local_path);


            fprintf( ...
                'Random peak preview saved:\n%s\n', ...
                preview_local_path);
        end


        % =========================================================
        % Save preview summary
        % =========================================================

        if preview_summary_needed

            same_destination = ...
                ~isempty(preview_local_path) && ...
                strcmpi( ...
                    char(preview_local_path), ...
                    char(preview_summary_path));


            if ~same_destination

                save_peak_figure( ...
                    figPreview, ...
                    preview_summary_path);


                fprintf( ...
                    'Random peak preview summary saved:\n%s\n', ...
                    preview_summary_path);
            end
        end


        if isgraphics(figPreview)

            close(figPreview);
        end
    end


    % =============================================================
    % STOP HERE IF ELECTROPORATED IS NOT INCLUDED
    % =============================================================

    if include_electroporated ~= 1
        return;
    end


    % =============================================================
    % Combined required for representative traces
    % =============================================================

    if ~use_combined_this_plane
        return;
    end


    % =============================================================
    %
    % 2) REPRESENTATIVE SINGLE-CELL TRACES
    %
    % =============================================================

    if isempty(sampling_rate) || ...
            ~isscalar(sampling_rate) || ...
            ~isfinite(sampling_rate) || ...
            sampling_rate <= 0

        warning( ...
            ['Representative single-cell traces skipped: ' ...
             'invalid sampling rate.']);

        return;
    end


    % =============================================================
    % Remap electroporated cells into final DF indices
    % =============================================================

    electroporated_idx = [];


    if ~isempty(electroporated_indices)

        electroporated_indices = ...
            round( ...
                double( ...
                    electroporated_indices(:)));


        electroporated_indices = ...
            electroporated_indices( ...
                isfinite( ...
                    electroporated_indices));


        [tf, loc] = ...
            ismember( ...
                electroporated_indices, ...
                valid_cells);


        electroporated_idx = ...
            unique( ...
                loc(tf));


        electroporated_idx = ...
            electroporated_idx( ...
                electroporated_idx >= 1 & ...
                electroporated_idx <= nCells);
    end


    % =============================================================
    % No electroporated cell available
    % =============================================================

    if isempty(electroporated_idx)

        fprintf( ...
            ['Representative single-cell traces skipped: ' ...
             'no valid electroporated cell.\n']);

        return;
    end


    % =============================================================
    % Non-electroporated GCaMP cells
    % =============================================================

    all_idx = ...
        (1:nCells)';


    gcamp_idx = ...
        setdiff( ...
            all_idx, ...
            electroporated_idx);


    if isempty(gcamp_idx)

        fprintf( ...
            ['Representative single-cell traces skipped: ' ...
             'no valid non-electroporated GCaMP cell.\n']);

        return;
    end


    % =============================================================
    % Random representative cells
    % =============================================================

    n_example = 3;


    n_gcamp_show = ...
        min( ...
            n_example, ...
            numel(gcamp_idx));


    n_electroporated_show = ...
        min( ...
            n_example, ...
            numel(electroporated_idx));


    rng('shuffle');


    gcamp_examples = ...
        gcamp_idx( ...
            randperm( ...
                numel(gcamp_idx), ...
                n_gcamp_show));


    electroporated_examples = ...
        electroporated_idx( ...
            randperm( ...
                numel(electroporated_idx), ...
                n_electroporated_show));


    % =============================================================
    % Representative filename
    % =============================================================

    if isempty(name_parts)

        representative_base_name = ...
            'representative_single_cell_traces';

    else

        representative_base_name = ...
            [ ...
                strjoin( ...
                    name_parts, ...
                    '_'), ...
                '_representative_single_cell_traces' ...
            ];
    end


    % =============================================================
    % Representative paths
    % =============================================================

    representative_local_path = '';

    if ~isempty(gcamp_current_output_folder)

        representative_local_path = ...
            fullfile( ...
                gcamp_current_output_folder, ...
                [ ...
                    representative_base_name, ...
                    '.png' ...
                ]);
    end


    representative_summary_path = '';

    if ~isempty(summary_recording_folder)

        representative_summary_path = ...
            fullfile( ...
                summary_recording_folder, ...
                [ ...
                    representative_base_name, ...
                    '.png' ...
                ]);
    end


    % =============================================================
    % Existing representative files
    % =============================================================

    representative_local_exists = ...
        ~isempty(representative_local_path) && ...
        exist( ...
            representative_local_path, ...
            'file') == 2;


    representative_summary_exists = ...
        ~isempty(representative_summary_path) && ...
        exist( ...
            representative_summary_path, ...
            'file') == 2;


    representative_local_needed = ...
        ~isempty(representative_local_path) && ...
        ~representative_local_exists;


    representative_summary_needed = ...
        ~isempty(representative_summary_path) && ...
        ~representative_summary_exists;


    if ~representative_local_needed && ...
            ~representative_summary_needed

        return;
    end


    % =============================================================
    % Figure
    % =============================================================

    figRep = ...
        figure( ...
            'Color', 'w', ...
            'Units', 'normalized', ...
            'Position', [0 0 1 1], ...
            'Visible', 'off');


    ax = ...
        axes(figRep);


    hold(ax, 'on');


    % =============================================================
    % Time
    % =============================================================

    t_plot = ...
        (0:nFrames - 1) / ...
        sampling_rate;


    % =============================================================
    % Trace offsets
    % =============================================================

    offset = 0;

    offset_step = 3.5;


    max_trace_y = ...
        -Inf;

    min_trace_y = ...
        Inf;


    % =============================================================
    % GCaMP traces
    % =============================================================

    for j = 1:numel(gcamp_examples)

        cell_idx = ...
            gcamp_examples(j);


        [ ...
            max_trace_y, ...
            min_trace_y ...
        ] = ...
            plot_peak_representative_trace( ...
                ax, ...
                DF, ...
                Acttmp2, ...
                valid_cells, ...
                cell_idx, ...
                t_plot, ...
                offset, ...
                [0 0.6 0], ...
                max_trace_y, ...
                min_trace_y);


        offset = ...
            offset + ...
            offset_step;
    end


    % =============================================================
    % Electroporated traces
    % =============================================================

    for j = 1:numel(electroporated_examples)

        cell_idx = ...
            electroporated_examples(j);


        [ ...
            max_trace_y, ...
            min_trace_y ...
        ] = ...
            plot_peak_representative_trace( ...
                ax, ...
                DF, ...
                Acttmp2, ...
                valid_cells, ...
                cell_idx, ...
                t_plot, ...
                offset, ...
                [0 0.35 1], ...
                max_trace_y, ...
                min_trace_y);


        offset = ...
            offset + ...
            offset_step;
    end


    % =============================================================
    % Formatting
    % =============================================================

    box( ...
        ax, ...
        'off');


    grid( ...
        ax, ...
        'off');


    xlabel( ...
        ax, ...
        'Time (s)', ...
        'FontSize', 42, ...
        'FontWeight', 'bold');


    ylabel( ...
        ax, ...
        '\DeltaF/F + offset', ...
        'FontSize', 42, ...
        'FontWeight', 'bold');


    title( ...
        ax, ...
        'Representative single-cell calcium traces', ...
        'FontSize', 42, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'none');


    set( ...
        ax, ...
        'FontSize', 36, ...
        'TickLength', [0 0], ...
        'YTick', []);


    xlim( ...
        ax, ...
        [ ...
            t_plot(1), ...
            t_plot(end) ...
        ]);


    % =============================================================
    % Scale bars
    % =============================================================

    bar_time = 60;

    bar_amp = 1;


    recording_duration = ...
        t_plot(end) - ...
        t_plot(1);


    if recording_duration < bar_time

        bar_time = ...
            max( ...
                1, ...
                round( ...
                    recording_duration / 5));
    end


    y0 = ...
        max_trace_y + ...
        0.8;


    ylim( ...
        ax, ...
        [ ...
            min_trace_y - 0.5, ...
            y0 + bar_amp + 0.8 ...
        ]);


    xl = ...
        xlim(ax);


    x0 = ...
        xl(2) - ...
        bar_time - ...
        0.03 * range(xl);


    % -------------------------------------------------------------
    % Horizontal time bar
    % -------------------------------------------------------------

    plot( ...
        ax, ...
        [ ...
            x0, ...
            x0 + bar_time ...
        ], ...
        [ ...
            y0, ...
            y0 ...
        ], ...
        'k', ...
        'LineWidth', 6);


    % -------------------------------------------------------------
    % Vertical amplitude bar
    % -------------------------------------------------------------

    plot( ...
        ax, ...
        [ ...
            x0, ...
            x0 ...
        ], ...
        [ ...
            y0, ...
            y0 + bar_amp ...
        ], ...
        'k', ...
        'LineWidth', 6);


    % -------------------------------------------------------------
    % Time text
    % -------------------------------------------------------------

    text( ...
        ax, ...
        x0 + bar_time / 2, ...
        y0 - 0.18, ...
        sprintf( ...
            '%g s', ...
            bar_time), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontSize', 34, ...
        'FontWeight', 'bold');


    % -------------------------------------------------------------
    % Amplitude text
    % -------------------------------------------------------------

    text( ...
        ax, ...
        x0 - 0.01 * range(xl), ...
        y0 + bar_amp / 2, ...
        '1 \DeltaF/F', ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'middle', ...
        'FontSize', 34, ...
        'FontWeight', 'bold');


    hold( ...
        ax, ...
        'off');


    % =============================================================
    % Save representative locally
    % =============================================================

    if representative_local_needed

        save_peak_figure( ...
            figRep, ...
            representative_local_path);


        fprintf( ...
            'Representative traces saved:\n%s\n', ...
            representative_local_path);
    end


    % =============================================================
    % Save representative summary
    % =============================================================

    if representative_summary_needed

        same_destination = ...
            ~isempty(representative_local_path) && ...
            strcmpi( ...
                char(representative_local_path), ...
                char(representative_summary_path));


        if ~same_destination

            save_peak_figure( ...
                figRep, ...
                representative_summary_path);


            fprintf( ...
                'Representative traces summary saved:\n%s\n', ...
                representative_summary_path);
        end
    end


    % =============================================================
    % Close
    % =============================================================

    if isgraphics(figRep)

        close(figRep);
    end
end


% ========================================================================
function [max_trace_y, min_trace_y] = ...
        plot_peak_representative_trace( ...
            ax, ...
            DF, ...
            Acttmp2, ...
            valid_cells, ...
            cell_idx, ...
            t_plot, ...
            offset, ...
            trace_color, ...
            max_trace_y, ...
            min_trace_y)

    trace = ...
        DF(cell_idx,:);


    trace = ...
        trace - ...
        median( ...
            trace, ...
            'omitnan');


    y_trace = ...
        trace + ...
        offset;


    % =============================================================
    % Trace
    % =============================================================

    plot( ...
        ax, ...
        t_plot, ...
        y_trace, ...
        'Color', trace_color, ...
        'LineWidth', 3);


    % =============================================================
    % Peaks
    % =============================================================

    pk = ...
        get_peak_figure_indices( ...
            Acttmp2, ...
            cell_idx, ...
            numel(t_plot));


    if ~isempty(pk)

        plot( ...
            ax, ...
            t_plot(pk), ...
            y_trace(pk), ...
            '*', ...
            'Color', [0.85 0.1 0.1], ...
            'MarkerSize', 8, ...
            'LineWidth', 1.2);
    end


    % =============================================================
    % Original cell ID
    % =============================================================

    text( ...
        ax, ...
        t_plot(1), ...
        offset + 0.15, ...
        sprintf( ...
            'Cell %g', ...
            valid_cells(cell_idx)), ...
        'FontSize', 22, ...
        'FontWeight', 'bold', ...
        'Color', trace_color, ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', ...
        'Interpreter', 'none');


    % =============================================================
    % Limits
    % =============================================================

    current_max = ...
        max( ...
            y_trace, ...
            [], ...
            'omitnan');


    current_min = ...
        min( ...
            y_trace, ...
            [], ...
            'omitnan');


    if isfinite(current_max)

        max_trace_y = ...
            max( ...
                max_trace_y, ...
                current_max);
    end


    if isfinite(current_min)

        min_trace_y = ...
            min( ...
                min_trace_y, ...
                current_min);
    end
end


% ========================================================================
function pk = get_peak_figure_indices( ...
        Acttmp2, ...
        cell_index, ...
        nFrames)

    pk = [];


    if ~iscell(Acttmp2) || ...
            numel(Acttmp2) < cell_index || ...
            isempty(Acttmp2{cell_index})

        return;
    end


    pk = ...
        round( ...
            double( ...
                Acttmp2{cell_index}(:)'));


    pk = ...
        pk( ...
            isfinite(pk) & ...
            pk >= 1 & ...
            pk <= nFrames);


    pk = ...
        unique(pk);
end


% ========================================================================
function current_threshold = get_peak_figure_threshold( ...
        thresholds, ...
        cell_index)

    current_threshold = NaN;


    if isempty(thresholds)
        return;
    end


    if iscell(thresholds)

        if numel(thresholds) < cell_index || ...
                isempty(thresholds{cell_index})

            return;
        end


        value = ...
            thresholds{cell_index};

    else

        if numel(thresholds) < cell_index
            return;
        end


        value = ...
            thresholds(cell_index);
    end


    if isnumeric(value) && ...
            isscalar(value) && ...
            isfinite(value)

        current_threshold = ...
            double(value);
    end
end


% ========================================================================
function save_peak_figure( ...
        fig_handle, ...
        file_path)

    try

        exportgraphics( ...
            fig_handle, ...
            file_path, ...
            'Resolution', 300);

    catch ME_export

        try

            saveas( ...
                fig_handle, ...
                file_path);

        catch ME_saveas

            warning( ...
                ['Unable to save figure:\n%s\n' ...
                 'exportgraphics: %s\n' ...
                 'saveas: %s'], ...
                file_path, ...
                ME_export.message, ...
                ME_saveas.message);
        end
    end
end


% ========================================================================
function value = normalize_peak_figure_text(value)

    if isempty(value)

        value = '';

        return;
    end


    if isstring(value)

        value = ...
            char(value(1));

    elseif iscell(value)

        value = ...
            value{1};


        if isstring(value)

            value = ...
                char(value);
        end
    end


    if isnumeric(value)

        value = ...
            num2str(value);
    end


    if ~ischar(value)

        value = ...
            char(string(value));
    end


    value = ...
        strtrim(value);
end


% ========================================================================
function value = sanitize_peak_figure_filename(value)

    value = ...
        normalize_peak_figure_text( ...
            value);


    if isempty(value)
        return;
    end


    value = ...
        regexprep( ...
            value, ...
            '[<>:"/\\|?*]', ...
            '-');


    value = ...
        regexprep( ...
            value, ...
            '\s+', ...
            '_');


    value = ...
        regexprep( ...
            value, ...
            '_+', ...
            '_');


    value = ...
        regexprep( ...
            value, ...
            '^[_\-.]+|[_\-.]+$', ...
            '');
end