function figHandle = make_all_metrics_figures_by_age( ...
        grouped, ...
        ages, ...
        save_folder, ...
        current_type, ...
        global_maxima, ...
        normalization_label, ...
        types_filename_prefix)

%MAKE_ALL_METRICS_FIGURES_BY_AGE
%
% Une seule figure par type.
% Un radar par âge.
% Maximum 3 radars par ligne.


    %==============================================================%
    % Métriques
    %==============================================================%
    metric_names = { ...
        'Activity', ...
        'Pairwise correlation', ...
        'SCE frequency', ...
        'SCE recruitment', ...
        'Burstiness' ...
    };
    
    
    metric_values = { ...
        grouped.FrequencyPerCell_gcamp, ...
        grouped.pairwise_corr_gcamp_gcamp, ...
        grouped.SCEsFrequency, ...
        grouped.SCEsCellParticipation_percent, ...
        grouped.BurstFraction_gcamp ...
    };

    nMetrics = ...
        numel(metric_names);


    %==============================================================%
    % Ordonner les âges
    %==============================================================%
    [ages, age_order] = ...
        sort( ...
            ages(:)', ...
            'ascend');


    nAges = ...
        numel(ages);


    if nAges == 0

        figHandle = [];
        return;
    end


    %==============================================================%
    % Nombre de recordings
    %==============================================================%
    if isfield( ...
            grouped, ...
            'NRecordings') && ...
            numel(grouped.NRecordings) >= ...
            max(age_order)

        n_recordings = ...
            grouped.NRecordings(age_order);

    else

        n_recordings = ...
            zeros(nAges, 1);
    end


    %==============================================================%
    % Médianes par âge
    %==============================================================%
    median_values = ...
        nan( ...
            nAges, ...
            nMetrics);


    for m = 1:nMetrics

        vals_by_age = ...
            metric_values{m};


        for a = 1:nAges

            original_idx = ...
                age_order(a);


            if original_idx > ...
                    numel(vals_by_age)

                continue;
            end


            vals = ...
                clean_numeric( ...
                    vals_by_age{original_idx});


            if isempty(vals)
                continue;
            end


            median_values(a,m) = ...
                median( ...
                    vals, ...
                    'omitnan');
        end
    end


    %==============================================================%
    % Normalisation par maximum
    %==============================================================%
    normalized_values = ...
        nan( ...
            size(median_values));


    for m = 1:nMetrics

        x = ...
            median_values(:,m);


        valid = ...
            isfinite(x);


        if ~any(valid)
            continue;
        end


        if ~isempty(global_maxima) && ...
                m <= numel(global_maxima) && ...
                isfinite(global_maxima(m))

            xmax = ...
                global_maxima(m);

        else

            xmax = ...
                max(x(valid));
        end


        if xmax > 0

            normalized_values(valid,m) = ...
                x(valid) ./ xmax;

        else

            normalized_values(valid,m) = ...
                0;
        end
    end


    %==============================================================%
    % Layout
    %==============================================================%
    max_cols = ...
        3;


    nCols = ...
        min( ...
            nAges, ...
            max_cols);


    nRows = ...
        ceil( ...
            nAges / max_cols);


    subplot_width = ...
        500;

    subplot_height = ...
        500;


    figure_width = ...
        max( ...
            1000, ...
            subplot_width * nCols);


    figure_height = ...
        max( ...
            650, ...
            subplot_height * nRows);


    figHandle = ...
        figure( ...
            'Color', 'w', ...
            'Name', ...
            sprintf( ...
                '%s_basic_metrics_spider', ...
                current_type), ...
            'Position', ...
            [ ...
                50, ...
                50, ...
                figure_width, ...
                figure_height ...
            ]);


    tl = ...
        tiledlayout( ...
            figHandle, ...
            nRows, ...
            nCols, ...
            'TileSpacing', 'compact', ...
            'Padding', 'compact');


    title( ...
        tl, ...
        { ...
            sprintf( ...
                '%s - Basic metrics', ...
                current_type), ...
            normalization_label ...
        }, ...
        'Interpreter', 'none', ...
        'FontSize', 16, ...
        'FontWeight', 'bold');


    %==============================================================%
    % Radar
    %==============================================================%
    age_colors = ...
        lines( ...
            max(nAges, 1));


    theta = ...
        pi/2 - ...
        (0:nMetrics-1) .* ...
        (2*pi/nMetrics);


    grid_levels = ...
        [ ...
            0.25, ...
            0.50, ...
            0.75, ...
            1.00 ...
        ];


    %==============================================================%
    % Un radar par âge
    %==============================================================%
    for a = 1:nAges

        ax = ...
            nexttile( ...
                tl, ...
                a);


        hold( ...
            ax, ...
            'on');


        axis( ...
            ax, ...
            'equal');

        axis( ...
            ax, ...
            'off');


        values_a = ...
            normalized_values(a,:);


        %==========================================================%
        % Grille
        %==========================================================%
        for r = grid_levels

            x_grid = ...
                r .* cos(theta);

            y_grid = ...
                r .* sin(theta);


            x_grid(end + 1) = ...
                x_grid(1);

            y_grid(end + 1) = ...
                y_grid(1);


            plot( ...
                ax, ...
                x_grid, ...
                y_grid, ...
                '-', ...
                'Color', ...
                [0.82 0.82 0.82], ...
                'LineWidth', ...
                0.8, ...
                'HandleVisibility', ...
                'off');
        end


        %==========================================================%
        % Axes
        %==========================================================%
        for m = 1:nMetrics

            plot( ...
                ax, ...
                [0 cos(theta(m))], ...
                [0 sin(theta(m))], ...
                '-', ...
                'Color', ...
                [0.78 0.78 0.78], ...
                'LineWidth', ...
                0.8, ...
                'HandleVisibility', ...
                'off');
        end


        %==========================================================%
        % Labels grille
        %==========================================================%
        label_theta = ...
            theta(1);


        for r = grid_levels

            text( ...
                ax, ...
                r*cos(label_theta) + 0.025, ...
                r*sin(label_theta), ...
                sprintf( ...
                    '%.2g', ...
                    r), ...
                'FontSize', 7, ...
                'Color', ...
                [0.45 0.45 0.45], ...
                'HorizontalAlignment', ...
                'left', ...
                'VerticalAlignment', ...
                'middle');
        end


        %==========================================================%
        % Noms métriques
        %==========================================================%
        label_radius = ...
            1.17;


        for m = 1:nMetrics

            x_txt = ...
                label_radius * ...
                cos(theta(m));


            y_txt = ...
                label_radius * ...
                sin(theta(m));


            ctheta = ...
                cos(theta(m));


            if ctheta > 0.20

                hAlign = ...
                    'left';

            elseif ctheta < -0.20

                hAlign = ...
                    'right';

            else

                hAlign = ...
                    'center';
            end


            stheta = ...
                sin(theta(m));


            if stheta > 0.35

                vAlign = ...
                    'bottom';

            elseif stheta < -0.35

                vAlign = ...
                    'top';

            else

                vAlign = ...
                    'middle';
            end


            text( ...
                ax, ...
                x_txt, ...
                y_txt, ...
                metric_names{m}, ...
                'Interpreter', 'none', ...
                'FontSize', 8, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', hAlign, ...
                'VerticalAlignment', vAlign);
        end


        %==========================================================%
        % Valeurs
        %==========================================================%
        missing_idx = ...
            find( ...
                ~isfinite(values_a));


        if isempty(missing_idx)

            x = ...
                values_a .* ...
                cos(theta);


            y = ...
                values_a .* ...
                sin(theta);


            x_closed = ...
                [ ...
                    x, ...
                    x(1) ...
                ];


            y_closed = ...
                [ ...
                    y, ...
                    y(1) ...
                ];


            c = ...
                age_colors(a,:);


            patch( ...
                ax, ...
                x_closed, ...
                y_closed, ...
                c, ...
                'FaceAlpha', 0.12, ...
                'EdgeColor', 'none', ...
                'HandleVisibility', 'off');


            plot( ...
                ax, ...
                x_closed, ...
                y_closed, ...
                '-o', ...
                'Color', c, ...
                'LineWidth', 2.2, ...
                'MarkerSize', 5, ...
                'MarkerFaceColor', c, ...
                'MarkerEdgeColor', c);

        else

            fprintf( ...
                ['Type %s | age P%d: ' ...
                 'missing metric(s): %s\n'], ...
                current_type, ...
                ages(a), ...
                strjoin( ...
                    metric_names(missing_idx), ...
                    ', '));


            text( ...
                ax, ...
                0, ...
                0, ...
                'Missing data', ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'middle', ...
                'FontSize', 10, ...
                'FontWeight', 'bold', ...
                'Color', ...
                [0.5 0.5 0.5]);
        end


        xlim( ...
            ax, ...
            [-1.38 1.38]);


        ylim( ...
            ax, ...
            [-1.28 1.38]);


        %==========================================================%
        % Titre âge
        %==========================================================%
        if a <= numel(n_recordings)

            nRec = ...
                n_recordings(a);

        else

            nRec = ...
                0;
        end


        if nRec == 1

            title_txt = ...
                sprintf( ...
                    'P%d - 1 recording', ...
                    ages(a));

        else

            title_txt = ...
                sprintf( ...
                    'P%d - %d recordings', ...
                    ages(a), ...
                    nRec);
        end


        title( ...
            ax, ...
            title_txt, ...
            'Interpreter', 'none', ...
            'FontWeight', 'bold', ...
            'FontSize', 13);
    end


    %==============================================================%
    % Nom fichier
    %==============================================================%
    if contains( ...
            types_filename_prefix, ...
            '_')

        output_name = ...
            sprintf( ...
                '%s_%s_basic_metrics_spider_all_ages.png', ...
                types_filename_prefix, ...
                current_type);

    else

        output_name = ...
            sprintf( ...
                '%s_basic_metrics_spider_all_ages.png', ...
                current_type);
    end


    %==============================================================%
    % Agrandir avant sauvegarde
    %==============================================================%
    set( ...
        figHandle, ...
        'WindowState', ...
        'maximized');


    drawnow;


    %==============================================================%
    % Sauvegarde
    %==============================================================%
    save_figure_png( ...
        figHandle, ...
        save_folder, ...
        output_name);


    %==============================================================%
    % Fermeture
    %==============================================================%
    if isgraphics(figHandle)

        close(figHandle);
    end
end


function x = clean_numeric(x)

    if isempty(x) || ...
            ~(isnumeric(x) || islogical(x))

        x = [];
        return;
    end


    x = ...
        double(x(:));


    x = ...
        x( ...
            isfinite(x));
end


function save_figure_png( ...
        figHandle, ...
        save_folder, ...
        filename)

    if isempty(figHandle) || ...
            ~ishghandle(figHandle)

        return;
    end


    if exist( ...
            save_folder, ...
            'dir') ~= 7

        mkdir(save_folder);
    end


    output_path = ...
        fullfile( ...
            save_folder, ...
            filename);


    drawnow;


    try

        exportgraphics( ...
            figHandle, ...
            output_path, ...
            'Resolution', ...
            300);

    catch

        saveas( ...
            figHandle, ...
            output_path);
    end


    fprintf( ...
        'Figure saved: %s\n', ...
        output_path);
end