function plot_recording_metrics_summary( ...
        results_analysis, ...
        current_automatic_selection, ...
        current_output_folder, ...
        gcamp_root_folders, ...
        current_line, ...
        current_animal, ...
        current_dates, ...
        current_ages)
%PLOT_RECORDING_METRICS_SUMMARY
%
% Crée une figure de synthèse par recording avec :
%
%   1) GCaMP frequency
%   2) GCaMP-GCaMP pairwise correlation
%   3) Burst fraction
%   4) SCE frequency
%   5) SCE cell participation
%   6) Burst rate
%
% Les métriques calculées par plan sont concaténées pour la
% visualisation du recording :
%
%   FrequencyPerCell{m}{p}
%   BurstFraction{m}{p}
%   BurstRate_per_min{m}{p}
%
% Pour les corrélations :
%   - chaque matrice de plan est traitée séparément ;
%   - la diagonale est supprimée ;
%   - seul le triangle supérieur est conservé ;
%   - les valeurs des plans sont ensuite concaténées.
%
% Les SCEs sont déjà calculées sur les plans concaténés et sont donc
% utilisées directement au niveau du recording.
%
% Sauvegarde :
%
%   Toujours :
%       gcamp_root_folders{m}
%
%   Si current_automatic_selection ~= 0 :
%       current_output_folder
%
% Aucun dossier n'est créé.
%
% Nomenclature :
%
%   line_animal_date_age_recN_GCaMP_recording_metrics_summary.png
%
% Si current_line est vide :
%
%   animal_date_age_recN_GCaMP_recording_metrics_summary.png


    %==============================================================%
    % Vérifications
    %==============================================================%
    if isempty(results_analysis) || ...
            ~isstruct(results_analysis)

        return;
    end


    %==============================================================%
    % Copie dans output global ?
    %==============================================================%
    save_in_current_output = ...
        current_automatic_selection ~= 0;


    if save_in_current_output

        if isempty(current_output_folder) || ...
                exist( ...
                    current_output_folder, ...
                    'dir') ~= 7

            warning( ...
                ['Recording metrics summary: current_output_folder ' ...
                 'missing or invalid. Global copies will be skipped.']);


            save_in_current_output = ...
                false;
        end
    end


    %==============================================================%
    % Nombre de recordings
    %==============================================================%
    nRec = ...
        max( ...
            [ ...
                numel(gcamp_root_folders), ...
                numel(current_dates), ...
                numel(current_ages) ...
            ]);


    %==============================================================%
    % Recordings
    %==============================================================%
    for m = 1:nRec

        fig = [];


        try

            %======================================================%
            % Dossier GCaMP du recording
            %======================================================%
            if m > numel(gcamp_root_folders) || ...
                    isempty(gcamp_root_folders{m})

                warning( ...
                    ['Rec %d: GCaMP root folder missing, ' ...
                     'recording skipped.'], ...
                    m);

                continue;
            end


            current_gcamp_root = ...
                gcamp_root_folders{m};


            %------------------------------------------------------%
            % Déballage éventuel d'une cellule singleton
            %------------------------------------------------------%
            while iscell(current_gcamp_root) && ...
                    numel(current_gcamp_root) == 1

                current_gcamp_root = ...
                    current_gcamp_root{1};
            end


            if isempty(current_gcamp_root) || ...
                    iscell(current_gcamp_root) || ...
                    exist( ...
                        current_gcamp_root, ...
                        'dir') ~= 7

                warning( ...
                    ['Rec %d: GCaMP root folder invalid or missing, ' ...
                     'recording skipped.'], ...
                    m);

                continue;
            end


            %======================================================%
            % Date
            %======================================================%
            if m <= numel(current_dates)

                current_date = ...
                    get_date_label( ...
                        current_dates, ...
                        m);

            else

                current_date = ...
                    '';
            end


            %======================================================%
            % Age
            %======================================================%
            if m <= numel(current_ages)

                current_age = ...
                    get_age_label( ...
                        current_ages, ...
                        m);

            else

                current_age = ...
                    '';
            end


            %======================================================%
            % FREQUENCY
            %======================================================%
            frequency_by_plane = ...
                get_results_analysis_value( ...
                    results_analysis, ...
                    { ...
                        'gcamp_plane', ...
                        'activity', ...
                        'FrequencyPerCell' ...
                    }, ...
                    m);


            frequency_all = ...
                concatenate_numeric_planes( ...
                    frequency_by_plane);


            %======================================================%
            % BURST FRACTION
            %======================================================%
            burst_fraction_by_plane = ...
                get_results_analysis_value( ...
                    results_analysis, ...
                    { ...
                        'gcamp_plane', ...
                        'activity', ...
                        'BurstFraction' ...
                    }, ...
                    m);


            burst_fraction_all = ...
                concatenate_numeric_planes( ...
                    burst_fraction_by_plane);


            %======================================================%
            % BURST RATE
            %======================================================%
            burst_rate_by_plane = ...
                get_results_analysis_value( ...
                    results_analysis, ...
                    { ...
                        'gcamp_plane', ...
                        'activity', ...
                        'BurstRate_per_min' ...
                    }, ...
                    m);


            burst_rate_all = ...
                concatenate_numeric_planes( ...
                    burst_rate_by_plane);


            %======================================================%
            % PAIRWISE CORRELATIONS
            %
            % Ne jamais concaténer les matrices avant extraction.
            % Chaque plan est traité séparément.
            %======================================================%
            corr_by_plane = ...
                get_results_analysis_value( ...
                    results_analysis, ...
                    { ...
                        'gcamp_plane', ...
                        'correlations', ...
                        'cross_corr_gcamp_gcamp_by_plane' ...
                    }, ...
                    m);


            corr_all = ...
                concatenate_unique_pairwise_correlations( ...
                    corr_by_plane);


            %======================================================%
            % SCE FREQUENCY
            %
            % Déjà calculée sur les plans concaténés.
            %======================================================%
            sce_frequency = ...
                get_results_analysis_value( ...
                    results_analysis, ...
                    { ...
                        'gcamp_plane', ...
                        'SCEs', ...
                        'Frequency' ...
                    }, ...
                    m);


            sce_frequency = ...
                force_numeric_vector( ...
                    sce_frequency);


            %======================================================%
            % SCE PARTICIPATION
            %
            % Déjà calculée sur les plans concaténés.
            %======================================================%
            sce_participation = ...
                get_results_analysis_value( ...
                    results_analysis, ...
                    { ...
                        'gcamp_plane', ...
                        'SCEs', ...
                        'CellParticipation_percent' ...
                    }, ...
                    m);


            sce_participation = ...
                force_numeric_vector( ...
                    sce_participation);


            %======================================================%
            % Au moins une donnée ?
            %======================================================%
            if isempty(frequency_all) && ...
                    isempty(corr_all) && ...
                    isempty(burst_fraction_all) && ...
                    isempty(burst_rate_all) && ...
                    isempty(sce_frequency) && ...
                    isempty(sce_participation)

                fprintf( ...
                    'Rec %d: no summary metrics, skip.\n', ...
                    m);

                continue;
            end


            %======================================================%
            % Filename
            %======================================================%
            filename_title = ...
                'GCaMP_recording_metrics_summary';


            if isempty(current_line)

                filename = ...
                    sprintf( ...
                        '%s_%s_%s_rec%d_%s.png', ...
                        current_animal, ...
                        current_date, ...
                        current_age, ...
                        m, ...
                        filename_title);

            else

                filename = ...
                    sprintf( ...
                        '%s_%s_%s_%s_rec%d_%s.png', ...
                        current_line, ...
                        current_animal, ...
                        current_date, ...
                        current_age, ...
                        m, ...
                        filename_title);
            end


            %======================================================%
            % Chemin GCaMP
            %======================================================%
            save_path_gcamp = ...
                fullfile( ...
                    current_gcamp_root, ...
                    filename);


            exists_gcamp = ...
                exist( ...
                    save_path_gcamp, ...
                    'file') == 2;


            %======================================================%
            % Chemin output global
            %======================================================%
            save_path_output = '';


            exists_output = ...
                true;


            if save_in_current_output

                save_path_output = ...
                    fullfile( ...
                        current_output_folder, ...
                        filename);


                exists_output = ...
                    exist( ...
                        save_path_output, ...
                        'file') == 2;
            end


            %======================================================%
            % Toutes les copies nécessaires existent
            %======================================================%
            if exists_gcamp && ...
                    exists_output

                fprintf( ...
                    'Rec %d: recording summary already exists, skip.\n', ...
                    m);

                continue;
            end


            %======================================================%
            % Figure
            %======================================================%
            figure_title = ...
                sprintf( ...
                    '%s - %s - %s - recording %d', ...
                    current_animal, ...
                    current_date, ...
                    current_age, ...
                    m);


            fig = ...
                figure( ...
                    'Color', ...
                    'w', ...
                    'Units', ...
                    'normalized', ...
                    'Position', ...
                    [0.03 0.05 0.94 0.88], ...
                    'Name', ...
                    figure_title);


            tl = ...
                tiledlayout( ...
                    fig, ...
                    2, ...
                    3, ...
                    'TileSpacing', ...
                    'compact', ...
                    'Padding', ...
                    'compact');


            title( ...
                tl, ...
                sprintf( ...
                    'GCaMP recording metrics summary - %s - %s - %s', ...
                    current_animal, ...
                    current_date, ...
                    current_age), ...
                'Interpreter', ...
                'none', ...
                'FontWeight', ...
                'bold', ...
                'FontSize', ...
                18);


            %======================================================%
            % 1) GCaMP frequency
            %======================================================%
            ax1 = ...
                nexttile(tl);


            plot_distribution_panel( ...
                ax1, ...
                frequency_all, ...
                'GCaMP frequency', ...
                'Frequency (events / min)', ...
                50);


            %======================================================%
            % 2) Pairwise correlation
            %======================================================%
            ax2 = ...
                nexttile(tl);


            plot_distribution_panel( ...
                ax2, ...
                corr_all, ...
                'GCaMP-GCaMP pairwise correlation', ...
                'Correlation', ...
                50);


            if ~isempty(corr_all)

                xlim( ...
                    ax2, ...
                    [-1 1]);


                xline( ...
                    ax2, ...
                    0, ...
                    '--k');
            end


            %======================================================%
            % 3) Burst fraction
            %======================================================%
            ax3 = ...
                nexttile(tl);


            plot_distribution_panel( ...
                ax3, ...
                burst_fraction_all, ...
                'Burst fraction', ...
                'Fraction of events in bursts', ...
                40);


            if ~isempty(burst_fraction_all)

                xlim( ...
                    ax3, ...
                    [0 1]);
            end


            %======================================================%
            % 4) SCE frequency
            %======================================================%
            ax4 = ...
                nexttile(tl);


            plot_single_value_panel( ...
                ax4, ...
                sce_frequency, ...
                'SCE frequency', ...
                'SCEs / min');


            %======================================================%
            % 5) SCE participation
            %======================================================%
            ax5 = ...
                nexttile(tl);


            plot_distribution_panel( ...
                ax5, ...
                sce_participation, ...
                'SCE cell participation', ...
                'Cell participation (%)', ...
                40);


            if ~isempty(sce_participation)

                xlim( ...
                    ax5, ...
                    [0 100]);
            end


            %======================================================%
            % 6) Burst rate
            %======================================================%
            ax6 = ...
                nexttile(tl);


            plot_distribution_panel( ...
                ax6, ...
                burst_rate_all, ...
                'Burst rate', ...
                'Bursts / min', ...
                40);


            %======================================================%
            % Maximiser
            %======================================================%
            set( ...
                fig, ...
                'WindowState', ...
                'maximized');


            drawnow;


            %======================================================%
            % Sauvegarde GCaMP
            % Toujours
            %======================================================%
            if ~exists_gcamp

                exportgraphics( ...
                    fig, ...
                    save_path_gcamp, ...
                    'Resolution', ...
                    300);


                fprintf( ...
                    'Recording summary saved: %s\n', ...
                    save_path_gcamp);
            end


            %======================================================%
            % Copie output global
            % Seulement si automatic_selection ~= 0
            %======================================================%
            if save_in_current_output && ...
                    ~exists_output

                exportgraphics( ...
                    fig, ...
                    save_path_output, ...
                    'Resolution', ...
                    300);


                fprintf( ...
                    'Recording summary saved: %s\n', ...
                    save_path_output);
            end


            %======================================================%
            % Fermeture
            %======================================================%
            if ~isempty(fig) && ...
                    isgraphics(fig)

                close(fig);
            end


        catch ME

            fprintf( ...
                'Recording summary error | rec %d: %s\n', ...
                m, ...
                ME.message);


            if ~isempty(fig) && ...
                    isgraphics(fig)

                close(fig);
            end
        end
    end
end


%=========================================================================%
% DISTRIBUTION PANEL
%=========================================================================%
function plot_distribution_panel( ...
        ax, ...
        values, ...
        panel_title, ...
        xlabel_text, ...
        nBins)

    values = ...
        force_numeric_vector( ...
            values);


    if isempty(values)

        empty_summary_axis( ...
            ax, ...
            panel_title);

        return;
    end


    histogram( ...
        ax, ...
        values, ...
        nBins);


    median_value = ...
        median( ...
            values, ...
            'omitnan');


    xline( ...
        ax, ...
        median_value, ...
        '--k', ...
        'LineWidth', ...
        1.5);


    xlabel( ...
        ax, ...
        xlabel_text);


    ylabel( ...
        ax, ...
        'Count');


    title( ...
        ax, ...
        panel_title, ...
        'Interpreter', ...
        'none');


    text( ...
        ax, ...
        0.97, ...
        0.95, ...
        sprintf( ...
            'median = %.3g\nn = %d', ...
            median_value, ...
            numel(values)), ...
        'Units', ...
        'normalized', ...
        'HorizontalAlignment', ...
        'right', ...
        'VerticalAlignment', ...
        'top');


    grid( ...
        ax, ...
        'on');


    box( ...
        ax, ...
        'off');
end


%=========================================================================%
% SINGLE VALUE PANEL
%=========================================================================%
function plot_single_value_panel( ...
        ax, ...
        values, ...
        panel_title, ...
        ylabel_text)

    values = ...
        force_numeric_vector( ...
            values);


    if isempty(values)

        empty_summary_axis( ...
            ax, ...
            panel_title);

        return;
    end


    value = ...
        median( ...
            values, ...
            'omitnan');


    bar( ...
        ax, ...
        1, ...
        value, ...
        0.45);


    xlim( ...
        ax, ...
        [0.5 1.5]);


    xticks( ...
        ax, ...
        []);


    ylabel( ...
        ax, ...
        ylabel_text);


    title( ...
        ax, ...
        panel_title, ...
        'Interpreter', ...
        'none');


    text( ...
        ax, ...
        1, ...
        value, ...
        sprintf( ...
            '  %.3g', ...
            value), ...
        'HorizontalAlignment', ...
        'left', ...
        'VerticalAlignment', ...
        'bottom', ...
        'FontWeight', ...
        'bold');


    grid( ...
        ax, ...
        'on');


    box( ...
        ax, ...
        'off');
end


%=========================================================================%
% CONCATENATE PLAN METRICS
%=========================================================================%
function values = concatenate_numeric_planes( ...
        values_by_plane)

    values = [];


    if isempty(values_by_plane)
        return;
    end


    if ~iscell(values_by_plane)

        values_by_plane = ...
            {values_by_plane};
    end


    for p = 1:numel(values_by_plane)

        current_values = ...
            force_numeric_vector( ...
                values_by_plane{p});


        if isempty(current_values)
            continue;
        end


        values = ...
            [ ...
                values; ...
                current_values(:) ...
            ]; %#ok<AGROW>
    end


    values = ...
        values(isfinite(values));
end


%=========================================================================%
% CONCATENATE UNIQUE PAIRWISE CORRELATIONS
%=========================================================================%
function values = ...
    concatenate_unique_pairwise_correlations( ...
        corr_by_plane)

    values = [];


    if isempty(corr_by_plane)
        return;
    end


    if ~iscell(corr_by_plane)

        corr_by_plane = ...
            {corr_by_plane};
    end


    for p = 1:numel(corr_by_plane)

        C = ...
            corr_by_plane{p};


        if isempty(C) || ...
                ~isnumeric(C)

            continue;
        end


        C = ...
            double(C);


        %==========================================================%
        % Matrice carrée de corrélation
        %==========================================================%
        if ismatrix(C) && ...
                size(C, 1) > 1 && ...
                size(C, 1) == size(C, 2)

            keep = ...
                triu( ...
                    true(size(C)), ...
                    1);


            current_values = ...
                C(keep);

        else

            current_values = ...
                C(:);
        end


        current_values = ...
            current_values( ...
                isfinite(current_values));


        values = ...
            [ ...
                values; ...
                current_values(:) ...
            ]; %#ok<AGROW>
    end
end


%=========================================================================%
% GET RESULTS_ANALYSIS VALUE
%=========================================================================%
function val = get_results_analysis_value( ...
        results_analysis, ...
        path_fields, ...
        idx)

    val = [];


    if isempty(results_analysis) || ...
            ~isstruct(results_analysis)

        return;
    end


    current = ...
        results_analysis;


    for i = 1:numel(path_fields)

        field_name = ...
            path_fields{i};


        if ~isstruct(current) || ...
                ~isfield(current, field_name)

            return;
        end


        current = ...
            current.(field_name);
    end


    if iscell(current)

        if numel(current) >= idx

            val = ...
                current{idx};
        end

    else

        val = ...
            current;
    end
end


%=========================================================================%
% FORCE NUMERIC VECTOR
%=========================================================================%
function v = force_numeric_vector(x)

    if isempty(x)

        v = [];
        return;
    end


    if iscell(x)

        combined = [];


        for i = 1:numel(x)

            current = ...
                force_numeric_vector( ...
                    x{i});


            if ~isempty(current)

                combined = ...
                    [ ...
                        combined; ...
                        current(:) ...
                    ]; %#ok<AGROW>
            end
        end


        v = ...
            combined;

        return;
    end


    if ~(isnumeric(x) || ...
            islogical(x))

        v = [];
        return;
    end


    v = ...
        double( ...
            x(:));


    v = ...
        v( ...
            isfinite(v));
end


%=========================================================================%
% EMPTY AXIS
%=========================================================================%
function empty_summary_axis( ...
        ax, ...
        panel_title)

    title( ...
        ax, ...
        panel_title, ...
        'Interpreter', ...
        'none');


    text( ...
        ax, ...
        0.5, ...
        0.5, ...
        'No data', ...
        'HorizontalAlignment', ...
        'center');


    xticks( ...
        ax, ...
        []);


    yticks( ...
        ax, ...
        []);


    box( ...
        ax, ...
        'off');
end


%=========================================================================%
% AGE
%=========================================================================%
function age_label = get_age_label( ...
        ages, ...
        m)

    if iscell(ages)

        age_value = ...
            ages{m};

    else

        age_value = ...
            ages(m);
    end


    if isnumeric(age_value) || ...
            islogical(age_value)

        age_label = ...
            sprintf( ...
                'P%d', ...
                round( ...
                    double(age_value)));

    else

        age_txt = ...
            age_value;


        token = ...
            regexp( ...
                age_txt, ...
                '\d+', ...
                'match', ...
                'once');


        if isempty(token)

            age_label = ...
                age_txt;

        else

            age_label = ...
                ['P' token];
        end
    end
end


%=========================================================================%
% DATE
%=========================================================================%
function date_label = get_date_label( ...
        dates, ...
        m)

    if iscell(dates)

        date_value = ...
            dates{m};

    else

        date_value = ...
            dates(m);
    end


    if isdatetime(date_value)

        date_label = ...
            datestr( ...
                date_value, ...
                'yyyy-mm-dd');

    else

        date_label = ...
            date_value;
    end
end