function plot_representative_traces_by_burst_rate( ...
        animal_struct, ...
        current_type, ...
        gcamp_output_folders, ...
        include_blue_cells)
%PLOT_REPRESENTATIVE_TRACES_BY_BURST_RATE
%
% Sélectionne des cellules représentatives selon leur burst rate :
%
%   - burst rate minimum
%   - burst rate médian
%   - burst rate maximum
%
% La sélection est réalisée globalement parmi tous les recordings
% et tous les plans de l'animal.
%
% Populations :
%   - GCaMP : toujours
%   - mTOR  : uniquement si include_blue_cells == true
%
% Sauvegarde :
%   current_gcamp_output_folder


    %==============================================================%
    % Vérifications
    %==============================================================%
    if nargin < 4 || ...
            isempty(include_blue_cells)

        include_blue_cells = ...
            false;
    end


    if isempty(animal_struct) || ...
            ~isstruct(animal_struct)

        return;
    end


    if ~isfield(animal_struct, 'data') || ...
            isempty(animal_struct.data)

        fprintf( ...
            'Representative burst traces skipped: no data.\n');

        return;
    end


    if ~isfield(animal_struct, 'results_analysis') || ...
            isempty(animal_struct.results_analysis) || ...
            ~isstruct(animal_struct.results_analysis)

        fprintf( ...
            'Representative burst traces skipped: no results_analysis.\n');

        return;
    end


    if ~isfield(animal_struct, 'metadata') || ...
            isempty(animal_struct.metadata) || ...
            ~isstruct(animal_struct.metadata) || ...
            ~isfield( ...
                animal_struct.metadata, ...
                'SamplingRatePlane')

        fprintf( ...
            'Representative burst traces skipped: SamplingRatePlane missing.\n');

        return;
    end

    %==============================================================%
    % Données communes
    %==============================================================%
    data = ...
        animal_struct.data;


    results_analysis = ...
        animal_struct.results_analysis;


    sampling_rate_group = ...
        animal_struct.metadata.SamplingRatePlane;


    current_line = ...
        animal_struct.line;


    current_animal = ...
        animal_struct.animal;


    %==============================================================%
    % GCaMP
    %==============================================================%
    plot_one_burst_branch( ...
        data, ...
        results_analysis, ...
        sampling_rate_group, ...
        'gcamp_plane', ...
        'DF_gcamp_by_plane', ...
        'GCaMP', ...
        current_type, ...
        gcamp_output_folders, ...
        current_line, ...
        current_animal);


    %==============================================================%
    % mTOR
    %==============================================================%
    if include_blue_cells

        plot_one_burst_branch( ...
            data, ...
            results_analysis, ...
            sampling_rate_group, ...
            'blue_plane', ...
            'DF_blue_by_plane', ...
            'mTOR', ...
            current_type, ...
            gcamp_output_folders, ...
            current_line, ...
            current_animal);
    end
end


%==================================================================%
% Une population : GCaMP ou mTOR
%==================================================================%
function plot_one_burst_branch( ...
        data, ...
        results_analysis, ...
        sampling_rate_group, ...
        branch_name, ...
        df_field, ...
        label_name, ...
        current_type, ...
        gcamp_output_folders, ...
        current_line, ...
        current_animal)

    all_burst = [];
    all_traces = {};
    all_time = {};
    all_labels = {};


    %==============================================================%
    % Vérifier traces
    %==============================================================%
    if ~isfield(data, branch_name) || ...
            ~isstruct(data.(branch_name)) || ...
            ~isfield(data.(branch_name), df_field) || ...
            isempty(data.(branch_name).(df_field))

        fprintf( ...
            '%s skipped: traces missing.\n', ...
            label_name);

        return;
    end


    DF_all = ...
        data.(branch_name).(df_field);


    %==============================================================%
    % Burst rates
    %==============================================================%
    if ~isfield(results_analysis, branch_name) || ...
            ~isstruct(results_analysis.(branch_name)) || ...
            ~isfield( ...
                results_analysis.(branch_name), ...
                'activity') || ...
            ~isstruct( ...
                results_analysis.(branch_name).activity) || ...
            ~isfield( ...
                results_analysis.(branch_name).activity, ...
                'BurstRate_per_min')

        fprintf( ...
            '%s skipped: %s.activity.BurstRate_per_min missing.\n', ...
            label_name, ...
            branch_name);

        return;
    end


    burst_all = ...
        results_analysis. ...
        (branch_name). ...
        activity. ...
        BurstRate_per_min;


    %==============================================================%
    % Sampling rate doit être organisé par recording
    %==============================================================%
    if ~iscell(sampling_rate_group)

        fprintf( ...
            '%s skipped: SamplingRatePlane must be a cell array by recording.\n', ...
            label_name);

        return;
    end


    %==============================================================%
    % Nombre de recordings
    %==============================================================%
    nRec = ...
        min( ...
            [ ...
                numel(DF_all), ...
                numel(burst_all), ...
                numel(sampling_rate_group) ...
            ]);


    if nRec == 0
        return;
    end


    %==============================================================%
    % Recordings
    %==============================================================%
    for m = 1:nRec
        
        %==========================================================%
        % Output du recording
        %==========================================================%
        current_gcamp_output_folder = '';


        if m <= numel(gcamp_output_folders) && ...
                ~isempty(gcamp_output_folders{m})

            current_gcamp_output_folder = ...
                char(string( ...
                    gcamp_output_folders{m}));


            if exist( ...
                    current_gcamp_output_folder, ...
                    'dir') ~= 7

                mkdir( ...
                    current_gcamp_output_folder);
            end
        end

        %==========================================================%
        % Sampling rate
        %==========================================================%
        sampling_rate = ...
            sampling_rate_group{m};


        % Petit déballage uniquement si nécessaire
        while iscell(sampling_rate) && ...
                numel(sampling_rate) == 1

            sampling_rate = ...
                sampling_rate{1};
        end


        if isempty(sampling_rate) || ...
                ~isnumeric(sampling_rate)

            fprintf( ...
                '%s rec %d skipped: invalid SamplingRatePlane.\n', ...
                label_name, ...
                m);

            continue;
        end


        sampling_rate = ...
            double( ...
                sampling_rate(1));


        if ~isfinite(sampling_rate) || ...
                sampling_rate <= 0

            fprintf( ...
                '%s rec %d skipped: invalid SamplingRatePlane.\n', ...
                label_name, ...
                m);

            continue;
        end


        %==========================================================%
        % Traces du recording
        %==========================================================%
        if isempty(DF_all{m})
            continue;
        end


        DF_planes = ...
            DF_all{m};


        if ~iscell(DF_planes)

            DF_planes = ...
                {DF_planes};
        end


        %==========================================================%
        % Burst rates du recording
        %==========================================================%
        if iscell(burst_all)

            if m > numel(burst_all) || ...
                    isempty(burst_all{m})

                continue;
            end


            burst_planes = ...
                burst_all{m};

        else

            if m ~= 1
                continue;
            end


            burst_planes = ...
                burst_all;
        end


        if ~iscell(burst_planes)

            burst_planes = ...
                {burst_planes};
        end


        %==========================================================%
        % Plans
        %==========================================================%
        nPlanes = ...
            min( ...
                numel(DF_planes), ...
                numel(burst_planes));


        for p = 1:nPlanes

            DF = ...
                DF_planes{p};


            burst_rate = ...
                unwrap_numeric( ...
                    burst_planes{p});


            if isempty(DF) || ...
                    isempty(burst_rate)

                continue;
            end


            if ~isnumeric(DF) || ...
                    ~isnumeric(burst_rate)

                fprintf( ...
                    '%s rec %d plane %d skipped: non-numeric data.\n', ...
                    label_name, ...
                    m, ...
                    p - 1);

                continue;
            end


            DF = ...
                double(DF);


            burst_rate = ...
                double( ...
                    burst_rate(:));


            %======================================================%
            % Harmoniser nombre de cellules
            %======================================================%
            n_cells = ...
                min( ...
                    size(DF, 1), ...
                    numel(burst_rate));


            if n_cells < 1
                continue;
            end


            DF = ...
                DF(1:n_cells, :);


            burst_rate = ...
                burst_rate(1:n_cells);


            valid_cells = ...
                find( ...
                    isfinite(burst_rate));


            %======================================================%
            % Collecter les cellules
            %======================================================%
            for ii = 1:numel(valid_cells)

                c = ...
                    valid_cells(ii);


                trace_c = ...
                    DF(c, :);


                if isempty(trace_c) || ...
                        all(~isfinite(trace_c))

                    continue;
                end


                %--------------------------------------------------%
                % Recentrer la trace
                %--------------------------------------------------%
                trace_c = ...
                    trace_c - ...
                    median( ...
                        trace_c, ...
                        'omitnan');


                %--------------------------------------------------%
                % Temps
                %--------------------------------------------------%
                n_frames = ...
                    numel(trace_c);


                time_c = ...
                    (0:n_frames - 1) ./ ...
                    sampling_rate;


                %--------------------------------------------------%
                % Stockage
                %--------------------------------------------------%
                all_burst(end + 1, 1) = ...
                    burst_rate(c); %#ok<AGROW>


                all_traces{end + 1, 1} = ...
                    trace_c; %#ok<AGROW>


                all_time{end + 1, 1} = ...
                    time_c; %#ok<AGROW>


                all_labels{end + 1, 1} = ...
                    sprintf( ...
                        'rec %d | plane %d | cell %d', ...
                        m, ...
                        p - 1, ...
                        c); %#ok<AGROW>
            end
        end
    end


    %==============================================================%
    % Minimum de 3 cellules
    %==============================================================%
    if numel(all_burst) < 3

        fprintf( ...
            '%s skipped: fewer than 3 valid cells globally.\n', ...
            label_name);

        return;
    end


    %==============================================================%
    % Trier selon burst rate
    %==============================================================%
    [~, idx_sort] = ...
        sort( ...
            all_burst, ...
            'ascend');


    idx_min = ...
        idx_sort(1);


    idx_median = ...
        idx_sort( ...
            round( ...
                (numel(idx_sort) + 1) / 2));


    idx_max = ...
        idx_sort(end);


    selected_idx = ...
        [ ...
            idx_min, ...
            idx_median, ...
            idx_max ...
        ];


    selected_names = ...
        { ...
            'Minimum', ...
            'Median', ...
            'Maximum' ...
        };


    %==============================================================%
    % Traces sélectionnées
    %==============================================================%
    selected_traces = ...
        cell(3, 1);


    selected_time = ...
        cell(3, 1);


    selected_labels = ...
        cell(3, 1);


    for i = 1:3

        idx = ...
            selected_idx(i);


        selected_traces{i} = ...
            all_traces{idx};


        selected_time{i} = ...
            all_time{idx};


        selected_labels{i} = ...
            sprintf( ...
                '%s | %.2f bursts/min | %s', ...
                selected_names{i}, ...
                all_burst(idx), ...
                all_labels{idx});
    end


    %==============================================================%
    % Offset
    %==============================================================%
    offset = ...
        compute_auto_trace_offset_from_cell( ...
            selected_traces);


    %==============================================================%
    % Figure
    %==============================================================%
    figure_title = ...
        sprintf( ...
            '%s representative traces by burst rate', ...
            label_name);


    fig = ...
        figure( ...
            'Color', 'w', ...
            'Units', 'normalized', ...
            'Position', ...
            [0.05 0.10 0.90 0.75], ...
            'Name', ...
            figure_title);


    ax = ...
        axes(fig);


    hold( ...
        ax, ...
        'on');


    for i = 1:3

        plot( ...
            ax, ...
            selected_time{i}, ...
            selected_traces{i} + ...
                (i - 1) * offset, ...
            'k', ...
            'LineWidth', ...
            1.3);
    end


    %==============================================================%
    % Axes
    %==============================================================%
    yticks( ...
        ax, ...
        (0:2) * offset);


    yticklabels( ...
        ax, ...
        selected_labels);


    set( ...
        ax, ...
        'TickLabelInterpreter', ...
        'none');


    xlabel( ...
        ax, ...
        'Time (s)');


    ylabel( ...
        ax, ...
        '\DeltaF/F + offset');


    title( ...
        ax, ...
        figure_title, ...
        'Interpreter', ...
        'none');


    grid( ...
        ax, ...
        'off');


    box( ...
        ax, ...
        'off');


    hold( ...
        ax, ...
        'off');


    %==============================================================%
    % Nom de sauvegarde
    %
    % Plusieurs recordings / dates / âges / plans sont poolés :
    % on ne met donc pas date_age_plane dans le nom.
    %==============================================================%
    if isempty(current_line)

        filename = ...
            sprintf( ...
                '%s_%s_%s_representative_traces_by_burst_rate.png', ...
                char(string(current_type)), ...
                char(string(current_animal)), ...
                label_name);

    else

        filename = ...
            sprintf( ...
                '%s_%s_%s_%s_representative_traces_by_burst_rate.png', ...
                char(string(current_line)), ...
                char(string(current_animal)), ...
                char(string(current_type)), ...
                label_name);
    end


    save_path = ...
        fullfile( ...
            current_gcamp_output_folder, ...
            filename);


    %==============================================================%
    % Ne pas recalculer/sauvegarder si existe
    %==============================================================%
    if exist(save_path, 'file') == 2

        fprintf( ...
            'Burst figure already exists, skip: %s\n', ...
            save_path);


        if isgraphics(fig)
            close(fig);
        end

        return;
    end


    %==============================================================%
    % Sauvegarde
    %==============================================================%
    set( ...
        fig, ...
        'WindowState', ...
        'maximized');


    drawnow;


    exportgraphics( ...
        fig, ...
        save_path, ...
        'Resolution', ...
        300);


    fprintf( ...
        'Saved: %s\n', ...
        save_path);


    if isgraphics(fig)
        close(fig);
    end
end


%==================================================================%
% Helper : déballage numérique
%==================================================================%
function out = unwrap_numeric(x)

    out = ...
        x;


    while iscell(out) && ...
            numel(out) == 1

        out = ...
            out{1};
    end


    if iscell(out)

        tmp = [];


        for i = 1:numel(out)

            xi = ...
                unwrap_numeric( ...
                    out{i});


            if isnumeric(xi) || ...
                    islogical(xi)

                tmp = ...
                    [ ...
                        tmp; ...
                        double(xi(:)) ...
                    ]; %#ok<AGROW>
            end
        end


        out = ...
            tmp;
    end


    if isnumeric(out) || ...
            islogical(out)

        out = ...
            double(out);
    end
end


%==================================================================%
% Helper : offset automatique
%==================================================================%
function offset = compute_auto_trace_offset_from_cell( ...
        trace_cells)

    all_vals = [];


    for i = 1:numel(trace_cells)

        x = ...
            trace_cells{i};


        if isempty(x) || ...
                ~isnumeric(x)

            continue;
        end


        x = ...
            double( ...
                x(:));


        x = ...
            x( ...
                isfinite(x));


        if isempty(x)
            continue;
        end


        all_vals = ...
            [ ...
                all_vals; ...
                x ...
            ]; %#ok<AGROW>
    end


    %==============================================================%
    % Fallback
    %==============================================================%
    if isempty(all_vals)

        offset = ...
            1;

        return;
    end


    %==============================================================%
    % Amplitude robuste
    %==============================================================%
    amp = ...
        prctile(all_vals, 99) - ...
        prctile(all_vals, 1);


    if ~isfinite(amp) || ...
            amp <= 0

        amp = ...
            std( ...
                all_vals, ...
                'omitnan');
    end


    if ~isfinite(amp) || ...
            amp <= 0

        amp = ...
            1;
    end


    offset = ...
        1.5 * amp;
end