function figs_by_line = plot_basic_metrics_by_line( ...
        selected_groups, ...
        include_electroporated, ...
        output_folders_line)

    %==============================================================%
    % PLOT BASIC METRICS BY LINE
    %
    % Une figure par current_line uniquement si cette line contient
    % plus d'un animal.
    %
    % Figure :
    %
    %   colonne 1 = GCaMP / non-electroporated
    %   colonne 2 = Electroporated
    %   colonne 3 = medianes par age
    %
    % Metriques :
    %
    %   Frequency
    %   Correlation
    %   SCE frequency
    %   SCE participation
    %   SCE duration
    %
    % Couleurs :
    %
    %   GCaMP / non-electroporated = vert
    %   Electroporated             = bleu
    %
    % Axe X :
    %
    %   positions proportionnelles a l'age reel
    %
    % Annotations :
    %
    %   les ages proches sont regroupes dans un seul cartouche
    %
    % Exemple :
    %
    %   P56   n = 2    1992
    %   P57   n = 4    1992
    %   P58   n = 22   1992
    %
    %==============================================================%


    %==============================================================%
    % Inputs
    %==============================================================%
    if nargin < 1 || ...
            isempty(selected_groups)

        return;
    end


    if nargin < 2 || ...
            isempty(include_electroporated)

        include_electroporated = ...
            false;
    end


    if nargin < 3 || ...
            isempty(output_folders_line)

        error( ...
            'output_folders_line must be provided.');
    end


    if ~isstruct(selected_groups)

        error( ...
            'selected_groups must be a structure.');
    end


    if ~iscell(output_folders_line)

        error( ...
            'output_folders_line must be a cell array.');
    end


    %==============================================================%
    % Electroporated
    %==============================================================%
    if islogical(include_electroporated)

        process_electroporated = ...
            include_electroporated;

    else

        process_electroporated = ...
            strcmp( ...
                char(string(include_electroporated)), ...
                '1');
    end


    %==============================================================%
    % Initialisation
    %==============================================================%
    figs_by_line = ...
        struct();


    type_names = ...
        fieldnames(selected_groups);


    %==============================================================%
    % Boucle types
    %==============================================================%
    for t = 1:numel(type_names)

        current_type = ...
            type_names{t};


        animals = ...
            selected_groups.(current_type);


        if isempty(animals)

            continue;
        end


        if t > numel(output_folders_line) || ...
                isempty(output_folders_line{t})

            warning( ...
                ['No output_folders_line entry found for ', ...
                 'type %s. Skipping this type.'], ...
                current_type);

            continue;
        end


        %==========================================================%
        % Recuperer les lines
        %==========================================================%
        line_values = ...
            strings( ...
                numel(animals), ...
                1);


        for k = 1:numel(animals)

            if isfield(animals(k), 'line') && ...
                    ~isempty(animals(k).line)

                line_values(k) = ...
                    string( ...
                        animals(k).line);

            else

                line_values(k) = ...
                    "";
            end
        end


        unique_lines = ...
            unique( ...
                line_values, ...
                'stable');


        unique_lines( ...
            strlength(unique_lines) == 0) = [];


        %==========================================================%
        % Boucle lines
        %==========================================================%
        for l = 1:numel(unique_lines)

            current_line = ...
                unique_lines(l);


            if l > numel(output_folders_line{t})

                warning( ...
                    ['No output folder found for ', ...
                     '%s | %s. Skipping this line.'], ...
                    current_type, ...
                    char(current_line));

                continue;
            end


            current_output_folder = ...
                output_folders_line{t}{l};


            if isempty(current_output_folder)

                warning( ...
                    ['Empty output folder for ', ...
                     '%s | %s. Skipping this line.'], ...
                    current_type, ...
                    char(current_line));

                continue;
            end


            %======================================================%
            % Animaux de cette line
            %======================================================%
            line_mask = ...
                line_values == current_line;


            current_animals = ...
                animals(line_mask);


            animal_names = ...
                strings( ...
                    numel(current_animals), ...
                    1);


            for k = 1:numel(current_animals)

                if isfield(current_animals(k), 'animal') && ...
                        ~isempty(current_animals(k).animal)

                    animal_names(k) = ...
                        string( ...
                            current_animals(k).animal);

                else

                    animal_names(k) = ...
                        "animal_" + string(k);
                end
            end


            n_animals = ...
                numel( ...
                    unique( ...
                        animal_names, ...
                        'stable'));


            if n_animals <= 1

                fprintf( ...
                    ['Basic metrics skipped: ', ...
                     '%s | %s | only %d animal.\n'], ...
                    current_type, ...
                    char(current_line), ...
                    n_animals);

                continue;
            end


            if exist( ...
                    current_output_folder, ...
                    'dir') ~= 7

                mkdir( ...
                    current_output_folder);
            end


            fprintf('\n');
            fprintf('============================================\n');
            fprintf('BASIC METRICS BY LINE\n');
            fprintf('Type: %s\n', current_type);
            fprintf('Line: %s\n', char(current_line));
            fprintf('Animals: %d\n', n_animals);
            fprintf('Output folder: %s\n', current_output_folder);
            fprintf('============================================\n');


            %======================================================%
            % Collecte
            %======================================================%
            records = ...
                collect_basic_metric_records( ...
                    current_animals);


            if isempty(records)

                fprintf( ...
                    'No basic metrics found for %s | %s.\n', ...
                    current_type, ...
                    char(current_line));

                continue;
            end


            age_values = ...
                [records.AgeValue]';


            valid_age = ...
                isfinite(age_values);


            records = ...
                records(valid_age);


            if isempty(records)

                continue;
            end


            age_values = ...
                [records.AgeValue]';


            [~, order_idx] = ...
                sort( ...
                    age_values, ...
                    'ascend');


            records = ...
                records(order_idx);


            ages = ...
                unique( ...
                    [records.AgeValue], ...
                    'sorted');



            %======================================================%
            % Figure
            %======================================================%
            figHandle = ...
                make_violin_metrics_figure( ...
                    records, ...
                    ages, ...
                    current_type, ...
                    current_line, ...
                    process_electroporated);


            if isempty(figHandle)

                continue;
            end


            %======================================================%
            % Sauvegarde
            %======================================================%
            safe_type_filename = ...
                sanitize_filename_basic_metrics( ...
                    current_type);


            safe_line_filename = ...
                sanitize_filename_basic_metrics( ...
                    current_line);


            if isempty(safe_line_filename)

                safe_line_filename = ...
                    'no_line';
            end


            output_name = ...
                sprintf( ...
                    '%s_%s_basic_metrics_violin_by_age.png', ...
                    safe_type_filename, ...
                    safe_line_filename);


            save_figure_png( ...
                figHandle, ...
                current_output_folder, ...
                output_name);


            if isgraphics(figHandle)

                close(figHandle);
            end
        end
    end
end


%==================================================================
% COLLECTER LES RECORDINGS
%==================================================================
function records = ...
    collect_basic_metric_records( ...
        animals)

    template = ...
        struct( ...
            'Animal', '', ...
            'Date', '', ...
            'AgeRaw', [], ...
            'AgeValue', NaN, ...
            ...
            'Frequency_gcamp', [], ...
            'Frequency_electroporated', [], ...
            ...
            'Correlation_gcamp', [], ...
            'Correlation_electroporated', [], ...
            ...
            'SCEFrequency', [], ...
            'SCEParticipation', []);


    records = ...
        repmat( ...
            template, ...
            0, ...
            1);


    record_counter = ...
        0;


    for k = 1:numel(animals)

        animal_struct = ...
            animals(k);


        if ~isfield( ...
                animal_struct, ...
                'results_analysis') || ...
                isempty(animal_struct.results_analysis) || ...
                ~isstruct(animal_struct.results_analysis)

            continue;
        end


        if ~isfield(animal_struct, 'ages') || ...
                isempty(animal_struct.ages)

            continue;
        end


        if ~isfield(animal_struct, 'dates') || ...
                isempty(animal_struct.dates)

            continue;
        end


        current_results = ...
            animal_struct.results_analysis;


        current_ages = ...
            animal_struct.ages(:);


        current_dates = ...
            animal_struct.dates(:);


        animal_name = ...
            get_animal_name( ...
                animal_struct, ...
                k);


        nRec_results = ...
            infer_nrec_from_current_results( ...
                current_results);


        nRec = ...
            max( ...
                [ ...
                    numel(current_ages), ...
                    numel(current_dates), ...
                    nRec_results ...
                ]);


        if nRec == 0

            continue;
        end


        current_ages = ...
            normalize_record_cell( ...
                current_ages, ...
                nRec);


        current_dates = ...
            normalize_record_cell( ...
                current_dates, ...
                nRec);


        for m = 1:nRec

            record_counter = ...
                record_counter + 1;


            age_raw = ...
                get_record_value( ...
                    current_ages, ...
                    m);


            date_raw = ...
                get_record_value( ...
                    current_dates, ...
                    m);


            records(record_counter).Animal = ...
                animal_name;


            records(record_counter).Date = ...
                value_to_text( ...
                    date_raw);


            records(record_counter).AgeRaw = ...
                age_raw;


            records(record_counter).AgeValue = ...
                parse_one_age( ...
                    age_raw);


            %======================================================%
            % GCaMP
            %======================================================%
            records(record_counter).Frequency_gcamp = ...
                get_nested_record_value( ...
                    current_results, ...
                    { ...
                        'gcamp_plane', ...
                        'activity', ...
                        'FrequencyPerCell' ...
                    }, ...
                    m, ...
                    nRec);


            records(record_counter).Correlation_gcamp = ...
                get_nested_record_value( ...
                    current_results, ...
                    { ...
                        'gcamp_plane', ...
                        'correlations', ...
                        'max_corr_gcamp_gcamp_by_plane' ...
                    }, ...
                    m, ...
                    nRec);


            %======================================================%
            % Electroporated frequency
            %======================================================%
            frequency_electroporated = ...
                get_nested_record_value( ...
                    current_results, ...
                    { ...
                        'electroporated_plane', ...
                        'activity', ...
                        'FrequencyPerCell' ...
                    }, ...
                    m, ...
                    nRec);


            if isempty(frequency_electroporated)

                frequency_electroporated = ...
                    get_nested_record_value( ...
                        current_results, ...
                        { ...
                            'blue_plane', ...
                            'activity', ...
                            'FrequencyPerCell' ...
                        }, ...
                        m, ...
                        nRec);
            end


            records(record_counter).Frequency_electroporated = ...
                frequency_electroporated;


            %======================================================%
            % Electroporated correlation
            %======================================================%
            correlation_electroporated = ...
                get_nested_record_value( ...
                    current_results, ...
                    { ...
                        'electroporated_plane', ...
                        'correlations', ...
                        'max_corr_gcamp_mtor_by_plane' ...
                    }, ...
                    m, ...
                    nRec);


            if isempty(correlation_electroporated)

                correlation_electroporated = ...
                    get_nested_record_value( ...
                        current_results, ...
                        { ...
                            'blue_plane', ...
                            'correlations', ...
                            'max_corr_gcamp_mtor_by_plane' ...
                        }, ...
                        m, ...
                        nRec);
            end


            records(record_counter).Correlation_electroporated = ...
                correlation_electroporated;


            %======================================================%
            % SCE
            %======================================================%
            records(record_counter).SCEFrequency = ...
                get_nested_record_value( ...
                    current_results, ...
                    { ...
                        'gcamp_plane', ...
                        'SCEs', ...
                        'Frequency' ...
                    }, ...
                    m, ...
                    nRec);


            records(record_counter).SCEParticipation = ...
                get_nested_record_value( ...
                    current_results, ...
                    { ...
                        'gcamp_plane', ...
                        'SCEs', ...
                        'CellParticipation_percent' ...
                    }, ...
                    m, ...
                    nRec);

        end
    end
end


%==================================================================
% CREER FIGURE
%==================================================================
function figHandle = ...
    make_violin_metrics_figure( ...
        records, ...
        ages, ...
        current_type, ...
        current_line, ...
        include_electroporated)

    %==============================================================%
    % Metriques
    %==============================================================%
    metric_names = { ...
        'Frequency'; ...
        'Correlation'; ...
        'SCE frequency'; ...
        'SCE participation'};
    
    
    metric_units = { ...
        'events / min'; ...
        'correlation'; ...
        'SCE / min'; ...
        '%'};
    
    
    gcamp_fields = { ...
        'Frequency_gcamp'; ...
        'Correlation_gcamp'; ...
        'SCEFrequency'; ...
        'SCEParticipation'};
    
    
    electroporated_fields = { ...
        'Frequency_electroporated'; ...
        'Correlation_electroporated'; ...
        ''; ...
        ''};
    
    
    correlation_rows = ...
        [false true false false];


    nMetrics = ...
        numel(metric_names);


    nAges = ...
        numel(ages);


    if nAges == 0

        figHandle = [];

        return;
    end


    %==============================================================%
    % Couleurs
    %==============================================================%
    gcamp_color = ...
        [0.10 0.65 0.25];


    electroporated_color = ...
        [0.15 0.40 0.95];


    %==============================================================%
    % Figure
    %==============================================================%
    row_height = ...
        470;


    figure_height = ...
        max( ...
            900, ...
            nMetrics * row_height);


    figHandle = ...
        figure( ...
            'Color', ...
            'w', ...
            'Name', ...
            sprintf( ...
                '%s_%s_basic_metrics', ...
                current_type, ...
                char(current_line)), ...
            'Units', ...
            'pixels', ...
            'Position', ...
            [50 50 1800 figure_height]);


    tl = ...
        tiledlayout( ...
            figHandle, ...
            nMetrics, ...
            3, ...
            'TileSpacing', ...
            'compact', ...
            'Padding', ...
            'compact');


    title( ...
        tl, ...
        sprintf( ...
            '%s | %s - Basic metrics by age', ...
            current_type, ...
            char(current_line)), ...
        'Interpreter', ...
        'none', ...
        'FontSize', ...
        18, ...
        'FontWeight', ...
        'bold');


    %==============================================================%
    % Metriques
    %==============================================================%
    for m = 1:nMetrics

        gcamp_by_age = ...
            cell( ...
                nAges, ...
                1);


        electroporated_by_age = ...
            cell( ...
                nAges, ...
                1);


        gcamp_animals_by_age = ...
            cell( ...
                nAges, ...
                1);


        electroporated_animals_by_age = ...
            cell( ...
                nAges, ...
                1);


        median_gcamp = ...
            nan( ...
                nAges, ...
                1);


        median_electroporated = ...
            nan( ...
                nAges, ...
                1);


        %==========================================================%
        % Boucle ages
        %==========================================================%
        for a = 1:nAges

            age_idx = ...
                [records.AgeValue] == ages(a);


            current_records = ...
                records(age_idx);


            %======================================================%
            % GCaMP
            %======================================================%
            values_gcamp = ...
                [];


            animals_gcamp = ...
                strings(0,1);


            for r = 1:numel(current_records)

                vals = ...
                    flatten_metric_values( ...
                        current_records(r). ...
                            (gcamp_fields{m}), ...
                        correlation_rows(m));


                if ~isempty(vals)

                    values_gcamp = ...
                        [ ...
                            values_gcamp; ...
                            vals(:) ...
                        ];


                    animals_gcamp(end+1,1) = ...
                        string( ...
                            current_records(r).Animal);
                end
            end


            values_gcamp = ...
                values_gcamp( ...
                    isfinite(values_gcamp));


            animals_gcamp = ...
                unique( ...
                    animals_gcamp, ...
                    'stable');


            gcamp_by_age{a} = ...
                values_gcamp;


            gcamp_animals_by_age{a} = ...
                animals_gcamp;


            if ~isempty(values_gcamp)

                median_gcamp(a) = ...
                    median( ...
                        values_gcamp, ...
                        'omitnan');
            end


            %======================================================%
            % Electroporated
            %======================================================%
            if include_electroporated && ...
                    ~isempty(electroporated_fields{m})

                values_electroporated = ...
                    [];


                animals_electroporated = ...
                    strings(0,1);


                for r = 1:numel(current_records)

                    vals = ...
                        flatten_metric_values( ...
                            current_records(r). ...
                                (electroporated_fields{m}), ...
                            correlation_rows(m));


                    if ~isempty(vals)

                        values_electroporated = ...
                            [ ...
                                values_electroporated; ...
                                vals(:) ...
                            ];


                        animals_electroporated(end+1,1) = ...
                            string( ...
                                current_records(r).Animal);
                    end
                end


                values_electroporated = ...
                    values_electroporated( ...
                        isfinite(values_electroporated));


                animals_electroporated = ...
                    unique( ...
                        animals_electroporated, ...
                        'stable');


                electroporated_by_age{a} = ...
                    values_electroporated;


                electroporated_animals_by_age{a} = ...
                    animals_electroporated;


                if ~isempty(values_electroporated)

                    median_electroporated(a) = ...
                        median( ...
                            values_electroporated, ...
                            'omitnan');
                end
            end
        end


        %==========================================================%
        % Limites Y communes
        %==========================================================%
        all_values = ...
            [];


        for a = 1:nAges

            all_values = ...
                [ ...
                    all_values; ...
                    gcamp_by_age{a}(:); ...
                    electroporated_by_age{a}(:) ...
                ];
        end


        all_values = ...
            all_values( ...
                isfinite(all_values));


        if isempty(all_values)

            y_limits = ...
                [0 1];

        else

            ymin = ...
                min(all_values);


            ymax = ...
                max(all_values);


            if ymin == ymax

                delta = ...
                    max( ...
                        abs(ymin) * 0.1, ...
                        1);


                y_limits = ...
                    [ ...
                        ymin - delta, ...
                        ymax + 2 * delta ...
                    ];

            else

                y_range = ...
                    ymax - ymin;


                padding_bottom = ...
                    0.05 * y_range;


                %==================================================%
                % Grande zone reservee aux cartouches
                %==================================================%
                annotation_space = ...
                    0.45 * y_range;


                y_limits = ...
                    [ ...
                        ymin - padding_bottom, ...
                        ymax + annotation_space ...
                    ];
            end
        end


        %==========================================================%
        % COLONNE 1 : GCaMP
        %==========================================================%
        ax1 = ...
            nexttile( ...
                tl, ...
                (m - 1) * 3 + 1);


        hold( ...
            ax1, ...
            'on');


        ylim( ...
            ax1, ...
            y_limits);


        plot_violin_by_age( ...
            ax1, ...
            gcamp_by_age, ...
            gcamp_animals_by_age, ...
            ages, ...
            gcamp_color);


        ylabel( ...
            ax1, ...
            sprintf( ...
                '%s\n(%s)', ...
                metric_names{m}, ...
                metric_units{m}), ...
            'Interpreter', ...
            'none', ...
            'FontWeight', ...
            'bold');


        if m == 1

            title( ...
                ax1, ...
                'GCaMP / non-electroporated', ...
                'FontWeight', ...
                'bold', ...
                'FontSize', ...
                14);
        end


        format_age_axis( ...
            ax1, ...
            ages);


        %==========================================================%
        % COLONNE 2 : Electroporated
        %==========================================================%
        ax2 = ...
            nexttile( ...
                tl, ...
                (m - 1) * 3 + 2);


        hold( ...
            ax2, ...
            'on');


        ylim( ...
            ax2, ...
            y_limits);


        if include_electroporated && ...
                ~isempty(electroporated_fields{m})

            has_electroporated_data = ...
                any( ...
                    cellfun( ...
                        @(x) ~isempty(x), ...
                        electroporated_by_age));


            if has_electroporated_data

                plot_violin_by_age( ...
                    ax2, ...
                    electroporated_by_age, ...
                    electroporated_animals_by_age, ...
                    ages, ...
                    electroporated_color);

            else

                text( ...
                    ax2, ...
                    0.5, ...
                    0.5, ...
                    'No electroporated data', ...
                    'Units', ...
                    'normalized', ...
                    'HorizontalAlignment', ...
                    'center', ...
                    'VerticalAlignment', ...
                    'middle', ...
                    'FontSize', ...
                    10);
            end

        else

            text( ...
                ax2, ...
                0.5, ...
                0.5, ...
                'Not applicable', ...
                'Units', ...
                'normalized', ...
                'HorizontalAlignment', ...
                'center', ...
                'VerticalAlignment', ...
                'middle', ...
                'FontSize', ...
                10);
        end


        if m == 1

            title( ...
                ax2, ...
                'Electroporated', ...
                'FontWeight', ...
                'bold', ...
                'FontSize', ...
                14);
        end


        format_age_axis( ...
            ax2, ...
            ages);


        %==========================================================%
        % COLONNE 3 : MEDIANES
        %==========================================================%
        ax3 = ...
            nexttile( ...
                tl, ...
                (m - 1) * 3 + 3);


        hold( ...
            ax3, ...
            'on');


        valid_gcamp = ...
            isfinite( ...
                median_gcamp);


        if any(valid_gcamp)

            plot( ...
                ax3, ...
                ages(valid_gcamp), ...
                median_gcamp(valid_gcamp), ...
                '-o', ...
                'Color', ...
                gcamp_color, ...
                'MarkerEdgeColor', ...
                gcamp_color, ...
                'MarkerFaceColor', ...
                'w', ...
                'LineWidth', ...
                2, ...
                'MarkerSize', ...
                7, ...
                'DisplayName', ...
                'GCaMP / non-electroporated');
        end


        valid_electroporated = ...
            isfinite( ...
                median_electroporated);


        if include_electroporated && ...
                any(valid_electroporated)

            plot( ...
                ax3, ...
                ages(valid_electroporated), ...
                median_electroporated(valid_electroporated), ...
                '-o', ...
                'Color', ...
                electroporated_color, ...
                'MarkerEdgeColor', ...
                electroporated_color, ...
                'MarkerFaceColor', ...
                'w', ...
                'LineWidth', ...
                2, ...
                'MarkerSize', ...
                7, ...
                'DisplayName', ...
                'Electroporated');
        end


        ylim( ...
            ax3, ...
            y_limits);


        format_age_axis( ...
            ax3, ...
            ages);


        grid( ...
            ax3, ...
            'on');


        if m == 1

            title( ...
                ax3, ...
                'Median by age', ...
                'FontWeight', ...
                'bold', ...
                'FontSize', ...
                14);
        end


        if m == 1 && ...
                (any(valid_gcamp) || ...
                 any(valid_electroporated))

            legend( ...
                ax3, ...
                'Location', ...
                'best', ...
                'Interpreter', ...
                'none');
        end


        if m == nMetrics

            xlabel( ...
                ax1, ...
                'Age');


            xlabel( ...
                ax2, ...
                'Age');


            xlabel( ...
                ax3, ...
                'Age');
        end
    end
end


%==================================================================
% VIOLIN PLOT PAR AGE
%==================================================================
function plot_violin_by_age( ...
        ax, ...
        values_by_age, ...
        animals_by_age, ...
        ages, ...
        violin_color)

    hold( ...
        ax, ...
        'on');


    nAges = ...
        numel(ages);


    if nAges == 0

        return;
    end


    %==============================================================%
    % Largeur violin
    %==============================================================%
    if nAges > 1

        minimum_age_spacing = ...
            min( ...
                diff(ages));


        violin_half_width = ...
            min( ...
                0.32, ...
                0.28 * minimum_age_spacing);

    else

        violin_half_width = ...
            0.32;
    end


    %==============================================================%
    % Dessiner les violins
    %==============================================================%
    for a = 1:nAges

        values = ...
            clean_numeric( ...
                values_by_age{a});


        if isempty(values)

            continue;
        end


        x_center = ...
            ages(a);


        n_values = ...
            numel(values);


        med = ...
            median( ...
                values, ...
                'omitnan');


        data_min = ...
            min(values);


        data_max = ...
            max(values);


        %==========================================================%
        % Un seul point
        %==========================================================%
        if n_values == 1

            plot( ...
                ax, ...
                x_center, ...
                values, ...
                'o', ...
                'MarkerSize', ...
                6, ...
                'MarkerFaceColor', ...
                violin_color, ...
                'MarkerEdgeColor', ...
                violin_color);

            continue;
        end


        %==========================================================%
        % Valeurs identiques
        %==========================================================%
        if data_min == data_max

            plot( ...
                ax, ...
                [ ...
                    x_center - violin_half_width, ...
                    x_center + violin_half_width ...
                ], ...
                [ ...
                    data_min, ...
                    data_min ...
                ], ...
                '-', ...
                'LineWidth', ...
                4, ...
                'Color', ...
                violin_color);


            plot( ...
                ax, ...
                x_center, ...
                data_min, ...
                'o', ...
                'MarkerFaceColor', ...
                violin_color, ...
                'MarkerEdgeColor', ...
                violin_color, ...
                'MarkerSize', ...
                5);

            continue;
        end


        %==========================================================%
        % KDE manuel
        %==========================================================%
        nGrid = ...
            100;


        data_std = ...
            std(values);


        data_iqr = ...
            local_iqr( ...
                values);


        robust_sigma = ...
            min( ...
                data_std, ...
                data_iqr / 1.34);


        if ~isfinite(robust_sigma) || ...
                robust_sigma <= 0

            robust_sigma = ...
                data_std;
        end


        if ~isfinite(robust_sigma) || ...
                robust_sigma <= 0

            robust_sigma = ...
                (data_max - data_min) / 4;
        end


        bandwidth = ...
            0.9 * ...
            robust_sigma * ...
            n_values^(-1/5);


        minimum_bandwidth = ...
            (data_max - data_min) / 100;


        bandwidth = ...
            max( ...
                bandwidth, ...
                minimum_bandwidth);


        padding = ...
            3 * bandwidth;


        y_grid = ...
            linspace( ...
                data_min - padding, ...
                data_max + padding, ...
                nGrid);


        density = ...
            zeros( ...
                size(y_grid));


        for i = 1:n_values

            z = ...
                ( ...
                    y_grid - values(i) ...
                ) ./ bandwidth;


            density = ...
                density + ...
                exp( ...
                    -0.5 * z.^2);
        end


        density = ...
            density ./ ...
            ( ...
                n_values * ...
                bandwidth * ...
                sqrt(2*pi) ...
            );


        density_max = ...
            max(density);


        if density_max > 0

            density = ...
                density ./ ...
                density_max;
        end


        width = ...
            violin_half_width * ...
            density;


        %==========================================================%
        % Violin
        %==========================================================%
        patch( ...
            ax, ...
            [ ...
                x_center - width, ...
                fliplr(x_center + width) ...
            ], ...
            [ ...
                y_grid, ...
                fliplr(y_grid) ...
            ], ...
            violin_color, ...
            'FaceAlpha', ...
            0.35, ...
            'EdgeColor', ...
            violin_color, ...
            'LineWidth', ...
            1.2);


        %==========================================================%
        % Mediane
        %==========================================================%
        plot( ...
            ax, ...
            [ ...
                x_center - violin_half_width * 0.30, ...
                x_center + violin_half_width * 0.30 ...
            ], ...
            [ ...
                med, ...
                med ...
            ], ...
            'k-', ...
            'LineWidth', ...
            2);
    end


    %==============================================================%
    % Annotations apres les violins
    %==============================================================%
    draw_grouped_violin_annotations( ...
        ax, ...
        values_by_age, ...
        animals_by_age, ...
        ages, ...
        violin_color);
end


%==================================================================
% CARTOUCHES GROUPES
%==================================================================
%==================================================================
% CARTOUCHES GROUPES
%==================================================================
function draw_grouped_violin_annotations( ...
        ax, ...
        values_by_age, ...
        animals_by_age, ...
        ages, ...
        violin_color)

    nAges = ...
        numel(ages);


    if nAges == 0

        return;
    end


    %==============================================================%
    % Ages separes de <= 3 jours = meme groupe
    %==============================================================%
    close_age_threshold = ...
        3;


    %==============================================================%
    % Construire les groupes
    %==============================================================%
    groups = ...
        cell(0,1);


    group_counter = ...
        1;


    groups{group_counter} = ...
        1;


    for a = 2:nAges

        if ages(a) - ages(a - 1) <= close_age_threshold

            groups{group_counter}(end+1) = ...
                a;

        else

            group_counter = ...
                group_counter + 1;


            groups{group_counter} = ...
                a;
        end
    end


    %==============================================================%
    % Limites axe
    %==============================================================%
    current_ylim = ...
        ylim(ax);


    y_range = ...
        current_ylim(2) - ...
        current_ylim(1);


    if ~isfinite(y_range) || ...
            y_range <= 0

        y_range = ...
            1;
    end


    %==============================================================%
    % Position verticale des cartouches
    %==============================================================%
    label_y = ...
        current_ylim(2) - ...
        0.10 * y_range;


    %==============================================================%
    % Chaque groupe
    %==============================================================%
    for g = 1:numel(groups)

        current_indices = ...
            groups{g};


        %==========================================================%
        % Garder uniquement les ages avec donnees
        %==========================================================%
        valid_indices = ...
            [];


        for j = 1:numel(current_indices)

            a = ...
                current_indices(j);


            values = ...
                clean_numeric( ...
                    values_by_age{a});


            if ~isempty(values)

                valid_indices(end+1) = ...
                    a;
            end
        end


        if isempty(valid_indices)

            continue;
        end


        %==========================================================%
        % Centre X du groupe
        %==========================================================%
        current_ages = ...
            ages(valid_indices);


        label_x = ...
            mean(current_ages);


        %==========================================================%
        % Recuperer animal(s) de chaque age
        %==========================================================%
        animal_text_by_age = ...
            strings( ...
                numel(valid_indices), ...
                1);


        for j = 1:numel(valid_indices)

            a = ...
                valid_indices(j);


            animal_names = ...
                string( ...
                    animals_by_age{a});


            animal_names = ...
                animal_names( ...
                    strlength(animal_names) > 0);


            animal_names = ...
                unique( ...
                    animal_names, ...
                    'stable');


            if isempty(animal_names)

                animal_text_by_age(j) = ...
                    "";

            else

                animal_text_by_age(j) = ...
                    strjoin( ...
                        animal_names, ...
                        ', ');
            end
        end


        %==========================================================%
        % CAS 1 :
        % UN SEUL AGE
        %
        %   1992
        %   n = 205
        %
        % Aucun age affiche
        %==========================================================%
        if numel(valid_indices) == 1

            a = ...
                valid_indices(1);


            values = ...
                clean_numeric( ...
                    values_by_age{a});


            n_values = ...
                numel(values);


            animal_text = ...
                animal_text_by_age(1);


            if strlength(animal_text) > 0

                label_text = ...
                    sprintf( ...
                        '%s\nn = %d', ...
                        animal_text, ...
                        n_values);

            else

                label_text = ...
                    sprintf( ...
                        'n = %d', ...
                        n_values);
            end


        %==========================================================%
        % CAS 2 :
        % PLUSIEURS AGES PROCHES
        %==========================================================%
        else

            %======================================================%
            % Verifier si tous les ages ont le meme animal
            %======================================================%
            nonempty_animals = ...
                animal_text_by_age( ...
                    strlength(animal_text_by_age) > 0);


            unique_animals = ...
                unique( ...
                    nonempty_animals, ...
                    'stable');


            same_animal = ...
                numel(unique_animals) == 1;


            %======================================================%
            % Meme animal pour tous les ages
            %
            %   1992
            %   n = 2
            %   n = 4
            %   n = 22
            %
            % Pas de 1-, 2-, 3-
            %======================================================%
            if same_animal

                label_lines = ...
                    strings(0,1);


                label_lines(end+1,1) = ...
                    unique_animals(1);


                for j = 1:numel(valid_indices)

                    a = ...
                        valid_indices(j);


                    values = ...
                        clean_numeric( ...
                            values_by_age{a});


                    n_values = ...
                        numel(values);


                    label_lines(end+1,1) = ...
                        string( ...
                            sprintf( ...
                                'n = %d', ...
                                n_values));
                end


            %======================================================%
            % Plusieurs animaux
            %
            %   1- 1992   n = 2
            %   2-        n = 4
            %   3- 2470   n = 22
            %
            % Ne pas repeter le meme animal consecutivement
            %======================================================%
            else

                label_lines = ...
                    strings(0,1);


                previous_animal_text = ...
                    "";


                for j = 1:numel(valid_indices)

                    a = ...
                        valid_indices(j);


                    values = ...
                        clean_numeric( ...
                            values_by_age{a});


                    n_values = ...
                        numel(values);


                    current_animal_text = ...
                        animal_text_by_age(j);


                    %==================================================%
                    % Ne pas repeter animal si identique
                    %==================================================%
                    if current_animal_text == previous_animal_text && ...
                            strlength(current_animal_text) > 0

                        animal_display = ...
                            "";

                    else

                        animal_display = ...
                            current_animal_text;
                    end


                    %==================================================%
                    % Ligne
                    %==================================================%
                    if strlength(animal_display) > 0

                        current_text = ...
                            sprintf( ...
                                '%d- %s   n = %d', ...
                                j, ...
                                animal_display, ...
                                n_values);

                    else

                        current_text = ...
                            sprintf( ...
                                '%d-        n = %d', ...
                                j, ...
                                n_values);
                    end


                    label_lines(end+1,1) = ...
                        string( ...
                            current_text);


                    previous_animal_text = ...
                        current_animal_text;
                end
            end


            label_text = ...
                strjoin( ...
                    label_lines, ...
                    newline);
        end


        %==========================================================%
        % Cartouche
        %==========================================================%
        text( ...
            ax, ...
            label_x, ...
            label_y, ...
            label_text, ...
            'HorizontalAlignment', ...
            'center', ...
            'VerticalAlignment', ...
            'middle', ...
            'FontSize', ...
            7.5, ...
            'FontWeight', ...
            'bold', ...
            'Color', ...
            [0.10 0.10 0.10], ...
            'BackgroundColor', ...
            'w', ...
            'EdgeColor', ...
            violin_color, ...
            'LineWidth', ...
            0.8, ...
            'Margin', ...
            2, ...
            'Clipping', ...
            'on');
    end
end

%==================================================================
% FORMAT AXE AGE
%==================================================================
function format_age_axis( ...
        ax, ...
        ages)

    if isempty(ages)

        return;
    end


    age_labels = ...
        compose( ...
            'P%d', ...
            ages);


    set( ...
        ax, ...
        'XTick', ...
        ages, ...
        'XTickLabel', ...
        age_labels, ...
        'TickDir', ...
        'out', ...
        'FontSize', ...
        9);


    xtickangle( ...
        ax, ...
        45);


    %==============================================================%
    % Positions reelles des ages
    %==============================================================%
    if numel(ages) == 1

        xlim( ...
            ax, ...
            [ ...
                ages(1) - 1, ...
                ages(1) + 1 ...
            ]);

    else

        total_age_range = ...
            max(ages) - ...
            min(ages);


        padding = ...
            max( ...
                1, ...
                0.03 * total_age_range);


        xlim( ...
            ax, ...
            [ ...
                min(ages) - padding, ...
                max(ages) + padding ...
            ]);
    end


    box( ...
        ax, ...
        'off');
end


%==================================================================
% APLATIR UNE METRIQUE
%==================================================================
function vals = ...
    flatten_metric_values( ...
        x, ...
        is_corr)

    vals = ...
        [];


    if nargin < 2

        is_corr = ...
            false;
    end


    if isempty(x)

        return;
    end


    if iscell(x)

        for i = 1:numel(x)

            current_vals = ...
                flatten_metric_values( ...
                    x{i}, ...
                    is_corr);


            if ~isempty(current_vals)

                vals = ...
                    [ ...
                        vals; ...
                        current_vals(:) ...
                    ];
            end
        end

        return;
    end


    if isstruct(x)

        return;
    end


    if ~(isnumeric(x) || ...
            islogical(x))

        return;
    end


    x = ...
        double(x);


    if is_corr && ...
            ismatrix(x) && ...
            size(x,1) > 1 && ...
            size(x,2) > 1 && ...
            size(x,1) == size(x,2)

        keep = ...
            triu( ...
                true(size(x)), ...
                1);


        x = ...
            x(keep);
    end


    vals = ...
        x(:);


    vals = ...
        vals( ...
            isfinite(vals));
end


%==================================================================
% GET NESTED RECORD VALUE
%==================================================================
function value = ...
    get_nested_record_value( ...
        S, ...
        path_fields, ...
        idx, ...
        nRec)

    value = ...
        [];


    x = ...
        get_nested_field_or_empty( ...
            S, ...
            path_fields);


    if isempty(x)

        return;
    end


    if iscell(x)

        if isvector(x)

            if numel(x) >= idx

                value = ...
                    x{idx};
            end

            return;
        end


        if size(x,1) == nRec && ...
                idx <= size(x,1)

            value = ...
                x(idx,:);

            return;
        end


        if numel(x) >= idx

            value = ...
                x{idx};
        end

        return;
    end


    if isstring(x)

        if numel(x) >= idx

            value = ...
                x(idx);

        elseif idx == 1

            value = ...
                x;
        end

        return;
    end


    if isnumeric(x) || ...
            islogical(x)

        if ~isvector(x) && ...
                size(x,1) == nRec && ...
                idx <= size(x,1)

            value = ...
                x(idx,:);

            return;
        end


        if isvector(x) && ...
                numel(x) == nRec

            value = ...
                x(idx);

            return;
        end


        if idx == 1

            value = ...
                x;
        end

        return;
    end


    if idx == 1

        value = ...
            x;
    end
end


%==================================================================
% GET NESTED FIELD
%==================================================================
function x = ...
    get_nested_field_or_empty( ...
        S, ...
        path_fields)

    x = ...
        [];


    current = ...
        S;


    for i = 1:numel(path_fields)

        fn = ...
            path_fields{i};


        if ~isstruct(current) || ...
                ~isfield(current, fn)

            return;
        end


        current = ...
            current.(fn);
    end


    x = ...
        current;
end


%==================================================================
% NOMBRE DE RECORDINGS
%==================================================================
function nRec = ...
    infer_nrec_from_current_results( ...
        results_analysis)

    nRec = ...
        0;


    candidate_paths = { ...
        ...
        {'gcamp_plane', 'activity', 'FrequencyPerCell'}, ...
        {'gcamp_plane', 'correlations', 'max_corr_gcamp_gcamp_by_plane'}, ...
        ...
        {'electroporated_plane', 'activity', 'FrequencyPerCell'}, ...
        {'electroporated_plane', 'correlations', 'max_corr_gcamp_mtor_by_plane'}, ...
        ...
        {'blue_plane', 'activity', 'FrequencyPerCell'}, ...
        {'blue_plane', 'correlations', 'max_corr_gcamp_mtor_by_plane'}, ...
        ...
        {'gcamp_plane', 'SCEs', 'Frequency'}, ...
        {'gcamp_plane', 'SCEs', 'CellParticipation_percent'}, ...
        {'gcamp_plane', 'SCEs', 'Duration_ms'} ...
    };


    for i = 1:numel(candidate_paths)

        x = ...
            get_nested_field_or_empty( ...
                results_analysis, ...
                candidate_paths{i});


        if isempty(x)

            continue;
        end


        if iscell(x) || ...
                isstring(x)

            if isvector(x)

                nRec = ...
                    max( ...
                        nRec, ...
                        numel(x));

            else

                nRec = ...
                    max( ...
                        nRec, ...
                        size(x,1));
            end
        end
    end
end


%==================================================================
% NORMALISER RECORD CELL
%==================================================================
function C = ...
    normalize_record_cell( ...
        C, ...
        nRec)

    if ~iscell(C)

        if isstring(C)

            C = ...
                cellstr(C(:));


        elseif isnumeric(C) || ...
                islogical(C)

            C = ...
                num2cell(C(:));


        elseif ischar(C)

            C = ...
                {C};


        else

            C = ...
                {C};
        end

    else

        C = ...
            C(:);
    end


    if numel(C) < nRec

        C(end+1:nRec,1) = ...
            {[]};


    elseif numel(C) > nRec

        C = ...
            C(1:nRec);
    end
end


%==================================================================
% GET RECORD VALUE
%==================================================================
function value = ...
    get_record_value( ...
        C, ...
        idx)

    value = ...
        [];


    if isempty(C) || ...
            idx > numel(C)

        return;
    end


    if iscell(C)

        value = ...
            C{idx};

    else

        value = ...
            C(idx);
    end
end


%==================================================================
% PARSE AGE
%==================================================================
function age_value = ...
    parse_one_age( ...
        age_raw)

    age_value = ...
        NaN;


    if isempty(age_raw)

        return;
    end


    if isnumeric(age_raw) || ...
            islogical(age_raw)

        age_raw = ...
            double(age_raw);


        if isscalar(age_raw) && ...
                isfinite(age_raw)

            age_value = ...
                age_raw;
        end

        return;
    end


    if iscell(age_raw)

        if ~isempty(age_raw)

            age_value = ...
                parse_one_age( ...
                    age_raw{1});
        end

        return;
    end


    if isstring(age_raw) || ...
            ischar(age_raw)

        tok = ...
            regexp( ...
                char(age_raw), ...
                '\d+(\.\d+)?', ...
                'match', ...
                'once');


        if ~isempty(tok)

            age_value = ...
                str2double(tok);
        end
    end
end


%==================================================================
% VALUE TO TEXT
%==================================================================
function txt = ...
    value_to_text( ...
        x)

    txt = ...
        '';


    if isempty(x)

        return;
    end


    if iscell(x)

        if ~isempty(x)

            txt = ...
                value_to_text( ...
                    x{1});
        end

        return;
    end


    if isdatetime(x)

        txt = ...
            char(string(x));

        return;
    end


    if isstring(x)

        if ~isempty(x)

            txt = ...
                char(x(1));
        end

        return;
    end


    if ischar(x)

        txt = ...
            x;

        return;
    end


    if isnumeric(x) || ...
            islogical(x)

        if isscalar(x)

            txt = ...
                char(string(x));
        end
    end
end


%==================================================================
% ANIMAL NAME
%==================================================================
function animal_name = ...
    get_animal_name( ...
        animal_struct, ...
        fallback_idx)

    animal_name = ...
        sprintf( ...
            'animal_%d', ...
            fallback_idx);


    candidate_fields = { ...
        'animal_group', ...
        'animal', ...
        'name'};


    for i = 1:numel(candidate_fields)

        fn = ...
            candidate_fields{i};


        if isfield(animal_struct, fn) && ...
                ~isempty(animal_struct.(fn))

            animal_name = ...
                char( ...
                    string( ...
                        animal_struct.(fn)));

            return;
        end
    end
end


%==================================================================
% CLEAN NUMERIC
%==================================================================
function x = ...
    clean_numeric( ...
        x)

    if isempty(x) || ...
            ~(isnumeric(x) || ...
              islogical(x))

        x = ...
            [];

        return;
    end


    x = ...
        double( ...
            x(:));


    x = ...
        x( ...
            isfinite(x));
end


%==================================================================
% IQR LOCAL
%==================================================================
function q = ...
    local_iqr( ...
        x)

    x = ...
        clean_numeric( ...
            x);


    if isempty(x)

        q = ...
            NaN;

        return;
    end


    x = ...
        sort(x);


    q25 = ...
        local_percentile( ...
            x, ...
            25);


    q75 = ...
        local_percentile( ...
            x, ...
            75);


    q = ...
        q75 - q25;
end


%==================================================================
% PERCENTILE LOCAL
%==================================================================
function value = ...
    local_percentile( ...
        x, ...
        percentile)

    x = ...
        sort( ...
            x(:));


    n = ...
        numel(x);


    if n == 0

        value = ...
            NaN;

        return;
    end


    if n == 1

        value = ...
            x(1);

        return;
    end


    position = ...
        1 + ...
        (n - 1) * ...
        percentile / 100;


    lower_index = ...
        floor(position);


    upper_index = ...
        ceil(position);


    if lower_index == upper_index

        value = ...
            x(lower_index);

    else

        fraction = ...
            position - lower_index;


        value = ...
            x(lower_index) * ...
            (1 - fraction) + ...
            x(upper_index) * ...
            fraction;
    end
end


%==================================================================
% SANITIZE FILENAME
%==================================================================
function safe_name = ...
    sanitize_filename_basic_metrics( ...
        input_name)

    safe_name = ...
        char( ...
            string( ...
                input_name));


    safe_name = ...
        regexprep( ...
            safe_name, ...
            '[<>:"/\\|?*]', ...
            '_');


    safe_name = ...
        strrep( ...
            safe_name, ...
            ' ', ...
            '_');
end


%==================================================================
% SAVE FIGURE
%==================================================================
function save_figure_png( ...
        figHandle, ...
        save_folder, ...
        filename)

    if isempty(figHandle) || ...
            ~ishghandle(figHandle)

        return;
    end


    if exist( ...
            save_folder, ...
            'dir') ~= 7

        mkdir( ...
            save_folder);
    end


    output_path = ...
        fullfile( ...
            save_folder, ...
            filename);


    try

        set( ...
            figHandle, ...
            'WindowState', ...
            'maximized');

    catch
    end


    drawnow;


    try

        exportgraphics( ...
            figHandle, ...
            output_path, ...
            'Resolution', ...
            300);

    catch

        saveas( ...
            figHandle, ...
            output_path);
    end


    fprintf( ...
        'Figure saved: %s\n', ...
        output_path);
end