function plot_functional_coupling( ...
        results_analysis, ...
        current_automatic_selection, ...
        current_output_folder, ...
        gcamp_output_folders, ...
        current_line, ...
        current_animal, ...
        current_dates, ...
        current_ages)

%PLOT_FUNCTIONAL_COUPLING
%
% Selon les données disponibles :
%
%   results_analysis.gcamp_plane.coupling
%       -> GCaMP-GCaMP functional coupling
%
%   results_analysis.electroporated_plane.coupling
%       -> GCaMP-mTOR functional coupling
%
%   les deux présents
%       -> GCaMP vs mTOR functional coupling
%
% Une figure par recording et par plan.
%
% Organisation des dossiers GCaMP :
%
%   gcamp_output_folders{m}{p}
%
% avec :
%   m = recording
%   p = plan
%
% Sauvegarde :
%
%   GCaMP-GCaMP
%       -> gcamp_output_folders{m}{p}
%
%   GCaMP-mTOR
%       -> gcamp_output_folders{m}{p}
%
%   GCaMP vs mTOR
%       -> current_output_folder
%
% IMPORTANT :
%   - aucun dossier n'est créé ici ;
%   - si un dossier GCaMP de plan est absent, les figures locales
%     de ce plan sont ignorées ;
%   - current_output_folder doit déjà exister.
%
% Nomenclature :
%
%   line_animal_date_age_planeN_nomFigure.png


    %==============================================================%
    % Vérifications
    %==============================================================%
    if isempty(results_analysis) || ...
            ~isstruct(results_analysis)

        return;
    end


    %==============================================================%
    % Sauvegarde comparative dans current_output_folder ?
    %==============================================================%
    save_in_current_output = ...
        current_automatic_selection ~= 0;
    
    
    %==============================================================%
    % Vérifier current_output_folder uniquement si utilisé
    %
    % current_output_folder contient déjà Adult ou Development.
    % L'arborescence line / animal / date est créée plus bas
    % recording par recording.
    %==============================================================%
    valid_global_output = ...
        false;
    
    
    if save_in_current_output
    
        valid_global_output = ...
            ~isempty(current_output_folder);
    
    
        if ~valid_global_output
    
            warning( ...
                ['Functional coupling: current_output_folder is empty. ' ...
                 'Comparative figures will be skipped.']);
        end
    end


    %==============================================================%
    % GCaMP-GCaMP coupling disponible ?
    %==============================================================%
    has_gcamp = ...
        isfield(results_analysis, 'gcamp_plane') && ...
        isstruct(results_analysis.gcamp_plane) && ...
        isfield(results_analysis.gcamp_plane, 'coupling') && ...
        isstruct(results_analysis.gcamp_plane.coupling) && ...
        ~isempty(fieldnames( ...
            results_analysis.gcamp_plane.coupling));


    %==============================================================%
    % GCaMP-mTOR coupling disponible ?
    %==============================================================%
    has_mtor = ...
        isfield(results_analysis, 'electroporated_plane') && ...
        isstruct(results_analysis.electroporated_plane) && ...
        isfield(results_analysis.electroporated_plane, 'coupling') && ...
        isstruct(results_analysis.electroporated_plane.coupling) && ...
        ~isempty(fieldnames( ...
            results_analysis.electroporated_plane.coupling));


    %==============================================================%
    % Rien à afficher
    %==============================================================%
    if ~has_gcamp && ...
            ~has_mtor

        fprintf( ...
            '%s: no functional coupling metrics available.\n', ...
            current_animal);

        return;
    end


    %==============================================================%
    % Nombre de recordings
    %==============================================================%
    nRec = ...
        max( ...
            [ ...
                numel(gcamp_output_folders), ...
                numel(current_dates), ...
                numel(current_ages) ...
            ]);


    %==============================================================%
    % Recordings
    %==============================================================%
    for m = 1:nRec

        %==========================================================%
        % Date / âge
        %==========================================================%
        if m <= numel(current_dates)

            current_date = ...
                get_date_label( ...
                    current_dates, ...
                    m);

        else

            current_date = ...
                '';
        end


        if m <= numel(current_ages)

            current_age = ...
                get_age_label( ...
                    current_ages, ...
                    m);

        else

            current_age = ...
                '';
        end

        %==========================================================%
        % Automatic-selection recording folder
        %
        % current_output_folder/
        %   line/
        %     animal/
        %       date/
        %==========================================================%
        automatic_recording_folder = '';
        
        
        if save_in_current_output && ...
                valid_global_output
        
            automatic_recording_folder = ...
                fullfile( ...
                    current_output_folder, ...
                    char(string(current_line)), ...
                    char(string(current_animal)), ...
                    char(string(current_date)));
        
        
            if exist(automatic_recording_folder, 'dir') ~= 7
        
                mkdir(automatic_recording_folder);
            end
        end

        %==========================================================%
        % GCaMP-GCaMP
        %==========================================================%
        gcamp = ...
            empty_coupling_data();


        if has_gcamp

            gcamp = ...
                get_gcamp_coupling_for_recording( ...
                    results_analysis. ...
                    gcamp_plane. ...
                    coupling, ...
                    m);
        end


        %==========================================================%
        % GCaMP-mTOR
        %==========================================================%
        mtor = ...
            empty_coupling_data();


        if has_mtor

            mtor = ...
                get_mtor_coupling_for_recording( ...
                    results_analysis. ...
                    electroporated_plane. ...
                    coupling, ...
                    m);
        end


        %==========================================================%
        % Nombre de plans
        %==========================================================%
        nPlanes = ...
            max( ...
                get_nplanes_coupling(gcamp), ...
                get_nplanes_coupling(mtor));


        if nPlanes == 0

            fprintf( ...
                'Rec %d: no functional coupling data, skip.\n', ...
                m);

            continue;
        end


        %==========================================================%
        % Plans
        %==========================================================%
        for p = 1:nPlanes

            plane_number = ...
                p - 1;


            %======================================================%
            % Dossier GCaMP DU PLAN
            %======================================================%
            current_gcamp_output_folder = '';


            if m <= numel(gcamp_output_folders) && ...
                    ~isempty(gcamp_output_folders{m}) && ...
                    iscell(gcamp_output_folders{m}) && ...
                    p <= numel(gcamp_output_folders{m}) && ...
                    ~isempty(gcamp_output_folders{m}{p})

                current_gcamp_output_folder = ...
                    gcamp_output_folders{m}{p};
            end


            valid_gcamp_output = ...
                ~isempty(current_gcamp_output_folder) && ...
                (ischar(current_gcamp_output_folder) || ...
                 isstring(current_gcamp_output_folder)) && ...
                isscalar(string(current_gcamp_output_folder)) && ...
                exist( ...
                    current_gcamp_output_folder, ...
                    'dir') == 7;


            %======================================================%
            % GCaMP-GCaMP
            %======================================================%
            has_gcamp_plane = ...
                coupling_plane_has_data( ...
                    gcamp, ...
                    p);


            if has_gcamp_plane

                if valid_gcamp_output

                    create_single_coupling_figure( ...
                        gcamp, ...
                        p, ...
                        'GCaMP-GCaMP functional coupling', ...
                        'GCaMP_GCaMP_functional_coupling', ...
                        current_gcamp_output_folder, ...
                        current_line, ...
                        current_animal, ...
                        current_date, ...
                        current_age, ...
                        plane_number);

                else

                    warning( ...
                        ['GCaMP-GCaMP rec %d plane %d: ' ...
                         'GCaMP output folder missing or invalid, ' ...
                         'figure skipped.'], ...
                        m, ...
                        plane_number);
                end
            end


            %======================================================%
            % GCaMP-mTOR
            %======================================================%
            has_mtor_plane = ...
                coupling_plane_has_data( ...
                    mtor, ...
                    p);


            if has_mtor_plane

                if valid_gcamp_output

                    create_single_coupling_figure( ...
                        mtor, ...
                        p, ...
                        'GCaMP-mTOR functional coupling', ...
                        'GCaMP_mTOR_functional_coupling', ...
                        current_gcamp_output_folder, ...
                        current_line, ...
                        current_animal, ...
                        current_date, ...
                        current_age, ...
                        plane_number);

                else

                    warning( ...
                        ['GCaMP-mTOR rec %d plane %d: ' ...
                         'GCaMP output folder missing or invalid, ' ...
                         'figure skipped.'], ...
                        m, ...
                        plane_number);
                end
            end


            %======================================================%
            % Comparaison GCaMP vs mTOR
            %
            % Sauvegardée uniquement si automatic selection ~= 0
            %======================================================%
            if save_in_current_output && ...
                    has_gcamp_plane && ...
                    has_mtor_plane
            
                if ~isempty(automatic_recording_folder)
            
                    create_comparative_coupling_figure( ...
                        gcamp, ...
                        mtor, ...
                        p, ...
                        automatic_recording_folder, ...
                        current_line, ...
                        current_animal, ...
                        current_date, ...
                        current_age, ...
                        plane_number);
            
                else
            
                    warning( ...
                        ['Comparative coupling rec %d plane %d: ' ...
                         'global output folder missing, figure skipped.'], ...
                        m, ...
                        plane_number);
                end
            end
        end
    end
end


%==================================================================%
% GCaMP coupling
%==================================================================%
function D = ...
    get_gcamp_coupling_for_recording( ...
        C, ...
        m)

    D = ...
        empty_coupling_data();


    D.population_corr = ...
        get_recording_field( ...
            C, ...
            'population_corr_gcamp_gcamp_by_plane', ...
            m);


    D.observed = ...
        get_recording_field( ...
            C, ...
            'peak_coupling_fraction_gcamp_gcamp_by_plane', ...
            m);


    D.shuffle = ...
        get_recording_field( ...
            C, ...
            'peak_coupling_shuffle_gcamp_gcamp_by_plane', ...
            m);


    D.excess = ...
        get_recording_field( ...
            C, ...
            'peak_coupling_excess_gcamp_gcamp_by_plane', ...
            m);


    D.ratio = ...
        get_recording_field( ...
            C, ...
            'peak_coupling_ratio_gcamp_gcamp_by_plane', ...
            m);


    D.max_lagged_corr = ...
        get_recording_field( ...
            C, ...
            'max_lagged_corr_gcamp_gcamp_population_by_plane', ...
            m);


    D.lag_ms = ...
        get_recording_field( ...
            C, ...
            'lag_to_gcamp_gcamp_population_ms_by_plane', ...
            m);


    D = ...
        normalize_coupling_planes(D);
end


%==================================================================%
% mTOR coupling
%==================================================================%
function D = ...
    get_mtor_coupling_for_recording( ...
        C, ...
        m)

    D = ...
        empty_coupling_data();


    D.population_corr = ...
        get_recording_field( ...
            C, ...
            'population_corr_gcamp_mtor_by_plane', ...
            m);


    D.observed = ...
        get_recording_field( ...
            C, ...
            'peak_coupling_fraction_by_plane', ...
            m);


    D.shuffle = ...
        get_recording_field( ...
            C, ...
            'peak_coupling_shuffle_by_plane', ...
            m);


    D.excess = ...
        get_recording_field( ...
            C, ...
            'peak_coupling_excess_by_plane', ...
            m);


    D.ratio = ...
        get_recording_field( ...
            C, ...
            'peak_coupling_ratio_by_plane', ...
            m);


    D.max_lagged_corr = ...
        get_recording_field( ...
            C, ...
            'max_lagged_corr_gcamp_population_by_plane', ...
            m);


    D.lag_ms = ...
        get_recording_field( ...
            C, ...
            'lag_to_gcamp_population_ms_by_plane', ...
            m);


    D = ...
        normalize_coupling_planes(D);
end


%==================================================================%
% Figure individuelle
%==================================================================%
function create_single_coupling_figure( ...
        D, ...
        p, ...
        figure_title, ...
        filename_title, ...
        current_gcamp_output_folder, ...
        current_line, ...
        current_animal, ...
        current_date, ...
        current_age, ...
        plane_number)

    fig = [];


    %==============================================================%
    % Vérifier dossier
    %==============================================================%
    if isempty(current_gcamp_output_folder) || ...
            exist( ...
                current_gcamp_output_folder, ...
                'dir') ~= 7

        fprintf( ...
            '%s | plane %d: invalid GCaMP output folder, skip.\n', ...
            figure_title, ...
            plane_number);

        return;
    end


    %==============================================================%
    % Filename
    %==============================================================%
    if isempty(current_line)

        filename = ...
            sprintf( ...
                '%s_%s_%s_plane%d_%s.png', ...
                current_animal, ...
                current_date, ...
                current_age, ...
                plane_number, ...
                filename_title);

    else

        filename = ...
            sprintf( ...
                '%s_%s_%s_%s_plane%d_%s.png', ...
                current_line, ...
                current_animal, ...
                current_date, ...
                current_age, ...
                plane_number, ...
                filename_title);
    end


    save_path = ...
        fullfile( ...
            current_gcamp_output_folder, ...
            filename);


    %==============================================================%
    % Skip
    %==============================================================%
    if exist(save_path, 'file') == 2

        fprintf( ...
            'Figure already exists, skip: %s\n', ...
            save_path);

        return;
    end


    try

        %==========================================================%
        % Figure
        %==========================================================%
        fig = ...
            figure( ...
                'Color', 'w', ...
                'Units', 'normalized', ...
                'Position', ...
                [0.03 0.15 0.94 0.68], ...
                'Name', ...
                figure_title);


        tl = ...
            tiledlayout( ...
                fig, ...
                1, ...
                4, ...
                'TileSpacing', ...
                'compact', ...
                'Padding', ...
                'compact');


        title( ...
            tl, ...
            figure_title, ...
            'Interpreter', ...
            'none', ...
            'FontWeight', ...
            'bold', ...
            'FontSize', ...
            18);


        %==========================================================%
        % 1) Population correlation
        %==========================================================%
        ax1 = ...
            nexttile(tl);


        pop = ...
            get_clean_plane( ...
                D.population_corr, ...
                p);


        if isempty(pop)

            empty_coupling_axis( ...
                ax1, ...
                'Population correlation');

        else

            histogram( ...
                ax1, ...
                pop, ...
                choose_nbins(pop));


            xline( ...
                ax1, ...
                0, ...
                '--k');


            xlim( ...
                ax1, ...
                [-1 1]);


            xlabel( ...
                ax1, ...
                'Correlation');


            ylabel( ...
                ax1, ...
                'Cells');


            title( ...
                ax1, ...
                'Population correlation', ...
                'Interpreter', ...
                'none');


            grid(ax1, 'on');
            box(ax1, 'off');


            text( ...
                ax1, ...
                0.03, ...
                0.95, ...
                sprintf( ...
                    'median = %.3f\nn = %d', ...
                    median( ...
                        pop, ...
                        'omitnan'), ...
                    numel(pop)), ...
                'Units', ...
                'normalized', ...
                'VerticalAlignment', ...
                'top');
        end


        %==========================================================%
        % 2) Observed vs shuffle
        %==========================================================%
        ax2 = ...
            nexttile(tl);


        obs = ...
            get_plane_raw( ...
                D.observed, ...
                p);


        shuf = ...
            get_plane_raw( ...
                D.shuffle, ...
                p);


        [obs, shuf] = ...
            pair_same_cells( ...
                obs, ...
                shuf);


        if isempty(obs)

            empty_coupling_axis( ...
                ax2, ...
                'Observed vs shuffle');

        else

            hold(ax2, 'on');


            for c = 1:numel(obs)

                plot( ...
                    ax2, ...
                    [1 2], ...
                    [obs(c) shuf(c)], ...
                    '-', ...
                    'Color', ...
                    [0.75 0.75 0.75], ...
                    'LineWidth', ...
                    0.8);
            end


            scatter( ...
                ax2, ...
                ones(size(obs)), ...
                obs, ...
                30, ...
                'filled');


            scatter( ...
                ax2, ...
                2 .* ones(size(shuf)), ...
                shuf, ...
                30, ...
                'filled');


            plot( ...
                ax2, ...
                1, ...
                median( ...
                    obs, ...
                    'omitnan'), ...
                'kd', ...
                'MarkerFaceColor', ...
                'k');


            plot( ...
                ax2, ...
                2, ...
                median( ...
                    shuf, ...
                    'omitnan'), ...
                'kd', ...
                'MarkerFaceColor', ...
                'k');


            xticks( ...
                ax2, ...
                [1 2]);


            xticklabels( ...
                ax2, ...
                { ...
                    'Observed', ...
                    'Shuffle' ...
                });


            xlim( ...
                ax2, ...
                [0.5 2.5]);


            set( ...
                ax2, ...
                'TickLabelInterpreter', ...
                'none');


            ylabel( ...
                ax2, ...
                'Active GCaMP fraction');


            title( ...
                ax2, ...
                'Observed vs shuffle', ...
                'Interpreter', ...
                'none');


            grid(ax2, 'on');
            box(ax2, 'off');


            hold(ax2, 'off');
        end


        %==========================================================%
        % 3) Excess coupling
        %==========================================================%
        ax3 = ...
            nexttile(tl);


        exc = ...
            get_clean_plane( ...
                D.excess, ...
                p);


        if isempty(exc)

            empty_coupling_axis( ...
                ax3, ...
                'Excess coupling');

        else

            histogram( ...
                ax3, ...
                exc, ...
                choose_nbins(exc));


            xline( ...
                ax3, ...
                0, ...
                '--k');


            xlabel( ...
                ax3, ...
                'Observed - shuffle');


            ylabel( ...
                ax3, ...
                'Cells');


            title( ...
                ax3, ...
                'Excess coupling', ...
                'Interpreter', ...
                'none');


            grid(ax3, 'on');
            box(ax3, 'off');


            text( ...
                ax3, ...
                0.03, ...
                0.95, ...
                sprintf( ...
                    'median = %.3f\nn = %d', ...
                    median( ...
                        exc, ...
                        'omitnan'), ...
                    numel(exc)), ...
                'Units', ...
                'normalized', ...
                'VerticalAlignment', ...
                'top');
        end


        %==========================================================%
        % 4) Lagged coupling
        %==========================================================%
        ax4 = ...
            nexttile(tl);


        lag = ...
            get_plane_raw( ...
                D.lag_ms, ...
                p);


        lagcorr = ...
            get_plane_raw( ...
                D.max_lagged_corr, ...
                p);


        [lag, lagcorr] = ...
            pair_same_cells( ...
                lag, ...
                lagcorr);


        if isempty(lag)

            empty_coupling_axis( ...
                ax4, ...
                'Lagged coupling');

        else

            scatter( ...
                ax4, ...
                lag, ...
                lagcorr, ...
                35, ...
                'filled', ...
                'MarkerFaceAlpha', ...
                0.65);


            xline( ...
                ax4, ...
                0, ...
                '--k');


            yline( ...
                ax4, ...
                0, ...
                '--k');


            xlabel( ...
                ax4, ...
                'Lag (ms)');


            ylabel( ...
                ax4, ...
                'Maximum correlation');


            ylim( ...
                ax4, ...
                [-1 1]);


            title( ...
                ax4, ...
                'Lagged coupling', ...
                'Interpreter', ...
                'none');


            grid(ax4, 'on');
            box(ax4, 'off');
        end


        %==========================================================%
        % Sauvegarde
        %==========================================================%
        set( ...
            fig, ...
            'WindowState', ...
            'maximized');


        drawnow;


        exportgraphics( ...
            fig, ...
            save_path, ...
            'Resolution', ...
            300);


        fprintf( ...
            'Saved: %s\n', ...
            save_path);


        if isgraphics(fig)
            close(fig);
        end


    catch ME

        fprintf( ...
            '%s | plane %d: %s\n', ...
            figure_title, ...
            plane_number, ...
            ME.message);


        if ~isempty(fig) && ...
                isgraphics(fig)

            close(fig);
        end
    end
end


%==================================================================%
% Figure comparative
%==================================================================%
function create_comparative_coupling_figure( ...
        G, ...
        M, ...
        p, ...
        current_output_folder, ...
        current_line, ...
        current_animal, ...
        current_date, ...
        current_age, ...
        plane_number)

    fig = [];


    %==============================================================%
    % Output
    %==============================================================%
    if isempty(current_output_folder) || ...
            exist( ...
                current_output_folder, ...
                'dir') ~= 7

        fprintf( ...
            ['Comparative coupling | plane %d: ' ...
             'invalid output folder, skip.\n'], ...
            plane_number);

        return;
    end


    %==============================================================%
    % Titre / filename
    %==============================================================%
    figure_title = ...
        'GCaMP vs mTOR functional coupling';


    if isempty(current_line)

        filename = ...
            sprintf( ...
                ['%s_%s_%s_plane%d_' ...
                 'GCaMP_vs_mTOR_functional_coupling.png'], ...
                current_animal, ...
                current_date, ...
                current_age, ...
                plane_number);

    else

        filename = ...
            sprintf( ...
                ['%s_%s_%s_%s_plane%d_' ...
                 'GCaMP_vs_mTOR_functional_coupling.png'], ...
                current_line, ...
                current_animal, ...
                current_date, ...
                current_age, ...
                plane_number);
    end


    save_path = ...
        fullfile( ...
            current_output_folder, ...
            filename);


    if exist(save_path, 'file') == 2

        fprintf( ...
            ['Comparative coupling figure already ' ...
             'exists, skip: %s\n'], ...
            save_path);

        return;
    end


    try

        %==========================================================%
        % Figure
        %==========================================================%
        fig = ...
            figure( ...
                'Color', 'w', ...
                'Units', 'normalized', ...
                'Position', ...
                [0.03 0.15 0.94 0.68], ...
                'Name', ...
                figure_title);


        tl = ...
            tiledlayout( ...
                fig, ...
                1, ...
                4, ...
                'TileSpacing', ...
                'compact', ...
                'Padding', ...
                'compact');


        title( ...
            tl, ...
            figure_title, ...
            'Interpreter', ...
            'none', ...
            'FontWeight', ...
            'bold', ...
            'FontSize', ...
            18);


        %==========================================================%
        % Population correlation
        %==========================================================%
        ax1 = ...
            nexttile(tl);


        plot_two_group_distribution( ...
            ax1, ...
            get_clean_plane( ...
                G.population_corr, ...
                p), ...
            get_clean_plane( ...
                M.population_corr, ...
                p), ...
            'Population correlation', ...
            'Cell-population correlation');


        %==========================================================%
        % Excess coupling
        %==========================================================%
        ax2 = ...
            nexttile(tl);


        plot_two_group_distribution( ...
            ax2, ...
            get_clean_plane( ...
                G.excess, ...
                p), ...
            get_clean_plane( ...
                M.excess, ...
                p), ...
            'Excess coupling', ...
            'Observed - shuffled coupling');


        %==========================================================%
        % Maximum lagged correlation
        %==========================================================%
        ax3 = ...
            nexttile(tl);


        plot_two_group_distribution( ...
            ax3, ...
            get_clean_plane( ...
                G.max_lagged_corr, ...
                p), ...
            get_clean_plane( ...
                M.max_lagged_corr, ...
                p), ...
            'Maximum lagged correlation', ...
            'Maximum correlation');


        ylim( ...
            ax3, ...
            [-1 1]);


        %==========================================================%
        % Lag
        %==========================================================%
        ax4 = ...
            nexttile(tl);


        plot_two_group_distribution( ...
            ax4, ...
            get_clean_plane( ...
                G.lag_ms, ...
                p), ...
            get_clean_plane( ...
                M.lag_ms, ...
                p), ...
            'Lag', ...
            'Lag (ms)');


        yline( ...
            ax4, ...
            0, ...
            '--k', ...
            'HandleVisibility', ...
            'off');


        %==========================================================%
        % Sauvegarde
        %==========================================================%
        set( ...
            fig, ...
            'WindowState', ...
            'maximized');


        drawnow;


        exportgraphics( ...
            fig, ...
            save_path, ...
            'Resolution', ...
            300);


        fprintf( ...
            'Saved: %s\n', ...
            save_path);


        if isgraphics(fig)
            close(fig);
        end


    catch ME

        fprintf( ...
            ['Comparative coupling | plane %d: ' ...
             '%s\n'], ...
            plane_number, ...
            ME.message);


        if ~isempty(fig) && ...
                isgraphics(fig)

            close(fig);
        end
    end
end


%==================================================================%
% Comparaison de deux distributions
%==================================================================%
function plot_two_group_distribution( ...
        ax, ...
        gcamp_gcamp_values, ...
        gcamp_mtor_values, ...
        panel_title, ...
        ylabel_text)

    gcamp_gcamp_values = ...
        clean_numeric_local( ...
            gcamp_gcamp_values);


    gcamp_mtor_values = ...
        clean_numeric_local( ...
            gcamp_mtor_values);


    n_gcamp = ...
        numel(gcamp_gcamp_values);


    n_mtor = ...
        numel(gcamp_mtor_values);


    if n_gcamp == 0 && ...
            n_mtor == 0

        empty_coupling_axis( ...
            ax, ...
            panel_title);

        return;
    end


    hold( ...
        ax, ...
        'on');


    %==============================================================%
    % Données boxplot
    %==============================================================%
    data = [];
    group = [];


    if n_gcamp > 0

        data = ...
            [ ...
                data; ...
                gcamp_gcamp_values(:) ...
            ];


        group = ...
            [ ...
                group; ...
                ones( ...
                    n_gcamp, ...
                    1) ...
            ];
    end


    if n_mtor > 0

        data = ...
            [ ...
                data; ...
                gcamp_mtor_values(:) ...
            ];


        group = ...
            [ ...
                group; ...
                2 .* ones( ...
                    n_mtor, ...
                    1) ...
            ];
    end


    boxplot( ...
        ax, ...
        data, ...
        group, ...
        'Symbol', '', ...
        'Colors', 'k');


    color_gcamp = ...
        [0.20 0.65 0.25];


    color_mtor = ...
        [0.10 0.35 0.90];


    %==============================================================%
    % GCaMP-GCaMP
    %==============================================================%
    if n_gcamp > 0

        jitter = ...
            0.06 .* ...
            randn( ...
                size(gcamp_gcamp_values));


        scatter( ...
            ax, ...
            1 + jitter, ...
            gcamp_gcamp_values, ...
            28, ...
            'filled', ...
            'MarkerFaceColor', ...
            color_gcamp, ...
            'MarkerEdgeColor', ...
            'none', ...
            'MarkerFaceAlpha', ...
            0.55);
    end


    %==============================================================%
    % GCaMP-mTOR
    %==============================================================%
    if n_mtor > 0

        jitter = ...
            0.06 .* ...
            randn( ...
                size(gcamp_mtor_values));


        scatter( ...
            ax, ...
            2 + jitter, ...
            gcamp_mtor_values, ...
            28, ...
            'filled', ...
            'MarkerFaceColor', ...
            color_mtor, ...
            'MarkerEdgeColor', ...
            'none', ...
            'MarkerFaceAlpha', ...
            0.55);
    end


    %==============================================================%
    % Labels
    %==============================================================%
    xticks( ...
        ax, ...
        [1 2]);


    xticklabels( ...
        ax, ...
        { ...
            sprintf( ...
                'GCaMP-GCaMP (n = %d)', ...
                n_gcamp), ...
            sprintf( ...
                'GCaMP-mTOR (n = %d)', ...
                n_mtor) ...
        });


    set( ...
        ax, ...
        'TickLabelInterpreter', ...
        'none');


    xlim( ...
        ax, ...
        [0.5 2.5]);


    ylabel( ...
        ax, ...
        ylabel_text);


    title( ...
        ax, ...
        panel_title, ...
        'Interpreter', ...
        'none');


    grid( ...
        ax, ...
        'on');


    box( ...
        ax, ...
        'off');


    hold( ...
        ax, ...
        'off');
end


%==================================================================%
% Nettoyage numérique
%==================================================================%
function x = clean_numeric_local(x)

    if isempty(x) || ...
            ~(isnumeric(x) || islogical(x))

        x = [];
        return;
    end


    x = ...
        double(x(:));


    x = ...
        x(isfinite(x));
end


%==================================================================%
% Structure standardisée
%==================================================================%
function D = empty_coupling_data()

    D = ...
        struct( ...
            'population_corr', {{}}, ...
            'observed', {{}}, ...
            'shuffle', {{}}, ...
            'excess', {{}}, ...
            'ratio', {{}}, ...
            'max_lagged_corr', {{}}, ...
            'lag_ms', {{}});
end


function D = ...
    normalize_coupling_planes(D)

    fields = ...
        fieldnames(D);


    for i = 1:numel(fields)

        D.(fields{i}) = ...
            normalize_planes_cell( ...
                D.(fields{i}));
    end
end


function nPlanes = ...
    get_nplanes_coupling(D)

    fields = ...
        fieldnames(D);


    nPlanes = ...
        0;


    for i = 1:numel(fields)

        nPlanes = ...
            max( ...
                nPlanes, ...
                numel( ...
                    D.(fields{i})));
    end
end


function tf = ...
    coupling_plane_has_data( ...
        D, ...
        p)

    tf = ...
        has_numeric_plane( ...
            D.population_corr, p) || ...
        has_numeric_plane( ...
            D.observed, p) || ...
        has_numeric_plane( ...
            D.shuffle, p) || ...
        has_numeric_plane( ...
            D.excess, p) || ...
        has_numeric_plane( ...
            D.max_lagged_corr, p) || ...
        has_numeric_plane( ...
            D.lag_ms, p);
end


%==================================================================%
% Extraction
%==================================================================%
function x = ...
    get_recording_field( ...
        S, ...
        field_name, ...
        m)

    x = [];


    if ~isstruct(S) || ...
            ~isfield(S, field_name)

        return;
    end


    all_values = ...
        S.(field_name);


    if isempty(all_values)
        return;
    end


    if iscell(all_values)

        if numel(all_values) >= m

            x = ...
                all_values{m};
        end


    elseif m == 1

        x = ...
            all_values;
    end
end


function planes = ...
    normalize_planes_cell(x)

    if isempty(x)

        planes = {};


    elseif iscell(x)

        planes = ...
            x(:).';


    else

        planes = ...
            {x};
    end
end


function tf = ...
    has_numeric_plane( ...
        planes, ...
        p)

    tf = ...
        false;


    if numel(planes) < p || ...
            isempty(planes{p})

        return;
    end


    x = ...
        planes{p};


    if isnumeric(x) || ...
            islogical(x)

        tf = ...
            any( ...
                isfinite( ...
                    double(x(:))));
    end
end


function x = ...
    get_plane_raw( ...
        planes, ...
        p)

    x = [];


    if numel(planes) < p
        return;
    end


    x = ...
        planes{p};


    if ~(isnumeric(x) || ...
            islogical(x))

        x = [];
        return;
    end


    x = ...
        double(x(:));
end


function x = ...
    get_clean_plane( ...
        planes, ...
        p)

    x = ...
        get_plane_raw( ...
            planes, ...
            p);


    if isempty(x)
        return;
    end


    x = ...
        x(isfinite(x));
end


function [x, y] = ...
    pair_same_cells( ...
        x, ...
        y)

    if isempty(x) || ...
            isempty(y)

        x = [];
        y = [];

        return;
    end


    x = ...
        double(x(:));


    y = ...
        double(y(:));


    n = ...
        min( ...
            numel(x), ...
            numel(y));


    x = ...
        x(1:n);


    y = ...
        y(1:n);


    valid = ...
        isfinite(x) & ...
        isfinite(y);


    x = ...
        x(valid);


    y = ...
        y(valid);
end


%==================================================================%
% Plot helpers
%==================================================================%
function empty_coupling_axis( ...
        ax, ...
        panel_title)

    title( ...
        ax, ...
        panel_title, ...
        'Interpreter', ...
        'none');


    text( ...
        ax, ...
        0.5, ...
        0.5, ...
        'No data', ...
        'HorizontalAlignment', ...
        'center');


    xticks(ax, []);
    yticks(ax, []);


    box(ax, 'off');
end


function nBins = ...
    choose_nbins(x)

    nBins = ...
        min( ...
            20, ...
            max( ...
                5, ...
                ceil( ...
                    sqrt(numel(x)))));
end


%==================================================================%
% Age / date
%==================================================================%
function age_label = ...
    get_age_label( ...
        ages, ...
        m)

    if iscell(ages)

        age_value = ...
            ages{m};

    else

        age_value = ...
            ages(m);
    end


    if isnumeric(age_value) || ...
            islogical(age_value)

        age_label = ...
            sprintf( ...
                'P%d', ...
                round( ...
                    double(age_value)));

    else

        age_txt = ...
            age_value;


        token = ...
            regexp( ...
                age_txt, ...
                '\d+', ...
                'match', ...
                'once');


        if isempty(token)

            age_label = ...
                age_txt;

        else

            age_label = ...
                ['P' token];
        end
    end
end


function date_label = ...
    get_date_label( ...
        dates, ...
        m)

    if iscell(dates)

        date_value = ...
            dates{m};

    else

        date_value = ...
            dates(m);
    end


    if isdatetime(date_value)

        date_label = ...
            datestr( ...
                date_value, ...
                'yyyy-mm-dd');

    else

        date_label = ...
            date_value;
    end
end