function [figs, day_table, animal_table, legend_table] = ...
    plot_selected_groups_overview( ...
        selected_groups, ...
        include_electroporated_cells, ...
        automatic_selection, ...
        output_folders_type)

% PLOT_SELECTED_GROUPS_OVERVIEW
%
% Crée et sauvegarde :
%
%   figs.overview : âges enregistrés et nombre moyen de cellules par animal
%   figs.layers   : profondeur des plans et couches corticales
%   figs.legend   : légende commune des couleurs attribuées aux animaux
%
% Structure attendue :
%
% selected_groups.(type)(k).line
% selected_groups.(type)(k).animal
% selected_groups.(type)(k).dates
% selected_groups.(type)(k).ages
% selected_groups.(type)(k).metadata
% selected_groups.(type)(k).data
%
% output_folders_type :
%
%   output_folders_type{t}
%
% avec une entrée par type dans le même ordre que :
%
%   type_names = fieldnames(selected_groups)
%
% Exemple :
%
%   D:\Imaging\FCD\Summary plots\Pre-selection electroporated cells\Adult
%
% Les figures et tables sont systématiquement recalculées et écrasées.


    %==============================================================%
    % Initialize outputs
    %==============================================================%
    figs = struct( ...
        'overview', struct(), ...
        'layers',   struct(), ...
        'legend',   []);

    day_table = ...
        initialize_day_table();

    animal_table = ...
        initialize_animal_table();

    legend_table = ...
        initialize_legend_table();


    %==============================================================%
    % Input checks
    %==============================================================%
    if nargin < 1 || isempty(selected_groups)

        error( ...
            'selected_groups is empty.');
    end


    if nargin < 2 || ...
            isempty(include_electroporated_cells)

        include_electroporated_cells = ...
            false;
    end


    if nargin < 3 || ...
            isempty(automatic_selection)

        automatic_selection = ...
            false;
    end


    type_names = ...
        fieldnames(selected_groups);


    if nargin < 4 || ...
            isempty(output_folders_type)

        error( ...
            'output_folders_type must be provided.');
    end


    if ~iscell(output_folders_type)

        output_folders_type = ...
            {output_folders_type};
    end


    if numel(output_folders_type) ~= ...
            numel(type_names)

        error( ...
            ['output_folders_type must contain ', ...
             'one output folder per type.']);
    end


    %==============================================================%
    % Vérifier qu'au moins un type est en sélection automatique
    %==============================================================%
    automatic_fields = ...
        fieldnames(automatic_selection);


    has_automatic_selection = ...
        false;


    for i = 1:numel(automatic_fields)

        if automatic_selection.(automatic_fields{i})

            has_automatic_selection = ...
                true;

            break;
        end
    end


    if ~has_automatic_selection

        fprintf( ...
            '[OVERVIEW] Manual selection: overview plots skipped.\n');

        return;
    end


    %==============================================================%
    % Extract data
    %==============================================================%
    for t = 1:numel(type_names)

        current_type = ...
            type_names{t};


        %==========================================================%
        % Seulement les types en sélection automatique
        %==========================================================%
        if ~isfield( ...
                automatic_selection, ...
                current_type)

            warning( ...
                'Missing automatic_selection for type %s.', ...
                current_type);

            continue;
        end


        current_automatic_selection = ...
            automatic_selection.(current_type);


        if ~current_automatic_selection

            fprintf( ...
                '[OVERVIEW] %s: manual selection, skipped.\n', ...
                current_type);

            continue;
        end


        current_groups = ...
            selected_groups.(current_type);


        if isempty(current_groups)

            continue;
        end


        for g = 1:numel(current_groups)

            current_group = ...
                current_groups(g);


            %======================================================%
            % Structure directe
            %======================================================%
            current_line = ...
                current_group.line;


            current_animal = ...
                current_group.animal;


            current_dates = ...
                current_group.dates;


            current_ages = ...
                current_group.ages;


            metadata = ...
                current_group.metadata;


            %======================================================%
            % Data
            %======================================================%
            if ~isfield(current_group, 'data') || ...
                    isempty(current_group.data) || ...
                    ~isstruct(current_group.data)

                fprintf( ...
                    '[OVERVIEW] No data for %s - %s\n', ...
                    current_type, ...
                    string(current_animal));

                continue;
            end


            data = ...
                current_group.data;


            %======================================================%
            % GCaMP
            %======================================================%
            day_table = ...
                extract_branch_counts( ...
                    day_table, ...
                    current_type, ...
                    current_line, ...
                    current_animal, ...
                    current_ages, ...
                    current_dates, ...
                    metadata, ...
                    data, ...
                    'gcamp_plane');


            %======================================================%
            % Electroporated
            %======================================================%
            if include_electroporated_cells

                day_table = ...
                    extract_branch_counts( ...
                        day_table, ...
                        current_type, ...
                        current_line, ...
                        current_animal, ...
                        current_ages, ...
                        current_dates, ...
                        metadata, ...
                        data, ...
                        'electroporated_plane');
            end
        end
    end


    %==============================================================%
    % Check extracted data
    %==============================================================%
    if isempty(day_table)

        warning( ...
            'No valid cell counts were found in selected_groups.');

        return;
    end


    %==============================================================%
    % Summaries and shared legend
    %==============================================================%
    animal_table = ...
        build_animal_summary( ...
            day_table);


    legend_table = ...
        build_animal_legend_table( ...
            day_table);


    %==============================================================%
    % Types réellement présents
    %==============================================================%
    plotted_types = ...
        unique( ...
            string(day_table.Type), ...
            'stable');


    plotted_types = ...
        plotted_types( ...
            strlength(plotted_types) > 0);


    if isempty(plotted_types)

        warning( ...
            'No valid experimental type was found in day_table.');

        return;
    end


    shared_prefix = ...
        char( ...
            strjoin( ...
                plotted_types, ...
                '_'));


    %==============================================================%
    % Overview + layers par type
    %==============================================================%
    for t = 1:numel(plotted_types)

        current_type = ...
            plotted_types(t);


        current_field = ...
            matlab.lang.makeValidName( ...
                char(current_type));


        %----------------------------------------------------------%
        % Retrouver l'index du type dans type_names
        %
        % Nécessaire car plotted_types peut être un sous-ensemble
        % de type_names.
        %----------------------------------------------------------%
        type_index = ...
            find( ...
                strcmpi( ...
                    string(type_names), ...
                    current_type), ...
                1, ...
                'first');


        if isempty(type_index)

            warning( ...
                'No type index found for %s.', ...
                char(current_type));

            continue;
        end


        %----------------------------------------------------------%
        % Output folder du type courant
        %----------------------------------------------------------%
        output_folder = ...
            output_folders_type{type_index};


        if isempty(output_folder)

            warning( ...
                'Empty output folder for type %s.', ...
                char(current_type));

            continue;
        end


        if exist(output_folder, 'dir') ~= 7

            mkdir( ...
                output_folder);
        end


        %----------------------------------------------------------%
        % Tables du type courant
        %----------------------------------------------------------%
        current_day_table = ...
            day_table( ...
                strcmpi( ...
                    string(day_table.Type), ...
                    current_type), ...
                :);


        current_animal_table = ...
            animal_table( ...
                strcmpi( ...
                    string(animal_table.Type), ...
                    current_type), ...
                :);


        %----------------------------------------------------------%
        % File names
        %----------------------------------------------------------%
        overview_filename = ...
            sprintf( ...
                '%s_overview.png', ...
                char(current_type));


        layers_filename = ...
            sprintf( ...
                '%s_layers.png', ...
                char(current_type));


        %==========================================================%
        % Overview
        %==========================================================%
        figs.overview.(current_field) = ...
            plot_combined_overview( ...
                current_day_table, ...
                current_animal_table, ...
                legend_table, ...
                include_electroporated_cells, ...
                current_type);


        save_overview_figure( ...
            figs.overview.(current_field), ...
            output_folder, ...
            overview_filename, ...
            true);


        %==========================================================%
        % Layers
        %==========================================================%
        figs.layers.(current_field) = ...
            plot_selected_groups_layers( ...
                current_day_table, ...
                legend_table, ...
                current_type);


        save_overview_figure( ...
            figs.layers.(current_field), ...
            output_folder, ...
            layers_filename, ...
            true);
    end


    %==============================================================%
    % Shared legend
    %==============================================================%
    legend_filename = ...
        sprintf( ...
            '%s_legend.png', ...
            shared_prefix);


    legend_table_filename = ...
        sprintf( ...
            '%s_legend_table.csv', ...
            shared_prefix);


    %==============================================================%
    % Utiliser le premier output folder valide
    %==============================================================%
    shared_output_folder = ...
        '';


    for t = 1:numel(output_folders_type)

        if ~isempty(output_folders_type{t})

            shared_output_folder = ...
                output_folders_type{t};

            break;
        end
    end


    if isempty(shared_output_folder)

        warning( ...
            'No valid output folder found for shared legend.');

        return;
    end


    if exist(shared_output_folder, 'dir') ~= 7

        mkdir( ...
            shared_output_folder);
    end


    %==============================================================%
    % Shared legend figure
    %==============================================================%
    figs.legend = ...
        plot_selected_groups_legend( ...
            legend_table);


    save_overview_figure( ...
        figs.legend, ...
        shared_output_folder, ...
        legend_filename, ...
        false);


    %==============================================================%
    % Shared legend table
    %==============================================================%
    legend_table_path = ...
        fullfile( ...
            shared_output_folder, ...
            legend_table_filename);


    writetable( ...
        legend_table, ...
        legend_table_path);


    fprintf( ...
        'Legend table saved/updated:\n%s\n', ...
        legend_table_path);


    close all
end


%% ========================================================================
% Extract cell counts for one branch
% =========================================================================
function day_table = ...
    extract_branch_counts( ...
        day_table, ...
        current_type, ...
        current_line, ...
        current_animal, ...
        current_ages, ...
        current_dates, ...
        metadata, ...
        data, ...
        branch_name)

    [planes_by_recording, source_field] = ...
        get_branch_planes( ...
            data, ...
            branch_name);


    if isempty(planes_by_recording)

        fprintf( ...
            '[OVERVIEW] No %s data for %s - %s\n', ...
            branch_name, ...
            current_type, ...
            string(current_animal));

        return;
    end


    n_recordings = ...
        numel(planes_by_recording);


    for m = 1:n_recordings

        current_planes = ...
            planes_by_recording{m};


        if isempty(current_planes)
            continue;
        end


        if ~iscell(current_planes)

            current_planes = ...
                {current_planes};
        end


        %==========================================================%
        % Age et date directement indexés par recording
        %==========================================================%
        if m > numel(current_ages) || ...
                m > numel(current_dates)

            warning( ...
                ['Missing age/date for %s - %s - ', ...
                 'recording %d. Skipping.'], ...
                current_type, ...
                string(current_animal), ...
                m);

            continue;
        end


        age_label = ...
            string( ...
                current_ages{m});


        age_number = ...
            extract_age_number_local( ...
                age_label);


        date_name = ...
            string( ...
                current_dates{m});


        %==========================================================%
        % Plans
        %==========================================================%
        n_planes = ...
            numel(current_planes);


        cells_by_plane = ...
            nan(1, n_planes);


        position_z_by_plane = ...
            nan(1, n_planes);


        for p = 1:n_planes

            current_data = ...
                current_planes{p};


            n_cells = ...
                count_cells_in_plane( ...
                    current_data);


            if isfinite(n_cells)

                cells_by_plane(p) = ...
                    n_cells;
            end


            position_z_by_plane(p) = ...
                get_position_z_for_plane( ...
                    metadata, ...
                    branch_name, ...
                    m, ...
                    p);
        end


        valid_planes = ...
            isfinite(cells_by_plane);


        if ~any(valid_planes)
            continue;
        end


        total_cells_day = ...
            sum( ...
                cells_by_plane(valid_planes), ...
                'omitnan');


        %==========================================================%
        % Une ligne par plan
        %==========================================================%
        for p = 1:n_planes

            if ~isfinite(cells_by_plane(p))
                continue;
            end


            new_row = ...
                table( ...
                    string(current_type), ...
                    string(current_line), ...
                    string(current_animal), ...
                    string(age_label), ...
                    double(age_number), ...
                    string(date_name), ...
                    double(m), ...
                    string(branch_name), ...
                    string(source_field), ...
                    double(p), ...
                    double(position_z_by_plane(p)), ...
                    double(cells_by_plane(p)), ...
                    double(total_cells_day), ...
                    'VariableNames', { ...
                        'Type', ...
                        'Line', ...
                        'Animal', ...
                        'Age', ...
                        'AgeNumber', ...
                        'Date', ...
                        'RecordingIndex', ...
                        'Branch', ...
                        'SourceField', ...
                        'Plane', ...
                        'PositionZ_um', ...
                        'CellsInPlane', ...
                        'TotalCellsDay'});


            day_table = ...
                [ ...
                    day_table; ...
                    new_row ...
                ]; %#ok<AGROW>
        end
    end
end


%% ========================================================================
% Find cellular field for branch
% =========================================================================
function [planes_by_recording, source_field] = ...
    get_branch_planes( ...
        data, ...
        branch_name)

    planes_by_recording = ...
        {};


    source_field = ...
        "";


    if ~isfield(data, branch_name) || ...
            ~isstruct(data.(branch_name))

        return;
    end


    branch = ...
        data.(branch_name);


    switch branch_name

        case 'gcamp_plane'

            candidate_fields = { ...
                'Raster_gcamp_by_plane', ...
                'DF_gcamp_by_plane', ...
                'F_gcamp_by_plane', ...
                'DFF0_gcamp_by_plane'};


        case 'electroporated_plane'

            candidate_fields = { ...
                'Raster_electroporated_by_plane', ...
                'DF_electroporated_by_plane', ...
                'F_electroporated_by_plane', ...
                'DFF0_electroporated_by_plane'};


        otherwise

            candidate_fields = {};
    end


    for f = 1:numel(candidate_fields)

        current_field = ...
            candidate_fields{f};


        if ~isfield(branch, current_field)
            continue;
        end


        current_value = ...
            branch.(current_field);


        if isempty(current_value)
            continue;
        end


        if ~iscell(current_value)

            current_value = ...
                {current_value};
        end


        if contains_nonempty_recording(current_value)

            planes_by_recording = ...
                current_value;


            source_field = ...
                string(current_field);

            return;
        end
    end
end


function tf = ...
    contains_nonempty_recording(values)

    tf = ...
        false;


    for m = 1:numel(values)

        current_value = ...
            values{m};


        if isempty(current_value)
            continue;
        end


        if iscell(current_value)

            for p = 1:numel(current_value)

                if ~isempty(current_value{p})

                    tf = ...
                        true;

                    return;
                end
            end

        else

            tf = ...
                true;

            return;
        end
    end
end


%% ========================================================================
% Count cells
% =========================================================================
function n_cells = ...
    count_cells_in_plane(current_data)

    n_cells = ...
        NaN;


    if isempty(current_data)
        return;
    end


    if istable(current_data)

        n_cells = ...
            height(current_data);

        return;
    end


    if isnumeric(current_data) || ...
            islogical(current_data)

        if ismatrix(current_data)

            n_cells = ...
                size(current_data, 1);
        end

        return;
    end


    if iscell(current_data)

        n_cells = ...
            numel(current_data);
    end
end


%% ========================================================================
% Build animal summary
% =========================================================================
function animal_table = ...
    build_animal_summary(day_table)

    animal_table = ...
        initialize_animal_table();


    if isempty(day_table)
        return;
    end


    session_table = ...
        unique( ...
            day_table(:, { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'Age', ...
                'AgeNumber', ...
                'Date', ...
                'RecordingIndex', ...
                'Branch', ...
                'TotalCellsDay'}), ...
            'rows', ...
            'stable');


    group_keys = ...
        unique( ...
            session_table(:, { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'Branch'}), ...
            'rows', ...
            'stable');


    for i = 1:height(group_keys)

        current_type = ...
            group_keys.Type(i);


        current_line = ...
            group_keys.Line(i);


        current_animal = ...
            group_keys.Animal(i);


        current_branch = ...
            group_keys.Branch(i);


        rows = ...
            session_table.Type == current_type & ...
            session_table.Line == current_line & ...
            session_table.Animal == current_animal & ...
            session_table.Branch == current_branch;


        current_sessions = ...
            session_table(rows, :);


        total_cells = ...
            double( ...
                current_sessions.TotalCellsDay);


        total_cells = ...
            total_cells( ...
                isfinite(total_cells));


        if isempty(total_cells)

            mean_cells = NaN;
            median_cells = NaN;
            min_cells = NaN;
            max_cells = NaN;

        else

            mean_cells = ...
                mean( ...
                    total_cells, ...
                    'omitnan');


            median_cells = ...
                median( ...
                    total_cells, ...
                    'omitnan');


            min_cells = ...
                min(total_cells);


            max_cells = ...
                max(total_cells);
        end


        age_numbers = ...
            double( ...
                current_sessions.AgeNumber);


        age_numbers = ...
            age_numbers( ...
                isfinite(age_numbers));


        if isempty(age_numbers)

            min_age = NaN;
            max_age = NaN;
            unique_ages = "";

        else

            min_age = ...
                min(age_numbers);


            max_age = ...
                max(age_numbers);


            unique_age_values = ...
                unique( ...
                    age_numbers, ...
                    'sorted');


            unique_ages = ...
                strjoin( ...
                    "P" + string(unique_age_values), ...
                    ", ");
        end


        n_recordings = ...
            height(current_sessions);


        valid_dates = ...
            current_sessions.Date;


        valid_dates = ...
            valid_dates( ...
                strlength(valid_dates) > 0);


        if isempty(valid_dates)

            n_days = ...
                n_recordings;

        else

            n_days = ...
                numel( ...
                    unique(valid_dates));
        end


        new_row = ...
            table( ...
                current_type, ...
                current_line, ...
                current_animal, ...
                current_branch, ...
                double(n_recordings), ...
                double(n_days), ...
                double(mean_cells), ...
                double(median_cells), ...
                double(min_cells), ...
                double(max_cells), ...
                double(min_age), ...
                double(max_age), ...
                string(unique_ages), ...
                'VariableNames', { ...
                    'Type', ...
                    'Line', ...
                    'Animal', ...
                    'Branch', ...
                    'NRecordings', ...
                    'NDays', ...
                    'MeanCellsPerDay', ...
                    'MedianCellsPerDay', ...
                    'MinCellsPerDay', ...
                    'MaxCellsPerDay', ...
                    'MinAge', ...
                    'MaxAge', ...
                    'Ages'});


        animal_table = ...
            [ ...
                animal_table; ...
                new_row ...
            ]; %#ok<AGROW>
    end


    animal_table = ...
        sortrows( ...
            animal_table, ...
            { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'Branch' ...
            });
end


%% ========================================================================
% Plot overview
% =========================================================================
function fig = ...
    plot_combined_overview( ...
        day_table, ...
        animal_table, ...
        legend_table, ...
        include_electroporated_cells, ...
        current_type)

    if isempty(day_table)

        fig = [];
        return;
    end


    session_table = ...
        unique( ...
            day_table(:, { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'Age', ...
                'AgeNumber', ...
                'Date', ...
                'RecordingIndex', ...
                'Branch', ...
                'TotalCellsDay'}), ...
            'rows', ...
            'stable');


    session_table.DisplayAnimal = ...
        create_animal_labels( ...
            session_table.Type, ...
            session_table.Line, ...
            session_table.Animal);


    animal_table.DisplayAnimal = ...
        create_animal_labels( ...
            animal_table.Type, ...
            animal_table.Line, ...
            animal_table.Animal);


    animal_labels = ...
        unique( ...
            session_table.DisplayAnimal, ...
            'stable');


    n_animals = ...
        numel(animal_labels);


    if n_animals == 0

        fig = [];
        return;
    end


    %==============================================================%
    % Ages
    %==============================================================%
    finite_ages = ...
        session_table.AgeNumber( ...
            isfinite( ...
                session_table.AgeNumber));


    if isempty(finite_ages)

        age_ticks = ...
            1;


        age_tick_labels = ...
            "";

    else

        min_age = ...
            floor( ...
                min(finite_ages));


        max_age = ...
            ceil( ...
                max(finite_ages));


        age_ticks = ...
            min_age:max_age;


        age_tick_labels = ...
            "P" + string(age_ticks);
    end


    y_positions = ...
        1:n_animals;


    %==============================================================%
    % Cell means
    %==============================================================%
    mean_gcamp = ...
        nan(n_animals, 1);


    mean_mtor = ...
        nan(n_animals, 1);


    for a = 1:n_animals

        current_animal = ...
            animal_labels(a);


        gcamp_rows = ...
            animal_table.DisplayAnimal == current_animal & ...
            animal_table.Branch == "gcamp_plane";


        if any(gcamp_rows)

            values = ...
                animal_table.MeanCellsPerDay(gcamp_rows);


            values = ...
                values( ...
                    isfinite(values));


            if ~isempty(values)

                mean_gcamp(a) = ...
                    values(1);
            end
        end


        electroporated_rows = ...
            animal_table.DisplayAnimal == current_animal & ...
            animal_table.Branch == "electroporated_plane";


        if any(electroporated_rows)

            values = ...
                animal_table.MeanCellsPerDay(electroporated_rows);


            values = ...
                values( ...
                    isfinite(values));


            if ~isempty(values)

                mean_mtor(a) = ...
                    values(1);
            end
        end
    end


    has_mtor_data = ...
        include_electroporated_cells && ...
        any( ...
            isfinite(mean_mtor));


    %==============================================================%
    % Figure
    %==============================================================%
    fig = ...
        figure( ...
            'Color', ...
            'w', ...
            'Name', ...
            'Selected groups overview', ...
            'NumberTitle', ...
            'off', ...
            'Units', ...
            'normalized', ...
            'OuterPosition', ...
            [0 0 1 1]);


    main_ax = ...
        axes( ...
            fig, ...
            'Position', ...
            [0.10 0.17 0.56 0.70]);


    bar_ax = ...
        axes( ...
            fig, ...
            'Position', ...
            [0.72 0.17 0.23 0.70]);


    hold(main_ax, 'on');
    hold(bar_ax, 'on');


    x_limits = ...
        [ ...
            age_ticks(1) - 0.5, ...
            age_ticks(end) + 0.5 ...
        ];


    %==============================================================%
    % Grid
    %==============================================================%
    for y = 0.5:1:(n_animals + 0.5)

        plot( ...
            main_ax, ...
            x_limits, ...
            [y y], ...
            'Color', ...
            [0.82 0.82 0.82], ...
            'LineWidth', ...
            0.8);
    end


    for x = ...
            (age_ticks(1) - 0.5):1: ...
            (age_ticks(end) + 0.5)

        plot( ...
            main_ax, ...
            [x x], ...
            [0.5 n_animals + 0.5], ...
            'Color', ...
            [0.82 0.82 0.82], ...
            'LineWidth', ...
            0.8);
    end


    %==============================================================%
    % Ages
    %==============================================================%
    for a = 1:n_animals

        current_animal = ...
            animal_labels(a);


        rows = ...
            session_table.DisplayAnimal == current_animal;


        ages = ...
            session_table.AgeNumber(rows);


        ages = ...
            unique( ...
                ages(isfinite(ages)), ...
                'sorted');


        if isempty(ages)
            continue;
        end


        animal_color = ...
            get_animal_color( ...
                legend_table, ...
                current_animal);


        scatter( ...
            main_ax, ...
            ages, ...
            repmat( ...
                y_positions(a), ...
                size(ages)), ...
            65, ...
            'filled', ...
            'MarkerFaceColor', ...
            animal_color, ...
            'MarkerEdgeColor', ...
            'k', ...
            'LineWidth', ...
            0.5, ...
            'HandleVisibility', ...
            'off');
    end


    %==============================================================%
    % Bars
    %==============================================================%
    if has_mtor_data

        bar_values = ...
            [ ...
                mean_gcamp, ...
                mean_mtor ...
            ];


        bar_handles = ...
            barh( ...
                bar_ax, ...
                y_positions, ...
                bar_values, ...
                'grouped');


        bar_handles(1).FaceColor = ...
            [0.20 0.70 0.20];


        bar_handles(1).EdgeColor = ...
            'none';


        bar_handles(2).FaceColor = ...
            [0.10 0.40 0.90];


        bar_handles(2).EdgeColor = ...
            'none';


        annotation( ...
            fig, ...
            'rectangle', ...
            [0.70 0.895 0.015 0.018], ...
            'FaceColor', ...
            [0.20 0.70 0.20], ...
            'EdgeColor', ...
            'none');


        annotation( ...
            fig, ...
            'textbox', ...
            [0.717 0.884 0.11 0.04], ...
            'String', ...
            'GCaMP cells', ...
            'EdgeColor', ...
            'none', ...
            'VerticalAlignment', ...
            'middle', ...
            'FontSize', ...
            10);


        annotation( ...
            fig, ...
            'rectangle', ...
            [0.82 0.895 0.015 0.018], ...
            'FaceColor', ...
            [0.10 0.40 0.90], ...
            'EdgeColor', ...
            'none');


        annotation( ...
            fig, ...
            'textbox', ...
            [0.837 0.884 0.15 0.04], ...
            'String', ...
            'mTOR-electroporated cells', ...
            'EdgeColor', ...
            'none', ...
            'VerticalAlignment', ...
            'middle', ...
            'FontSize', ...
            10);

    else

        bar_handles = ...
            barh( ...
                bar_ax, ...
                y_positions, ...
                mean_gcamp, ...
                0.58);


        bar_handles.FaceColor = ...
            [0.20 0.70 0.20];


        bar_handles.EdgeColor = ...
            'none';
    end


    all_values = ...
        [ ...
            mean_gcamp; ...
            mean_mtor ...
        ];


    all_values = ...
        all_values( ...
            isfinite(all_values));


    if isempty(all_values)

        max_value = ...
            1;

    else

        max_value = ...
            max(all_values);


        if max_value <= 0

            max_value = ...
                1;
        end
    end


    text_offset = ...
        max( ...
            1, ...
            0.025 * max_value);


    %==============================================================%
    % Numeric labels
    %==============================================================%
    if has_mtor_data

        for a = 1:n_animals

            if isfinite(mean_gcamp(a))

                text( ...
                    bar_ax, ...
                    mean_gcamp(a) + text_offset, ...
                    y_positions(a) - 0.18, ...
                    sprintf( ...
                        '%.0f', ...
                        mean_gcamp(a)), ...
                    'HorizontalAlignment', ...
                    'left', ...
                    'VerticalAlignment', ...
                    'middle');
            end


            if isfinite(mean_mtor(a))

                text( ...
                    bar_ax, ...
                    mean_mtor(a) + text_offset, ...
                    y_positions(a) + 0.18, ...
                    sprintf( ...
                        '%.0f', ...
                        mean_mtor(a)), ...
                    'HorizontalAlignment', ...
                    'left', ...
                    'VerticalAlignment', ...
                    'middle');
            end
        end

    else

        for a = 1:n_animals

            if isfinite(mean_gcamp(a))

                text( ...
                    bar_ax, ...
                    mean_gcamp(a) + text_offset, ...
                    y_positions(a), ...
                    sprintf( ...
                        '%.0f', ...
                        mean_gcamp(a)), ...
                    'HorizontalAlignment', ...
                    'left', ...
                    'VerticalAlignment', ...
                    'middle');
            end
        end
    end


    %==============================================================%
    % Axes
    %==============================================================%
    xlim( ...
        main_ax, ...
        x_limits);


    ylim( ...
        main_ax, ...
        [0.5 n_animals + 0.5]);


    main_ax.XTick = ...
        age_ticks;


    main_ax.XTickLabel = ...
        age_tick_labels;


    main_ax.YTick = ...
        1:n_animals;


    main_ax.YTickLabel = ...
        animal_labels;


    main_ax.YDir = ...
        'reverse';


    xlabel( ...
        main_ax, ...
        'Postnatal age');


    ylabel( ...
        main_ax, ...
        'Mouse');


    ylim( ...
        bar_ax, ...
        [0.5 n_animals + 0.5]);


    bar_ax.YTick = ...
        1:n_animals;


    bar_ax.YTickLabel = ...
        {};


    bar_ax.YDir = ...
        'reverse';


    xlim( ...
        bar_ax, ...
        [0 max_value * 1.30]);


    xlabel( ...
        bar_ax, ...
        'Mean number of cells per day');


    title( ...
        bar_ax, ...
        'N cells');


    annotation( ...
        fig, ...
        'textbox', ...
        [0.10 0.92 0.85 0.05], ...
        'String', ...
        sprintf( ...
            '%s overview', ...
            char(current_type)), ...
        'EdgeColor', ...
        'none', ...
        'HorizontalAlignment', ...
        'center', ...
        'FontWeight', ...
        'bold', ...
        'FontSize', ...
        14);


    hold(main_ax, 'off');
    hold(bar_ax, 'off');
end


%% ========================================================================
% Animal labels
% =========================================================================
function labels = ...
    create_animal_labels( ...
        types, ...
        lines, ...
        animals)

    types = ...
        string(types);


    lines = ...
        string(lines);


    animals = ...
        string(animals);


    labels = ...
        animals;


    has_line = ...
        strlength( ...
            strtrim(lines)) > 0;


    labels(has_line) = ...
        strtrim(lines(has_line)) + ...
        "_" + ...
        strtrim(animals(has_line));


    unique_labels = ...
        unique(labels);


    for i = 1:numel(unique_labels)

        rows = ...
            labels == unique_labels(i);


        associated_types = ...
            unique( ...
                types(rows));


        if numel(associated_types) > 1

            labels(rows) = ...
                types(rows) + ...
                " - " + ...
                labels(rows);
        end
    end
end


%% ========================================================================
% Extract age number
% =========================================================================
function age_number = ...
    extract_age_number_local(age_label)

    age_number = ...
        NaN;


    token = ...
        regexp( ...
            char(string(age_label)), ...
            '[-+]?\d*\.?\d+', ...
            'match', ...
            'once');


    if ~isempty(token)

        age_number = ...
            str2double(token);
    end
end


%% ========================================================================
% Initialize tables
% =========================================================================
function day_table = ...
    initialize_day_table()

    day_table = ...
        table( ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            'VariableNames', { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'Age', ...
                'AgeNumber', ...
                'Date', ...
                'RecordingIndex', ...
                'Branch', ...
                'SourceField', ...
                'Plane', ...
                'PositionZ_um', ...
                'CellsInPlane', ...
                'TotalCellsDay'});
end


function animal_table = ...
    initialize_animal_table()

    animal_table = ...
        table( ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            'VariableNames', { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'Branch', ...
                'NRecordings', ...
                'NDays', ...
                'MeanCellsPerDay', ...
                'MedianCellsPerDay', ...
                'MinCellsPerDay', ...
                'MaxCellsPerDay', ...
                'MinAge', ...
                'MaxAge', ...
                'Ages'});
end


%% ========================================================================
% Position Z
% =========================================================================
function z = ...
    get_position_z_for_plane( ...
        metadata, ...
        branch_name, ...
        recording_index, ...
        plane_index)

    z = ...
        NaN;


    if ~isfield(metadata, branch_name)
        return;
    end


    branch = ...
        metadata.(branch_name);


    if ~isfield(branch, 'PositionZ') || ...
            isempty(branch.PositionZ)

        return;
    end


    if numel(branch.PositionZ) < recording_index
        return;
    end


    raw = ...
        branch.PositionZ{recording_index};


    z = ...
        extract_position_z_plane_local( ...
            raw, ...
            plane_index);
end


function z = ...
    extract_position_z_plane_local( ...
        raw, ...
        plane_index)

    z = ...
        NaN;


    if isempty(raw)
        return;
    end


    if iscell(raw)

        if numel(raw) >= plane_index

            raw = ...
                raw{plane_index};

        elseif isscalar(raw)

            raw = ...
                raw{1};

        else

            return;
        end
    end


    if isnumeric(raw) || ...
            islogical(raw)

        values = ...
            double(raw(:));


        values = ...
            values(isfinite(values));


        if numel(values) >= plane_index

            z = ...
                values(plane_index);

        elseif numel(values) == 1 && ...
                plane_index == 1

            z = ...
                values(1);
        end

        return;
    end


    tokens = ...
        regexp( ...
            char(string(raw)), ...
            '[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?', ...
            'match');


    values = ...
        str2double(tokens);


    values = ...
        values(isfinite(values));


    if numel(values) >= plane_index

        z = ...
            values(plane_index);
    end
end


%% ========================================================================
% Legend table
% =========================================================================
function legend_table = ...
    build_animal_legend_table(day_table)

    legend_table = ...
        initialize_legend_table();


    display_labels = ...
        create_animal_labels( ...
            day_table.Type, ...
            day_table.Line, ...
            day_table.Animal);


    source_table = ...
        table( ...
            string(day_table.Type), ...
            string(day_table.Line), ...
            string(day_table.Animal), ...
            string(display_labels), ...
            double(day_table.AgeNumber), ...
            'VariableNames', { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'DisplayAnimal', ...
                'AgeNumber'});


    animal_keys = ...
        unique( ...
            source_table(:, { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'DisplayAnimal'}), ...
            'rows', ...
            'stable');


    animal_keys = ...
        sort_animal_legend_keys( ...
            animal_keys);


    colors = ...
        generate_unique_animal_colors( ...
            height(animal_keys));


    for i = 1:height(animal_keys)

        rows = ...
            source_table.Type == animal_keys.Type(i) & ...
            source_table.Line == animal_keys.Line(i) & ...
            source_table.Animal == animal_keys.Animal(i);


        ages = ...
            unique( ...
                source_table.AgeNumber(rows));


        ages = ...
            ages(isfinite(ages));


        if isempty(ages)

            age_min = NaN;
            age_max = NaN;
            age_text = "";

        else

            age_min = ...
                min(ages);


            age_max = ...
                max(ages);


            age_text = ...
                strjoin( ...
                    "P" + string(ages), ...
                    ", ");
        end


        new_row = ...
            table( ...
                string(animal_keys.Type(i)), ...
                string(animal_keys.Line(i)), ...
                string(animal_keys.Animal(i)), ...
                string(animal_keys.DisplayAnimal(i)), ...
                double(i), ...
                colors(i,1), ...
                colors(i,2), ...
                colors(i,3), ...
                age_min, ...
                age_max, ...
                age_text, ...
                'VariableNames', ...
                legend_table.Properties.VariableNames);


        legend_table = ...
            [ ...
                legend_table; ...
                new_row ...
            ]; %#ok<AGROW>
    end
end


function animal_keys = ...
    sort_animal_legend_keys(animal_keys)

    preferred_order = ...
        [ ...
            "WT", ...
            "SHAM", ...
            "FCD" ...
        ];


    rank = ...
        nan(height(animal_keys),1);


    for i = 1:height(animal_keys)

        idx = ...
            find( ...
                strcmpi( ...
                    preferred_order, ...
                    string(animal_keys.Type(i))), ...
                1);


        if isempty(idx)

            rank(i) = ...
                numel(preferred_order) + 1;

        else

            rank(i) = ...
                idx;
        end
    end


    animal_keys.rank_tmp = ...
        rank;


    animal_keys = ...
        sortrows( ...
            animal_keys, ...
            { ...
                'rank_tmp', ...
                'Type', ...
                'Line', ...
                'Animal' ...
            });


    animal_keys.rank_tmp = [];
end


function colors = ...
    generate_unique_animal_colors(n)

    if n == 0

        colors = ...
            zeros(0,3);

        return;
    end


    if n == 1

        colors = ...
            [0 0.45 0.74];

        return;
    end


    palette = ...
        turbo(n + 2);


    colors = ...
        palette(2:end-1,:);
end


function color = ...
    get_animal_color( ...
        legend_table, ...
        display_animal)

    row = ...
        find( ...
            legend_table.DisplayAnimal == ...
            string(display_animal), ...
            1);


    if isempty(row)

        color = ...
            [0.45 0.45 0.45];

    else

        color = ...
            [ ...
                legend_table.Red(row), ...
                legend_table.Green(row), ...
                legend_table.Blue(row) ...
            ];
    end
end


function legend_table = ...
    initialize_legend_table()

    legend_table = ...
        table( ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            'VariableNames', { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'DisplayAnimal', ...
                'ColorIndex', ...
                'Red', ...
                'Green', ...
                'Blue', ...
                'AgeMin', ...
                'AgeMax', ...
                'Ages'});
end


%% ========================================================================
% Layers
% =========================================================================
function fig = ...
    plot_selected_groups_layers( ...
        day_table, ...
        legend_table, ...
        current_type)

    fig = [];


    layer_table = ...
        unique( ...
            day_table(:, { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'Age', ...
                'AgeNumber', ...
                'Date', ...
                'RecordingIndex', ...
                'Plane', ...
                'PositionZ_um'}), ...
            'rows', ...
            'stable');


    layer_table = ...
        layer_table( ...
            isfinite(layer_table.AgeNumber) & ...
            isfinite(layer_table.PositionZ_um), ...
            :);


    if isempty(layer_table)
        return;
    end


    layer_table.DisplayAnimal = ...
        create_animal_labels( ...
            layer_table.Type, ...
            layer_table.Line, ...
            layer_table.Animal);


    min_age = ...
        floor( ...
            min(layer_table.AgeNumber));


    max_age = ...
        ceil( ...
            max(layer_table.AgeNumber));


    age_ticks = ...
        min_age:max_age;


    x_limits = ...
        [ ...
            min_age - 0.65, ...
            max_age + 0.65 ...
        ];


    fig = ...
        figure( ...
            'Color', ...
            'w', ...
            'Units', ...
            'normalized', ...
            'OuterPosition', ...
            [0 0 1 1]);


    ax = ...
        axes( ...
            fig, ...
            'Position', ...
            [0.08 0.13 0.88 0.78]);


    hold(ax, 'on');


    layer_defs = { ...
        'I',       0,  80; ...
        'II/III', 80, 300; ...
        'IV',    300, 450};


    layer_colors = ...
        [ ...
            0.97 0.97 0.97; ...
            0.91 0.91 0.91; ...
            0.85 0.85 0.85 ...
        ];


    for l = 1:size(layer_defs,1)

        z_min = ...
            layer_defs{l,2};


        z_max = ...
            layer_defs{l,3};


        patch( ...
            ax, ...
            [ ...
                x_limits(1), ...
                x_limits(2), ...
                x_limits(2), ...
                x_limits(1) ...
            ], ...
            [ ...
                z_min, ...
                z_min, ...
                z_max, ...
                z_max ...
            ], ...
            layer_colors(l,:), ...
            'EdgeColor', ...
            'none', ...
            'HandleVisibility', ...
            'off');


        yline( ...
            ax, ...
            z_min, ...
            '--k', ...
            'HandleVisibility', ...
            'off');


        text( ...
            ax, ...
            x_limits(1) + 0.04, ...
            mean([z_min z_max]), ...
            layer_defs{l,1}, ...
            'FontWeight', ...
            'bold');
    end


    yline( ...
        ax, ...
        layer_defs{end,3}, ...
        '--k', ...
        'HandleVisibility', ...
        'off');


    animals = ...
        unique( ...
            layer_table.DisplayAnimal, ...
            'stable');


    for a = 1:numel(animals)

        rows = ...
            layer_table.DisplayAnimal == animals(a);


        color = ...
            get_animal_color( ...
                legend_table, ...
                animals(a));


        rng(a, 'twister');


        jitter = ...
            ( ...
                rand( ...
                    sum(rows), ...
                    1) - 0.5 ...
            ) * 0.20;


        scatter( ...
            ax, ...
            layer_table.AgeNumber(rows) + jitter, ...
            layer_table.PositionZ_um(rows), ...
            75, ...
            'filled', ...
            'MarkerFaceColor', ...
            color, ...
            'MarkerEdgeColor', ...
            'k');
    end


    xlim( ...
        ax, ...
        x_limits);


    ylim( ...
        ax, ...
        [0 450]);


    ax.YDir = ...
        'reverse';


    ax.XTick = ...
        age_ticks;


    ax.XTickLabel = ...
        "P" + string(age_ticks);


    xlabel( ...
        ax, ...
        'Postnatal age');


    ylabel( ...
        ax, ...
        'Cortical depth (\mum)');


    title( ...
        ax, ...
        sprintf( ...
            '%s - recording depth by age and animal', ...
            char(current_type)));


    hold(ax, 'off');
end


%% ========================================================================
% Shared legend
% =========================================================================
function fig = ...
    plot_selected_groups_legend(legend_table)

    if isempty(legend_table)

        fig = [];
        return;
    end


    n = ...
        height(legend_table);


    fig = ...
        figure( ...
            'Color', ...
            'w', ...
            'Position', ...
            [ ...
                200, ...
                150, ...
                1000, ...
                max(280, 80 + 42*n) ...
            ]);


    ax = ...
        axes( ...
            fig, ...
            'Position', ...
            [0.04 0.07 0.92 0.86]);


    hold(ax, 'on');


    for i = 1:n

        y = ...
            n - i + 1;


        color = ...
            [ ...
                legend_table.Red(i), ...
                legend_table.Green(i), ...
                legend_table.Blue(i) ...
            ];


        scatter( ...
            ax, ...
            1, ...
            y, ...
            110, ...
            'filled', ...
            'MarkerFaceColor', ...
            color, ...
            'MarkerEdgeColor', ...
            'k');


        text( ...
            ax, ...
            1.18, ...
            y, ...
            sprintf( ...
                '%s | Type: %s | Ages: %s', ...
                legend_table.DisplayAnimal(i), ...
                legend_table.Type(i), ...
                legend_table.Ages(i)), ...
            'Interpreter', ...
            'none');
    end


    xlim( ...
        ax, ...
        [0.8 7]);


    ylim( ...
        ax, ...
        [0 n+1]);


    axis( ...
        ax, ...
        'off');


    title( ...
        ax, ...
        'Animal color legend');


    hold(ax, 'off');
end


%% ========================================================================
% Save figure
% =========================================================================
function save_overview_figure( ...
        fig, ...
        output_folder, ...
        filename, ...
        maximize_figure)

    if isempty(fig) || ...
            ~ishghandle(fig)

        return;
    end


    if exist(output_folder, 'dir') ~= 7

        mkdir( ...
            output_folder);
    end


    if maximize_figure

        set( ...
            fig, ...
            'Units', ...
            'normalized', ...
            'OuterPosition', ...
            [0 0 1 1]);
    end


    drawnow;


    output_path = ...
        fullfile( ...
            output_folder, ...
            filename);


    try

        exportgraphics( ...
            fig, ...
            output_path, ...
            'Resolution', ...
            300);

    catch ME

        warning( ...
            'exportgraphics failed (%s). saveas used instead.', ...
            ME.message);


        saveas( ...
            fig, ...
            output_path);
    end


    fprintf( ...
        'Figure saved/updated:\n%s\n', ...
        output_path);
end