function plot_radar_metrics_by_type( ...
        selected_groups, ...
        include_electroporated, ...
        type_names, ...
        automatic_selection, ...
        output_folders)

    %==============================================================%
    % Automatic selection only
    %==============================================================%
    if ~any(automatic_selection)
        return;
    end

    %==============================================================%
    % Collect metrics
    %==============================================================%
    [ ...
        grouped_by_type, ...
        ages_by_type, ...
        valid_type_names ...
    ] = ...
        collect_basic_metrics_by_type( ...
            selected_groups, ...
            include_electroporated);

    if isempty(valid_type_names)
        return;
    end

    %==============================================================%
    % Normalisation
    %==============================================================%
    if numel(valid_type_names) > 1

        global_maxima = ...
            compute_global_radar_maxima( ...
                grouped_by_type, ...
                valid_type_names);

        normalization_label = ...
            sprintf( ...
                'Normalization across %s', ...
                strjoin( ...
                    valid_type_names, ...
                    ' & '));

        types_filename_prefix = ...
            strjoin( ...
                valid_type_names, ...
                '_');

    else

        global_maxima = ...
            [];

        normalization_label = ...
            sprintf( ...
                'Normalization within %s', ...
                valid_type_names{1});

        types_filename_prefix = ...
            valid_type_names{1};
    end

    %==============================================================%
    % Radar per type
    %==============================================================%
    for t = 1:numel(type_names)

        current_type = ...
            type_names{t};

        current_automatic_selection = ...
            automatic_selection(t);

        if ~current_automatic_selection
            continue;
        end

        if ~isfield( ...
                grouped_by_type, ...
                current_type)

            continue;
        end

        if t > numel(output_folders) || ...
                isempty(output_folders{t})

            warning( ...
                'Missing output folder for type: %s', ...
                current_type);

            continue;
        end

        current_output_folder = ...
            output_folders{t};

        if exist( ...
                current_output_folder, ...
                'dir') ~= 7

            mkdir( ...
                current_output_folder);
        end

        make_all_metrics_figures_by_age( ...
            grouped_by_type.(current_type), ...
            ages_by_type.(current_type), ...
            current_output_folder, ...
            current_type, ...
            global_maxima, ...
            normalization_label, ...
            types_filename_prefix);
    end
end