function plot_all_pairwise_corr_types( ...
    current_ages_group, ...
    results_analysis, ...
    gcamp_root_folders, ...
    animal_name)

    numFolders = numel(gcamp_root_folders);

    for m = 1:numFolders

        fig = [];

        try

            %======================================================%
            % Age + chemin de sauvegarde
            %======================================================%
            if m <= numel(current_ages_group) && ...
                    ~isempty(current_ages_group{m})

                ageLabel = ...
                    normalize_age_label( ...
                        current_ages_group{m});

            else

                ageLabel = ...
                    sprintf('sess%d', m);
            end


            file_name = ...
                sprintf( ...
                    'Corr_ALL_hist_heatmap_%s_%s_m%d.png', ...
                    char(string(animal_name)), ...
                    ageLabel, ...
                    m);

            save_path = ...
                fullfile( ...
                    gcamp_root_folders{m}, ...
                    file_name);


            %======================================================%
            % Skip si déjà existant
            %======================================================%
            if exist(save_path, 'file') == 2

                fprintf( ...
                    'm=%d: figure déjà existante, skip: %s\n', ...
                    m, ...
                    save_path);

                continue;
            end


            %======================================================%
            % Matrices complètes de corrélation
            %======================================================%

            %------------------------------------------------------%
            % GCaMP-GCaMP
            %------------------------------------------------------%
            corr_gg = ...
                get_results_corr_safe( ...
                    results_analysis, ...
                    { ...
                        'gcamp_plane', ...
                        'correlations', ...
                        'cross_corr_gcamp_gcamp_by_plane' ...
                    }, ...
                    m);


            %------------------------------------------------------%
            % GCaMP-mTOR
            %------------------------------------------------------%
            corr_gm = ...
                get_results_corr_safe( ...
                    results_analysis, ...
                    { ...
                        'electroporated_plane', ...
                        'correlations', ...
                        'cross_corr_gcamp_mtor_by_plane' ...
                    }, ...
                    m);


            %------------------------------------------------------%
            % mTOR-mTOR
            %------------------------------------------------------%
            corr_mm = ...
                get_results_corr_safe( ...
                    results_analysis, ...
                    { ...
                        'electroporated_plane', ...
                        'correlations', ...
                        'cross_corr_mtor_mtor_by_plane' ...
                    }, ...
                    m);


            %======================================================%
            % GCaMP-GCaMP obligatoire
            %======================================================%
            if isempty(corr_gg)

                fprintf( ...
                    'm=%d: pas de données GCaMP-GCaMP, skip.\n', ...
                    m);

                continue;
            end


            %======================================================%
            % Normaliser en cell par plan
            %======================================================%
            if ~iscell(corr_gg)
                corr_gg = {corr_gg};
            end

            if ~iscell(corr_gm)
                corr_gm = {corr_gm};
            end

            if ~iscell(corr_mm)
                corr_mm = {corr_mm};
            end


            nPlanes = ...
                max( ...
                    [ ...
                        numel(corr_gg), ...
                        numel(corr_gm), ...
                        numel(corr_mm) ...
                    ]);


            %======================================================%
            % Construire liste des plots
            %======================================================%
            plot_list = {};


            for p = 1:nPlanes

                plane_number = ...
                    p - 1;


                %--------------------------------------------------%
                % GCaMP-GCaMP
                %--------------------------------------------------%
                if has_valid_corr(corr_gg, p)

                    plot_list{end + 1} = { ...
                        @plot_corr_hist, ...
                        corr_gg, ...
                        p, ...
                        sprintf( ...
                            'GCaMP-GCaMP (plane %d)', ...
                            plane_number) ...
                        }; %#ok<AGROW>

                    plot_list{end + 1} = { ...
                        @plot_corr_heatmap, ...
                        corr_gg, ...
                        p, ...
                        sprintf( ...
                            'GCaMP-GCaMP (plane %d)', ...
                            plane_number) ...
                        }; %#ok<AGROW>
                end


                %--------------------------------------------------%
                % GCaMP-mTOR
                %--------------------------------------------------%
                if has_valid_corr(corr_gm, p)

                    plot_list{end + 1} = { ...
                        @plot_corr_hist, ...
                        corr_gm, ...
                        p, ...
                        sprintf( ...
                            'GCaMP-mTOR (plane %d)', ...
                            plane_number) ...
                        }; %#ok<AGROW>

                    plot_list{end + 1} = { ...
                        @plot_corr_heatmap, ...
                        corr_gm, ...
                        p, ...
                        sprintf( ...
                            'GCaMP-mTOR (plane %d)', ...
                            plane_number) ...
                        }; %#ok<AGROW>
                end


                %--------------------------------------------------%
                % mTOR-mTOR
                %--------------------------------------------------%
                if has_valid_corr(corr_mm, p)

                    plot_list{end + 1} = { ...
                        @plot_corr_hist, ...
                        corr_mm, ...
                        p, ...
                        sprintf( ...
                            'mTOR-mTOR (plane %d)', ...
                            plane_number) ...
                        }; %#ok<AGROW>

                    plot_list{end + 1} = { ...
                        @plot_corr_heatmap, ...
                        corr_mm, ...
                        p, ...
                        sprintf( ...
                            'mTOR-mTOR (plane %d)', ...
                            plane_number) ...
                        }; %#ok<AGROW>
                end
            end


            nPlots = ...
                numel(plot_list);


            if nPlots == 0

                fprintf( ...
                    'm=%d: aucun plot valide.\n', ...
                    m);

                continue;
            end


            %======================================================%
            % Layout dynamique
            %======================================================%
            nCols = 2;

            nRows = ...
                ceil(nPlots / nCols);


            fig = ...
                figure( ...
                    'Color', 'w', ...
                    'Units', 'normalized', ...
                    'Position', [0.03 0.03 0.94 0.90]);


            tl = ...
                tiledlayout( ...
                    fig, ...
                    nRows, ...
                    nCols, ...
                    'TileSpacing', 'compact', ...
                    'Padding', 'compact');


            title( ...
                tl, ...
                sprintf( ...
                    '%s | %s', ...
                    char(string(animal_name)), ...
                    ageLabel), ...
                'Interpreter', 'none', ...
                'FontWeight', 'bold');


            %======================================================%
            % Tracés
            %======================================================%
            for i = 1:nPlots

                ax = ...
                    nexttile(tl);

                f = ...
                    plot_list{i};

                f{1}( ...
                    ax, ...
                    f{2}, ...
                    f{3}, ...
                    f{4});
            end


            %======================================================%
            % Sauvegarde
            %======================================================%
            exportgraphics( ...
                fig, ...
                save_path, ...
                'Resolution', 300);


            if ishghandle(fig)
                close(fig);
            end


            fprintf( ...
                'Saved: %s\n', ...
                save_path);


        catch ME

            fprintf( ...
                'Erreur m=%d: %s\n', ...
                m, ...
                ME.message);


            if ~isempty(fig) && ...
                    ishghandle(fig)

                close(fig);
            end
        end
    end
end


function plot_corr_hist( ...
    ax, ...
    corr_cell, ...
    p, ...
    panelTitle)

    if isempty(corr_cell) || ...
            numel(corr_cell) < p

        text( ...
            ax, ...
            0.5, ...
            0.5, ...
            'no data', ...
            'HorizontalAlignment', 'center');

        axis(ax, 'off');
        return;
    end


    V = ...
        corr_cell{p};


    if isempty(V)

        text( ...
            ax, ...
            0.5, ...
            0.5, ...
            'empty', ...
            'HorizontalAlignment', 'center');

        axis(ax, 'off');
        return;
    end


    v = ...
        corr_to_unique_pairs(V);


    if isempty(v)

        text( ...
            ax, ...
            0.5, ...
            0.5, ...
            'empty distribution', ...
            'HorizontalAlignment', 'center');

        axis(ax, 'off');
        return;
    end


    histogram( ...
        ax, ...
        v, ...
        50);


    xlabel( ...
        ax, ...
        'Correlation');


    ylabel( ...
        ax, ...
        'Count');


    title( ...
        ax, ...
        ['Histogram - ' panelTitle], ...
        'Interpreter', 'none');


    xlim( ...
        ax, ...
        [-1 1]);


    grid( ...
        ax, ...
        'on');


    box( ...
        ax, ...
        'off');
end


function plot_corr_heatmap( ...
    ax, ...
    corr_cell, ...
    p, ...
    panelTitle)

    if isempty(corr_cell) || ...
            numel(corr_cell) < p

        text( ...
            ax, ...
            0.5, ...
            0.5, ...
            'no data', ...
            'HorizontalAlignment', 'center');

        axis(ax, 'off');
        return;
    end


    V = ...
        corr_cell{p};


    if isempty(V)

        text( ...
            ax, ...
            0.5, ...
            0.5, ...
            'empty', ...
            'HorizontalAlignment', 'center');

        axis(ax, 'off');
        return;
    end


    if ~isnumeric(V) || ...
            ~ismatrix(V)

        text( ...
            ax, ...
            0.5, ...
            0.5, ...
            'not a matrix', ...
            'HorizontalAlignment', 'center');

        axis(ax, 'off');
        return;
    end


    imagesc( ...
        ax, ...
        V);


    axis( ...
        ax, ...
        'image');


    colormap( ...
        ax, ...
        parula);


    clim( ...
        ax, ...
        [-1 1]);


    colorbar(ax);


    title( ...
        ax, ...
        ['Heatmap - ' panelTitle], ...
        'Interpreter', 'none');


    xlabel( ...
        ax, ...
        'Cell');


    ylabel( ...
        ax, ...
        'Cell');
end


function v_vec = corr_to_unique_pairs(v)

    if isempty(v)

        v_vec = [];
        return;
    end


    if ~isnumeric(v)

        v_vec = [];
        return;
    end


    if ismatrix(v)

        %----------------------------------------------------------%
        % Matrice carrée :
        % prendre uniquement triangle supérieur
        % pour ne pas compter deux fois les mêmes paires
        %----------------------------------------------------------%
        if size(v, 1) == size(v, 2)

            mask = ...
                triu( ...
                    true(size(v)), ...
                    1);

            v_vec = ...
                v(mask);

        %----------------------------------------------------------%
        % Matrice rectangulaire GCaMP-mTOR :
        % toutes les paires sont uniques
        %----------------------------------------------------------%
        else

            v_vec = ...
                v(:);
        end

    else

        v_vec = ...
            v(:);
    end


    v_vec = ...
        v_vec( ...
            isfinite(v_vec));
end


function ageLabel = normalize_age_label(ageStr)

    ageStr = ...
        char(string(ageStr));

    ageStr = ...
        strtrim(ageStr);


    tok = ...
        regexp( ...
            ageStr, ...
            '\d+', ...
            'match', ...
            'once');


    if isempty(tok)

        ageLabel = ...
            ageStr;

    else

        ageLabel = ...
            ['P' tok];
    end
end


function tf = has_valid_corr( ...
    corr_cell, ...
    p)

    tf = ...
        false;


    if isempty(corr_cell) || ...
            numel(corr_cell) < p

        return;
    end


    V = ...
        corr_cell{p};


    if isempty(V)
        return;
    end


    if isnumeric(V) && ...
            ismatrix(V)

        tf = ...
            any( ...
                isfinite(V(:)));
    end
end


function val = get_results_corr_safe( ...
    results_analysis, ...
    path_fields, ...
    idx)

    val = [];


    if isempty(results_analysis) || ...
            ~isstruct(results_analysis)

        return;
    end


    current = ...
        results_analysis;


    for i = 1:numel(path_fields)

        fn = ...
            path_fields{i};


        if ~isstruct(current) || ...
                ~isfield(current, fn)

            return;
        end


        current = ...
            current.(fn);
    end


    if iscell(current)

        if numel(current) >= idx

            val = ...
                current{idx};
        end

    else

        val = ...
            current;
    end
end