function plot_representative_gcamp_blue_traces( ...
        animal_struct, ...
        current_type, ...
        current_output_folder)

% PLOT_RASTER_MEAN_GCAMP_BLUE_WINDOW
%
% Affiche des traces représentatives de cellules :
%   - non électroporées : vert
%   - électroporées     : bleu
%
% Les pics détectés sont affichés par des astérisques rouges.
% L'identifiant original de chaque cellule est récupéré depuis
% valid_combined_cells_by_plane.
%
% La fonction parcourt automatiquement :
%   - tous les recordings de l'animal ;
%   - tous les plans disponibles.
%
% Sauvegarde :
%
%   line_animal_date_age_planeX_representative_single_cell_traces.png
%
% Si la figure existe déjà, elle n'est ni recréée ni sauvegardée.


    %==============================================================%
    % Vérifications générales
    %==============================================================%
    if ~isfield(animal_struct, 'data') || ...
            isempty(animal_struct.data)

        warning( ...
            'No data found for animal %s.', ...
            char(string(animal_struct.animal)));

        return;
    end

    data = animal_struct.data;

    if ~isfield(data, 'combined_plane') || ...
            isempty(data.combined_plane)

        warning( ...
            '%s - %s: no combined_plane data.', ...
            current_type, ...
            char(string(animal_struct.animal)));

        return;
    end


    %==============================================================%
    % Informations animal
    %==============================================================%
    if isfield(animal_struct, 'animal')
        current_animal = animal_struct.animal;
    else
        current_animal = '';
    end

    if isfield(animal_struct, 'line')
        current_line = animal_struct.line;
    else
        current_line = '';
    end

    if isfield(animal_struct, 'dates')
        current_dates = animal_struct.dates(:);
    else
        current_dates = [];
    end

    if isfield(animal_struct, 'ages')
        current_ages = animal_struct.ages(:);
    else
        current_ages = [];
    end

    current_animal = ...
        char(string(current_animal));

    current_line = ...
        char(string(current_line));


    %==============================================================%
    % Sampling rates
    %==============================================================%
    if ~isfield(animal_struct, 'metadata') || ...
            isempty(animal_struct.metadata)

        warning( ...
            '%s - %s: metadata missing.', ...
            current_type, ...
            current_animal);

        return;
    end

    metadata = animal_struct.metadata;

    if ~isfield(metadata, 'SamplingRatePlane') || ...
            isempty(metadata.SamplingRatePlane)

        warning( ...
            '%s - %s: SamplingRatePlane missing from metadata.', ...
            current_type, ...
            current_animal);

        return;
    end

    sampling_rate_group = ...
        metadata.SamplingRatePlane;


    %==============================================================%
    % Vérifier DF_combined_by_plane
    %==============================================================%
    if ~isfield( ...
            data.combined_plane, ...
            'DF_combined_by_plane') || ...
            isempty( ...
            data.combined_plane.DF_combined_by_plane)

        warning( ...
            '%s - %s: DF_combined_by_plane not found.', ...
            current_type, ...
            current_animal);

        return;
    end

    DF_group = ...
        data.combined_plane.DF_combined_by_plane;


    %==============================================================%
    % Dossier de sortie
    %==============================================================%
    if exist(current_output_folder, 'dir') ~= 7
        mkdir(current_output_folder);
    end


    %==============================================================%
    % Boucle recordings
    %==============================================================%
    nRecordings = ...
        numel(DF_group);

    for m = 1:nRecordings

        if isempty(DF_group{m})
            continue;
        end


        %==========================================================%
        % Date
        %==========================================================%
        current_date = '';

        if m <= numel(current_dates)

            try
                current_date = ...
                    char(string(current_dates(m)));

            catch
                current_date = '';
            end
        end


        %==========================================================%
        % Age
        %==========================================================%
        current_age = '';

        if m <= numel(current_ages)

            try
                current_age = ...
                    char(string(current_ages(m)));

            catch
                current_age = '';
            end
        end


        %==========================================================%
        % Sampling rate du recording
        %==========================================================%
        sampling_rate = [];

        if iscell(sampling_rate_group)

            if m <= numel(sampling_rate_group)

                sampling_rate = ...
                    sampling_rate_group{m};
            end

        elseif isnumeric(sampling_rate_group)

            if isscalar(sampling_rate_group)

                sampling_rate = ...
                    sampling_rate_group;

            elseif m <= numel(sampling_rate_group)

                sampling_rate = ...
                    sampling_rate_group(m);
            end
        end


        if isempty(sampling_rate) || ...
                ~isscalar(sampling_rate) || ...
                ~isfinite(sampling_rate) || ...
                sampling_rate <= 0

            warning( ...
                ['%s - %s - recording %d: ' ...
                 'invalid sampling rate.'], ...
                current_type, ...
                current_animal, ...
                m);

            continue;
        end


        %==========================================================%
        % Boucle plans
        %==========================================================%
        nPlanes = ...
            numel(DF_group{m});

        for p = 1:nPlanes


            %======================================================%
            % Chemin de sauvegarde
            %======================================================%
            figure_name = ...
                'representative_single_cell_traces';

            plane_number = ...
                p - 1;

            line_str = ...
                sanitize_filename_component( ...
                    current_line);

            animal_str = ...
                sanitize_filename_component( ...
                    current_animal);

            date_str = ...
                sanitize_filename_component( ...
                    current_date);

            age_str = ...
                sanitize_filename_component( ...
                    current_age);

            name_parts = { ...
                line_str, ...
                animal_str, ...
                date_str, ...
                age_str, ...
                sprintf( ...
                    'plane%d', ...
                    plane_number)};

            name_parts = ...
                name_parts( ...
                    ~cellfun( ...
                        @isempty, ...
                        name_parts));

            save_name = ...
                [ ...
                    strjoin( ...
                        name_parts, ...
                        '_'), ...
                    '_', ...
                    figure_name, ...
                    '.png' ...
                ];

            save_path = ...
                fullfile( ...
                    current_output_folder, ...
                    save_name);


            %======================================================%
            % Skip si figure déjà existante
            %======================================================%
            if exist(save_path, 'file') == 2

                fprintf( ...
                    'Figure already exists, skipped -> %s\n', ...
                    save_path);

                continue;
            end


            %======================================================%
            % DF combiné
            %======================================================%
            DF_combined = ...
                data.combined_plane. ...
                DF_combined_by_plane{m}{p};

            if isempty(DF_combined)
                continue;
            end


            %======================================================%
            % Récupérer isort
            %======================================================%
            isort = [];

            if isfield( ...
                    data.combined_plane, ...
                    'isort1_combined_by_plane') && ...
                    m <= numel( ...
                    data.combined_plane. ...
                    isort1_combined_by_plane) && ...
                    ~isempty( ...
                    data.combined_plane. ...
                    isort1_combined_by_plane{m}) && ...
                    p <= numel( ...
                    data.combined_plane. ...
                    isort1_combined_by_plane{m})

                isort = ...
                    data.combined_plane. ...
                    isort1_combined_by_plane{m}{p};
            end


            %======================================================%
            % Indices cellules électroporées
            %======================================================%
            blue_idx_original = [];

            if isfield( ...
                    data.combined_plane, ...
                    'blue_indices_combined_by_plane') && ...
                    m <= numel( ...
                    data.combined_plane. ...
                    blue_indices_combined_by_plane) && ...
                    ~isempty( ...
                    data.combined_plane. ...
                    blue_indices_combined_by_plane{m}) && ...
                    p <= numel( ...
                    data.combined_plane. ...
                    blue_indices_combined_by_plane{m})

                blue_idx_original = ...
                    data.combined_plane. ...
                    blue_indices_combined_by_plane{m}{p};
            end


            %======================================================%
            % Valid combined cells
            %======================================================%
            valid_combined = [];

            if isfield( ...
                    data.combined_plane, ...
                    'valid_combined_cells_by_plane') && ...
                    m <= numel( ...
                    data.combined_plane. ...
                    valid_combined_cells_by_plane) && ...
                    ~isempty( ...
                    data.combined_plane. ...
                    valid_combined_cells_by_plane{m}) && ...
                    p <= numel( ...
                    data.combined_plane. ...
                    valid_combined_cells_by_plane{m})

                valid_combined = ...
                    data.combined_plane. ...
                    valid_combined_cells_by_plane{m}{p};
            end


            if isempty(valid_combined)

                warning( ...
                    ['%s - %s - %s - plane %d: ' ...
                     'valid_combined_cells missing.'], ...
                    current_type, ...
                    current_animal, ...
                    current_date, ...
                    plane_number);

                continue;
            end


            %======================================================%
            % Pics détectés
            %======================================================%
            Acttmp2 = [];

            if isfield( ...
                    data.combined_plane, ...
                    'Acttmp2_combined_by_plane') && ...
                    m <= numel( ...
                    data.combined_plane. ...
                    Acttmp2_combined_by_plane) && ...
                    ~isempty( ...
                    data.combined_plane. ...
                    Acttmp2_combined_by_plane{m}) && ...
                    p <= numel( ...
                    data.combined_plane. ...
                    Acttmp2_combined_by_plane{m})

                Acttmp2 = ...
                    data.combined_plane. ...
                    Acttmp2_combined_by_plane{m}{p};
            end


            %======================================================%
            % Dimensions
            %======================================================%
            [NCell, Nz] = ...
                size(DF_combined);

            if NCell == 0 || Nz == 0
                continue;
            end


            %======================================================%
            % Sanitize isort
            %======================================================%
            if isempty(isort)

                isort = ...
                    (1:NCell)';

            else

                isort = ...
                    isort(:);

                isort( ...
                    isnan(isort) | ...
                    isort < 1 | ...
                    isort > NCell) = [];

                if numel(unique(isort)) ~= NCell

                    isort = ...
                        (1:NCell)';
                end
            end


            %======================================================%
            % Remap cellules électroporées
            %======================================================%
            blue_idx_original = ...
                blue_idx_original(:);

            valid_combined = ...
                valid_combined(:);

            [tf, loc] = ...
                ismember( ...
                    blue_idx_original, ...
                    valid_combined);

            blue_idx = ...
                loc(tf);

            blue_idx = ...
                unique(blue_idx);

            blue_idx( ...
                blue_idx < 1 | ...
                blue_idx > NCell) = [];


            %======================================================%
            % Cellules non électroporées
            %======================================================%
            all_idx = ...
                (1:NCell)';

            gcamp_idx = ...
                setdiff( ...
                    all_idx, ...
                    blue_idx);


            %======================================================%
            % Informations console
            %======================================================%
            fprintf('\n');

            fprintf( ...
                '%s | %s | %s | age %s | plane %d\n', ...
                current_type, ...
                current_animal, ...
                current_date, ...
                current_age, ...
                plane_number);

            fprintf( ...
                'Valid neurons = %d\n', ...
                NCell);

            fprintf( ...
                'Electroporated neurons = %d\n', ...
                numel(blue_idx));

            fprintf( ...
                'Non-electroporated neurons = %d\n', ...
                numel(gcamp_idx));


            %======================================================%
            % Nombre de traces
            %======================================================%
            n_example = 3;

            if numel(gcamp_idx) < n_example || ...
                    numel(blue_idx) < n_example

                warning( ...
                    ['%s - %s - %s - plane %d: ' ...
                     'not enough cells for 3 examples per group.'], ...
                    current_type, ...
                    current_animal, ...
                    current_date, ...
                    plane_number);

                continue;
            end


            %======================================================%
            % Sélection aléatoire
            %======================================================%
            rng('shuffle');

            gcamp_examples = ...
                gcamp_idx( ...
                    randperm( ...
                        numel(gcamp_idx), ...
                        n_example));

            blue_examples = ...
                blue_idx( ...
                    randperm( ...
                        numel(blue_idx), ...
                        n_example));


            %======================================================%
            % Figure
            %======================================================%
            fig = figure( ...
                'Color', 'w', ...
                'Units', 'normalized', ...
                'Position', [0 0 1 1]);

            ax = ...
                axes(fig);

            hold( ...
                ax, ...
                'on');


            %======================================================%
            % Temps
            %======================================================%
            t_plot = ...
                (0:Nz - 1) / sampling_rate;

            xlim_full = ...
                [ ...
                    t_plot(1), ...
                    t_plot(end) ...
                ];


            %======================================================%
            % Paramètres offsets
            %======================================================%
            offset = 0;

            offset_step = 3.5;

            max_trace_y = -Inf;
            min_trace_y = Inf;


            %======================================================%
            % GCaMP
            %======================================================%
            for j = 1:n_example

                cell_idx = ...
                    gcamp_examples(j);

                trace = ...
                    DF_combined( ...
                        cell_idx, ...
                        :);

                trace = ...
                    trace - ...
                    median( ...
                        trace, ...
                        'omitnan');

                y_trace = ...
                    trace + offset;


                %--------------------------------------------------%
                % Trace
                %--------------------------------------------------%
                plot( ...
                    ax, ...
                    t_plot, ...
                    y_trace, ...
                    'Color', [0 0.6 0], ...
                    'LineWidth', 3);


                %--------------------------------------------------%
                % Pics détectés
                %--------------------------------------------------%
                pk = [];

                if iscell(Acttmp2) && ...
                        numel(Acttmp2) >= cell_idx && ...
                        ~isempty(Acttmp2{cell_idx})

                    pk = ...
                        Acttmp2{cell_idx};

                    pk = ...
                        round(pk(:)');

                    pk = ...
                        pk( ...
                            isfinite(pk) & ...
                            pk >= 1 & ...
                            pk <= Nz);

                    pk = ...
                        unique(pk);
                end


                if ~isempty(pk)

                    plot( ...
                        ax, ...
                        t_plot(pk), ...
                        y_trace(pk), ...
                        '*', ...
                        'Color', [0.85 0.1 0.1], ...
                        'MarkerSize', 8, ...
                        'LineWidth', 1.2);
                end


                %--------------------------------------------------%
                % Valid cell ID
                %--------------------------------------------------%
                if cell_idx <= numel(valid_combined)

                    valid_cell_id = ...
                        valid_combined(cell_idx);

                else

                    valid_cell_id = ...
                        cell_idx;
                end


                text( ...
                    ax, ...
                    t_plot(1), ...
                    offset + 0.15, ...
                    sprintf( ...
                        'Cell %g', ...
                        valid_cell_id), ...
                    'FontSize', 22, ...
                    'FontWeight', 'bold', ...
                    'Color', [0 0.6 0], ...
                    'HorizontalAlignment', 'left', ...
                    'VerticalAlignment', 'bottom', ...
                    'Interpreter', 'none');


                max_trace_y = ...
                    max( ...
                        max_trace_y, ...
                        max( ...
                            y_trace, ...
                            [], ...
                            'omitnan'));

                min_trace_y = ...
                    min( ...
                        min_trace_y, ...
                        min( ...
                            y_trace, ...
                            [], ...
                            'omitnan'));

                offset = ...
                    offset + offset_step;
            end


            %======================================================%
            % Cellules électroporées
            %======================================================%
            for j = 1:n_example

                cell_idx = ...
                    blue_examples(j);

                trace = ...
                    DF_combined( ...
                        cell_idx, ...
                        :);

                trace = ...
                    trace - ...
                    median( ...
                        trace, ...
                        'omitnan');

                y_trace = ...
                    trace + offset;


                %--------------------------------------------------%
                % Trace
                %--------------------------------------------------%
                plot( ...
                    ax, ...
                    t_plot, ...
                    y_trace, ...
                    'Color', [0 0.35 1], ...
                    'LineWidth', 3);


                %--------------------------------------------------%
                % Pics détectés
                %--------------------------------------------------%
                pk = [];

                if iscell(Acttmp2) && ...
                        numel(Acttmp2) >= cell_idx && ...
                        ~isempty(Acttmp2{cell_idx})

                    pk = ...
                        Acttmp2{cell_idx};

                    pk = ...
                        round(pk(:)');

                    pk = ...
                        pk( ...
                            isfinite(pk) & ...
                            pk >= 1 & ...
                            pk <= Nz);

                    pk = ...
                        unique(pk);
                end


                if ~isempty(pk)

                    plot( ...
                        ax, ...
                        t_plot(pk), ...
                        y_trace(pk), ...
                        '*', ...
                        'Color', [0.85 0.1 0.1], ...
                        'MarkerSize', 8, ...
                        'LineWidth', 1.2);
                end


                %--------------------------------------------------%
                % Valid cell ID
                %--------------------------------------------------%
                if cell_idx <= numel(valid_combined)

                    valid_cell_id = ...
                        valid_combined(cell_idx);

                else

                    valid_cell_id = ...
                        cell_idx;
                end


                text( ...
                    ax, ...
                    t_plot(1), ...
                    offset + 0.15, ...
                    sprintf( ...
                        'Cell %g', ...
                        valid_cell_id), ...
                    'FontSize', 22, ...
                    'FontWeight', 'bold', ...
                    'Color', [0 0.35 1], ...
                    'HorizontalAlignment', 'left', ...
                    'VerticalAlignment', 'bottom', ...
                    'Interpreter', 'none');


                max_trace_y = ...
                    max( ...
                        max_trace_y, ...
                        max( ...
                            y_trace, ...
                            [], ...
                            'omitnan'));

                min_trace_y = ...
                    min( ...
                        min_trace_y, ...
                        min( ...
                            y_trace, ...
                            [], ...
                            'omitnan'));

                offset = ...
                    offset + offset_step;
            end


            %======================================================%
            % Mise en forme
            %======================================================%
            box( ...
                ax, ...
                'off');

            grid( ...
                ax, ...
                'off');


            xlabel( ...
                ax, ...
                'Time (s)', ...
                'FontSize', 42, ...
                'FontWeight', 'bold');


            ylabel( ...
                ax, ...
                '\DeltaF/F + offset', ...
                'FontSize', 42, ...
                'FontWeight', 'bold');


            title( ...
                ax, ...
                'Representative single-cell calcium traces', ...
                'FontSize', 42, ...
                'FontWeight', 'bold', ...
                'Interpreter', 'none');


            set( ...
                ax, ...
                'FontSize', 36, ...
                'TickLength', [0 0], ...
                'YTick', []);


            xlim( ...
                ax, ...
                xlim_full);


            %======================================================%
            % Barre d'échelle
            %======================================================%
            bar_time = 60;

            bar_amp = 1;

            recording_duration = ...
                t_plot(end) - ...
                t_plot(1);


            if recording_duration < bar_time

                bar_time = ...
                    max( ...
                        1, ...
                        round( ...
                            recording_duration / 5));
            end


            y0 = ...
                max_trace_y + 0.8;


            ylim( ...
                ax, ...
                [ ...
                    min_trace_y - 0.5, ...
                    y0 + bar_amp + 0.8 ...
                ]);


            xl = ...
                xlim(ax);


            x0 = ...
                xl(2) - ...
                bar_time - ...
                0.03 * range(xl);


            %------------------------------------------------------%
            % Barre horizontale
            %------------------------------------------------------%
            plot( ...
                ax, ...
                [ ...
                    x0, ...
                    x0 + bar_time ...
                ], ...
                [ ...
                    y0, ...
                    y0 ...
                ], ...
                'k', ...
                'LineWidth', 6);


            %------------------------------------------------------%
            % Barre verticale
            %------------------------------------------------------%
            plot( ...
                ax, ...
                [ ...
                    x0, ...
                    x0 ...
                ], ...
                [ ...
                    y0, ...
                    y0 + bar_amp ...
                ], ...
                'k', ...
                'LineWidth', 6);


            %------------------------------------------------------%
            % Texte temps
            %------------------------------------------------------%
            text( ...
                ax, ...
                x0 + bar_time / 2, ...
                y0 - 0.18, ...
                sprintf( ...
                    '%g s', ...
                    bar_time), ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'top', ...
                'FontSize', 34, ...
                'FontWeight', 'bold');


            %------------------------------------------------------%
            % Texte amplitude
            %------------------------------------------------------%
            text( ...
                ax, ...
                x0 - 0.01 * range(xl), ...
                y0 + bar_amp / 2, ...
                '1 \DeltaF/F', ...
                'HorizontalAlignment', 'right', ...
                'VerticalAlignment', 'middle', ...
                'FontSize', 34, ...
                'FontWeight', 'bold');


            %======================================================%
            % Fin du tracé
            %======================================================%
            hold( ...
                ax, ...
                'off');


            %======================================================%
            % Sauvegarde
            %======================================================%
            exportgraphics( ...
                fig, ...
                save_path, ...
                'Resolution', 300);


            fprintf( ...
                'Figure saved -> %s\n', ...
                save_path);


            %======================================================%
            % Fermeture
            %======================================================%
            if ishghandle(fig)

                close(fig);
            end
        end
    end
end


function value = sanitize_filename_component(value)
%SANITIZE_FILENAME_COMPONENT
% Convertit une valeur en texte et retire les caractères interdits.

    if isempty(value)

        value = '';

        return;
    end


    if isstring(value)

        value = ...
            char(value(1));

    elseif iscell(value)

        value = ...
            value{1};

        if isstring(value)

            value = ...
                char(value);
        end
    end


    if isnumeric(value)

        value = ...
            num2str(value);
    end


    if ~ischar(value)

        value = ...
            char(string(value));
    end


    value = ...
        strtrim(value);


    value = ...
        regexprep( ...
            value, ...
            '[<>:"/\\|?*]', ...
            '-');


    value = ...
        regexprep( ...
            value, ...
            '\s+', ...
            '_');


    value = ...
        regexprep( ...
            value, ...
            '_+', ...
            '_');


    value = ...
        regexprep( ...
            value, ...
            '^[_\-.]+|[_\-.]+$', ...
            '');
end