function plot_gcamp_histograms( ...
        results_analysis, ...
        gcamp_output_folders, ...
        current_line, ...
        current_animal, ...
        current_dates, ...
        current_ages)
%PLOT_GCAMP_HISTOGRAMS
%
% Crée pour chaque recording et chaque plan :
%   - histogramme de fréquence GCaMP ;
%   - histogramme des intervalles inter-événements.
%
% Organisation des dossiers :
%
%   gcamp_output_folders{m}{p}
%
% avec :
%   m = recording
%   p = plan
%
% Les métriques sont lues dans :
%
%   results_analysis.gcamp_plane.activity.FrequencyPerCell{m}{p}
%   results_analysis.gcamp_plane.activity.InterEventIntervals_ms{m}{p}
%
% Sauvegarde :
%
%   gcamp_output_folders{m}{p}
%
% Aucun dossier n'est créé.
% Si le dossier GCaMP d'un plan est absent, ce plan est ignoré.
%
% Nomenclature :
%
%   line_animal_date_age_planeN_GCaMP_frequency_interevent_intervals_histograms.png
%
% Si current_line est vide :
%
%   animal_date_age_planeN_GCaMP_frequency_interevent_intervals_histograms.png


    %==============================================================%
    % Nombre de recordings
    %==============================================================%
    nRec = ...
        numel(gcamp_output_folders);


    %==============================================================%
    % Boucle recordings
    %==============================================================%
    for m = 1:nRec

        %==========================================================%
        % Date
        %==========================================================%
        if m <= numel(current_dates)

            current_date = ...
                get_date_label( ...
                    current_dates, ...
                    m);

        else

            current_date = ...
                '';
        end


        %==========================================================%
        % Age
        %==========================================================%
        if m <= numel(current_ages)

            current_age = ...
                get_age_label( ...
                    current_ages, ...
                    m);

        else

            current_age = ...
                '';
        end


        %==========================================================%
        % Fréquences GCaMP
        %==========================================================%
        freq_by_plane = ...
            get_results_analysis_value( ...
                results_analysis, ...
                { ...
                    'gcamp_plane', ...
                    'activity', ...
                    'FrequencyPerCell' ...
                }, ...
                m);


        %==========================================================%
        % Inter-event intervals GCaMP
        %==========================================================%
        intervals_by_plane = ...
            get_results_analysis_value( ...
                results_analysis, ...
                { ...
                    'gcamp_plane', ...
                    'activity', ...
                    'InterEventIntervals_ms' ...
                }, ...
                m);


        %==========================================================%
        % Normalisation en cellules par plan
        %==========================================================%
        freq_by_plane = ...
            normalize_planes_cell( ...
                freq_by_plane);


        intervals_by_plane = ...
            normalize_planes_cell( ...
                intervals_by_plane);


        %==========================================================%
        % Nombre de plans
        %==========================================================%
        nPlanes = ...
            max( ...
                [ ...
                    numel(freq_by_plane), ...
                    numel(intervals_by_plane), ...
                    get_number_of_output_planes( ...
                        gcamp_output_folders, ...
                        m) ...
                ]);


        if nPlanes == 0

            fprintf( ...
                'Rec %d: no histogram data, skip.\n', ...
                m);

            continue;
        end


        %==========================================================%
        % Boucle plans
        %==========================================================%
        for p = 1:nPlanes

            fig = [];


            try

                plane_number = ...
                    p - 1;


                %==================================================%
                % Dossier GCaMP du plan
                %==================================================%
                if m > numel(gcamp_output_folders) || ...
                        isempty(gcamp_output_folders{m}) || ...
                        ~iscell(gcamp_output_folders{m}) || ...
                        p > numel(gcamp_output_folders{m}) || ...
                        isempty(gcamp_output_folders{m}{p})

                    warning( ...
                        ['Rec %d | plane %d: GCaMP output folder ' ...
                         'missing, plane skipped.'], ...
                        m, ...
                        plane_number);

                    continue;
                end


                current_gcamp_output_folder = ...
                    gcamp_output_folders{m}{p};


                %==================================================%
                % Le dossier doit déjà exister
                %==================================================%
                if exist( ...
                        current_gcamp_output_folder, ...
                        'dir') ~= 7

                    warning( ...
                        ['Rec %d | plane %d: GCaMP output folder ' ...
                         'does not exist, plane skipped: %s'], ...
                        m, ...
                        plane_number, ...
                        current_gcamp_output_folder);

                    continue;
                end


                %==================================================%
                % Données du plan
                %==================================================%
                freq = [];

                intervals = [];


                %--------------------------------------------------%
                % Frequency
                %--------------------------------------------------%
                if p <= numel(freq_by_plane)

                    freq = ...
                        force_numeric_vector( ...
                            freq_by_plane{p});
                end


                %--------------------------------------------------%
                % Inter-event intervals
                %--------------------------------------------------%
                if p <= numel(intervals_by_plane)

                    intervals = ...
                        force_numeric_vector( ...
                            intervals_by_plane{p});


                    %----------------------------------------------%
                    % ms -> secondes
                    %----------------------------------------------%
                    intervals = ...
                        intervals ./ ...
                        1000;
                end


                %==================================================%
                % Aucune donnée
                %==================================================%
                if isempty(freq) && ...
                        isempty(intervals)

                    fprintf( ...
                        ['Rec %d | plane %d: no histogram ' ...
                         'data, skip.\n'], ...
                        m, ...
                        plane_number);

                    continue;
                end


                %==================================================%
                % Nom de la figure
                %==================================================%
                filename_title = ...
                    'GCaMP_frequency_interevent_intervals_histograms';


                %==================================================%
                % Filename
                %==================================================%
                if isempty(current_line)

                    filename = ...
                        sprintf( ...
                            '%s_%s_%s_plane%d_%s.png', ...
                            current_animal, ...
                            current_date, ...
                            current_age, ...
                            plane_number, ...
                            filename_title);

                else

                    filename = ...
                        sprintf( ...
                            '%s_%s_%s_%s_plane%d_%s.png', ...
                            current_line, ...
                            current_animal, ...
                            current_date, ...
                            current_age, ...
                            plane_number, ...
                            filename_title);
                end


                %==================================================%
                % Chemin
                %==================================================%
                save_path = ...
                    fullfile( ...
                        current_gcamp_output_folder, ...
                        filename);


                %==================================================%
                % Skip si déjà existant
                %==================================================%
                if exist(save_path, 'file') == 2

                    fprintf( ...
                        ['Rec %d | plane %d: figure already ' ...
                         'exists, skip: %s\n'], ...
                        m, ...
                        plane_number, ...
                        save_path);

                    continue;
                end


                %==================================================%
                % Figure
                %==================================================%
                figure_title = ...
                    sprintf( ...
                        'GCaMP frequency and interval histograms - plane %d', ...
                        plane_number);


                fig = ...
                    figure( ...
                        'Color', ...
                        'w', ...
                        'Units', ...
                        'normalized', ...
                        'Position', ...
                        [0.15 0.12 0.70 0.72], ...
                        'Name', ...
                        figure_title);


                tl = ...
                    tiledlayout( ...
                        fig, ...
                        1, ...
                        2, ...
                        'TileSpacing', ...
                        'compact', ...
                        'Padding', ...
                        'compact');


                %==================================================%
                % Histogramme fréquence
                %==================================================%
                ax1 = ...
                    nexttile(tl);


                if ~isempty(freq)

                    histogram( ...
                        ax1, ...
                        freq, ...
                        50);


                    xlabel( ...
                        ax1, ...
                        'Frequency (events / min)');


                    ylabel( ...
                        ax1, ...
                        'Count');


                    title( ...
                        ax1, ...
                        'GCaMP frequencies', ...
                        'Interpreter', ...
                        'none');


                    grid( ...
                        ax1, ...
                        'on');


                    box( ...
                        ax1, ...
                        'off');

                else

                    empty_hist_axis( ...
                        ax1, ...
                        'No frequency data');
                end


                %==================================================%
                % Histogramme IEI
                %==================================================%
                ax2 = ...
                    nexttile(tl);


                if ~isempty(intervals)

                    intervals = ...
                        intervals( ...
                            intervals >= 0 & ...
                            intervals <= 60);


                    if ~isempty(intervals)

                        histogram( ...
                            ax2, ...
                            intervals, ...
                            150, ...
                            'BinLimits', ...
                            [0 60]);


                        xlim( ...
                            ax2, ...
                            [0 60]);


                        xlabel( ...
                            ax2, ...
                            'Inter-event interval (s)');


                        ylabel( ...
                            ax2, ...
                            'Count');


                        title( ...
                            ax2, ...
                            'Inter-event intervals', ...
                            'Interpreter', ...
                            'none');


                        grid( ...
                            ax2, ...
                            'on');


                        box( ...
                            ax2, ...
                            'off');

                    else

                        empty_hist_axis( ...
                            ax2, ...
                            'No interval data');
                    end

                else

                    empty_hist_axis( ...
                        ax2, ...
                        'No interval data');
                end


                %==================================================%
                % Titre général
                %==================================================%
                title( ...
                    tl, ...
                    sprintf( ...
                        ['GCaMP frequency and interval histograms - ' ...
                         '%s - %s - %s - plane %d'], ...
                        current_animal, ...
                        current_date, ...
                        current_age, ...
                        plane_number), ...
                    'Interpreter', ...
                    'none', ...
                    'FontWeight', ...
                    'bold');


                %==================================================%
                % Maximiser
                %==================================================%
                set( ...
                    fig, ...
                    'WindowState', ...
                    'maximized');


                drawnow;


                %==================================================%
                % Sauvegarde
                %==================================================%
                exportgraphics( ...
                    fig, ...
                    save_path, ...
                    'Resolution', ...
                    300);


                fprintf( ...
                    'Saved: %s\n', ...
                    save_path);


                %==================================================%
                % Fermeture
                %==================================================%
                if ~isempty(fig) && ...
                        isgraphics(fig)

                    close(fig);
                end


            catch ME

                fprintf( ...
                    ['GCaMP histogram error | rec %d | ' ...
                     'plane %d: %s\n'], ...
                    m, ...
                    p - 1, ...
                    ME.message);


                if ~isempty(fig) && ...
                        isgraphics(fig)

                    close(fig);
                end
            end
        end
    end
end


%=========================================================================%
% GET RESULTS_ANALYSIS VALUE
%=========================================================================%
function val = get_results_analysis_value( ...
        results_analysis, ...
        path_fields, ...
        idx)

    val = [];


    if isempty(results_analysis) || ...
            ~isstruct(results_analysis)

        return;
    end


    current = ...
        results_analysis;


    for i = 1:numel(path_fields)

        field_name = ...
            path_fields{i};


        if ~isstruct(current) || ...
                ~isfield(current, field_name)

            return;
        end


        current = ...
            current.(field_name);
    end


    if iscell(current)

        if numel(current) >= idx

            val = ...
                current{idx};
        end

    else

        val = ...
            current;
    end
end


%=========================================================================%
% NORMALIZE PLANES
%=========================================================================%
function planes = normalize_planes_cell(x)

    if isempty(x)

        planes = {};

    elseif iscell(x)

        planes = ...
            x(:).';

    else

        planes = ...
            {x};
    end
end


%=========================================================================%
% NUMBER OF OUTPUT PLANES
%=========================================================================%
function nPlanes = get_number_of_output_planes( ...
        gcamp_output_folders, ...
        m)

    nPlanes = ...
        0;


    if m > numel(gcamp_output_folders) || ...
            isempty(gcamp_output_folders{m}) || ...
            ~iscell(gcamp_output_folders{m})

        return;
    end


    nPlanes = ...
        numel( ...
            gcamp_output_folders{m});
end


%=========================================================================%
% FORCE NUMERIC VECTOR
%=========================================================================%
function v = force_numeric_vector(x)

    if isempty(x)

        v = [];
        return;
    end


    %==============================================================%
    % Cell array
    %==============================================================%
    if iscell(x)

        x = ...
            x( ...
                ~cellfun( ...
                    @isempty, ...
                    x));


        if isempty(x)

            v = [];
            return;
        end


        is_numeric = ...
            cellfun( ...
                @(c) ...
                    isnumeric(c) || ...
                    islogical(c), ...
                x);


        x = ...
            x(is_numeric);


        if isempty(x)

            v = [];
            return;
        end


        x = ...
            cellfun( ...
                @(c) ...
                    double(c(:)), ...
                x, ...
                'UniformOutput', ...
                false);


        x = ...
            vertcat( ...
                x{:});
    end


    %==============================================================%
    % Numeric
    %==============================================================%
    if ~(isnumeric(x) || ...
            islogical(x))

        v = [];
        return;
    end


    v = ...
        double( ...
            x(:));


    v = ...
        v( ...
            isfinite(v));
end


%=========================================================================%
% EMPTY HISTOGRAM AXIS
%=========================================================================%
function empty_hist_axis( ...
        ax, ...
        msg)

    title( ...
        ax, ...
        msg, ...
        'Interpreter', ...
        'none');


    xticks( ...
        ax, ...
        []);


    yticks( ...
        ax, ...
        []);


    box( ...
        ax, ...
        'off');
end


%=========================================================================%
% AGE
%=========================================================================%
function age_label = get_age_label( ...
        ages, ...
        m)

    if iscell(ages)

        age_value = ...
            ages{m};

    else

        age_value = ...
            ages(m);
    end


    if isnumeric(age_value) || ...
            islogical(age_value)

        age_label = ...
            sprintf( ...
                'P%d', ...
                round( ...
                    double(age_value)));

    else

        age_txt = ...
            age_value;


        token = ...
            regexp( ...
                age_txt, ...
                '\d+', ...
                'match', ...
                'once');


        if isempty(token)

            age_label = ...
                age_txt;

        else

            age_label = ...
                ['P' token];
        end
    end
end


%=========================================================================%
% DATE
%=========================================================================%
function date_label = get_date_label( ...
        dates, ...
        m)

    if iscell(dates)

        date_value = ...
            dates{m};

    else

        date_value = ...
            dates(m);
    end


    if isdatetime(date_value)

        date_label = ...
            datestr( ...
                date_value, ...
                'yyyy-mm-dd');

    else

        date_label = ...
            date_value;
    end
end