function plot_representative_traces_by_burst_rate( ...
        data, ...
        results_analysis, ...
        sampling_rate_group, ...
        current_type, ...
        current_output_folder, ...
        gcamp_output_folders, ...
        current_line, ...
        current_animal, ...
        include_electroporated_cells)
%PLOT_REPRESENTATIVE_TRACES_BY_BURST_RATE
%
% Sélectionne des cellules représentatives selon leur burst rate :
%
%   - burst rate minimum
%   - burst rate médian
%   - burst rate maximum
%
% La sélection est réalisée globalement parmi tous les recordings
% et tous les plans de l'animal.
%
% Les variables nécessaires sont préparées en amont dans visualize_data.
%
% gcamp_output_folders :
%
%   gcamp_output_folders{m}{p}
%
% avec :
%   m = recording
%   p = plan
%
% Sauvegarde :
%
%   1. Toujours dans le premier dossier GCaMP valide rencontré
%      pour la population considérée.
%
%   2. Également dans current_output_folder lorsque celui-ci
%      est renseigné et existe.
%
% Aucun dossier n'est créé ici.


    %==============================================================%
    % Vérifications
    %==============================================================%
    if nargin < 9 || ...
            isempty(include_electroporated_cells)

        include_electroporated_cells = ...
            false;
    end


    if isempty(data) || ...
            ~isstruct(data)

        fprintf( ...
            'Representative burst traces skipped: no data.\n');

        return;
    end


    if isempty(results_analysis) || ...
            ~isstruct(results_analysis)

        fprintf( ...
            ['Representative burst traces skipped: ' ...
             'no results_analysis.\n']);

        return;
    end


    if isempty(sampling_rate_group)

        fprintf( ...
            ['Representative burst traces skipped: ' ...
             'SamplingRatePlane missing.\n']);

        return;
    end


    %==============================================================%
    % Sauvegarde dans current_output_folder ?
    %
    % current_output_folder contient déjà Adult ou Development.
    %
    % Arborescence :
    %
    % current_output_folder/
    %   line/
    %     animal/
    %==============================================================%
    save_in_current_output = ...
        ~isempty(current_output_folder);
    
    
    automatic_animal_folder = '';
    
    
    if save_in_current_output
    
        automatic_animal_folder = ...
            fullfile( ...
                current_output_folder, ...
                char(string(current_line)), ...
                char(string(current_animal)));
    
    
        if exist(automatic_animal_folder, 'dir') ~= 7
    
            mkdir(automatic_animal_folder);
        end
    end

    %==============================================================%
    % GCaMP
    %==============================================================%
    plot_one_burst_branch( ...
        data, ...
        results_analysis, ...
        sampling_rate_group, ...
        'gcamp_plane', ...
        'DF_gcamp_by_plane', ...
        'GCaMP', ...
        current_type, ...
        automatic_animal_folder, ...
        save_in_current_output, ...
        gcamp_output_folders, ...
        current_line, ...
        current_animal);


    %==============================================================%
    % mTOR / électroporées
    %==============================================================%
    if include_electroporated_cells

        plot_one_burst_branch( ...
            data, ...
            results_analysis, ...
            sampling_rate_group, ...
            'electroporated_plane', ...
            'DF_electroporated_by_plane', ...
            'mTOR', ...
            current_type, ...
            automatic_animal_folder, ...
            save_in_current_output, ...
            gcamp_output_folders, ...
            current_line, ...
            current_animal);
    end
end


%==================================================================%
% Une population
%==================================================================%
function plot_one_burst_branch( ...
        data, ...
        results_analysis, ...
        sampling_rate_group, ...
        branch_name, ...
        df_field, ...
        label_name, ...
        current_type, ...
        current_output_folder, ...
        save_in_current_output, ...
        gcamp_output_folders, ...
        current_line, ...
        current_animal)

    all_burst = [];

    all_traces = {};

    all_time = {};

    all_labels = {};


    save_output_folder = '';


    %==============================================================%
    % Vérifier traces
    %==============================================================%
    if ~isfield(data, branch_name) || ...
            ~isstruct(data.(branch_name)) || ...
            ~isfield(data.(branch_name), df_field) || ...
            isempty(data.(branch_name).(df_field))

        fprintf( ...
            '%s skipped: traces missing.\n', ...
            label_name);

        return;
    end


    DF_all = ...
        data.(branch_name).(df_field);


    %==============================================================%
    % Burst rates
    %==============================================================%
    if ~isfield(results_analysis, branch_name) || ...
            ~isstruct(results_analysis.(branch_name)) || ...
            ~isfield( ...
                results_analysis.(branch_name), ...
                'activity') || ...
            ~isstruct( ...
                results_analysis.(branch_name).activity) || ...
            ~isfield( ...
                results_analysis.(branch_name).activity, ...
                'BurstRate_per_min')

        fprintf( ...
            '%s skipped: %s.activity.BurstRate_per_min missing.\n', ...
            label_name, ...
            branch_name);

        return;
    end


    burst_all = ...
        results_analysis. ...
            (branch_name). ...
            activity. ...
            BurstRate_per_min;


    %==============================================================%
    % Nombre recordings
    %==============================================================%
    nRec = ...
        min( ...
            [ ...
                numel(DF_all), ...
                numel(burst_all), ...
                numel(sampling_rate_group) ...
            ]);


    if nRec == 0
        return;
    end


    %==============================================================%
    % Recordings
    %==============================================================%
    for m = 1:nRec

        %==========================================================%
        % Sampling rate
        %==========================================================%
        if iscell(sampling_rate_group)

            if m > numel(sampling_rate_group) || ...
                    isempty(sampling_rate_group{m})

                fprintf( ...
                    ['%s rec %d skipped: ' ...
                     'sampling rate missing.\n'], ...
                    label_name, ...
                    m);

                continue;
            end


            sampling_rate = ...
                sampling_rate_group{m};

        else

            if m > numel(sampling_rate_group)

                continue;
            end


            sampling_rate = ...
                sampling_rate_group(m);
        end


        sampling_rate = ...
            unwrap_numeric( ...
                sampling_rate);


        if isempty(sampling_rate) || ...
                ~isnumeric(sampling_rate)

            continue;
        end


        sampling_rate = ...
            double( ...
                sampling_rate(1));


        if ~isfinite(sampling_rate) || ...
                sampling_rate <= 0

            continue;
        end


        %==========================================================%
        % Traces recording
        %==========================================================%
        if m > numel(DF_all) || ...
                isempty(DF_all{m})

            continue;
        end


        DF_planes = ...
            DF_all{m};


        if ~iscell(DF_planes)

            DF_planes = ...
                {DF_planes};
        end


        %==========================================================%
        % Burst recording
        %==========================================================%
        if iscell(burst_all)

            if m > numel(burst_all) || ...
                    isempty(burst_all{m})

                continue;
            end


            burst_planes = ...
                burst_all{m};

        else

            if m ~= 1
                continue;
            end


            burst_planes = ...
                burst_all;
        end


        if ~iscell(burst_planes)

            burst_planes = ...
                {burst_planes};
        end


        %==========================================================%
        % Plans
        %==========================================================%
        nPlanes = ...
            min( ...
                numel(DF_planes), ...
                numel(burst_planes));


        for p = 1:nPlanes

            %======================================================%
            % Dossier GCaMP du plan
            %======================================================%
            if m > numel(gcamp_output_folders) || ...
                    isempty(gcamp_output_folders{m}) || ...
                    ~iscell(gcamp_output_folders{m}) || ...
                    p > numel(gcamp_output_folders{m}) || ...
                    isempty(gcamp_output_folders{m}{p})

                warning( ...
                    ['%s rec %d plane %d: GCaMP output folder ' ...
                     'missing, plane skipped.'], ...
                    label_name, ...
                    m, ...
                    p - 1);

                continue;
            end


            current_gcamp_output_folder = ...
                gcamp_output_folders{m}{p};


            if exist( ...
                    current_gcamp_output_folder, ...
                    'dir') ~= 7

                warning( ...
                    ['%s rec %d plane %d: GCaMP output folder ' ...
                     'does not exist, plane skipped: %s'], ...
                    label_name, ...
                    m, ...
                    p - 1, ...
                    current_gcamp_output_folder);

                continue;
            end


            %======================================================%
            % Premier dossier GCaMP valide utilisé pour sauvegarde
            %======================================================%
            if isempty(save_output_folder)

                save_output_folder = ...
                    current_gcamp_output_folder;
            end


            %======================================================%
            % Données du plan
            %======================================================%
            DF = ...
                DF_planes{p};


            burst_rate = ...
                unwrap_numeric( ...
                    burst_planes{p});


            if isempty(DF) || ...
                    isempty(burst_rate)

                continue;
            end


            if ~isnumeric(DF) || ...
                    ~isnumeric(burst_rate)

                fprintf( ...
                    ['%s rec %d plane %d skipped: ' ...
                     'non-numeric data.\n'], ...
                    label_name, ...
                    m, ...
                    p - 1);

                continue;
            end


            DF = ...
                double(DF);


            burst_rate = ...
                double( ...
                    burst_rate(:));


            %======================================================%
            % Harmoniser cellules
            %======================================================%
            n_cells = ...
                min( ...
                    size(DF, 1), ...
                    numel(burst_rate));


            if n_cells < 1
                continue;
            end


            DF = ...
                DF( ...
                    1:n_cells, ...
                    :);


            burst_rate = ...
                burst_rate( ...
                    1:n_cells);


            valid_cells = ...
                find( ...
                    isfinite(burst_rate));


            %======================================================%
            % Collecte
            %======================================================%
            for ii = 1:numel(valid_cells)

                c = ...
                    valid_cells(ii);


                trace_c = ...
                    DF(c, :);


                if isempty(trace_c) || ...
                        all(~isfinite(trace_c))

                    continue;
                end


                trace_c = ...
                    trace_c - ...
                    median( ...
                        trace_c, ...
                        'omitnan');


                n_frames = ...
                    numel(trace_c);


                time_c = ...
                    (0:n_frames - 1) ./ ...
                    sampling_rate;


                all_burst(end + 1, 1) = ...
                    burst_rate(c); %#ok<AGROW>


                all_traces{end + 1, 1} = ...
                    trace_c; %#ok<AGROW>


                all_time{end + 1, 1} = ...
                    time_c; %#ok<AGROW>


                all_labels{end + 1, 1} = ...
                    sprintf( ...
                        'rec %d | plane %d | cell %d', ...
                        m, ...
                        p - 1, ...
                        c); %#ok<AGROW>
            end
        end
    end


    %==============================================================%
    % Aucun dossier GCaMP valide
    %==============================================================%
    if isempty(save_output_folder)

        fprintf( ...
            '%s skipped: no valid GCaMP output folder.\n', ...
            label_name);

        return;
    end


    %==============================================================%
    % Minimum 3 cellules
    %==============================================================%
    if numel(all_burst) < 3

        fprintf( ...
            '%s skipped: fewer than 3 valid cells globally.\n', ...
            label_name);

        return;
    end


    %==============================================================%
    % Trier burst rate
    %==============================================================%
    [~, idx_sort] = ...
        sort( ...
            all_burst, ...
            'ascend');


    idx_min = ...
        idx_sort(1);


    idx_median = ...
        idx_sort( ...
            round( ...
                (numel(idx_sort) + 1) / 2));


    idx_max = ...
        idx_sort(end);


    selected_idx = ...
        [ ...
            idx_min, ...
            idx_median, ...
            idx_max ...
        ];


    selected_names = ...
        { ...
            'Minimum', ...
            'Median', ...
            'Maximum' ...
        };


    %==============================================================%
    % Sélection
    %==============================================================%
    selected_traces = ...
        cell(3, 1);


    selected_time = ...
        cell(3, 1);


    selected_labels = ...
        cell(3, 1);


    for i = 1:3

        idx = ...
            selected_idx(i);


        selected_traces{i} = ...
            all_traces{idx};


        selected_time{i} = ...
            all_time{idx};


        selected_labels{i} = ...
            sprintf( ...
                '%s | %.2f bursts/min | %s', ...
                selected_names{i}, ...
                all_burst(idx), ...
                all_labels{idx});
    end


    %==============================================================%
    % Offset
    %==============================================================%
    offset = ...
        compute_auto_trace_offset_from_cell( ...
            selected_traces);


    %==============================================================%
    % Filename
    %==============================================================%
    if isempty(current_line)

        filename = ...
            sprintf( ...
                '%s_%s_%s_representative_traces_by_burst_rate.png', ...
                current_type, ...
                current_animal, ...
                label_name);

    else

        filename = ...
            sprintf( ...
                '%s_%s_%s_%s_representative_traces_by_burst_rate.png', ...
                current_line, ...
                current_animal, ...
                current_type, ...
                label_name);
    end


    %==============================================================%
    % Chemin sauvegarde GCaMP
    %==============================================================%
    save_path_gcamp = ...
        fullfile( ...
            save_output_folder, ...
            filename);


    exists_gcamp = ...
        exist( ...
            save_path_gcamp, ...
            'file') == 2;


    %==============================================================%
    % Chemin sauvegarde current_output_folder
    %==============================================================%
    save_path_output = '';


    exists_output = ...
        true;


    if save_in_current_output

        save_path_output = ...
            fullfile( ...
                current_output_folder, ...
                filename);


        exists_output = ...
            exist( ...
                save_path_output, ...
                'file') == 2;
    end


    %==============================================================%
    % Toutes les copies existent déjà
    %==============================================================%
    if exists_gcamp && ...
            exists_output

        if save_in_current_output

            fprintf( ...
                ['Burst figure already exists in both ' ...
                 'folders, skip: %s\n'], ...
                filename);

        else

            fprintf( ...
                ['Burst figure already exists in GCaMP ' ...
                 'folder, skip: %s\n'], ...
                save_path_gcamp);
        end

        return;
    end


    %==============================================================%
    % Figure
    %==============================================================%
    figure_title = ...
        sprintf( ...
            '%s representative traces by burst rate', ...
            label_name);


    fig = ...
        figure( ...
            'Color', ...
            'w', ...
            'Units', ...
            'normalized', ...
            'Position', ...
            [0.05 0.10 0.90 0.75], ...
            'Name', ...
            figure_title);


    ax = ...
        axes(fig);


    hold( ...
        ax, ...
        'on');


    for i = 1:3

        plot( ...
            ax, ...
            selected_time{i}, ...
            selected_traces{i} + ...
                (i - 1) * offset, ...
            'k', ...
            'LineWidth', ...
            1.3);
    end


    yticks( ...
        ax, ...
        (0:2) * offset);


    yticklabels( ...
        ax, ...
        selected_labels);


    set( ...
        ax, ...
        'TickLabelInterpreter', ...
        'none');


    xlabel( ...
        ax, ...
        'Time (s)');


    ylabel( ...
        ax, ...
        '\DeltaF/F + offset');


    title( ...
        ax, ...
        figure_title, ...
        'Interpreter', ...
        'none');


    grid( ...
        ax, ...
        'off');


    box( ...
        ax, ...
        'off');


    hold( ...
        ax, ...
        'off');


    %==============================================================%
    % Agrandir avant sauvegarde
    %==============================================================%
    set( ...
        fig, ...
        'WindowState', ...
        'maximized');


    drawnow;


    %==============================================================%
    % Sauvegarde GCaMP
    %==============================================================%
    if ~exists_gcamp

        exportgraphics( ...
            fig, ...
            save_path_gcamp, ...
            'Resolution', ...
            300);


        fprintf( ...
            'Burst figure saved: %s\n', ...
            save_path_gcamp);
    end


    %==============================================================%
    % Sauvegarde dans current_output_folder
    %==============================================================%
    if save_in_current_output && ...
            ~exists_output

        exportgraphics( ...
            fig, ...
            save_path_output, ...
            'Resolution', ...
            300);


        fprintf( ...
            'Burst figure saved: %s\n', ...
            save_path_output);
    end


    %==============================================================%
    % Fermeture
    %==============================================================%
    if isgraphics(fig)

        close(fig);
    end
end


%==================================================================%
% Helper numérique
%==================================================================%
function out = unwrap_numeric(x)

    out = ...
        x;


    while iscell(out) && ...
            numel(out) == 1

        out = ...
            out{1};
    end


    if iscell(out)

        tmp = [];


        for i = 1:numel(out)

            xi = ...
                unwrap_numeric( ...
                    out{i});


            if isnumeric(xi) || ...
                    islogical(xi)

                tmp = ...
                    [ ...
                        tmp; ...
                        double(xi(:)) ...
                    ]; %#ok<AGROW>
            end
        end


        out = ...
            tmp;
    end


    if isnumeric(out) || ...
            islogical(out)

        out = ...
            double(out);
    end
end


%==================================================================%
% Offset automatique
%==================================================================%
function offset = compute_auto_trace_offset_from_cell( ...
        trace_cells)

    all_vals = [];


    for i = 1:numel(trace_cells)

        x = ...
            trace_cells{i};


        if isempty(x) || ...
                ~isnumeric(x)

            continue;
        end


        x = ...
            double( ...
                x(:));


        x = ...
            x( ...
                isfinite(x));


        if isempty(x)
            continue;
        end


        all_vals = ...
            [ ...
                all_vals; ...
                x ...
            ]; %#ok<AGROW>
    end


    if isempty(all_vals)

        offset = ...
            1;

        return;
    end


    amp = ...
        prctile(all_vals, 99) - ...
        prctile(all_vals, 1);


    if ~isfinite(amp) || ...
            amp <= 0

        amp = ...
            std( ...
                all_vals, ...
                'omitnan');
    end


    if ~isfinite(amp) || ...
            amp <= 0

        amp = ...
            1;
    end


    offset = ...
        1.5 * amp;
end