function [ ...
    grouped_by_type, ...
    ages_by_type, ...
    valid_type_names ...
    ] = ...
    collect_basic_metrics_by_type( ...
        selected_groups, ...
        include_blue_cells)

%COLLECT_BASIC_METRICS_BY_TYPE
%
% Regroupe les résultats de selected_groups :
%
%   results_analysis
%       -> recordings individuels
%       -> pool par type
%       -> regroupement par âge
%
% Métriques principales pour le radar :
%
%   FrequencyPerCell_gcamp
%   pairwise_corr_gcamp_gcamp
%   SCEsFrequency
%   SCEsCellParticipation_percent
%   BurstFraction_gcamp


    %==============================================================%
    % Initialisation
    %==============================================================%
    grouped_by_type = ...
        struct();

    ages_by_type = ...
        struct();

    valid_type_names = {};


    plot_blue = ...
        isequal( ...
            include_blue_cells, ...
            1);


    type_names = ...
        fieldnames(selected_groups);


    %==============================================================%
    % Types
    %==============================================================%
    for t = 1:numel(type_names)

        current_type = ...
            type_names{t};

        %==========================================================%
        % Animaux
        %==========================================================%
        animals = ...
            selected_groups.(current_type);


        fprintf('\n==============================\n');
        fprintf('Collect basic metrics\n');
        fprintf('Type: %s\n', current_type);
        fprintf('Animals: %d\n', numel(animals));
        fprintf('==============================\n');


        pooled_records = ...
            struct([]);


        %==========================================================%
        % Boucle animaux
        %==========================================================%
        for k = 1:numel(animals)

            %------------------------------------------------------%
            % results_analysis
            %------------------------------------------------------%
            if ~isfield( ...
                    animals(k), ...
                    'results_analysis') || ...
                    isempty(animals(k).results_analysis) || ...
                    ~isstruct(animals(k).results_analysis)

                fprintf( ...
                    ['Type %s | animal %d skipped: ' ...
                     'no results_analysis\n'], ...
                    current_type, ...
                    k);

                continue;
            end


            %------------------------------------------------------%
            % Ages
            %------------------------------------------------------%
            if ~isfield( ...
                    animals(k), ...
                    'ages') || ...
                    isempty(animals(k).ages)

                fprintf( ...
                    'Type %s | animal %d skipped: no ages\n', ...
                    current_type, ...
                    k);

                continue;
            end


            %------------------------------------------------------%
            % Dates
            %------------------------------------------------------%
            if ~isfield( ...
                    animals(k), ...
                    'dates') || ...
                    isempty(animals(k).dates)

                fprintf( ...
                    'Type %s | animal %d skipped: no dates\n', ...
                    current_type, ...
                    k);

                continue;
            end


            current_ages = ...
                animals(k).ages(:);

            current_dates = ...
                animals(k).dates(:);

            current_results = ...
                animals(k).results_analysis;

            animal_name = ...
                char(string(animals(k).animal));

            nRec = ...
                numel(current_ages);


            if nRec == 0
                continue;
            end


            %======================================================%
            % results_analysis -> records
            %======================================================%
            records_k = ...
                results_analysis_to_record_array( ...
                    current_results, ...
                    current_ages, ...
                    current_dates, ...
                    animal_name, ...
                    nRec);


            if isempty(records_k)
                continue;
            end


            if isempty(pooled_records)

                pooled_records = ...
                    records_k(:);

            else

                pooled_records = ...
                    [ ...
                        pooled_records(:); ...
                        records_k(:) ...
                    ];
            end
        end


        %==========================================================%
        % Vérification
        %==========================================================%
        if isempty(pooled_records)

            fprintf( ...
                'Type %s skipped: no pooled data\n', ...
                current_type);

            continue;
        end


        age_values = ...
            [pooled_records.AgeValue]';


        valid_age = ...
            isfinite(age_values);


        pooled_records = ...
            pooled_records(valid_age);

        age_values = ...
            age_values(valid_age);


        if isempty(pooled_records)

            fprintf( ...
                'Type %s skipped: no valid age\n', ...
                current_type);

            continue;
        end


        %==========================================================%
        % Trier par âge
        %==========================================================%
        [~, order_idx] = ...
            sort( ...
                age_values, ...
                'ascend');


        pooled_records = ...
            pooled_records(order_idx);


        %==========================================================%
        % Regrouper par âge
        %==========================================================%
        [ ...
            grouped, ...
            age_centers ...
        ] = ...
            group_metrics_by_age( ...
                pooled_records, ...
                plot_blue);


        if isempty(age_centers)

            fprintf( ...
                'Type %s skipped: no grouped data\n', ...
                current_type);

            continue;
        end


        grouped_by_type.(current_type) = ...
            grouped;

        ages_by_type.(current_type) = ...
            age_centers;


        valid_type_names{end + 1, 1} = ...
            current_type; %#ok<AGROW>
    end
end


function records = results_analysis_to_record_array( ...
        results_analysis, ...
        current_ages, ...
        current_dates, ...
        animal_name, ...
        nRec)

    template = struct( ...
        'Animal', '', ...
        'Date', '', ...
        'AgeRaw', [], ...
        'AgeValue', NaN, ...
        ...
        'FrequencyPerCell_gcamp', [], ...
        'FrequencyPerCell_blue', [], ...
        ...
        'InterEventIntervals_gcamp_ms', [], ...
        'InterEventIntervals_blue_ms', [], ...
        ...
        'BurstFraction_gcamp', [], ...
        ...
        'pairwise_corr_gcamp_gcamp', [], ...
        ...
        'max_corr_gcamp_gcamp_by_plane', [], ...
        'max_corr_gcamp_mtor_by_plane', [], ...
        ...
        'SCEsFrequency', [], ...
        'SCEsCellParticipation_percent', [], ...
        'SCEsduration_ms', []);


    records = ...
        repmat( ...
            template, ...
            nRec, ...
            1);


    for m = 1:nRec

        age_raw = ...
            current_ages{m};

        date_raw = ...
            current_dates{m};


        records(m).Animal = ...
            animal_name;

        records(m).AgeRaw = ...
            age_raw;

        records(m).AgeValue = ...
            parse_one_age( ...
                age_raw);

        records(m).Date = ...
            value_to_text( ...
                date_raw);


        %==========================================================%
        % GCaMP activity
        %==========================================================%
        records(m).FrequencyPerCell_gcamp = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'gcamp_plane', ...
                    'activity', ...
                    'FrequencyPerCell' ...
                }, ...
                m, ...
                nRec);


        records(m).InterEventIntervals_gcamp_ms = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'gcamp_plane', ...
                    'activity', ...
                    'InterEventIntervals_ms' ...
                }, ...
                m, ...
                nRec);


        records(m).BurstFraction_gcamp = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'gcamp_plane', ...
                    'activity', ...
                    'BurstFraction' ...
                }, ...
                m, ...
                nRec);


        %==========================================================%
        % GCaMP correlations
        %==========================================================%

        %----------------------------------------------------------%
        % Matrices pairwise complètes
        %
        % Elles seront transformées plus bas en valeurs uniques
        % hors diagonale.
        %----------------------------------------------------------%
        records(m).pairwise_corr_gcamp_gcamp = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'gcamp_plane', ...
                    'correlations', ...
                    'cross_corr_gcamp_gcamp_by_plane' ...
                }, ...
                m, ...
                nRec);


        %----------------------------------------------------------%
        % Conservé pour compatibilité / autres figures
        %----------------------------------------------------------%
        records(m).max_corr_gcamp_gcamp_by_plane = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'gcamp_plane', ...
                    'correlations', ...
                    'max_corr_gcamp_gcamp_by_plane' ...
                }, ...
                m, ...
                nRec);


        %==========================================================%
        % Blue activity
        %==========================================================%
        records(m).FrequencyPerCell_blue = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'blue_plane', ...
                    'activity', ...
                    'FrequencyPerCell' ...
                }, ...
                m, ...
                nRec);


        records(m).InterEventIntervals_blue_ms = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'blue_plane', ...
                    'activity', ...
                    'InterEventIntervals_ms' ...
                }, ...
                m, ...
                nRec);


        %==========================================================%
        % Blue correlations
        %==========================================================%
        records(m).max_corr_gcamp_mtor_by_plane = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'blue_plane', ...
                    'correlations', ...
                    'max_corr_gcamp_mtor_by_plane' ...
                }, ...
                m, ...
                nRec);


        %==========================================================%
        % SCEs
        %==========================================================%
        records(m).SCEsFrequency = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'gcamp_plane', ...
                    'SCEs', ...
                    'Frequency' ...
                }, ...
                m, ...
                nRec);


        records(m).SCEsCellParticipation_percent = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'gcamp_plane', ...
                    'SCEs', ...
                    'CellParticipation_percent' ...
                }, ...
                m, ...
                nRec);


        records(m).SCEsduration_ms = ...
            get_nested_record_value( ...
                results_analysis, ...
                { ...
                    'gcamp_plane', ...
                    'SCEs', ...
                    'Duration_ms' ...
                }, ...
                m, ...
                nRec);
    end
end


function [grouped, age_centers] = ...
        group_metrics_by_age( ...
            records, ...
            plot_blue)

    age_values = ...
        [records.AgeValue]';


    age_centers = ...
        sort( ...
            unique( ...
                age_values( ...
                    isfinite(age_values))), ...
            'ascend');


    grouped = ...
        struct();


    %==============================================================%
    % GCaMP activity
    %==============================================================%
    grouped.FrequencyPerCell_gcamp = ...
        cell(numel(age_centers), 1);


    grouped.InterEventIntervals_gcamp_ms = ...
        cell(numel(age_centers), 1);


    grouped.BurstFraction_gcamp = ...
        cell(numel(age_centers), 1);


    %==============================================================%
    % GCaMP correlations
    %==============================================================%

    %--------------------------------------------------------------%
    % Pour le radar :
    % toutes les pairwise correlations uniques
    %--------------------------------------------------------------%
    grouped.pairwise_corr_gcamp_gcamp = ...
        cell(numel(age_centers), 1);


    %--------------------------------------------------------------%
    % Conservé pour compatibilité
    %--------------------------------------------------------------%
    grouped.max_corr_gcamp_gcamp_by_plane = ...
        cell(numel(age_centers), 1);


    %==============================================================%
    % Blue
    %==============================================================%
    if plot_blue

        grouped.FrequencyPerCell_blue = ...
            cell(numel(age_centers), 1);


        grouped.InterEventIntervals_blue_ms = ...
            cell(numel(age_centers), 1);


        grouped.max_corr_gcamp_mtor_by_plane = ...
            cell(numel(age_centers), 1);
    end


    %==============================================================%
    % SCEs
    %==============================================================%
    grouped.SCEsFrequency = ...
        cell(numel(age_centers), 1);


    grouped.SCEsCellParticipation_percent = ...
        cell(numel(age_centers), 1);


    grouped.SCEsduration_ms = ...
        cell(numel(age_centers), 1);


    %==============================================================%
    % Metadata regroupement
    %==============================================================%
    grouped.Animals = ...
        cell(numel(age_centers), 1);


    grouped.NRecordings = ...
        zeros(numel(age_centers), 1);


    %==============================================================%
    % Ages
    %==============================================================%
    for a = 1:numel(age_centers)

        this_age = ...
            age_centers(a);


        idx = ...
            find( ...
                age_values == this_age);


        grouped.NRecordings(a) = ...
            numel(idx);


        animals_a = {};


        %==========================================================%
        % Recordings de cet âge
        %==========================================================%
        for ii = 1:numel(idx)

            R = ...
                records(idx(ii));


            %======================================================%
            % Activity
            %======================================================%
            grouped.FrequencyPerCell_gcamp{a} = ...
                append_metric_values( ...
                    grouped.FrequencyPerCell_gcamp{a}, ...
                    R.FrequencyPerCell_gcamp, ...
                    false);


            grouped.InterEventIntervals_gcamp_ms{a} = ...
                append_metric_values( ...
                    grouped.InterEventIntervals_gcamp_ms{a}, ...
                    R.InterEventIntervals_gcamp_ms, ...
                    false);


            grouped.BurstFraction_gcamp{a} = ...
                append_metric_values( ...
                    grouped.BurstFraction_gcamp{a}, ...
                    R.BurstFraction_gcamp, ...
                    false);


            %======================================================%
            % Pairwise correlation
            %
            % true :
            %   pour une matrice carrée de corrélation :
            %   - enlève la diagonale
            %   - garde seulement le triangle supérieur
            %   - chaque paire est donc comptée une seule fois
            %======================================================%
            grouped.pairwise_corr_gcamp_gcamp{a} = ...
                append_metric_values( ...
                    grouped.pairwise_corr_gcamp_gcamp{a}, ...
                    R.pairwise_corr_gcamp_gcamp, ...
                    true);


            %======================================================%
            % Max corr conservée
            %======================================================%
            grouped.max_corr_gcamp_gcamp_by_plane{a} = ...
                append_metric_values( ...
                    grouped.max_corr_gcamp_gcamp_by_plane{a}, ...
                    R.max_corr_gcamp_gcamp_by_plane, ...
                    false);


            %======================================================%
            % Blue
            %======================================================%
            if plot_blue

                grouped.FrequencyPerCell_blue{a} = ...
                    append_metric_values( ...
                        grouped.FrequencyPerCell_blue{a}, ...
                        R.FrequencyPerCell_blue, ...
                        false);


                grouped.InterEventIntervals_blue_ms{a} = ...
                    append_metric_values( ...
                        grouped.InterEventIntervals_blue_ms{a}, ...
                        R.InterEventIntervals_blue_ms, ...
                        false);


                grouped.max_corr_gcamp_mtor_by_plane{a} = ...
                    append_metric_values( ...
                        grouped.max_corr_gcamp_mtor_by_plane{a}, ...
                        R.max_corr_gcamp_mtor_by_plane, ...
                        false);
            end


            %======================================================%
            % SCEs
            %======================================================%
            grouped.SCEsFrequency{a} = ...
                append_metric_values( ...
                    grouped.SCEsFrequency{a}, ...
                    R.SCEsFrequency, ...
                    false);


            grouped.SCEsCellParticipation_percent{a} = ...
                append_metric_values( ...
                    grouped.SCEsCellParticipation_percent{a}, ...
                    R.SCEsCellParticipation_percent, ...
                    false);


            grouped.SCEsduration_ms{a} = ...
                append_metric_values( ...
                    grouped.SCEsduration_ms{a}, ...
                    R.SCEsduration_ms, ...
                    false);


            %======================================================%
            % Animaux
            %======================================================%
            if ~isempty(R.Animal)

                animals_a{end + 1, 1} = ...
                    R.Animal; %#ok<AGROW>
            end
        end


        grouped.Animals{a} = ...
            unique( ...
                animals_a, ...
                'stable');
    end
end


function out = append_metric_values( ...
        out, ...
        x, ...
        is_corr)

    if nargin < 3

        is_corr = ...
            false;
    end


    if isempty(out)

        out = ...
            [];
    end


    vals = ...
        flatten_metric_values( ...
            x, ...
            is_corr);


    if ~isempty(vals)

        out = ...
            [ ...
                out; ...
                vals ...
            ];
    end
end


function vals = flatten_metric_values( ...
        x, ...
        is_corr)

    vals = [];


    if isempty(x)
        return;
    end


    %==============================================================%
    % Cell arrays
    %
    % Typiquement :
    %   une cell par plan contenant une matrice de corrélation
    %==============================================================%
    if iscell(x)

        for i = 1:numel(x)

            vals = ...
                [ ...
                    vals; ...
                    flatten_metric_values( ...
                        x{i}, ...
                        is_corr) ...
                ]; %#ok<AGROW>
        end

        return;
    end


    if isstruct(x)
        return;
    end


    if ~(isnumeric(x) || ...
            islogical(x))

        return;
    end


    x = ...
        double(x);


    %==============================================================%
    % Matrice de corrélation carrée
    %
    % Exemple :
    %
    %       1    r12   r13
    %      r12    1    r23
    %      r13   r23    1
    %
    % On garde uniquement :
    %
    %      r12, r13, r23
    %
    % Donc :
    %   - pas d'autocorrélation
    %   - pas de duplication des paires
    %==============================================================%
    if is_corr && ...
            ismatrix(x) && ...
            size(x,1) > 1 && ...
            size(x,2) > 1 && ...
            size(x,1) == size(x,2)

        keep = ...
            triu( ...
                true(size(x)), ...
                1);


        x = ...
            x(keep);
    end


    vals = ...
        x(:);


    vals = ...
        vals( ...
            isfinite(vals));
end


function value = get_nested_record_value( ...
        S, ...
        path_fields, ...
        idx, ...
        nRec)

    value = [];


    x = ...
        get_nested_field_or_empty( ...
            S, ...
            path_fields);


    if isempty(x)
        return;
    end


    if iscell(x)

        if isvector(x)

            if numel(x) >= idx

                value = ...
                    x{idx};
            end

            return;
        end


        if size(x,1) == nRec && ...
                idx <= size(x,1)

            value = ...
                x(idx,:);

            return;
        end


        if numel(x) >= idx

            value = ...
                x{idx};
        end

        return;
    end


    if isstring(x)

        if numel(x) >= idx

            value = ...
                x(idx);

        elseif idx == 1

            value = ...
                x;
        end

        return;
    end


    if isnumeric(x) || ...
            islogical(x)

        if ~isvector(x) && ...
                size(x,1) == nRec && ...
                idx <= size(x,1)

            value = ...
                x(idx,:);

            return;
        end


        if isvector(x) && ...
                numel(x) == nRec

            value = ...
                x(idx);

            return;
        end


        if idx == 1

            value = ...
                x;
        end

        return;
    end


    if idx == 1

        value = ...
            x;
    end
end


function x = get_nested_field_or_empty( ...
        S, ...
        path_fields)

    x = [];


    current = ...
        S;


    for i = 1:numel(path_fields)

        fn = ...
            path_fields{i};


        if ~isstruct(current) || ...
                ~isfield(current, fn)

            return;
        end


        current = ...
            current.(fn);
    end


    x = ...
        current;
end


function age_value = parse_one_age( ...
        age_raw)

    age_value = ...
        NaN;


    if isempty(age_raw)
        return;
    end


    if isnumeric(age_raw) || ...
            islogical(age_raw)

        age_raw = ...
            double(age_raw);


        if isscalar(age_raw) && ...
                isfinite(age_raw)

            age_value = ...
                age_raw;
        end

        return;
    end


    if iscell(age_raw)

        if ~isempty(age_raw)

            age_value = ...
                parse_one_age( ...
                    age_raw{1});
        end

        return;
    end


    if isstring(age_raw) || ...
            ischar(age_raw)

        tok = ...
            regexp( ...
                char(age_raw), ...
                '\d+', ...
                'match', ...
                'once');


        if ~isempty(tok)

            age_value = ...
                str2double(tok);
        end
    end
end


function txt = value_to_text(x)

    txt = '';


    if isempty(x)
        return;
    end


    if iscell(x)

        if ~isempty(x)

            txt = ...
                value_to_text( ...
                    x{1});
        end

        return;
    end


    if isdatetime(x)

        txt = ...
            char(string(x));

        return;
    end


    if isstring(x)

        if ~isempty(x)

            txt = ...
                char(x(1));
        end

        return;
    end


    if ischar(x)

        txt = ...
            x;

        return;
    end


    if isnumeric(x) || ...
            islogical(x)

        if isscalar(x)

            txt = ...
                char(string(x));
        end
    end
end