function create_ppt_from_figs(current_group_paths, daytime)

        % Importer la bibliothèque pour PowerPoint
        import mlreportgen.ppt.*;
        
        % Créer et ouvrir une présentation PowerPoint
        pptFileName = sprintf('AnalysisFigures_%s.pptx', daytime);
        ppt = Presentation(pptFileName);
        
        open(ppt);
        
        % Ajouter une diapositive de titre initiale
        slide = add(ppt, 'Title Slide');
        replace(slide, 'Title', 'Analysis Results');
        replace(slide, 'Subtitle', 'Generated by MATLAB');
        
        % Parcourir les chemins des groupes et ajouter les figures
        for group_idx = 1:length(current_group_paths)
            group_paths = current_group_paths{group_idx};
            
            for path_idx = 1:length(group_paths)
                figure_folder = group_paths{path_idx};
                
                % Recherche des fichiers PNG dans le dossier actuel
                png_files = dir(fullfile(figure_folder, '*.png'));
                
                for file_idx = 1:length(png_files)
                    figure_path = fullfile(png_files(file_idx).folder, png_files(file_idx).name);
                    
                    % Ajouter une diapositive pour chaque figure
                    slide = add(ppt, 'Title and Content');
                    
                    % Ajouter un titre à la diapositive (le nom du fichier image sans extension)
                    [~, figure_name, ~] = fileparts(png_files(file_idx).name);
                    
                    % Enlever les underscores et remplacer par des espaces
                    figure_name = strrep(figure_name, '_', ' ');
                    
                    % Remplacer le titre de la diapositive par le nom de la figure
                    replace(slide, 'Title', figure_name);
                    
                    % Ajouter l'image sur la diapositive
                    img = Picture(figure_path);
                    replace(slide, 'Content', img); % Remplace le contenu par l'image
                end
            end
        end
        
        % Sauvegarder et fermer la présentation
        close(ppt);
        disp('PowerPoint presentation saved as AnalysisFigures.pptx.');
end
