function recap_all = create_summary_sheets(selected_groups)

% =========================================================
% TABLEAU FINAL
% =========================================================
%
% Une ligne = un recording GCaMP
%
% Colonnes :
%   Type
%   Line
%   Animal
%   Date
%   TSeries
%   Comment
%
% Interface :
%   Une seule fenêtre par lignée mTOR.
%   Une ligne par TSeries GCaMP avec :
%       Animal | Date | chemin TSeries | Commentaire | Action
%
%   Action =
%       Ajouter   si aucun commentaire
%       Modifier  si commentaire existant
% =========================================================

recap_all = ...
    table( ...
        'Size', [0 6], ...
        'VariableTypes', { ...
            'string', ...
            'string', ...
            'string', ...
            'string', ...
            'string', ...
            'string'}, ...
        'VariableNames', { ...
            'Type', ...
            'Line', ...
            'Animal', ...
            'Date', ...
            'TSeries', ...
            'Comment'});

if nargin < 1 || isempty(selected_groups)
    return;
end

% =========================================================
% TABLE INTERNE
% =========================================================
%
% TSeriesPath et OutputFile servent uniquement à l'interface
% et à la sauvegarde.
% =========================================================

recordings = ...
    table( ...
        'Size', [0 8], ...
        'VariableTypes', { ...
            'string', ...
            'string', ...
            'string', ...
            'string', ...
            'string', ...
            'string', ...
            'string', ...
            'string'}, ...
        'VariableNames', { ...
            'Type', ...
            'Line', ...
            'Animal', ...
            'Date', ...
            'TSeries', ...
            'TSeriesPath', ...
            'Comment', ...
            'OutputFile'});

type_names = ...
    fieldnames(selected_groups);

% =========================================================
% RÉCUPÉRER TOUS LES RECORDINGS
% =========================================================

for t = 1:numel(type_names)

    current_type = ...
        type_names{t};

    for k = 1:numel(selected_groups.(current_type))

        current_group = ...
            selected_groups.(current_type)(k);

        % -------------------------------------------------
        % Lignée
        % -------------------------------------------------

        current_line = '';

        if isfield(current_group, 'line') && ...
                ~isempty(current_group.line)

            current_line = ...
                current_group.line;
        end

        % -------------------------------------------------
        % Animal
        % -------------------------------------------------

        current_animal = '';

        if isfield(current_group, 'animal') && ...
                ~isempty(current_group.animal)

            current_animal = ...
                current_group.animal;
        end

        % -------------------------------------------------
        % Paths
        % -------------------------------------------------

        if ~isfield(current_group, 'paths') || ...
                ~isstruct(current_group.paths)

            fprintf( ...
                'Pas de paths pour %s | %s -> skip.\n', ...
                current_type, ...
                string(current_animal));

            continue;
        end

        current_paths = ...
            current_group.paths;

        % -------------------------------------------------
        % TSeries
        %
        % Colonne 1 = GCaMP
        % -------------------------------------------------

        if ~isfield(current_paths, 'TSeries') || ...
                isempty(current_paths.TSeries)

            fprintf( ...
                'Pas de TSeries pour %s | %s -> skip.\n', ...
                current_type, ...
                string(current_animal));

            continue;
        end

        current_TSeries = ...
            current_paths.TSeries;

        nRecordings = ...
            size(current_TSeries, 1);

        for idx = 1:nRecordings

            % =============================================
            % TSeries GCaMP
            % =============================================

            if size(current_TSeries, 2) < 1 || ...
                    isempty(current_TSeries{idx,1})

                continue;
            end

            tseries_path = ...
                current_TSeries{idx,1};

            tseries_path_for_name = ...
                value_to_string(tseries_path);

            while ~isempty(tseries_path_for_name) && ...
                    ( ...
                        tseries_path_for_name(end) == '\' || ...
                        tseries_path_for_name(end) == '/' ...
                    )

                tseries_path_for_name(end) = [];
            end

            [~, tseries_name] = ...
                fileparts( ...
                    tseries_path_for_name);

            % =============================================
            % Date
            % =============================================

            current_date = '';

            if isfield(current_group, 'dates') && ...
                    numel(current_group.dates) >= idx && ...
                    ~isempty(current_group.dates{idx})

                current_date = ...
                    current_group.dates{idx};

            elseif isfield(current_group, 'metadata') && ...
                    isstruct(current_group.metadata) && ...
                    isfield(current_group.metadata, 'gcamp_plane') && ...
                    isfield(current_group.metadata.gcamp_plane, 'Date')

                dates_metadata = ...
                    current_group.metadata.gcamp_plane.Date;

                if iscell(dates_metadata)

                    if numel(dates_metadata) >= idx

                        current_date = ...
                            dates_metadata{idx};
                    end

                elseif numel(dates_metadata) >= idx

                    current_date = ...
                        dates_metadata(idx);
                end
            end

            % =============================================
            % Dossier de la fiche
            % =============================================

            output_folder = '';

            if isfield(current_paths, 'gcamp_root') && ...
                    ~isempty(current_paths.gcamp_root) && ...
                    numel(current_paths.gcamp_root) >= idx && ...
                    ~isempty(current_paths.gcamp_root{idx})

                output_folder = ...
                    current_paths.gcamp_root{idx};
            end

            % =============================================
            % Fichier de résumé
            % =============================================

            output_file = '';
            current_comment = '';

            if ~isempty(output_folder)

                output_folder = ...
                    value_to_string(output_folder);

                if ~exist(output_folder, 'dir')
                    mkdir(output_folder);
                end

                % Ancien format sans TSeries
                old_output_file = ...
                    fullfile( ...
                        output_folder, ...
                        sprintf( ...
                            'recording_summary_%s_%s.txt', ...
                            value_to_filename(current_animal), ...
                            value_to_filename(current_date)));

                % Nouveau format avec TSeries GCaMP
                output_file = ...
                    fullfile( ...
                        output_folder, ...
                        sprintf( ...
                            'recording_summary_%s_%s_%s.txt', ...
                            value_to_filename(current_animal), ...
                            value_to_filename(current_date), ...
                            value_to_filename(tseries_name)));

                % -----------------------------------------
                % Compatibilité ancienne fiche
                % -----------------------------------------

                if exist(output_file, 'file') ~= 2 && ...
                        exist(old_output_file, 'file') == 2

                    movefile( ...
                        old_output_file, ...
                        output_file);

                    fprintf( ...
                        'Ancienne fiche renommée : %s -> %s\n', ...
                        old_output_file, ...
                        output_file);
                end

                % -----------------------------------------
                % Charger commentaire existant
                % -----------------------------------------

                if exist(output_file, 'file') == 2

                    current_comment = ...
                        read_summary_comment( ...
                            output_file);

                % -----------------------------------------
                % Créer la fiche si elle n'existe pas
                % -----------------------------------------

                else

                    write_summary_file( ...
                        output_file, ...
                        current_type, ...
                        current_line, ...
                        current_animal, ...
                        current_date, ...
                        tseries_name, ...
                        current_comment);

                    fprintf( ...
                        'Fiche créée : %s\n', ...
                        output_file);
                end
            end

            % =============================================
            % AJOUT TABLE INTERNE
            % =============================================

            new_row = ...
                table( ...
                    string(current_type), ...
                    string(current_line), ...
                    string(current_animal), ...
                    string(current_date), ...
                    string(tseries_name), ...
                    string(tseries_path_for_name), ...
                    string(current_comment), ...
                    string(output_file), ...
                    'VariableNames', { ...
                        'Type', ...
                        'Line', ...
                        'Animal', ...
                        'Date', ...
                        'TSeries', ...
                        'TSeriesPath', ...
                        'Comment', ...
                        'OutputFile'});

            recordings = ...
                [ ...
                    recordings; ...
                    new_row ...
                ];
        end
    end
end

if isempty(recordings)
    return;
end

% =========================================================
% UNE FENÊTRE PAR LIGNÉE mTOR
% =========================================================

line_names = ...
    unique( ...
        recordings.Line, ...
        'stable');

for l = 1:numel(line_names)

    current_line = ...
        line_names(l);

    line_idx = ...
        find( ...
            recordings.Line == current_line);

    line_recordings = ...
        recordings(line_idx, :);

    line_recordings = ...
        show_lineage_recap( ...
            line_recordings, ...
            current_line);

    recordings.Comment(line_idx) = ...
        line_recordings.Comment;
end

% =========================================================
% TABLEAU FINAL
% =========================================================

recap_all = ...
    recordings( ...
        :, ...
        { ...
            'Type', ...
            'Line', ...
            'Animal', ...
            'Date', ...
            'TSeries', ...
            'Comment' ...
        });

end


%% ========================================================================
% INTERFACE : RÉCAPITULATIF D'UNE LIGNÉE
% ========================================================================

function line_recordings = show_lineage_recap( ...
        line_recordings, ...
        current_line)

nRecordings = ...
    height(line_recordings);

if nRecordings == 0
    return;
end

line_name = ...
    value_to_string(current_line);

if isempty(line_name)
    line_name = ...
        'Sans lignée';
end

% =========================================================
% DIMENSIONS
% =========================================================

screen_size = ...
    get( ...
        0, ...
        'ScreenSize');

window_width = ...
    min( ...
        1000, ...
        screen_size(3) - 80);

window_height = ...
    min( ...
        600, ...
        screen_size(4) - 100);

window_x = ...
    max( ...
        20, ...
        (screen_size(3) - window_width) / 2);

window_y = ...
    max( ...
        20, ...
        (screen_size(4) - window_height) / 2);

fig = ...
    uifigure( ...
        'Name', ...
            sprintf( ...
                'Récapitulatif recordings - %s', ...
                line_name), ...
        'Position', [ ...
            window_x, ...
            window_y, ...
            window_width, ...
            window_height]);

fig.CloseRequestFcn = ...
    @close_lineage_recap;

% =========================================================
% GRILLE PRINCIPALE
% =========================================================

main_grid = ...
    uigridlayout( ...
        fig, ...
        [2 1]);

main_grid.RowHeight = ...
    {48, '1x'};

main_grid.ColumnWidth = ...
    {'1x'};

% ---------------------------------------------------------
% Titre
% ---------------------------------------------------------

title_label = ...
    uilabel( ...
        main_grid, ...
        'Text', ...
            sprintf( ...
                '%s   —   %d TSeries GCaMP', ...
                line_name, ...
                nRecordings), ...
        'FontSize', 18, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left');

title_label.Layout.Row = 1;
title_label.Layout.Column = 1;

% ---------------------------------------------------------
% Zone scrollable
% ---------------------------------------------------------

scroll_panel = ...
    uipanel( ...
        main_grid, ...
        'BorderType', 'none');

scroll_panel.Layout.Row = 2;
scroll_panel.Layout.Column = 1;

records_grid = ...
    uigridlayout( ...
        scroll_panel, ...
        [nRecordings + 1, 5]);

records_grid.Scrollable = ...
    'on';

records_grid.ColumnWidth = ...
    {100, 110, 280, 280, 110};

records_grid.RowHeight = ...
    [ ...
        {30}, ...
        repmat( ...
            {52}, ...
            1, ...
            nRecordings) ...
    ];

records_grid.Padding = ...
    [8 8 8 8];

records_grid.RowSpacing = ...
    3;

records_grid.ColumnSpacing = ...
    5;

% =========================================================
% EN-TÊTES
% =========================================================

header_names = ...
    { ...
        'Animal', ...
        'Date', ...
        'TSeries GCaMP', ...
        'Commentaire', ...
        'Action' ...
    };

for c = 1:numel(header_names)

    header = ...
        uilabel( ...
            records_grid, ...
            'Text', header_names{c}, ...
            'FontWeight', 'bold', ...
            'FontSize', 12, ...
            'HorizontalAlignment', 'left');

    header.Layout.Row = 1;
    header.Layout.Column = c;
end

% =========================================================
% LIGNES RECORDINGS
% =========================================================

comment_boxes = ...
    gobjects( ...
        nRecordings, ...
        1);

action_buttons = ...
    gobjects( ...
        nRecordings, ...
        1);

for r = 1:nRecordings

    current_row = ...
        r + 1;

    % -----------------------------------------------------
    % Animal
    % -----------------------------------------------------

    animal_label = ...
        uilabel( ...
            records_grid, ...
            'Text', ...
                value_to_string( ...
                    line_recordings.Animal(r)), ...
            'FontSize', 11, ...
            'HorizontalAlignment', 'left');

    animal_label.Layout.Row = current_row;
    animal_label.Layout.Column = 1;

    % -----------------------------------------------------
    % Date
    % -----------------------------------------------------

    date_label = ...
        uilabel( ...
            records_grid, ...
            'Text', ...
                value_to_string( ...
                    line_recordings.Date(r)), ...
            'FontSize', 11, ...
            'HorizontalAlignment', 'left');

    date_label.Layout.Row = current_row;
    date_label.Layout.Column = 2;

    % -----------------------------------------------------
    % Chemin complet TSeries
    % -----------------------------------------------------

    tseries_label = ...
        uilabel( ...
            records_grid, ...
            'Text', ...
                value_to_string( ...
                    line_recordings.TSeries(r)), ...
            'FontSize', 11, ...
            'HorizontalAlignment', 'left');

    tseries_label.Layout.Row = current_row;
    tseries_label.Layout.Column = 3;

    % -----------------------------------------------------
    % Commentaire actuel
    % -----------------------------------------------------

    current_comment = ...
        value_to_string( ...
            line_recordings.Comment(r));

    if isempty(strtrim(current_comment))

        display_comment = ...
            'Aucun commentaire';

    else

        display_comment = ...
            current_comment;
    end

    comment_boxes(r) = ...
        uitextarea( ...
            records_grid, ...
            'Value', ...
                splitlines_for_textarea( ...
                    display_comment), ...
            'Editable', 'off', ...
            'FontSize', 10);

    comment_boxes(r).Layout.Row = current_row;
    comment_boxes(r).Layout.Column = 4;

    % -----------------------------------------------------
    % Bouton Ajouter / Modifier
    % -----------------------------------------------------

    if isempty(strtrim(current_comment))

        button_text = ...
            'Ajouter';

    else

        button_text = ...
            'Modifier';
    end

    action_buttons(r) = ...
        uibutton( ...
            records_grid, ...
            'push', ...
            'Text', button_text, ...
            'FontSize', 11, ...
            'ButtonPushedFcn', ...
                @edit_lineage_comment);

    action_buttons(r).Layout.Row = current_row;
    action_buttons(r).Layout.Column = 5;

    action_buttons(r).UserData = ...
        struct( ...
            'Row', r, ...
            'Figure', fig);
end

% =========================================================
% DONNÉES DE L'INTERFACE
% =========================================================

fig.UserData = ...
    struct( ...
        'Recordings', line_recordings, ...
        'CommentBoxes', comment_boxes, ...
        'ActionButtons', action_buttons);

% =========================================================
% ATTENDRE FERMETURE
% =========================================================

uiwait(fig);

if isvalid(fig)

    data = ...
        fig.UserData;

    line_recordings = ...
        data.Recordings;

    delete(fig);
end

end


%% ========================================================================
% CALLBACK : AJOUTER / MODIFIER COMMENTAIRE
% ========================================================================

function edit_lineage_comment(src, ~)

info = ...
    src.UserData;

fig = ...
    info.Figure;

if isempty(fig) || ...
        ~isvalid(fig)

    return;
end

row_idx = ...
    info.Row;

data = ...
    fig.UserData;

line_recordings = ...
    data.Recordings;

tseries_path = ...
    value_to_string( ...
        line_recordings.TSeriesPath(row_idx));

existing_comment = ...
    value_to_string( ...
        line_recordings.Comment(row_idx));

if isempty(strtrim(existing_comment))

    dialog_title = ...
        'Ajouter un commentaire';

    default_answer = ...
        {''};

else

    dialog_title = ...
        'Modifier le commentaire';

    default_answer = ...
        {existing_comment};
end

comment_answer = ...
    inputdlg( ...
        sprintf( ...
            'Commentaire pour le TSeries GCaMP :\n%s', ...
            tseries_path), ...
        dialog_title, ...
        [8 140], ...
        default_answer);

if isempty(comment_answer)
    return;
end

new_comment = ...
    value_to_string( ...
        comment_answer{1});

line_recordings.Comment(row_idx) = ...
    string(new_comment);

output_file = ...
    value_to_string( ...
        line_recordings.OutputFile(row_idx));

if ~isempty(output_file)

    write_summary_file( ...
        output_file, ...
        line_recordings.Type(row_idx), ...
        line_recordings.Line(row_idx), ...
        line_recordings.Animal(row_idx), ...
        line_recordings.Date(row_idx), ...
        line_recordings.TSeries(row_idx), ...
        new_comment);

    fprintf( ...
        'Commentaire mis à jour : %s\n', ...
        output_file);
end

% ---------------------------------------------------------
% Mettre à jour l'affichage
% ---------------------------------------------------------

if isempty(strtrim(new_comment))

    data.CommentBoxes(row_idx).Value = ...
        {'Aucun commentaire'};

    data.ActionButtons(row_idx).Text = ...
        'Ajouter';

else

    data.CommentBoxes(row_idx).Value = ...
        splitlines_for_textarea( ...
            new_comment);

    data.ActionButtons(row_idx).Text = ...
        'Modifier';
end

data.Recordings = ...
    line_recordings;

fig.UserData = ...
    data;

end


%% ========================================================================
% CALLBACK : FERMETURE CROIX
% ========================================================================

function close_lineage_recap(src, ~)

if isempty(src) || ...
        ~isvalid(src)

    return;
end

uiresume(src);

end


%% ========================================================================
% ÉCRITURE FICHE
% ========================================================================

function write_summary_file( ...
        output_file, ...
        current_type, ...
        current_line, ...
        current_animal, ...
        current_date, ...
        tseries_name, ...
        current_comment)

fid = ...
    fopen( ...
        output_file, ...
        'w');

if fid == -1

    error( ...
        'Impossible de créer le fichier : %s', ...
        output_file);
end

fprintf(fid, 'FICHE ENREGISTREMENT\n');
fprintf(fid, '====================\n\n');

fprintf( ...
    fid, ...
    'Type       : %s\n', ...
    value_to_string(current_type));

fprintf( ...
    fid, ...
    'Line       : %s\n', ...
    value_to_string(current_line));

fprintf( ...
    fid, ...
    'Animal     : %s\n', ...
    value_to_string(current_animal));

fprintf( ...
    fid, ...
    'Date       : %s\n', ...
    value_to_string(current_date));

fprintf( ...
    fid, ...
    'TSeries    : %s\n\n', ...
    value_to_string(tseries_name));

fprintf(fid, 'COMMENTAIRES\n');
fprintf(fid, '------------\n');

fprintf( ...
    fid, ...
    '%s\n', ...
    value_to_string(current_comment));

fclose(fid);

end


%% ========================================================================
% LECTURE COMMENTAIRE
% ========================================================================

function comment_text = read_summary_comment(output_file)

comment_text = '';

if exist(output_file, 'file') ~= 2
    return;
end

txt = ...
    fileread( ...
        output_file);

lines = ...
    regexp( ...
        txt, ...
        '\r\n|\n|\r', ...
        'split');

comment_idx = ...
    find( ...
        strcmp( ...
            strtrim(lines), ...
            'COMMENTAIRES'), ...
        1, ...
        'first');

if isempty(comment_idx)
    return;
end

start_idx = ...
    comment_idx + 2;

if start_idx > numel(lines)
    return;
end

comment_lines = ...
    lines(start_idx:end);

old_end = ...
    find( ...
        strcmp( ...
            strtrim(comment_lines), ...
            'INFOS ENREGISTREMENT'), ...
        1, ...
        'first');

if ~isempty(old_end)

    comment_lines = ...
        comment_lines(1:old_end-1);
end

while ~isempty(comment_lines) && ...
        isempty(strtrim(comment_lines{1}))

    comment_lines(1) = [];
end

while ~isempty(comment_lines) && ...
        isempty(strtrim(comment_lines{end}))

    comment_lines(end) = [];
end

if isempty(comment_lines)
    return;
end

comment_text = ...
    strjoin( ...
        comment_lines, ...
        newline);

if strcmpi(strtrim(comment_text), 'NA')

    comment_text = ...
        '';
end

end


%% ========================================================================
% TEXTE POUR UITEXTAREA
% ========================================================================

function lines = splitlines_for_textarea(value)

value = ...
    value_to_string(value);

if isempty(value)

    lines = ...
        {''};

    return;
end

lines = ...
    regexp( ...
        value, ...
        '\r\n|\n|\r', ...
        'split');

if isempty(lines)

    lines = ...
        {value};
end

end


%% ========================================================================
% CONVERSION NOM FICHIER
% ========================================================================

function filename_str = value_to_filename(value)

filename_str = ...
    value_to_string(value);

if strcmp(filename_str, 'NA')

    filename_str = ...
        'unknown';
end

filename_str = ...
    regexprep( ...
        filename_str, ...
        '[^\w\-]', ...
        '_');

end


%% ========================================================================
% CONVERSION TEXTE
% ========================================================================

function str = value_to_string(value)

if isempty(value)

    str = ...
        '';

elseif ischar(value)

    if size(value, 1) > 1

        lines = ...
            cellstr(value);

        lines = ...
            cellfun( ...
                @deblank, ...
                lines, ...
                'UniformOutput', ...
                false);

        str = ...
            strjoin( ...
                lines, ...
                newline);

    else

        str = ...
            value;
    end

elseif isstring(value)

    if isscalar(value)

        str = ...
            char(value);

    else

        str = ...
            strjoin( ...
                cellstr(value), ...
                newline);
    end

elseif isnumeric(value) || ...
        islogical(value)

    if isscalar(value)

        str = ...
            num2str(value);

    else

        str = ...
            mat2str(value);
    end

else

    str = ...
        char(string(value));
end

end
