function create_ppt_from_figs(ani_name_groups, ani_path_groups, gcamp_output_folders_groups, ani_age_groups, env_groups, daytime)

    % Importer la bibliothèque pour PowerPoint
    import mlreportgen.ppt.*;
    
    % Définir le chemin de sauvegarde du fichier PowerPoint
    pptFileName = fullfile('D:\Imaging\Outputs\Presentations', sprintf('AnalysisFigures_%s.pptx', daytime));
    
    % Créer et ouvrir une présentation PowerPoint
    ppt = Presentation(pptFileName);
    open(ppt);
    
    % Ajouter une diapositive de titre initiale
    slide = add(ppt, 'Title Slide');
    replace(slide, 'Title', 'Analysis Results');
    replace(slide, 'Subtitle', 'Generated by MATLAB');
    
    % Parcourir les chemins des groupes et ajouter les figures
    for gcamp_idx = 1:length(gcamp_output_folders_groups)
        
        % Add a slide with the name of the animal
        slide = add(ppt, 'Title Slide');
        figure_name = ani_name_groups{gcamp_idx};      
        replace(slide, 'Title', figure_name);       
        

        
        % Add a Slide with a Table
        tableSlide = add(ppt,'Title and Table');
        replace(tableSlide,'Title','Parameters');
        
        gcamp_paths = gcamp_output_folders_groups{gcamp_idx};
        env_paths = env_groups{gcamp_idx};
        [all_recording_time, all_optical_zoom, all_depth, all_duration_minutes] = find_recording_infos(gcamp_paths,env_paths);
        ani_ages = ani_age_groups{gcamp_idx};
        
        % Nouvelle table
        paramTable = Table();
        colSpecs(1) = ColSpec('2in'); % Age
        colSpecs(2) = ColSpec('2in'); % Recording time
        colSpecs(3) = ColSpec('2in'); % Depth
        colSpecs(4) = ColSpec('2in'); % Duration
        paramTable.ColSpecs = colSpecs;
        
        % Créer la ligne d'en-tête
        headerRow = TableRow();
        headerRow.Style = {Bold(true)};
        append(headerRow, TableEntry(Paragraph('Animal Age')));
        append(headerRow, TableEntry(Paragraph('Recording time')));
        append(headerRow, TableEntry(Paragraph('Depth')));
        append(headerRow, TableEntry(Paragraph('Duration (minutes)')));
        append(paramTable, headerRow);
        
        % Boucle sur chaque path pour remplir les lignes
        for path_idx = 1:length(gcamp_paths)
            ani_age = ani_ages{path_idx};
            recording_time = all_recording_time{path_idx};
            depth = all_depth{path_idx};
            duration_minutes = all_duration_minutes{path_idx};
        
            % Créer une nouvelle ligne pour chaque enregistrement
            row = TableRow();
            append(row, TableEntry(Paragraph(string(ani_age))));
            append(row, TableEntry(Paragraph(string(recording_time))));
            append(row, TableEntry(Paragraph(string(depth))));
            append(row, TableEntry(Paragraph(string(duration_minutes))));
            
            append(paramTable, row);
        end
        
        % Remplacer la table sur la slide
        replace(tableSlide, 'Table', paramTable);

        

        % Recherche des fichiers PNG dans le dossier actuel
        figure_folder = ani_path_groups{gcamp_idx};
        png_files = dir(fullfile(figure_folder, '*.png'));
        
        for file_idx = 1:length(png_files)
            figure_path = fullfile(png_files(file_idx).folder, png_files(file_idx).name);
            
            % Ajouter une diapositive pour chaque figure
            slide = add(ppt, 'Title and Picture');
            
            % Ajouter un titre à la diapositive (le nom du fichier image sans extension)
            [~, figure_name, ~] = fileparts(png_files(file_idx).name);
            
            % Enlever les underscores et remplacer par des espaces
            figure_name = strrep(figure_name, '_', ' ');
            
            % Remplacer le titre de la diapositive par le nom de la figure
            replace(slide, 'Title', figure_name);
            
            % Ajouter l'image sur la diapositive
            img = Picture(figure_path);
            replace(slide, 'Picture', img); % Remplace le contenu par l'image
        end



        for path_idx = 1:length(gcamp_paths)
            figure_folder = gcamp_paths{path_idx};
            
            % Recherche des fichiers PNG dans le dossier actuel
            png_files = dir(fullfile(figure_folder, '*.png'));
            
            for file_idx = 1:length(png_files)
                figure_path = fullfile(png_files(file_idx).folder, png_files(file_idx).name);
                
                % Ajouter une diapositive pour chaque figure
                slide = add(ppt, 'Title and Picture');
                
                % Ajouter un titre à la diapositive (le nom du fichier image sans extension)
                [~, figure_name, ~] = fileparts(png_files(file_idx).name);
                
                % Enlever les underscores et remplacer par des espaces
                figure_name = strrep(figure_name, '_', ' ');
                
                % Remplacer le titre de la diapositive par le nom de la figure
                replace(slide, 'Title', figure_name);
                
                % Ajouter l'image sur la diapositive
                img = Picture(figure_path);
                replace(slide, 'Picture', img); % Remplace le contenu par l'image
            end
        end
    end
    
    % Sauvegarder et fermer la présentation
    close(ppt);
    fprintf('PowerPoint presentation saved as %s\n', pptFileName);

end
