function recap_all = create_summary_sheets(selected_groups)

% =========================================================
% TABLEAU FINAL
% =========================================================
%
% Une ligne = un recording GCaMP
%
% Colonnes :
%   Type
%   Line
%   Animal
%   Date
%   TSeries
%   Comment
% =========================================================

recap_all = ...
    table( ...
        'Size', [0 6], ...
        'VariableTypes', { ...
            'string', ...
            'string', ...
            'string', ...
            'string', ...
            'string', ...
            'string'}, ...
        'VariableNames', { ...
            'Type', ...
            'Line', ...
            'Animal', ...
            'Date', ...
            'TSeries', ...
            'Comment'});

if nargin < 1 || isempty(selected_groups)
    return;
end

type_names = ...
    fieldnames(selected_groups);

% =========================================================
% TYPES
% =========================================================

for t = 1:numel(type_names)

    current_type = ...
        type_names{t};

    % =====================================================
    % ANIMAUX
    % =====================================================

    for k = 1:numel(selected_groups.(current_type))

        current_group = ...
            selected_groups.(current_type)(k);

        % -------------------------------------------------
        % Lignée
        % -------------------------------------------------

        current_line = '';

        if isfield(current_group, 'line') && ...
                ~isempty(current_group.line)

            current_line = ...
                current_group.line;
        end

        % -------------------------------------------------
        % Animal
        % -------------------------------------------------

        current_animal = '';

        if isfield(current_group, 'animal') && ...
                ~isempty(current_group.animal)

            current_animal = ...
                current_group.animal;
        end

        % -------------------------------------------------
        % Paths
        % -------------------------------------------------

        if ~isfield(current_group, 'paths') || ...
                ~isstruct(current_group.paths)

            fprintf( ...
                'Pas de paths pour %s | %s -> skip.\n', ...
                current_type, ...
                string(current_animal));

            continue;
        end

        current_paths = ...
            current_group.paths;

        % -------------------------------------------------
        % TSeries
        %
        % Colonne 1 = GCaMP
        % -------------------------------------------------

        if ~isfield(current_paths, 'TSeries') || ...
                isempty(current_paths.TSeries)

            fprintf( ...
                'Pas de TSeries pour %s | %s -> skip.\n', ...
                current_type, ...
                string(current_animal));

            continue;
        end

        current_TSeries = ...
            current_paths.TSeries;

        nRecordings = ...
            size(current_TSeries, 1);

        % =================================================
        % RECORDINGS
        % =================================================

        for idx = 1:nRecordings

            % =============================================
            % TSeries GCaMP
            % =============================================

            if size(current_TSeries, 2) < 1 || ...
                    isempty(current_TSeries{idx,1})

                continue;
            end

            tseries_path = ...
                current_TSeries{idx,1};

            % ---------------------------------------------
            % Nom du dossier TSeries seulement
            % ---------------------------------------------

            tseries_path_for_name = ...
                tseries_path;

            % Retirer un éventuel "\" final
            while ~isempty(tseries_path_for_name) && ...
                    ( ...
                        tseries_path_for_name(end) == '\' || ...
                        tseries_path_for_name(end) == '/' ...
                    )

                tseries_path_for_name(end) = [];
            end

            [~, tseries_name] = ...
                fileparts( ...
                    tseries_path_for_name);

            % =============================================
            % Date
            % =============================================

            current_date = '';

            % ---------------------------------------------
            % Source principale : current_group.dates
            % ---------------------------------------------

            if isfield(current_group, 'dates') && ...
                    numel(current_group.dates) >= idx && ...
                    ~isempty(current_group.dates{idx})

                current_date = ...
                    current_group.dates{idx};

            % ---------------------------------------------
            % Fallback : metadata.gcamp_plane.Date
            % ---------------------------------------------

            elseif isfield(current_group, 'metadata') && ...
                    isstruct(current_group.metadata) && ...
                    isfield(current_group.metadata, 'gcamp_plane') && ...
                    isfield(current_group.metadata.gcamp_plane, 'Date')

                dates_metadata = ...
                    current_group.metadata.gcamp_plane.Date;

                if iscell(dates_metadata)

                    if numel(dates_metadata) >= idx

                        current_date = ...
                            dates_metadata{idx};
                    end

                elseif numel(dates_metadata) >= idx

                    current_date = ...
                        dates_metadata(idx);
                end
            end

            % =============================================
            % Dossier dans lequel se trouve la fiche
            % =============================================

            output_folder = '';

            if isfield(current_paths, 'gcamp_root') && ...
                    ~isempty(current_paths.gcamp_root) && ...
                    numel(current_paths.gcamp_root) >= idx && ...
                    ~isempty(current_paths.gcamp_root{idx})

                output_folder = ...
                    current_paths.gcamp_root{idx};
            end

            % =============================================
            % Commentaire
            % =============================================

            current_comment = '';

            if ~isempty(output_folder)

                if ~exist(output_folder, 'dir')
                    mkdir(output_folder);
                end

                % -----------------------------------------
                % Nom de la fiche
                %
                % recording_summary_ANIMAL_DATE.txt
                % -----------------------------------------

                output_file = ...
                    fullfile( ...
                        output_folder, ...
                        sprintf( ...
                            'recording_summary_%s_%s.txt', ...
                            value_to_filename(current_animal), ...
                            value_to_filename(current_date)));

                file_exists = ...
                    exist(output_file, 'file') == 2;

                % =========================================
                % FICHE EXISTANTE
                % =========================================

                if file_exists

                    existing_comment = ...
                        read_summary_comment( ...
                            output_file);

                    current_comment = ...
                        existing_comment;

                    % -------------------------------------
                    % Commentaire déjà présent
                    % -------------------------------------

                    if ~isempty(strtrim(existing_comment))

                        choice = ...
                            questdlg( ...
                                sprintf( ...
                                    ['Commentaire actuel :\n\n%s\n\n' ...
                                     'Que voulez-vous faire ?'], ...
                                    existing_comment), ...
                                sprintf( ...
                                    '%s | %s | %s', ...
                                    current_type, ...
                                    value_to_string(current_animal), ...
                                    value_to_string(current_date)), ...
                                'Conserver', ...
                                'Modifier', ...
                                'Conserver');

                        % ---------------------------------
                        % Modifier
                        % ---------------------------------

                        if strcmp(choice, 'Modifier')

                            comment_answer = ...
                                inputdlg( ...
                                    sprintf( ...
                                        'Commentaire pour %s | %s | %s :', ...
                                        current_type, ...
                                        value_to_string(current_animal), ...
                                        value_to_string(current_date)), ...
                                    'Modifier le commentaire', ...
                                    [5 80], ...
                                    {existing_comment});

                            if ~isempty(comment_answer)

                                current_comment = ...
                                    value_to_string( ...
                                        comment_answer{1});

                                write_summary_file( ...
                                    output_file, ...
                                    current_type, ...
                                    current_line, ...
                                    current_animal, ...
                                    current_date, ...
                                    tseries_name, ...
                                    current_comment);

                                fprintf( ...
                                    'Commentaire mis à jour : %s\n', ...
                                    output_file);
                            end
                        end

                    % -------------------------------------
                    % Fiche existante, commentaire vide
                    % -------------------------------------

                    else

                        choice = ...
                            questdlg( ...
                                'Aucun commentaire enregistré. Voulez-vous en ajouter un ?', ...
                                sprintf( ...
                                    '%s | %s | %s', ...
                                    current_type, ...
                                    value_to_string(current_animal), ...
                                    value_to_string(current_date)), ...
                                'Continuer', ...
                                'Ajouter', ...
                                'Continuer');

                        if strcmp(choice, 'Ajouter')

                            comment_answer = ...
                                inputdlg( ...
                                    sprintf( ...
                                        'Commentaire pour %s | %s | %s :', ...
                                        current_type, ...
                                        value_to_string(current_animal), ...
                                        value_to_string(current_date)), ...
                                    'Ajouter un commentaire', ...
                                    [5 80]);

                            if ~isempty(comment_answer)

                                current_comment = ...
                                    value_to_string( ...
                                        comment_answer{1});

                                write_summary_file( ...
                                    output_file, ...
                                    current_type, ...
                                    current_line, ...
                                    current_animal, ...
                                    current_date, ...
                                    tseries_name, ...
                                    current_comment);
                            end
                        end
                    end

                % =========================================
                % NOUVELLE FICHE
                % =========================================

                else

                    comment_answer = ...
                        inputdlg( ...
                            sprintf( ...
                                'Commentaire pour %s | %s | %s :', ...
                                current_type, ...
                                value_to_string(current_animal), ...
                                value_to_string(current_date)), ...
                            'Recording comment', ...
                            [5 80]);

                    if isempty(comment_answer)

                        current_comment = ...
                            '';

                    else

                        current_comment = ...
                            value_to_string( ...
                                comment_answer{1});
                    end

                    write_summary_file( ...
                        output_file, ...
                        current_type, ...
                        current_line, ...
                        current_animal, ...
                        current_date, ...
                        tseries_name, ...
                        current_comment);

                    fprintf( ...
                        'Fiche sauvegardée : %s\n', ...
                        output_file);
                end
            end

            % =============================================
            % AJOUT DANS recap_all
            % =============================================

            new_row = ...
                table( ...
                    string(current_type), ...
                    string(current_line), ...
                    string(current_animal), ...
                    string(current_date), ...
                    string(tseries_name), ...
                    string(current_comment), ...
                    'VariableNames', { ...
                        'Type', ...
                        'Line', ...
                        'Animal', ...
                        'Date', ...
                        'TSeries', ...
                        'Comment'});

            recap_all = ...
                [ ...
                    recap_all; ...
                    new_row ...
                ];
        end
    end
end

end


%% ========================================================================
% ÉCRITURE FICHE
% ========================================================================

function write_summary_file( ...
        output_file, ...
        current_type, ...
        current_line, ...
        current_animal, ...
        current_date, ...
        tseries_name, ...
        current_comment)

fid = ...
    fopen( ...
        output_file, ...
        'w');

if fid == -1

    error( ...
        'Impossible de créer le fichier : %s', ...
        output_file);
end

fprintf(fid, 'FICHE ENREGISTREMENT\n');
fprintf(fid, '====================\n\n');

fprintf( ...
    fid, ...
    'Type       : %s\n', ...
    value_to_string(current_type));

fprintf( ...
    fid, ...
    'Line       : %s\n', ...
    value_to_string(current_line));

fprintf( ...
    fid, ...
    'Animal     : %s\n', ...
    value_to_string(current_animal));

fprintf( ...
    fid, ...
    'Date       : %s\n', ...
    value_to_string(current_date));

fprintf( ...
    fid, ...
    'TSeries    : %s\n\n', ...
    value_to_string(tseries_name));

fprintf(fid, 'COMMENTAIRES\n');
fprintf(fid, '------------\n');

fprintf( ...
    fid, ...
    '%s\n', ...
    value_to_string(current_comment));

fclose(fid);

end


%% ========================================================================
% LECTURE COMMENTAIRE
% ========================================================================

function comment_text = read_summary_comment(output_file)

comment_text = '';

if exist(output_file, 'file') ~= 2
    return;
end

txt = ...
    fileread( ...
        output_file);

lines = ...
    regexp( ...
        txt, ...
        '\r\n|\n|\r', ...
        'split');

comment_idx = ...
    find( ...
        strcmp( ...
            strtrim(lines), ...
            'COMMENTAIRES'), ...
        1, ...
        'first');

if isempty(comment_idx)
    return;
end

start_idx = ...
    comment_idx + 2;

if start_idx > numel(lines)
    return;
end

comment_lines = ...
    lines(start_idx:end);

% =========================================================
% Compatibilité avec les anciennes fiches
% =========================================================
%
% Anciennes fiches :
% COMMENTAIRES
% ------------
% ...
%
% INFOS ENREGISTREMENT
% =========================================================

old_end = ...
    find( ...
        strcmp( ...
            strtrim(comment_lines), ...
            'INFOS ENREGISTREMENT'), ...
        1, ...
        'first');

if ~isempty(old_end)

    comment_lines = ...
        comment_lines(1:old_end-1);
end

% ---------------------------------------------------------
% Supprimer lignes vides début
% ---------------------------------------------------------

while ~isempty(comment_lines) && ...
        isempty(strtrim(comment_lines{1}))

    comment_lines(1) = [];
end

% ---------------------------------------------------------
% Supprimer lignes vides fin
% ---------------------------------------------------------

while ~isempty(comment_lines) && ...
        isempty(strtrim(comment_lines{end}))

    comment_lines(end) = [];
end

if isempty(comment_lines)
    return;
end

comment_text = ...
    strjoin( ...
        comment_lines, ...
        newline);

if strcmpi(strtrim(comment_text), 'NA')

    comment_text = ...
        '';
end

end


%% ========================================================================
% CONVERSION NOM FICHIER
% ========================================================================

function filename_str = value_to_filename(value)

filename_str = ...
    value_to_string(value);

if strcmp(filename_str, 'NA')

    filename_str = ...
        'unknown';
end

filename_str = ...
    regexprep( ...
        filename_str, ...
        '[^\w\-]', ...
        '_');

end


%% ========================================================================
% CONVERSION TEXTE
% ========================================================================

function str = value_to_string(value)

if isempty(value)

    str = ...
        '';

elseif ischar(value)

    if size(value, 1) > 1

        lines = ...
            cellstr(value);

        lines = ...
            cellfun( ...
                @deblank, ...
                lines, ...
                'UniformOutput', ...
                false);

        str = ...
            strjoin( ...
                lines, ...
                newline);

    else

        str = ...
            value;
    end

elseif isstring(value)

    if isscalar(value)

        str = ...
            char(value);

    else

        str = ...
            strjoin( ...
                cellstr(value), ...
                newline);
    end

elseif isnumeric(value) || ...
        islogical(value)

    if isscalar(value)

        str = ...
            num2str(value);

    else

        str = ...
            mat2str(value);
    end

else

    str = ...
        char(string(value));
end

end