function [selected_groups, recap_all] = DF_peak_detection( ...
        selected_groups, ...
        include_electroporated, ...
        automatic_selection, ...
        recap_all, ...
        detection_mode)
    if nargin < 1 || isempty(selected_groups)
        return;
    end
    type_names = ...
        fieldnames(selected_groups);
    % Mode facultatif
    if nargin < 5 || isempty(detection_mode)
        [peak_detection_mode, clear_outputs_requested] = ...
            ask_initial_peak_detection_mode();
    else
        peak_detection_mode = char(lower(strtrim(string(detection_mode))));
        clear_outputs_requested = false;
        if strcmp(peak_detection_mode, 'clear')
            peak_detection_mode = 'interactive';
            clear_outputs_requested = true;
        end
    end
    if isempty(peak_detection_mode)
        return;
    end
    %==============================================================
    % VIEWER SCOPE
    %
    % En mode Viewer uniquement, choisir progressivement :
    %   Line -> Animal -> Date
    %
    % A chaque niveau, [ALL] permet de conserver toutes les valeurs
    % encore disponibles. Les niveaux suivants ne proposent que les
    % valeurs compatibles avec les choix precedents.
    %==============================================================
    viewer_scope = struct('enabled',false);
    if strcmpi(peak_detection_mode,'viewer')
        [viewer_scope, viewer_scope_cancelled] = ...
            ask_viewer_processing_scope(selected_groups);
        if viewer_scope_cancelled
            return;
        end
    end
    % Une ligne par enregistrement ; chaque case contient un cell(nPlanes,1).
    % Ne pas ecraser les valeurs deja presentes dans le recap interactive.
    if ~ismember('recording_keep',recap_all.Properties.VariableNames) || ...
            ~iscell(recap_all.recording_keep)
        recap_all.recording_keep = cell(height(recap_all),1);
    end
    if ~ismember('comment_saved',recap_all.Properties.VariableNames) || ...
            ~iscell(recap_all.comment_saved)
        recap_all.comment_saved = cell(height(recap_all),1);
    end
    for t = 1:numel(type_names)
        type = ...
            type_names{t};
        automatic_selection = ...
            automatic_selection.(type);
        for k = 1:numel(selected_groups.(type))
            %======================================================
            % VIEWER : filtrage Line / Animal
            %======================================================
            if viewer_scope.enabled
                current_line_scope = ...
                    scalar_scope_string( ...
                        selected_groups.(type)(k).line);
                current_animal_scope = ...
                    scalar_scope_string( ...
                        selected_groups.(type)(k).animal);
                if ~scope_contains_value( ...
                        viewer_scope.lines, ...
                        current_line_scope) || ...
                        ~scope_contains_value( ...
                            viewer_scope.animals, ...
                            make_scope_key( ...
                                current_line_scope, ...
                                current_animal_scope))
                    continue;
                end
            end
            fprintf('\n==============================\n');
            fprintf('DF peak detection\n');
            fprintf('Type: %s\n', type);
            fprintf( ...
                'Animal %d / %d: %s\n', ...
                k, ...
                numel(selected_groups.(type)), ...
                char(string( ...
                    selected_groups.(type)(k).animal)));
            fprintf('==============================\n');
            %======================================================
            % Paths
            %======================================================
            paths = ...
                selected_groups.(type)(k).paths;
            gcamp_root_folders = ...
                paths.gcamp_root;
            gcamp_output_folders = ...
                paths.gcamp_output;
            output_folders = ...
                paths.output_folders;
            camera_folders = ...
                paths.camera;
            suite2p_folders = ...
                paths.suite2p;
            TSeries_folders = ...
                paths.TSeries;
            gcamp_TSeries_folders = ...
                TSeries_folders(:, 1);
            gcamp_suite2p_folders = ...
                suite2p_folders(:, 1);
            numAcquisitions = ...
                size(gcamp_TSeries_folders, 1);
            %======================================================
            % Animal information
            %======================================================
            line = ...
                selected_groups.(type)(k).line;
            animal = ...
                selected_groups.(type)(k).animal;
            dates = ...
                selected_groups.(type)(k).dates;
            ages = ...
                selected_groups.(type)(k).ages;
            metadata = ...
                selected_groups.(type)(k).metadata;
            data = ...
                selected_groups.(type)(k).data;
            %======================================================
            % VIEWER : filtrage des acquisitions par date
            %
            % Toutes les acquisitions partageant une date selectionnee
            % restent selectionnees. Cela preserve correctement les cas
            % avec plusieurs TSeries le meme jour.
            %======================================================
            viewer_recording_mask = ...
                true(numAcquisitions,1);
            if viewer_scope.enabled
                viewer_recording_mask = ...
                    build_viewer_recording_mask( ...
                        line, ...
                        animal, ...
                        dates, ...
                        numAcquisitions, ...
                        viewer_scope.date_keys);
                if ~any(viewer_recording_mask)
                    continue;
                end
            end
            %======================================================
            % Animal path
            %======================================================
            animal_path = '';
            if isfield(paths, 'date') && ...
                    ~isempty(paths.date)
                if iscell(paths.date)
                    first_valid_date = ...
                        find( ...
                            ~cellfun(@isempty, paths.date), ...
                            1, ...
                            'first');
                    if ~isempty(first_valid_date)
                        animal_path = ...
                            fileparts( ...
                                paths.date{first_valid_date});
                    end
                else
                    animal_path = ...
                        fileparts(paths.date);
                end
            end
            %======================================================
            % Sampling rate + synchronous frames
            %======================================================
            sampling_rate_plane = ...
                metadata.gcamp_plane.SamplingRatePlane;
            synchronous_frames_group = ...
                cell(size(sampling_rate_plane));
            for m = 1:numel(sampling_rate_plane)
                sampling_rate = ...
                    get_numeric_cell_value( ...
                        sampling_rate_plane, ...
                        m);
                if isfinite(sampling_rate) && ...
                        sampling_rate > 0
                    synchronous_frames_group{m} = ...
                        round( ...
                            0.2 * sampling_rate);
                else
                    synchronous_frames_group{m} = [];
                end
            end
            %======================================================
            % Mean images
            %======================================================
            meanImgs_gcamp = ...
                save_mean_images( ...
                    'GCaMP', ...
                    animal, ...
                    ages, ...
                    dates, ...
                    numAcquisitions, ...
                    gcamp_output_folders, ...
                    suite2p_folders(:, 1));
            data.gcamp_plane.meanImgs_gcamp = ...
                meanImgs_gcamp;
            %======================================================
            % Recapitulatif : uniquement les TSeries de cet animal
            % (Type + Line + Animal pour eviter les homonymes).
            %======================================================
            % Memoriser les indices du tableau interactive avant extraction.
            % Ils garantissent le retour sur les bonnes lignes, meme si
            % plusieurs TSeries partagent une date ou un animal.
            recap_rows = ...
                strcmp(string(recap_all.Type), string(type)) & ...
                strcmp(string(recap_all.Line), string(line)) & ...
                strcmp(string(recap_all.Animal), string(animal));
            recap_all_animal = recap_all(recap_rows,:);
            %======================================================
            % DF processing and peak detection
            %======================================================
            [data, has_new_saved, modified_planes, recap_all_animal] = ...
                run_gcamp_peak_detection( ...
                    type, ...
                    line, ...
                    animal, ...
                    dates, ...
                    ages, ...
                    gcamp_suite2p_folders, ...
                    gcamp_root_folders, ...
                    gcamp_output_folders, ...
                    camera_folders, ...
                    metadata, ...
                    sampling_rate_plane, ...
                    synchronous_frames_group, ...
                    data, ...
                    meanImgs_gcamp, ...
                    gcamp_TSeries_folders , ...
                    include_electroporated, ...
                    peak_detection_mode, ...
                    automatic_selection, ...
                    output_folders, ...
                    clear_outputs_requested, ...
                    recap_all_animal, ...
                    viewer_recording_mask);
            selected_groups.(type)(k).data = ...
                data;
            %======================================================
            % Reconstruire recap_all depuis le recap de cet animal.
            % Conserver l'ordre des enregistrements, les colonnes initiales
            % et les lignes des autres animaux. Le cell(nPlanes,1) reste
            % contenu dans UNE case de la ligne correspondante.
            %======================================================
            if height(recap_all_animal) ~= nnz(recap_rows)
                error('DF_peak_detection:RecapRowMismatch', ...
                    'Le nombre de lignes du recap animal a change.');
            end
            recap_all.recording_keep(recap_rows) = ...
                recap_all_animal.recording_keep;
            recap_all.comment_saved(recap_rows) = ...
                recap_all_animal.comment_saved;
            %======================================================
            % Si de nouvelles données ont été sauvegardées,
            % forcer la reconstruction des figures de tous les plans.
            %======================================================
            if has_new_saved
                for m = 1:numel(modified_planes)
                    if isempty(modified_planes{m})
                        continue;
                    end
                    modified_planes{m}(:) = true;
                end
            end
            %======================================================
            % Figures internes à l'animal
            %======================================================
            build_rasterplot_DF( ...
                data, ...
                gcamp_output_folders, ...
                gcamp_root_folders, ...
                animal_path, ...
                line, ...
                animal, ...
                dates, ...
                ages, ...
                sampling_rate_plane, ...
                automatic_selection, ...
                output_folders, ...
                has_new_saved, ...
                modified_planes);
            build_rasterplot_peaks( ...
                data, ...
                gcamp_output_folders, ...
                gcamp_root_folders, ...
                animal_path, ...
                line, ...
                animal, ...
                dates, ...
                ages, ...
                sampling_rate_plane, ...
                automatic_selection, ...
                output_folders, ...
                has_new_saved, ...
                modified_planes);
        end
    end
end
function [scope, cancelled] = ask_viewer_processing_scope(selected_groups)
    scope = struct( ...
        'enabled', true, ...
        'lines', strings(0,1), ...
        'animals', strings(0,1), ...
        'date_keys', strings(0,1));
    cancelled = false;
    catalog = build_viewer_scope_catalog(selected_groups);
    if isempty(catalog)
        cancelled = true;
        return;
    end
    %==============================================================
    % 1) LINE
    %==============================================================
    all_lines = unique( ...
        string({catalog.line}).', ...
        'stable');
    all_lines = ...
        clean_scope_values(all_lines);
    [scope.lines, ok] = ...
        choose_scope_values( ...
            all_lines, ...
            all_lines, ...
            'Viewer - Line', ...
            'Selectionner une ou plusieurs lines :');
    if ~ok
        cancelled = true;
        return;
    end
    %==============================================================
    % 2) ANIMAL
    %
    % La valeur interne est une cle LINE + ANIMAL. Si plusieurs lines
    % sont retenues, le nom de la line est affiche entre parentheses afin
    % de distinguer d'eventuels numeros d'animaux identiques.
    %==============================================================
    keep_line = ...
        arrayfun( ...
            @(x) scope_contains_value(scope.lines,string(x.line)), ...
            catalog);
    catalog_line = catalog(keep_line);
    animal_keys = strings(0,1);
    animal_labels = strings(0,1);
    show_line_in_animal = numel(scope.lines) > 1;
    for i = 1:numel(catalog_line)
        key = make_scope_key( ...
            catalog_line(i).line, ...
            catalog_line(i).animal);
        if any(strcmp(animal_keys,key))
            continue;
        end
        animal_keys(end+1,1) = key; %#ok<AGROW>
        if show_line_in_animal
            animal_labels(end+1,1) = sprintf( ...
                '%s (%s)', ...
                char(catalog_line(i).animal), ...
                char(catalog_line(i).line)); %#ok<AGROW>
        else
            animal_labels(end+1,1) = catalog_line(i).animal; %#ok<AGROW>
        end
    end
    [scope.animals, ok] = ...
        choose_scope_values( ...
            animal_keys, ...
            animal_labels, ...
            'Viewer - Animal', ...
            'Selectionner un ou plusieurs animaux :');
    if ~ok
        cancelled = true;
        return;
    end
    %==============================================================
    % 3) DATE
    %
    % Chaque option garde une cle LINE + ANIMAL + DATE. Ainsi deux animaux
    % ayant la meme date restent selectionnables independamment.
    %
    % Affichage :
    %   - plusieurs animaux : DATE (ANIMAL)
    %   - plusieurs lines   : DATE (..., LINE)
    %   - les deux          : DATE (ANIMAL, LINE)
    %==============================================================
    keep_animal = ...
        arrayfun( ...
            @(x) scope_contains_value( ...
                scope.animals, ...
                make_scope_key(x.line,x.animal)), ...
            catalog_line);
    catalog_animal = ...
        catalog_line(keep_animal);
    date_keys = strings(0,1);
    date_labels = strings(0,1);
    show_animal_in_date = numel(scope.animals) > 1;
    show_line_in_date = numel(scope.lines) > 1;
    for i = 1:numel(catalog_animal)
        current_dates = clean_scope_values(catalog_animal(i).dates);
        for d = 1:numel(current_dates)
            key = make_scope_key( ...
                catalog_animal(i).line, ...
                catalog_animal(i).animal, ...
                current_dates(d));
            if any(strcmp(date_keys,key))
                continue;
            end
            date_keys(end+1,1) = key; %#ok<AGROW>
            if show_animal_in_date && show_line_in_date
                label = sprintf( ...
                    '%s (%s, %s)', ...
                    char(current_dates(d)), ...
                    char(catalog_animal(i).animal), ...
                    char(catalog_animal(i).line));
            elseif show_animal_in_date
                label = sprintf( ...
                    '%s (%s)', ...
                    char(current_dates(d)), ...
                    char(catalog_animal(i).animal));
            elseif show_line_in_date
                label = sprintf( ...
                    '%s (%s)', ...
                    char(current_dates(d)), ...
                    char(catalog_animal(i).line));
            else
                label = char(current_dates(d));
            end
            date_labels(end+1,1) = string(label); %#ok<AGROW>
        end
    end
    [scope.date_keys, ok] = ...
        choose_scope_values( ...
            date_keys, ...
            date_labels, ...
            'Viewer - Date', ...
            'Selectionner une ou plusieurs dates :');
    if ~ok
        cancelled = true;
        return;
    end
end
function catalog = build_viewer_scope_catalog(selected_groups)
    catalog = struct( ...
        'line', {}, ...
        'animal', {}, ...
        'dates', {});
    if isempty(selected_groups) || ~isstruct(selected_groups)
        return;
    end
    type_names = ...
        fieldnames(selected_groups);
    for t = 1:numel(type_names)
        type_name = ...
            type_names{t};
        groups = ...
            selected_groups.(type_name);
        for k = 1:numel(groups)
            if ~isfield(groups(k),'line') || ...
                    ~isfield(groups(k),'animal')
                continue;
            end
            line_value = ...
                scalar_scope_string(groups(k).line);
            animal_value = ...
                scalar_scope_string(groups(k).animal);
            if line_value == "" || animal_value == ""
                continue;
            end
            dates_value = ...
                strings(0,1);
            if isfield(groups(k),'dates')
                dates_value = ...
                    sequence_scope_strings(groups(k).dates);
            end
            entry = struct();
            entry.line = line_value;
            entry.animal = animal_value;
            entry.dates = dates_value;
            catalog(end+1) = entry; %#ok<AGROW>
        end
    end
end
function [selected_values, ok] = choose_scope_values( ...
        values, ...
        display_labels, ...
        dialog_title, ...
        prompt_text)
    values = string(values(:));
    display_labels = string(display_labels(:));
    valid = ...
        ~ismissing(values) & values ~= "" & ...
        ~ismissing(display_labels) & display_labels ~= "";
    values = values(valid);
    display_labels = display_labels(valid);
    if isempty(values)
        selected_values = strings(0,1);
        ok = false;
        return;
    end
    % Les valeurs internes peuvent contenir des cles composites ; ne pas
    % appliquer clean_scope_values separement aux labels afin de conserver
    % leur correspondance exacte.
    [values, ia] = unique(values,'stable');
    display_labels = display_labels(ia);
    display_values = [ ...
        "[ALL]"; ...
        display_labels(:)];
    [selection, ok_numeric] = ...
        listdlg( ...
            'ListString', cellstr(display_values), ...
            'SelectionMode', 'multiple', ...
            'Name', dialog_title, ...
            'PromptString', prompt_text, ...
            'ListSize', [420 340], ...
            'InitialValue', 1);
    ok = ...
        logical(ok_numeric);
    if ~ok || isempty(selection)
        selected_values = strings(0,1);
        ok = false;
        return;
    end
    if any(selection == 1)
        selected_values = values(:);
    else
        selected_values = ...
            values(selection - 1);
    end
    selected_values = string(selected_values(:));
end
function mask = build_viewer_recording_mask( ...
        line, ...
        animal, ...
        dates, ...
        numAcquisitions, ...
        selected_date_keys)
    mask = ...
        false(numAcquisitions,1);
    if numAcquisitions <= 0
        return;
    end
    line_value = scalar_scope_string(line);
    animal_value = scalar_scope_string(animal);
    date_values = ...
        sequence_scope_strings(dates);
    n = ...
        min(numAcquisitions,numel(date_values));
    if n <= 0
        return;
    end
    for m = 1:n
        current_key = make_scope_key( ...
            line_value, ...
            animal_value, ...
            date_values(m));
        mask(m) = ...
            scope_contains_value( ...
                selected_date_keys, ...
                current_key);
    end
end
function key = make_scope_key(varargin)
    parts = strings(numel(varargin),1);
    for i = 1:numel(varargin)
        parts(i) = scalar_scope_string(varargin{i});
    end
    key = strjoin(parts,"|||");
end
function tf = scope_contains_value(values,value)
    values = ...
        clean_scope_values(values);
    value = ...
        scalar_scope_string(value);
    tf = ...
        value ~= "" && ...
        any(strcmp(values,value));
end
function values = clean_scope_values(values)
    values = ...
        string(values(:));
    values = ...
        strtrim(values);
    values = ...
        values( ...
            ~ismissing(values) & ...
            values ~= "");
    values = ...
        unique(values,'stable');
end
function value = scalar_scope_string(value)
    values = ...
        sequence_scope_strings(value);
    if isempty(values)
        value = "";
    else
        value = values(1);
    end
end
function values = sequence_scope_strings(input_value)
    values = ...
        strings(0,1);
    if isempty(input_value)
        return;
    end
    if iscell(input_value)
        values = ...
            strings(numel(input_value),1);
        for i = 1:numel(input_value)
            current_value = ...
                input_value{i};
            while iscell(current_value)
                if isempty(current_value)
                    current_value = "";
                    break;
                end
                current_value = ...
                    current_value{1};
            end
            values(i) = ...
                string(current_value);
        end
    else
        values = ...
            string(input_value(:));
    end
    values = ...
        clean_scope_values(values);
end
function value = get_numeric_cell_value( ...
        values, ...
        index)
    value = NaN;
    if isempty(values) || ...
            numel(values) < index
        return;
    end
    if iscell(values)
        value = ...
            values{index};
    else
        value = ...
            values(index);
    end
    if isempty(value)
        return;
    end
    value = ...
        double( ...
            value(1));
end
function [mode, clear_outputs_requested] = ...
        ask_initial_peak_detection_mode()
    mode = [];
    clear_outputs_requested = false;
    scr = ...
    get( ...
        groot, ...
        'ScreenSize');
    dlg_width  = 520;
    dlg_height = 250;
    left = ...
        round((scr(3) - dlg_width) / 2);
    bottom = ...
        round(scr(4) * 0.60);
    dlg = ...
        dialog( ...
            'Name', 'Peak detection mode', ...
            'Units', 'pixels', ...
            'Position', [ ...
                left, ...
                bottom, ...
                dlg_width, ...
                dlg_height], ...
            'WindowStyle', 'modal', ...
            'Resize', 'off', ...
            'CloseRequestFcn', @(src,~) close_dialog(src));
    uicontrol( ...
        'Parent', dlg, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.45 0.90 0.50], ...
        'HorizontalAlignment', 'left', ...
        'FontSize', 10, ...
        'String', { ...
        'Choose peak detection mode for ALL animals / recordings / planes:'; ...
        ' '; ...
        'Viewer mode:'; ...
        'Load existing detection and open the viewer.'; ...
        ' '; ...
        'Process or load data:'; ...
        'Process missing detections or load existing results only.'; ...
        ' '; ...
        'Clear outputs:'; ...
        'Delete all existing peak-detection outputs and recompute.'});
    uicontrol( ...
        'Parent', dlg, ...
        'Style', 'pushbutton', ...
        'String', 'Viewer mode', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.10 0.20 0.15], ...
        'Callback', @(~,~) choose_mode('viewer'));
    uicontrol( ...
        'Parent', dlg, ...
        'Style', 'pushbutton', ...
        'String', 'Process or load data', ...
        'Units', 'normalized', ...
        'Position', [0.28 0.10 0.25 0.15], ...
        'Callback', @(~,~) choose_mode('load_only'));
    uicontrol( ...
        'Parent', dlg, ...
        'Style', 'pushbutton', ...
        'String', 'Clear outputs', ...
        'Units', 'normalized', ...
        'Position', [0.56 0.10 0.18 0.15], ...
        'Callback', @(~,~) choose_mode('clear'));
    uicontrol( ...
        'Parent', dlg, ...
        'Style', 'pushbutton', ...
        'String', 'Cancel', ...
        'Units', 'normalized', ...
        'Position', [0.77 0.10 0.18 0.15], ...
        'Callback', @(~,~) choose_mode('cancel'));
    uiwait(dlg);
    %==============================================================
    function choose_mode(choice)
        switch choice
            case 'viewer'
                mode = 'viewer';
            case 'load_only'
                mode = 'load_only';
            case 'clear'
                mode = 'interactive';
                clear_outputs_requested = true;
            case 'cancel'
                mode = [];
                clear_outputs_requested = false;
        end
        if isvalid(dlg)
            uiresume(dlg);
            delete(dlg);
        end
    end
    %==============================================================
    function close_dialog(src)
        mode = [];
        clear_outputs_requested = false;
        uiresume(src);
        delete(src);
    end
end
