function selected_groups = DF_peak_detection( ...
        selected_groups, ...
        include_electroporated, ...
        automatic_selection)

    if nargin < 1 || isempty(selected_groups)
        return;
    end

    type_names = ...
        fieldnames(selected_groups);

    [ ...
        peak_detection_mode, ...
        clear_outputs_requested ...
    ] = ...
        ask_initial_peak_detection_mode();
    
    if isempty(peak_detection_mode)
        return;
    end


    for t = 1:numel(type_names)

        current_type = ...
            type_names{t};

        current_automatic_selection = ...
            automatic_selection.(current_type);

        for k = 1:numel(selected_groups.(current_type))

            fprintf('\n==============================\n');
            fprintf('DF peak detection\n');
            fprintf('Type: %s\n', current_type);
            fprintf( ...
                'Animal %d / %d: %s\n', ...
                k, ...
                numel(selected_groups.(current_type)), ...
                char(string( ...
                    selected_groups.(current_type)(k).animal)));
            fprintf('==============================\n');


            %======================================================
            % Paths
            %======================================================

            paths = ...
                selected_groups.(current_type)(k).paths;


            gcamp_root_folders = ...
                paths.gcamp_root;


            gcamp_output_folders = ...
                paths.gcamp_output;


            current_output_folders = ...
                paths.output_folders;


            current_suite2p_group = ...
                paths.suite2p;


            current_gcamp_suite2p_folders = ...
                current_suite2p_group(:, 1);


            current_TSeries_group = ...
                paths.TSeries;


            %======================================================
            % Animal information
            %======================================================

            current_line = ...
                selected_groups.(current_type)(k).line;


            current_animal = ...
                selected_groups.(current_type)(k).animal;


            current_dates = ...
                selected_groups.(current_type)(k).dates;


            current_ages = ...
                selected_groups.(current_type)(k).ages;


            metadata = ...
                selected_groups.(current_type)(k).metadata;


            data = ...
                selected_groups.(current_type)(k).data;


            %======================================================
            % Animal path
            %======================================================

            animal_path = '';


            if isfield(paths, 'date') && ...
                    ~isempty(paths.date)

                if iscell(paths.date)

                    first_valid_date = ...
                        find( ...
                            ~cellfun(@isempty, paths.date), ...
                            1, ...
                            'first');


                    if ~isempty(first_valid_date)

                        animal_path = ...
                            fileparts( ...
                                paths.date{first_valid_date});
                    end

                else

                    animal_path = ...
                        fileparts(paths.date);
                end
            end


            %======================================================
            % Sampling rate + synchronous frames
            %======================================================

            sampling_rate_plane = ...
                metadata.gcamp_plane.SamplingRatePlane;


            synchronous_frames_group = ...
                cell(size(sampling_rate_plane));


            for m = 1:numel(sampling_rate_plane)

                sampling_rate = ...
                    get_numeric_cell_value( ...
                        sampling_rate_plane, ...
                        m);


                if isfinite(sampling_rate) && ...
                        sampling_rate > 0

                    synchronous_frames_group{m} = ...
                        round( ...
                            0.2 * sampling_rate);

                else

                    synchronous_frames_group{m} = [];
                end
            end


            %======================================================
            % Mean images
            %======================================================

            meanImgs_gcamp = ...
                save_mean_images( ...
                    'GCaMP', ...
                    current_animal, ...
                    current_ages, ...
                    current_dates, ...
                    gcamp_output_folders, ...
                    current_suite2p_group(:, 1));


            data.gcamp_plane.meanImgs_gcamp = ...
                meanImgs_gcamp;


            %======================================================
            % DF processing and peak detection
            %======================================================

            [data, has_new_saved, modified_planes] = ...
                run_gcamp_peak_detection( ...
                    current_type, ...
                    current_line, ...
                    current_animal, ...
                    current_dates, ...
                    current_ages, ...
                    current_gcamp_suite2p_folders, ...
                    gcamp_root_folders, ...
                    gcamp_output_folders, ...
                    metadata, ...
                    sampling_rate_plane, ...
                    synchronous_frames_group, ...
                    data, ...
                    meanImgs_gcamp, ...
                    current_TSeries_group(:, 1), ...
                    include_electroporated, ...
                    peak_detection_mode, ...
                    current_automatic_selection, ...
                    current_output_folders, ...
                    clear_outputs_requested);


            selected_groups.(current_type)(k).data = ...
                data;

            
            %======================================================
            % Si de nouvelles données ont été sauvegardées,
            % forcer la reconstruction des figures de tous les plans.
            %======================================================
            
            if has_new_saved
            
                for m = 1:numel(modified_planes)
            
                    if isempty(modified_planes{m})
                        continue;
                    end
            
                    modified_planes{m}(:) = true;
                end
            end

            %======================================================
            % Figures internes à l'animal
            %======================================================

            build_rasterplot_DF( ...
                data, ...
                gcamp_output_folders, ...
                gcamp_root_folders, ...
                animal_path, ...
                current_line, ...
                current_animal, ...
                current_dates, ...
                current_ages, ...
                sampling_rate_plane, ...
                current_automatic_selection, ...
                current_output_folders, ...
                has_new_saved, ...
                modified_planes);


            build_rasterplot_peaks( ...
                data, ...
                gcamp_output_folders, ...
                gcamp_root_folders, ...
                animal_path, ...
                current_line, ...
                current_animal, ...
                current_dates, ...
                current_ages, ...
                sampling_rate_plane, ...
                current_automatic_selection, ...
                current_output_folders, ...
                has_new_saved, ...
                modified_planes);
        end
    end
end


function value = get_numeric_cell_value( ...
        values, ...
        index)

    value = NaN;


    if isempty(values) || ...
            numel(values) < index

        return;
    end


    if iscell(values)

        current_value = ...
            values{index};

    else

        current_value = ...
            values(index);
    end


    if isempty(current_value)
        return;
    end


    value = ...
        double( ...
            current_value(1));
end


function [mode, clear_outputs_requested] = ...
        ask_initial_peak_detection_mode()

    mode = [];
    clear_outputs_requested = false;

    scr = ...
    get( ...
        groot, ...
        'ScreenSize');

    dlg_width  = 520;
    dlg_height = 250;
    
    left = ...
        round((scr(3) - dlg_width) / 2);
    
    bottom = ...
        round(scr(4) * 0.60);
    
    dlg = ...
        dialog( ...
            'Name', 'Peak detection mode', ...
            'Units', 'pixels', ...
            'Position', [ ...
                left, ...
                bottom, ...
                dlg_width, ...
                dlg_height], ...
            'WindowStyle', 'modal', ...
            'Resize', 'off', ...
            'CloseRequestFcn', @(src,~) close_dialog(src));

    uicontrol( ...
        'Parent', dlg, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.45 0.90 0.50], ...
        'HorizontalAlignment', 'left', ...
        'FontSize', 10, ...
        'String', { ...
        'Choose peak detection mode for ALL animals / recordings / planes:'; ...
        ' '; ...
        'Viewer mode:'; ...
        'Load existing detection and open the viewer.'; ...
        ' '; ...
        'Process or load data:'; ...
        'Process missing detections or load existing results only.'; ...
        ' '; ...
        'Clear outputs:'; ...
        'Delete all existing peak-detection outputs and recompute.'});

    uicontrol( ...
        'Parent', dlg, ...
        'Style', 'pushbutton', ...
        'String', 'Viewer mode', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.10 0.20 0.15], ...
        'Callback', @(~,~) choose_mode('viewer'));

    uicontrol( ...
        'Parent', dlg, ...
        'Style', 'pushbutton', ...
        'String', 'Process or load data', ...
        'Units', 'normalized', ...
        'Position', [0.28 0.10 0.25 0.15], ...
        'Callback', @(~,~) choose_mode('load_only'));

    uicontrol( ...
        'Parent', dlg, ...
        'Style', 'pushbutton', ...
        'String', 'Clear outputs', ...
        'Units', 'normalized', ...
        'Position', [0.56 0.10 0.18 0.15], ...
        'Callback', @(~,~) choose_mode('clear'));

    uicontrol( ...
        'Parent', dlg, ...
        'Style', 'pushbutton', ...
        'String', 'Cancel', ...
        'Units', 'normalized', ...
        'Position', [0.77 0.10 0.18 0.15], ...
        'Callback', @(~,~) choose_mode('cancel'));

    uiwait(dlg);

    %==============================================================
    function choose_mode(choice)

        switch choice

            case 'viewer'

                mode = 'viewer';

            case 'load_only'

                mode = 'load_only';

            case 'clear'

                mode = 'global';
                clear_outputs_requested = true;

            case 'cancel'

                mode = [];
                clear_outputs_requested = false;
        end

        if isvalid(dlg)
            uiresume(dlg);
            delete(dlg);
        end
    end

    %==============================================================
    function close_dialog(src)

        mode = [];
        clear_outputs_requested = false;

        uiresume(src);
        delete(src);
    end
end