function [selected_groups, output_folders] = DF_peak_detection( ...
        selected_groups, include_electroporated, automatic_selection, output_folders)

    if nargin < 1 || isempty(selected_groups)
        return;
    end

    type_names = fieldnames(selected_groups);
    peak_detection_mode = ask_initial_peak_detection_mode();

    for t = 1:numel(type_names)

        current_type = type_names{t};

        if t > numel(output_folders)
            error(['Missing output folder for type: ' current_type]);
        end
        
        current_output_folder = output_folders{t};
        current_automatic_selection = automatic_selection(t);

        for k = 1:numel(selected_groups.(current_type))

            fprintf('\n==============================\n');
            fprintf('DF peak detection\n');
            fprintf('Type: %s\n', current_type);
            fprintf('Animal %d / %d: %s\n', ...
                k, numel(selected_groups.(current_type)), ...
                char(string( ...
                    selected_groups.(current_type)(k).animal)));
            fprintf('==============================\n');

            paths = selected_groups.(current_type)(k).paths;

            gcamp_root_folders = paths.gcamp_root;
            gcamp_output_folders = paths.gcamp_output;
            
            current_line = selected_groups.(current_type)(k).line;

            current_animal = ...
                selected_groups.(current_type)(k).animal;

            current_dates = ...
                selected_groups.(current_type)(k).dates;

            current_ages = ...
                selected_groups.(current_type)(k).ages;

            current_suite2p_group = paths.suite2p;
            current_TSeries_group = paths.TSeries;

            metadata = selected_groups.(current_type)(k).metadata;
            data = selected_groups.(current_type)(k).data;

            animal_path = '';

            if isfield(paths, 'date') && ~isempty(paths.date)

                if iscell(paths.date)
                    first_valid_date = find( ...
                        ~cellfun(@isempty, paths.date), 1, 'first');

                    if ~isempty(first_valid_date)
                        animal_path = ...
                            fileparts(paths.date{first_valid_date});
                    end
                else
                    animal_path = fileparts(paths.date);
                end
            end

            %======================================================
            % Sampling rate + synchronous frames
            %======================================================
            sampling_rate_group = metadata.gcamp_plane.SamplingRatePlane;

            synchronous_frames_group = ...
                cell(size(sampling_rate_group));

            for m = 1:numel(sampling_rate_group)

                sampling_rate = ...
                    get_numeric_cell_value( ...
                        sampling_rate_group, m);

                if isfinite(sampling_rate) && sampling_rate > 0
                    synchronous_frames_group{m} = ...
                        round(0.2 * sampling_rate);
                else
                    synchronous_frames_group{m} = [];
                end
            end

            %======================================================
            % Mean images
            %======================================================
            meanImgs_gcamp = save_mean_images( ...
                'GCaMP', ...
                current_animal, ...
                current_ages, ...
                current_dates, ...
                gcamp_output_folders, ...
                current_suite2p_group(:, 1));

            data.meanImgs_gcamp = meanImgs_gcamp;

            %======================================================
            % DF processing and peak detection
            %======================================================
            data = run_gcamp_peak_detection( ...
                current_type, ...
                current_line, ...
                current_animal, ...
                current_ages, ...
                gcamp_output_folders, ...
                metadata, ...
                sampling_rate_group, ...
                synchronous_frames_group, ...
                data, ...
                meanImgs_gcamp, ...
                current_TSeries_group(:, 1), ...
                include_electroporated, ...
                peak_detection_mode, ...
                current_automatic_selection, ...
                current_output_folder);

            selected_groups.(current_type)(k).data = data;

            %======================================================
            % Figures internes à l’animal
            %======================================================
            build_rasterplot_DF( ...
                data, ...
                gcamp_output_folders, ...
                gcamp_root_folders, ...
                animal_path, ...
                current_line, ...
                current_animal, ...
                current_dates, ...
                current_ages, ...
                sampling_rate_group, ...
                current_automatic_selection, ...
                current_output_folder);

            build_rasterplot_peaks( ...
                data, ...
                gcamp_output_folders, ...
                gcamp_root_folders, ...
                animal_path, ...
                current_line, ...
                current_animal, ...
                current_dates, ...
                current_ages, ...
                sampling_rate_group);
        end
    end
end


function value = get_numeric_cell_value(values, index)

    value = NaN;

    if isempty(values) || numel(values) < index
        return;
    end

    if iscell(values)
        current_value = values{index};
    else
        current_value = values(index);
    end

    if isempty(current_value)
        return;
    end

    value = double(current_value(1));
end

function mode = ask_initial_peak_detection_mode()

    answer = questdlg( ...
        ['Choose peak detection mode for ALL animals / recordings / planes:' newline newline ...
         'Viewer mode: load existing detection and open the viewer.' newline ...
         'Load data: load existing detection only, without opening the viewer.'], ...
        'Peak detection mode', ...
        'Viewer mode', ...
        'Load data', ...
        'Load data');

    switch answer
        case 'Viewer mode'
            mode = 'viewer';

        otherwise
            mode = 'load_only';
    end
end
