function zseries = load_or_process_zseries( ...
        zseries_paths, ...
        gcamp_root_folders, ...
        zseries_metadata)

    % ==============================================================
    % OPTIONS
    % ==============================================================

    apply_xy_registration = ...
        true;

    isotropic_voxel_um = ...
        [];

    processing_version = ...
        4;


    % ==============================================================
    % Initialisation
    % ==============================================================

    nRecordings = ...
        numel(zseries_paths);


    zseries = struct();

    zseries.raw_volume = ...
        cell(nRecordings,1);

    zseries.registered_volume = ...
        cell(nRecordings,1);

    zseries.filtered_volume = ...
        cell(nRecordings,1);

    zseries.cell_mask_3d = ...
        cell(nRecordings,1);

    zseries.cells_3d = ...
        cell(nRecordings,1);

    zseries.isotropic_volume = ...
        cell(nRecordings,1);

    zseries.isotropic_mask = ...
        cell(nRecordings,1);

    zseries.z_positions = ...
        cell(nRecordings,1);

    zseries.pixel_size_x_um = ...
        cell(nRecordings,1);

    zseries.pixel_size_y_um = ...
        cell(nRecordings,1);

    zseries.z_step_um = ...
        cell(nRecordings,1);

    zseries.isotropic_voxel_um = ...
        cell(nRecordings,1);

    zseries.registration_shifts_xy = ...
        cell(nRecordings,1);

    zseries.source_path = ...
        cell(nRecordings,1);

    zseries.results_path = ...
        cell(nRecordings,1);


    % ==============================================================
    % RECORDINGS
    % ==============================================================

    for m = 1:nRecordings

        fprintf('\n');
        fprintf('============================================================\n');
        fprintf('ZSeries 3D reconstruction - recording %d/%d\n', ...
            m, ...
            nRecordings);
        fprintf('============================================================\n');


        % ==========================================================
        % ZSeries absent
        % ==========================================================

        if isempty(zseries_paths{m})

            fprintf( ...
                'No ZSeries for recording %d.\n', ...
                m);

            continue;
        end


        current_zseries_path = ...
            zseries_paths{m};


        if ~isfolder(current_zseries_path)

            fprintf( ...
                'ZSeries folder does not exist:\n%s\n', ...
                current_zseries_path);

            continue;
        end


        zseries.source_path{m} = ...
            current_zseries_path;


        % ==========================================================
        % Metadata physiques
        % ==========================================================

        pixel_size_x = ...
            get_zseries_metadata_numeric( ...
                zseries_metadata, ...
                'PixelSizeX_um', ...
                m);

        pixel_size_y = ...
            get_zseries_metadata_numeric( ...
                zseries_metadata, ...
                'PixelSizeY_um', ...
                m);

        z_step = ...
            get_zseries_metadata_numeric( ...
                zseries_metadata, ...
                'ZStep_um', ...
                m);


        if ~isfinite(pixel_size_x)

            warning( ...
                'PixelSizeX_um absent pour recording %d -> 1 um utilisé.', ...
                m);

            pixel_size_x = ...
                1;
        end


        if ~isfinite(pixel_size_y)

            pixel_size_y = ...
                pixel_size_x;
        end


        if ~isfinite(z_step)

            warning( ...
                'ZStep_um absent pour recording %d -> 1 um utilisé.', ...
                m);

            z_step = ...
                1;
        end


        zseries.pixel_size_x_um{m} = ...
            pixel_size_x;

        zseries.pixel_size_y_um{m} = ...
            pixel_size_y;

        zseries.z_step_um{m} = ...
            z_step;


        % ==========================================================
        % Positions Z
        % ==========================================================

        z_positions = ...
            get_zseries_positions( ...
                zseries_metadata, ...
                m);


        zseries.z_positions{m} = ...
            z_positions;


        % ==========================================================
        % Dossier résultats
        % ==========================================================

        output_folder = ...
            current_zseries_path;


        if m <= numel(gcamp_root_folders) && ...
                ~isempty(gcamp_root_folders{m}) && ...
                isfolder(gcamp_root_folders{m})

            output_folder = ...
                gcamp_root_folders{m};
        end


        results_path = ...
            fullfile( ...
                output_folder, ...
                'results_zseries.mat');


        zseries.results_path{m} = ...
            results_path;


        % ==========================================================
        % Charger résultat existant
        % ==========================================================

        loaded_existing = ...
            false;


        if exist(results_path, 'file') == 2

            try

                S = ...
                    load( ...
                        results_path);


                valid_version = ...
                    isfield(S, 'processing_version_saved') && ...
                    S.processing_version_saved == ...
                        processing_version;


                required_fields = { ...
                    'raw_volume', ...
                    'registered_volume', ...
                    'filtered_volume', ...
                    'cell_mask_3d', ...
                    'cells_3d', ...
                    'isotropic_volume', ...
                    'isotropic_mask'};


                has_all = ...
                    true;


                for f = 1:numel(required_fields)

                    if ~isfield( ...
                            S, ...
                            required_fields{f})

                        has_all = ...
                            false;

                        break;
                    end
                end


                if valid_version && ...
                        has_all

                    zseries.raw_volume{m} = ...
                        S.raw_volume;

                    zseries.registered_volume{m} = ...
                        S.registered_volume;

                    zseries.filtered_volume{m} = ...
                        S.filtered_volume;

                    zseries.cell_mask_3d{m} = ...
                        S.cell_mask_3d;

                    zseries.cells_3d{m} = ...
                        S.cells_3d;

                    zseries.isotropic_volume{m} = ...
                        S.isotropic_volume;

                    zseries.isotropic_mask{m} = ...
                        S.isotropic_mask;


                    if isfield(S, 'registration_shifts_xy')

                        zseries.registration_shifts_xy{m} = ...
                            S.registration_shifts_xy;
                    end


                    if isfield(S, 'isotropic_voxel_size_um')

                        zseries.isotropic_voxel_um{m} = ...
                            S.isotropic_voxel_size_um;
                    end


                    loaded_existing = ...
                        true;


                    fprintf( ...
                        'Existing ZSeries reconstruction loaded.\n');

                else

                    fprintf( ...
                        'Existing ZSeries result obsolete -> reprocessing.\n');
                end

            catch ME

                warning( ...
                    'Unable to load existing ZSeries: %s', ...
                    ME.message);
            end
        end


        % ==========================================================
        % Nouvelle reconstruction
        % ==========================================================

        if ~loaded_existing

            % ======================================================
            % 1. Volume brut
            % ======================================================

            [ ...
                raw_volume, ...
                tiff_paths ...
            ] = ...
                reconstruct_raw_zseries_volume( ...
                    current_zseries_path);


            if isempty(raw_volume)
                continue;
            end


            nSlices = ...
                size(raw_volume,3);


            % ======================================================
            % 2. Recalage XY
            % ======================================================

            if apply_xy_registration

                fprintf( ...
                    'Registering Z slices in XY...\n');


                [ ...
                    registered_volume, ...
                    registration_shifts_xy ...
                ] = ...
                    register_zseries_slices( ...
                        raw_volume);

            else

                registered_volume = ...
                    raw_volume;


                registration_shifts_xy = ...
                    zeros( ...
                        nSlices, ...
                        2);
            end


            % ======================================================
            % 3. Détection cellules
            % ======================================================

            fprintf( ...
                'Detecting cellular objects across Z planes...\n');


            [ ...
                filtered_volume, ...
                cell_mask_3d, ...
                cells_3d ...
            ] = ...
                keep_real_cells_3d( ...
                    registered_volume, ...
                    pixel_size_x, ...
                    pixel_size_y, ...
                    z_step);


            % ======================================================
            % 4. Reconstruction isotrope
            % ======================================================

            if isempty(isotropic_voxel_um)

                target_voxel = ...
                    min( ...
                        [ ...
                            pixel_size_x, ...
                            pixel_size_y, ...
                            z_step ...
                        ]) / 1.5;

            else

                target_voxel = ...
                    isotropic_voxel_um;
            end


            [ ...
                isotropic_volume, ...
                isotropic_mask ...
            ] = ...
                make_isotropic_zseries_volume( ...
                    registered_volume, ...
                    cell_mask_3d, ...
                    pixel_size_x, ...
                    pixel_size_y, ...
                    z_step, ...
                    target_voxel);


            % ======================================================
            % Stocker
            % ======================================================

            zseries.raw_volume{m} = ...
                raw_volume;

            zseries.registered_volume{m} = ...
                registered_volume;

            zseries.filtered_volume{m} = ...
                filtered_volume;

            zseries.cell_mask_3d{m} = ...
                cell_mask_3d;

            zseries.cells_3d{m} = ...
                cells_3d;

            zseries.isotropic_volume{m} = ...
                isotropic_volume;

            zseries.isotropic_mask{m} = ...
                isotropic_mask;

            zseries.registration_shifts_xy{m} = ...
                registration_shifts_xy;

            zseries.isotropic_voxel_um{m} = ...
                target_voxel;


            % ======================================================
            % Sauvegarde
            % ======================================================

            isotropic_voxel_size_um = ...
                target_voxel;


            processing_version_saved = ...
                processing_version;


            save( ...
                results_path, ...
                'processing_version_saved', ...
                'raw_volume', ...
                'registered_volume', ...
                'filtered_volume', ...
                'cell_mask_3d', ...
                'cells_3d', ...
                'isotropic_volume', ...
                'isotropic_mask', ...
                'registration_shifts_xy', ...
                'isotropic_voxel_size_um', ...
                'pixel_size_x', ...
                'pixel_size_y', ...
                'z_step', ...
                'z_positions', ...
                'tiff_paths', ...
                '-v7.3');
        end


        % ==========================================================
        % Affichage
        % ==========================================================

        choice = ...
            questdlg( ...
                sprintf( ...
                    [ ...
                    'Afficher la reconstruction 3D filtrée ?\n\n' ...
                    'Recording %d\n' ...
                    '%d cellules retenues' ...
                    ], ...
                    m, ...
                    numel(zseries.cells_3d{m})), ...
                'ZSeries', ...
                '3D filtrée', ...
                'Aucun', ...
                '3D filtrée');


        if strcmp( ...
                choice, ...
                '3D filtrée')

            show_zseries_3d_physical( ...
                zseries.isotropic_volume{m}, ...
                zseries.isotropic_voxel_um{m}, ...
                m);
        end
    end
end


%% ========================================================================
% RECONSTRUCTION VOLUME BRUT
% ========================================================================

function [volume, tiff_paths] = ...
        reconstruct_raw_zseries_volume( ...
            zseries_path)

    volume = [];
    tiff_paths = {};


    tiff_files = ...
        dir( ...
            fullfile( ...
                zseries_path, ...
                '*.tif'));


    if isempty(tiff_files)

        raw_data_path = ...
            fullfile( ...
                zseries_path, ...
                'raw_data');


        if isfolder(raw_data_path)

            tiff_files = ...
                dir( ...
                    fullfile( ...
                        raw_data_path, ...
                        '*.tif'));

            zseries_path = ...
                raw_data_path;
        end
    end


    if isempty(tiff_files)

        fprintf( ...
            'No TIFF found in ZSeries folder.\n');

        return;
    end


    frame_numbers = ...
        nan(numel(tiff_files),1);


    for i = 1:numel(tiff_files)

        token = ...
            regexp( ...
                tiff_files(i).name, ...
                '_(\d+)\.ome\.tif$', ...
                'tokens', ...
                'once');


        if isempty(token)

            token = ...
                regexp( ...
                    tiff_files(i).name, ...
                    '_(\d+)\.tif$', ...
                    'tokens', ...
                    'once');
        end


        if ~isempty(token)

            frame_numbers(i) = ...
                str2double( ...
                    token{1});
        end
    end


    if all(isfinite(frame_numbers))

        [~, order] = ...
            sort(frame_numbers);

    else

        [~, order] = ...
            sort( ...
                {tiff_files.name});
    end


    tiff_files = ...
        tiff_files(order);


    first_path = ...
        fullfile( ...
            zseries_path, ...
            tiff_files(1).name);


    first_image = ...
        imread(first_path);


    if ndims(first_image) > 2

        first_image = ...
            first_image(:,:,1);
    end


    [ny, nx] = ...
        size(first_image);


    nz = ...
        numel(tiff_files);


    volume = ...
        zeros( ...
            ny, ...
            nx, ...
            nz, ...
            'like', ...
            first_image);


    tiff_paths = ...
        cell(nz,1);


    for z = 1:nz

        current_path = ...
            fullfile( ...
                zseries_path, ...
                tiff_files(z).name);


        current_image = ...
            imread(current_path);


        if ndims(current_image) > 2

            current_image = ...
                current_image(:,:,1);
        end


        if size(current_image,1) ~= ny || ...
                size(current_image,2) ~= nx

            error( ...
                'Different image size in ZSeries: %s', ...
                current_path);
        end


        volume(:,:,z) = ...
            current_image;


        tiff_paths{z} = ...
            current_path;
    end
end


%% ========================================================================
% RECALAGE XY
% ========================================================================

function [registered_volume, shifts_xy] = ...
        register_zseries_slices( ...
            volume)

    nz = ...
        size(volume,3);


    registered_volume = ...
        zeros( ...
            size(volume), ...
            'like', ...
            volume);


    shifts_xy = ...
        zeros(nz,2);


    reference_idx = ...
        round(nz / 2);


    registered_volume(:,:,reference_idx) = ...
        volume(:,:,reference_idx);


    previous_reference = ...
        single(volume(:,:,reference_idx));


    for z = reference_idx-1:-1:1

        moving = ...
            single(volume(:,:,z));


        shift = ...
            estimate_translation_phasecorr( ...
                moving, ...
                previous_reference);


        registered = ...
            imtranslate( ...
                volume(:,:,z), ...
                shift, ...
                'OutputView', ...
                'same', ...
                'FillValues', ...
                0);


        registered_volume(:,:,z) = ...
            registered;

        shifts_xy(z,:) = ...
            shift;

        previous_reference = ...
            single(registered);
    end


    previous_reference = ...
        single(volume(:,:,reference_idx));


    for z = reference_idx+1:nz

        moving = ...
            single(volume(:,:,z));


        shift = ...
            estimate_translation_phasecorr( ...
                moving, ...
                previous_reference);


        registered = ...
            imtranslate( ...
                volume(:,:,z), ...
                shift, ...
                'OutputView', ...
                'same', ...
                'FillValues', ...
                0);


        registered_volume(:,:,z) = ...
            registered;

        shifts_xy(z,:) = ...
            shift;

        previous_reference = ...
            single(registered);
    end
end


%% ========================================================================
% ESTIMATION TRANSLATION
% ========================================================================

function shift_xy = ...
        estimate_translation_phasecorr( ...
            moving, ...
            fixed)

    moving = ...
        mat2gray(moving);

    fixed = ...
        mat2gray(fixed);


    try

        tform = ...
            imregcorr( ...
                moving, ...
                fixed, ...
                'translation');


        shift_xy = ...
            [ ...
                tform.T(3,1), ...
                tform.T(3,2) ...
            ];


        max_shift_px = ...
            20;


        shift_xy = ...
            max( ...
                min( ...
                    shift_xy, ...
                    max_shift_px), ...
                -max_shift_px);

    catch

        shift_xy = ...
            [0 0];
    end
end


%% ========================================================================
% DÉTECTION CELLULAIRE
% ========================================================================

function [filtered_volume, cell_mask_3d, cells_3d] = ...
        keep_real_cells_3d( ...
            volume, ...
            pixel_size_x_um, ...
            pixel_size_y_um, ...
            z_step_um)


    % ==============================================================
    % PARAMÈTRES
    % ==============================================================

    intensity_percentile = ...
        98.5;


    min_area_um2 = ...
        60;

    max_area_um2 = ...
        1500;


    min_circularity = ...
        0.60;


    min_consecutive_planes = ...
        3;


    max_centroid_distance_um = ...
        10;


    min_overlap_fraction = ...
        0.15;


    min_cell_volume_um3 = ...
        800;

    max_cell_volume_um3 = ...
        20000;


    % ==============================================================
    % CONTRASTE PAR SLICE
    %
    % Utilisé UNIQUEMENT pour la détection.
    % Le volume original n'est pas modifié.
    % ==============================================================

    use_clahe = ...
        true;

    clahe_clip_limit = ...
        0.01;

    clahe_num_tiles = ...
        [8 8];


    % ==============================================================
    % Conversion aire
    % ==============================================================

    pixel_area_um2 = ...
        pixel_size_x_um * ...
        pixel_size_y_um;


    min_area_px = ...
        max( ...
            3, ...
            round( ...
                min_area_um2 / ...
                pixel_area_um2));


    max_area_px = ...
        max( ...
            min_area_px + 1, ...
            round( ...
                max_area_um2 / ...
                pixel_area_um2));


    [ny, nx, nz] = ...
        size(volume);


    detections_by_plane = ...
        cell(nz,1);


    % ==============================================================
    % CANDIDATS 2D
    % ==============================================================

    for z = 1:nz

        image_original = ...
            single(volume(:,:,z));


        valid_pixels = ...
            image_original( ...
                isfinite(image_original));


        if isempty(valid_pixels)
            continue;
        end


        % ==========================================================
        % Normalisation robuste propre à la slice
        % ==========================================================

        low_value = ...
            prctile( ...
                valid_pixels, ...
                1);


        high_value = ...
            prctile( ...
                valid_pixels, ...
                99.8);


        if high_value <= low_value
            continue;
        end


        image_detection = ...
            (image_original - low_value) ./ ...
            (high_value - low_value);


        image_detection = ...
            min( ...
                max( ...
                    image_detection, ...
                    0), ...
                1);


        % ==========================================================
        % CLAHE
        % ==========================================================

        if use_clahe

            image_detection = ...
                adapthisteq( ...
                    image_detection, ...
                    'NumTiles', ...
                    clahe_num_tiles, ...
                    'ClipLimit', ...
                    clahe_clip_limit);
        end


        % ==========================================================
        % Seuil d'intensité
        % ==========================================================

        detection_pixels = ...
            image_detection( ...
                isfinite(image_detection));


        threshold = ...
            prctile( ...
                detection_pixels, ...
                intensity_percentile);


        binary = ...
            image_detection >= ...
            threshold;


        % ==========================================================
        % Nettoyage
        % ==========================================================

        binary = ...
            bwareaopen( ...
                binary, ...
                min_area_px);


        binary = ...
            imfill( ...
                binary, ...
                'holes');


        binary = ...
            imclose( ...
                binary, ...
                strel( ...
                    'disk', ...
                    1));


        % ==========================================================
        % Composantes 2D
        % ==========================================================

        CC = ...
            bwconncomp( ...
                binary, ...
                8);


        props = ...
            regionprops( ...
                CC, ...
                'Area', ...
                'Perimeter', ...
                'Centroid', ...
                'PixelIdxList');


        detections = ...
            struct( ...
                'Area_um2', {}, ...
                'Circularity', {}, ...
                'Centroid_px', {}, ...
                'Centroid_um', {}, ...
                'Mask', {}, ...
                'Plane', {});


        detection_idx = ...
            0;


        for i = 1:numel(props)

            area = ...
                props(i).Area;


            perimeter = ...
                props(i).Perimeter;


            if area < min_area_px || ...
                    area > max_area_px || ...
                    perimeter <= 0

                continue;
            end


            circularity = ...
                4 * pi * area / ...
                perimeter^2;


            if circularity < ...
                    min_circularity

                continue;
            end


            detection_idx = ...
                detection_idx + 1;


            mask = ...
                false(ny,nx);


            mask( ...
                props(i).PixelIdxList) = ...
                true;


            centroid_px = ...
                props(i).Centroid;


            centroid_um = ...
                [ ...
                    centroid_px(1) * ...
                        pixel_size_x_um, ...
                    centroid_px(2) * ...
                        pixel_size_y_um ...
                ];


            detections(detection_idx).Area_um2 = ...
                area * ...
                pixel_area_um2;


            detections(detection_idx).Circularity = ...
                circularity;


            detections(detection_idx).Centroid_px = ...
                centroid_px;


            detections(detection_idx).Centroid_um = ...
                centroid_um;


            detections(detection_idx).Mask = ...
                mask;


            detections(detection_idx).Plane = ...
                z;
        end


        detections_by_plane{z} = ...
            detections;
    end


    % ==============================================================
    % TRACKING ENTRE PLANS
    % ==============================================================

    tracks = ...
        struct( ...
            'planes', {}, ...
            'detections', {});


    nTracks = ...
        0;


    for z = 1:nz

        detections = ...
            detections_by_plane{z};


        if isempty(detections)
            continue;
        end


        used_tracks = ...
            false( ...
                max(nTracks,1), ...
                1);


        for d = 1:numel(detections)

            current_detection = ...
                detections(d);


            best_track = ...
                0;


            best_score = ...
                inf;


            for tr = 1:nTracks

                if tracks(tr).planes(end) ~= ...
                        z - 1

                    continue;
                end


                if tr <= numel(used_tracks) && ...
                        used_tracks(tr)

                    continue;
                end


                previous_detection = ...
                    tracks(tr).detections(end);


                delta = ...
                    current_detection.Centroid_um - ...
                    previous_detection.Centroid_um;


                centroid_distance = ...
                    sqrt( ...
                        sum(delta.^2));


                if centroid_distance > ...
                        max_centroid_distance_um

                    continue;
                end


                intersection = ...
                    nnz( ...
                        current_detection.Mask & ...
                        previous_detection.Mask);


                min_object_area = ...
                    min( ...
                        nnz(current_detection.Mask), ...
                        nnz(previous_detection.Mask));


                if min_object_area > 0

                    overlap_fraction = ...
                        intersection / ...
                        min_object_area;

                else

                    overlap_fraction = ...
                        0;
                end


                if overlap_fraction < ...
                        min_overlap_fraction && ...
                        centroid_distance > ...
                        max_centroid_distance_um / 2

                    continue;
                end


                normalized_distance = ...
                    centroid_distance / ...
                    max_centroid_distance_um;


                score = ...
                    normalized_distance - ...
                    overlap_fraction;


                if score < best_score

                    best_score = ...
                        score;

                    best_track = ...
                        tr;
                end
            end


            if best_track > 0

                tracks(best_track).planes(end+1) = ...
                    z;


                tracks(best_track).detections(end+1) = ...
                    current_detection;


                used_tracks(best_track) = ...
                    true;

            else

                nTracks = ...
                    nTracks + 1;


                tracks(nTracks).planes = ...
                    z;


                tracks(nTracks).detections = ...
                    current_detection;


                if numel(used_tracks) < nTracks

                    used_tracks(nTracks,1) = ...
                        true;

                else

                    used_tracks(nTracks) = ...
                        true;
                end
            end
        end
    end


    % ==============================================================
    % TRACKS PERSISTANTS
    % ==============================================================

    initial_cell_mask_3d = ...
        false( ...
            ny, ...
            nx, ...
            nz);


    valid_track_idx = ...
        0;


    for tr = 1:nTracks

        planes = ...
            tracks(tr).planes;


        if numel(planes) < ...
                min_consecutive_planes

            continue;
        end


        if any(diff(planes) ~= 1)
            continue;
        end


        valid_track_idx = ...
            valid_track_idx + 1;


        for j = 1:numel(planes)

            plane = ...
                planes(j);


            detection = ...
                tracks(tr).detections(j);


            initial_cell_mask_3d(:,:,plane) = ...
                initial_cell_mask_3d(:,:,plane) | ...
                detection.Mask;
        end
    end


    % ==============================================================
    % FILTRAGE FINAL 3D
    % ==============================================================

    voxel_volume_um3 = ...
        pixel_size_x_um * ...
        pixel_size_y_um * ...
        z_step_um;


    CC3D = ...
        bwconncomp( ...
            initial_cell_mask_3d, ...
            26);


    cell_mask_3d = ...
        false( ...
            size(initial_cell_mask_3d));


    cells_3d = ...
        struct( ...
            'Volume_um3', {}, ...
            'CentroidXYZ_um', {}, ...
            'DiameterX_um', {}, ...
            'DiameterY_um', {}, ...
            'ZExtent_um', {});


    cell_idx = ...
        0;


    for c = 1:CC3D.NumObjects

        voxel_idx = ...
            CC3D.PixelIdxList{c};


        n_voxels = ...
            numel(voxel_idx);


        current_volume_um3 = ...
            n_voxels * ...
            voxel_volume_um3;


        if current_volume_um3 < ...
                min_cell_volume_um3 || ...
                current_volume_um3 > ...
                max_cell_volume_um3

            continue;
        end


        [yy, xx, zz] = ...
            ind2sub( ...
                size(initial_cell_mask_3d), ...
                voxel_idx);


        diameter_x_um = ...
            (max(xx) - min(xx) + 1) * ...
            pixel_size_x_um;


        diameter_y_um = ...
            (max(yy) - min(yy) + 1) * ...
            pixel_size_y_um;


        z_extent_um = ...
            (max(zz) - min(zz) + 1) * ...
            z_step_um;


        cell_mask_3d(voxel_idx) = ...
            true;


        cell_idx = ...
            cell_idx + 1;


        cells_3d(cell_idx).Volume_um3 = ...
            current_volume_um3;


        cells_3d(cell_idx).CentroidXYZ_um = ...
            [ ...
                mean(xx) * ...
                    pixel_size_x_um, ...
                mean(yy) * ...
                    pixel_size_y_um, ...
                mean(zz) * ...
                    z_step_um ...
            ];


        cells_3d(cell_idx).DiameterX_um = ...
            diameter_x_um;


        cells_3d(cell_idx).DiameterY_um = ...
            diameter_y_um;


        cells_3d(cell_idx).ZExtent_um = ...
            z_extent_um;
    end


    % ==============================================================
    % Volume filtré
    % ==============================================================

    filtered_volume = ...
        zeros( ...
            size(volume), ...
            'like', ...
            volume);


    filtered_volume(cell_mask_3d) = ...
        volume(cell_mask_3d);


    fprintf('\n');
    fprintf('Candidate tracks  : %d\n', nTracks);
    fprintf('Persistent tracks : %d\n', valid_track_idx);
    fprintf('3D components     : %d\n', CC3D.NumObjects);
    fprintf('Cells retained    : %d\n', numel(cells_3d));
end


%% ========================================================================
% RECONSTRUCTION ISOTROPE AVEC INTERPOLATION
% ========================================================================

function [isotropic_volume, isotropic_mask] = ...
        make_isotropic_zseries_volume( ...
            volume, ...
            cell_mask_3d, ...
            pixel_size_x, ...
            pixel_size_y, ...
            z_step, ...
            target_voxel)


    [ny, nx, nz] = ...
        size(volume);


    physical_x = ...
        nx * ...
        pixel_size_x;


    physical_y = ...
        ny * ...
        pixel_size_y;


    physical_z = ...
        nz * ...
        z_step;


    new_nx = ...
        max( ...
            1, ...
            round( ...
                physical_x / ...
                target_voxel));


    new_ny = ...
        max( ...
            1, ...
            round( ...
                physical_y / ...
                target_voxel));


    new_nz = ...
        max( ...
            1, ...
            round( ...
                physical_z / ...
                target_voxel));


    % ==============================================================
    % Intensité interpolée
    % ==============================================================

    isotropic_intensity = ...
        imresize3( ...
            single(volume), ...
            [ ...
                new_ny, ...
                new_nx, ...
                new_nz ...
            ], ...
            'cubic');


    % ==============================================================
    % Masque interpolé
    % ==============================================================

    isotropic_mask_float = ...
        imresize3( ...
            single(cell_mask_3d), ...
            [ ...
                new_ny, ...
                new_nx, ...
                new_nz ...
            ], ...
            'linear');


    % ==============================================================
    % Lissage léger
    % ==============================================================

    isotropic_mask_float = ...
        imgaussfilt3( ...
            isotropic_mask_float, ...
            0.8);


    % ==============================================================
    % Rebinarisation
    % ==============================================================

    isotropic_mask = ...
        isotropic_mask_float >= ...
        0.35;


    % ==============================================================
    % Volume final
    % ==============================================================

    isotropic_volume = ...
        zeros( ...
            size(isotropic_intensity), ...
            'single');


    isotropic_volume(isotropic_mask) = ...
        isotropic_intensity(isotropic_mask);
end


%% ========================================================================
% AFFICHAGE 3D
% ========================================================================

function show_zseries_3d_physical( ...
        volume, ...
        voxel_size_um, ...
        recording_idx)


    if isempty(volume)
        return;
    end


    volume_display = ...
        single(volume);


    nonzero_values = ...
        volume_display( ...
            volume_display > 0 & ...
            isfinite(volume_display));


    if isempty(nonzero_values)

        fprintf( ...
            'No detected cells to display.\n');

        return;
    end


    lo = ...
        prctile( ...
            nonzero_values, ...
            1);


    hi = ...
        prctile( ...
            nonzero_values, ...
            99.8);


    if hi > lo

        volume_display = ...
            (volume_display - lo) ./ ...
            (hi - lo);


        volume_display = ...
            min( ...
                max( ...
                    volume_display, ...
                    0), ...
                1);


        volume_display(volume <= 0) = ...
            0;
    end


    if exist('volshow', 'file') == 2

        volshow( ...
            volume_display);

        return;
    end


    figure( ...
        'Name', ...
        sprintf( ...
            'Filtered ZSeries 3D - recording %d', ...
            recording_idx), ...
        'NumberTitle', ...
        'off');


    mask_display = ...
        volume_display > 0;


    surface = ...
        patch( ...
            isosurface( ...
                mask_display, ...
                0.5));


    isonormals( ...
        mask_display, ...
        surface);


    set( ...
        surface, ...
        'FaceColor', ...
        [0.8 0.8 0.8], ...
        'EdgeColor', ...
        'none');


    daspect([1 1 1]);

    axis tight;

    view(3);

    camlight;

    lighting gouraud;
end


%% ========================================================================
% GET NUMERIC METADATA
% ========================================================================

function value = ...
        get_zseries_metadata_numeric( ...
            metadata, ...
            field, ...
            idx)


    value = ...
        NaN;


    if isempty(metadata) || ...
            ~isfield(metadata, field) || ...
            numel(metadata.(field)) < idx || ...
            isempty(metadata.(field){idx})

        return;
    end


    value = ...
        metadata.(field){idx};


    if ischar(value) || ...
            isstring(value)

        value = ...
            str2double(value);
    end
end


%% ========================================================================
% GET Z POSITIONS
% ========================================================================

function z_positions = ...
        get_zseries_positions( ...
            metadata, ...
            idx)


    z_positions = ...
        [];


    if isempty(metadata) || ...
            ~isfield(metadata, 'ZPositions') || ...
            numel(metadata.ZPositions) < idx || ...
            isempty(metadata.ZPositions{idx})

        return;
    end


    value = ...
        metadata.ZPositions{idx};


    if isnumeric(value)

        z_positions = ...
            value(:).';

        return;
    end


    z_positions = ...
        sscanf( ...
            value, ...
            '%f').';
end