function [motion, camFolders, needs_processing] = load_or_process_movie( ...
    current_gcamp_TSeries_path, ...
    gcamp_output_folders, ...
    avg_block, ...
    sampling_rate_group, ...
    current_animal_group, ...
    data, ...
    processing_mode)

% LOAD_OR_PROCESS_MOVIE
%
% Charge ou calcule l'énergie de mouvement pour chaque acquisition.
%
% Organisation :
%   m = acquisition / TSeries
%
% Sorties :
%   motion
%       Structure contenant uniquement les données de mouvement.
%
%   camFolders
%       Cell array contenant le dossier caméra correspondant
%       à chaque acquisition / TSeries.
%
% La fonction :
%   - conserve les données motion déjà présentes en mémoire ;
%   - recharge results_motion.mat uniquement si nécessaire ;
%   - renomme les anciens results_movie.mat en results_motion.mat ;
%   - recharge camFolders depuis results_motion.mat s'il existe ;
%   - sinon recherche automatiquement :
%         TSeries\cam\Concatenated
%         TSeries\camera\Concatenated
%   - ajoute camFolders aux anciens results_motion.mat ;
%   - calcule la motion energy si demandé ;
%   - détecte les périodes de mouvement ;
%   - sauvegarde les résultats par acquisition.
%
% IMPORTANT :
%   camFolders n'est PAS stocké dans data.motion.


    if nargin < 7 || isempty(processing_mode)
        processing_mode = 'interactive';
    end

    processing_mode = char(string(processing_mode));

    if ~ismember(lower(processing_mode), {'load_only', 'interactive'})
        error( ...
            'processing_mode must be ''load_only'' or ''interactive''.');
    end

    is_load_only = ...
        strcmpi(processing_mode, 'load_only');

    needs_processing = false;

    numAcquisitions = ...
        numel(current_gcamp_TSeries_path);

    fields_motion = { ...
        'motion_energy_group', ...
        'motion_energy_smooth_group', ...
        'avg_active_motion_onsets_group', ...
        'avg_active_motion_offsets_group', ...
        'active_motion_onsets_group', ...
        'active_motion_offsets_group', ...
        'speed_active_group', ...
        'motion_energy_status' ...
    };

    % Preserve which entries genuinely existed in the input data BEFORE
    % preallocation. This lets us distinguish a valid stored [] (for
    % example no detected motion periods) from a field that was absent and
    % has just been created as an empty placeholder by initialization.
    initial_motion_presence = ...
        capture_motion_field_presence( ...
            data, ...
            fields_motion, ...
            numAcquisitions);

    data = init_motion_data_struct_if_needed( ...
        data, ...
        numAcquisitions, ...
        fields_motion);

    camFolders = ...
        cell(numAcquisitions, 1);

    fijiPath = ...
        'C:\Users\goldstein\Fiji.app\fiji-windows-x64.exe';

    motion_strategy = [];
    motion_strategy_initialized = false;

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('MOTION PROCESSING\n');
    fprintf('Animal       : %s\n', char(string(current_animal_group)));
    fprintf('Acquisitions : %d\n', numAcquisitions);
    fprintf('Average block: %d frames\n', avg_block);
    fprintf('============================================================\n');

    for m = 1:numAcquisitions

        data = ensure_motion_entry_exists( ...
            data, ...
            fields_motion, ...
            numAcquisitions, ...
            m);

        tseries_path_m = get_tseries_path( ...
            current_gcamp_TSeries_path, ...
            m);

        tseries_name = find_tseries_name_in_path( ...
            tseries_path_m);

        sampling_rate_m = get_sampling_rate( ...
            sampling_rate_group, ...
            m);

        fprintf('\n');
        fprintf('------------------------------------------------------------\n');
        fprintf('Motion acquisition %d/%d\n', m, numAcquisitions);
        fprintf('Animal       : %s\n', char(string(current_animal_group)));
        fprintf('TSeries      : %s\n', tseries_name);
        fprintf('Sampling rate: %.4f Hz\n', sampling_rate_m);
        fprintf('------------------------------------------------------------\n');

        root_folder_m = extract_motion_root_folder( ...
            gcamp_output_folders, ...
            m);

        if isempty(root_folder_m)

            warning( ...
                'load_or_process_movie:MissingOutputFolder', ...
                ['Acquisition %d/%d | %s | impossible de ' ...
                 'déterminer le dossier de sortie.'], ...
                m, ...
                numAcquisitions, ...
                tseries_name);

            fprintf( ...
                'Status: skipped because output folder is missing.\n');

            continue;
        end

        fprintf( ...
            'Output folder: %s\n', ...
            root_folder_m);

        oldPath = fullfile( ...
            root_folder_m, ...
            'results_movie.mat');

        savePath = fullfile( ...
            root_folder_m, ...
            'results_motion.mat');

        % =========================================================
        % Rename old results file
        % =========================================================

        if exist(oldPath, 'file') == 2 && ...
                exist(savePath, 'file') ~= 2

            try

                movefile( ...
                    oldPath, ...
                    savePath);

                fprintf( ...
                    ['Existing results_movie.mat renamed to ' ...
                     'results_motion.mat.\n']);

            catch ME

                warning( ...
                    'load_or_process_movie:RenameFailed', ...
                    ['Acquisition %d/%d | %s | unable to rename ' ...
                     'results_movie.mat: %s'], ...
                    m, ...
                    numAcquisitions, ...
                    tseries_name, ...
                    ME.message);
            end
        end

        % =========================================================
        % Camera folder
        %
        % 1. Try loading camFolders from results_motion.mat.
        % 2. If missing / invalid, reconstruct from TSeries.
        % 3. Update results_motion.mat if necessary.
        %
        % camFolders remains independent from data.motion.
        % =========================================================

        fprintf('\nCamera folder\n');

        cam_folder_m = [];
        cam_folder_needs_save = false;

        % ---------------------------------------------------------
        % Load existing camFolders from results_motion.mat
        % ---------------------------------------------------------

        if exist(savePath, 'file') == 2

            try

                cam_variable = ...
                    whos( ...
                        '-file', ...
                        savePath, ...
                        'camFolders');

                if ~isempty(cam_variable)

                    loaded_cam = load( ...
                        savePath, ...
                        'camFolders');

                    saved_cam = ...
                        loaded_cam.camFolders;

                    if iscell(saved_cam)

                        if ~isempty(saved_cam)

                            cam_folder_m = ...
                                saved_cam{1};
                        end

                    else

                        cam_folder_m = ...
                            saved_cam;
                    end

                    if ~isempty(cam_folder_m) && ...
                            isfolder(cam_folder_m)

                        fprintf( ...
                            '  Status: saved camera folder reused.\n');

                        fprintf( ...
                            '  Folder: %s\n', ...
                            cam_folder_m);

                    else

                        cam_folder_m = [];

                        fprintf( ...
                            ['  Status: saved camera folder is empty ' ...
                             'or no longer exists.\n']);
                    end
                end

            catch ME

                warning( ...
                    'load_or_process_movie:CameraPathLoadFailed', ...
                    ['Acquisition %d/%d | %s | unable to load ' ...
                     'camFolders from results_motion.mat: %s'], ...
                    m, ...
                    numAcquisitions, ...
                    tseries_name, ...
                    ME.message);
            end
        end

        % ---------------------------------------------------------
        % Reconstruct camera folder if necessary
        % ---------------------------------------------------------

        if isempty(cam_folder_m)

            camPath = fullfile( ...
                tseries_path_m, ...
                'cam', ...
                'Concatenated');

            cameraPath = fullfile( ...
                tseries_path_m, ...
                'camera', ...
                'Concatenated');

            if isfolder(camPath)

                cam_folder_m = ...
                    camPath;

                cam_folder_needs_save = true;

                fprintf( ...
                    '  Status: camera folder found.\n');

                fprintf( ...
                    '  Folder: %s\n', ...
                    cam_folder_m);

            elseif isfolder(cameraPath)

                cam_folder_m = ...
                    cameraPath;

                cam_folder_needs_save = true;

                fprintf( ...
                    '  Status: camera folder found.\n');

                fprintf( ...
                    '  Folder: %s\n', ...
                    cam_folder_m);

            else

                cam_folder_m = [];

                fprintf( ...
                    '  Status: no camera folder found.\n');

                fprintf( ...
                    '  Search: %s\n', ...
                    camPath);

                fprintf( ...
                    '          %s\n', ...
                    cameraPath);

                % Sauvegarde également l'absence du dossier caméra
                % si la variable n'était pas encore présente.
                if exist(savePath, 'file') == 2

                    try

                        cam_variable = ...
                            whos( ...
                                '-file', ...
                                savePath, ...
                                'camFolders');

                        if isempty(cam_variable)

                            cam_folder_needs_save = true;
                        end

                    catch
                    end
                end
            end
        end

        camFolders{m} = ...
            cam_folder_m;

        % ---------------------------------------------------------
        % Add / update camFolders in results_motion.mat
        %
        % Each results_motion.mat corresponds to one acquisition,
        % therefore camFolders stored in the file contains the
        % camera path for THIS acquisition.
        % ---------------------------------------------------------

        if cam_folder_needs_save

            saveCam = struct();

            saveCam.camFolders = ...
                cam_folder_m;

            try

                if exist(savePath, 'file') == 2

                    save( ...
                        savePath, ...
                        '-struct', ...
                        'saveCam', ...
                        '-append');

                else

                    save( ...
                        savePath, ...
                        '-struct', ...
                        'saveCam');
                end

                fprintf( ...
                    '  Saved : camFolders added to results_motion.mat.\n');

            catch ME

                warning( ...
                    'load_or_process_movie:CameraPathSaveFailed', ...
                    ['Acquisition %d/%d | %s | unable to save ' ...
                     'camFolders: %s'], ...
                    m, ...
                    numAcquisitions, ...
                    tseries_name, ...
                    ME.message);
            end
        end

        % =========================================================
        % Data already complete in memory
        %
        % IMPORTANT:
        % Camera folder has already been handled above because
        % camFolders is intentionally independent from data.motion.
        % =========================================================

        already_has_all = ...
            motion_already_complete( ...
                data, ...
                m);

        if already_has_all

            status_name = ...
                get_motion_status_name( ...
                    data, ...
                    m);

            fprintf('\n');
            fprintf('Memory status: complete.\n');
            fprintf('Motion status: %s\n', status_name);
            fprintf( ...
                'Action       : no reload or recalculation required.\n');

            if ~is_load_only

                save_motion_figure_if_missing( ...
                    root_folder_m, ...
                    data, ...
                    m, ...
                    current_animal_group, ...
                    tseries_name, ...
                    sampling_rate_m, ...
                    avg_block);
            end

            continue;
        end

        % =========================================================
        % Complete memory selectively from results_motion.mat
        %
        % Only the variables that are genuinely needed are loaded.
        % results_motion.mat is never loaded in full.
        %
        % For a status "done", empty onset/offset arrays can be valid
        % results (no movement period). Their original presence before
        % initialization is therefore taken into account.
        %
        % For "no_camera" / "no_motion", the saved state is deliberately
        % not reloaded: the filesystem is rechecked below so newly added
        % camera data can be detected.
        % =========================================================

        has_new_data_for_acquisition = false;

        if exist(savePath, 'file') == 2

            fields_to_load = ...
                get_motion_fields_to_load( ...
                    data, ...
                    fields_motion, ...
                    initial_motion_presence(:, m), ...
                    m);

            fprintf('\n');
            fprintf('Memory status: incomplete.\n');

            if isempty(fields_to_load)

                fprintf( ...
                    ['Saved motion data: no variable needs to be ' ...
                     'loaded from results_motion.mat.\n']);

            else

                try

                    variables_in_file = ...
                        whos('-file', savePath);

                    variable_names = ...
                        {variables_in_file.name};

                    fields_available = ...
                        fields_to_load( ...
                            ismember( ...
                                fields_to_load, ...
                                variable_names));

                    if isempty(fields_available)

                        fprintf( ...
                            ['Saved motion data: none of the missing ' ...
                             'variables is available in results_motion.mat.\n']);

                    else

                        fprintf( ...
                            'Loading only missing motion variables:\n');

                        for field_idx = 1:numel(fields_available)

                            fprintf( ...
                                '  %s\n', ...
                                fields_available{field_idx});
                        end

                        loaded = ...
                            load( ...
                                savePath, ...
                                fields_available{:});

                        data = ...
                            merge_loaded_motion_into_data( ...
                                data, ...
                                loaded, ...
                                fields_available, ...
                                m);

                    end

                catch ME

                    warning( ...
                        'load_or_process_movie:ResultsLoadFailed', ...
                        ['Acquisition %d/%d | %s | unable to load ' ...
                         'missing fields from results_motion.mat: %s'], ...
                        m, ...
                        numAcquisitions, ...
                        tseries_name, ...
                        ME.message);
                end

            end

        else

            fprintf('\n');
            fprintf( ...
                'Saved motion file: not found.\n');
        end

        already_has_all = ...
            motion_already_complete( ...
                data, ...
                m);

        if already_has_all

            status_name = ...
                get_motion_status_name( ...
                    data, ...
                    m);

            fprintf( ...
                'Memory completed from saved file.\n');

            fprintf( ...
                'Motion status: %s\n', ...
                status_name);

            fprintf( ...
                'Action       : calculation skipped.\n');

            if ~is_load_only

                save_motion_figure_if_missing( ...
                    root_folder_m, ...
                    data, ...
                    m, ...
                    current_animal_group, ...
                    tseries_name, ...
                    sampling_rate_m, ...
                    avg_block);
            end

            continue;
        end

        % =========================================================
        % LOAD ONLY
        %
        % Existing saved motion values have already been merged above.
        % If the acquisition is still incomplete, stop here: no prompt,
        % no Fiji launch, no motion-energy calculation and no figure.
        % =========================================================

        if is_load_only

            needs_processing = true;

            fprintf( ...
                ['LOAD ONLY: motion data remain incomplete for this ' ...
                 'acquisition; calculation deferred to the sequential ' ...
                 'fallback.\n']);

            continue;
        end

        % =========================================================
        % No camera folder
        % =========================================================

        if isempty(cam_folder_m)

            data = assign_empty_motion_fields_if_missing( ...
                data, ...
                m);

            data.motion.motion_energy_status{m} = ...
                'no_camera';

            has_new_data_for_acquisition = ...
                true;

            save_motion_fields_if_needed( ...
                savePath, ...
                data, ...
                fields_motion, ...
                m, ...
                has_new_data_for_acquisition, ...
                tseries_name);

            continue;
        end

        % =========================================================
        % Camera movie
        % =========================================================

        filepath = fullfile( ...
            cam_folder_m, ...
            'cam_crop.tif');

        fprintf('\nCamera data\n');

        if exist(filepath, 'file') ~= 2

            fprintf( ...
                '  Movie status: cam_crop.tif not found.\n');

            fprintf( ...
                '  Expected file: %s\n', ...
                filepath);

            data = assign_empty_motion_fields_if_missing( ...
                data, ...
                m);

            data.motion.motion_energy_status{m} = ...
                'no_motion';

            has_new_data_for_acquisition = ...
                true;

            save_motion_fields_if_needed( ...
                savePath, ...
                data, ...
                fields_motion, ...
                m, ...
                has_new_data_for_acquisition, ...
                tseries_name);

            continue;
        end

        fprintf( ...
            '  Movie status: camera movie available.\n');

        fprintf( ...
            '  Movie file  : %s\n', ...
            filepath);

        % =========================================================
        % 1. Motion energy
        % =========================================================

        fprintf('\nMotion energy\n');

        if ~motion_field_has_value( ...
                data, ...
                'motion_energy_group', ...
                m)

            fprintf( ...
                ['  Status: motion energy not available ' ...
                 'in memory.\n']);

            if ~motion_strategy_initialized

                motion_strategy = ...
                    ask_motion_energy_strategy_once();

                motion_strategy_initialized = ...
                    true;
            end

            motion_energy = ...
                compute_motion_energy_with_strategy( ...
                    filepath, ...
                    fijiPath, ...
                    motion_strategy);

            data.motion.motion_energy_group{m} = ...
                motion_energy;

            if isempty(motion_energy)

                data.motion.motion_energy_status{m} = ...
                    'skipped';

                fprintf( ...
                    ['  Result: motion energy calculation ' ...
                     'skipped.\n']);

            else

                data.motion.motion_energy_status{m} = ...
                    'processing';

                fprintf( ...
                    '  Result: motion energy calculated.\n');

                fprintf( ...
                    '  Frames: %d\n', ...
                    numel(motion_energy));
            end

            has_new_data_for_acquisition = ...
                true;

        else

            motion_energy = ...
                data.motion.motion_energy_group{m};

            fprintf( ...
                '  Status: existing motion energy reused.\n');

            fprintf( ...
                '  Frames: %d\n', ...
                numel(motion_energy));

            if ~motion_status_exists(data, m) || ...
                    isempty(data.motion.motion_energy_status{m})

                data.motion.motion_energy_status{m} = ...
                    'processing';

                has_new_data_for_acquisition = ...
                    true;
            end
        end

        if isempty(motion_energy)

            data = assign_empty_motion_fields_if_missing( ...
                data, ...
                m);

            has_new_data_for_acquisition = ...
                true;

            save_motion_fields_if_needed( ...
                savePath, ...
                data, ...
                fields_motion, ...
                m, ...
                has_new_data_for_acquisition, ...
                tseries_name);

            continue;
        end

        % =========================================================
        % 2. Temporal averaging
        % =========================================================

        avg_motion_energy = average_frames( ...
            motion_energy, ...
            avg_block);

        fprintf('\nTemporal averaging\n');

        fprintf( ...
            '  Input frames : %d\n', ...
            numel(motion_energy));

        fprintf( ...
            '  Block size   : %d\n', ...
            avg_block);

        fprintf( ...
            '  Output points: %d\n', ...
            numel(avg_motion_energy));

        % =========================================================
        % 3. Smoothing
        % =========================================================

        fprintf('\nMotion smoothing\n');

        if ~motion_field_has_value( ...
                data, ...
                'motion_energy_smooth_group', ...
                m)

            motion_energy_smooth = smooth_savgol( ...
                avg_motion_energy, ...
                3, ...
                11);

            data.motion.motion_energy_smooth_group{m} = ...
                motion_energy_smooth;

            has_new_data_for_acquisition = ...
                true;

            fprintf( ...
                ['  Status: smoothed motion signal ' ...
                 'calculated.\n']);

        else

            motion_energy_smooth = ...
                data.motion.motion_energy_smooth_group{m};

            fprintf( ...
                ['  Status: existing smoothed signal ' ...
                 'reused.\n']);
        end

        if isempty(motion_energy_smooth)

            fprintf( ...
                ['  Result: smoothed motion signal ' ...
                 'is empty.\n']);

            data = assign_empty_binary_motion_fields_if_missing( ...
                data, ...
                m);

            has_new_data_for_acquisition = ...
                true;

            save_motion_fields_if_needed( ...
                savePath, ...
                data, ...
                fields_motion, ...
                m, ...
                has_new_data_for_acquisition, ...
                tseries_name);

            continue;
        end

        % =========================================================
        % 4. Motion state detection
        % =========================================================

        need_bin = ...
            ~motion_field_has_value( ...
                data, ...
                'avg_active_motion_onsets_group', ...
                m) || ...
            ~motion_field_has_value( ...
                data, ...
                'avg_active_motion_offsets_group', ...
                m) || ...
            ~motion_field_has_value( ...
                data, ...
                'active_motion_onsets_group', ...
                m) || ...
            ~motion_field_has_value( ...
                data, ...
                'active_motion_offsets_group', ...
                m) || ...
            ~motion_field_has_value( ...
                data, ...
                'speed_active_group', ...
                m);

        thr_li = [];
        bin_sig = [];

        fprintf('\nMotion state detection\n');

        if need_bin

            [~, thr_li, ~] = ...
                compute_thresholds_for_bin_state_detection( ...
                    motion_energy_smooth, ...
                    false);

            [bin_sig, ~, ~, ~] = ...
                binarise_motion( ...
                    motion_energy_smooth, ...
                    thr_li, ...
                    sampling_rate_m, ...
                    avg_block, ...
                    3.0, ...
                    5);

            avg_onsets = ...
                get_onsets(bin_sig);

            avg_offsets = ...
                get_offsets(bin_sig);

            if ~isempty(bin_sig)

                if bin_sig(1) == 1

                    avg_onsets = [ ...
                        1; ...
                        avg_onsets(:) ...
                    ];
                end

                if bin_sig(end) == 1

                    avg_offsets = [ ...
                        avg_offsets(:); ...
                        numel(bin_sig) ...
                    ];
                end
            end

            N_frames = ...
                numel(motion_energy);

            onsets_frames = ...
                (avg_onsets - 1) * avg_block + 1;

            offsets_frames = ...
                avg_offsets * avg_block;

            onsets_frames = max( ...
                1, ...
                onsets_frames);

            offsets_frames = min( ...
                N_frames, ...
                offsets_frames);

            speed_active = repelem( ...
                bin_sig(:), ...
                avg_block);

            if isempty(speed_active)

                speed_active = ...
                    zeros(N_frames, 1);

            elseif numel(speed_active) < N_frames

                speed_active( ...
                    end + 1:N_frames) = ...
                    speed_active(end);

            else

                speed_active = ...
                    speed_active(1:N_frames);
            end

            data.motion.avg_active_motion_onsets_group{m} = ...
                avg_onsets;

            data.motion.avg_active_motion_offsets_group{m} = ...
                avg_offsets;

            data.motion.active_motion_onsets_group{m} = ...
                onsets_frames;

            data.motion.active_motion_offsets_group{m} = ...
                offsets_frames;

            data.motion.speed_active_group{m} = ...
                speed_active;

            has_new_data_for_acquisition = ...
                true;

            fprintf( ...
                '  Status         : motion states calculated.\n');

            fprintf( ...
                '  Threshold      : %.6f\n', ...
                thr_li);

            fprintf( ...
                '  Motion periods : %d\n', ...
                min( ...
                    numel(avg_onsets), ...
                    numel(avg_offsets)));

        else

            avg_onsets = ...
                data.motion.avg_active_motion_onsets_group{m};

            avg_offsets = ...
                data.motion.avg_active_motion_offsets_group{m};

            fprintf( ...
                '  Status         : existing motion states reused.\n');

            fprintf( ...
                '  Motion periods : %d\n', ...
                min( ...
                    numel(avg_onsets), ...
                    numel(avg_offsets)));
        end

        % The status becomes "done" only once the complete motion
        % pipeline has reached the state-detection stage successfully.
        if ~motion_status_exists(data, m) || ...
                ~strcmp( ...
                    string(data.motion.motion_energy_status{m}), ...
                    "done")

            data.motion.motion_energy_status{m} = ...
                'done';

            has_new_data_for_acquisition = ...
                true;
        end

        % =========================================================
        % Save motion
        % =========================================================

        save_motion_fields_if_needed( ...
            savePath, ...
            data, ...
            fields_motion, ...
            m, ...
            has_new_data_for_acquisition, ...
            tseries_name);

        % =========================================================
        % Figure
        % =========================================================

        save_motion_figure_if_missing( ...
            root_folder_m, ...
            data, ...
            m, ...
            current_animal_group, ...
            tseries_name, ...
            sampling_rate_m, ...
            avg_block);

        fprintf('\nAcquisition summary\n');

        fprintf( ...
            '  TSeries: %s\n', ...
            tseries_name);

        fprintf( ...
            '  Status : %s\n', ...
            get_motion_status_name( ...
                data, ...
                m));
    end

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('MOTION PROCESSING COMPLETED\n');
    fprintf('Animal      : %s\n', char(string(current_animal_group)));
    fprintf('Acquisitions: %d\n', numAcquisitions);
    fprintf('============================================================\n');

    motion = ...
        data.motion;
end


% =====================================================================
% Helpers
% =====================================================================

function presence = capture_motion_field_presence( ...
    data, ...
    fieldNames, ...
    numAcquisitions)

    presence = ...
        false( ...
            numel(fieldNames), ...
            numAcquisitions);

    if isempty(data) || ...
            ~isstruct(data) || ...
            ~isfield(data, 'motion') || ...
            ~isstruct(data.motion)

        return;
    end

    for f = 1:numel(fieldNames)

        fieldName = ...
            fieldNames{f};

        if ~isfield(data.motion, fieldName) || ...
                ~iscell(data.motion.(fieldName))

            continue;
        end

        nStored = ...
            min( ...
                numel(data.motion.(fieldName)), ...
                numAcquisitions);

        if nStored > 0

            presence(f, 1:nStored) = ...
                true;
        end
    end
end


function fields_to_load = get_motion_fields_to_load( ...
    data, ...
    fields_motion, ...
    initial_presence_for_acquisition, ...
    m)

    fields_to_load = ...
        {};

    status = ...
        "";

    if motion_status_exists(data, m) && ...
            ~isempty(data.motion.motion_energy_status{m})

        status = ...
            string( ...
                data.motion.motion_energy_status{m});
    end

    % No trustworthy status in memory: try to recover every missing saved
    % variable. Empty values are included because, without a status, we do
    % not yet know whether [] is a valid result or merely uninitialized.
    if strlength(status) == 0

        for f = 1:numel(fields_motion)

            fieldName = ...
                fields_motion{f};

            if ~motion_field_has_value( ...
                    data, ...
                    fieldName, ...
                    m) || ...
                    ~initial_presence_for_acquisition(f)

                fields_to_load{end + 1} = ... %#ok<AGROW>
                    fieldName;
            end
        end

        return;
    end

    switch status

        case "done"

            % These fields must contain actual data for a completed
            % acquisition.
            required_nonempty = { ...
                'motion_energy_group', ...
                'motion_energy_smooth_group', ...
                'speed_active_group' ...
            };

            for f = 1:numel(required_nonempty)

                fieldName = ...
                    required_nonempty{f};

                if ~motion_field_has_value( ...
                        data, ...
                        fieldName, ...
                        m)

                    fields_to_load{end + 1} = ... %#ok<AGROW>
                        fieldName;
                end
            end

            % Event arrays are allowed to be genuinely empty. They are
            % loaded only when that entry did not exist at all in the input
            % data before initialization.
            empty_can_be_valid = { ...
                'avg_active_motion_onsets_group', ...
                'avg_active_motion_offsets_group', ...
                'active_motion_onsets_group', ...
                'active_motion_offsets_group' ...
            };

            for f = 1:numel(empty_can_be_valid)

                fieldName = ...
                    empty_can_be_valid{f};

                field_idx = ...
                    find( ...
                        strcmp( ...
                            fields_motion, ...
                            fieldName), ...
                        1, ...
                        'first');

                if ~isempty(field_idx) && ...
                        ~initial_presence_for_acquisition(field_idx)

                    fields_to_load{end + 1} = ... %#ok<AGROW>
                        fieldName;
                end
            end

        case "skipped"

            % Intentional persistent decision: nothing else is required.

        case {"no_camera", "no_motion"}

            % Do not reload stale empty values. The camera folder / movie is
            % rechecked on every run so newly added files can be detected.

        otherwise

            % Partial / legacy state (including "processing"): recover all
            % fields that do not currently contain useful information, and
            % all fields that were absent from the original input data.
            for f = 1:numel(fields_motion)

                fieldName = ...
                    fields_motion{f};

                if strcmp( ...
                        fieldName, ...
                        'motion_energy_status')

                    continue;
                end

                if ~motion_field_has_value( ...
                        data, ...
                        fieldName, ...
                        m) || ...
                        ~initial_presence_for_acquisition(f)

                    fields_to_load{end + 1} = ... %#ok<AGROW>
                        fieldName;
                end
            end
    end

    fields_to_load = ...
        unique( ...
            fields_to_load, ...
            'stable');
end


function save_motion_figure_if_missing( ...
    root_folder_m, ...
    data, ...
    m, ...
    current_animal_group, ...
    tseries_name, ...
    sampling_rate_m, ...
    avg_block)

    png_filename = ...
        fullfile( ...
            root_folder_m, ...
            'binary_motion_energy.png');

    fprintf('\nMotion figure\n');

    if isfile(png_filename)

        fprintf( ...
            '  Status: existing figure retained.\n');

        fprintf( ...
            '  File  : %s\n', ...
            png_filename);

        return;
    end

    if ~motion_field_has_value( ...
            data, ...
            'motion_energy_smooth_group', ...
            m)

        fprintf( ...
            ['  Status: figure not generated; ' ...
             'smoothed signal is unavailable.\n']);

        return;
    end

    motion_energy_smooth = ...
        data.motion.motion_energy_smooth_group{m};

    if isempty(motion_energy_smooth)

        fprintf( ...
            ['  Status: figure not generated; ' ...
             'signal is empty.\n']);

        return;
    end

    avg_onsets = ...
        [];

    avg_offsets = ...
        [];

    if motion_field_slot_exists( ...
            data, ...
            'avg_active_motion_onsets_group', ...
            m)

        avg_onsets = ...
            data.motion.avg_active_motion_onsets_group{m};
    end

    if motion_field_slot_exists( ...
            data, ...
            'avg_active_motion_offsets_group', ...
            m)

        avg_offsets = ...
            data.motion.avg_active_motion_offsets_group{m};
    end

    try

        [~, thr_li, ~] = ...
            compute_thresholds_for_bin_state_detection( ...
                motion_energy_smooth, ...
                false);

        [bin_sig, ~, ~, ~] = ...
            binarise_motion( ...
                motion_energy_smooth, ...
                thr_li, ...
                sampling_rate_m, ...
                avg_block, ...
                3.0, ...
                5);

        fig = figure( ...
            'Visible', ...
            'off', ...
            'Color', ...
            'w');

        hold on;

        dt = ...
            avg_block / sampling_rate_m;

        time_axis = ...
            (0:numel(motion_energy_smooth) - 1) * dt;

        yl = [ ...
            min(motion_energy_smooth), ...
            max(motion_energy_smooth) ...
        ];

        if yl(1) == yl(2)

            yl = ...
                yl + [-1 1] * eps;
        end

        number_periods = ...
            min( ...
                numel(avg_onsets), ...
                numel(avg_offsets));

        for kk = 1:number_periods

            onset_idx = ...
                round(avg_onsets(kk));

            offset_idx = ...
                round(avg_offsets(kk));

            if onset_idx < 1 || ...
                    offset_idx < 1 || ...
                    onset_idx > numel(time_axis) || ...
                    offset_idx > numel(time_axis)

                continue;
            end

            patch( ...
                [ ...
                    time_axis(onset_idx), ...
                    time_axis(offset_idx), ...
                    time_axis(offset_idx), ...
                    time_axis(onset_idx) ...
                ], ...
                [ ...
                    yl(1), ...
                    yl(1), ...
                    yl(2), ...
                    yl(2) ...
                ], ...
                [1 0.8 0.8], ...
                'EdgeColor', ...
                'none', ...
                'FaceAlpha', ...
                0.4);
        end

        plot( ...
            time_axis, ...
            bin_sig(:)' * yl(2), ...
            'Color', ...
            [1 0.5 0], ...
            'LineWidth', ...
            2);

        yline( ...
            thr_li, ...
            '--r', ...
            'LineWidth', ...
            1);

        plot( ...
            time_axis, ...
            motion_energy_smooth, ...
            'Color', ...
            [0 0 1], ...
            'LineWidth', ...
            2);

        title( ...
            sprintf( ...
                'Binary motion energy - %s - %s', ...
                char(string(current_animal_group)), ...
                tseries_name), ...
            'Interpreter', ...
            'none');

        xlabel('Time (s)');
        ylabel('Motion energy');

        grid on;
        hold off;

        saveas( ...
            fig, ...
            png_filename);

        close(fig);

        fprintf( ...
            '  Status: motion figure created.\n');

        fprintf( ...
            '  File  : %s\n', ...
            png_filename);

    catch ME

        if exist('fig', 'var') && ...
                isgraphics(fig)

            close(fig);
        end

        warning( ...
            'load_or_process_movie:FigureFailed', ...
            ['%s | unable to create motion figure: %s'], ...
            tseries_name, ...
            ME.message);

        fprintf( ...
            '  Status: figure generation failed.\n');
    end
end


function tf = motion_already_complete( ...
    data, ...
    m)

    tf = false;

    if ~motion_status_exists(data, m) || ...
            isempty(data.motion.motion_energy_status{m})

        return;
    end

    status = string( ...
        data.motion.motion_energy_status{m});

    switch status

        case "done"

            tf = ...
                motion_field_has_value( ...
                    data, ...
                    'motion_energy_group', ...
                    m) && ...
                motion_field_has_value( ...
                    data, ...
                    'motion_energy_smooth_group', ...
                    m) && ...
                motion_field_has_value( ...
                    data, ...
                    'speed_active_group', ...
                    m);

        case "skipped"

            tf = true;

        case {"no_camera", "no_motion"}

            tf = false;

        otherwise

            tf = false;
    end
end


function strategy = ask_motion_energy_strategy_once()

    strategy = struct();

    strategy.open_in_fiji = false;
    strategy.compute_direct = false;
    strategy.skip = false;

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('MOTION ENERGY STRATEGY\n');
    fprintf('============================================================\n');

    choice = input( ...
        ['Open the camera movie in Fiji for cropping?\n' ...
         '  1 = Yes\n' ...
         '  2 = No\n' ...
         'Choice: '], ...
        's');

    if strcmpi(choice, '1')

        strategy.open_in_fiji = ...
            true;

        return;
    end

    subchoice = input( ...
        ['Calculate motion energy on the current movie?\n' ...
         '  1 = Calculate directly\n' ...
         '  2 = Skip motion energy\n' ...
         'Choice: '], ...
        's');

    if strcmpi(subchoice, '1')

        strategy.compute_direct = ...
            true;

    else

        strategy.skip = ...
            true;
    end
end


function motion_energy = compute_motion_energy_with_strategy( ...
    filepath, ...
    fijiPath, ...
    strategy)

    if strategy.open_in_fiji

        fprintf( ...
            'Opening camera movie in Fiji:\n');

        fprintf( ...
            '%s\n', ...
            filepath);

        system( ...
            sprintf( ...
                '"%s" "%s"', ...
                fijiPath, ...
                filepath));

        motion_energy = ...
            compute_motion_energy(filepath);

    elseif strategy.compute_direct

        fprintf( ...
            'Calculating motion energy directly from:\n');

        fprintf( ...
            '%s\n', ...
            filepath);

        motion_energy = ...
            compute_motion_energy(filepath);

    else

        fprintf( ...
            'Motion energy calculation skipped for:\n');

        fprintf( ...
            '%s\n', ...
            filepath);

        motion_energy = [];
    end
end


function data = init_motion_data_struct_if_needed( ...
    data, ...
    numAcquisitions, ...
    fieldNames)

    if nargin < 1 || isempty(data)

        data = struct();
    end

    if ~isfield(data, 'motion') || ...
            ~isstruct(data.motion) || ...
            isempty(data.motion)

        data.motion = struct();
    end

    for i = 1:numel(fieldNames)

        fieldName = ...
            fieldNames{i};

        if ~isfield(data.motion, fieldName) || ...
                ~iscell(data.motion.(fieldName))

            data.motion.(fieldName) = ...
                cell(numAcquisitions, 1);

        elseif numel(data.motion.(fieldName)) < ...
                numAcquisitions

            old_values = ...
                data.motion.(fieldName);

            new_values = ...
                cell(numAcquisitions, 1);

            new_values(1:numel(old_values)) = ...
                old_values(:);

            data.motion.(fieldName) = ...
                new_values;
        end
    end
end


function data = ensure_motion_entry_exists( ...
    data, ...
    fieldNames, ...
    numAcquisitions, ...
    m)

    data = init_motion_data_struct_if_needed( ...
        data, ...
        numAcquisitions, ...
        fieldNames);

    for i = 1:numel(fieldNames)

        fieldName = ...
            fieldNames{i};

        if numel(data.motion.(fieldName)) < m

            new_values = ...
                cell(numAcquisitions, 1);

            new_values( ...
                1:numel(data.motion.(fieldName))) = ...
                data.motion.(fieldName)(:);

            data.motion.(fieldName) = ...
                new_values;
        end
    end
end


function tf = motion_field_slot_exists( ...
    data, ...
    fieldName, ...
    m)

    tf = ...
        isfield(data, 'motion') && ...
        isfield(data.motion, fieldName) && ...
        iscell(data.motion.(fieldName)) && ...
        numel(data.motion.(fieldName)) >= m;
end


function tf = motion_field_has_value( ...
    data, ...
    fieldName, ...
    m)

    tf = ...
        motion_field_slot_exists( ...
            data, ...
            fieldName, ...
            m) && ...
        ~isempty(data.motion.(fieldName){m});
end


function tf = motion_status_exists( ...
    data, ...
    m)

    tf = motion_field_slot_exists( ...
        data, ...
        'motion_energy_status', ...
        m);
end


function data = merge_loaded_motion_into_data( ...
    data, ...
    loaded, ...
    fields_motion, ...
    m)

    for f = 1:numel(fields_motion)

        fieldName = ...
            fields_motion{f};

        if ~isfield(loaded, fieldName)

            continue;
        end

        if ~motion_field_slot_exists( ...
                data, ...
                fieldName, ...
                m) || ...
                isempty(data.motion.(fieldName){m})

            data.motion.(fieldName){m} = ...
                loaded.(fieldName);
        end
    end
end


function root_folder_m = extract_motion_root_folder( ...
    gcamp_output_folders, ...
    m)

    root_folder_m = '';

    if isempty(gcamp_output_folders) || ...
            m > numel(gcamp_output_folders) || ...
            isempty(gcamp_output_folders{m})

        return;
    end

    this_entry = ...
        gcamp_output_folders{m};

    if iscell(this_entry)

        if ~isempty(this_entry) && ...
                ~isempty(this_entry{1})

            root_folder_m = ...
                fileparts(this_entry{1});
        end

    elseif ischar(this_entry) || ...
            isstring(this_entry)

        root_folder_m = ...
            char(this_entry);
    end
end


function data = assign_empty_motion_fields_if_missing( ...
    data, ...
    m)

    motion_fields = { ...
        'motion_energy_group', ...
        'motion_energy_smooth_group', ...
        'avg_active_motion_onsets_group', ...
        'avg_active_motion_offsets_group', ...
        'active_motion_onsets_group', ...
        'active_motion_offsets_group', ...
        'speed_active_group' ...
    };

    for i = 1:numel(motion_fields)

        fieldName = ...
            motion_fields{i};

        if ~motion_field_slot_exists( ...
                data, ...
                fieldName, ...
                m) || ...
                isempty(data.motion.(fieldName){m})

            data.motion.(fieldName){m} = [];
        end
    end
end


function data = assign_empty_binary_motion_fields_if_missing( ...
    data, ...
    m)

    motion_fields = { ...
        'avg_active_motion_onsets_group', ...
        'avg_active_motion_offsets_group', ...
        'active_motion_onsets_group', ...
        'active_motion_offsets_group', ...
        'speed_active_group' ...
    };

    for i = 1:numel(motion_fields)

        fieldName = ...
            motion_fields{i};

        if ~motion_field_slot_exists( ...
                data, ...
                fieldName, ...
                m) || ...
                isempty(data.motion.(fieldName){m})

            data.motion.(fieldName){m} = [];
        end
    end
end


function save_motion_fields_if_needed( ...
    savePath, ...
    data, ...
    fields_motion, ...
    m, ...
    has_new_data_for_acquisition, ...
    tseries_name)

    if ~has_new_data_for_acquisition

        fprintf('\nMotion results\n');

        fprintf( ...
            '  TSeries: %s\n', ...
            tseries_name);

        fprintf( ...
            ['  Status : no new data; ' ...
             'results_motion.mat unchanged.\n']);

        return;
    end

    saveStruct = ...
        struct();

    for f = 1:numel(fields_motion)

        fieldName = ...
            fields_motion{f};

        if isfield(data, 'motion') && ...
                isfield(data.motion, fieldName) && ...
                numel(data.motion.(fieldName)) >= m

            saveStruct.(fieldName) = ...
                data.motion.(fieldName){m};
        end
    end

    try

        if exist(savePath, 'file') == 2

            save( ...
                savePath, ...
                '-struct', ...
                'saveStruct', ...
                '-append');

        else

            save( ...
                savePath, ...
                '-struct', ...
                'saveStruct');
        end

        fprintf('\nMotion results\n');

        fprintf( ...
            '  TSeries: %s\n', ...
            tseries_name);

        fprintf( ...
            '  Status : results_motion.mat updated.\n');

        fprintf( ...
            '  File   : %s\n', ...
            savePath);

    catch ME

        warning( ...
            'load_or_process_movie:SaveFailed', ...
            'TSeries %s | unable to save motion results: %s', ...
            tseries_name, ...
            ME.message);

        fprintf('\nMotion results\n');

        fprintf( ...
            '  TSeries: %s\n', ...
            tseries_name);

        fprintf( ...
            '  Status : save failed.\n');
    end
end


function y = smooth_savgol( ...
    x, ...
    order, ...
    framelen_target)

    x = ...
        x(:);

    N = ...
        numel(x);

    framelen = min( ...
        framelen_target, ...
        N);

    if mod(framelen, 2) == 0

        framelen = ...
            framelen - 1;
    end

    if framelen <= order

        framelen = ...
            order + 2;

        if mod(framelen, 2) == 0

            framelen = ...
                framelen + 1;
        end
    end

    if N < framelen || ...
            framelen < 3

        y = x;

        return;
    end

    y = sgolayfilt( ...
        x, ...
        order, ...
        framelen);
end


function onsets = get_onsets( ...
    bin_motion)

    bin_motion = ...
        bin_motion(:);

    onsets = find( ...
        bin_motion(2:end) == 1 & ...
        bin_motion(1:end - 1) == 0) + 1;
end


function offsets = get_offsets( ...
    bin_motion)

    bin_motion = ...
        bin_motion(:);

    offsets = find( ...
        bin_motion(2:end) == 0 & ...
        bin_motion(1:end - 1) == 1) + 1;
end


function tseries_path = get_tseries_path( ...
    current_gcamp_TSeries_path, ...
    m)

    tseries_path = '';

    if isempty(current_gcamp_TSeries_path) || ...
            m > numel(current_gcamp_TSeries_path) || ...
            isempty(current_gcamp_TSeries_path{m})

        return;
    end

    tseries_path = ...
        char(string( ...
            current_gcamp_TSeries_path{m}));
end


function tseries_name = find_tseries_name_in_path( ...
    path_value)

    tseries_name = ...
        'TSeries_unknown';

    if isempty(path_value)

        return;
    end

    path_value = ...
        char(string(path_value));

    while ~isempty(path_value)

        [parent_path, current_name] = ...
            fileparts(path_value);

        if startsWith( ...
                current_name, ...
                'TSeries-', ...
                'IgnoreCase', ...
                true)

            tseries_name = ...
                current_name;

            return;
        end

        if isempty(parent_path) || ...
                strcmp(parent_path, path_value)

            break;
        end

        path_value = ...
            parent_path;
    end
end


function sampling_rate_m = get_sampling_rate( ...
    sampling_rate_group, ...
    m)

    sampling_rate_m = ...
        NaN;

    if isempty(sampling_rate_group)

        return;
    end

    if iscell(sampling_rate_group)

        if m <= numel(sampling_rate_group) && ...
                ~isempty(sampling_rate_group{m})

            sampling_rate_m = ...
                double(sampling_rate_group{m});
        end

    elseif isnumeric(sampling_rate_group)

        if isscalar(sampling_rate_group)

            sampling_rate_m = ...
                double(sampling_rate_group);

        elseif m <= numel(sampling_rate_group)

            sampling_rate_m = ...
                double(sampling_rate_group(m));
        end
    end

    if isempty(sampling_rate_m) || ...
            ~isfinite(sampling_rate_m) || ...
            sampling_rate_m <= 0

        sampling_rate_m = ...
            1;

        warning( ...
            'load_or_process_movie:InvalidSamplingRate', ...
            ['Invalid sampling rate for acquisition %d. ' ...
             'Fallback value of 1 Hz used.'], ...
            m);
    end
end


function status_name = get_motion_status_name( ...
    data, ...
    m)

    status_name = ...
        'unknown';

    if ~motion_status_exists(data, m) || ...
            isempty(data.motion.motion_energy_status{m})

        return;
    end

    raw_status = string( ...
        data.motion.motion_energy_status{m});

    switch raw_status

        case "done"

            status_name = ...
                'completed';

        case "processing"

            status_name = ...
                'partial processing';

        case "skipped"

            status_name = ...
                'calculation skipped';

        case "no_camera"

            status_name = ...
                'no camera data';

        case "no_motion"

            status_name = ...
                'camera movie missing';

        otherwise

            status_name = ...
                char(raw_status);
    end
end