function [meanImg_channels, aligned_image, npy_file_path, meanImg] = ...
    load_or_process_cellpose_TSeries( ...
        filePath, ...
        date_group_path, ...
        gcamp_plane_path, ...
        electroporated_plane_path, ...
        green_plane_path, ...
        current_electroporated_TSeries_path, ...
        gcamp_output_folder_plane)

    % ==============================================================
    % Workflow
    %
    %   1) Charger GCaMP.
    %
    %   2) Charger le canal electroporated :
    %        - depuis Suite2p si electroporated_plane_path existe ;
    %        - sinon depuis current_electroporated_TSeries_path.
    %
    %   3) Charger Green si disponible.
    %
    %   4) Estimer la translation :
    %        Green -> GCaMP si Green existe,
    %        sinon Electroporated -> GCaMP.
    %
    %   5) Appliquer cette translation à Electroporated.
    %
    %   6) Segmenter l'image electroporated alignée avec Cellpose.
    %
    %   7) Reporter ces masques sur une référence GCaMP,
    %      puis permettre leur correction manuelle.
    %
    % meanImg_channels :
    %   {1} = GCaMP
    %   {2} = Electroporated
    %   {3} = Green
    % ==============================================================

    numChannelsLocal = 3;

    meanImg_channels = cell(numChannelsLocal, 1);

    aligned_image = [];
    aligned_image_path = '';
    npy_file_path = [];
    meanImg = [];

    % ==============================================================
    % Paths du plan courant
    % ==============================================================

    current_gcamp_folders_group_plane = ...
        gcamp_plane_path;

    current_electroporated_folders_group_plane = ...
        electroporated_plane_path;

    current_green_folders_group_plane = ...
        green_plane_path;

    % ==============================================================
    % Numéro du plan
    % ==============================================================

    plane_index_zero_based = ...
        infer_plane_index_from_paths( ...
            gcamp_plane_path, ...
            electroporated_plane_path, ...
            gcamp_output_folder_plane);

    p = plane_index_zero_based + 1;

    % ==============================================================
    % Output folder
    % ==============================================================

    if isempty(gcamp_output_folder_plane)

        if ~isempty(gcamp_plane_path)

            gcamp_output_folder_plane = ...
                gcamp_plane_path;

        else

            gcamp_output_folder_plane = ...
                date_group_path;
        end
    end

    if ~isempty(gcamp_output_folder_plane) && ...
            ~isfolder(gcamp_output_folder_plane)

        mkdir(gcamp_output_folder_plane);
    end

    % ==============================================================
    % Normaliser current_electroporated_TSeries_path
    % ==============================================================

    if iscell(current_electroporated_TSeries_path)

        if isempty(current_electroporated_TSeries_path)

            current_electroporated_TSeries_path = "";

        else

            current_electroporated_TSeries_path = ...
                current_electroporated_TSeries_path{1};
        end
    end

    if isempty(current_electroporated_TSeries_path)

        current_electroporated_TSeries_path = "";
    end

    % ==============================================================
    % Vérifier date_group_path
    % ==============================================================

    if isempty(date_group_path) || ...
            ~(ischar(date_group_path) || ...
              isstring(date_group_path))

        warning( ...
            'load_or_process_cellpose_TSeries:InvalidDateGroupPath', ...
            'Invalid date_group_path for plane %d.', ...
            p);

        [meanImg_channels, meanImg] = ...
            complete_meanImg_channels( ...
                meanImg_channels, ...
                filePath, ...
                current_gcamp_folders_group_plane, ...
                meanImg);

        return;
    end

    % ==============================================================
    % 1) Charger meanImg GCaMP
    % ==============================================================

    if ~isempty(current_gcamp_folders_group_plane)

        tmp = ...
            load_meanImg_from_path( ...
                current_gcamp_folders_group_plane);

        if ~isempty(tmp)

            meanImg_channels{1} = tmp;
            meanImg = tmp;
        end
    end

    % ==============================================================
    % 2) Charger meanImg Electroporated depuis Suite2p
    % ==============================================================

    if ~isempty(current_electroporated_folders_group_plane)

        tmp = ...
            load_meanImg_from_path( ...
                current_electroporated_folders_group_plane);

        if ~isempty(tmp)

            meanImg_channels{2} = tmp;
        end
    end

    % ==============================================================
    % 3) Charger meanImg Green
    % ==============================================================

    if ~isempty(current_green_folders_group_plane)

        tmp = ...
            load_meanImg_from_path( ...
                current_green_folders_group_plane);

        if ~isempty(tmp)

            meanImg_channels{3} = tmp;
        end
    end

    if isempty(meanImg) && ...
            ~isempty(meanImg_channels{1})

        meanImg = ...
            meanImg_channels{1};
    end

    % ==============================================================
    % CAS 1
    %
    % Pas de Suite2p electroporated :
    % utiliser directement current_electroporated_TSeries_path
    % ==============================================================

    if isempty(current_electroporated_folders_group_plane)

        if isempty(current_electroporated_TSeries_path) || ...
                ~(ischar(current_electroporated_TSeries_path) || ...
                  isstring(current_electroporated_TSeries_path))

            warning( ...
                'load_or_process_cellpose_TSeries:InvalidElectroporatedTSeries', ...
                ['No valid electroporated TSeries available ' ...
                 'for plane %d.'], ...
                p);

            [meanImg_channels, meanImg] = ...
                complete_meanImg_channels( ...
                    meanImg_channels, ...
                    filePath, ...
                    current_gcamp_folders_group_plane, ...
                    meanImg);

            return;
        end

        % ==========================================================
        % Chercher le dossier plane*
        % ==========================================================

        planeFolderName = ...
            sprintf( ...
                'plane%d', ...
                p - 1);

        current_electroporated_TSeries_path_plane = ...
            fullfile( ...
                current_electroporated_TSeries_path, ...
                planeFolderName);

        if ~isfolder( ...
                current_electroporated_TSeries_path_plane)

            current_electroporated_TSeries_path_plane = ...
                char(current_electroporated_TSeries_path);
        end

        % ==========================================================
        % Chercher segmentation electroporated existante
        % ==========================================================

        segPattern = ...
            sprintf( ...
                'aligned_%s_AVG*_seg.npy', ...
                planeFolderName);

        segFiles = ...
            dir( ...
                fullfile( ...
                    current_electroporated_TSeries_path_plane, ...
                    segPattern));

        % ==========================================================
        % CAS 1A : segmentation déjà présente
        % ==========================================================

        if ~isempty(segFiles)

            electroporated_seg_path = ...
                fullfile( ...
                    current_electroporated_TSeries_path_plane, ...
                    segFiles(1).name);

            electroporated_seg_path = ...
                validate_existing_file( ...
                    electroporated_seg_path);

            if ~isempty(electroporated_seg_path)

                [segDir, segName, ~] = ...
                    fileparts( ...
                        electroporated_seg_path);

                baseName = ...
                    regexprep( ...
                        segName, ...
                        '_seg$', ...
                        '');

                aligned_image_path = ...
                    fullfile( ...
                        segDir, ...
                        [baseName '.tif']);
            end

            % ------------------------------------------------------
            % Charger image moyenne brute electroporated
            % ------------------------------------------------------

            avgPattern = ...
                sprintf( ...
                    'plane%d_AVG*.tif', ...
                    p - 1);

            avgFiles = ...
                dir( ...
                    fullfile( ...
                        current_electroporated_TSeries_path_plane, ...
                        avgPattern));

            if ~isempty(avgFiles)

                avg_path = ...
                    fullfile( ...
                        current_electroporated_TSeries_path_plane, ...
                        avgFiles(1).name);

                electroporated_img = ...
                    safe_read_and_normalize( ...
                        avg_path);

                if ~isempty(electroporated_img)

                    meanImg_channels{2} = ...
                        electroporated_img;
                end
            end

            aligned_image = ...
                safe_read_and_normalize( ...
                    aligned_image_path);

            % ------------------------------------------------------
            % TIFF aligné absent / illisible
            % ------------------------------------------------------

            if isempty(aligned_image)

                fprintf( ...
                    ['Plane %d: existing electroporated masks found, ' ...
                     'but aligned TIFF must be reconstructed.\n'], ...
                    p);

                [aligned_image, ~, source_used] = ...
                    align_electroporated_locally_and_confirm( ...
                        meanImg_channels, ...
                        aligned_image_path);

                fprintf( ...
                    'Transform estimated from: %s\n', ...
                    source_used);
            end

        % ==========================================================
        % CAS 1B : pas de segmentation existante
        % ==========================================================

        else

            % ------------------------------------------------------
            % Chercher image alignée existante
            % ------------------------------------------------------

            alignedPattern = ...
                sprintf( ...
                    'aligned_plane%d_AVG*.tif', ...
                    p - 1);

            alignedFiles = ...
                dir( ...
                    fullfile( ...
                        current_electroporated_TSeries_path_plane, ...
                        alignedPattern));

            % ------------------------------------------------------
            % Charger image moyenne electroporated
            % ------------------------------------------------------

            avgPattern = ...
                sprintf( ...
                    'plane%d_AVG*.tif', ...
                    p - 1);

            avgFiles = ...
                dir( ...
                    fullfile( ...
                        current_electroporated_TSeries_path_plane, ...
                        avgPattern));

            if ~isempty(avgFiles)

                avg_path = ...
                    fullfile( ...
                        current_electroporated_TSeries_path_plane, ...
                        avgFiles(1).name);

                electroporated_img = ...
                    safe_read_and_normalize( ...
                        avg_path);

                if ~isempty(electroporated_img)

                    meanImg_channels{2} = ...
                        electroporated_img;
                end
            end

            % ------------------------------------------------------
            % Aligned existe déjà
            % ------------------------------------------------------

            if ~isempty(alignedFiles)

                aligned_image_path = ...
                    fullfile( ...
                        current_electroporated_TSeries_path_plane, ...
                        alignedFiles(1).name);

                aligned_image = ...
                    safe_read_and_normalize( ...
                        aligned_image_path);

            % ------------------------------------------------------
            % Aucun aligned -> recalage
            % ------------------------------------------------------

            else

                if isempty(meanImg_channels{2})

                    fprintf( ...
                        ['Plane %d: no electroporated mean image ' ...
                         'found in:\n%s\n'], ...
                        p, ...
                        current_electroporated_TSeries_path_plane);

                    aligned_image = [];
                    npy_file_path = [];

                else

                    if isempty(meanImg_channels{1})

                        warning( ...
                            ['Plane %d: GCaMP mean image missing. ' ...
                             'Electroporated alignment impossible.'], ...
                            p);

                        aligned_image = [];
                        npy_file_path = [];

                    else

                        aligned_image_path = ...
                            fullfile( ...
                                current_electroporated_TSeries_path_plane, ...
                                sprintf( ...
                                    'aligned_plane%d_AVG.tif', ...
                                    p - 1));

                        [ ...
                            aligned_image, ...
                            ~, ...
                            source_used ...
                        ] = ...
                            align_electroporated_locally_and_confirm( ...
                                meanImg_channels, ...
                                aligned_image_path);

                        fprintf( ...
                            'Transform estimated from: %s\n', ...
                            source_used);
                    end
                end
            end
        end

    % ==============================================================
    % CAS 2
    %
    % Suite2p electroporated existe
    % ==============================================================

    else

        try

            % ======================================================
            % Charger image electroporated depuis Suite2p
            % ======================================================

            if isempty(meanImg_channels{2})

                tmp = ...
                    load_meanImg_from_path( ...
                        current_electroporated_folders_group_plane);

                if ~isempty(tmp)

                    meanImg_channels{2} = tmp;
                end
            end

            % ======================================================
            % Chercher une segmentation existante
            % ======================================================

            cellpose_files = ...
                dir( ...
                    fullfile( ...
                        current_electroporated_folders_group_plane, ...
                        '*_seg.npy'));

            if ~isempty(cellpose_files)

                electroporated_seg_path = ...
                    select_or_default( ...
                        cellpose_files, ...
                        '', ...
                        '*.npy');

                electroporated_seg_path = ...
                    validate_existing_file( ...
                        electroporated_seg_path);

                if ~isempty(electroporated_seg_path)

                    [segDir, segName, ~] = ...
                        fileparts( ...
                            electroporated_seg_path);

                    baseName = ...
                        regexprep( ...
                            segName, ...
                            '_seg$', ...
                            '');

                    aligned_image_path = ...
                        fullfile( ...
                            segDir, ...
                            [baseName '.tif']);
                end
            end

            % ======================================================
            % Si aucun chemin fourni par le seg :
            % chemin aligned standard
            % ======================================================

            if isempty(aligned_image_path)

                aligned_image_path = ...
                    fullfile( ...
                        current_electroporated_folders_group_plane, ...
                        sprintf( ...
                            'aligned_plane%d_AVG.tif', ...
                            p - 1));
            end

            % ======================================================
            % Aligned existe
            % ======================================================

            if isfile(aligned_image_path)

                aligned_image = ...
                    safe_read_and_normalize( ...
                        aligned_image_path);

            % ======================================================
            % Sinon créer aligned
            % ======================================================

            else

                [ ...
                    aligned_image, ...
                    ~, ...
                    source_used ...
                ] = ...
                    align_electroporated_locally_and_confirm( ...
                        meanImg_channels, ...
                        aligned_image_path);

                fprintf( ...
                    'Transform estimated from: %s\n', ...
                    source_used);
            end

        catch ME

            warning( ...
                'load_or_process_cellpose_TSeries:ExistingElectroporatedBranchFailed', ...
                ['Plane %d: existing-electroporated branch ' ...
                 'failed: %s'], ...
                p, ...
                ME.message);

            aligned_image = [];
            npy_file_path = [];
        end
    end

    % ==============================================================
    % FLUX CELLPOSE FINAL
    % ==============================================================

    if ~isempty(aligned_image_path) && ...
            isfile(aligned_image_path)

        if isempty(aligned_image)

            aligned_image = ...
                safe_read_and_normalize( ...
                    aligned_image_path);
        end

        if ~isempty(aligned_image)

            [ ...
                aligned_folder, ...
                aligned_name, ...
                ~ ...
            ] = ...
                fileparts( ...
                    aligned_image_path);

            electroporated_seg_path = ...
                fullfile( ...
                    aligned_folder, ...
                    [aligned_name '_seg.npy']);

            % ======================================================
            % STEP 1 :
            % Dessiner les masques sur electroporated si absents
            % ======================================================

            if ~isfile(electroporated_seg_path)

                fprintf('\n');
                fprintf('============================================\n');
                fprintf('CELLPOSE STEP 1\n');
                fprintf('DRAW MASKS ON ALIGNED ELECTROPORATED IMAGE\n');
                fprintf('Save with Ctrl+S, then close Cellpose.\n');
                fprintf('============================================\n');

                electroporated_seg_path = ...
                    launch_cellpose_from_matlab( ...
                        aligned_image_path, ...
                        true, ...
                        'Draw masks on aligned electroporated image');

                electroporated_seg_path = ...
                    validate_existing_file( ...
                        electroporated_seg_path);

            else
            
                fprintf( ...
                    'Existing aligned-electroporated masks found:\n%s\n', ...
                    electroporated_seg_path);
            end

            % ======================================================
            % STEP 2 :
            % Reporter / corriger les masques sur GCaMP
            % ======================================================

            if ~isempty(electroporated_seg_path)

                npy_file_path = ...
                    create_and_refine_masks_on_gcamp( ...
                        aligned_image_path, ...
                        meanImg_channels{1}, ...
                        gcamp_output_folder_plane, ...
                        electroporated_seg_path);

                npy_file_path = ...
                    validate_existing_file( ...
                        npy_file_path);

            else

                warning( ...
                    ['No aligned-electroporated *_seg.npy was saved. ' ...
                     'GCaMP correction cannot start.']);

                npy_file_path = [];
            end

        else

            warning( ...
                ['Aligned electroporated TIFF exists but ' ...
                 'could not be read.']);

            npy_file_path = [];
        end

    elseif ~isempty(aligned_image)

        warning( ...
            ['An aligned electroporated image exists in memory, ' ...
             'but its TIFF path is unavailable.']);

        npy_file_path = [];
    end

    % ==============================================================
    % Post-processing
    % ==============================================================

    [meanImg_channels, meanImg] = ...
        complete_meanImg_channels( ...
            meanImg_channels, ...
            filePath, ...
            current_gcamp_folders_group_plane, ...
            meanImg);
end


% ========================================================================
% SAFE READ
% ========================================================================

function img = safe_read_and_normalize(img_path)

    img = [];

    if isempty(img_path)
        return;
    end

    if ~(ischar(img_path) || ...
            isstring(img_path))
        return;
    end

    if ~isfile(img_path)
        return;
    end

    try

        img = ...
            normalize_image( ...
                imread(img_path));

    catch ME

        warning( ...
            'load_or_process_cellpose_TSeries:ReadImageFailed', ...
            'Failed reading image "%s": %s', ...
            char(img_path), ...
            ME.message);

        img = [];
    end
end


% ========================================================================
% VALIDATE FILE
% ========================================================================

function filepath = validate_existing_file(filepath)

    if isempty(filepath)

        filepath = [];
        return;
    end

    if ~(ischar(filepath) || ...
            isstring(filepath))

        filepath = [];
        return;
    end

    if ~isfile(filepath)

        filepath = [];
    end
end


% ========================================================================
% ALIGN ELECTROPORATED
% ========================================================================

function [aligned_image, T, source_used] = ...
        align_electroporated_locally_and_confirm( ...
            meanImg_channels, ...
            aligned_image_path)

    % meanImg_channels:
    %   {1} GCaMP
    %   {2} Electroporated
    %   {3} Green

    ref_img = [];

    if numel(meanImg_channels) >= 1

        ref_img = ...
            meanImg_channels{1};
    end

    electroporated_img = [];

    if numel(meanImg_channels) >= 2

        electroporated_img = ...
            meanImg_channels{2};
    end

    green_img = [];

    if numel(meanImg_channels) >= 3

        green_img = ...
            meanImg_channels{3};
    end

    aligned_image = [];
    T = [];
    source_used = '';

    % ==============================================================
    % Vérifications
    % ==============================================================

    if isempty(ref_img)

        warning( ...
            ['align_electroporated_locally_and_confirm: ' ...
             'GCaMP absent.']);

        return;
    end

    if isempty(electroporated_img)

        warning( ...
            ['align_electroporated_locally_and_confirm: ' ...
             'Electroporated image absent.']);

        return;
    end

    ref_img = ...
        double(ref_img);

    % ==============================================================
    % Image utilisée pour ESTIMER la translation
    %
    % Green prioritaire lorsqu'il existe.
    % Sinon Electroporated.
    % ==============================================================

    if ~isempty(green_img)

        moving_for_estimation = ...
            double(green_img);

        source_used = ...
            'Green';

    else

        moving_for_estimation = ...
            double(electroporated_img);

        source_used = ...
            'Electroporated';
    end

    % ==============================================================
    % Image réellement transformée
    % ==============================================================

    moving_img = ...
        double(electroporated_img);

    % ==============================================================
    % Registration
    % ==============================================================

    moving_reg = ...
        mat2gray( ...
            moving_for_estimation);

    ref_reg = ...
        mat2gray( ...
            ref_img);

    % Si tailles différentes, mettre la moving d'estimation
    % aux dimensions de la référence uniquement pour calculer T.

    if ~isequal(size(moving_reg), size(ref_reg))

        moving_reg = ...
            imresize( ...
                moving_reg, ...
                size(ref_reg));
    end

    try

        reg_obj = ...
            imregcorr( ...
                moving_reg, ...
                ref_reg, ...
                'translation');

        T = ...
            reg_obj.T;

        fprintf( ...
            '%s -> GCaMP | imregcorr translation\n', ...
            source_used);

        fprintf( ...
            'dx = %.3f px\n', ...
            T(3,1));

        fprintf( ...
            'dy = %.3f px\n', ...
            T(3,2));

    catch ME

        warning( ...
            'imregcorr failed: %s', ...
            ME.message);

        T = ...
            eye(3);
    end

    % ==============================================================
    % Appliquer T à ELECTROPORATED
    % ==============================================================

    aligned_image = ...
        apply_transform_with_phasecorr( ...
            moving_img, ...
            T, ...
            ref_img);

    if isempty(aligned_image)

        warning( ...
            ['align_electroporated_locally_and_confirm: ' ...
             'empty transformation.']);

        return;
    end

    % ==============================================================
    % Dimensions
    % ==============================================================

    if ~isequal( ...
            size(aligned_image,1), ...
            size(ref_img,1)) || ...
            ~isequal( ...
                size(aligned_image,2), ...
                size(ref_img,2))

        aligned_image = ...
            imresize( ...
                aligned_image, ...
                [ ...
                    size(ref_img,1), ...
                    size(ref_img,2) ...
                ]);
    end

    % ==============================================================
    % Métriques
    % ==============================================================

    before_cmp = ...
        mat2gray( ...
            moving_img);

    ref_cmp = ...
        mat2gray( ...
            ref_img);

    after_cmp = ...
        mat2gray( ...
            aligned_image);

    if ~isequal( ...
            size(before_cmp), ...
            size(ref_cmp))

        before_cmp = ...
            imresize( ...
                before_cmp, ...
                size(ref_cmp));
    end

    if ~isequal( ...
            size(after_cmp), ...
            size(ref_cmp))

        after_cmp = ...
            imresize( ...
                after_cmp, ...
                size(ref_cmp));
    end

    before_err = ...
        mean( ...
            abs( ...
                ref_cmp(:) - ...
                before_cmp(:)), ...
            'omitnan');

    after_err = ...
        mean( ...
            abs( ...
                ref_cmp(:) - ...
                after_cmp(:)), ...
            'omitnan');

    fprintf( ...
        'Error vs ref before = %.6f\n', ...
        before_err);

    fprintf( ...
        'Error vs ref after  = %.6f\n', ...
        after_err);

    fprintf( ...
        'Improvement         = %.6f\n', ...
        before_err - after_err);

    % ==============================================================
    % Validation manuelle
    % ==============================================================

    [ ...
        was_saved, ...
        aligned_image, ...
        T ...
    ] = ...
        preview_alignment_with_save_cancel( ...
            moving_img, ...
            aligned_image, ...
            ref_img, ...
            T);

    if ~was_saved

        fprintf( ...
            'Alignment cancelled by user.\n');

        aligned_image = [];
        T = [];
        source_used = '';

        return;
    end

    % ==============================================================
    % Sauvegarde
    % ==============================================================

    if ~isempty(aligned_image) && ...
            ~isempty(aligned_image_path)

        try

            imwrite( ...
                aligned_image, ...
                aligned_image_path, ...
                'tif');

            fprintf( ...
                'Aligned electroporated image saved:\n%s\n', ...
                aligned_image_path);

        catch ME

            warning( ...
                ['Unable to save aligned electroporated ' ...
                 'image "%s": %s'], ...
                aligned_image_path, ...
                ME.message);
        end
    end
end


% ========================================================================
% PREVIEW ALIGNMENT
% ========================================================================

function [was_saved, aligned_img, T] = ...
        preview_alignment_with_save_cancel( ...
            original_img, ...
            aligned_img, ...
            ref_img, ...
            T)

    was_saved = false;

    if isempty(original_img) || ...
            isempty(aligned_img) || ...
            isempty(ref_img) || ...
            isempty(T)

        return;
    end

    original_img = double(original_img);
    aligned_img  = double(aligned_img);
    ref_img      = double(ref_img);

    dx = T(3,1);
    dy = T(3,2);

    original_disp = ...
        enhance_for_overlay( ...
            original_img);

    aligned_disp = ...
        enhance_for_overlay( ...
            aligned_img);

    ref_disp = ...
        enhance_for_overlay( ...
            ref_img);

    hFig = figure( ...
        'Name', ...
        'Preview electroporated alignment', ...
        'NumberTitle', ...
        'off', ...
        'MenuBar', ...
        'none', ...
        'ToolBar', ...
        'none', ...
        'Color', ...
        'w', ...
        'Position', ...
        [80 80 1500 720], ...
        'CloseRequestFcn', ...
        @onCancel);

    S = struct();

    S.saved = false;
    S.state = 1;

    S.original_img = original_img;
    S.aligned_img = aligned_img;
    S.ref_img = ref_img;
    S.T = T;

    S.original_disp = original_disp;
    S.aligned_disp = aligned_disp;
    S.ref_disp = ref_disp;

    S.ax1 = axes( ...
        'Parent', hFig, ...
        'Position', [0.05 0.12 0.34 0.78]);

    S.ax2 = axes( ...
        'Parent', hFig, ...
        'Position', [0.44 0.12 0.34 0.78]);

    S.infoTxt = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'text', ...
        'String', ...
        sprintf( ...
            ['Automatic alignment\n\n' ...
             'dx = %.2f px\n' ...
             'dy = %.2f px\n\n' ...
             'Left: original / aligned\n' ...
             'Right: GCaMP / aligned'], ...
            dx, ...
            dy), ...
        'FontSize', 11, ...
        'BackgroundColor', 'w', ...
        'HorizontalAlignment', 'left', ...
        'Units', 'normalized', ...
        'Position', [0.81 0.62 0.16 0.22]);

    S.btnManual = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Manual alignment', ...
        'FontSize', 12, ...
        'Units', 'normalized', ...
        'Position', [0.82 0.54 0.14 0.08], ...
        'Callback', @onManual);

    S.btnSave = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Save', ...
        'FontSize', 12, ...
        'Units', 'normalized', ...
        'Position', [0.82 0.42 0.14 0.08], ...
        'Callback', @onSave);

    S.btnCancel = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Cancel', ...
        'FontSize', 12, ...
        'Units', 'normalized', ...
        'Position', [0.82 0.30 0.14 0.08], ...
        'Callback', @onCancel);

    guidata(hFig, S);

    refresh_alternating_display(hFig);

    animTimer = timer( ...
        'ExecutionMode', ...
        'fixedSpacing', ...
        'Period', ...
        0.6, ...
        'TimerFcn', ...
        @(~,~) toggle_display(hFig));

    S = guidata(hFig);

    S.animTimer = ...
        animTimer;

    guidata(hFig, S);

    start(animTimer);

    uiwait(hFig);

    if isvalid_handle(hFig)

        S = guidata(hFig);

        if isfield(S, 'animTimer') && ...
                ~isempty(S.animTimer) && ...
                isvalid(S.animTimer)

            stop(S.animTimer);
            delete(S.animTimer);
        end

        was_saved = S.saved;
        aligned_img = S.aligned_img;
        T = S.T;

        delete(hFig);
    end


    function toggle_display(fig)

        if ~isvalid_handle(fig)
            return;
        end

        S = guidata(fig);

        S.state = ...
            3 - S.state;

        guidata(fig, S);

        refresh_alternating_display(fig);
    end


    function refresh_alternating_display(fig)

        if ~isvalid_handle(fig)
            return;
        end

        S = guidata(fig);

        cla(S.ax1);
        cla(S.ax2);

        if S.state == 1

            imagesc( ...
                S.ax1, ...
                S.original_disp);

            axis( ...
                S.ax1, ...
                'image');

            title( ...
                S.ax1, ...
                'Electroporated original');

            imagesc( ...
                S.ax2, ...
                S.ref_disp);

            axis( ...
                S.ax2, ...
                'image');

            title( ...
                S.ax2, ...
                'GCaMP reference');

        else

            imagesc( ...
                S.ax1, ...
                S.aligned_disp);

            axis( ...
                S.ax1, ...
                'image');

            title( ...
                S.ax1, ...
                'Electroporated aligned');

            imagesc( ...
                S.ax2, ...
                S.aligned_disp);

            axis( ...
                S.ax2, ...
                'image');

            title( ...
                S.ax2, ...
                'Electroporated aligned');
        end

        colormap(S.ax1, parula);
        colormap(S.ax2, parula);

        drawnow limitrate;
    end


    function onManual(src, ~)

        fig = ...
            ancestor( ...
                src, ...
                'figure');

        if isempty(fig) || ...
                ~isvalid_handle(fig)

            return;
        end

        S = ...
            guidata(fig);

        if isfield(S, 'animTimer') && ...
                ~isempty(S.animTimer) && ...
                isvalid(S.animTimer)

            stop(S.animTimer);
        end

        [ ...
            T_manual, ...
            was_manual_saved ...
        ] = ...
            manual_translation_gui( ...
                S.original_img, ...
                S.ref_img, ...
                S.T);

        if was_manual_saved && ...
                ~isempty(T_manual)

            S.T = ...
                T_manual;

            S.aligned_img = ...
                apply_transform_with_phasecorr( ...
                    S.original_img, ...
                    S.T, ...
                    S.ref_img);

            if ~isempty(S.aligned_img)

                S.aligned_disp = ...
                    enhance_for_overlay( ...
                        S.aligned_img);

                dx = S.T(3,1);
                dy = S.T(3,2);

                set( ...
                    S.infoTxt, ...
                    'String', ...
                    sprintf( ...
                        ['Manual alignment\n\n' ...
                         'dx = %.2f px\n' ...
                         'dy = %.2f px'], ...
                        dx, ...
                        dy));
            end

            guidata(fig, S);

            refresh_alternating_display(fig);
        end

        S = guidata(fig);

        if isfield(S, 'animTimer') && ...
                ~isempty(S.animTimer) && ...
                isvalid(S.animTimer)

            start(S.animTimer);
        end
    end


    function onSave(src, ~)

        fig = ...
            ancestor(src, 'figure');

        if isempty(fig) || ...
                ~isvalid_handle(fig)

            return;
        end

        S = guidata(fig);

        S.saved = true;

        guidata(fig, S);

        if isfield(S, 'animTimer') && ...
                ~isempty(S.animTimer) && ...
                isvalid(S.animTimer)

            stop(S.animTimer);
        end

        uiresume(fig);
    end


    function onCancel(src, ~)

        fig = src;

        if ~ishandle(fig) || ...
                ~strcmp(get(fig, 'Type'), 'figure')

            fig = ...
                ancestor(src, 'figure');
        end

        if isempty(fig) || ...
                ~isvalid_handle(fig)

            return;
        end

        S = guidata(fig);

        S.saved = false;

        guidata(fig, S);

        if isfield(S, 'animTimer') && ...
                ~isempty(S.animTimer) && ...
                isvalid(S.animTimer)

            stop(S.animTimer);
        end

        uiresume(fig);
    end
end


% ========================================================================
% MANUAL TRANSLATION
% ========================================================================

function [T_out, was_saved] = ...
        manual_translation_gui( ...
            moving_img, ...
            ref_img, ...
            T_init)

    was_saved = false;
    T_out = [];

    if isempty(moving_img) || ...
            isempty(ref_img)

        return;
    end

    moving_img = double(moving_img);
    ref_img = double(ref_img);

    if nargin < 3 || ...
            isempty(T_init)

        T_init = eye(3);
    end

    tx = T_init(3,1);
    ty = T_init(3,2);

    ref_size = size(ref_img);
    ref_size = ref_size(1:2);

    S = struct();

    S.moving = moving_img;
    S.ref = ref_img;
    S.tx = tx;
    S.ty = ty;
    S.dragging = false;
    S.startPoint = [0 0];
    S.startTxTy = [tx ty];
    S.saved = false;

    hFig = figure( ...
        'Name', 'Manual alignment', ...
        'NumberTitle', 'off', ...
        'Color', 'w', ...
        'MenuBar', 'none', ...
        'ToolBar', 'figure', ...
        'Position', [200 120 1200 780], ...
        'WindowButtonDownFcn', @onMouseDown, ...
        'WindowButtonUpFcn', @onMouseUp, ...
        'WindowButtonMotionFcn', @onMouseMove, ...
        'CloseRequestFcn', @onCancel);

    S.ax = axes( ...
        'Parent', hFig, ...
        'Position', [0.05 0.08 0.70 0.86]);

    axis(S.ax, 'image');
    hold(S.ax, 'on');

    uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Save', ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [0.81 0.80 0.15 0.08], ...
        'Callback', @onSave);

    uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Cancel', ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [0.81 0.68 0.15 0.08], ...
        'Callback', @onCancel);

    S.sliderAlpha = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'slider', ...
        'Min', 0.05, ...
        'Max', 1, ...
        'Value', 0.5, ...
        'Units', 'normalized', ...
        'Position', [0.81 0.54 0.15 0.04], ...
        'Callback', ...
        @(~,~) refreshOverlay(hFig));

    S.txt = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'text', ...
        'String', '', ...
        'FontSize', 11, ...
        'BackgroundColor', 'w', ...
        'HorizontalAlignment', 'left', ...
        'Units', 'normalized', ...
        'Position', [0.80 0.35 0.18 0.12]);

    guidata(hFig, S);

    refreshOverlay(hFig);

    uiwait(hFig);

    if isvalid_handle(hFig)

        S = guidata(hFig);

        if S.saved

            T_out = eye(3);

            T_out(3,1) = S.tx;
            T_out(3,2) = S.ty;

            was_saved = true;
        end

        delete(hFig);
    end


    function onMouseDown(src, ~)

        S = guidata(src);

        cp = ...
            get( ...
                S.ax, ...
                'CurrentPoint');

        S.dragging = true;
        S.startPoint = cp(1,1:2);
        S.startTxTy = [S.tx S.ty];

        guidata(src, S);
    end


    function onMouseMove(src, ~)

        S = guidata(src);

        if ~S.dragging
            return;
        end

        cp = ...
            get( ...
                S.ax, ...
                'CurrentPoint');

        delta = ...
            cp(1,1:2) - ...
            S.startPoint;

        S.tx = ...
            S.startTxTy(1) + ...
            delta(1);

        S.ty = ...
            S.startTxTy(2) + ...
            delta(2);

        guidata(src, S);

        refreshOverlay(src);
    end


    function onMouseUp(src, ~)

        S = guidata(src);

        S.dragging = false;

        guidata(src, S);
    end


    function onSave(src, ~)

        fig = ancestor(src, 'figure');

        S = guidata(fig);

        S.saved = true;

        guidata(fig, S);

        uiresume(fig);
    end


    function onCancel(src, ~)

        fig = ancestor(src, 'figure');

        if isempty(fig)
            fig = src;
        end

        if ~isvalid_handle(fig)
            return;
        end

        S = guidata(fig);

        S.saved = false;

        guidata(fig, S);

        uiresume(fig);
    end


    function refreshOverlay(fig)

        if ~isvalid_handle(fig)
            return;
        end

        S = guidata(fig);

        Ttmp = eye(3);

        Ttmp(3,1) = S.tx;
        Ttmp(3,2) = S.ty;

        moved = ...
            imwarp( ...
                double(S.moving), ...
                affine2d(Ttmp), ...
                'OutputView', ...
                imref2d(ref_size));

        ref_disp = ...
            enhance_for_overlay( ...
                S.ref);

        moved_disp = ...
            enhance_for_overlay( ...
                moved);

        alpha_val = ...
            get( ...
                S.sliderAlpha, ...
                'Value');

        cla(S.ax);

        hold(S.ax, 'on');

        imagesc( ...
            S.ax, ...
            ref_disp);

        hMov = ...
            imagesc( ...
                S.ax, ...
                moved_disp);

        set( ...
            hMov, ...
            'AlphaData', ...
            alpha_val);

        axis(S.ax, 'image');

        title( ...
            S.ax, ...
            'Drag electroporated image');

        set( ...
            S.txt, ...
            'String', ...
            sprintf( ...
                'dx = %.2f px\ndy = %.2f px\nalpha = %.2f', ...
                S.tx, ...
                S.ty, ...
                alpha_val));

        drawnow limitrate;
    end
end


% ========================================================================
% APPLY TRANSFORM
% ========================================================================

function aligned_img = ...
        apply_transform_with_phasecorr( ...
            channel_img, ...
            T, ...
            ref_img)

    aligned_img = [];

    if isempty(channel_img) || ...
            isempty(T) || ...
            isempty(ref_img)

        return;
    end

    ref_size = ...
        size(ref_img);

    ref_size = ...
        ref_size(1:2);

    try

        aligned_raw = ...
            imwarp( ...
                double(channel_img), ...
                affine2d(T), ...
                'OutputView', ...
                imref2d(ref_size), ...
                'Interp', ...
                'linear');

    catch ME

        warning( ...
            'apply_transform_with_phasecorr: %s', ...
            ME.message);

        return;
    end

    aligned_img = ...
        normalize_image( ...
            aligned_raw);
end


% ========================================================================
% LOAD MEAN IMAGE
% ========================================================================

function meanImg = load_meanImg_from_path(path_in)

    meanImg = [];

    if isempty(path_in)
        return;
    end

    if isfolder(path_in)

        ops_npy = ...
            fullfile( ...
                path_in, ...
                'ops.npy');

        if isfile(ops_npy)

            try

                mod = ...
                    py.importlib.import_module( ...
                        'python_function');

                ops = ...
                    mod.read_npy_file( ...
                        ops_npy);

                meanImg = ...
                    double( ...
                        ops{'meanImg'});

                return;

            catch

                warning( ...
                    'Error reading ops.npy in %s', ...
                    path_in);
            end
        end

        ops_mat = ...
            fullfile( ...
                path_in, ...
                'ops.mat');

        if isfile(ops_mat)

            S = load(ops_mat);

            if isfield(S, 'ops') && ...
                    isfield(S.ops, 'meanImg')

                meanImg = ...
                    S.ops.meanImg;

                return;
            end
        end
    end
end


% ========================================================================
% SELECT FILE
% ========================================================================

function path_out = ...
        select_or_default( ...
            files, ...
            canal_str, ...
            pattern)

    if isempty(files)

        path_out = '';
        return;
    end

    if numel(files) > 1

        [selected_file, selected_path] = ...
            uigetfile( ...
                {['*' canal_str pattern]}, ...
                'Select file', ...
                fullfile( ...
                    files(1).folder, ...
                    files(1).name));

        if isequal(selected_file, 0)

            path_out = '';
            return;
        end

        path_out = ...
            fullfile( ...
                selected_path, ...
                selected_file);

    else

        path_out = ...
            fullfile( ...
                files(1).folder, ...
                files(1).name);
    end
end


% ========================================================================
% COMPLETE MEAN IMAGES
% ========================================================================

function [meanImg_channels, meanImg] = ...
        complete_meanImg_channels( ...
            meanImg_channels, ...
            filePath, ...
            gcamp_plane_path, ...
            meanImg)

    try

        if ~isempty(filePath) && ...
                exist(filePath, 'file') == 2

            saved_data = ...
                load(filePath);

            if isfield( ...
                    saved_data, ...
                    'meanImg_channels')

                source = ...
                    saved_data.meanImg_channels;

                n = ...
                    min( ...
                        numel(meanImg_channels), ...
                        numel(source));

                for j = 1:n

                    if isempty(meanImg_channels{j})

                        meanImg_channels{j} = ...
                            source{j};
                    end
                end
            end
        end

        if isempty(meanImg)

            if ~isempty(meanImg_channels{1})

                meanImg = ...
                    meanImg_channels{1};

            elseif ~isempty(gcamp_plane_path)

                meanImg = ...
                    load_meanImg_from_path( ...
                        gcamp_plane_path);

                if ~isempty(meanImg)

                    meanImg_channels{1} = ...
                        meanImg;
                end
            end
        end

    catch ME

        warning( ...
            'complete_meanImg_channels: %s', ...
            ME.message);
    end
end


% ========================================================================
% NORMALIZE IMAGE
% ========================================================================

function norm_img = normalize_image(img)

    if isfloat(img)

        norm_img = ...
            mat2gray(img);

    elseif isinteger(img)

        denom = ...
            double( ...
                max(img(:)));

        if denom == 0

            norm_img = ...
                uint8(img);

        else

            norm_img = ...
                uint8( ...
                    double(img) ./ denom .* 255);
        end

    else

        norm_img = ...
            mat2gray( ...
                double(img));
    end
end


% ========================================================================
% ENHANCE DISPLAY
% ========================================================================

function out = enhance_for_overlay(img)

    img = double(img);

    if isempty(img) || ...
            all(~isfinite(img(:)))

        out = zeros(size(img));
        return;
    end

    vals = ...
        img(isfinite(img));

    p_low = ...
        prctile(vals, 2);

    p_high = ...
        prctile(vals, 98);

    if p_high <= p_low

        out = ...
            mat2gray(img);

        return;
    end

    out = ...
        (img - p_low) ./ ...
        (p_high - p_low);

    out = ...
        max( ...
            min(out, 1), ...
            0);

    out = ...
        out .^ 0.7;
end


% ========================================================================
% HANDLE
% ========================================================================

function tf = isvalid_handle(h)

    tf = ...
        ~isempty(h) && ...
        isgraphics(h);
end


% ========================================================================
% CREATE / REFINE GCAMP MASKS
% ========================================================================

function final_npy_path = ...
        create_and_refine_masks_on_gcamp( ...
            aligned_electroporated_path, ...
            gcamp_image, ...
            output_folder, ...
            electroporated_seg_path)

    final_npy_path = [];

    if isempty(aligned_electroporated_path) || ...
            ~isfile(aligned_electroporated_path)

        warning( ...
            'create_and_refine_masks_on_gcamp:MissingAlignedElectroporated', ...
            'Aligned electroporated image not found.');

        return;
    end

    if isempty(output_folder)

        output_folder = ...
            fileparts( ...
                aligned_electroporated_path);
    end

    if ~isfolder(output_folder)

        mkdir(output_folder);
    end

    % ==============================================================
    % GCaMP reference path
    % ==============================================================

    [~, electroporated_name, ~] = ...
        fileparts( ...
            aligned_electroporated_path);

    electroporated_name = ...
        regexprep( ...
            electroporated_name, ...
            '^aligned_', ...
            '');

    gcamp_reference_path = ...
        fullfile( ...
            output_folder, ...
            [ ...
                'gcamp_reference_' ...
                electroporated_name ...
                '.tif' ...
            ]);
    
    fprintf( ...
    ['Existing aligned-electroporated masks found.\n' ...
     'Continuing with GCaMP reference:\n%s\n'], ...
    gcamp_reference_path);
    
    [gcamp_folder, gcamp_name, ~] = ...
        fileparts( ...
            gcamp_reference_path);

    existing_gcamp_seg_path = ...
        fullfile( ...
            gcamp_folder, ...
            [gcamp_name '_seg.npy']);

    % ==============================================================
    % Déjà corrigé
    % ==============================================================

    if isfile(existing_gcamp_seg_path)

        final_npy_path = ...
            validate_existing_file( ...
                existing_gcamp_seg_path);

        fprintf( ...
            'Existing corrected GCaMP masks found:\n%s\n', ...
            final_npy_path);

        return;
    end

    % ==============================================================
    % Vérifier source masks
    % ==============================================================

    if isempty(electroporated_seg_path) || ...
            ~isfile(electroporated_seg_path)

        warning( ...
            'create_and_refine_masks_on_gcamp:MissingElectroporatedMasks', ...
            'Aligned-electroporated Cellpose masks not found.');

        return;
    end

    if isempty(gcamp_image)

        warning( ...
            'create_and_refine_masks_on_gcamp:MissingGCampImage', ...
            'GCaMP reference mean image is empty.');

        return;
    end

    % ==============================================================
    % Créer référence GCaMP
    % ==============================================================

    if ~isfile(gcamp_reference_path)

        gcamp_reference_image = ...
            prepare_image_for_cellpose_display( ...
                gcamp_image);

        try

            imwrite( ...
                gcamp_reference_image, ...
                gcamp_reference_path, ...
                'tif');

        catch ME

            warning( ...
                'create_and_refine_masks_on_gcamp:SaveReferenceFailed', ...
                '%s', ...
                ME.message);

            return;
        end
    end

    % ==============================================================
    % Copier masques electroporated vers GCaMP
    % ==============================================================

    success = ...
        create_gcamp_seg_from_electroporated_seg( ...
            electroporated_seg_path, ...
            gcamp_reference_path, ...
            existing_gcamp_seg_path);

    if ~success || ...
            ~isfile(existing_gcamp_seg_path)

        warning( ...
            'create_and_refine_masks_on_gcamp:InitialSegFailed', ...
            'Unable to create initial GCaMP segmentation.');

        return;
    end

    % ==============================================================
    % Correction GCaMP
    % ==============================================================

    fprintf('\n');
    fprintf('GCaMP mask correction\n');
    fprintf('Save with Ctrl+S, then close Cellpose.\n');

    final_npy_path = ...
        launch_cellpose_from_matlab( ...
            gcamp_reference_path, ...
            false, ...
            'Correct masks on GCaMP');

    final_npy_path = ...
        validate_existing_file( ...
            final_npy_path);
end


% ========================================================================
% COPY ELECTROPORATED MASKS TO GCAMP
% ========================================================================

function success = ...
        create_gcamp_seg_from_electroporated_seg( ...
            source_seg_path, ...
            gcamp_image_path, ...
            destination_seg_path)

    success = false;

    if ~isfile(source_seg_path) || ...
            ~isfile(gcamp_image_path)

        return;
    end

    pyExec = ...
        'C:\Users\goldstein\AppData\Local\anaconda3\envs\cellpose\python.exe';

    script_path = ...
        [tempname '.py'];

    fid = ...
        fopen( ...
            script_path, ...
            'w');

    if fid == -1

        warning( ...
            'Unable to create temporary Python script.');

        return;
    end

    cleanupObj = ...
        onCleanup( ...
            @() delete_temp_script( ...
                script_path)); %#ok<NASGU>

    lines = {
        'import sys'
        'import numpy as np'
        'import tifffile'
        ''
        'source_seg = sys.argv[1]'
        'gcamp_path = sys.argv[2]'
        'destination_seg = sys.argv[3]'
        ''
        'data = np.load(source_seg, allow_pickle=True).item()'
        'gcamp_img = tifffile.imread(gcamp_path)'
        'masks = np.asarray(data["masks"])'
        ''
        'if masks.shape[-2:] != gcamp_img.shape[-2:]:'
        '    raise ValueError("Mask and GCaMP dimensions differ")'
        ''
        'data["img"] = gcamp_img'
        'data["filename"] = gcamp_path'
        'np.save(destination_seg, data, allow_pickle=True)'
    };

    for k = 1:numel(lines)

        fprintf( ...
            fid, ...
            '%s\n', ...
            lines{k});
    end

    fclose(fid);

    command = ...
        sprintf( ...
            '"%s" "%s" "%s" "%s" "%s"', ...
            pyExec, ...
            script_path, ...
            source_seg_path, ...
            gcamp_image_path, ...
            destination_seg_path);

    [status, command_output] = ...
        system(command);

    if status ~= 0

        warning( ...
            'Error creating GCaMP segmentation:\n%s', ...
            command_output);

        return;
    end

    success = ...
        isfile(destination_seg_path);
end


% ========================================================================
% TEMP SCRIPT
% ========================================================================

function delete_temp_script(script_path)

    if isfile(script_path)

        try
            delete(script_path);
        catch
        end
    end
end


% ========================================================================
% PREPARE GCAMP IMAGE
% ========================================================================

function image_out = ...
        prepare_image_for_cellpose_display( ...
            image_in)

    image_in = ...
        double(image_in);

    image_in(~isfinite(image_in)) = 0;

    values = ...
        image_in(isfinite(image_in));

    if isempty(values)

        image_out = ...
            uint16( ...
                zeros(size(image_in)));

        return;
    end

    low_value = ...
        prctile(values, 1);

    high_value = ...
        prctile(values, 99.8);

    if high_value <= low_value

        normalized = ...
            mat2gray(image_in);

    else

        normalized = ...
            (image_in - low_value) ./ ...
            (high_value - low_value);

        normalized = ...
            max( ...
                0, ...
                min(1, normalized));
    end

    normalized = ...
        normalized .^ 0.7;

    image_out = ...
        uint16( ...
            normalized .* 65535);
end


% ========================================================================
% PLANE INDEX
% ========================================================================

function plane_index = ...
        infer_plane_index_from_paths(varargin)

    plane_index = 0;

    for i = 1:nargin

        path_in = ...
            varargin{i};

        if isempty(path_in) || ...
                ~(ischar(path_in) || ...
                  isstring(path_in))

            continue;
        end

        token = ...
            regexp( ...
                char(path_in), ...
                'plane(\d+)', ...
                'tokens', ...
                'once');

        if ~isempty(token)

            plane_index = ...
                str2double( ...
                    token{1});

            if isfinite(plane_index)
                return;
            end
        end
    end
end


% ========================================================================
% CELLPOSE
% ========================================================================

function npy_file_path = ...
        launch_cellpose_from_matlab( ...
            image_path, ...
            ask_confirmation, ...
            dialog_title)

    npy_file_path = [];

    if nargin < 2 || ...
            isempty(ask_confirmation)

        ask_confirmation = true;
    end

    if nargin < 3 || ...
            isempty(dialog_title)

        dialog_title = ...
            'Launch Cellpose';
    end

    if isempty(image_path) || ...
            ~isfile(image_path)

        warning( ...
            'Cellpose image not found: %s', ...
            char(string(image_path)));

        return;
    end

    pyExec = ...
        'C:\Users\goldstein\AppData\Local\anaconda3\envs\cellpose\python.exe';

    cellposePath = ...
        'C:\Users\goldstein\AppData\Local\anaconda3\envs\cellpose\Scripts\cellpose.exe';

    if ~isfile(cellposePath)

        warning( ...
            'cellpose.exe not found: %s', ...
            cellposePath);

        return;
    end

    try

        currentPyEnv = pyenv;

        if ~strcmp( ...
                currentPyEnv.Version, ...
                pyExec)

            pyenv( ...
                'Version', ...
                pyExec);
        end

    catch ME

        warning( ...
            'Unable to configure pyenv: %s', ...
            ME.message);
    end

    [folderPath, fileName, ~] = ...
        fileparts( ...
            image_path);

    candidate_npy = ...
        fullfile( ...
            folderPath, ...
            [fileName '_seg.npy']);

    file_existed_before = ...
        isfile(candidate_npy);

    previous_datenum = [];
    previous_bytes = [];

    if file_existed_before

        info_before = ...
            dir(candidate_npy);

        previous_datenum = ...
            info_before.datenum;

        previous_bytes = ...
            info_before.bytes;
    end

    if ask_confirmation

        answer = ...
            questdlg( ...
                sprintf( ...
                    ['Do you want to launch Cellpose?\n\n' ...
                     '%s\n\n' ...
                     'Save with Ctrl+S, then close Cellpose.'], ...
                    image_path), ...
                dialog_title, ...
                'Yes', ...
                'No', ...
                'Yes');

        if ~strcmp(answer, 'Yes')
            return;
        end
    end

    [status, command_output] = ...
        system( ...
            ['"' cellposePath '"']);

    if status ~= 0

        warning( ...
            'Cellpose closed with status %d:\n%s', ...
            status, ...
            command_output);

        return;
    end

    if ~isfile(candidate_npy)

        warning( ...
            'No Cellpose segmentation saved for:\n%s', ...
            image_path);

        return;
    end

    info_after = ...
        dir(candidate_npy);

    if file_existed_before

        file_was_modified = ...
            info_after.datenum > previous_datenum || ...
            info_after.bytes ~= previous_bytes;

        if ~file_was_modified

            warning( ...
                ['Existing segmentation was not modified. ' ...
                 'Use Ctrl+S before closing Cellpose.']);

            return;
        end
    end

    npy_file_path = ...
        candidate_npy;
end