function [meanImg_channels, aligned_image, npy_file_path, meanImg] = ...
    load_or_process_cellpose_TSeries( ...
        filePath, ...
        date_group_path, ...
        gcamp_plane_path, ...
        electroporated_plane_path, ...
        green_plane_path, ...
        current_electroporated_TSeries_path, ...
        gcamp_output_folder_plane)

    % ==============================================================
    % Workflow
    %
    %   1) Charger GCaMP.
    %
    %   2) Charger Electroporated avec l'ordre de priorité suivant :
    %
    %        1. Suite2p Electroporated
    %        2. TSeries Electroporated / plane*
    %        3. Single images / ChX
    %
    %      Pour Single images, le numéro du canal Electroporated
    %      est demandé à l'utilisateur.
    %
    %   3) Charger Green si disponible.
    %
    %   4) Estimer la translation :
    %        Green -> GCaMP si Green existe,
    %        sinon Electroporated -> GCaMP.
    %
    %   5) Appliquer cette translation à Electroporated.
    %
    %   6) Segmenter l'image Electroporated alignée avec Cellpose.
    %
    %   7) Reporter ces masques sur une référence GCaMP,
    %      puis permettre leur correction manuelle.
    %
    % meanImg_channels :
    %   {1} = GCaMP
    %   {2} = Electroporated
    %   {3} = Green
    % ==============================================================

    numChannelsLocal = 3;

    meanImg_channels = ...
        cell( ...
            numChannelsLocal, ...
            1);

    aligned_image = [];
    aligned_image_path = '';
    npy_file_path = [];
    meanImg = [];
    electroporated_seg_path = [];

    % ==============================================================
    % Paths du plan courant
    % ==============================================================

    current_gcamp_suite2p_plane_path = ...
        gcamp_plane_path;

    current_electroporated_suite2p_plane_path = ...
        electroporated_plane_path;

    current_green_suite2p_plane_path = ...
        green_plane_path;

    % ==============================================================
    % Numéro du plan
    % ==============================================================

    plane_index_zero_based = ...
        infer_plane_index_from_paths( ...
            gcamp_plane_path, ...
            electroporated_plane_path, ...
            gcamp_output_folder_plane);

    p = ...
        plane_index_zero_based + 1;

    % ==============================================================
    % Output folder
    % ==============================================================

    if isempty(gcamp_output_folder_plane)

        if ~isempty(gcamp_plane_path)

            gcamp_output_folder_plane = ...
                gcamp_plane_path;

        else

            gcamp_output_folder_plane = ...
                date_group_path;
        end
    end

    if ~isempty(gcamp_output_folder_plane) && ...
            ~isfolder(gcamp_output_folder_plane)

        mkdir( ...
            gcamp_output_folder_plane);
    end

    % ==============================================================
    % Normaliser current_electroporated_TSeries_path
    % ==============================================================

    if iscell(current_electroporated_TSeries_path)

        if isempty(current_electroporated_TSeries_path)

            current_electroporated_TSeries_path = "";

        else

            current_electroporated_TSeries_path = ...
                current_electroporated_TSeries_path{1};
        end
    end

    if isempty(current_electroporated_TSeries_path)

        current_electroporated_TSeries_path = "";
    end

    % ==============================================================
    % Vérifier date_group_path
    % ==============================================================

    if isempty(date_group_path) || ...
            ~( ...
                ischar(date_group_path) || ...
                isstring(date_group_path))

        warning( ...
            'load_or_process_cellpose_TSeries:InvalidDateGroupPath', ...
            'Invalid date_group_path for plane %d.', ...
            p);

        [ ...
            meanImg_channels, ...
            meanImg ...
        ] = ...
            complete_meanImg_channels( ...
                meanImg_channels, ...
                filePath, ...
                current_gcamp_suite2p_plane_path, ...
                meanImg);

        return;
    end

    % ==============================================================
    % 1) Charger meanImg GCaMP
    % ==============================================================

    if ~isempty(current_gcamp_suite2p_plane_path)

        tmp = ...
            load_meanImg_from_path( ...
                current_gcamp_suite2p_plane_path);

        if ~isempty(tmp)

            meanImg_channels{1} = ...
                tmp;

            meanImg = ...
                tmp;
        end
    end

    % ==============================================================
    % 2) Charger meanImg Electroporated depuis Suite2p si disponible
    % ==============================================================

    if ~isempty(current_electroporated_suite2p_plane_path)

        tmp = ...
            load_meanImg_from_path( ...
                current_electroporated_suite2p_plane_path);

        if ~isempty(tmp)

            meanImg_channels{2} = ...
                tmp;
        end
    end

    % ==============================================================
    % 3) Charger meanImg Green
    % ==============================================================

    if ~isempty(current_green_suite2p_plane_path)

        tmp = ...
            load_meanImg_from_path( ...
                current_green_suite2p_plane_path);

        if ~isempty(tmp)

            meanImg_channels{3} = ...
                tmp;
        end
    end

    if isempty(meanImg) && ...
            ~isempty(meanImg_channels{1})

        meanImg = ...
            meanImg_channels{1};
    end

    % ==============================================================
    % Déterminer si TSeries Electroporated est disponible
    % ==============================================================

    has_electroporated_TSeries = ...
        ~isempty(current_electroporated_TSeries_path) && ...
        ( ...
            ischar(current_electroporated_TSeries_path) || ...
            isstring(current_electroporated_TSeries_path)) && ...
        isfolder( ...
            char(current_electroporated_TSeries_path));

    % ==============================================================
    % Single images
    % ==============================================================

    single_images_path = ...
        fullfile( ...
            date_group_path, ...
            'Single images');

    has_single_images = ...
        isfolder(single_images_path);

    % ==============================================================
    %
    % PRIORITÉ 1
    %
    % SUITE2P ELECTROPORATED
    %
    % ==============================================================

    if ~isempty(current_electroporated_suite2p_plane_path)

        fprintf('\n');
        fprintf('============================================\n');
        fprintf('ELECTROPORATED SOURCE: SUITE2P\n');
        fprintf('Plane: %d\n', p);
        fprintf('============================================\n');

        try

            % ======================================================
            % Charger Electroporated depuis Suite2p
            % ======================================================

            if isempty(meanImg_channels{2})

                tmp = ...
                    load_meanImg_from_path( ...
                        current_electroporated_suite2p_plane_path);

                if ~isempty(tmp)

                    meanImg_channels{2} = ...
                        tmp;
                end
            end

            % ======================================================
            % Chercher segmentation existante
            % ======================================================

            cellpose_files = ...
                dir( ...
                    fullfile( ...
                        current_electroporated_suite2p_plane_path, ...
                        '*_seg.npy'));

            if ~isempty(cellpose_files)

                electroporated_seg_path = ...
                    select_or_default( ...
                        cellpose_files, ...
                        '', ...
                        '*.npy');

                electroporated_seg_path = ...
                    validate_existing_file( ...
                        electroporated_seg_path);

                if ~isempty(electroporated_seg_path)

                    [ ...
                        segDir, ...
                        segName, ...
                        ~ ...
                    ] = ...
                        fileparts( ...
                            electroporated_seg_path);

                    baseName = ...
                        regexprep( ...
                            segName, ...
                            '_seg$', ...
                            '');

                    aligned_image_path = ...
                        fullfile( ...
                            segDir, ...
                            [baseName '.tif']);
                end
            end

            % ======================================================
            % Chemin aligned standard
            % ======================================================

            if isempty(aligned_image_path)

                aligned_image_path = ...
                    fullfile( ...
                        current_electroporated_suite2p_plane_path, ...
                        sprintf( ...
                            'aligned_plane%d_AVG.tif', ...
                            p - 1));
            end

            % ======================================================
            % Charger aligned s'il existe
            % ======================================================

            if isfile(aligned_image_path)

                aligned_image = ...
                    safe_read_and_normalize( ...
                        aligned_image_path);

            % ======================================================
            % Sinon recalage
            % ======================================================

            else

                [ ...
                    aligned_image, ...
                    ~, ...
                    source_used ...
                ] = ...
                    align_electroporated_locally_and_confirm( ...
                        meanImg_channels, ...
                        aligned_image_path);

                fprintf( ...
                    'Transform estimated from: %s\n', ...
                    source_used);
            end

        catch ME

            warning( ...
                'load_or_process_cellpose_TSeries:Suite2pElectroporatedFailed', ...
                ['Plane %d: Suite2p Electroporated branch ' ...
                 'failed: %s'], ...
                p, ...
                ME.message);

            aligned_image = [];
            npy_file_path = [];
        end

    % ==============================================================
    %
    % PRIORITÉ 2
    %
    % TSERIES ELECTROPORATED / plane*
    %
    % ==============================================================

    elseif has_electroporated_TSeries

        fprintf('\n');
        fprintf('============================================\n');
        fprintf('ELECTROPORATED SOURCE: TSERIES\n');
        fprintf('Plane: %d\n', p);
        fprintf('============================================\n');

        % ==========================================================
        % Chercher dossier plane*
        % ==========================================================

        planeFolderName = ...
            sprintf( ...
                'plane%d', ...
                p - 1);

        current_electroporated_TSeries_plane_path = ...
            fullfile( ...
                current_electroporated_TSeries_path, ...
                planeFolderName);

        if ~isfolder(current_electroporated_TSeries_plane_path)

            current_electroporated_TSeries_plane_path = ...
                char( ...
                    current_electroporated_TSeries_path);
        end

        % ==========================================================
        % Chercher segmentation Electroporated existante
        % ==========================================================

        segPattern = ...
            sprintf( ...
                'aligned_%s_AVG*_seg.npy', ...
                planeFolderName);

        segFiles = ...
            dir( ...
                fullfile( ...
                    current_electroporated_TSeries_plane_path, ...
                    segPattern));

        % ==========================================================
        % Segmentation déjà présente
        % ==========================================================

        if ~isempty(segFiles)

            electroporated_seg_path = ...
                fullfile( ...
                    current_electroporated_TSeries_plane_path, ...
                    segFiles(1).name);

            electroporated_seg_path = ...
                validate_existing_file( ...
                    electroporated_seg_path);

            if ~isempty(electroporated_seg_path)

                [ ...
                    segDir, ...
                    segName, ...
                    ~ ...
                ] = ...
                    fileparts( ...
                        electroporated_seg_path);

                baseName = ...
                    regexprep( ...
                        segName, ...
                        '_seg$', ...
                        '');

                aligned_image_path = ...
                    fullfile( ...
                        segDir, ...
                        [baseName '.tif']);
            end

            % ======================================================
            % Charger image brute Electroporated
            % ======================================================

            avgPattern = ...
                sprintf( ...
                    'plane%d_AVG*.tif', ...
                    p - 1);

            avgFiles = ...
                dir( ...
                    fullfile( ...
                        current_electroporated_TSeries_plane_path, ...
                        avgPattern));

            if ~isempty(avgFiles)

                avg_path = ...
                    fullfile( ...
                        current_electroporated_TSeries_plane_path, ...
                        avgFiles(1).name);

                electroporated_img = ...
                    safe_read_and_normalize( ...
                        avg_path);

                if ~isempty(electroporated_img)

                    meanImg_channels{2} = ...
                        electroporated_img;
                end
            end

            aligned_image = ...
                safe_read_and_normalize( ...
                    aligned_image_path);

            % ======================================================
            % Seg existe mais TIFF aligned absent
            % ======================================================

            if isempty(aligned_image)

                fprintf( ...
                    ['Plane %d: existing Electroporated masks found, ' ...
                     'but aligned TIFF must be reconstructed.\n'], ...
                    p);

                [ ...
                    aligned_image, ...
                    ~, ...
                    source_used ...
                ] = ...
                    align_electroporated_locally_and_confirm( ...
                        meanImg_channels, ...
                        aligned_image_path);

                fprintf( ...
                    'Transform estimated from: %s\n', ...
                    source_used);
            end

        % ==========================================================
        % Pas de segmentation
        % ==========================================================

        else

            alignedPattern = ...
                sprintf( ...
                    'aligned_plane%d_AVG*.tif', ...
                    p - 1);

            alignedFiles = ...
                dir( ...
                    fullfile( ...
                        current_electroporated_TSeries_plane_path, ...
                        alignedPattern));

            avgPattern = ...
                sprintf( ...
                    'plane%d_AVG*.tif', ...
                    p - 1);

            avgFiles = ...
                dir( ...
                    fullfile( ...
                        current_electroporated_TSeries_plane_path, ...
                        avgPattern));

            % ======================================================
            % Charger image moyenne Electroporated
            % ======================================================

            if ~isempty(avgFiles)

                avg_path = ...
                    fullfile( ...
                        current_electroporated_TSeries_plane_path, ...
                        avgFiles(1).name);

                electroporated_img = ...
                    safe_read_and_normalize( ...
                        avg_path);

                if ~isempty(electroporated_img)

                    meanImg_channels{2} = ...
                        electroporated_img;
                end
            end

            % ======================================================
            % Aligned existe
            % ======================================================

            if ~isempty(alignedFiles)

                aligned_image_path = ...
                    fullfile( ...
                        current_electroporated_TSeries_plane_path, ...
                        alignedFiles(1).name);

                aligned_image = ...
                    safe_read_and_normalize( ...
                        aligned_image_path);

            % ======================================================
            % Aucun aligned -> recalage
            % ======================================================

            else

                if isempty(meanImg_channels{2})

                    fprintf( ...
                        ['Plane %d: no Electroporated mean image ' ...
                         'found in:\n%s\n'], ...
                        p, ...
                        current_electroporated_TSeries_plane_path);

                    aligned_image = [];
                    npy_file_path = [];

                elseif isempty(meanImg_channels{1})

                    warning( ...
                        ['Plane %d: GCaMP mean image missing. ' ...
                         'Electroporated alignment impossible.'], ...
                        p);

                    aligned_image = [];
                    npy_file_path = [];

                else

                    aligned_image_path = ...
                        fullfile( ...
                            current_electroporated_TSeries_plane_path, ...
                            sprintf( ...
                                'aligned_plane%d_AVG.tif', ...
                                p - 1));

                    [ ...
                        aligned_image, ...
                        ~, ...
                        source_used ...
                    ] = ...
                        align_electroporated_locally_and_confirm( ...
                            meanImg_channels, ...
                            aligned_image_path);

                    fprintf( ...
                        'Transform estimated from: %s\n', ...
                        source_used);
                end
            end
        end

    % ==============================================================
    %
    % PRIORITÉ 3
    %
    % SINGLE IMAGES
    %
    % ==============================================================

    elseif has_single_images

        fprintf('\n');
        fprintf('============================================\n');
        fprintf('ELECTROPORATED SOURCE: SINGLE IMAGES\n');
        fprintf('Folder:\n%s\n', single_images_path);
        fprintf('============================================\n');

        % ==========================================================
        % Demander numéro du canal Electroporated
        % ==========================================================

        answer = ...
            inputdlg( ...
                'Enter electroporated channel number:', ...
                'Electroporated channel', ...
                [1 45], ...
                {'3'});

        if isempty(answer)

            fprintf( ...
                'Electroporated channel selection cancelled.\n');

            [ ...
                meanImg_channels, ...
                meanImg ...
            ] = ...
                complete_meanImg_channels( ...
                    meanImg_channels, ...
                    filePath, ...
                    current_gcamp_suite2p_plane_path, ...
                    meanImg);

            return;
        end

        electroporated_channel_number = ...
            str2double( ...
                strtrim(answer{1}));

        if ~isfinite(electroporated_channel_number) || ...
                electroporated_channel_number < 1 || ...
                electroporated_channel_number ~= ...
                    round(electroporated_channel_number)

            warning( ...
                'load_or_process_cellpose_TSeries:InvalidElectroporatedChannel', ...
                'Invalid Electroporated channel number.');

            [ ...
                meanImg_channels, ...
                meanImg ...
            ] = ...
                complete_meanImg_channels( ...
                    meanImg_channels, ...
                    filePath, ...
                    current_gcamp_suite2p_plane_path, ...
                    meanImg);

            return;
        end

        electroporated_channel_number = ...
            round( ...
                electroporated_channel_number);

        electroporated_channel_str = ...
            sprintf( ...
                'Ch%d', ...
                electroporated_channel_number);

        fprintf( ...
            'Electroporated channel: %s\n', ...
            electroporated_channel_str);

        % ==========================================================
        % Chercher les segmentations du canal demandé
        % ==========================================================

        cellpose_files = ...
            dir( ...
                fullfile( ...
                    single_images_path, ...
                    '*_seg.npy'));

        cellpose_files_electroporated = ...
            cellpose_files( ...
                contains( ...
                    {cellpose_files.name}, ...
                    electroporated_channel_str, ...
                    'IgnoreCase', ...
                    true));

        % ==========================================================
        % SINGLE IMAGES :
        % segmentation déjà présente
        % ==========================================================

        if ~isempty(cellpose_files_electroporated)

            electroporated_seg_path = ...
                select_or_default( ...
                    cellpose_files_electroporated, ...
                    electroporated_channel_str, ...
                    '*.npy');

            electroporated_seg_path = ...
                validate_existing_file( ...
                    electroporated_seg_path);

            if ~isempty(electroporated_seg_path)

                [ ...
                    seg_folder, ...
                    seg_name, ...
                    ~ ...
                ] = ...
                    fileparts( ...
                        electroporated_seg_path);

                base_name = ...
                    regexprep( ...
                        seg_name, ...
                        '_seg$', ...
                        '');

                aligned_image_path = ...
                    fullfile( ...
                        seg_folder, ...
                        [base_name '.tif']);

                % ==================================================
                % Retrouver image brute
                %
                % aligned_xxx_ChX.tif
                % ->
                % xxx_ChX.tif
                % ==================================================

                raw_name = ...
                    regexprep( ...
                        base_name, ...
                        '^aligned_', ...
                        '');

                electroporated_tif_path = ...
                    fullfile( ...
                        seg_folder, ...
                        [raw_name '.tif']);

                electroporated_img = ...
                    safe_read_and_normalize( ...
                        electroporated_tif_path);

                if ~isempty(electroporated_img)

                    meanImg_channels{2} = ...
                        electroporated_img;
                end

                aligned_image = ...
                    safe_read_and_normalize( ...
                        aligned_image_path);

                % ==================================================
                % Segmentation présente mais TIFF aligned absent
                % ==================================================

                if isempty(aligned_image)

                    fprintf( ...
                        ['Existing Electroporated masks found, ' ...
                         'but aligned TIFF must be reconstructed.\n']);

                    if isempty(meanImg_channels{2})

                        warning( ...
                            ['Raw Electroporated Single image ' ...
                             'could not be found.']);

                    elseif isempty(meanImg_channels{1})

                        warning( ...
                            ['GCaMP mean image missing. ' ...
                             'Electroporated alignment impossible.']);

                    else

                        [ ...
                            aligned_image, ...
                            ~, ...
                            source_used ...
                        ] = ...
                            align_electroporated_locally_and_confirm( ...
                                meanImg_channels, ...
                                aligned_image_path);

                        fprintf( ...
                            'Transform estimated from: %s\n', ...
                            source_used);
                    end
                end
            end

        % ==========================================================
        % SINGLE IMAGES :
        % aucune segmentation
        % ==========================================================

        else

            tif_files = ...
                dir( ...
                    fullfile( ...
                        single_images_path, ...
                        '*.tif'));

            tif_files_electroporated = ...
                tif_files( ...
                    contains( ...
                        {tif_files.name}, ...
                        electroporated_channel_str, ...
                        'IgnoreCase', ...
                        true));

            % ======================================================
            % Séparer TIFF aligned et TIFF brut
            % ======================================================

            if ~isempty(tif_files_electroporated)

                is_aligned = ...
                    startsWith( ...
                        {tif_files_electroporated.name}, ...
                        'aligned_', ...
                        'IgnoreCase', ...
                        true);

                aligned_files = ...
                    tif_files_electroporated( ...
                        is_aligned);

                raw_files = ...
                    tif_files_electroporated( ...
                        ~is_aligned);

            else

                aligned_files = ...
                    tif_files_electroporated;

                raw_files = ...
                    tif_files_electroporated;
            end

            % ======================================================
            % Aucun fichier du canal demandé
            % ======================================================

            if isempty(aligned_files) && ...
                    isempty(raw_files)

                warning( ...
                    'load_or_process_cellpose_TSeries:SingleImageChannelMissing', ...
                    ['No Single image containing "%s" ' ...
                     'was found in:\n%s'], ...
                    electroporated_channel_str, ...
                    single_images_path);

                aligned_image = [];
                aligned_image_path = '';

            % ======================================================
            % Aligned existe déjà
            % ======================================================

            elseif ~isempty(aligned_files)

                aligned_image_path = ...
                    select_or_default( ...
                        aligned_files, ...
                        electroporated_channel_str, ...
                        '*.tif');

                aligned_image = ...
                    safe_read_and_normalize( ...
                        aligned_image_path);

                % ==================================================
                % Charger également le TIFF brut
                % ==================================================

                if ~isempty(raw_files)

                    electroporated_tif_path = ...
                        select_or_default( ...
                            raw_files, ...
                            electroporated_channel_str, ...
                            '*.tif');

                    if ~isempty(electroporated_tif_path)

                        electroporated_img = ...
                            safe_read_and_normalize( ...
                                electroporated_tif_path);

                        if ~isempty(electroporated_img)

                            meanImg_channels{2} = ...
                                electroporated_img;
                        end
                    end
                end

                % ==================================================
                % Aligned trouvé mais illisible
                % ==================================================

                if isempty(aligned_image) && ...
                        ~isempty(meanImg_channels{2}) && ...
                        ~isempty(meanImg_channels{1})

                    [ ...
                        aligned_image, ...
                        ~, ...
                        source_used ...
                    ] = ...
                        align_electroporated_locally_and_confirm( ...
                            meanImg_channels, ...
                            aligned_image_path);

                    fprintf( ...
                        'Transform estimated from: %s\n', ...
                        source_used);
                end

            % ======================================================
            % Aucun aligned :
            % charger TIFF brut puis recalage
            % ======================================================

            else

                electroporated_tif_path = ...
                    select_or_default( ...
                        raw_files, ...
                        electroporated_channel_str, ...
                        '*.tif');

                if isempty(electroporated_tif_path)

                    warning( ...
                        ['No Electroporated Single image ' ...
                         'was selected.']);

                    aligned_image = [];
                    aligned_image_path = '';

                else

                    electroporated_img = ...
                        safe_read_and_normalize( ...
                            electroporated_tif_path);

                    if ~isempty(electroporated_img)

                        meanImg_channels{2} = ...
                            electroporated_img;
                    end

                    % ==============================================
                    % GCaMP absent -> essayer de le recharger
                    % ==============================================

                    if isempty(meanImg_channels{1}) && ...
                            ~isempty(current_gcamp_suite2p_plane_path)

                        tmp = ...
                            load_meanImg_from_path( ...
                                current_gcamp_suite2p_plane_path);

                        if ~isempty(tmp)

                            meanImg_channels{1} = ...
                                tmp;

                            meanImg = ...
                                tmp;
                        end
                    end

                    if isempty(meanImg_channels{1})

                        warning( ...
                            ['GCaMP mean image missing. ' ...
                             'Electroporated alignment impossible.']);

                        aligned_image = [];
                        aligned_image_path = '';

                    elseif isempty(meanImg_channels{2})

                        warning( ...
                            ['Electroporated Single image could ' ...
                             'not be loaded.']);

                        aligned_image = [];
                        aligned_image_path = '';

                    else

                        [ ...
                            ~, ...
                            electroporated_file_name, ...
                            ~ ...
                        ] = ...
                            fileparts( ...
                                electroporated_tif_path);

                        aligned_image_path = ...
                            fullfile( ...
                                single_images_path, ...
                                [ ...
                                    'aligned_' ...
                                    electroporated_file_name ...
                                    '.tif' ...
                                ]);

                        [ ...
                            aligned_image, ...
                            ~, ...
                            source_used ...
                        ] = ...
                            align_electroporated_locally_and_confirm( ...
                                meanImg_channels, ...
                                aligned_image_path);

                        fprintf( ...
                            'Transform estimated from: %s\n', ...
                            source_used);
                    end
                end
            end
        end

    % ==============================================================
    %
    % AUCUNE SOURCE ELECTROPORATED
    %
    % ==============================================================

    else

        warning( ...
            'load_or_process_cellpose_TSeries:NoElectroporatedSource', ...
            ['No Electroporated source found for plane %d.\n' ...
             'Checked:\n' ...
             '1. Suite2p Electroporated\n' ...
             '2. Electroporated TSeries\n' ...
             '3. Single images'], ...
            p);

        [ ...
            meanImg_channels, ...
            meanImg ...
        ] = ...
            complete_meanImg_channels( ...
                meanImg_channels, ...
                filePath, ...
                current_gcamp_suite2p_plane_path, ...
                meanImg);

        return;
    end

    % ==============================================================
    % FLUX CELLPOSE FINAL
    % ==============================================================

    if ~isempty(aligned_image_path) && ...
            isfile(aligned_image_path)

        if isempty(aligned_image)

            aligned_image = ...
                safe_read_and_normalize( ...
                    aligned_image_path);
        end

        if ~isempty(aligned_image)

            [ ...
                aligned_folder, ...
                aligned_name, ...
                ~ ...
            ] = ...
                fileparts( ...
                    aligned_image_path);

            electroporated_seg_path = ...
                fullfile( ...
                    aligned_folder, ...
                    [aligned_name '_seg.npy']);

            % ======================================================
            % STEP 1
            %
            % Dessiner masques Electroporated si absents
            % ======================================================

            if ~isfile(electroporated_seg_path)

                fprintf('\n');
                fprintf('============================================\n');
                fprintf('CELLPOSE STEP 1\n');
                fprintf('DRAW MASKS ON ALIGNED ELECTROPORATED IMAGE\n');
                fprintf('Save with Ctrl+S, then close Cellpose.\n');
                fprintf('============================================\n');

                electroporated_seg_path = ...
                    launch_cellpose_from_matlab( ...
                        aligned_image_path, ...
                        true, ...
                        'Draw masks on aligned electroporated image');

                electroporated_seg_path = ...
                    validate_existing_file( ...
                        electroporated_seg_path);

            else

                fprintf( ...
                    ['Existing aligned-Electroporated masks ' ...
                     'found:\n%s\n'], ...
                    electroporated_seg_path);
            end

            % ======================================================
            % STEP 2
            %
            % Reporter / corriger masques sur GCaMP
            % ======================================================

            if ~isempty(electroporated_seg_path)

                npy_file_path = ...
                    create_and_refine_masks_on_gcamp( ...
                        aligned_image_path, ...
                        meanImg_channels{1}, ...
                        gcamp_output_folder_plane, ...
                        electroporated_seg_path);

                npy_file_path = ...
                    validate_existing_file( ...
                        npy_file_path);

            else

                warning( ...
                    ['No aligned-Electroporated *_seg.npy was saved. ' ...
                     'GCaMP correction cannot start.']);

                npy_file_path = [];
            end

        else

            warning( ...
                ['Aligned Electroporated TIFF exists but ' ...
                 'could not be read.']);

            npy_file_path = [];
        end

    elseif ~isempty(aligned_image)

        warning( ...
            ['An aligned Electroporated image exists in memory, ' ...
             'but its TIFF path is unavailable.']);

        npy_file_path = [];
    end

    % ==============================================================
    % Post-processing
    % ==============================================================

    [ ...
        meanImg_channels, ...
        meanImg ...
    ] = ...
        complete_meanImg_channels( ...
            meanImg_channels, ...
            filePath, ...
            current_gcamp_suite2p_plane_path, ...
            meanImg);
end

% ========================================================================
% SAFE READ
% ========================================================================

function img = safe_read_and_normalize(img_path)

    img = [];

    if isempty(img_path)
        return;
    end

    if ~(ischar(img_path) || ...
            isstring(img_path))
        return;
    end

    if ~isfile(img_path)
        return;
    end

    try

        img = ...
            normalize_image( ...
                imread(img_path));

    catch ME

        warning( ...
            'load_or_process_cellpose_TSeries:ReadImageFailed', ...
            'Failed reading image "%s": %s', ...
            char(img_path), ...
            ME.message);

        img = [];
    end
end


% ========================================================================
% VALIDATE FILE
% ========================================================================

function filepath = validate_existing_file(filepath)

    if isempty(filepath)

        filepath = [];
        return;
    end

    if ~(ischar(filepath) || ...
            isstring(filepath))

        filepath = [];
        return;
    end

    if ~isfile(filepath)

        filepath = [];
    end
end


% ========================================================================
% ALIGN ELECTROPORATED
% ========================================================================

function [aligned_image, T, source_used] = ...
        align_electroporated_locally_and_confirm( ...
            meanImg_channels, ...
            aligned_image_path)

    % meanImg_channels:
    %   {1} GCaMP
    %   {2} Electroporated
    %   {3} Green

    ref_img = [];

    if numel(meanImg_channels) >= 1

        ref_img = ...
            meanImg_channels{1};
    end

    electroporated_img = [];

    if numel(meanImg_channels) >= 2

        electroporated_img = ...
            meanImg_channels{2};
    end

    green_img = [];

    if numel(meanImg_channels) >= 3

        green_img = ...
            meanImg_channels{3};
    end

    aligned_image = [];
    T = [];
    source_used = '';

    % ==============================================================
    % Vérifications
    % ==============================================================

    if isempty(ref_img)

        warning( ...
            ['align_electroporated_locally_and_confirm: ' ...
             'GCaMP absent.']);

        return;
    end

    if isempty(electroporated_img)

        warning( ...
            ['align_electroporated_locally_and_confirm: ' ...
             'Electroporated image absent.']);

        return;
    end

    ref_img = ...
        double(ref_img);

    % ==============================================================
    % Image utilisée pour ESTIMER la translation
    %
    % Green prioritaire lorsqu'il existe.
    % Sinon Electroporated.
    % ==============================================================

    if ~isempty(green_img)

        moving_for_estimation = ...
            double(green_img);

        source_used = ...
            'Green';

    else

        moving_for_estimation = ...
            double(electroporated_img);

        source_used = ...
            'Electroporated';
    end

    % ==============================================================
    % Image réellement transformée
    % ==============================================================

    moving_img = ...
        double(electroporated_img);

    % ==============================================================
    % ==============================================================
    % Registration
    %
    % Extraire les structures sombres locales
    % (ex. vaisseaux) avant imregcorr
    % ==============================================================
    
    [moving_reg, moving_components] = ...
    extract_dark_structures_for_registration( ...
        moving_for_estimation);

    [ref_reg, ref_components] = ...
        extract_dark_structures_for_registration( ...
            ref_img);
    
    if ~isequal(size(moving_reg), size(ref_reg))
    
        moving_reg = ...
            imresize( ...
                moving_reg, ...
                size(ref_reg));
    
        moving_components = ...
            resize_registration_components( ...
                moving_components, ...
                size(ref_reg));
    end
    
    % ==============================================================
    % Afficher les transformations utilisées pour le recalage
    % ==============================================================
    
    % show_registration_components( ...
    %     moving_components, ...
    %     ref_components, ...
    %     moving_reg, ...
    %     ref_reg, ...
    %     source_used);
    
    % ==============================================================
    % Registration limitée à un rayon de 20 pixels
    % ==============================================================
    
    max_radius = 20;
    
    try
    
        T = ...
            find_best_translation_within_radius( ...
                moving_reg, ...
                ref_reg, ...
                max_radius);
    
        fprintf( ...
            '%s -> GCaMP | dark-weighted registration\n', ...
            source_used);
    
        fprintf( ...
            'Search radius = %d px\n', ...
            max_radius);
    
        fprintf( ...
            'dx = %.3f px\n', ...
            T(3,1));
    
        fprintf( ...
            'dy = %.3f px\n', ...
            T(3,2));
    
        fprintf( ...
            'distance = %.3f px\n', ...
            hypot( ...
                T(3,1), ...
                T(3,2)));
    
    catch ME
    
        warning( ...
            'Registration failed: %s', ...
            ME.message);
    
        T = ...
            eye(3);
    end
    % ==============================================================
    % Appliquer T à ELECTROPORATED
    % ==============================================================

    aligned_image = ...
        apply_transform_with_phasecorr( ...
            moving_img, ...
            T, ...
            ref_img);

    if isempty(aligned_image)

        warning( ...
            ['align_electroporated_locally_and_confirm: ' ...
             'empty transformation.']);

        return;
    end

    % ==============================================================
    % Dimensions
    % ==============================================================

    if ~isequal( ...
            size(aligned_image,1), ...
            size(ref_img,1)) || ...
            ~isequal( ...
                size(aligned_image,2), ...
                size(ref_img,2))

        aligned_image = ...
            imresize( ...
                aligned_image, ...
                [ ...
                    size(ref_img,1), ...
                    size(ref_img,2) ...
                ]);
    end

    % ==============================================================
    % Métriques
    % ==============================================================

    before_cmp = ...
        mat2gray( ...
            moving_img);

    ref_cmp = ...
        mat2gray( ...
            ref_img);

    after_cmp = ...
        mat2gray( ...
            aligned_image);

    if ~isequal( ...
            size(before_cmp), ...
            size(ref_cmp))

        before_cmp = ...
            imresize( ...
                before_cmp, ...
                size(ref_cmp));
    end

    if ~isequal( ...
            size(after_cmp), ...
            size(ref_cmp))

        after_cmp = ...
            imresize( ...
                after_cmp, ...
                size(ref_cmp));
    end

    before_err = ...
        mean( ...
            abs( ...
                ref_cmp(:) - ...
                before_cmp(:)), ...
            'omitnan');

    after_err = ...
        mean( ...
            abs( ...
                ref_cmp(:) - ...
                after_cmp(:)), ...
            'omitnan');

    fprintf( ...
        'Error vs ref before = %.6f\n', ...
        before_err);

    fprintf( ...
        'Error vs ref after  = %.6f\n', ...
        after_err);

    fprintf( ...
        'Improvement         = %.6f\n', ...
        before_err - after_err);

    % ==============================================================
    % Validation manuelle
    % ==============================================================

    [ ...
        was_saved, ...
        aligned_image, ...
        T ...
    ] = ...
        preview_alignment_with_save_cancel( ...
            moving_img, ...
            aligned_image, ...
            ref_img, ...
            T);

    if ~was_saved

        fprintf( ...
            'Alignment cancelled by user.\n');

        aligned_image = [];
        T = [];
        source_used = '';

        return;
    end

    % ==============================================================
    % Sauvegarde
    % ==============================================================

    if ~isempty(aligned_image) && ...
            ~isempty(aligned_image_path)

        try

            imwrite( ...
                aligned_image, ...
                aligned_image_path, ...
                'tif');

            fprintf( ...
                'Aligned electroporated image saved:\n%s\n', ...
                aligned_image_path);

        catch ME

            warning( ...
                ['Unable to save aligned electroporated ' ...
                 'image "%s": %s'], ...
                aligned_image_path, ...
                ME.message);
        end
    end
end

% ========================================================================
% FIND BEST TRANSLATION WITHIN RADIUS
%
% Recherche exhaustive de la meilleure translation entière dans un
% cercle de rayon max_radius autour de (0,0).
%
% Le score est une corrélation normalisée calculée uniquement sur la
% région réellement commune aux deux images. Les pixels ajoutés par
% translation ne participent donc pas au score.
% ========================================================================

function T = ...
        find_best_translation_within_radius( ...
            moving_img, ...
            ref_img, ...
            max_radius)

    % ==============================================================
    % Vérifications
    % ==============================================================

    if isempty(moving_img) || ...
            isempty(ref_img)

        error( ...
            'Moving and reference images must not be empty.');
    end

    moving_img = ...
        double(moving_img);

    ref_img = ...
        double(ref_img);

    if ~isequal( ...
            size(moving_img), ...
            size(ref_img))

        moving_img = ...
            imresize( ...
                moving_img, ...
                size(ref_img));
    end

    % ==============================================================
    % Initialisation
    % ==============================================================

    best_score = ...
        -Inf;

    best_dx = 0;
    best_dy = 0;

    n_rows = ...
        size(ref_img, 1);

    n_cols = ...
        size(ref_img, 2);

    % ==============================================================
    % Tester toutes les translations autorisées
    %
    % dx² + dy² <= rayon²
    % ==============================================================

    for dy = -max_radius:max_radius

        for dx = -max_radius:max_radius

            % ------------------------------------------------------
            % Limite CIRCULAIRE
            % ------------------------------------------------------

            if dx^2 + dy^2 > max_radius^2
                continue;
            end

            % ------------------------------------------------------
            % Coordonnées X de la zone commune
            % ------------------------------------------------------

            if dx >= 0

                ref_cols = ...
                    (1 + dx):n_cols;

                moving_cols = ...
                    1:(n_cols - dx);

            else

                ref_cols = ...
                    1:(n_cols + dx);

                moving_cols = ...
                    (1 - dx):n_cols;
            end

            % ------------------------------------------------------
            % Coordonnées Y de la zone commune
            % ------------------------------------------------------

            if dy >= 0

                ref_rows = ...
                    (1 + dy):n_rows;

                moving_rows = ...
                    1:(n_rows - dy);

            else

                ref_rows = ...
                    1:(n_rows + dy);

                moving_rows = ...
                    (1 - dy):n_rows;
            end

            % ------------------------------------------------------
            % Extraire uniquement la zone commune
            % ------------------------------------------------------

            ref_crop = ...
                ref_img( ...
                    ref_rows, ...
                    ref_cols);

            moving_crop = ...
                moving_img( ...
                    moving_rows, ...
                    moving_cols);

            % ------------------------------------------------------
            % Pixels valides
            % ------------------------------------------------------

            valid = ...
                isfinite(ref_crop) & ...
                isfinite(moving_crop);

            if nnz(valid) < 100
                continue;
            end

            a = ...
                ref_crop(valid);

            b = ...
                moving_crop(valid);

            % ------------------------------------------------------
            % Retirer la moyenne
            %
            % Cela évite que le niveau moyen de fluorescence
            % détermine le recalage.
            % ------------------------------------------------------

            a = ...
                a - mean(a);

            b = ...
                b - mean(b);

            % ------------------------------------------------------
            % Corrélation normalisée
            % ------------------------------------------------------

            denominator = ...
                sqrt( ...
                    sum(a.^2) * ...
                    sum(b.^2));

            if denominator <= eps
                continue;
            end

            score = ...
                sum(a .* b) ./ ...
                denominator;

            % ------------------------------------------------------
            % Meilleur déplacement
            % ------------------------------------------------------

            if score > best_score

                best_score = ...
                    score;

                best_dx = ...
                    dx;

                best_dy = ...
                    dy;
            end
        end
    end

    % ==============================================================
    % Transformation
    % ==============================================================

    if ~isfinite(best_score)

        error( ...
            'No valid translation found within %d pixels.', ...
            max_radius);
    end

    T = ...
        eye(3);

    T(3,1) = ...
        best_dx;

    T(3,2) = ...
        best_dy;

    fprintf( ...
        ['Best constrained registration: ' ...
         'dx = %d px | dy = %d px | ' ...
         'r = %.2f px | score = %.5f\n'], ...
        best_dx, ...
        best_dy, ...
        hypot(best_dx, best_dy), ...
        best_score);
end

% ========================================================================
% EXTRACT DARK STRUCTURES FOR REGISTRATION
%
% Prépare une image spécifiquement pour le recalage.
%
% Priorités :
%   - 65 % : minima sombres locaux / structures fines
%   - 25 % : structures sombres plus larges
%   - 10 % : organisation sombre globale
%
% Aucun seuillage dur afin de conserver les petits minima locaux.
% ========================================================================

% ========================================================================
% EXTRACT DARK STRUCTURES FOR REGISTRATION
% ========================================================================

function [out, components] = ...
        extract_dark_structures_for_registration(img)

    out = [];

    components = struct( ...
        'normalized', [], ...
        'fine_dark', [], ...
        'medium_dark', [], ...
        'coarse_dark', [], ...
        'global_dark', []);

    if isempty(img)
        return;
    end

    img = double(img);
    img(~isfinite(img)) = 0;

    % ==============================================================
    % 1) Normalisation robuste
    % ==============================================================

    vals = ...
        img(isfinite(img));

    if isempty(vals)

        out = ...
            zeros(size(img));

        return;
    end

    low_val = ...
        prctile(vals, 1);

    high_val = ...
        prctile(vals, 99);

    if high_val <= low_val

        img_norm = ...
            mat2gray(img);

    else

        img_norm = ...
            (img - low_val) ./ ...
            (high_val - low_val);

        img_norm = ...
            max( ...
                min(img_norm, 1), ...
                0);
    end

    components.normalized = ...
        img_norm;

    % ==============================================================
    % 2) Minima locaux fins
    % ==============================================================

    fine_img = ...
        imgaussfilt( ...
            img_norm, ...
            0.4);

    fine_background = ...
        imgaussfilt( ...
            img_norm, ...
            2.5);

    fine_dark = ...
        fine_background - ...
        fine_img;

    fine_dark = ...
        max( ...
            fine_dark, ...
            0);

    if any(fine_dark(:) > 0)

        fine_dark = ...
            mat2gray( ...
                fine_dark);

    else

        fine_dark = ...
            zeros(size(img_norm));
    end

    components.fine_dark = ...
        fine_dark;

    % ==============================================================
    % 3) Minima locaux intermédiaires
    % ==============================================================

    medium_img = ...
        imgaussfilt( ...
            img_norm, ...
            1);

    medium_background = ...
        imgaussfilt( ...
            img_norm, ...
            7);

    medium_dark = ...
        medium_background - ...
        medium_img;

    medium_dark = ...
        max( ...
            medium_dark, ...
            0);

    if any(medium_dark(:) > 0)

        medium_dark = ...
            mat2gray( ...
                medium_dark);

    else

        medium_dark = ...
            zeros(size(img_norm));
    end

    components.medium_dark = ...
        medium_dark;

    % ==============================================================
    % 4) Structures sombres larges
    % ==============================================================

    coarse_img = ...
        imgaussfilt( ...
            img_norm, ...
            2);

    coarse_background = ...
        imgaussfilt( ...
            img_norm, ...
            18);

    coarse_dark = ...
        coarse_background - ...
        coarse_img;

    coarse_dark = ...
        max( ...
            coarse_dark, ...
            0);

    if any(coarse_dark(:) > 0)

        coarse_dark = ...
            mat2gray( ...
                coarse_dark);

    else

        coarse_dark = ...
            zeros(size(img_norm));
    end

    components.coarse_dark = ...
        coarse_dark;

    % ==============================================================
    % 5) Organisation sombre globale
    % ==============================================================

    global_component = ...
        imgaussfilt( ...
            img_norm, ...
            2);

    global_dark = ...
        1 - global_component;

    global_dark = ...
        mat2gray( ...
            global_dark);

    components.global_dark = ...
        global_dark;

    % ==============================================================
    % 6) Combinaison
    %
    % Forte priorité aux minima locaux.
    % ==============================================================

    out = ...
        0.55 .* fine_dark + ...
        0.15 .* medium_dark + ...
        0.20 .* coarse_dark + ...
        0.10 .* global_dark;

    out = ...
        mat2gray(out);

    out = ...
        out .^ 1.1;

    out = ...
        imgaussfilt( ...
            out, ...
            0.25);

    out = ...
        mat2gray(out);
end


% ========================================================================
% SHOW REGISTRATION COMPONENTS
% ========================================================================

function show_registration_components( ...
        moving_components, ...
        ref_components, ...
        moving_reg, ...
        ref_reg, ...
        source_used)

    hFig = ...
        figure( ...
            'Name', ...
            'Registration preprocessing', ...
            'NumberTitle', ...
            'off', ...
            'Color', ...
            'w', ...
            'Position', ...
            [50 50 1700 950]);

    tl = ...
        tiledlayout( ...
            hFig, ...
            2, ...
            6, ...
            'TileSpacing', ...
            'compact', ...
            'Padding', ...
            'compact');

    % ==============================================================
    % Moving
    % ==============================================================

    nexttile;

    imagesc( ...
        moving_components.normalized);

    axis image off;
    colormap(gca, gray);

    title( ...
        sprintf( ...
            '%s normalized', ...
            source_used), ...
        'Interpreter', ...
        'none');

    nexttile;

    imagesc( ...
        moving_components.fine_dark);

    axis image off;
    colormap(gca, gray);

    title('Fine minima - 55%');

    nexttile;

    imagesc( ...
        moving_components.medium_dark);

    axis image off;
    colormap(gca, gray);

    title('Medium minima - 15%');

    nexttile;

    imagesc( ...
        moving_components.coarse_dark);

    axis image off;
    colormap(gca, gray);

    title('Coarse dark - 20%');

    nexttile;

    imagesc( ...
        moving_components.global_dark);

    axis image off;
    colormap(gca, gray);

    title('Global dark - 10%');

    nexttile;

    imagesc( ...
        moving_reg);

    axis image off;
    colormap(gca, gray);

    title('FINAL used for translation');

    % ==============================================================
    % Reference
    % ==============================================================

    nexttile;

    imagesc( ...
        ref_components.normalized);

    axis image off;
    colormap(gca, gray);

    title('GCaMP normalized');

    nexttile;

    imagesc( ...
        ref_components.fine_dark);

    axis image off;
    colormap(gca, gray);

    title('Fine minima - 55%');

    nexttile;

    imagesc( ...
        ref_components.medium_dark);

    axis image off;
    colormap(gca, gray);

    title('Medium minima - 15%');

    nexttile;

    imagesc( ...
        ref_components.coarse_dark);

    axis image off;
    colormap(gca, gray);

    title('Coarse dark - 20%');

    nexttile;

    imagesc( ...
        ref_components.global_dark);

    axis image off;
    colormap(gca, gray);

    title('Global dark - 10%');

    nexttile;

    imagesc( ...
        ref_reg);

    axis image off;
    colormap(gca, gray);

    title('FINAL used for translation');

    title( ...
        tl, ...
        sprintf( ...
            ['Registration preprocessing\n' ...
             '%s -> GCaMP'], ...
            source_used), ...
        'FontWeight', ...
        'bold');

    drawnow;
end

% ========================================================================
% PREVIEW ALIGNMENT
% ========================================================================

function [was_saved, aligned_img, T] = ...
        preview_alignment_with_save_cancel( ...
            original_img, ...
            aligned_img, ...
            ref_img, ...
            T)

    was_saved = false;

    if isempty(original_img) || ...
            isempty(aligned_img) || ...
            isempty(ref_img) || ...
            isempty(T)

        return;
    end

    original_img = double(original_img);
    aligned_img  = double(aligned_img);
    ref_img      = double(ref_img);

    dx = T(3,1);
    dy = T(3,2);

    original_disp = ...
        enhance_for_overlay( ...
            original_img);

    aligned_disp = ...
        enhance_for_overlay( ...
            aligned_img);

    ref_disp = ...
        enhance_for_overlay( ...
            ref_img);

    hFig = figure( ...
        'Name', ...
        'Preview electroporated alignment', ...
        'NumberTitle', ...
        'off', ...
        'MenuBar', ...
        'none', ...
        'ToolBar', ...
        'none', ...
        'Color', ...
        'w', ...
        'Position', ...
        [80 80 1500 720], ...
        'CloseRequestFcn', ...
        @onCancel);

    S = struct();

    S.saved = false;
    S.state = 1;

    S.original_img = original_img;
    S.aligned_img = aligned_img;
    S.ref_img = ref_img;
    S.T = T;

    S.original_disp = original_disp;
    S.aligned_disp = aligned_disp;
    S.ref_disp = ref_disp;

    S.ax1 = axes( ...
        'Parent', hFig, ...
        'Position', [0.05 0.12 0.34 0.78]);

    S.ax2 = axes( ...
        'Parent', hFig, ...
        'Position', [0.44 0.12 0.34 0.78]);

    S.infoTxt = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'text', ...
        'String', ...
        sprintf( ...
            ['Automatic alignment\n\n' ...
             'dx = %.2f px\n' ...
             'dy = %.2f px\n\n' ...
             'Left: original / aligned\n' ...
             'Right: GCaMP / aligned'], ...
            dx, ...
            dy), ...
        'FontSize', 11, ...
        'BackgroundColor', 'w', ...
        'HorizontalAlignment', 'left', ...
        'Units', 'normalized', ...
        'Position', [0.81 0.62 0.16 0.22]);

    S.btnManual = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Manual alignment', ...
        'FontSize', 12, ...
        'Units', 'normalized', ...
        'Position', [0.82 0.54 0.14 0.08], ...
        'Callback', @onManual);

    S.btnSave = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Save', ...
        'FontSize', 12, ...
        'Units', 'normalized', ...
        'Position', [0.82 0.42 0.14 0.08], ...
        'Callback', @onSave);

    S.btnCancel = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Cancel', ...
        'FontSize', 12, ...
        'Units', 'normalized', ...
        'Position', [0.82 0.30 0.14 0.08], ...
        'Callback', @onCancel);

    guidata(hFig, S);

    refresh_alternating_display(hFig);

    animTimer = timer( ...
        'ExecutionMode', ...
        'fixedSpacing', ...
        'Period', ...
        0.6, ...
        'TimerFcn', ...
        @(~,~) toggle_display(hFig));

    S = guidata(hFig);

    S.animTimer = ...
        animTimer;

    guidata(hFig, S);

    start(animTimer);

    uiwait(hFig);

    if isvalid_handle(hFig)

        S = guidata(hFig);

        if isfield(S, 'animTimer') && ...
                ~isempty(S.animTimer) && ...
                isvalid(S.animTimer)

            stop(S.animTimer);
            delete(S.animTimer);
        end

        was_saved = S.saved;
        aligned_img = S.aligned_img;
        T = S.T;

        delete(hFig);
    end


    function toggle_display(fig)

        if ~isvalid_handle(fig)
            return;
        end

        S = guidata(fig);

        S.state = ...
            3 - S.state;

        guidata(fig, S);

        refresh_alternating_display(fig);
    end


    function refresh_alternating_display(fig)

        if ~isvalid_handle(fig)
            return;
        end

        S = guidata(fig);

        cla(S.ax1);
        cla(S.ax2);

        if S.state == 1

            imagesc( ...
                S.ax1, ...
                S.original_disp);

            axis( ...
                S.ax1, ...
                'image');

            title( ...
                S.ax1, ...
                'Electroporated original');

            imagesc( ...
                S.ax2, ...
                S.ref_disp);

            axis( ...
                S.ax2, ...
                'image');

            title( ...
                S.ax2, ...
                'GCaMP reference');

        else

            imagesc( ...
                S.ax1, ...
                S.aligned_disp);

            axis( ...
                S.ax1, ...
                'image');

            title( ...
                S.ax1, ...
                'Electroporated aligned');

            imagesc( ...
                S.ax2, ...
                S.aligned_disp);

            axis( ...
                S.ax2, ...
                'image');

            title( ...
                S.ax2, ...
                'Electroporated aligned');
        end

        colormap(S.ax1, parula);
        colormap(S.ax2, parula);

        drawnow limitrate;
    end


    function onManual(src, ~)

        fig = ...
            ancestor( ...
                src, ...
                'figure');

        if isempty(fig) || ...
                ~isvalid_handle(fig)

            return;
        end

        S = ...
            guidata(fig);

        if isfield(S, 'animTimer') && ...
                ~isempty(S.animTimer) && ...
                isvalid(S.animTimer)

            stop(S.animTimer);
        end

        [ ...
            T_manual, ...
            was_manual_saved ...
        ] = ...
            manual_translation_gui( ...
                S.original_img, ...
                S.ref_img, ...
                S.T);

        if was_manual_saved && ...
                ~isempty(T_manual)

            S.T = ...
                T_manual;

            S.aligned_img = ...
                apply_transform_with_phasecorr( ...
                    S.original_img, ...
                    S.T, ...
                    S.ref_img);

            if ~isempty(S.aligned_img)

                S.aligned_disp = ...
                    enhance_for_overlay( ...
                        S.aligned_img);

                dx = S.T(3,1);
                dy = S.T(3,2);

                set( ...
                    S.infoTxt, ...
                    'String', ...
                    sprintf( ...
                        ['Manual alignment\n\n' ...
                         'dx = %.2f px\n' ...
                         'dy = %.2f px'], ...
                        dx, ...
                        dy));
            end

            guidata(fig, S);

            refresh_alternating_display(fig);
        end

        S = guidata(fig);

        if isfield(S, 'animTimer') && ...
                ~isempty(S.animTimer) && ...
                isvalid(S.animTimer)

            start(S.animTimer);
        end
    end


    function onSave(src, ~)

        fig = ...
            ancestor(src, 'figure');

        if isempty(fig) || ...
                ~isvalid_handle(fig)

            return;
        end

        S = guidata(fig);

        S.saved = true;

        guidata(fig, S);

        if isfield(S, 'animTimer') && ...
                ~isempty(S.animTimer) && ...
                isvalid(S.animTimer)

            stop(S.animTimer);
        end

        uiresume(fig);
    end


    function onCancel(src, ~)

        fig = src;

        if ~ishandle(fig) || ...
                ~strcmp(get(fig, 'Type'), 'figure')

            fig = ...
                ancestor(src, 'figure');
        end

        if isempty(fig) || ...
                ~isvalid_handle(fig)

            return;
        end

        S = guidata(fig);

        S.saved = false;

        guidata(fig, S);

        if isfield(S, 'animTimer') && ...
                ~isempty(S.animTimer) && ...
                isvalid(S.animTimer)

            stop(S.animTimer);
        end

        uiresume(fig);
    end
end


% ========================================================================
% MANUAL TRANSLATION
% ========================================================================

function [T_out, was_saved] = ...
        manual_translation_gui( ...
            moving_img, ...
            ref_img, ...
            T_init)

    was_saved = false;
    T_out = [];

    if isempty(moving_img) || ...
            isempty(ref_img)

        return;
    end

    moving_img = double(moving_img);
    ref_img = double(ref_img);

    if nargin < 3 || ...
            isempty(T_init)

        T_init = eye(3);
    end

    tx = T_init(3,1);
    ty = T_init(3,2);

    ref_size = size(ref_img);
    ref_size = ref_size(1:2);

    S = struct();

    S.moving = moving_img;
    S.ref = ref_img;
    S.tx = tx;
    S.ty = ty;
    S.dragging = false;
    S.startPoint = [0 0];
    S.startTxTy = [tx ty];
    S.saved = false;

    hFig = figure( ...
        'Name', 'Manual alignment', ...
        'NumberTitle', 'off', ...
        'Color', 'w', ...
        'MenuBar', 'none', ...
        'ToolBar', 'figure', ...
        'Position', [200 120 1200 780], ...
        'WindowButtonDownFcn', @onMouseDown, ...
        'WindowButtonUpFcn', @onMouseUp, ...
        'WindowButtonMotionFcn', @onMouseMove, ...
        'CloseRequestFcn', @onCancel);

    S.ax = axes( ...
        'Parent', hFig, ...
        'Position', [0.05 0.08 0.70 0.86]);

    axis(S.ax, 'image');
    hold(S.ax, 'on');

    uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Save', ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [0.81 0.80 0.15 0.08], ...
        'Callback', @onSave);

    uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Cancel', ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [0.81 0.68 0.15 0.08], ...
        'Callback', @onCancel);

    S.sliderAlpha = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'slider', ...
        'Min', 0.05, ...
        'Max', 1, ...
        'Value', 0.5, ...
        'Units', 'normalized', ...
        'Position', [0.81 0.54 0.15 0.04], ...
        'Callback', ...
        @(~,~) refreshOverlay(hFig));

    S.txt = uicontrol( ...
        'Parent', hFig, ...
        'Style', 'text', ...
        'String', '', ...
        'FontSize', 11, ...
        'BackgroundColor', 'w', ...
        'HorizontalAlignment', 'left', ...
        'Units', 'normalized', ...
        'Position', [0.80 0.35 0.18 0.12]);

    guidata(hFig, S);

    refreshOverlay(hFig);

    uiwait(hFig);

    if isvalid_handle(hFig)

        S = guidata(hFig);

        if S.saved

            T_out = eye(3);

            T_out(3,1) = S.tx;
            T_out(3,2) = S.ty;

            was_saved = true;
        end

        delete(hFig);
    end


    function onMouseDown(src, ~)

        S = guidata(src);

        cp = ...
            get( ...
                S.ax, ...
                'CurrentPoint');

        S.dragging = true;
        S.startPoint = cp(1,1:2);
        S.startTxTy = [S.tx S.ty];

        guidata(src, S);
    end


    function onMouseMove(src, ~)

        S = guidata(src);

        if ~S.dragging
            return;
        end

        cp = ...
            get( ...
                S.ax, ...
                'CurrentPoint');

        delta = ...
            cp(1,1:2) - ...
            S.startPoint;

        S.tx = ...
            S.startTxTy(1) + ...
            delta(1);

        S.ty = ...
            S.startTxTy(2) + ...
            delta(2);

        guidata(src, S);

        refreshOverlay(src);
    end


    function onMouseUp(src, ~)

        S = guidata(src);

        S.dragging = false;

        guidata(src, S);
    end


    function onSave(src, ~)

        fig = ancestor(src, 'figure');

        S = guidata(fig);

        S.saved = true;

        guidata(fig, S);

        uiresume(fig);
    end


    function onCancel(src, ~)

        fig = ancestor(src, 'figure');

        if isempty(fig)
            fig = src;
        end

        if ~isvalid_handle(fig)
            return;
        end

        S = guidata(fig);

        S.saved = false;

        guidata(fig, S);

        uiresume(fig);
    end


    function refreshOverlay(fig)

        if ~isvalid_handle(fig)
            return;
        end

        S = guidata(fig);

        Ttmp = eye(3);

        Ttmp(3,1) = S.tx;
        Ttmp(3,2) = S.ty;

        moved = ...
            imwarp( ...
                double(S.moving), ...
                affine2d(Ttmp), ...
                'OutputView', ...
                imref2d(ref_size));

        ref_disp = ...
            enhance_for_overlay( ...
                S.ref);

        moved_disp = ...
            enhance_for_overlay( ...
                moved);

        alpha_val = ...
            get( ...
                S.sliderAlpha, ...
                'Value');

        cla(S.ax);

        hold(S.ax, 'on');

        imagesc( ...
            S.ax, ...
            ref_disp);

        hMov = ...
            imagesc( ...
                S.ax, ...
                moved_disp);

        set( ...
            hMov, ...
            'AlphaData', ...
            alpha_val);

        axis(S.ax, 'image');

        title( ...
            S.ax, ...
            'Drag electroporated image');

        set( ...
            S.txt, ...
            'String', ...
            sprintf( ...
                'dx = %.2f px\ndy = %.2f px\nalpha = %.2f', ...
                S.tx, ...
                S.ty, ...
                alpha_val));

        drawnow limitrate;
    end
end


% ========================================================================
% APPLY TRANSFORM
% ========================================================================

function aligned_img = ...
        apply_transform_with_phasecorr( ...
            channel_img, ...
            T, ...
            ref_img)

    aligned_img = [];

    if isempty(channel_img) || ...
            isempty(T) || ...
            isempty(ref_img)

        return;
    end

    ref_size = ...
        size(ref_img);

    ref_size = ...
        ref_size(1:2);

    try

        aligned_raw = ...
            imwarp( ...
                double(channel_img), ...
                affine2d(T), ...
                'OutputView', ...
                imref2d(ref_size), ...
                'Interp', ...
                'linear');

    catch ME

        warning( ...
            'apply_transform_with_phasecorr: %s', ...
            ME.message);

        return;
    end

    aligned_img = ...
        normalize_image( ...
            aligned_raw);
end


% ========================================================================
% LOAD MEAN IMAGE
% ========================================================================

function meanImg = load_meanImg_from_path(path_in)

    meanImg = [];

    if isempty(path_in)
        return;
    end

    if isfolder(path_in)

        ops_npy = ...
            fullfile( ...
                path_in, ...
                'ops.npy');

        if isfile(ops_npy)

            try

                mod = ...
                    py.importlib.import_module( ...
                        'python_function');

                ops = ...
                    mod.read_npy_file( ...
                        ops_npy);

                meanImg = ...
                    double( ...
                        ops{'meanImg'});

                return;

            catch

                warning( ...
                    'Error reading ops.npy in %s', ...
                    path_in);
            end
        end

        ops_mat = ...
            fullfile( ...
                path_in, ...
                'ops.mat');

        if isfile(ops_mat)

            S = load(ops_mat);

            if isfield(S, 'ops') && ...
                    isfield(S.ops, 'meanImg')

                meanImg = ...
                    S.ops.meanImg;

                return;
            end
        end
    end
end


% ========================================================================
% SELECT FILE
% ========================================================================

function path_out = ...
        select_or_default( ...
            files, ...
            canal_str, ...
            pattern)

    if isempty(files)

        path_out = '';
        return;
    end

    if numel(files) > 1

        [selected_file, selected_path] = ...
            uigetfile( ...
                {['*' canal_str pattern]}, ...
                'Select file', ...
                fullfile( ...
                    files(1).folder, ...
                    files(1).name));

        if isequal(selected_file, 0)

            path_out = '';
            return;
        end

        path_out = ...
            fullfile( ...
                selected_path, ...
                selected_file);

    else

        path_out = ...
            fullfile( ...
                files(1).folder, ...
                files(1).name);
    end
end


% ========================================================================
% COMPLETE MEAN IMAGES
% ========================================================================

function [meanImg_channels, meanImg] = ...
        complete_meanImg_channels( ...
            meanImg_channels, ...
            filePath, ...
            gcamp_plane_path, ...
            meanImg)

    try

        if ~isempty(filePath) && ...
                exist(filePath, 'file') == 2

            saved_data = ...
                load(filePath);

            if isfield( ...
                    saved_data, ...
                    'meanImg_channels')

                source = ...
                    saved_data.meanImg_channels;

                n = ...
                    min( ...
                        numel(meanImg_channels), ...
                        numel(source));

                for j = 1:n

                    if isempty(meanImg_channels{j})

                        meanImg_channels{j} = ...
                            source{j};
                    end
                end
            end
        end

        if isempty(meanImg)

            if ~isempty(meanImg_channels{1})

                meanImg = ...
                    meanImg_channels{1};

            elseif ~isempty(gcamp_plane_path)

                meanImg = ...
                    load_meanImg_from_path( ...
                        gcamp_plane_path);

                if ~isempty(meanImg)

                    meanImg_channels{1} = ...
                        meanImg;
                end
            end
        end

    catch ME

        warning( ...
            'complete_meanImg_channels: %s', ...
            ME.message);
    end
end


% ========================================================================
% NORMALIZE IMAGE
% ========================================================================

function norm_img = normalize_image(img)

    if isfloat(img)

        norm_img = ...
            mat2gray(img);

    elseif isinteger(img)

        denom = ...
            double( ...
                max(img(:)));

        if denom == 0

            norm_img = ...
                uint8(img);

        else

            norm_img = ...
                uint8( ...
                    double(img) ./ denom .* 255);
        end

    else

        norm_img = ...
            mat2gray( ...
                double(img));
    end
end


% ========================================================================
% ENHANCE DISPLAY
% ========================================================================

function out = enhance_for_overlay(img)

    img = double(img);

    if isempty(img) || ...
            all(~isfinite(img(:)))

        out = zeros(size(img));
        return;
    end

    vals = ...
        img(isfinite(img));

    p_low = ...
        prctile(vals, 2);

    p_high = ...
        prctile(vals, 98);

    if p_high <= p_low

        out = ...
            mat2gray(img);

        return;
    end

    out = ...
        (img - p_low) ./ ...
        (p_high - p_low);

    out = ...
        max( ...
            min(out, 1), ...
            0);

    out = ...
        out .^ 0.7;
end


% ========================================================================
% HANDLE
% ========================================================================

function tf = isvalid_handle(h)

    tf = ...
        ~isempty(h) && ...
        isgraphics(h);
end


% ========================================================================
% CREATE / REFINE GCAMP MASKS
% ========================================================================

function final_npy_path = ...
        create_and_refine_masks_on_gcamp( ...
            aligned_electroporated_path, ...
            gcamp_image, ...
            output_folder, ...
            electroporated_seg_path)

    final_npy_path = [];

    if isempty(aligned_electroporated_path) || ...
            ~isfile(aligned_electroporated_path)

        warning( ...
            'create_and_refine_masks_on_gcamp:MissingAlignedElectroporated', ...
            'Aligned electroporated image not found.');

        return;
    end

    if isempty(output_folder)

        output_folder = ...
            fileparts( ...
                aligned_electroporated_path);
    end

    if ~isfolder(output_folder)

        mkdir(output_folder);
    end

    % ==============================================================
    % GCaMP reference path
    % ==============================================================

    [~, electroporated_name, ~] = ...
        fileparts( ...
            aligned_electroporated_path);

    electroporated_name = ...
        regexprep( ...
            electroporated_name, ...
            '^aligned_', ...
            '');

    gcamp_reference_path = ...
        fullfile( ...
            output_folder, ...
            [ ...
                'gcamp_reference_' ...
                electroporated_name ...
                '.tif' ...
            ]);
    
    fprintf( ...
    ['Existing aligned-electroporated masks found.\n' ...
     'Continuing with GCaMP reference:\n%s\n'], ...
    gcamp_reference_path);
    
    [gcamp_folder, gcamp_name, ~] = ...
        fileparts( ...
            gcamp_reference_path);

    existing_gcamp_seg_path = ...
        fullfile( ...
            gcamp_folder, ...
            [gcamp_name '_seg.npy']);

    % ==============================================================
    % Déjà corrigé
    % ==============================================================

    if isfile(existing_gcamp_seg_path)

        final_npy_path = ...
            validate_existing_file( ...
                existing_gcamp_seg_path);

        fprintf( ...
            'Existing corrected GCaMP masks found:\n%s\n', ...
            final_npy_path);

        return;
    end

    % ==============================================================
    % Vérifier source masks
    % ==============================================================

    if isempty(electroporated_seg_path) || ...
            ~isfile(electroporated_seg_path)

        warning( ...
            'create_and_refine_masks_on_gcamp:MissingElectroporatedMasks', ...
            'Aligned-electroporated Cellpose masks not found.');

        return;
    end

    if isempty(gcamp_image)

        warning( ...
            'create_and_refine_masks_on_gcamp:MissingGCampImage', ...
            'GCaMP reference mean image is empty.');

        return;
    end

    % ==============================================================
    % Créer référence GCaMP
    % ==============================================================

    if ~isfile(gcamp_reference_path)

        gcamp_reference_image = ...
            prepare_image_for_cellpose_display( ...
                gcamp_image);

        try

            imwrite( ...
                gcamp_reference_image, ...
                gcamp_reference_path, ...
                'tif');

        catch ME

            warning( ...
                'create_and_refine_masks_on_gcamp:SaveReferenceFailed', ...
                '%s', ...
                ME.message);

            return;
        end
    end

    % ==============================================================
    % Copier masques electroporated vers GCaMP
    % ==============================================================

    success = ...
        create_gcamp_seg_from_electroporated_seg( ...
            electroporated_seg_path, ...
            gcamp_reference_path, ...
            existing_gcamp_seg_path);

    if ~success || ...
            ~isfile(existing_gcamp_seg_path)

        warning( ...
            'create_and_refine_masks_on_gcamp:InitialSegFailed', ...
            'Unable to create initial GCaMP segmentation.');

        return;
    end

    % ==============================================================
    % Correction GCaMP
    % ==============================================================

    fprintf('\n');
    fprintf('GCaMP mask correction\n');
    fprintf('Save with Ctrl+S, then close Cellpose.\n');

    final_npy_path = ...
        launch_cellpose_from_matlab( ...
            gcamp_reference_path, ...
            false, ...
            'Correct masks on GCaMP');

    final_npy_path = ...
        validate_existing_file( ...
            final_npy_path);
end


% ========================================================================
% COPY ELECTROPORATED MASKS TO GCAMP
% ========================================================================

function success = ...
        create_gcamp_seg_from_electroporated_seg( ...
            source_seg_path, ...
            gcamp_image_path, ...
            destination_seg_path)

    success = false;

    if ~isfile(source_seg_path) || ...
            ~isfile(gcamp_image_path)

        return;
    end

    pyExec = ...
        'C:\Users\goldstein\AppData\Local\anaconda3\envs\cellpose\python.exe';

    script_path = ...
        [tempname '.py'];

    fid = ...
        fopen( ...
            script_path, ...
            'w');

    if fid == -1

        warning( ...
            'Unable to create temporary Python script.');

        return;
    end

    cleanupObj = ...
        onCleanup( ...
            @() delete_temp_script( ...
                script_path)); %#ok<NASGU>

    lines = {
        'import sys'
        'import numpy as np'
        'import tifffile'
        ''
        'source_seg = sys.argv[1]'
        'gcamp_path = sys.argv[2]'
        'destination_seg = sys.argv[3]'
        ''
        'data = np.load(source_seg, allow_pickle=True).item()'
        'gcamp_img = tifffile.imread(gcamp_path)'
        'masks = np.asarray(data["masks"])'
        ''
        'if masks.shape[-2:] != gcamp_img.shape[-2:]:'
        '    raise ValueError("Mask and GCaMP dimensions differ")'
        ''
        'data["img"] = gcamp_img'
        'data["filename"] = gcamp_path'
        'np.save(destination_seg, data, allow_pickle=True)'
    };

    for k = 1:numel(lines)

        fprintf( ...
            fid, ...
            '%s\n', ...
            lines{k});
    end

    fclose(fid);

    command = ...
        sprintf( ...
            '"%s" "%s" "%s" "%s" "%s"', ...
            pyExec, ...
            script_path, ...
            source_seg_path, ...
            gcamp_image_path, ...
            destination_seg_path);

    [status, command_output] = ...
        system(command);

    if status ~= 0

        warning( ...
            'Error creating GCaMP segmentation:\n%s', ...
            command_output);

        return;
    end

    success = ...
        isfile(destination_seg_path);
end


% ========================================================================
% TEMP SCRIPT
% ========================================================================

function delete_temp_script(script_path)

    if isfile(script_path)

        try
            delete(script_path);
        catch
        end
    end
end


% ========================================================================
% PREPARE GCAMP IMAGE
% ========================================================================

function image_out = ...
        prepare_image_for_cellpose_display( ...
            image_in)

    image_in = ...
        double(image_in);

    image_in(~isfinite(image_in)) = 0;

    values = ...
        image_in(isfinite(image_in));

    if isempty(values)

        image_out = ...
            uint16( ...
                zeros(size(image_in)));

        return;
    end

    low_value = ...
        prctile(values, 1);

    high_value = ...
        prctile(values, 99.8);

    if high_value <= low_value

        normalized = ...
            mat2gray(image_in);

    else

        normalized = ...
            (image_in - low_value) ./ ...
            (high_value - low_value);

        normalized = ...
            max( ...
                0, ...
                min(1, normalized));
    end

    normalized = ...
        normalized .^ 0.7;

    image_out = ...
        uint16( ...
            normalized .* 65535);
end


% ========================================================================
% PLANE INDEX
% ========================================================================

function plane_index = ...
        infer_plane_index_from_paths(varargin)

    plane_index = 0;

    for i = 1:nargin

        path_in = ...
            varargin{i};

        if isempty(path_in) || ...
                ~(ischar(path_in) || ...
                  isstring(path_in))

            continue;
        end

        token = ...
            regexp( ...
                char(path_in), ...
                'plane(\d+)', ...
                'tokens', ...
                'once');

        if ~isempty(token)

            plane_index = ...
                str2double( ...
                    token{1});

            if isfinite(plane_index)
                return;
            end
        end
    end
end


% ========================================================================
% CELLPOSE
% ========================================================================

function npy_file_path = ...
        launch_cellpose_from_matlab( ...
            image_path, ...
            ask_confirmation, ...
            dialog_title)

    npy_file_path = [];

    if nargin < 2 || ...
            isempty(ask_confirmation)

        ask_confirmation = true;
    end

    if nargin < 3 || ...
            isempty(dialog_title)

        dialog_title = ...
            'Launch Cellpose';
    end

    if isempty(image_path) || ...
            ~isfile(image_path)

        warning( ...
            'Cellpose image not found: %s', ...
            char(string(image_path)));

        return;
    end

    pyExec = ...
        'C:\Users\goldstein\AppData\Local\anaconda3\envs\cellpose\python.exe';

    cellposePath = ...
        'C:\Users\goldstein\AppData\Local\anaconda3\envs\cellpose\Scripts\cellpose.exe';

    if ~isfile(cellposePath)

        warning( ...
            'cellpose.exe not found: %s', ...
            cellposePath);

        return;
    end

    try

        currentPyEnv = pyenv;

        if ~strcmp( ...
                currentPyEnv.Version, ...
                pyExec)

            pyenv( ...
                'Version', ...
                pyExec);
        end

    catch ME

        warning( ...
            'Unable to configure pyenv: %s', ...
            ME.message);
    end

    [folderPath, fileName, ~] = ...
        fileparts( ...
            image_path);

    candidate_npy = ...
        fullfile( ...
            folderPath, ...
            [fileName '_seg.npy']);

    file_existed_before = ...
        isfile(candidate_npy);

    previous_datenum = [];
    previous_bytes = [];

    if file_existed_before

        info_before = ...
            dir(candidate_npy);

        previous_datenum = ...
            info_before.datenum;

        previous_bytes = ...
            info_before.bytes;
    end

    if ask_confirmation

        % Afficher le chemin dans la Command Window
        fprintf('\n');
        fprintf('Cellpose image:\n');
        fprintf('%s\n\n', image_path);
    
        answer = ...
            questdlg( ...
                ['Do you want to launch Cellpose?' newline newline ...
                 'Save with Ctrl+S, then close Cellpose.'], ...
                dialog_title, ...
                'Yes', ...
                'No', ...
                'Yes');
    
        if ~strcmp(answer, 'Yes')
            return;
        end
    end

    [status, command_output] = ...
        system( ...
            ['"' cellposePath '"']);

    if status ~= 0

        warning( ...
            'Cellpose closed with status %d:\n%s', ...
            status, ...
            command_output);

        return;
    end

    if ~isfile(candidate_npy)

        warning( ...
            'No Cellpose segmentation saved for:\n%s', ...
            image_path);

        return;
    end

    info_after = ...
        dir(candidate_npy);

    if file_existed_before

        file_was_modified = ...
            info_after.datenum > previous_datenum || ...
            info_after.bytes ~= previous_bytes;

        if ~file_was_modified

            warning( ...
                ['Existing segmentation was not modified. ' ...
                 'Use Ctrl+S before closing Cellpose.']);

            return;
        end
    end

    npy_file_path = ...
        candidate_npy;
end