function [processing_cache, data] = process_electroporated_pass1( ...
    gcamp_root_folders, ...
    gcamp_output_folders, ...
    include_electroporated, ...
    date_group_paths, ...
    TSeries_paths, ...
    suite2p_folders, ...
    metadata, ...
    data)

    numFolders = numel(gcamp_root_folders);

    % ==============================================================
    % Colonnes suite2p
    %
    %   1 = GCaMP
    %   2 = canal potentiel electroporated
    %   3 = canal potentiel electroporated
    %   4 = Green
    % ==============================================================

    current_gcamp_folders_group = ...
        suite2p_folders(:, 1);

    current_green_folders_group = ...
        suite2p_folders(:, 4);

    % ==============================================================
    % Déterminer automatiquement le canal electroporated
    % ==============================================================

    [ ...
        current_electroporated_TSeries_path, ...
        current_electroporated_folders_group, ...
        electroporated_column_by_group ...
    ] = ...
        get_electroporated_channel( ...
            TSeries_paths, ...
            suite2p_folders, ...
            numFolders);

    % ==============================================================
    % Champs electroporated sauvegardés
    % ==============================================================

    fields_electroporated_saved = { ...
        'matched_gcamp_idx_by_plane', ...
        'matched_cellpose_idx_by_plane', ...
        'gcamp_unmatched_idx_by_plane', ...
        'cellpose_unmatched_idx_by_plane', ...
        'num_cells_mask_by_plane', ...
        'mask_cellpose_by_plane', ...
        'props_cellpose_by_plane', ...
        'outlines_x_cellpose_by_plane', ...
        'outlines_y_cellpose_by_plane', ...
        'F_electroporated_by_plane', ...
        'electroporated_match_mask_by_plane', ...
        'roi_extraction_completed_by_plane', ...
        'roi_extraction_npy_signature_by_plane'};

    fields_electroporated_memory = { ...
        'ops_suite2p_electroporated_by_plane', ...
        'electroporated_fall_path_by_plane', ...
        'meanImg_channels_by_plane', ...
        'alignedImgs_electroporated', ...
        'cellpose_npy_file_path_by_plane', ...
        'gcamp_reference_meanImg_by_plane'};

    fields_electroporated_all = [ ...
        fields_electroporated_saved, ...
        fields_electroporated_memory];

    % ==============================================================
    % Champs GCaMP nécessaires
    % ==============================================================

    gcamp_needed = { ...
        'stat_by_plane', ...
        'F_gcamp_by_plane', ...
        'gcamp_props_by_plane', ...
        'outlines_gcampx_by_plane', ...
        'outlines_gcampy_by_plane', ...
        'iscell_gcamp_by_plane', ...
        'gcamp_mask_by_plane', ...
        'gcamp_props_false_by_plane', ...
        'outlines_gcampx_false_by_plane', ...
        'outlines_gcampy_false_by_plane', ...
        'gcamp_mask_false_by_plane'};

    % ==============================================================
    % Initialisation
    % ==============================================================

    data = init_electroporated_plane_struct_if_needed( ...
        data, ...
        numFolders, ...
        fields_electroporated_all);

    data = init_gcamp_plane_struct_if_needed_local( ...
        data, ...
        numFolders, ...
        gcamp_needed);

    processing_cache = cell(numFolders, 1);

    fprintf('\n============================================================\n');
    fprintf('ELECTROPORATED PASS 1: CELLPOSE PREPARATION\n');
    fprintf('============================================================\n');

    % ==============================================================
    % PASS 1A
    % ==============================================================

    for m = 1:numFolders

        cache = struct();

        cache.valid_group = false;
        cache.skip_group = false;
        cache.nPlanes = 0;

        cache.electroporated_column = NaN;

        cache.filePath_electroporated = '';
        cache.filePath_gcamp = '';

        cache.gcamp_planes = {};
        cache.electroporated_planes = {};
        cache.green_planes = {};

        cache.F_gcamp_by_plane = {};
        cache.gcamp_props_by_plane = {};
        cache.iscell_gcamp_by_plane = {};
        cache.gcamp_mask_by_plane = {};
        cache.gcamp_mask_false_by_plane = {};

        cache.has_new_electroporated_data = false;

        cache.metadata_match = true;
        cache.metadata_mismatch_message = '';

        cache.planes = {};

        fprintf( ...
            '\nPreparing recording group %d/%d...\n', ...
            m, ...
            numFolders);

        % ==========================================================
        % Canal electroporated
        % ==========================================================

        cache.electroporated_column = ...
            electroporated_column_by_group(m);

        if ~isfinite(cache.electroporated_column)

            warning( ...
                'process_electroporated_pass1:NoElectroporatedChannel', ...
                ['Recording group %d: no electroporated channel ' ...
                 'detected. Recording skipped.'], ...
                m);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Processing désactivé
        % ==========================================================

        if include_electroporated ~= 1

            fprintf( ...
                ['Group %d: electroporated processing ' ...
                 'disabled.\n'], ...
                m);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % VALIDATE GCAMP / ELECTROPORATED METADATA
        % ==========================================================
        
        cache.metadata_match = true;
        cache.metadata_mismatch_message = '';
        
        if isfinite(cache.electroporated_column)
        
            fields_to_compare = { ...
                'PositionX_um', ...
                'PositionY_um', ...
                'PositionZ', ...
                'OpticalZoom', ...
                'NumPlanes'};
        
            mismatch_lines = {};
        
            for f = 1:numel(fields_to_compare)
        
                field_name = ...
                    fields_to_compare{f};
        
                gcamp_value = ...
                    metadata.gcamp_plane.(field_name){m};
        
                electroporated_value = ...
                    metadata.electroporated_plane.(field_name){m};
        
                if isempty(gcamp_value) || ...
                        isempty(electroporated_value)
        
                    mismatch_lines{end+1,1} = ...
                        sprintf( ...
                            ['%s:\n' ...
                             '    GCaMP          : %s\n' ...
                             '    Electroporated : %s\n' ...
                             '    Reason         : missing metadata value'], ...
                            field_name, ...
                            mat2str(gcamp_value), ...
                            mat2str(electroporated_value));
        
                    continue;
                end
        
                if ~isequal(gcamp_value, electroporated_value)
        
                    mismatch_lines{end+1,1} = ...
                        sprintf( ...
                            ['%s:\n' ...
                             '    GCaMP          : %s\n' ...
                             '    Electroporated : %s\n' ...
                             '    Reason         : different values'], ...
                            field_name, ...
                            mat2str(gcamp_value), ...
                            mat2str(electroporated_value));
                end
            end
        
            if ~isempty(mismatch_lines)
        
                cache.metadata_match = false;
        
                cache.metadata_mismatch_message = ...
                    strjoin(mismatch_lines, newline);
            end
        end

        % ==========================================================
        % Racine de l'analyse
        % ==========================================================

        root_folder_m = ...
            gcamp_root_folders{m};

        migrate_old_electroporated_results( ...
            root_folder_m);

        cache.filePath_electroporated = ...
            fullfile( ...
                root_folder_m, ...
                'results_electroporated.mat');

        cache.filePath_gcamp = ...
            fullfile( ...
                root_folder_m, ...
                'results_gcamp.mat');

        % ==========================================================
        % Plans GCaMP
        % ==========================================================

        cache.gcamp_planes = ...
            current_gcamp_folders_group{m};

        if ~iscell(cache.gcamp_planes)

            cache.gcamp_planes = ...
                {cache.gcamp_planes};
        end

        cache.nPlanes = ...
            numel(cache.gcamp_planes);

        if cache.nPlanes == 0

            fprintf( ...
                'Group %d: no GCaMP planes, skipped.\n', ...
                m);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Vérification NumPlanes / suite2p
        % ==========================================================

        metadata_nplanes = ...
            metadata.gcamp_plane.NumPlanes{m};

        if cache.nPlanes ~= metadata_nplanes

            warning( ...
                'process_electroporated_pass1:Suite2pPlaneMismatch', ...
                ['Recording group %d skipped.\n' ...
                 'GCaMP suite2p planes : %d\n' ...
                 'GCaMP XML NumPlanes  : %d'], ...
                m, ...
                cache.nPlanes, ...
                metadata_nplanes);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Initialiser slots
        % ==========================================================

        for f = 1:numel(fields_electroporated_all)

            data = ensure_electroporated_plane_cell( ...
                data, ...
                fields_electroporated_all{f}, ...
                m, ...
                cache.nPlanes);
        end

        for f = 1:numel(gcamp_needed)

            data = ensure_local_gcamp_plane_cell( ...
                data, ...
                gcamp_needed{f}, ...
                m, ...
                cache.nPlanes);
        end

        % ==========================================================
        % Plans electroporated
        % ==========================================================

        cache.electroporated_planes = ...
            current_electroporated_folders_group{m};
        
        if ~isfinite(cache.electroporated_column)
        
            cache.electroporated_planes = ...
                cell(cache.nPlanes, 1);
        
            for p = 1:cache.nPlanes
                cache.electroporated_planes{p} = '';
            end
        
        elseif ~iscell(cache.electroporated_planes)
        
            cache.electroporated_planes = ...
                {cache.electroporated_planes};
        end
        % ==========================================================
        % Plans Green
        % ==========================================================

        cache.green_planes = ...
            current_green_folders_group{m};

        if ~iscell(cache.green_planes)

            cache.green_planes = ...
                {cache.green_planes};
        end

        % ==========================================================
        % Vérifier nombre de plans electroporated AVANT indexation
        % ==========================================================

        if numel(cache.electroporated_planes) ~= cache.nPlanes

            warning( ...
                'process_electroporated_pass1:ElectroporatedPlaneMismatch', ...
                ['Recording group %d skipped.\n' ...
                 'GCaMP suite2p planes         : %d\n' ...
                 'Electroporated suite2p planes: %d'], ...
                m, ...
                cache.nPlanes, ...
                numel(cache.electroporated_planes));

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Chemins electroporated
        % ==========================================================

        for p = 1:cache.nPlanes

            data.electroporated_plane. ...
                electroporated_fall_path_by_plane{m}{p} = ...
                cache.electroporated_planes{p};
        end

        % ==========================================================
        % Charger results_electroporated
        % ==========================================================

        if ~electroporated_group_already_complete( ...
                data, ...
                m, ...
                cache.nPlanes) && ...
                exist( ...
                    cache.filePath_electroporated, ...
                    'file') == 2

            loaded_electroporated = ...
                load( ...
                    cache.filePath_electroporated);

            loaded_electroporated = ...
                normalize_electroporated_loaded_fields( ...
                    loaded_electroporated);

            data = merge_loaded_electroporated_into_data( ...
                data, ...
                loaded_electroporated, ...
                fields_electroporated_saved, ...
                m, ...
                cache.nPlanes);
        end

        % ==========================================================
        % Charger results_gcamp
        % ==========================================================

        if ~local_gcamp_group_already_complete( ...
                data, ...
                gcamp_needed, ...
                m, ...
                cache.nPlanes) && ...
                exist( ...
                    cache.filePath_gcamp, ...
                    'file') == 2

            loaded_gcamp = ...
                load( ...
                    cache.filePath_gcamp);

            data = merge_loaded_local_gcamp_into_data( ...
                data, ...
                loaded_gcamp, ...
                gcamp_needed, ...
                m, ...
                cache.nPlanes);
        end

        % ==========================================================
        % Pas de fluorescence GCaMP
        % ==========================================================

        if ~local_gcamp_group_has_values( ...
                data, ...
                'F_gcamp_by_plane', ...
                m, ...
                cache.nPlanes)

            fprintf( ...
                ['Group %d: no GCaMP fluorescence, ' ...
                 'empty electroporated outputs stored.\n'], ...
                m);

            for p = 1:cache.nPlanes

                if ~electroporated_plane_has_meaningful_content( ...
                        data, ...
                        m, ...
                        p)

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end
            end

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Extraire GCaMP
        % ==========================================================

        cache.F_gcamp_by_plane = ...
            coerce_to_plane_cell_local( ...
                data.gcamp_plane.F_gcamp_by_plane{m}, ...
                cache.nPlanes);

        cache.gcamp_props_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'gcamp_props_by_plane', ...
                m, ...
                cache.nPlanes);

        cache.iscell_gcamp_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'iscell_gcamp_by_plane', ...
                m, ...
                cache.nPlanes);

        cache.gcamp_mask_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'gcamp_mask_by_plane', ...
                m, ...
                cache.nPlanes);

        cache.gcamp_mask_false_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'gcamp_mask_false_by_plane', ...
                m, ...
                cache.nPlanes);

        % ==========================================================
        % Cache plans
        % ==========================================================

        cache.planes = ...
            cell(cache.nPlanes, 1);

        for p = 1:cache.nPlanes

            cache.planes{p} = struct( ...
                'process_plane', false, ...
                'requires_roi_extraction', false, ...
                'meanImg_channels', [], ...
                'aligned_image', [], ...
                'npy_file_path', '', ...
                'gcamp_reference_meanImg', [], ...
                'metadata_match', cache.metadata_match, ...
                'metadata_mismatch_message', ...
                    cache.metadata_mismatch_message, ...
                'error_message', '');
        end

        cache.valid_group = true;

        processing_cache{m} = cache;
    end

    % ==============================================================
    % PASS 1B
    % ==============================================================

    for m = 1:numFolders

        cache = ...
            processing_cache{m};

        if isempty(cache) || ...
                cache.skip_group || ...
                ~cache.valid_group

            continue;
        end

        % ==========================================================
        % TSeries
        % ==========================================================

        current_gcamp_TSeries_path_m = ...
            TSeries_paths{m, 1};

        fprintf( ...
            'GCaMP TSeries          : %s\n', ...
            current_gcamp_TSeries_path_m);

        current_electroporated_TSeries_path_m = ...
            current_electroporated_TSeries_path{m};

        fprintf( ...
            'Electroporated TSeries : %s\n', ...
            current_electroporated_TSeries_path_m);

        % ==========================================================
        % METADATA MISMATCH
        %
        % Si les résultats electroporated sont déjà complets ET
        % que l'extraction est toujours à jour par rapport au NPY,
        % le mismatch est seulement affiché en warning.
        %
        % Aucun choix utilisateur.
        % Aucun alignement / Cellpose.
        %
        % Sinon, le choix 1 / 0 est demandé.
        % ==========================================================

        if ~cache.metadata_match

            existing_results_are_complete_and_current = ...
                electroporated_group_results_complete_and_current_pass1( ...
                    data, ...
                    m, ...
                    cache.nPlanes);

            if existing_results_are_complete_and_current

                warning( ...
                    'process_electroporated_pass1:MetadataMismatch', ...
                    ['============================================================\n' ...
                     'GCaMP / ELECTROPORATED METADATA MISMATCH\n' ...
                     '============================================================\n\n' ...
                     '%s\n\n' ...
                     'GCaMP and electroporated metadata do not match.\n\n' ...
                     'Existing electroporated results are complete and up to date.\n' ...
                     'Existing results retained.\n' ...
                     'Alignment / Cellpose skipped.'], ...
                    cache.metadata_mismatch_message);
            
                input( ...
                    sprintf([ ...
                        '\nPress Enter to continue.\n']), ...
                    's');
            
                for p = 1:cache.nPlanes
            
                    cache.planes{p}.process_plane = false;
            
                    cache.planes{p}.requires_roi_extraction = false;
                end
            
                processing_cache{m} = ...
                    cache;
            
                continue;
            end

            choice = input( ...
                sprintf([ ...
                    '\n============================================================\n' ...
                    'GCaMP / ELECTROPORATED METADATA MISMATCH\n' ...
                    '============================================================\n\n' ...
                    '%s\n\n' ...
                    'GCaMP and electroporated metadata do not match.\n\n' ...
                    'Press 1 to continue with alignment / Cellpose anyway.\n' ...
                    'Press 0 to keep existing data and skip this recording.\n> '], ...
                    cache.metadata_mismatch_message), ...
                's');

            user_accepted_metadata_mismatch = ...
                strcmp(strtrim(choice), '1');

            if ~user_accepted_metadata_mismatch

                fprintf( ...
                    ['Existing results retained.\n' ...
                     'Cellpose/alignment skipped.\n']);

                for p = 1:cache.nPlanes

                    cache.planes{p}.process_plane = false;

                    cache.planes{p}.requires_roi_extraction = false;
                end

                processing_cache{m} = ...
                    cache;

                continue;
            end

            fprintf( ...
                ['Metadata mismatch accepted. ' ...
                 'Continuing with alignment / Cellpose.\n']);
        end

        % ==========================================================
        % Plans
        % ==========================================================

        for p = 1:cache.nPlanes

            fprintf( ...
                '\nCellpose | Group %d/%d | Plane %d/%d\n', ...
                m, ...
                numFolders, ...
                p, ...
                cache.nPlanes);

            electroporated_plane_folder = ...
                cache.electroporated_planes{p};

            data.electroporated_plane. ...
                electroporated_fall_path_by_plane{m}{p} = ...
                electroporated_plane_folder;

            % ======================================================
            % Ops electroporated
            % ======================================================

            if ~electroporated_plane_slot_exists( ...
                    data, ...
                    'ops_suite2p_electroporated_by_plane', ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.electroporated_plane. ...
                        ops_suite2p_electroporated_by_plane{m}{p})

                if isempty(electroporated_plane_folder)

                    data.electroporated_plane. ...
                        ops_suite2p_electroporated_by_plane{m}{p} = [];

                else

                    data.electroporated_plane. ...
                        ops_suite2p_electroporated_by_plane{m}{p} = ...
                        load_ops_only( ...
                            electroporated_plane_folder);
                end
            end

            electroporated_results_already_complete = ...
                electroporated_plane_has_meaningful_content( ...
                    data, ...
                    m, ...
                    p);

            if electroporated_results_already_complete

                fprintf( ...
                    ['Plane %d: electroporated ROI results already ' ...
                     'complete. Aligned image will still be loaded.\n'], ...
                    p);
            end

            % ======================================================
            % GCaMP
            % ======================================================

            if isempty(cache.F_gcamp_by_plane{p})

                fprintf( ...
                    'Plane %d: empty GCaMP fluorescence.\n', ...
                    p);

                if ~electroporated_results_already_complete

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            if isempty(cache.gcamp_planes{p})

                fprintf( ...
                    'Plane %d: missing GCaMP folder.\n', ...
                    p);

                if ~electroporated_results_already_complete

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            % ======================================================
            % Output folder plan
            % ======================================================

            output_folders_m = ...
                gcamp_output_folders{m};

            if iscell(output_folders_m)

                output_folder_p = ...
                    output_folders_m{p};

            else

                output_folder_p = ...
                    output_folders_m;
            end

            % ======================================================
            % Green
            % ======================================================

            if isempty(cache.green_planes)

                green_plane_folder = '';

            elseif numel(cache.green_planes) >= p

                green_plane_folder = ...
                    cache.green_planes{p};

            else

                green_plane_folder = '';
            end

            % ======================================================
            % Cellpose
            % ======================================================

            try

                [ ...
                    meanImg_channels, ...
                    aligned_image_plane, ...
                    npy_file_path, ...
                    gcamp_reference_meanImg ...
                ] = ...
                    load_or_process_cellpose_TSeries( ...
                        cache.filePath_electroporated, ...
                        date_group_paths{m}, ...
                        cache.gcamp_planes{p}, ...
                        cache.electroporated_planes{p}, ...
                        green_plane_folder, ...
                        current_electroporated_TSeries_path_m, ...
                        output_folder_p);

            catch ME

                warning( ...
                    'process_electroporated_pass1:CellposeFailed', ...
                    ['Group %d plane %d failed while loading ' ...
                     'the aligned image: %s'], ...
                    m, ...
                    p, ...
                    ME.message);

                cache.planes{p}.error_message = ...
                    ME.message;

                if ~electroporated_results_already_complete

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            % ======================================================
            % Store outputs
            % ======================================================

            cache.planes{p}.meanImg_channels = ...
                meanImg_channels;

            cache.planes{p}.aligned_image = ...
                aligned_image_plane;

            cache.planes{p}.npy_file_path = ...
                npy_file_path;

            cache.planes{p}.gcamp_reference_meanImg = ...
                gcamp_reference_meanImg;

            data.electroporated_plane. ...
                meanImg_channels_by_plane{m}{p} = ...
                meanImg_channels;

            data.electroporated_plane. ...
                alignedImgs_electroporated{m}{p} = ...
                aligned_image_plane;

            data.electroporated_plane. ...
                cellpose_npy_file_path_by_plane{m}{p} = ...
                npy_file_path;

            data.electroporated_plane. ...
                gcamp_reference_meanImg_by_plane{m}{p} = ...
                gcamp_reference_meanImg;

            cache.planes{p}.metadata_match = ...
                cache.metadata_match;

            cache.planes{p}.metadata_mismatch_message = ...
                cache.metadata_mismatch_message;

            % ======================================================
            % NPY
            % ======================================================

            if isempty(npy_file_path)

                fprintf( ...
                    ['Plane %d: empty NPY path. ' ...
                     'Aligned image was nevertheless stored.\n'], ...
                    p);

                if electroporated_results_already_complete

                    cache.planes{p}.process_plane = false;

                else

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            if exist(npy_file_path, 'file') ~= 2

                fprintf( ...
                    ['Plane %d: NPY not found. ' ...
                     'Aligned image was nevertheless stored:\n%s\n'], ...
                    p, ...
                    npy_file_path);

                if electroporated_results_already_complete

                    cache.planes{p}.process_plane = false;

                else

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            fprintf( ...
                'Plane %d: Cellpose NPY ready:\n%s\n', ...
                p, ...
                npy_file_path);

            % ======================================================
            % Extraction actuelle ?
            % ======================================================

            extraction_is_current = ...
                is_electroporated_roi_extraction_current_pass1( ...
                    data, ...
                    m, ...
                    p, ...
                    npy_file_path);

            if extraction_is_current

                cache.planes{p}.process_plane = false;

                cache.planes{p}.requires_roi_extraction = false;

                fprintf( ...
                    ['Plane %d: electroporated ROI extraction already ' ...
                     'up to date. Existing results retained.\n'], ...
                    p);

                continue;
            end

            cache.planes{p}.requires_roi_extraction = true;

            cache.planes{p}.process_plane = true;

            fprintf( ...
                ['Plane %d: electroporated ROI extraction ' ...
                 'required.\n'], ...
                p);
        end

        processing_cache{m} = ...
            cache;
    end
end


% ========================================================================
% GROUP RESULTS COMPLETE AND CURRENT
%
% Permet de vérifier l'état de l'extraction AVANT d'appeler
% load_or_process_cellpose_TSeries.
%
% La signature NPY sauvegardée contient déjà le chemin du fichier NPY.
% On compare donc directement ce fichier au fichier actuel.
% ========================================================================

function tf = electroporated_group_results_complete_and_current_pass1( ...
        data, ...
        m, ...
        nPlanes)

    tf = ...
        nPlanes > 0;

    for p = 1:nPlanes

        if ~electroporated_plane_has_meaningful_content( ...
                data, ...
                m, ...
                p)

            tf = false;
            return;
        end

        if ~is_electroporated_roi_current_saved_sig_pass1( ...
                data, ...
                m, ...
                p)

            tf = false;
            return;
        end
    end
end


% ========================================================================
% EXTRACTION CURRENT FROM SAVED SIGNATURE
% ========================================================================

function extraction_is_current = ...
        is_electroporated_roi_current_saved_sig_pass1( ...
            data, ...
            m, ...
            p)

    extraction_is_current = false;

    if ~isfield(data, 'electroporated_plane') || ...
            isempty(data.electroporated_plane) || ...
            ~isstruct(data.electroporated_plane)

        return;
    end

    electroporated_plane = ...
        data.electroporated_plane;

    % ==============================================================
    % Completed marker
    % ==============================================================

    if ~isfield( ...
            electroporated_plane, ...
            'roi_extraction_completed_by_plane')

        return;
    end

    completed_value = ...
        get_nested_plane_value_pass1( ...
            electroporated_plane. ...
                roi_extraction_completed_by_plane, ...
            m, ...
            p);

    if isempty(completed_value) || ...
            numel(completed_value) ~= 1

        return;
    end

    if islogical(completed_value)

        if ~completed_value
            return;
        end

    elseif isnumeric(completed_value)

        if ~isfinite(completed_value) || ...
                completed_value == 0

            return;
        end

    else

        return;
    end

    % ==============================================================
    % Required extraction outputs
    % ==============================================================

    required_fields = { ...
        'F_electroporated_by_plane', ...
        'mask_cellpose_by_plane', ...
        'props_cellpose_by_plane', ...
        'num_cells_mask_by_plane', ...
        'electroporated_match_mask_by_plane'};

    for k = 1:numel(required_fields)

        field_name = ...
            required_fields{k};

        if ~isfield( ...
                electroporated_plane, ...
                field_name)

            return;
        end

        if ~nested_plane_entry_exists_pass1( ...
                electroporated_plane.(field_name), ...
                m, ...
                p)

            return;
        end
    end

    % ==============================================================
    % Signature NPY sauvegardée
    % ==============================================================

    if ~isfield( ...
            electroporated_plane, ...
            'roi_extraction_npy_signature_by_plane')

        return;
    end

    saved_signature = ...
        get_nested_plane_value_pass1( ...
            electroporated_plane. ...
                roi_extraction_npy_signature_by_plane, ...
            m, ...
            p);

    if isempty(saved_signature) || ...
            ~isstruct(saved_signature) || ...
            ~isfield(saved_signature, 'path') || ...
            isempty(saved_signature.path)

        return;
    end

    % ==============================================================
    % Relire directement le fichier NPY correspondant
    % ==============================================================

    current_signature = ...
        get_npy_file_signature_pass1( ...
            saved_signature.path);

    if isempty(current_signature)
        return;
    end

    extraction_is_current = ...
        compare_npy_signatures_pass1( ...
            saved_signature, ...
            current_signature);
end


% ========================================================================
% MIGRATION OLD RESULTS
% ========================================================================

function migrate_old_electroporated_results(root_folder)

    old_file = ...
        fullfile( ...
            root_folder, ...
            'results_blue.mat');

    new_file = ...
        fullfile( ...
            root_folder, ...
            'results_electroporated.mat');

    if exist(old_file, 'file') ~= 2
        return;
    end

    if exist(new_file, 'file') ~= 2

        loaded = ...
            load(old_file);

        loaded = ...
            normalize_electroporated_loaded_fields( ...
                loaded);

        save( ...
            new_file, ...
            '-struct', ...
            'loaded', ...
            '-v7.3');

        fprintf( ...
            ['Migrated old electroporated results:\n' ...
             '%s\n'], ...
            new_file);
    end

    if exist(new_file, 'file') == 2

        delete(old_file);

        fprintf( ...
            'Old results file removed.\n');
    end
end


% ========================================================================
% NORMALIZE OLD ELECTROPORATED FIELDS
% ========================================================================

function loaded = normalize_electroporated_loaded_fields(loaded)

    old_names = { ...
        'F_blue_by_plane', ...
        'blue_match_mask_by_plane', ...
        'ops_suite2p_blue_by_plane', ...
        'blue_fall_path_by_plane'};

    new_names = { ...
        'F_electroporated_by_plane', ...
        'electroporated_match_mask_by_plane', ...
        'ops_suite2p_electroporated_by_plane', ...
        'electroporated_fall_path_by_plane'};

    for i = 1:numel(old_names)

        if isfield( ...
                loaded, ...
                old_names{i})

            if ~isfield( ...
                    loaded, ...
                    new_names{i})

                loaded.(new_names{i}) = ...
                    loaded.(old_names{i});
            end

            loaded = ...
                rmfield( ...
                    loaded, ...
                    old_names{i});
        end
    end
end


% ========================================================================
% GCAMP FIELD
% ========================================================================

function vals = get_gcamp_field_as_plane_cell( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    vals = ...
        cell(nPlanes, 1);

    if isfield(data, 'gcamp_plane') && ...
            isfield( ...
                data.gcamp_plane, ...
                fieldName) && ...
            numel( ...
                data.gcamp_plane.(fieldName)) >= m

        vals = ...
            coerce_to_plane_cell_local( ...
                data.gcamp_plane.(fieldName){m}, ...
                nPlanes);
    end
end


% ========================================================================
% ELECTROPORATED GROUP COMPLETE
% ========================================================================

function tf = electroporated_group_already_complete( ...
        data, ...
        m, ...
        nPlanes)

    tf = ...
        nPlanes > 0;

    for p = 1:nPlanes

        if ~electroporated_plane_has_meaningful_content( ...
                data, ...
                m, ...
                p)

            tf = false;
            return;
        end
    end
end


% ========================================================================
% GCAMP GROUP COMPLETE
% ========================================================================

function tf = local_gcamp_group_already_complete( ...
        data, ...
        fields, ...
        m, ...
        nPlanes)

    tf = ...
        nPlanes > 0;

    for p = 1:nPlanes

        for f = 1:numel(fields)

            name = ...
                fields{f};

            if ~local_gcamp_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.gcamp_plane.(name){m}{p})

                tf = false;
                return;
            end
        end
    end
end


% ========================================================================
% INIT ELECTROPORATED STRUCT
% ========================================================================

function data = init_electroporated_plane_struct_if_needed( ...
        data, ...
        numFolders, ...
        fields)

    if nargin < 1 || ...
            isempty(data)

        data = struct();
    end

    % ==============================================================
    % Migration data.blue_plane
    % ==============================================================

    if isfield(data, 'blue_plane')

        if ~isfield( ...
                data, ...
                'electroporated_plane') || ...
                ~isstruct( ...
                    data.electroporated_plane)

            data.electroporated_plane = ...
                data.blue_plane;
        end

        data = ...
            rmfield( ...
                data, ...
                'blue_plane');
    end

    if ~isfield( ...
            data, ...
            'electroporated_plane') || ...
            ~isstruct( ...
                data.electroporated_plane)

        data.electroporated_plane = ...
            struct();
    end

    data.electroporated_plane = ...
        normalize_electroporated_loaded_fields( ...
            data.electroporated_plane);

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield( ...
                data.electroporated_plane, ...
                name) || ...
                ~iscell( ...
                    data.electroporated_plane.(name))

            data.electroporated_plane.(name) = ...
                cell(numFolders, 1);

        elseif numel( ...
                data.electroporated_plane.(name)) < numFolders

            old = ...
                data.electroporated_plane.(name);

            tmp = ...
                cell(numFolders, 1);

            tmp(1:numel(old)) = ...
                old(:);

            data.electroporated_plane.(name) = ...
                tmp;
        end
    end
end


% ========================================================================
% INIT GCAMP
% ========================================================================

function data = init_gcamp_plane_struct_if_needed_local( ...
        data, ...
        numFolders, ...
        fields)

    if ~isfield(data, 'gcamp_plane') || ...
            ~isstruct(data.gcamp_plane)

        data.gcamp_plane = ...
            struct();
    end

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield( ...
                data.gcamp_plane, ...
                name) || ...
                ~iscell( ...
                    data.gcamp_plane.(name))

            data.gcamp_plane.(name) = ...
                cell(numFolders, 1);

        elseif numel( ...
                data.gcamp_plane.(name)) < numFolders

            old = ...
                data.gcamp_plane.(name);

            tmp = ...
                cell(numFolders, 1);

            tmp(1:numel(old)) = ...
                old(:);

            data.gcamp_plane.(name) = ...
                tmp;
        end
    end
end


% ========================================================================
% ENSURE ELECTROPORATED
% ========================================================================

function data = ensure_electroporated_plane_cell( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    if ~isfield( ...
            data.electroporated_plane, ...
            fieldName)

        data.electroporated_plane.(fieldName) = ...
            cell(m, 1);
    end

    if numel( ...
            data.electroporated_plane.(fieldName)) < m

        tmp = ...
            cell(m, 1);

        tmp( ...
            1:numel( ...
                data.electroporated_plane.(fieldName))) = ...
            data.electroporated_plane.(fieldName)(:);

        data.electroporated_plane.(fieldName) = ...
            tmp;
    end

    if isempty( ...
            data.electroporated_plane.(fieldName){m}) || ...
            ~iscell( ...
                data.electroporated_plane.(fieldName){m})

        data.electroporated_plane.(fieldName){m} = ...
            cell(nPlanes, 1);

    elseif numel( ...
            data.electroporated_plane.(fieldName){m}) ~= nPlanes

        old = ...
            data.electroporated_plane.(fieldName){m};

        tmp = ...
            cell(nPlanes, 1);

        n = ...
            min( ...
                numel(old), ...
                nPlanes);

        tmp(1:n) = ...
            old(1:n);

        data.electroporated_plane.(fieldName){m} = ...
            tmp;
    end
end


% ========================================================================
% ENSURE GCAMP
% ========================================================================

function data = ensure_local_gcamp_plane_cell( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    if ~isfield( ...
            data.gcamp_plane, ...
            fieldName)

        data.gcamp_plane.(fieldName) = ...
            cell(m, 1);
    end

    if numel( ...
            data.gcamp_plane.(fieldName)) < m

        tmp = ...
            cell(m, 1);

        tmp( ...
            1:numel( ...
                data.gcamp_plane.(fieldName))) = ...
            data.gcamp_plane.(fieldName)(:);

        data.gcamp_plane.(fieldName) = ...
            tmp;
    end

    if isempty( ...
            data.gcamp_plane.(fieldName){m}) || ...
            ~iscell( ...
                data.gcamp_plane.(fieldName){m})

        data.gcamp_plane.(fieldName){m} = ...
            cell(nPlanes, 1);

    elseif numel( ...
            data.gcamp_plane.(fieldName){m}) ~= nPlanes

        old = ...
            data.gcamp_plane.(fieldName){m};

        tmp = ...
            cell(nPlanes, 1);

        n = ...
            min( ...
                numel(old), ...
                nPlanes);

        tmp(1:n) = ...
            old(1:n);

        data.gcamp_plane.(fieldName){m} = ...
            tmp;
    end
end


% ========================================================================
% COERCE PLANE CELL
% ========================================================================

function out = coerce_to_plane_cell_local( ...
        val, ...
        nPlanes)

    out = ...
        cell(nPlanes, 1);

    if isempty(val)
        return;
    end

    if iscell(val)

        n = ...
            min( ...
                numel(val), ...
                nPlanes);

        out(1:n) = ...
            val(1:n);

    elseif nPlanes >= 1

        out{1} = ...
            val;
    end
end


% ========================================================================
% MERGE ELECTROPORATED
% ========================================================================

function data = merge_loaded_electroporated_into_data( ...
        data, ...
        loaded, ...
        fields, ...
        m, ...
        nPlanes)

    loaded = ...
        normalize_electroporated_loaded_fields( ...
            loaded);

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield(loaded, name)
            continue;
        end

        vals = ...
            coerce_to_plane_cell_local( ...
                loaded.(name), ...
                nPlanes);

        for p = 1:nPlanes

            if ~electroporated_plane_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.electroporated_plane.(name){m}{p})

                data.electroporated_plane.(name){m}{p} = ...
                    vals{p};
            end
        end
    end
end


% ========================================================================
% MERGE GCAMP
% ========================================================================

function data = merge_loaded_local_gcamp_into_data( ...
        data, ...
        loaded, ...
        fields, ...
        m, ...
        nPlanes)

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield(loaded, name)
            continue;
        end

        vals = ...
            coerce_to_plane_cell_local( ...
                loaded.(name), ...
                nPlanes);

        for p = 1:nPlanes

            if ~local_gcamp_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.gcamp_plane.(name){m}{p})

                data.gcamp_plane.(name){m}{p} = ...
                    vals{p};
            end
        end
    end
end


% ========================================================================
% ELECTROPORATED SLOT
% ========================================================================

function tf = electroporated_plane_slot_exists( ...
        data, ...
        fieldName, ...
        m, ...
        p)

    tf = ...
        isfield( ...
            data, ...
            'electroporated_plane') && ...
        isfield( ...
            data.electroporated_plane, ...
            fieldName) && ...
        numel( ...
            data.electroporated_plane.(fieldName)) >= m && ...
        iscell( ...
            data.electroporated_plane.(fieldName){m}) && ...
        numel( ...
            data.electroporated_plane.(fieldName){m}) >= p;
end


% ========================================================================
% GCAMP SLOT
% ========================================================================

function tf = local_gcamp_slot_exists( ...
        data, ...
        fieldName, ...
        m, ...
        p)

    tf = ...
        isfield( ...
            data, ...
            'gcamp_plane') && ...
        isfield( ...
            data.gcamp_plane, ...
            fieldName) && ...
        numel( ...
            data.gcamp_plane.(fieldName)) >= m && ...
        iscell( ...
            data.gcamp_plane.(fieldName){m}) && ...
        numel( ...
            data.gcamp_plane.(fieldName){m}) >= p;
end


% ========================================================================
% GCAMP HAS VALUES
% ========================================================================

function tf = local_gcamp_group_has_values( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    tf = false;

    if ~isfield( ...
            data, ...
            'gcamp_plane') || ...
            ~isfield( ...
                data.gcamp_plane, ...
                fieldName) || ...
            numel( ...
                data.gcamp_plane.(fieldName)) < m

        return;
    end

    vals = ...
        coerce_to_plane_cell_local( ...
            data.gcamp_plane.(fieldName){m}, ...
            nPlanes);

    tf = ...
        any( ...
            ~cellfun( ...
                @isempty, ...
                vals));
end


% ========================================================================
% ELECTROPORATED CONTENT
% ========================================================================

function tf = electroporated_plane_has_meaningful_content( ...
        data, ...
        m, ...
        p)

    required = { ...
        'F_electroporated_by_plane', ...
        'mask_cellpose_by_plane', ...
        'props_cellpose_by_plane', ...
        'outlines_x_cellpose_by_plane', ...
        'outlines_y_cellpose_by_plane', ...
        'num_cells_mask_by_plane'};

    tf = true;

    for i = 1:numel(required)

        name = ...
            required{i};

        if ~electroporated_plane_slot_exists( ...
                data, ...
                name, ...
                m, ...
                p) || ...
                isempty( ...
                    data.electroporated_plane.(name){m}{p})

            tf = false;
            return;
        end
    end
end


% ========================================================================
% EMPTY ELECTROPORATED
% ========================================================================

function data = set_empty_electroporated_plane( ...
        data, ...
        m, ...
        p)

    data.electroporated_plane. ...
        matched_gcamp_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        matched_cellpose_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        gcamp_unmatched_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        cellpose_unmatched_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        num_cells_mask_by_plane{m}{p} = 0;

    data.electroporated_plane. ...
        mask_cellpose_by_plane{m}{p} = ...
        false(0,0,0);

    data.electroporated_plane. ...
        props_cellpose_by_plane{m}{p} = ...
        struct([]);

    data.electroporated_plane. ...
        outlines_x_cellpose_by_plane{m}{p} = {};

    data.electroporated_plane. ...
        outlines_y_cellpose_by_plane{m}{p} = {};

    data.electroporated_plane. ...
        F_electroporated_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        electroporated_match_mask_by_plane{m}{p} = ...
        false(0,1);

    data.electroporated_plane. ...
        ops_suite2p_electroporated_by_plane{m}{p} = [];
end


% ========================================================================
% ELECTROPORATED ROI EXTRACTION CURRENT - PASS 1
% ========================================================================

function extraction_is_current = ...
        is_electroporated_roi_extraction_current_pass1( ...
            data, ...
            m, ...
            p, ...
            npy_file_path)

    extraction_is_current = false;

    if ~isfield(data, 'electroporated_plane') || ...
            isempty(data.electroporated_plane) || ...
            ~isstruct(data.electroporated_plane)

        return;
    end

    electroporated_plane = ...
        data.electroporated_plane;

    % ==============================================================
    % Completed marker
    % ==============================================================

    if ~isfield( ...
            electroporated_plane, ...
            'roi_extraction_completed_by_plane')

        return;
    end

    completed_value = ...
        get_nested_plane_value_pass1( ...
            electroporated_plane. ...
                roi_extraction_completed_by_plane, ...
            m, ...
            p);

    if isempty(completed_value) || ...
            numel(completed_value) ~= 1

        return;
    end

    if islogical(completed_value)

        if ~completed_value
            return;
        end

    elseif isnumeric(completed_value)

        if ~isfinite(completed_value) || ...
                completed_value == 0

            return;
        end

    else

        return;
    end

    % ==============================================================
    % Required extraction outputs
    % ==============================================================

    required_fields = { ...
        'F_electroporated_by_plane', ...
        'mask_cellpose_by_plane', ...
        'props_cellpose_by_plane', ...
        'num_cells_mask_by_plane', ...
        'electroporated_match_mask_by_plane'};

    for k = 1:numel(required_fields)

        field_name = ...
            required_fields{k};

        if ~isfield( ...
                electroporated_plane, ...
                field_name)

            return;
        end

        if ~nested_plane_entry_exists_pass1( ...
                electroporated_plane.(field_name), ...
                m, ...
                p)

            return;
        end
    end

    % ==============================================================
    % NPY signature
    % ==============================================================

    if ~isfield( ...
            electroporated_plane, ...
            'roi_extraction_npy_signature_by_plane')

        return;
    end

    saved_signature = ...
        get_nested_plane_value_pass1( ...
            electroporated_plane. ...
                roi_extraction_npy_signature_by_plane, ...
            m, ...
            p);

    current_signature = ...
        get_npy_file_signature_pass1( ...
            npy_file_path);

    if isempty(saved_signature) || ...
            isempty(current_signature)

        return;
    end

    extraction_is_current = ...
        compare_npy_signatures_pass1( ...
            saved_signature, ...
            current_signature);
end


% ========================================================================
% NESTED PLANE ENTRY EXISTS - PASS 1
% ========================================================================

function tf = ...
        nested_plane_entry_exists_pass1( ...
            values, ...
            m, ...
            p)

    tf = false;

    if ~iscell(values) || ...
            m < 1 || ...
            m > numel(values)

        return;
    end

    values_m = ...
        values{m};

    if ~iscell(values_m) || ...
            p < 1 || ...
            p > numel(values_m)

        return;
    end

    tf = true;
end


% ========================================================================
% GET NESTED PLANE VALUE - PASS 1
% ========================================================================

function value = ...
        get_nested_plane_value_pass1( ...
            values, ...
            m, ...
            p)

    value = [];

    if ~nested_plane_entry_exists_pass1( ...
            values, ...
            m, ...
            p)

        return;
    end

    value = ...
        values{m}{p};
end


% ========================================================================
% NPY FILE SIGNATURE - PASS 1
% ========================================================================

function signature = ...
        get_npy_file_signature_pass1( ...
            npy_file_path)

    signature = [];

    if isempty(npy_file_path) || ...
            ~(ischar(npy_file_path) || ...
              isstring(npy_file_path))

        return;
    end

    npy_file_path = ...
        char(npy_file_path);

    if ~isfile(npy_file_path)
        return;
    end

    file_info = ...
        dir(npy_file_path);

    if isempty(file_info)
        return;
    end

    signature = struct();

    signature.path = ...
        npy_file_path;

    signature.bytes = ...
        file_info(1).bytes;

    signature.datenum = ...
        file_info(1).datenum;
end


% ========================================================================
% COMPARE NPY SIGNATURES - PASS 1
% ========================================================================

function signatures_match = ...
        compare_npy_signatures_pass1( ...
            saved_signature, ...
            current_signature)

    signatures_match = false;

    if ~isstruct(saved_signature) || ...
            ~isstruct(current_signature)

        return;
    end

    required_fields = { ...
        'path', ...
        'bytes', ...
        'datenum'};

    for k = 1:numel(required_fields)

        field_name = ...
            required_fields{k};

        if ~isfield(saved_signature, field_name) || ...
                ~isfield(current_signature, field_name)

            return;
        end
    end

    saved_path = ...
        char( ...
            string( ...
                saved_signature.path));

    current_path = ...
        char( ...
            string( ...
                current_signature.path));

    same_path = ...
        strcmpi( ...
            saved_path, ...
            current_path);

    same_size = ...
        isequal( ...
            double(saved_signature.bytes), ...
            double(current_signature.bytes));

    saved_date = ...
        double( ...
            saved_signature.datenum);

    current_date = ...
        double( ...
            current_signature.datenum);

    same_date = ...
        isfinite(saved_date) && ...
        isfinite(current_date) && ...
        abs(saved_date - current_date) < 1e-10;

    signatures_match = ...
        same_path && ...
        same_size && ...
        same_date;
end