function selected_groups = process_selected_groups( ...
        selected_groups, ...
        include_electroporated, ...
        automatic_selection, ...
        processing_mode)

    if nargin < 1 || isempty(selected_groups)
        return;
    end

    if nargin < 2
        include_electroporated = true;
    end

    if nargin < 4 || isempty(processing_mode)
        processing_mode = 'interactive';
    end

    processing_mode = ...
        char(string(processing_mode));

    if ~ismember( ...
            lower(processing_mode), ...
            {'load_only', 'interactive'})

        error( ...
            'processing_mode must be ''load_only'' or ''interactive''.');
    end

    %% ============================================================
    % Flatten all animals from all types into one job list.
    %
    % This avoids processing each type with a separate PARFOR and therefore
    % keeps the worker pool busy even when a type contains only 1-2 animals.
    % =============================================================

    type_names = ...
        fieldnames(selected_groups);

    job_types = {};
    job_indices = [];
    job_groups = {};
    job_automatic_selection = {};

    for t = 1:numel(type_names)

        current_type = ...
            type_names{t};

        groups = ...
            selected_groups.(current_type);

        current_automatic_selection = ...
            automatic_selection.(current_type);

        for k = 1:numel(groups)

            job_types{end + 1, 1} = ... %#ok<AGROW>
                current_type;

            job_indices(end + 1, 1) = ... %#ok<AGROW>
                k;

            job_groups{end + 1, 1} = ... %#ok<AGROW>
                groups(k);

            job_automatic_selection{end + 1, 1} = ... %#ok<AGROW>
                current_automatic_selection;
        end
    end

    numJobs = ...
        numel(job_groups);

    if numJobs == 0
        return;
    end

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('SELECTED GROUP PROCESSING\n');
    fprintf('Animals: %d\n', numJobs);
    fprintf('Mode   : %s\n', processing_mode);
    fprintf('============================================================\n');

    %% ============================================================
    % LOAD ONLY
    %
    % Parallel stage:
    %   mean images
    %   ZSeries load
    %   motion load
    %   stim
    %   GCaMP
    %   electroporated saved-results load/status inspection
    %   combined + overview when everything is already complete
    %
    % Sequential fallback:
    %   ONLY animals for which Cellpose/ROI data are missing/outdated.
    %
    % This preserves the user's desired behavior:
    % load_only loads when possible, but missing Cellpose detection is still
    % processed rather than silently skipped.
    % =============================================================

    if strcmpi(processing_mode, 'load_only')

        pool = ...
            gcp('nocreate');

        if numJobs > 1 && isempty(pool)

            fprintf('Starting parallel pool...\n');

            pool = ...
                parpool;
        end

        if numJobs > 1 && ~isempty(pool)

            parfor_workers = ...
                min(pool.NumWorkers, numJobs);

        else

            parfor_workers = 0;
        end

        if parfor_workers > 0

            fprintf( ...
                'LOAD ONLY parallel stage: %d workers\n', ...
                parfor_workers);

        else

            fprintf( ...
                'LOAD ONLY stage: sequential (single animal)\n');
        end

        processed_groups = ...
            cell(numJobs, 1);

        needs_motion_processing = ...
            false(numJobs, 1);

        needs_electroporated_processing = ...
            false(numJobs, 1);

        parfor (j = 1:numJobs, parfor_workers)

            current_group = ...
                job_groups{j};

            current_automatic_selection = ...
                job_automatic_selection{j};

            [ ...
                current_group, ...
                ~, ...
                current_needs ...
            ] = ...
                process_single_animal_base( ...
                    current_group, ...
                    include_electroporated, ...
                    current_automatic_selection, ...
                    'load_only');

            current_needs_any = ...
                current_needs.motion || ...
                current_needs.electroporated;

            if ~current_needs_any

                current_group = ...
                    finalize_single_animal_processing( ...
                        current_group, ...
                        include_electroporated, ...
                        current_automatic_selection);
            end

            processed_groups{j} = ...
                current_group;

            needs_motion_processing(j) = ...
                current_needs.motion;

            needs_electroporated_processing(j) = ...
                current_needs.electroporated;
        end

        %% ========================================================
        % Sequential Cellpose fallback only when required.
        %
        % We deliberately keep this outside PARFOR because Cellpose / user
        % validation / metadata mismatch dialogs must never run concurrently.
        % =========================================================

        fallback_jobs = ...
            find( ...
                needs_motion_processing | ...
                needs_electroporated_processing);

        if ~isempty(fallback_jobs)

            fprintf('\n');
            fprintf('============================================================\n');
            fprintf('SEQUENTIAL FALLBACK REQUIRED\n');
            fprintf('Animals requiring processing: %d/%d\n', ...
                numel(fallback_jobs), ...
                numJobs);
            fprintf('============================================================\n');
        end

        for ii = 1:numel(fallback_jobs)

            j = ...
                fallback_jobs(ii);

            current_group = ...
                processed_groups{j};

            current_automatic_selection = ...
                job_automatic_selection{j};

            paths = ...
                current_group.paths;

            data = ...
                current_group.data;

            metadata = ...
                current_group.metadata;

            fprintf('\n');
            fprintf('------------------------------------------------------------\n');
            fprintf('Sequential missing-data fallback %d/%d\n', ...
                ii, ...
                numel(fallback_jobs));
            fprintf('Type  : %s\n', job_types{j});
            fprintf('Animal: %s\n', ...
                char(string(current_group.animal)));
            fprintf('------------------------------------------------------------\n');

            if needs_motion_processing(j)

                sampling_rate_group = ...
                    metadata.gcamp_plane.SamplingRatePlane;

                [motion, camFolders] = ...
                    load_or_process_movie( ...
                        paths.TSeries(:, 1), ...
                        paths.gcamp_output, ...
                        5, ...
                        sampling_rate_group, ...
                        current_group.animal, ...
                        data, ...
                        'interactive');

                data.motion = ...
                    motion;

                paths.camera = ...
                    camFolders;

                current_group.paths = ...
                    paths;
            end

            if needs_electroporated_processing(j)

            [processing_cache, data] = ...
                process_electroporated_pass1( ...
                    paths.gcamp_root, ...
                    paths.gcamp_output, ...
                    include_electroporated, ...
                    paths.date, ...
                    paths.TSeries, ...
                    paths.suite2p, ...
                    metadata, ...
                    data, ...
                    'process_missing');

            [electroporated_plane, data] = ...
                process_electroporated_pass2( ...
                    processing_cache, ...
                    paths.gcamp_output, ...
                    data.gcamp_plane.meanImgs_gcamp, ...
                    data);

            data.electroporated_plane = ...
                electroporated_plane;

            end

            current_group.data = ...
                data;

            current_group = ...
                finalize_single_animal_processing( ...
                    current_group, ...
                    include_electroporated, ...
                    current_automatic_selection);

            processed_groups{j} = ...
                current_group;
        end

    else

        %% ========================================================
        % INTERACTIVE
        %
        % The whole animal remains sequential because ZSeries, motion and
        % Cellpose can all display UI / request user input.
        % =========================================================

        processed_groups = ...
            cell(numJobs, 1);

        for j = 1:numJobs

            current_group = ...
                job_groups{j};

            current_automatic_selection = ...
                job_automatic_selection{j};

            fprintf('\n');
            fprintf('============================================================\n');
            fprintf('INTERACTIVE ANIMAL %d/%d\n', j, numJobs);
            fprintf('Type  : %s\n', job_types{j});
            fprintf('Animal: %s\n', ...
                char(string(current_group.animal)));
            fprintf('============================================================\n');

            [ ...
                current_group, ...
                processing_cache, ...
                ~ ...
            ] = ...
                process_single_animal_base( ...
                    current_group, ...
                    include_electroporated, ...
                    current_automatic_selection, ...
                    'interactive');

            paths = ...
                current_group.paths;

            data = ...
                current_group.data;

            [electroporated_plane, data] = ...
                process_electroporated_pass2( ...
                    processing_cache, ...
                    paths.gcamp_output, ...
                    data.gcamp_plane.meanImgs_gcamp, ...
                    data);

            data.electroporated_plane = ...
                electroporated_plane;

            current_group.data = ...
                data;

            current_group = ...
                finalize_single_animal_processing( ...
                    current_group, ...
                    include_electroporated, ...
                    current_automatic_selection);

            processed_groups{j} = ...
                current_group;
        end
    end

    %% ============================================================
    % Reinsert into selected_groups
    % =============================================================

    for j = 1:numJobs

        current_type = ...
            job_types{j};

        current_index = ...
            job_indices(j);

        selected_groups.(current_type)(current_index) = ...
            processed_groups{j};
    end

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('SELECTED GROUP PROCESSING COMPLETED\n');
    fprintf('Animals: %d\n', numJobs);
    fprintf('============================================================\n');
end
