function [processing_cache, data] = process_electroporated_pass1( ...
    gcamp_output_folders, ...
    include_electroporated, ...
    date_group_paths, ...
    TSeries_paths, ...
    suite2p_folders, ...
    metadata, ...
    data)

    numFolders = numel(gcamp_output_folders);

    % ==============================================================
    % Colonnes attendues
    %
    %   1 = GCaMP
    %   2 = canal potentiel electroporated
    %   3 = canal potentiel electroporated
    %   4 = Green
    % ==============================================================

    current_gcamp_folders_group = ...
        get_path_column( ...
            suite2p_folders, ...
            1, ...
            numFolders);

    current_green_folders_group = ...
        get_path_column( ...
            suite2p_folders, ...
            4, ...
            numFolders);

    % ==============================================================
    % Déterminer automatiquement le canal electroporated
    %
    % Fonction externe :
    % get_electroporated_channel.m
    % ==============================================================

    [ ...
        current_electroporated_TSeries_path, ...
        current_electroporated_folders_group, ...
        electroporated_column_by_group ...
    ] = ...
        get_electroporated_channel( ...
            TSeries_paths, ...
            suite2p_folders, ...
            numFolders);

    % ==============================================================
    % Champs electroporated sauvegardés
    % ==============================================================

    fields_electroporated_saved = { ...
        'matched_gcamp_idx_by_plane', ...
        'matched_cellpose_idx_by_plane', ...
        'gcamp_unmatched_idx_by_plane', ...
        'cellpose_unmatched_idx_by_plane', ...
        'num_cells_mask_by_plane', ...
        'mask_cellpose_by_plane', ...
        'props_cellpose_by_plane', ...
        'outlines_x_cellpose_by_plane', ...
        'outlines_y_cellpose_by_plane', ...
        'F_electroporated_by_plane', ...
        'electroporated_match_mask_by_plane'};

    fields_electroporated_memory = { ...
        'ops_suite2p_electroporated_by_plane', ...
        'electroporated_fall_path_by_plane', ...
        'meanImg_channels_by_plane', ...
        'alignedImgs_electroporated', ...
        'cellpose_npy_file_path_by_plane', ...
        'gcamp_reference_meanImg_by_plane'};

    fields_electroporated_all = [ ...
        fields_electroporated_saved, ...
        fields_electroporated_memory];

    % ==============================================================
    % Champs GCaMP nécessaires
    % ==============================================================

    gcamp_needed = { ...
        'stat_by_plane', ...
        'F_gcamp_by_plane', ...
        'gcamp_props_by_plane', ...
        'outlines_gcampx_by_plane', ...
        'outlines_gcampy_by_plane', ...
        'iscell_gcamp_by_plane', ...
        'gcamp_mask_by_plane', ...
        'gcamp_props_false_by_plane', ...
        'outlines_gcampx_false_by_plane', ...
        'outlines_gcampy_false_by_plane', ...
        'gcamp_mask_false_by_plane'};

    % ==============================================================
    % Initialisation
    % ==============================================================

    data = init_electroporated_plane_struct_if_needed( ...
        data, ...
        numFolders, ...
        fields_electroporated_all);

    data = init_gcamp_plane_struct_if_needed_local( ...
        data, ...
        numFolders, ...
        gcamp_needed);

    processing_cache = ...
        cell(numFolders, 1);

    fprintf('\n============================================================\n');
    fprintf('ELECTROPORATED PASS 1: CELLPOSE PREPARATION\n');
    fprintf('============================================================\n');

    % ==============================================================
    % PASS 1A
    % ==============================================================

    for m = 1:numFolders

        cache = struct();

        cache.valid_group = false;
        cache.skip_group = false;
        cache.nPlanes = 0;

        cache.electroporated_column = NaN;

        cache.filePath_electroporated = '';
        cache.filePath_gcamp = '';

        cache.gcamp_planes = {};
        cache.electroporated_planes = {};
        cache.green_planes = {};

        cache.F_gcamp_by_plane = {};
        cache.gcamp_props_by_plane = {};
        cache.iscell_gcamp_by_plane = {};
        cache.gcamp_mask_by_plane = {};
        cache.gcamp_mask_false_by_plane = {};

        cache.has_new_electroporated_data = false;

        cache.metadata_match = true;
        cache.metadata_mismatch_message = '';

        cache.planes = {};

        fprintf( ...
            '\nPreparing recording group %d/%d...\n', ...
            m, ...
            numFolders);

        % ==========================================================
        % Canal electroporated
        % ==========================================================

        if m <= numel(electroporated_column_by_group)

            cache.electroporated_column = ...
                electroporated_column_by_group(m);
        end

        if ~isfinite(cache.electroporated_column)

            warning( ...
                'process_electroporated_pass1:NoElectroporatedChannel', ...
                ['Recording group %d: no electroporated channel ' ...
                 'detected. Recording skipped.'], ...
                m);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Processing désactivé
        % ==========================================================

        if include_electroporated ~= 1

            fprintf( ...
                ['Group %d: electroporated processing ' ...
                 'disabled.\n'], ...
                m);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % VALIDATE GCAMP / ELECTROPORATED METADATA
        %
        % IMPORTANT:
        % The mismatch is checked and DISPLAYED immediately, but it does
        % NOT block PASS 1A / PASS 1B here. The result is stored in cache
        % and will only be enforced AFTER load_or_process_cellpose_TSeries
        % has been called and all of its outputs have been stored.
        % ==========================================================

        [cache.metadata_match, cache.metadata_mismatch_message] = ...
            validate_gcamp_electroporated_metadata( ...
                metadata, ...
                m);

        % ==========================================================
        % Output folder
        % ==========================================================

        if m > numel(gcamp_output_folders) || ...
                isempty(gcamp_output_folders{m}) || ...
                ~iscell(gcamp_output_folders{m}) || ...
                isempty(gcamp_output_folders{m}{1})

            fprintf( ...
                'Group %d: invalid output folder, skipped.\n', ...
                m);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        root_folder_m = ...
            fileparts( ...
                gcamp_output_folders{m}{1});

        % ==========================================================
        % Migration ancien results_blue.mat
        % ==========================================================

        migrate_old_electroporated_results( ...
            root_folder_m);

        cache.filePath_electroporated = ...
            fullfile( ...
                root_folder_m, ...
                'results_electroporated.mat');

        cache.filePath_gcamp = ...
            fullfile( ...
                root_folder_m, ...
                'results_gcamp.mat');

        % ==========================================================
        % GCaMP planes
        % ==========================================================

        if m <= numel(current_gcamp_folders_group)

            cache.gcamp_planes = ...
                current_gcamp_folders_group{m};
        end

        cache.nPlanes = ...
            numel(cache.gcamp_planes);

        if cache.nPlanes == 0

            fprintf( ...
                'Group %d: no GCaMP planes, skipped.\n', ...
                m);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Vérification supplémentaire NumPlanes / suite2p
        %
        % Normalement déjà garanti par les métadonnées, mais permet
        % d'éviter de poursuivre si le contenu suite2p ne correspond
        % pas au nombre de plans annoncé.
        % ==========================================================

        metadata_nplanes = ...
            get_metadata_recording_value( ...
                metadata.gcamp_plane, ...
                'NumPlanes', ...
                m);

        metadata_nplanes = ...
            convert_metadata_numeric( ...
                metadata_nplanes);

        if isempty(metadata_nplanes) || ...
                ~isscalar(metadata_nplanes) || ...
                cache.nPlanes ~= metadata_nplanes

            warning( ...
                'process_electroporated_pass1:Suite2pPlaneMismatch', ...
                ['Recording group %d skipped.\n' ...
                 'GCaMP suite2p planes : %d\n' ...
                 'GCaMP XML NumPlanes  : %s'], ...
                m, ...
                cache.nPlanes, ...
                metadata_value_to_string(metadata_nplanes));

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Initialiser slots
        % ==========================================================

        for f = 1:numel(fields_electroporated_all)

            data = ensure_electroporated_plane_cell( ...
                data, ...
                fields_electroporated_all{f}, ...
                m, ...
                cache.nPlanes);
        end

        for f = 1:numel(gcamp_needed)

            data = ensure_local_gcamp_plane_cell( ...
                data, ...
                gcamp_needed{f}, ...
                m, ...
                cache.nPlanes);
        end

        % ==========================================================
        % Chemins electroporated
        % ==========================================================

        for p = 1:cache.nPlanes

            electroporated_path_p = ...
                get_electroporated_plane_folder( ...
                    current_electroporated_folders_group, ...
                    m, ...
                    p);

            if isempty(electroporated_path_p)

                data.electroporated_plane. ...
                    electroporated_fall_path_by_plane{m}{p} = '';

            else

                data.electroporated_plane. ...
                    electroporated_fall_path_by_plane{m}{p} = ...
                    char(electroporated_path_p);
            end
        end

        % ==========================================================
        % Charger results_electroporated
        % ==========================================================

        if ~electroporated_group_already_complete( ...
                data, ...
                m, ...
                cache.nPlanes) && ...
                exist( ...
                    cache.filePath_electroporated, ...
                    'file') == 2

            loaded_electroporated = ...
                load( ...
                    cache.filePath_electroporated);

            loaded_electroporated = ...
                normalize_electroporated_loaded_fields( ...
                    loaded_electroporated);

            data = merge_loaded_electroporated_into_data( ...
                data, ...
                loaded_electroporated, ...
                fields_electroporated_saved, ...
                m, ...
                cache.nPlanes);
        end

        % ==========================================================
        % Charger results_gcamp
        % ==========================================================

        if ~local_gcamp_group_already_complete( ...
                data, ...
                gcamp_needed, ...
                m, ...
                cache.nPlanes) && ...
                exist( ...
                    cache.filePath_gcamp, ...
                    'file') == 2

            loaded_gcamp = ...
                load( ...
                    cache.filePath_gcamp);

            data = merge_loaded_local_gcamp_into_data( ...
                data, ...
                loaded_gcamp, ...
                gcamp_needed, ...
                m, ...
                cache.nPlanes);
        end

        % ==========================================================
        % Pas de fluorescence GCaMP
        % ==========================================================

        if ~local_gcamp_group_has_values( ...
                data, ...
                'F_gcamp_by_plane', ...
                m, ...
                cache.nPlanes)

            fprintf( ...
                ['Group %d: no GCaMP fluorescence, ' ...
                 'empty electroporated outputs stored.\n'], ...
                m);

            for p = 1:cache.nPlanes

                if ~electroporated_plane_has_meaningful_content( ...
                        data, ...
                        m, ...
                        p)

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end
            end

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Extraire GCaMP
        % ==========================================================

        cache.F_gcamp_by_plane = ...
            coerce_to_plane_cell_local( ...
                data.gcamp_plane.F_gcamp_by_plane{m}, ...
                cache.nPlanes);

        cache.gcamp_props_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'gcamp_props_by_plane', ...
                m, ...
                cache.nPlanes);

        cache.iscell_gcamp_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'iscell_gcamp_by_plane', ...
                m, ...
                cache.nPlanes);

        cache.gcamp_mask_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'gcamp_mask_by_plane', ...
                m, ...
                cache.nPlanes);

        cache.gcamp_mask_false_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'gcamp_mask_false_by_plane', ...
                m, ...
                cache.nPlanes);

        % ==========================================================
        % Electroporated / Green planes
        % ==========================================================

        cache.electroporated_planes = ...
            get_group_entry( ...
                current_electroporated_folders_group, ...
                m);

        cache.green_planes = ...
            get_group_entry( ...
                current_green_folders_group, ...
                m);

        % ==========================================================
        % Nombre de plans electroporated
        % ==========================================================

        if isempty(cache.electroporated_planes) || ...
                numel(cache.electroporated_planes) ~= cache.nPlanes

            warning( ...
                'process_electroporated_pass1:ElectroporatedPlaneMismatch', ...
                ['Recording group %d skipped.\n' ...
                 'GCaMP suite2p planes         : %d\n' ...
                 'Electroporated suite2p planes: %d'], ...
                m, ...
                cache.nPlanes, ...
                numel(cache.electroporated_planes));

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Cache plans
        % ==========================================================

        cache.planes = ...
            cell(cache.nPlanes, 1);

        for p = 1:cache.nPlanes

            cache.planes{p} = struct( ...
                'process_plane', false, ...
                'meanImg_channels', [], ...
                'aligned_image', [], ...
                'npy_file_path', '', ...
                'gcamp_reference_meanImg', [], ...
                'metadata_match', cache.metadata_match, ...
                'metadata_mismatch_message', cache.metadata_mismatch_message, ...
                'error_message', '');
        end

        cache.valid_group = true;

        processing_cache{m} = cache;
    end

    % ==============================================================
    % PASS 1B
    % ==============================================================

    for m = 1:numFolders

        cache = ...
            processing_cache{m};

        if isempty(cache) || ...
                cache.skip_group || ...
                ~cache.valid_group

            continue;
        end

        fprintf( ...
            '\nCellpose | Recording group %d/%d | %d planes\n', ...
            m, ...
            numFolders, ...
            cache.nPlanes);

        % ==========================================================
        % Metadata mismatch decision: ONCE per recording
        % ==========================================================

        user_accepted_metadata_mismatch = false;

        if ~cache.metadata_match

            choice = input( ...
                sprintf([ ...
                '\n============================================================\n' ...
                'GCaMP / ELECTROPORATED METADATA MISMATCH\n' ...
                '============================================================\n\n' ...
                '%s\n\n' ...
                '============================================================\n' ...
                'The Cellpose alignment can still be performed.\n' ...
                'Electroporated ROI extraction will be skipped.\n\n' ...
                'Press 1 to continue.\n' ...
                'Press 0 to skip this recording.\n> '], ...
                cache.metadata_mismatch_message), ...
                's');

            user_accepted_metadata_mismatch = ...
                strcmp(strtrim(choice), '1');

            if ~user_accepted_metadata_mismatch

                cache.skip_group = true;
                processing_cache{m} = cache;
                continue;
            end
        end

        for p = 1:cache.nPlanes

            fprintf( ...
                '\nCellpose | Group %d/%d | Plane %d/%d\n', ...
                m, ...
                numFolders, ...
                p, ...
                cache.nPlanes);

            % ======================================================
            % Electroporated plane folder
            % ======================================================

            electroporated_plane_folder = ...
                get_electroporated_plane_folder( ...
                    current_electroporated_folders_group, ...
                    m, ...
                    p);

            if isempty(electroporated_plane_folder)

                data.electroporated_plane. ...
                    electroporated_fall_path_by_plane{m}{p} = '';

            else

                data.electroporated_plane. ...
                    electroporated_fall_path_by_plane{m}{p} = ...
                    char(electroporated_plane_folder);
            end

            % ======================================================
            % Ops electroporated
            % ======================================================

            if ~electroporated_plane_slot_exists( ...
                    data, ...
                    'ops_suite2p_electroporated_by_plane', ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.electroporated_plane. ...
                        ops_suite2p_electroporated_by_plane{m}{p})

                if isempty(electroporated_plane_folder)

                    data.electroporated_plane. ...
                        ops_suite2p_electroporated_by_plane{m}{p} = [];

                else

                    data.electroporated_plane. ...
                        ops_suite2p_electroporated_by_plane{m}{p} = ...
                        load_ops_only( ...
                            electroporated_plane_folder);
                end
            end

            % ======================================================
            % Résultats déjà présents ?
            % ======================================================

            electroporated_results_already_complete = ...
                electroporated_plane_has_meaningful_content( ...
                    data, ...
                    m, ...
                    p);

            if electroporated_results_already_complete

                fprintf( ...
                    ['Plane %d: electroporated ROI results already ' ...
                     'complete. Aligned image will still be loaded.\n'], ...
                    p);
            end

            % ======================================================
            % Vérifier GCaMP
            % ======================================================

            if p > numel(cache.F_gcamp_by_plane) || ...
                    isempty(cache.F_gcamp_by_plane{p})

                fprintf( ...
                    'Plane %d: empty GCaMP fluorescence.\n', ...
                    p);

                if ~electroporated_results_already_complete

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            if p > numel(cache.gcamp_planes) || ...
                    isempty(cache.gcamp_planes{p})

                fprintf( ...
                    'Plane %d: missing GCaMP folder.\n', ...
                    p);

                if ~electroporated_results_already_complete

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            % ======================================================
            % TSeries electroporated
            % ======================================================

            current_electroporated_TSeries_path_m = ...
                get_group_entry( ...
                    current_electroporated_TSeries_path, ...
                    m);

            % ======================================================
            % Charger / traiter Cellpose
            % ======================================================

            try

                [ ...
                    meanImg_channels, ...
                    aligned_image_plane, ...
                    npy_file_path, ...
                    gcamp_reference_meanImg ...
                ] = ...
                    load_or_process_cellpose_TSeries( ...
                        cache.filePath_electroporated, ...
                        date_group_paths{m}, ...
                        get_plane_path( ...
                            cache.gcamp_planes, ...
                            p), ...
                        get_plane_path( ...
                            cache.electroporated_planes, ...
                            p), ...
                        get_plane_path( ...
                            cache.green_planes, ...
                            p), ...
                        current_electroporated_TSeries_path_m, ...
                        get_plane_path( ...
                            gcamp_output_folders{m}, ...
                            p));

            catch ME

                warning( ...
                    'process_electroporated_pass1:CellposeFailed', ...
                    ['Group %d plane %d failed while loading ' ...
                     'the aligned image: %s'], ...
                    m, ...
                    p, ...
                    ME.message);

                cache.planes{p}.error_message = ...
                    ME.message;

                if ~electroporated_results_already_complete

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            % ======================================================
            % Store ALL load_or_process_cellpose_TSeries outputs
            % ======================================================

            cache.planes{p}.meanImg_channels = ...
                meanImg_channels;

            cache.planes{p}.aligned_image = ...
                aligned_image_plane;

            cache.planes{p}.npy_file_path = ...
                npy_file_path;

            cache.planes{p}.gcamp_reference_meanImg = ...
                gcamp_reference_meanImg;

            data.electroporated_plane. ...
                meanImg_channels_by_plane{m}{p} = ...
                meanImg_channels;

            data.electroporated_plane. ...
                alignedImgs_electroporated{m}{p} = ...
                aligned_image_plane;

            data.electroporated_plane. ...
                cellpose_npy_file_path_by_plane{m}{p} = ...
                npy_file_path;

            data.electroporated_plane. ...
                gcamp_reference_meanImg_by_plane{m}{p} = ...
                gcamp_reference_meanImg;

            % ======================================================
            % APPLY GCAMP / ELECTROPORATED METADATA VALIDATION
            %
            % The mismatch was already checked and displayed at the
            % beginning of PASS 1A. Only now, AFTER Cellpose loading and
            % AFTER all outputs have been stored, do we enforce it.
            % ======================================================

            cache.planes{p}.metadata_match = ...
                cache.metadata_match;

            cache.planes{p}.metadata_mismatch_message = ...
                cache.metadata_mismatch_message;

            if user_accepted_metadata_mismatch

                fprintf( ...
                    ['Group %d plane %d: Cellpose outputs stored. ' ...
                     'Metadata mismatch accepted.\n'], ...
                    m, ...
                    p);

                cache.planes{p}.process_plane = true;

                continue;
            end

            % ======================================================
            % NPY path
            % ======================================================

            if isempty(npy_file_path) || ...
                    ~(ischar(npy_file_path) || ...
                      isstring(npy_file_path))

                fprintf( ...
                    ['Plane %d: invalid or empty NPY path. ' ...
                     'Aligned image was nevertheless stored.\n'], ...
                    p);

                cache.planes{p}.npy_file_path = '';

                if electroporated_results_already_complete

                    cache.planes{p}.process_plane = false;

                else

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            npy_file_path = ...
                char(npy_file_path);

            cache.planes{p}.npy_file_path = ...
                npy_file_path;

            if exist(npy_file_path, 'file') ~= 2

                fprintf( ...
                    ['Plane %d: NPY not found. ' ...
                     'Aligned image was nevertheless stored:\n%s\n'], ...
                    p, ...
                    npy_file_path);

                if electroporated_results_already_complete

                    cache.planes{p}.process_plane = false;

                else

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            fprintf( ...
                'Plane %d: Cellpose NPY ready:\n%s\n', ...
                p, ...
                npy_file_path);

            % ======================================================
            % PASS 2 ?
            % ======================================================

            if electroporated_results_already_complete

                cache.planes{p}.process_plane = false;

                fprintf( ...
                    ['Plane %d: aligned image loaded. ' ...
                     'Electroporated ROI extraction remains skipped.\n'], ...
                    p);

            else

                cache.planes{p}.process_plane = true;

                fprintf( ...
                    ['Plane %d: aligned image loaded. ' ...
                     'Electroporated ROI extraction enabled.\n'], ...
                    p);
            end
        end

        processing_cache{m} = ...
            cache;
    end
end


% ========================================================================
% VALIDATE GCAMP / ELECTROPORATED METADATA
% ========================================================================

function [tf, message] = ...
        validate_gcamp_electroporated_metadata( ...
            metadata, ...
            m)

    tf = false;
    message = '';

    % ==============================================================
    % Vérifier structure metadata
    % ==============================================================

    if isempty(metadata) || ...
            ~isstruct(metadata) || ...
            ~isfield(metadata, 'gcamp_plane') || ...
            ~isfield(metadata, 'electroporated_plane')

        message = ...
            'GCaMP/electroporated metadata structure missing.';

        return;
    end

    fields_to_compare = { ...
        'PositionX_um', ...
        'PositionY_um', ...
        'PositionZ', ...
        'OpticalZoom', ...
        'NumPlanes'};

    mismatch_lines = {};

    % ==============================================================
    % Comparaison
    % ==============================================================

    for f = 1:numel(fields_to_compare)

        field_name = ...
            fields_to_compare{f};

        gcamp_value = ...
            get_metadata_recording_value( ...
                metadata.gcamp_plane, ...
                field_name, ...
                m);

        electroporated_value = ...
            get_metadata_recording_value( ...
                metadata.electroporated_plane, ...
                field_name, ...
                m);

        [values_match, reason] = ...
            metadata_values_match( ...
                gcamp_value, ...
                electroporated_value);

        if values_match
            continue;
        end

        mismatch_lines{end+1,1} = ...
            sprintf( ...
                ['%s:\n' ...
                 '    GCaMP          : %s\n' ...
                 '    Electroporated : %s\n' ...
                 '    Reason         : %s'], ...
                field_name, ...
                metadata_value_to_string(gcamp_value), ...
                metadata_value_to_string(electroporated_value), ...
                reason); %#ok<AGROW>
    end

    if ~isempty(mismatch_lines)

        message = ...
            strjoin( ...
                mismatch_lines, ...
                newline);

        return;
    end

    tf = true;
end


% ========================================================================
% GET ONE METADATA VALUE
% ========================================================================

function value = ...
        get_metadata_recording_value( ...
            branch, ...
            field_name, ...
            m)

    value = [];

    if isempty(branch) || ...
            ~isstruct(branch) || ...
            ~isfield(branch, field_name)

        return;
    end

    values = ...
        branch.(field_name);

    if isempty(values)
        return;
    end

    if iscell(values)

        if numel(values) < m
            return;
        end

        value = ...
            values{m};

    elseif isstring(values)

        if numel(values) < m
            return;
        end

        value = ...
            values(m);

    elseif isnumeric(values) || ...
            islogical(values)

        if isvector(values)

            if numel(values) < m
                return;
            end

            value = ...
                values(m);

        elseif size(values,1) >= m

            value = ...
                values(m,:);
        end

    else

        try

            if numel(values) >= m
                value = values(m);
            end

        catch
            value = [];
        end
    end
end


% ========================================================================
% COMPARE METADATA VALUES
% ========================================================================

function [tf, reason] = ...
        metadata_values_match( ...
            value1, ...
            value2)

    tf = false;
    reason = '';

    % ==============================================================
    % Valeur absente
    % ==============================================================

    if metadata_value_is_empty(value1) || ...
            metadata_value_is_empty(value2)

        reason = ...
            'missing metadata value';

        return;
    end

    % ==============================================================
    % Essayer une comparaison numérique
    % ==============================================================

    num1 = ...
        convert_metadata_numeric( ...
            value1);

    num2 = ...
        convert_metadata_numeric( ...
            value2);

    if ~isempty(num1) && ...
            ~isempty(num2)

        if ~isequal(size(num1), size(num2))

            reason = ...
                'different value dimensions';

            return;
        end

        tolerance = 1e-6;

        difference = ...
            abs( ...
                double(num1) - ...
                double(num2));

        scale = ...
            max( ...
                1, ...
                max( ...
                    abs( ...
                        [ ...
                            double(num1(:)); ...
                            double(num2(:)) ...
                        ])));

        tf = ...
            all( ...
                difference(:) <= ...
                tolerance * scale);

        if ~tf

            reason = ...
                'different numerical values';
        end

        return;
    end

    % ==============================================================
    % Comparaison string
    % ==============================================================

    str1 = ...
        string(value1);

    str2 = ...
        string(value2);

    tf = ...
        isequal( ...
            str1, ...
            str2);

    if ~tf

        reason = ...
            'different values';
    end
end


% ========================================================================
% METADATA VALUE EMPTY
% ========================================================================

function tf = metadata_value_is_empty(value)

    if isempty(value)

        tf = true;
        return;
    end

    if iscell(value)

        if isempty(value)

            tf = true;

        elseif numel(value) == 1

            tf = ...
                metadata_value_is_empty( ...
                    value{1});

        else

            tf = false;
        end

        return;
    end

    if isstring(value)

        tf = ...
            all( ...
                ismissing(value) | ...
                strlength(strtrim(value)) == 0);

        return;
    end

    if ischar(value)

        tf = ...
            isempty( ...
                strtrim(value));

        return;
    end

    if isnumeric(value)

        tf = ...
            isempty(value) || ...
            all(isnan(value(:)));

        return;
    end

    tf = false;
end


% ========================================================================
% CONVERT METADATA TO NUMERIC
% ========================================================================

function value_num = ...
        convert_metadata_numeric(value)

    value_num = [];

    if isempty(value)
        return;
    end

    % Cellule simple
    if iscell(value)

        if numel(value) == 1

            value_num = ...
                convert_metadata_numeric( ...
                    value{1});
        end

        return;
    end

    % Déjà numérique
    if isnumeric(value) || ...
            islogical(value)

        value_num = ...
            double(value);

        return;
    end

    % String / char
    if isstring(value) || ...
            ischar(value)

        value_string = ...
            strtrim( ...
                char( ...
                    string(value)));

        % ----------------------------------------------------------
        % Essayer d'abord une valeur simple
        % ----------------------------------------------------------

        simple_value = ...
            str2double(value_string);

        if ~isnan(simple_value)

            value_num = ...
                simple_value;

            return;
        end

        % ----------------------------------------------------------
        % Essayer un vecteur numérique
        %
        % Compatible par exemple avec :
        %   "[100 200 300]"
        %   "100, 200, 300"
        % ----------------------------------------------------------

        value_string = ...
            strrep( ...
                value_string, ...
                '[', ...
                '');

        value_string = ...
            strrep( ...
                value_string, ...
                ']', ...
                '');

        value_string = ...
            strrep( ...
                value_string, ...
                ',', ...
                ' ');

        tokens = ...
            regexp( ...
                value_string, ...
                '\s+', ...
                'split');

        tokens = ...
            tokens( ...
                ~cellfun( ...
                    @isempty, ...
                    tokens));

        if isempty(tokens)
            return;
        end

        nums = ...
            cellfun( ...
                @str2double, ...
                tokens);

        if all(~isnan(nums))

            value_num = ...
                nums;
        end
    end
end


% ========================================================================
% METADATA VALUE TO STRING
% ========================================================================

function txt = ...
        metadata_value_to_string(value)

    if metadata_value_is_empty(value)

        txt = '<missing>';
        return;
    end

    if iscell(value)

        if numel(value) == 1

            txt = ...
                metadata_value_to_string( ...
                    value{1});

        else

            parts = ...
                cellfun( ...
                    @metadata_value_to_string, ...
                    value, ...
                    'UniformOutput', ...
                    false);

            txt = ...
                ['{' strjoin(parts, ', ') '}'];
        end

        return;
    end

    if isnumeric(value) || ...
            islogical(value)

        txt = ...
            mat2str(value);

        return;
    end

    try

        txt = ...
            char( ...
                string(value));

    catch

        txt = ...
            '<unprintable>';
    end
end


% ========================================================================
% MIGRATION OLD RESULTS
% ========================================================================

function migrate_old_electroporated_results(root_folder)

    old_file = ...
        fullfile( ...
            root_folder, ...
            'results_blue.mat');

    new_file = ...
        fullfile( ...
            root_folder, ...
            'results_electroporated.mat');

    if exist(old_file, 'file') ~= 2
        return;
    end

    if exist(new_file, 'file') ~= 2

        loaded = ...
            load(old_file);

        loaded = ...
            normalize_electroporated_loaded_fields( ...
                loaded);

        save( ...
            new_file, ...
            '-struct', ...
            'loaded', ...
            '-v7.3');

        fprintf( ...
            ['Migrated old electroporated results:\n' ...
             '%s\n'], ...
            new_file);
    end

    if exist(new_file, 'file') == 2

        delete(old_file);

        fprintf( ...
            'Old results file removed.\n');
    end
end


% ========================================================================
% NORMALIZE OLD ELECTROPORATED FIELDS
% ========================================================================

function loaded = normalize_electroporated_loaded_fields(loaded)

    old_names = { ...
        'F_blue_by_plane', ...
        'blue_match_mask_by_plane', ...
        'ops_suite2p_blue_by_plane', ...
        'blue_fall_path_by_plane'};

    new_names = { ...
        'F_electroporated_by_plane', ...
        'electroporated_match_mask_by_plane', ...
        'ops_suite2p_electroporated_by_plane', ...
        'electroporated_fall_path_by_plane'};

    for i = 1:numel(old_names)

        if isfield( ...
                loaded, ...
                old_names{i})

            if ~isfield( ...
                    loaded, ...
                    new_names{i})

                loaded.(new_names{i}) = ...
                    loaded.(old_names{i});
            end

            loaded = ...
                rmfield( ...
                    loaded, ...
                    old_names{i});
        end
    end
end


% ========================================================================
% GET COLUMN
% ========================================================================

function column_data = get_path_column( ...
        paths_matrix, ...
        column_idx, ...
        numFolders)

    column_data = ...
        cell(numFolders, 1);

    if isempty(paths_matrix) || ...
            ~iscell(paths_matrix) || ...
            column_idx > size(paths_matrix, 2)

        return;
    end

    n = ...
        min( ...
            numFolders, ...
            size(paths_matrix, 1));

    column_data(1:n) = ...
        paths_matrix(1:n, column_idx);
end


% ========================================================================
% GROUP ENTRY
% ========================================================================

function out = get_group_entry( ...
        group_cell, ...
        m)

    out = {};

    if isempty(group_cell)
        return;
    end

    if iscell(group_cell)

        if m <= numel(group_cell)

            out = ...
                group_cell{m};
        end

    elseif ischar(group_cell) || ...
            isstring(group_cell)

        out = ...
            char(group_cell);
    end
end


% ========================================================================
% GCAMP FIELD
% ========================================================================

function vals = get_gcamp_field_as_plane_cell( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    vals = ...
        cell(nPlanes, 1);

    if isfield(data, 'gcamp_plane') && ...
            isfield( ...
                data.gcamp_plane, ...
                fieldName) && ...
            numel( ...
                data.gcamp_plane.(fieldName)) >= m

        vals = ...
            coerce_to_plane_cell_local( ...
                data.gcamp_plane.(fieldName){m}, ...
                nPlanes);
    end
end


% ========================================================================
% ELECTROPORATED GROUP COMPLETE
% ========================================================================

function tf = electroporated_group_already_complete( ...
        data, ...
        m, ...
        nPlanes)

    tf = ...
        nPlanes > 0;

    for p = 1:nPlanes

        if ~electroporated_plane_has_meaningful_content( ...
                data, ...
                m, ...
                p)

            tf = false;
            return;
        end
    end
end


% ========================================================================
% GCAMP GROUP COMPLETE
% ========================================================================

function tf = local_gcamp_group_already_complete( ...
        data, ...
        fields, ...
        m, ...
        nPlanes)

    tf = ...
        nPlanes > 0;

    for p = 1:nPlanes

        for f = 1:numel(fields)

            name = ...
                fields{f};

            if ~local_gcamp_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.gcamp_plane.(name){m}{p})

                tf = false;
                return;
            end
        end
    end
end


% ========================================================================
% INIT ELECTROPORATED STRUCT
% ========================================================================

function data = init_electroporated_plane_struct_if_needed( ...
        data, ...
        numFolders, ...
        fields)

    if nargin < 1 || ...
            isempty(data)

        data = struct();
    end

    % ==============================================================
    % Migration data.blue_plane
    % ==============================================================

    if isfield(data, 'blue_plane')

        if ~isfield( ...
                data, ...
                'electroporated_plane') || ...
                ~isstruct( ...
                    data.electroporated_plane)

            data.electroporated_plane = ...
                data.blue_plane;
        end

        data = ...
            rmfield( ...
                data, ...
                'blue_plane');
    end

    if ~isfield( ...
            data, ...
            'electroporated_plane') || ...
            ~isstruct( ...
                data.electroporated_plane)

        data.electroporated_plane = ...
            struct();
    end

    data.electroporated_plane = ...
        normalize_electroporated_loaded_fields( ...
            data.electroporated_plane);

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield( ...
                data.electroporated_plane, ...
                name) || ...
                ~iscell( ...
                    data.electroporated_plane.(name))

            data.electroporated_plane.(name) = ...
                cell(numFolders, 1);

        elseif numel( ...
                data.electroporated_plane.(name)) < numFolders

            old = ...
                data.electroporated_plane.(name);

            tmp = ...
                cell(numFolders, 1);

            tmp(1:numel(old)) = ...
                old(:);

            data.electroporated_plane.(name) = ...
                tmp;
        end
    end
end


% ========================================================================
% INIT GCAMP
% ========================================================================

function data = init_gcamp_plane_struct_if_needed_local( ...
        data, ...
        numFolders, ...
        fields)

    if ~isfield(data, 'gcamp_plane') || ...
            ~isstruct(data.gcamp_plane)

        data.gcamp_plane = ...
            struct();
    end

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield( ...
                data.gcamp_plane, ...
                name) || ...
                ~iscell( ...
                    data.gcamp_plane.(name))

            data.gcamp_plane.(name) = ...
                cell(numFolders, 1);

        elseif numel( ...
                data.gcamp_plane.(name)) < numFolders

            old = ...
                data.gcamp_plane.(name);

            tmp = ...
                cell(numFolders, 1);

            tmp(1:numel(old)) = ...
                old(:);

            data.gcamp_plane.(name) = ...
                tmp;
        end
    end
end


% ========================================================================
% ENSURE ELECTROPORATED
% ========================================================================

function data = ensure_electroporated_plane_cell( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    if ~isfield( ...
            data.electroporated_plane, ...
            fieldName)

        data.electroporated_plane.(fieldName) = ...
            cell(m, 1);
    end

    if numel( ...
            data.electroporated_plane.(fieldName)) < m

        tmp = ...
            cell(m, 1);

        tmp( ...
            1:numel( ...
                data.electroporated_plane.(fieldName))) = ...
            data.electroporated_plane.(fieldName)(:);

        data.electroporated_plane.(fieldName) = ...
            tmp;
    end

    if isempty( ...
            data.electroporated_plane.(fieldName){m}) || ...
            ~iscell( ...
                data.electroporated_plane.(fieldName){m})

        data.electroporated_plane.(fieldName){m} = ...
            cell(nPlanes, 1);

    elseif numel( ...
            data.electroporated_plane.(fieldName){m}) ~= nPlanes

        old = ...
            data.electroporated_plane.(fieldName){m};

        tmp = ...
            cell(nPlanes, 1);

        n = ...
            min( ...
                numel(old), ...
                nPlanes);

        tmp(1:n) = ...
            old(1:n);

        data.electroporated_plane.(fieldName){m} = ...
            tmp;
    end
end


% ========================================================================
% ENSURE GCAMP
% ========================================================================

function data = ensure_local_gcamp_plane_cell( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    if ~isfield( ...
            data.gcamp_plane, ...
            fieldName)

        data.gcamp_plane.(fieldName) = ...
            cell(m, 1);
    end

    if numel( ...
            data.gcamp_plane.(fieldName)) < m

        tmp = ...
            cell(m, 1);

        tmp( ...
            1:numel( ...
                data.gcamp_plane.(fieldName))) = ...
            data.gcamp_plane.(fieldName)(:);

        data.gcamp_plane.(fieldName) = ...
            tmp;
    end

    if isempty( ...
            data.gcamp_plane.(fieldName){m}) || ...
            ~iscell( ...
                data.gcamp_plane.(fieldName){m})

        data.gcamp_plane.(fieldName){m} = ...
            cell(nPlanes, 1);

    elseif numel( ...
            data.gcamp_plane.(fieldName){m}) ~= nPlanes

        old = ...
            data.gcamp_plane.(fieldName){m};

        tmp = ...
            cell(nPlanes, 1);

        n = ...
            min( ...
                numel(old), ...
                nPlanes);

        tmp(1:n) = ...
            old(1:n);

        data.gcamp_plane.(fieldName){m} = ...
            tmp;
    end
end


% ========================================================================
% COERCE PLANE CELL
% ========================================================================

function out = coerce_to_plane_cell_local( ...
        val, ...
        nPlanes)

    out = ...
        cell(nPlanes, 1);

    if isempty(val)
        return;
    end

    if iscell(val)

        n = ...
            min( ...
                numel(val), ...
                nPlanes);

        out(1:n) = ...
            val(1:n);

    elseif nPlanes >= 1

        out{1} = ...
            val;
    end
end


% ========================================================================
% MERGE ELECTROPORATED
% ========================================================================

function data = merge_loaded_electroporated_into_data( ...
        data, ...
        loaded, ...
        fields, ...
        m, ...
        nPlanes)

    loaded = ...
        normalize_electroporated_loaded_fields( ...
            loaded);

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield(loaded, name)
            continue;
        end

        vals = ...
            coerce_to_plane_cell_local( ...
                loaded.(name), ...
                nPlanes);

        for p = 1:nPlanes

            if ~electroporated_plane_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.electroporated_plane.(name){m}{p})

                data.electroporated_plane.(name){m}{p} = ...
                    vals{p};
            end
        end
    end
end


% ========================================================================
% MERGE GCAMP
% ========================================================================

function data = merge_loaded_local_gcamp_into_data( ...
        data, ...
        loaded, ...
        fields, ...
        m, ...
        nPlanes)

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield(loaded, name)
            continue;
        end

        vals = ...
            coerce_to_plane_cell_local( ...
                loaded.(name), ...
                nPlanes);

        for p = 1:nPlanes

            if ~local_gcamp_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.gcamp_plane.(name){m}{p})

                data.gcamp_plane.(name){m}{p} = ...
                    vals{p};
            end
        end
    end
end


% ========================================================================
% ELECTROPORATED SLOT
% ========================================================================

function tf = electroporated_plane_slot_exists( ...
        data, ...
        fieldName, ...
        m, ...
        p)

    tf = ...
        isfield( ...
            data, ...
            'electroporated_plane') && ...
        isfield( ...
            data.electroporated_plane, ...
            fieldName) && ...
        numel( ...
            data.electroporated_plane.(fieldName)) >= m && ...
        iscell( ...
            data.electroporated_plane.(fieldName){m}) && ...
        numel( ...
            data.electroporated_plane.(fieldName){m}) >= p;
end


% ========================================================================
% GCAMP SLOT
% ========================================================================

function tf = local_gcamp_slot_exists( ...
        data, ...
        fieldName, ...
        m, ...
        p)

    tf = ...
        isfield( ...
            data, ...
            'gcamp_plane') && ...
        isfield( ...
            data.gcamp_plane, ...
            fieldName) && ...
        numel( ...
            data.gcamp_plane.(fieldName)) >= m && ...
        iscell( ...
            data.gcamp_plane.(fieldName){m}) && ...
        numel( ...
            data.gcamp_plane.(fieldName){m}) >= p;
end


% ========================================================================
% GCAMP HAS VALUES
% ========================================================================

function tf = local_gcamp_group_has_values( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    tf = false;

    if ~isfield( ...
            data, ...
            'gcamp_plane') || ...
            ~isfield( ...
                data.gcamp_plane, ...
                fieldName) || ...
            numel( ...
                data.gcamp_plane.(fieldName)) < m

        return;
    end

    vals = ...
        coerce_to_plane_cell_local( ...
            data.gcamp_plane.(fieldName){m}, ...
            nPlanes);

    tf = ...
        any( ...
            ~cellfun( ...
                @isempty, ...
                vals));
end


% ========================================================================
% ELECTROPORATED CONTENT
% ========================================================================

function tf = electroporated_plane_has_meaningful_content( ...
        data, ...
        m, ...
        p)

    required = { ...
        'F_electroporated_by_plane', ...
        'mask_cellpose_by_plane', ...
        'props_cellpose_by_plane', ...
        'outlines_x_cellpose_by_plane', ...
        'outlines_y_cellpose_by_plane', ...
        'num_cells_mask_by_plane'};

    tf = true;

    for i = 1:numel(required)

        name = ...
            required{i};

        if ~electroporated_plane_slot_exists( ...
                data, ...
                name, ...
                m, ...
                p) || ...
                isempty( ...
                    data.electroporated_plane.(name){m}{p})

            tf = false;
            return;
        end
    end
end


% ========================================================================
% EMPTY ELECTROPORATED
% ========================================================================

function data = set_empty_electroporated_plane( ...
        data, ...
        m, ...
        p)

    data.electroporated_plane. ...
        matched_gcamp_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        matched_cellpose_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        gcamp_unmatched_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        cellpose_unmatched_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        num_cells_mask_by_plane{m}{p} = 0;

    data.electroporated_plane. ...
        mask_cellpose_by_plane{m}{p} = ...
        false(0,0,0);

    data.electroporated_plane. ...
        props_cellpose_by_plane{m}{p} = ...
        struct([]);

    data.electroporated_plane. ...
        outlines_x_cellpose_by_plane{m}{p} = {};

    data.electroporated_plane. ...
        outlines_y_cellpose_by_plane{m}{p} = {};

    data.electroporated_plane. ...
        F_electroporated_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        electroporated_match_mask_by_plane{m}{p} = ...
        false(0,1);

    data.electroporated_plane. ...
        ops_suite2p_electroporated_by_plane{m}{p} = [];
end


% ========================================================================
% GET ELECTROPORATED PLANE
% ========================================================================

function electroporated_plane_folder = ...
        get_electroporated_plane_folder( ...
            group, ...
            m, ...
            p)

    electroporated_plane_folder = '';

    if isempty(group) || ...
            m > numel(group) || ...
            isempty(group{m})

        return;
    end

    vals = ...
        group{m};

    if p <= numel(vals) && ...
            ~isempty(vals{p})

        electroporated_plane_folder = ...
            vals{p};
    end
end


% ========================================================================
% GET PLANE PATH
% ========================================================================

function plane_path = get_plane_path( ...
        paths_by_plane, ...
        p)

    plane_path = '';

    if isempty(paths_by_plane) || ...
            ~iscell(paths_by_plane) || ...
            p > numel(paths_by_plane) || ...
            isempty(paths_by_plane{p})

        return;
    end

    candidate = ...
        paths_by_plane{p};

    if ischar(candidate) || ...
            isstring(candidate)

        plane_path = ...
            char(candidate);
    end
end