function [processing_cache, data] = process_electroporated_pass1( ...
    gcamp_root_folders, ...
    gcamp_output_folders, ...
    include_electroporated, ...
    date_group_paths, ...
    TSeries_paths, ...
    suite2p_folders, ...
    metadata, ...
    data, ...
    cellpose_mode)

    if nargin < 9 || isempty(cellpose_mode)
        cellpose_mode = 'interactive';
    end

    include_electroporated_enabled = ...
        is_include_electroporated_enabled_pass1( ...
            include_electroporated);

    numFolders = numel(gcamp_root_folders);

    % ==============================================================
    % Colonnes suite2p
    %
    %   1 = GCaMP
    %   2 = canal potentiel electroporated
    %   3 = canal potentiel electroporated
    %   4 = Green
    % ==============================================================

    current_gcamp_folders_group = ...
        suite2p_folders(:, 1);

    current_green_folders_group = ...
        suite2p_folders(:, 4);

    % ==============================================================
    % Déterminer automatiquement le canal electroporated
    % ==============================================================

    [ ...
        current_electroporated_TSeries_path, ...
        current_electroporated_folders_group, ...
        electroporated_column_by_group ...
    ] = ...
        get_electroporated_channel( ...
            TSeries_paths, ...
            suite2p_folders, ...
            numFolders);

    % ==============================================================
    % Champs electroporated sauvegardés
    % ==============================================================

    fields_electroporated_saved = { ...
        'matched_gcamp_idx_by_plane', ...
        'matched_cellpose_idx_by_plane', ...
        'gcamp_unmatched_idx_by_plane', ...
        'cellpose_unmatched_idx_by_plane', ...
        'num_cells_mask_by_plane', ...
        'mask_cellpose_by_plane', ...
        'props_cellpose_by_plane', ...
        'outlines_x_cellpose_by_plane', ...
        'outlines_y_cellpose_by_plane', ...
        'F_electroporated_by_plane', ...
        'electroporated_match_mask_by_plane', ...
        'roi_extraction_completed_by_plane', ...
        'roi_extraction_npy_signature_by_plane'};

    fields_electroporated_memory = { ...
        'ops_suite2p_electroporated_by_plane', ...
        'electroporated_fall_path_by_plane', ...
        'meanImg_channels_by_plane', ...
        'alignedImgs_electroporated', ...
        'cellpose_npy_file_path_by_plane', ...
        'gcamp_reference_meanImg_by_plane'};

    fields_electroporated_all = [ ...
        fields_electroporated_saved, ...
        fields_electroporated_memory];

    % ==============================================================
    % Champs GCaMP nécessaires
    %
    % stat_false / iscell_false sont inclus pour pouvoir distinguer :
    %   - aucun ROI rejeté -> champs false vides valides
    %   - ROI rejetés présents -> masks false requis
    % ==============================================================

    gcamp_needed = { ...
        'stat_by_plane', ...
        'F_gcamp_by_plane', ...
        'gcamp_props_by_plane', ...
        'outlines_gcampx_by_plane', ...
        'outlines_gcampy_by_plane', ...
        'iscell_gcamp_by_plane', ...
        'gcamp_mask_by_plane', ...
        'stat_false_by_plane', ...
        'iscell_false_by_plane', ...
        'gcamp_props_false_by_plane', ...
        'outlines_gcampx_false_by_plane', ...
        'outlines_gcampy_false_by_plane', ...
        'gcamp_mask_false_by_plane'};

    % ==============================================================
    % Initialisation
    % ==============================================================

    data = init_electroporated_plane_struct_if_needed( ...
        data, ...
        numFolders, ...
        fields_electroporated_all);

    data = init_gcamp_plane_struct_if_needed_local( ...
        data, ...
        numFolders, ...
        gcamp_needed);

    processing_cache = cell(numFolders, 1);

    fprintf('\n============================================================\n');
    fprintf('ELECTROPORATED PASS 1: CELLPOSE PREPARATION\n');
    fprintf('Mode: %s\n', char(string(cellpose_mode)));
    fprintf('============================================================\n');

    % ==============================================================
    % PASS 1A
    % ==============================================================

    for m = 1:numFolders

        cache = struct();

        cache.valid_group = false;
        cache.skip_group = false;
        cache.nPlanes = 0;

        cache.electroporated_column = NaN;

        cache.filePath_electroporated = '';
        cache.filePath_gcamp = '';

        cache.gcamp_planes = {};
        cache.electroporated_planes = {};
        cache.green_planes = {};

        cache.F_gcamp_by_plane = {};
        cache.gcamp_props_by_plane = {};
        cache.iscell_gcamp_by_plane = {};
        cache.gcamp_mask_by_plane = {};
        cache.gcamp_mask_false_by_plane = {};

        cache.has_new_electroporated_data = false;

        % In load_only, this flag tells the outer orchestrator that
        % existing Cellpose / electroporated ROI results are missing or
        % outdated and that a sequential interactive fallback is required.
        cache.requires_processing = false;

        cache.metadata_match = true;
        cache.metadata_mismatch_message = '';

        cache.planes = {};

        fprintf( ...
            '\nPreparing recording group %d/%d...\n', ...
            m, ...
            numFolders);

        % ==========================================================
        % Processing désactivé
        % ==========================================================

        if ~include_electroporated_enabled

            fprintf( ...
                ['Group %d: electroporated processing ' ...
                 'disabled.\n'], ...
                m);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Canal electroporated
        %
        % IMPORTANT :
        % l'absence de canal electroporated Suite2p ne doit PAS
        % provoquer le skip du recording.
        %
        % load_or_process_cellpose_TSeries pourra ensuite chercher :
        %   1) Electroporated TSeries
        %   2) Single images
        % ==========================================================

        cache.electroporated_column = ...
            electroporated_column_by_group(m);

        if ~isfinite(cache.electroporated_column)

            fprintf( ...
                ['Group %d: no electroporated Suite2p channel detected.\n' ...
                 'Continuing with empty electroporated paths.\n' ...
                 'TSeries / Single images will still be checked.\n'], ...
                m);
        end

        % ==========================================================
        % VALIDATE GCAMP / ELECTROPORATED METADATA
        % ==========================================================

        cache.metadata_match = true;
        cache.metadata_mismatch_message = '';

        if isfinite(cache.electroporated_column)

            fields_to_compare = { ...
                'PositionX_um', ...
                'PositionY_um', ...
                'PositionZ', ...
                'OpticalZoom', ...
                'NumPlanes'};

            mismatch_lines = {};

            for f = 1:numel(fields_to_compare)

                field_name = ...
                    fields_to_compare{f};

                gcamp_value = ...
                    metadata.gcamp_plane.(field_name){m};

                electroporated_value = ...
                    metadata.electroporated_plane.(field_name){m};

                if isempty(gcamp_value) || ...
                        isempty(electroporated_value)

                    mismatch_lines{end+1,1} = ...
                        sprintf( ...
                            ['%s:\n' ...
                             '    GCaMP          : %s\n' ...
                             '    Electroporated : %s\n' ...
                             '    Reason         : missing metadata value'], ...
                            field_name, ...
                            mat2str(gcamp_value), ...
                            mat2str(electroporated_value));

                    continue;
                end

                if ~isequal(gcamp_value, electroporated_value)

                    mismatch_lines{end+1,1} = ...
                        sprintf( ...
                            ['%s:\n' ...
                             '    GCaMP          : %s\n' ...
                             '    Electroporated : %s\n' ...
                             '    Reason         : different values'], ...
                            field_name, ...
                            mat2str(gcamp_value), ...
                            mat2str(electroporated_value));
                end
            end

            if ~isempty(mismatch_lines)

                cache.metadata_match = false;

                cache.metadata_mismatch_message = ...
                    strjoin(mismatch_lines, newline);
            end
        end

        % ==========================================================
        % Racine de l'analyse
        % ==========================================================

        root_folder_m = ...
            gcamp_root_folders{m};

        migrate_old_electroporated_results( ...
            root_folder_m);

        cache.filePath_electroporated = ...
            fullfile( ...
                root_folder_m, ...
                'results_electroporated.mat');

        cache.filePath_gcamp = ...
            fullfile( ...
                root_folder_m, ...
                'results_gcamp.mat');

        % ==========================================================
        % Plans GCaMP
        % ==========================================================

        cache.gcamp_planes = ...
            current_gcamp_folders_group{m};

        if ~iscell(cache.gcamp_planes)

            cache.gcamp_planes = ...
                {cache.gcamp_planes};
        end

        cache.nPlanes = ...
            numel(cache.gcamp_planes);

        if cache.nPlanes == 0

            fprintf( ...
                'Group %d: no GCaMP planes, skipped.\n', ...
                m);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Vérification NumPlanes / suite2p
        % ==========================================================

        metadata_nplanes = ...
            metadata.gcamp_plane.NumPlanes{m};

        if cache.nPlanes ~= metadata_nplanes

            warning( ...
                'process_electroporated_pass1:Suite2pPlaneMismatch', ...
                ['Recording group %d skipped.\n' ...
                 'GCaMP suite2p planes : %d\n' ...
                 'GCaMP XML NumPlanes  : %d'], ...
                m, ...
                cache.nPlanes, ...
                metadata_nplanes);

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Initialiser slots
        % ==========================================================

        for f = 1:numel(fields_electroporated_all)

            data = ensure_electroporated_plane_cell( ...
                data, ...
                fields_electroporated_all{f}, ...
                m, ...
                cache.nPlanes);
        end

        for f = 1:numel(gcamp_needed)

            data = ensure_local_gcamp_plane_cell( ...
                data, ...
                gcamp_needed{f}, ...
                m, ...
                cache.nPlanes);
        end

        % ==========================================================
        % Plans electroporated
        % ==========================================================

        if ~isfinite(cache.electroporated_column)

            cache.electroporated_planes = ...
                repmat( ...
                    {''}, ...
                    cache.nPlanes, ...
                    1);

        else

            cache.electroporated_planes = ...
                current_electroporated_folders_group{m};

            if ~iscell(cache.electroporated_planes)

                cache.electroporated_planes = ...
                    {cache.electroporated_planes};
            end
        end

        % ==========================================================
        % Plans Green
        % ==========================================================

        cache.green_planes = ...
            current_green_folders_group{m};

        if ~iscell(cache.green_planes)

            cache.green_planes = ...
                {cache.green_planes};
        end

        % ==========================================================
        % Vérifier nombre de plans electroporated AVANT indexation
        % ==========================================================

        if numel(cache.electroporated_planes) ~= cache.nPlanes

            warning( ...
                'process_electroporated_pass1:ElectroporatedPlaneMismatch', ...
                ['Recording group %d skipped.\n' ...
                 'GCaMP suite2p planes         : %d\n' ...
                 'Electroporated suite2p planes: %d'], ...
                m, ...
                cache.nPlanes, ...
                numel(cache.electroporated_planes));

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Chemins electroporated
        % ==========================================================

        for p = 1:cache.nPlanes

            data.electroporated_plane. ...
                electroporated_fall_path_by_plane{m}{p} = ...
                cache.electroporated_planes{p};
        end

        % ==========================================================
        % Charger results_electroporated uniquement si data est
        % incomplète.
        %
        % IMPORTANT :
        % roi_extraction_completed_by_plane = true permet de considérer
        % comme valides des sorties vides (par exemple 0 cellule).
        % ==============================================================

        if ~electroporated_group_already_complete( ...
                data, ...
                m, ...
                cache.nPlanes) && ...
                exist( ...
                    cache.filePath_electroporated, ...
                    'file') == 2

            requested_electroporated_fields = ...
                get_electroporated_fields_to_load_pass1( ...
                    data, ...
                    fields_electroporated_saved, ...
                    m, ...
                    cache.nPlanes);

            legacy_fields = { ...
                'F_blue_by_plane', ...
                'blue_match_mask_by_plane'};

            requested_electroporated_fields = ...
                unique( ...
                    [ ...
                        requested_electroporated_fields, ...
                        legacy_fields ...
                    ], ...
                    'stable');

            if ~isempty(requested_electroporated_fields)

                fprintf( ...
                    ['Group %d: loading missing electroporated ' ...
                     'variables from results_electroporated.mat.\n'], ...
                    m);

                loaded_electroporated = ...
                    load_available_variables_pass1( ...
                        cache.filePath_electroporated, ...
                        requested_electroporated_fields);

                loaded_electroporated = ...
                    normalize_electroporated_loaded_fields( ...
                        loaded_electroporated);

                data = merge_loaded_electroporated_into_data( ...
                    data, ...
                    loaded_electroporated, ...
                    fields_electroporated_saved, ...
                    m, ...
                    cache.nPlanes);
            end
        end

        % ==========================================================
        % Charger results_gcamp uniquement si nécessaire.
        % Le fichier complet n'est jamais chargé.
        % ==========================================================

        if ~local_gcamp_group_already_complete( ...
                data, ...
                gcamp_needed, ...
                m, ...
                cache.nPlanes) && ...
                exist( ...
                    cache.filePath_gcamp, ...
                    'file') == 2

            requested_gcamp_fields = ...
                get_local_gcamp_fields_to_load_pass1( ...
                    data, ...
                    gcamp_needed, ...
                    m, ...
                    cache.nPlanes);

            if ~isempty(requested_gcamp_fields)

                fprintf( ...
                    ['Group %d: loading missing GCaMP variables ' ...
                     'from results_gcamp.mat.\n'], ...
                    m);

                loaded_gcamp = ...
                    load_available_variables_pass1( ...
                        cache.filePath_gcamp, ...
                        requested_gcamp_fields);

                data = merge_loaded_local_gcamp_into_data( ...
                    data, ...
                    loaded_gcamp, ...
                    gcamp_needed, ...
                    m, ...
                    cache.nPlanes);
            end
        end

        % ==========================================================
        % Pas de fluorescence GCaMP
        % ==========================================================

        if ~local_gcamp_group_has_values( ...
                data, ...
                'F_gcamp_by_plane', ...
                m, ...
                cache.nPlanes)

            fprintf( ...
                ['Group %d: no GCaMP fluorescence, ' ...
                 'empty electroporated outputs stored.\n'], ...
                m);

            for p = 1:cache.nPlanes

                if ~electroporated_plane_has_meaningful_content( ...
                        data, ...
                        m, ...
                        p)

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end
            end

            cache.skip_group = true;
            processing_cache{m} = cache;

            continue;
        end

        % ==========================================================
        % Extraire GCaMP
        % ==========================================================

        cache.F_gcamp_by_plane = ...
            coerce_to_plane_cell_local( ...
                data.gcamp_plane.F_gcamp_by_plane{m}, ...
                cache.nPlanes);

        cache.gcamp_props_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'gcamp_props_by_plane', ...
                m, ...
                cache.nPlanes);

        cache.iscell_gcamp_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'iscell_gcamp_by_plane', ...
                m, ...
                cache.nPlanes);

        cache.gcamp_mask_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'gcamp_mask_by_plane', ...
                m, ...
                cache.nPlanes);

        cache.gcamp_mask_false_by_plane = ...
            get_gcamp_field_as_plane_cell( ...
                data, ...
                'gcamp_mask_false_by_plane', ...
                m, ...
                cache.nPlanes);

        % ==========================================================
        % Cache plans
        % ==========================================================

        cache.planes = ...
            cell(cache.nPlanes, 1);

        for p = 1:cache.nPlanes

            cache.planes{p} = struct( ...
                'process_plane', false, ...
                'requires_roi_extraction', false, ...
                'meanImg_channels', [], ...
                'aligned_image', [], ...
                'npy_file_path', '', ...
                'gcamp_reference_meanImg', [], ...
                'clear_electroporated_outputs_requested', false, ...
                'metadata_match', cache.metadata_match, ...
                'metadata_mismatch_message', ...
                    cache.metadata_mismatch_message, ...
                'error_message', '');
        end

        cache.valid_group = true;

        processing_cache{m} = cache;
    end

    % ==============================================================
    % PASS 1B
    % ==============================================================

    for m = 1:numFolders

        cache = ...
            processing_cache{m};

        if isempty(cache) || ...
                cache.skip_group || ...
                ~cache.valid_group

            continue;
        end

        % ==========================================================
        % TSeries Electroporated
        % ==========================================================

        if numel(current_electroporated_TSeries_path) >= m

            current_electroporated_TSeries_path_m = ...
                current_electroporated_TSeries_path{m};

        else

            current_electroporated_TSeries_path_m = '';
        end

        % ==========================================================
        % LOAD ONLY
        %
        % IMPORTANT:
        %   load_only ne se contente plus de regarder si les nouveaux
        %   champs de results_electroporated.mat existent.
        %
        %   Pour chaque plan on recherche aussi le masque Cellpose final
        %   réellement présent sur disque :
        %
        %       1) cellpose_npy_file_path_by_plane déjà en mémoire
        %       2) chemin mémorisé dans la signature ROI
        %       3) gcamp_reference_*_seg.npy dans le dossier de sortie
        %
        %   Si un masque final existe :
        %       - aucun fallback interactif n'est demandé ;
        %       - si l'extraction ROI est ancienne/incomplète, PASS 2 la
        %         recalculera automatiquement.
        %
        %   Le fallback séquentiel n'est demandé QUE lorsqu'aucun masque
        %   Cellpose final exploitable n'existe réellement.
        % ==========================================================

        if strcmpi(cellpose_mode, 'load_only')

            fprintf('\n');
            fprintf('============================================================\n');
            fprintf('ELECTROPORATED LOAD ONLY\n');
            fprintf('Recording group: %d/%d\n', m, numFolders);
            fprintf('============================================================\n');

            cache.requires_processing = ...
                false;

            % ------------------------------------------------------
            % IMPORTANT : en load_only, un mismatch de metadata est
            % informatif uniquement. Il ne doit JAMAIS provoquer un
            % fallback hors du PARFOR.
            %
            % Le seul critere qui peut demander le fallback
            % process_missing est l'absence reelle d'un masque Cellpose
            % final exploitable pour au moins un plan.
            % ------------------------------------------------------
            if ~cache.metadata_match

                warning( ...
                    'process_electroporated_pass1:MetadataMismatchLoadOnly', ...
                    ['GCaMP / Electroporated metadata mismatch for group %d.\n' ...
                     '%s\n' ...
                     'LOAD_ONLY: warning only; processing continues in the PARFOR.\n' ...
                     'This mismatch does not trigger process_missing.\n' ...
                     'Only a genuinely missing final Cellpose mask can do so.'], ...
                    m, ...
                    cache.metadata_mismatch_message);
            end

            for p = 1:cache.nPlanes

                cache.planes{p}.process_plane = ...
                    false;

                cache.planes{p}.requires_roi_extraction = ...
                    false;

                if electroporated_plane_slot_exists( ...
                        data, ...
                        'alignedImgs_electroporated', ...
                        m, ...
                        p)

                    cache.planes{p}.aligned_image = ...
                        data.electroporated_plane. ...
                            alignedImgs_electroporated{m}{p};

                else

                    cache.planes{p}.aligned_image = [];
                end

                existing_npy_file = ...
                    find_existing_final_cellpose_npy_pass1( ...
                        data, ...
                        gcamp_output_folders, ...
                        m, ...
                        p);

                if isempty(existing_npy_file)

                    fprintf( ...
                        ['Plane %d: no final GCaMP/Cellpose mask was found.\n' ...
                         'Sequential processing will be required only for ' ...
                         'this missing detection.\n'], ...
                        p);

                    cache.requires_processing = ...
                        true;

                    continue;
                end

                fprintf( ...
                    'Plane %d: existing final Cellpose masks found:\n%s\n', ...
                    p, ...
                    existing_npy_file);

                cache.planes{p}.npy_file_path = ...
                    existing_npy_file;

                data.electroporated_plane. ...
                    cellpose_npy_file_path_by_plane{m}{p} = ...
                    existing_npy_file;

                extraction_is_current = ...
                    is_electroporated_roi_extraction_current_pass1( ...
                        data, ...
                        m, ...
                        p, ...
                        existing_npy_file);

                if extraction_is_current

                    fprintf( ...
                        ['Plane %d: ROI extraction already complete and ' ...
                         'current.\n'], ...
                        p);

                else

                    fprintf( ...
                        ['Plane %d: masks already exist; ROI extraction is ' ...
                         'missing/outdated and will be rebuilt automatically.\n'], ...
                        p);

                    cache.planes{p}.process_plane = ...
                        true;

                    cache.planes{p}.requires_roi_extraction = ...
                        true;
                end
            end

            processing_cache{m} = ...
                cache;

            continue;
        end

        % ==========================================================
        % MODE INTERACTIF NORMAL
        % ==========================================================

        current_gcamp_TSeries_path_m = ...
            TSeries_paths{m, 1};

        fprintf( ...
            'GCaMP TSeries          : %s\n', ...
            current_gcamp_TSeries_path_m);

        fprintf( ...
            'Electroporated TSeries : %s\n', ...
            current_electroporated_TSeries_path_m);

        % ==========================================================
        % METADATA MISMATCH
        % ==========================================================

        if ~cache.metadata_match

            % ------------------------------------------------------
            % process_missing est le fallback interne du LOAD_ONLY.
            % Un mismatch ne doit donc pas demander d'interaction et
            % ne doit pas interrompre le traitement. Le fallback a ete
            % demande pour une vraie donnee manquante, pas pour le
            % mismatch lui-meme.
            % ------------------------------------------------------
            if strcmpi(cellpose_mode, 'process_missing')

                warning( ...
                    'process_electroporated_pass1:MetadataMismatchProcessMissing', ...
                    ['GCaMP / Electroporated metadata mismatch for group %d.\n' ...
                     '%s\n' ...
                     'PROCESS_MISSING: warning only; continuing automatically.'], ...
                    m, ...
                    cache.metadata_mismatch_message);

            else

                existing_results_are_complete_and_current = ...
                    electroporated_group_results_complete_and_current_pass1( ...
                        data, ...
                        m, ...
                        cache.nPlanes);

                if existing_results_are_complete_and_current

                    warning( ...
                        'process_electroporated_pass1:MetadataMismatch', ...
                        ['============================================================\n' ...
                         'GCaMP / ELECTROPORATED METADATA MISMATCH\n' ...
                         '============================================================\n\n' ...
                         '%s\n\n' ...
                         'GCaMP and electroporated metadata do not match.\n\n' ...
                         'Existing electroporated results are complete and up to date.\n' ...
                         'Existing results retained.\n' ...
                         'The existing aligned image will still be loaded.'], ...
                        cache.metadata_mismatch_message);

                    input( ...
                        '\nPress Enter to continue.\n', ...
                        's');

                    fprintf( ...
                        ['Continuing in order to load / check the existing ' ...
                         'aligned image.\n']);

                else

                    choice = input( ...
                        sprintf([ ...
                            '\n============================================================\n' ...
                            'GCaMP / ELECTROPORATED METADATA MISMATCH\n' ...
                            '============================================================\n\n' ...
                            '%s\n\n' ...
                            'GCaMP and electroporated metadata do not match.\n\n' ...
                            'Press 1 to continue with alignment / Cellpose anyway.\n' ...
                            'Press 0 to keep existing data and skip this recording.\n> '], ...
                            cache.metadata_mismatch_message), ...
                        's');

                    user_accepted_metadata_mismatch = ...
                        strcmp(strtrim(choice), '1');

                    if ~user_accepted_metadata_mismatch

                        fprintf( ...
                            ['Existing results retained.\n' ...
                             'Cellpose/alignment skipped.\n']);

                        for p = 1:cache.nPlanes

                            cache.planes{p}.process_plane = false;
                            cache.planes{p}.requires_roi_extraction = false;
                        end

                        processing_cache{m} = ...
                            cache;

                        continue;
                    end

                    fprintf( ...
                        ['Metadata mismatch accepted. ' ...
                         'Continuing with alignment / Cellpose.\n']);
                end
            end
        end

        % ==========================================================
        % Plans
        % ==========================================================

        for p = 1:cache.nPlanes

            fprintf( ...
                '\nCellpose | Date %d/%d | Plane %d/%d\n', ...
                m, ...
                numFolders, ...
                p, ...
                cache.nPlanes);

            electroporated_plane_folder = ...
                cache.electroporated_planes{p};

            data.electroporated_plane. ...
                electroporated_fall_path_by_plane{m}{p} = ...
                electroporated_plane_folder;

            % ======================================================
            % Ops electroporated
            % ======================================================

            if ~electroporated_plane_slot_exists( ...
                    data, ...
                    'ops_suite2p_electroporated_by_plane', ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.electroporated_plane. ...
                        ops_suite2p_electroporated_by_plane{m}{p})

                if isempty(electroporated_plane_folder)

                    data.electroporated_plane. ...
                        ops_suite2p_electroporated_by_plane{m}{p} = [];

                else

                    data.electroporated_plane. ...
                        ops_suite2p_electroporated_by_plane{m}{p} = ...
                        load_ops_only( ...
                            electroporated_plane_folder);
                end
            end

            electroporated_results_already_complete = ...
                electroporated_plane_has_meaningful_content( ...
                    data, ...
                    m, ...
                    p);

            if electroporated_results_already_complete

                fprintf( ...
                    ['Plane %d: electroporated ROI results already ' ...
                     'complete. Aligned image will still be loaded.\n'], ...
                    p);
            end

            % ======================================================
            % GCaMP
            % ======================================================

            if isempty(cache.F_gcamp_by_plane{p})

                fprintf( ...
                    'Plane %d: empty GCaMP fluorescence.\n', ...
                    p);

                if ~electroporated_results_already_complete

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            if isempty(cache.gcamp_planes{p})

                fprintf( ...
                    'Plane %d: missing GCaMP folder.\n', ...
                    p);

                if ~electroporated_results_already_complete

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            % ======================================================
            % Output folder plan
            % ======================================================

            output_folders_m = ...
                gcamp_output_folders{m};

            if iscell(output_folders_m)

                output_folder_p = ...
                    output_folders_m{p};

            else

                output_folder_p = ...
                    output_folders_m;
            end

            % ======================================================
            % Green
            % ======================================================

            if isempty(cache.green_planes)

                green_plane_folder = '';

            elseif numel(cache.green_planes) >= p

                green_plane_folder = ...
                    cache.green_planes{p};

            else

                green_plane_folder = '';
            end

            % ======================================================
            % Cellpose
            % ======================================================

            try

                [ ...
                    meanImg_channels, ...
                    aligned_image_plane, ...
                    npy_file_path, ...
                    gcamp_reference_meanImg, ...
                    clear_electroporated_outputs_requested ...
                ] = ...
                    load_or_process_cellpose_TSeries( ...
                        cache.filePath_electroporated, ...
                        date_group_paths{m}, ...
                        cache.gcamp_planes{p}, ...
                        cache.electroporated_planes{p}, ...
                        green_plane_folder, ...
                        current_electroporated_TSeries_path_m, ...
                        output_folder_p, ...
                        cellpose_mode);

            catch ME

                warning( ...
                    'process_electroporated_pass1:CellposeFailed', ...
                    ['Group %d plane %d failed while loading ' ...
                     'the aligned image: %s'], ...
                    m, ...
                    p, ...
                    ME.message);

                cache.planes{p}.error_message = ...
                    ME.message;

                if ~electroporated_results_already_complete

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            % ======================================================
            % Store outputs
            % ======================================================

            cache.planes{p}.meanImg_channels = ...
                meanImg_channels;

            cache.planes{p}.aligned_image = ...
                aligned_image_plane;

            cache.planes{p}.npy_file_path = ...
                npy_file_path;

            cache.planes{p}.gcamp_reference_meanImg = ...
                gcamp_reference_meanImg;

            data.electroporated_plane. ...
                meanImg_channels_by_plane{m}{p} = ...
                meanImg_channels;

            data.electroporated_plane. ...
                alignedImgs_electroporated{m}{p} = ...
                aligned_image_plane;

            data.electroporated_plane. ...
                cellpose_npy_file_path_by_plane{m}{p} = ...
                npy_file_path;

            data.electroporated_plane. ...
                gcamp_reference_meanImg_by_plane{m}{p} = ...
                gcamp_reference_meanImg;

            cache.planes{p}.clear_electroporated_outputs_requested = ...
                clear_electroporated_outputs_requested;

            cache.planes{p}.metadata_match = ...
                cache.metadata_match;

            cache.planes{p}.metadata_mismatch_message = ...
                cache.metadata_mismatch_message;

            % ======================================================
            % NPY
            % ======================================================

            if isempty(npy_file_path)

                fprintf( ...
                    ['Plane %d: empty NPY path. ' ...
                     'Aligned image was nevertheless stored.\n'], ...
                    p);

                if electroporated_results_already_complete

                    cache.planes{p}.process_plane = false;

                else

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            if exist(npy_file_path, 'file') ~= 2

                fprintf( ...
                    ['Plane %d: NPY not found. ' ...
                     'Aligned image was nevertheless stored:\n%s\n'], ...
                    p, ...
                    npy_file_path);

                if electroporated_results_already_complete

                    cache.planes{p}.process_plane = false;

                else

                    data = set_empty_electroporated_plane( ...
                        data, ...
                        m, ...
                        p);

                    cache.has_new_electroporated_data = true;
                end

                continue;
            end

            fprintf( ...
                'Plane %d: Cellpose NPY ready:\n%s\n', ...
                p, ...
                npy_file_path);

            % ======================================================
            % Extraction actuelle ?
            % ======================================================

            extraction_is_current = ...
                is_electroporated_roi_extraction_current_pass1( ...
                    data, ...
                    m, ...
                    p, ...
                    npy_file_path);

            if extraction_is_current

                cache.planes{p}.process_plane = false;

                cache.planes{p}.requires_roi_extraction = false;

                fprintf( ...
                    ['Plane %d: electroporated ROI extraction already ' ...
                     'up to date. Existing results retained.\n'], ...
                    p);

                continue;
            end

            cache.planes{p}.requires_roi_extraction = true;
            cache.planes{p}.process_plane = true;

            fprintf( ...
                ['Plane %d: electroporated ROI extraction ' ...
                 'required.\n'], ...
                p);
        end

        processing_cache{m} = ...
            cache;
    end
end


% ========================================================================
% INCLUDE ELECTROPORATED ENABLED
% ========================================================================

function tf = is_include_electroporated_enabled_pass1(value)

    tf = false;

    if isempty(value)
        return;
    end

    if isnumeric(value) || ...
            islogical(value)

        tf = ...
            any(value(:) == 1);

        return;
    end

    if ischar(value) || ...
            isstring(value)

        tf = ...
            strcmp( ...
                strtrim(char(string(value))), ...
                '1');
    end
end


% ========================================================================
% GROUP RESULTS COMPLETE AND CURRENT
% ========================================================================

function tf = electroporated_group_results_complete_and_current_pass1( ...
        data, ...
        m, ...
        nPlanes)

    tf = ...
        nPlanes > 0;

    for p = 1:nPlanes

        if ~is_electroporated_roi_current_saved_sig_pass1( ...
                data, ...
                m, ...
                p)

            tf = false;
            return;
        end
    end
end


% ========================================================================
% EXTRACTION CURRENT FROM SAVED SIGNATURE
% ========================================================================

function extraction_is_current = ...
        is_electroporated_roi_current_saved_sig_pass1( ...
            data, ...
            m, ...
            p)

    extraction_is_current = false;

    if ~electroporated_plane_results_complete_pass1( ...
            data, ...
            m, ...
            p)

        return;
    end

    electroporated_plane = ...
        data.electroporated_plane;

    saved_signature = ...
        get_nested_plane_value_pass1( ...
            electroporated_plane. ...
                roi_extraction_npy_signature_by_plane, ...
            m, ...
            p);

    current_signature = ...
        get_npy_file_signature_pass1( ...
            saved_signature.path);

    if isempty(current_signature)
        return;
    end

    extraction_is_current = ...
        compare_npy_signatures_pass1( ...
            saved_signature, ...
            current_signature);
end


% ========================================================================
% MIGRATION OLD RESULTS
% ========================================================================

function migrate_old_electroporated_results(root_folder)

    old_file = ...
        fullfile( ...
            root_folder, ...
            'results_blue.mat');

    new_file = ...
        fullfile( ...
            root_folder, ...
            'results_electroporated.mat');

    if exist(old_file, 'file') ~= 2
        return;
    end

    if exist(new_file, 'file') ~= 2

        loaded = ...
            load(old_file);

        loaded = ...
            normalize_electroporated_loaded_fields( ...
                loaded);

        save( ...
            new_file, ...
            '-struct', ...
            'loaded', ...
            '-v7.3');

        fprintf( ...
            ['Migrated old electroporated results:\n' ...
             '%s\n'], ...
            new_file);
    end

    if exist(new_file, 'file') == 2

        delete(old_file);

        fprintf( ...
            'Old results file removed.\n');
    end
end


% ========================================================================
% NORMALIZE OLD ELECTROPORATED FIELDS
% ========================================================================

function loaded = normalize_electroporated_loaded_fields(loaded)

    old_names = { ...
        'F_blue_by_plane', ...
        'blue_match_mask_by_plane', ...
        'ops_suite2p_blue_by_plane', ...
        'blue_fall_path_by_plane'};

    new_names = { ...
        'F_electroporated_by_plane', ...
        'electroporated_match_mask_by_plane', ...
        'ops_suite2p_electroporated_by_plane', ...
        'electroporated_fall_path_by_plane'};

    for i = 1:numel(old_names)

        if isfield( ...
                loaded, ...
                old_names{i})

            if ~isfield( ...
                    loaded, ...
                    new_names{i})

                loaded.(new_names{i}) = ...
                    loaded.(old_names{i});
            end

            loaded = ...
                rmfield( ...
                    loaded, ...
                    old_names{i});
        end
    end
end


% ========================================================================
% GCAMP FIELD
% ========================================================================

function vals = get_gcamp_field_as_plane_cell( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    vals = ...
        cell(nPlanes, 1);

    if isfield(data, 'gcamp_plane') && ...
            isfield( ...
                data.gcamp_plane, ...
                fieldName) && ...
            numel( ...
                data.gcamp_plane.(fieldName)) >= m

        vals = ...
            coerce_to_plane_cell_local( ...
                data.gcamp_plane.(fieldName){m}, ...
                nPlanes);
    end
end


% ========================================================================
% ELECTROPORATED GROUP COMPLETE
% ========================================================================

function tf = electroporated_group_already_complete( ...
        data, ...
        m, ...
        nPlanes)

    tf = ...
        nPlanes > 0;

    for p = 1:nPlanes

        if ~electroporated_plane_results_complete_pass1( ...
                data, ...
                m, ...
                p)

            tf = false;
            return;
        end
    end
end


% ========================================================================
% ELECTROPORATED PLANE COMPLETE
%
% Une sortie vide peut être valide si roi_extraction_completed_by_plane
% vaut true. On vérifie donc l'existence des slots, pas leur non-vacuité.
% ========================================================================

function tf = electroporated_plane_results_complete_pass1( ...
        data, ...
        m, ...
        p)

    tf = false;

    if ~isfield(data, 'electroporated_plane') || ...
            isempty(data.electroporated_plane) || ...
            ~isstruct(data.electroporated_plane)

        return;
    end

    ep = ...
        data.electroporated_plane;

    if ~isfield( ...
            ep, ...
            'roi_extraction_completed_by_plane')

        return;
    end

    completed_value = ...
        get_nested_plane_value_pass1( ...
            ep.roi_extraction_completed_by_plane, ...
            m, ...
            p);

    if isempty(completed_value) || ...
            numel(completed_value) ~= 1

        return;
    end

    if islogical(completed_value)

        if ~completed_value
            return;
        end

    elseif isnumeric(completed_value)

        if ~isfinite(completed_value) || ...
                completed_value == 0

            return;
        end

    else

        return;
    end

    required_slot_fields = { ...
        'matched_gcamp_idx_by_plane', ...
        'matched_cellpose_idx_by_plane', ...
        'gcamp_unmatched_idx_by_plane', ...
        'cellpose_unmatched_idx_by_plane', ...
        'num_cells_mask_by_plane', ...
        'mask_cellpose_by_plane', ...
        'props_cellpose_by_plane', ...
        'outlines_x_cellpose_by_plane', ...
        'outlines_y_cellpose_by_plane', ...
        'F_electroporated_by_plane', ...
        'electroporated_match_mask_by_plane'};

    for k = 1:numel(required_slot_fields)

        field_name = ...
            required_slot_fields{k};

        if ~isfield(ep, field_name)

            return;
        end

        if ~nested_plane_entry_exists_pass1( ...
                ep.(field_name), ...
                m, ...
                p)

            return;
        end
    end

    if ~isfield( ...
            ep, ...
            'roi_extraction_npy_signature_by_plane')

        return;
    end

    saved_signature = ...
        get_nested_plane_value_pass1( ...
            ep.roi_extraction_npy_signature_by_plane, ...
            m, ...
            p);

    if isempty(saved_signature) || ...
            ~isstruct(saved_signature) || ...
            ~isfield(saved_signature, 'path') || ...
            isempty(saved_signature.path)

        return;
    end

    tf = true;
end


% ========================================================================
% GCAMP GROUP COMPLETE
% ========================================================================

function tf = local_gcamp_group_already_complete( ...
        data, ...
        fields, ...
        m, ...
        nPlanes)

    %#ok<INUSD>

    required_nonempty_fields = { ...
        'stat_by_plane', ...
        'F_gcamp_by_plane', ...
        'gcamp_props_by_plane', ...
        'outlines_gcampx_by_plane', ...
        'outlines_gcampy_by_plane', ...
        'iscell_gcamp_by_plane', ...
        'gcamp_mask_by_plane'};

    tf = ...
        nPlanes > 0;

    for p = 1:nPlanes

        for f = 1:numel(required_nonempty_fields)

            name = ...
                required_nonempty_fields{f};

            if ~local_gcamp_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.gcamp_plane.(name){m}{p})

                tf = false;
                return;
            end
        end

        % Si des rejected ROIs existent, leurs masks doivent exister.
        % Si stat_false est vide, les champs false vides sont valides.
        if local_gcamp_slot_exists( ...
                data, ...
                'stat_false_by_plane', ...
                m, ...
                p)

            stat_false = ...
                data.gcamp_plane.stat_false_by_plane{m}{p};

        else

            stat_false = [];
        end

        if ~isempty(stat_false)

            required_false_fields = { ...
                'iscell_false_by_plane', ...
                'gcamp_props_false_by_plane', ...
                'outlines_gcampx_false_by_plane', ...
                'outlines_gcampy_false_by_plane', ...
                'gcamp_mask_false_by_plane'};

            for f = 1:numel(required_false_fields)

                name = ...
                    required_false_fields{f};

                if ~local_gcamp_slot_exists( ...
                        data, ...
                        name, ...
                        m, ...
                        p) || ...
                        isempty( ...
                            data.gcamp_plane.(name){m}{p})

                    tf = false;
                    return;
                end
            end
        end
    end
end


% ========================================================================
% INIT ELECTROPORATED STRUCT
% ========================================================================

function data = init_electroporated_plane_struct_if_needed( ...
        data, ...
        numFolders, ...
        fields)

    if nargin < 1 || ...
            isempty(data)

        data = struct();
    end

    if isfield(data, 'blue_plane')

        if ~isfield( ...
                data, ...
                'electroporated_plane') || ...
                ~isstruct( ...
                    data.electroporated_plane)

            data.electroporated_plane = ...
                data.blue_plane;
        end

        data = ...
            rmfield( ...
                data, ...
                'blue_plane');
    end

    if ~isfield( ...
            data, ...
            'electroporated_plane') || ...
            ~isstruct( ...
                data.electroporated_plane)

        data.electroporated_plane = ...
            struct();
    end

    data.electroporated_plane = ...
        normalize_electroporated_loaded_fields( ...
            data.electroporated_plane);

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield( ...
                data.electroporated_plane, ...
                name) || ...
                ~iscell( ...
                    data.electroporated_plane.(name))

            data.electroporated_plane.(name) = ...
                cell(numFolders, 1);

        elseif numel( ...
                data.electroporated_plane.(name)) < numFolders

            old = ...
                data.electroporated_plane.(name);

            tmp = ...
                cell(numFolders, 1);

            tmp(1:numel(old)) = ...
                old(:);

            data.electroporated_plane.(name) = ...
                tmp;
        end
    end
end


% ========================================================================
% INIT GCAMP
% ========================================================================

function data = init_gcamp_plane_struct_if_needed_local( ...
        data, ...
        numFolders, ...
        fields)

    if ~isfield(data, 'gcamp_plane') || ...
            ~isstruct(data.gcamp_plane)

        data.gcamp_plane = ...
            struct();
    end

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield( ...
                data.gcamp_plane, ...
                name) || ...
                ~iscell( ...
                    data.gcamp_plane.(name))

            data.gcamp_plane.(name) = ...
                cell(numFolders, 1);

        elseif numel( ...
                data.gcamp_plane.(name)) < numFolders

            old = ...
                data.gcamp_plane.(name);

            tmp = ...
                cell(numFolders, 1);

            tmp(1:numel(old)) = ...
                old(:);

            data.gcamp_plane.(name) = ...
                tmp;
        end
    end
end


% ========================================================================
% ENSURE ELECTROPORATED
% ========================================================================

function data = ensure_electroporated_plane_cell( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    if ~isfield( ...
            data.electroporated_plane, ...
            fieldName)

        data.electroporated_plane.(fieldName) = ...
            cell(m, 1);
    end

    if numel( ...
            data.electroporated_plane.(fieldName)) < m

        tmp = ...
            cell(m, 1);

        tmp( ...
            1:numel( ...
                data.electroporated_plane.(fieldName))) = ...
            data.electroporated_plane.(fieldName)(:);

        data.electroporated_plane.(fieldName) = ...
            tmp;
    end

    if isempty( ...
            data.electroporated_plane.(fieldName){m}) || ...
            ~iscell( ...
                data.electroporated_plane.(fieldName){m})

        data.electroporated_plane.(fieldName){m} = ...
            cell(nPlanes, 1);

    elseif numel( ...
            data.electroporated_plane.(fieldName){m}) ~= nPlanes

        old = ...
            data.electroporated_plane.(fieldName){m};

        tmp = ...
            cell(nPlanes, 1);

        n = ...
            min( ...
                numel(old), ...
                nPlanes);

        tmp(1:n) = ...
            old(1:n);

        data.electroporated_plane.(fieldName){m} = ...
            tmp;
    end
end


% ========================================================================
% ENSURE GCAMP
% ========================================================================

function data = ensure_local_gcamp_plane_cell( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    if ~isfield( ...
            data.gcamp_plane, ...
            fieldName)

        data.gcamp_plane.(fieldName) = ...
            cell(m, 1);
    end

    if numel( ...
            data.gcamp_plane.(fieldName)) < m

        tmp = ...
            cell(m, 1);

        tmp( ...
            1:numel( ...
                data.gcamp_plane.(fieldName))) = ...
            data.gcamp_plane.(fieldName)(:);

        data.gcamp_plane.(fieldName) = ...
            tmp;
    end

    if isempty( ...
            data.gcamp_plane.(fieldName){m}) || ...
            ~iscell( ...
                data.gcamp_plane.(fieldName){m})

        data.gcamp_plane.(fieldName){m} = ...
            cell(nPlanes, 1);

    elseif numel( ...
            data.gcamp_plane.(fieldName){m}) ~= nPlanes

        old = ...
            data.gcamp_plane.(fieldName){m};

        tmp = ...
            cell(nPlanes, 1);

        n = ...
            min( ...
                numel(old), ...
                nPlanes);

        tmp(1:n) = ...
            old(1:n);

        data.gcamp_plane.(fieldName){m} = ...
            tmp;
    end
end


% ========================================================================
% COERCE PLANE CELL
% ========================================================================

function out = coerce_to_plane_cell_local( ...
        val, ...
        nPlanes)

    out = ...
        cell(nPlanes, 1);

    if isempty(val)
        return;
    end

    if iscell(val)

        n = ...
            min( ...
                numel(val), ...
                nPlanes);

        out(1:n) = ...
            val(1:n);

    elseif nPlanes >= 1

        out{1} = ...
            val;
    end
end


% ========================================================================
% MERGE ELECTROPORATED
% ========================================================================

function data = merge_loaded_electroporated_into_data( ...
        data, ...
        loaded, ...
        fields, ...
        m, ...
        nPlanes)

    loaded = ...
        normalize_electroporated_loaded_fields( ...
            loaded);

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield(loaded, name)
            continue;
        end

        vals = ...
            coerce_to_plane_cell_local( ...
                loaded.(name), ...
                nPlanes);

        for p = 1:nPlanes

            plane_completed = ...
                electroporated_completed_marker_true_pass1( ...
                    data, ...
                    m, ...
                    p);

            if ~electroporated_plane_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p)

                data.electroporated_plane.(name){m}{p} = ...
                    vals{p};

            elseif isempty( ...
                    data.electroporated_plane.(name){m}{p}) && ...
                    ~plane_completed

                data.electroporated_plane.(name){m}{p} = ...
                    vals{p};
            end
        end
    end
end


% ========================================================================
% MERGE GCAMP
% ========================================================================

function data = merge_loaded_local_gcamp_into_data( ...
        data, ...
        loaded, ...
        fields, ...
        m, ...
        nPlanes)

    for f = 1:numel(fields)

        name = ...
            fields{f};

        if ~isfield(loaded, name)
            continue;
        end

        vals = ...
            coerce_to_plane_cell_local( ...
                loaded.(name), ...
                nPlanes);

        for p = 1:nPlanes

            if ~local_gcamp_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.gcamp_plane.(name){m}{p})

                data.gcamp_plane.(name){m}{p} = ...
                    vals{p};
            end
        end
    end
end


% ========================================================================
% ELECTROPORATED SLOT
% ========================================================================

function tf = electroporated_plane_slot_exists( ...
        data, ...
        fieldName, ...
        m, ...
        p)

    tf = ...
        isfield( ...
            data, ...
            'electroporated_plane') && ...
        isfield( ...
            data.electroporated_plane, ...
            fieldName) && ...
        numel( ...
            data.electroporated_plane.(fieldName)) >= m && ...
        iscell( ...
            data.electroporated_plane.(fieldName){m}) && ...
        numel( ...
            data.electroporated_plane.(fieldName){m}) >= p;
end


% ========================================================================
% GCAMP SLOT
% ========================================================================

function tf = local_gcamp_slot_exists( ...
        data, ...
        fieldName, ...
        m, ...
        p)

    tf = ...
        isfield( ...
            data, ...
            'gcamp_plane') && ...
        isfield( ...
            data.gcamp_plane, ...
            fieldName) && ...
        numel( ...
            data.gcamp_plane.(fieldName)) >= m && ...
        iscell( ...
            data.gcamp_plane.(fieldName){m}) && ...
        numel( ...
            data.gcamp_plane.(fieldName){m}) >= p;
end


% ========================================================================
% GCAMP HAS VALUES
% ========================================================================

function tf = local_gcamp_group_has_values( ...
        data, ...
        fieldName, ...
        m, ...
        nPlanes)

    tf = false;

    if ~isfield( ...
            data, ...
            'gcamp_plane') || ...
            ~isfield( ...
                data.gcamp_plane, ...
                fieldName) || ...
            numel( ...
                data.gcamp_plane.(fieldName)) < m

        return;
    end

    vals = ...
        coerce_to_plane_cell_local( ...
            data.gcamp_plane.(fieldName){m}, ...
            nPlanes);

    tf = ...
        any( ...
            ~cellfun( ...
                @isempty, ...
                vals));
end


% ========================================================================
% ELECTROPORATED CONTENT
% ========================================================================

function tf = electroporated_plane_has_meaningful_content( ...
        data, ...
        m, ...
        p)

    tf = ...
        electroporated_plane_results_complete_pass1( ...
            data, ...
            m, ...
            p);
end


% ========================================================================
% EMPTY ELECTROPORATED
% ========================================================================

function data = set_empty_electroporated_plane( ...
        data, ...
        m, ...
        p)

    data.electroporated_plane. ...
        matched_gcamp_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        matched_cellpose_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        gcamp_unmatched_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        cellpose_unmatched_idx_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        num_cells_mask_by_plane{m}{p} = 0;

    data.electroporated_plane. ...
        mask_cellpose_by_plane{m}{p} = ...
        false(0,0,0);

    data.electroporated_plane. ...
        props_cellpose_by_plane{m}{p} = ...
        struct([]);

    data.electroporated_plane. ...
        outlines_x_cellpose_by_plane{m}{p} = {};

    data.electroporated_plane. ...
        outlines_y_cellpose_by_plane{m}{p} = {};

    data.electroporated_plane. ...
        F_electroporated_by_plane{m}{p} = [];

    data.electroporated_plane. ...
        electroporated_match_mask_by_plane{m}{p} = ...
        false(0,1);

    data.electroporated_plane. ...
        ops_suite2p_electroporated_by_plane{m}{p} = [];

    % Une sortie vidée ne doit jamais rester marquée comme extraction
    % complète ou conserver une ancienne signature.
    data.electroporated_plane. ...
        roi_extraction_completed_by_plane{m}{p} = ...
        false;

    data.electroporated_plane. ...
        roi_extraction_npy_signature_by_plane{m}{p} = ...
        [];
end


% ========================================================================
% ELECTROPORATED ROI EXTRACTION CURRENT - PASS 1
% ========================================================================

function extraction_is_current = ...
        is_electroporated_roi_extraction_current_pass1( ...
            data, ...
            m, ...
            p, ...
            npy_file_path)

    extraction_is_current = false;

    if ~electroporated_plane_results_complete_pass1( ...
            data, ...
            m, ...
            p)

        return;
    end

    saved_signature = ...
        get_nested_plane_value_pass1( ...
            data.electroporated_plane. ...
                roi_extraction_npy_signature_by_plane, ...
            m, ...
            p);

    current_signature = ...
        get_npy_file_signature_pass1( ...
            npy_file_path);

    if isempty(current_signature)
        return;
    end

    extraction_is_current = ...
        compare_npy_signatures_pass1( ...
            saved_signature, ...
            current_signature);
end


% ========================================================================
% COMPLETED MARKER TRUE
% ========================================================================

function tf = electroporated_completed_marker_true_pass1( ...
        data, ...
        m, ...
        p)

    tf = false;

    if ~isfield(data, 'electroporated_plane') || ...
            ~isfield( ...
                data.electroporated_plane, ...
                'roi_extraction_completed_by_plane')

        return;
    end

    value = ...
        get_nested_plane_value_pass1( ...
            data.electroporated_plane. ...
                roi_extraction_completed_by_plane, ...
            m, ...
            p);

    if isempty(value) || ...
            numel(value) ~= 1

        return;
    end

    if islogical(value)

        tf = ...
            value;

    elseif isnumeric(value)

        tf = ...
            isfinite(value) && ...
            value ~= 0;
    end
end


% ========================================================================
% ELECTROPORATED FIELDS TO LOAD
% ========================================================================

function fields_to_load = get_electroporated_fields_to_load_pass1( ...
        data, ...
        fields, ...
        m, ...
        nPlanes)

    fields_to_load = {};

    for f = 1:numel(fields)

        name = ...
            fields{f};

        field_needed = false;

        for p = 1:nPlanes

            plane_completed = ...
                electroporated_completed_marker_true_pass1( ...
                    data, ...
                    m, ...
                    p);

            if ~electroporated_plane_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p)

                field_needed = true;
                break;
            end

            % Une valeur vide n'est considérée manquante que si le plan
            % n'est pas déjà marqué comme extraction terminée.
            if isempty( ...
                    data.electroporated_plane.(name){m}{p}) && ...
                    ~plane_completed

                field_needed = true;
                break;
            end
        end

        if field_needed

            fields_to_load{end + 1} = ...
                name; %#ok<AGROW>
        end
    end
end


% ========================================================================
% GCAMP FIELDS TO LOAD
% ========================================================================

function fields_to_load = get_local_gcamp_fields_to_load_pass1( ...
        data, ...
        fields, ...
        m, ...
        nPlanes)

    fields_to_load = {};

    accepted_required = { ...
        'stat_by_plane', ...
        'F_gcamp_by_plane', ...
        'gcamp_props_by_plane', ...
        'outlines_gcampx_by_plane', ...
        'outlines_gcampy_by_plane', ...
        'iscell_gcamp_by_plane', ...
        'gcamp_mask_by_plane'};

    false_fields = { ...
        'stat_false_by_plane', ...
        'iscell_false_by_plane', ...
        'gcamp_props_false_by_plane', ...
        'outlines_gcampx_false_by_plane', ...
        'outlines_gcampy_false_by_plane', ...
        'gcamp_mask_false_by_plane'};

    for f = 1:numel(fields)

        name = ...
            fields{f};

        field_needed = false;

        if any(strcmp(name, accepted_required))

            for p = 1:nPlanes

                if ~local_gcamp_slot_exists( ...
                        data, ...
                        name, ...
                        m, ...
                        p) || ...
                        isempty( ...
                            data.gcamp_plane.(name){m}{p})

                    field_needed = true;
                    break;
                end
            end

        elseif any(strcmp(name, false_fields))

            % Si stat_false est non vide, les champs false sont requis.
            % Si stat_false est vide, [] est un résultat valide.
            for p = 1:nPlanes

                stat_false = [];

                if local_gcamp_slot_exists( ...
                        data, ...
                        'stat_false_by_plane', ...
                        m, ...
                        p)

                    stat_false = ...
                        data.gcamp_plane.stat_false_by_plane{m}{p};
                end

                if strcmp(name, 'stat_false_by_plane')

                    % On ne peut pas distinguer ici un [] valide d'un []
                    % placeholder créé par l'initialisation. On tente donc
                    % de charger stat_false depuis le fichier uniquement
                    % lorsqu'un autre champ GCaMP indispensable manque.
                    if ~local_gcamp_group_core_complete_pass1( ...
                            data, ...
                            m, ...
                            nPlanes)

                        field_needed = true;
                        break;
                    end

                elseif ~isempty(stat_false)

                    if ~local_gcamp_slot_exists( ...
                            data, ...
                            name, ...
                            m, ...
                            p) || ...
                            isempty( ...
                                data.gcamp_plane.(name){m}{p})

                        field_needed = true;
                        break;
                    end
                end
            end
        end

        if field_needed

            fields_to_load{end + 1} = ...
                name; %#ok<AGROW>
        end
    end
end


% ========================================================================
% GCAMP CORE COMPLETE
% ========================================================================

function tf = local_gcamp_group_core_complete_pass1( ...
        data, ...
        m, ...
        nPlanes)

    required = { ...
        'stat_by_plane', ...
        'F_gcamp_by_plane', ...
        'gcamp_props_by_plane', ...
        'outlines_gcampx_by_plane', ...
        'outlines_gcampy_by_plane', ...
        'iscell_gcamp_by_plane', ...
        'gcamp_mask_by_plane'};

    tf = ...
        nPlanes > 0;

    for p = 1:nPlanes

        for f = 1:numel(required)

            name = ...
                required{f};

            if ~local_gcamp_slot_exists( ...
                    data, ...
                    name, ...
                    m, ...
                    p) || ...
                    isempty( ...
                        data.gcamp_plane.(name){m}{p})

                tf = false;
                return;
            end
        end
    end
end


% ========================================================================
% LOAD AVAILABLE VARIABLES ONLY
% ========================================================================

function loaded = load_available_variables_pass1( ...
        file_path, ...
        requested_fields)

    loaded = struct();

    if isempty(file_path) || ...
            exist(file_path, 'file') ~= 2 || ...
            isempty(requested_fields)

        return;
    end

    variables_in_file = ...
        whos( ...
            '-file', ...
            file_path);

    if isempty(variables_in_file)
        return;
    end

    variable_names = ...
        {variables_in_file.name};

    fields_to_load = ...
        requested_fields( ...
            ismember( ...
                requested_fields, ...
                variable_names));

    fields_to_load = ...
        unique( ...
            fields_to_load, ...
            'stable');

    if isempty(fields_to_load)
        return;
    end

    loaded = ...
        load( ...
            file_path, ...
            fields_to_load{:});
end


% ========================================================================
% NESTED PLANE ENTRY EXISTS - PASS 1
% ========================================================================

function tf = ...
        nested_plane_entry_exists_pass1( ...
            values, ...
            m, ...
            p)

    tf = false;

    if ~iscell(values) || ...
            m < 1 || ...
            m > numel(values)

        return;
    end

    values_m = ...
        values{m};

    if ~iscell(values_m) || ...
            p < 1 || ...
            p > numel(values_m)

        return;
    end

    tf = true;
end


% ========================================================================
% GET NESTED PLANE VALUE - PASS 1
% ========================================================================

function value = ...
        get_nested_plane_value_pass1( ...
            values, ...
            m, ...
            p)

    value = [];

    if ~nested_plane_entry_exists_pass1( ...
            values, ...
            m, ...
            p)

        return;
    end

    value = ...
        values{m}{p};
end


% ========================================================================
% FIND EXISTING FINAL CELLPOSE NPY - PASS 1
%
% Recherche non interactive du masque FINAL utilisé pour l'extraction ROI.
%
% Priorité :
%   1) chemin déjà mémorisé dans cellpose_npy_file_path_by_plane ;
%   2) chemin enregistré dans roi_extraction_npy_signature_by_plane ;
%   3) gcamp_reference_*_seg.npy dans le dossier de sortie du plan.
% ========================================================================

function npy_file_path = ...
        find_existing_final_cellpose_npy_pass1( ...
            data, ...
            gcamp_output_folders, ...
            m, ...
            p)

    npy_file_path = '';

    if electroporated_plane_slot_exists( ...
            data, ...
            'cellpose_npy_file_path_by_plane', ...
            m, ...
            p)

        candidate = ...
            data.electroporated_plane. ...
                cellpose_npy_file_path_by_plane{m}{p};

        if (ischar(candidate) || isstring(candidate)) && ...
                ~isempty(candidate) && ...
                isfile(char(candidate))

            npy_file_path = ...
                char(candidate);

            return;
        end
    end

    if isfield(data, 'electroporated_plane') && ...
            isfield( ...
                data.electroporated_plane, ...
                'roi_extraction_npy_signature_by_plane') && ...
            nested_plane_entry_exists_pass1( ...
                data.electroporated_plane. ...
                    roi_extraction_npy_signature_by_plane, ...
                m, ...
                p)

        signature = ...
            get_nested_plane_value_pass1( ...
                data.electroporated_plane. ...
                    roi_extraction_npy_signature_by_plane, ...
                m, ...
                p);

        if isstruct(signature) && ...
                isfield(signature, 'path') && ...
                ~isempty(signature.path) && ...
                isfile(char(string(signature.path)))

            npy_file_path = ...
                char(string(signature.path));

            return;
        end
    end

    output_folder_p = '';

    if iscell(gcamp_output_folders) && ...
            numel(gcamp_output_folders) >= m && ...
            ~isempty(gcamp_output_folders{m})

        folders_m = ...
            gcamp_output_folders{m};

        if iscell(folders_m)

            if numel(folders_m) >= p && ...
                    ~isempty(folders_m{p})

                output_folder_p = ...
                    char(string(folders_m{p}));
            end

        elseif p == 1

            output_folder_p = ...
                char(string(folders_m));
        end
    end

    if isempty(output_folder_p) || ...
            ~isfolder(output_folder_p)

        return;
    end

    candidates = ...
        dir( ...
            fullfile( ...
                output_folder_p, ...
                'gcamp_reference_*_seg.npy'));

    if isempty(candidates)
        return;
    end

    [~, order] = ...
        sort( ...
            [candidates.datenum], ...
            'descend');

    candidate = ...
        fullfile( ...
            candidates(order(1)).folder, ...
            candidates(order(1)).name);

    if isfile(candidate)

        npy_file_path = ...
            candidate;
    end
end


% ========================================================================
% NPY FILE SIGNATURE - PASS 1
% ========================================================================

function signature = ...
        get_npy_file_signature_pass1( ...
            npy_file_path)

    signature = [];

    if isempty(npy_file_path) || ...
            ~(ischar(npy_file_path) || ...
              isstring(npy_file_path))

        return;
    end

    npy_file_path = ...
        char(npy_file_path);

    if ~isfile(npy_file_path)
        return;
    end

    file_info = ...
        dir(npy_file_path);

    if isempty(file_info)
        return;
    end

    signature = struct();

    signature.path = ...
        npy_file_path;

    signature.bytes = ...
        file_info(1).bytes;

    signature.datenum = ...
        file_info(1).datenum;
end


% ========================================================================
% COMPARE NPY SIGNATURES - PASS 1
% ========================================================================

function signatures_match = ...
        compare_npy_signatures_pass1( ...
            saved_signature, ...
            current_signature)

    signatures_match = false;

    if ~isstruct(saved_signature) || ...
            ~isstruct(current_signature)

        return;
    end

    required_fields = { ...
        'path', ...
        'bytes', ...
        'datenum'};

    for k = 1:numel(required_fields)

        field_name = ...
            required_fields{k};

        if ~isfield(saved_signature, field_name) || ...
                ~isfield(current_signature, field_name)

            return;
        end
    end

    saved_path = ...
        char( ...
            string( ...
                saved_signature.path));

    current_path = ...
        char( ...
            string( ...
                current_signature.path));

    same_path = ...
        strcmpi( ...
            saved_path, ...
            current_path);

    same_size = ...
        isequal( ...
            double(saved_signature.bytes), ...
            double(current_signature.bytes));

    saved_date = ...
        double( ...
            saved_signature.datenum);

    current_date = ...
        double( ...
            current_signature.datenum);

    same_date = ...
        isfinite(saved_date) && ...
        isfinite(current_date) && ...
        abs(saved_date - current_date) < 1e-10;

    signatures_match = ...
        same_path && ...
        same_size && ...
        same_date;
end
