function gcamp_plane = process_gcamp_cells( ...
    gcamp_output_folders, ...
    current_gcamp_folders_group, ...
    meanImgs_gcamp, ...
    data)

    numAcquisitions = numel(gcamp_output_folders);

    fields_gcamp_saved = { ...
        'F_gcamp_by_plane', ...
        'F_deconv_gcamp_by_plane', ...
        'stat_by_plane', ...
        'iscell_gcamp_by_plane', ...
        'iscell_idx_gcamp_by_plane', ...
        'stat_false_by_plane', ...
        'iscell_false_by_plane', ...
        'outlines_gcampx_by_plane', ...
        'outlines_gcampy_by_plane', ...
        'gcamp_mask_by_plane', ...
        'gcamp_props_by_plane', ...
        'imageHeight_by_plane', ...
        'imageWidth_by_plane', ...
        'outlines_gcampx_false_by_plane', ...
        'outlines_gcampy_false_by_plane', ...
        'gcamp_mask_false_by_plane', ...
        'gcamp_props_false_by_plane' ...
    };

    fields_gcamp_memory = { ...
        'ops_suite2p_by_plane', ...
        'gcamp_fall_path_by_plane' ...
    };

    fields_gcamp_all = [ ...
        fields_gcamp_saved, ...
        fields_gcamp_memory ...
    ];

    if isempty(data)
        data = struct();
    end

    if ~isfield(data, 'gcamp_plane') || ...
            ~isstruct(data.gcamp_plane) || ...
            isempty(data.gcamp_plane)

        data.gcamp_plane = struct();
    end

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('GCAMP CELL PROCESSING\n');
    fprintf('Acquisitions: %d\n', numAcquisitions);
    fprintf('============================================================\n');

    for m = 1:numAcquisitions

        % =========================================================
        % Acquisition paths
        % =========================================================

        if isempty(current_gcamp_folders_group) || ...
                m > numel(current_gcamp_folders_group) || ...
                isempty(current_gcamp_folders_group{m})

            gcamp_planes = {};

        else

            gcamp_planes = ...
                current_gcamp_folders_group{m};
        end

        if ischar(gcamp_planes) || isstring(gcamp_planes)
            gcamp_planes = {char(gcamp_planes)};
        end

        nPlanes = numel(gcamp_planes);

        tseries_name = get_acquisition_name( ...
            gcamp_planes, ...
            gcamp_output_folders, ...
            m);

        fprintf('\n');
        fprintf('------------------------------------------------------------\n');
        fprintf('GCaMP acquisition %d/%d\n', ...
            m, numAcquisitions);
        fprintf('TSeries: %s\n', tseries_name);
        fprintf('Planes : %d\n', nPlanes);
        fprintf('------------------------------------------------------------\n');

        if nPlanes == 0

            fprintf('Status: no GCaMP planes available.\n');
            continue;
        end

        % =========================================================
        % Output folder
        % =========================================================

        root_folder_m = extract_gcamp_root_folder( ...
            gcamp_output_folders, ...
            m);

        if isempty(root_folder_m)

            warning( ...
                'process_gcamp_cells:MissingOutputFolder', ...
                ['Acquisition %d/%d | %s | unable to determine ' ...
                'output folder.'], ...
                m, numAcquisitions, tseries_name);

            fprintf('Status: skipped because output folder is missing.\n');
            continue;
        end

        fprintf('Output folder: %s\n', root_folder_m);

        filePath_gcamp = fullfile( ...
            root_folder_m, ...
            'results_gcamp.mat');
        
        % =========================================================
        % Check memory completeness BEFORE creating empty placeholders
        % =========================================================

        [already_complete, missing] = ...
            gcamp_group_already_complete( ...
                data, ...
                m, ...
                nPlanes);

        fprintf('\nMemory status\n');

        if already_complete

            fprintf('  Status: all required GCaMP data are already in memory.\n');
            fprintf('  Action: results_gcamp.mat will not be opened.\n');

        else

            fprintf('  Status: GCaMP data are incomplete in memory.\n');
            fprintf('  Missing entries: %d\n', numel(missing));

            for i_missing = 1:numel(missing)

                fprintf('    Plane %d | %s\n', ...
                    missing(i_missing).plane, ...
                    missing(i_missing).field);
            end

            % =====================================================
            % Reload ONLY missing variables from results_gcamp.mat
            % =====================================================

            if exist(filePath_gcamp, 'file') == 2

                missing_field_names = ...
                    unique( ...
                        {missing.field}, ...
                        'stable');

                file_variables = ...
                    whos( ...
                        '-file', ...
                        filePath_gcamp);

                file_variable_names = ...
                    {file_variables.name};

                fields_to_load = ...
                    missing_field_names( ...
                        ismember( ...
                            missing_field_names, ...
                            file_variable_names));

                fprintf('\nSaved data\n');
                fprintf('  Status: results_gcamp.mat found.\n');
                fprintf('  File  : %s\n', filePath_gcamp);

                if isempty(fields_to_load)

                    fprintf('  Action: none of the missing fields are stored in the file.\n');

                else

                    fprintf('  Action: loading only missing variables:\n');

                    for i_field = 1:numel(fields_to_load)

                        fprintf('    %s\n', fields_to_load{i_field});
                    end

                    try

                        loaded = ...
                            load( ...
                                filePath_gcamp, ...
                                fields_to_load{:});

                        data = ...
                            merge_loaded_gcamp_into_data( ...
                                data, ...
                                loaded, ...
                                fields_to_load, ...
                                m, ...
                                nPlanes);

                    catch ME

                        warning( ...
                            'process_gcamp_cells:ResultsLoadFailed', ...
                            ['Acquisition %d/%d | %s | unable to load ' ...
                            'missing fields from results_gcamp.mat: %s'], ...
                            m, numAcquisitions, ...
                            tseries_name, ME.message);

                        fprintf('  Status: saved data could not be loaded.\n');
                    end
                end

            else

                fprintf('\nSaved data\n');
                fprintf('  Status: results_gcamp.mat not found.\n');
                fprintf('  Action: missing fields will be calculated.\n');
            end
        end

        % =========================================================
        % Record which SAVED fields genuinely existed before creating
        % empty storage slots. Empty values count as present.
        % =========================================================

        saved_presence = ...
            get_gcamp_saved_presence( ...
                data, ...
                fields_gcamp_saved, ...
                m, ...
                nPlanes);

        % =========================================================
        % Initialize storage only AFTER the memory/disk checks.
        % This prevents empty placeholders from being mistaken for data.
        % =========================================================

        data = ...
            init_gcamp_plane_struct_if_needed( ...
                data, ...
                numAcquisitions, ...
                fields_gcamp_all);

        for f = 1:numel(fields_gcamp_all)

            data = ...
                ensure_gcamp_plane_cell( ...
                    data, ...
                    fields_gcamp_all{f}, ...
                    m, ...
                    nPlanes);
        end

        for p = 1:nPlanes

            if isempty(gcamp_planes{p})

                data.gcamp_plane. ...
                    gcamp_fall_path_by_plane{m}{p} = '';

            else

                data.gcamp_plane. ...
                    gcamp_fall_path_by_plane{m}{p} = ...
                    char(string(gcamp_planes{p}));
            end
        end

        has_new_data_for_acquisition = false;

        % =========================================================
        % Processing by plane
        % =========================================================

        for p = 1:nPlanes

            fprintf('\n');
            fprintf('  ----------------------------------------------------------\n');
            fprintf('  GCaMP plane %d/%d\n', p, nPlanes);
            fprintf('  ----------------------------------------------------------\n');

            fall_path = gcamp_planes{p};

            if isempty(fall_path)

                fprintf('  Status: skipped because Suite2p path is empty.\n');
                continue;
            end

            fall_path = char(string(fall_path));

            data.gcamp_plane. ...
                gcamp_fall_path_by_plane{m}{p} = ...
                fall_path;

            fprintf('  Suite2p path: %s\n', fall_path);

            % =====================================================
            % Check which SAVED values were really available
            % =====================================================

            raw_fields = { ...
                'F_gcamp_by_plane', ...
                'F_deconv_gcamp_by_plane', ...
                'stat_by_plane', ...
                'iscell_gcamp_by_plane', ...
                'iscell_idx_gcamp_by_plane', ...
                'stat_false_by_plane', ...
                'iscell_false_by_plane' ...
            };

            true_mask_fields = { ...
                'gcamp_props_by_plane', ...
                'gcamp_mask_by_plane', ...
                'outlines_gcampx_by_plane', ...
                'outlines_gcampy_by_plane' ...
            };

            false_mask_fields = { ...
                'gcamp_props_false_by_plane', ...
                'gcamp_mask_false_by_plane', ...
                'outlines_gcampx_false_by_plane', ...
                'outlines_gcampy_false_by_plane' ...
            };

            already_has_raw = ...
                gcamp_presence_all( ...
                    saved_presence, ...
                    raw_fields, ...
                    p);

            already_has_true_masks = ...
                gcamp_presence_all( ...
                    saved_presence, ...
                    true_mask_fields, ...
                    p);

            % =====================================================
            % Load raw Suite2p data only if at least one raw value is
            % absent from data AND was not recovered from results_gcamp.mat.
            % Existing values are never overwritten.
            % =====================================================

            if ~already_has_raw

                fprintf('\n  Suite2p data\n');
                fprintf('    Status: one or more raw fields are missing.\n');
                fprintf('    Action: loading Suite2p outputs once.\n');

                try

                    [~, ...
                        F, ...
                        F_deconv, ...
                        ops, ...
                        stat, ...
                        iscell_cells, ...
                        iscell_cells_idx, ...
                        stat_false, ...
                        iscell_false] = ...
                        load_data(fall_path);

                    raw_values = { ...
                        F, ...
                        F_deconv, ...
                        stat, ...
                        iscell_cells, ...
                        iscell_cells_idx, ...
                        stat_false, ...
                        iscell_false ...
                    };

                    for i_raw = 1:numel(raw_fields)

                        current_field = ...
                            raw_fields{i_raw};

                        if ~saved_presence.(current_field)(p)

                            data.gcamp_plane.(current_field){m}{p} = ...
                                raw_values{i_raw};

                            saved_presence.(current_field)(p) = ...
                                true;

                            has_new_data_for_acquisition = ...
                                true;
                        end
                    end

                    data.gcamp_plane. ...
                        ops_suite2p_by_plane{m}{p} = ...
                        ops;

                    fprintf('    Status: missing Suite2p fields recovered.\n');

                    if isempty(F)
                        fprintf('    Cells : 0\n');
                    else
                        fprintf('    Cells : %d\n', size(F, 1));
                        fprintf('    Frames: %d\n', size(F, 2));
                    end

                    if isempty(stat_false)
                        fprintf('    Rejected ROIs: 0\n');
                    else
                        fprintf('    Rejected ROIs: %d\n', ...
                            numel(stat_false));
                    end

                catch ME

                    warning( ...
                        'process_gcamp_cells:LoadDataFailed', ...
                        ['Acquisition %d/%d | %s | Plane %d/%d | ' ...
                        'Suite2p loading failed: %s'], ...
                        m, numAcquisitions, ...
                        tseries_name, ...
                        p, nPlanes, ...
                        ME.message);

                    fprintf('    Status: Suite2p loading failed.\n');
                    continue;
                end

            else

                fprintf('\n  Suite2p data\n');
                fprintf('    Status: all raw saved fields already available.\n');

                if ~gcamp_field_slot_exists( ...
                        data, ...
                        'ops_suite2p_by_plane', ...
                        m, p) || ...
                        isempty(data.gcamp_plane. ...
                        ops_suite2p_by_plane{m}{p})

                    data.gcamp_plane. ...
                        ops_suite2p_by_plane{m}{p} = ...
                        load_ops_only(fall_path);
                end
            end

            % Always read the current values from data after the optional
            % memory/disk/Suite2p recovery step.
            stat = ...
                get_gcamp_plane_or_empty( ...
                    data, ...
                    'stat_by_plane', ...
                    m, p);

            iscell_cells = ...
                get_gcamp_plane_or_empty( ...
                    data, ...
                    'iscell_gcamp_by_plane', ...
                    m, p);

            stat_false = ...
                get_gcamp_plane_or_empty( ...
                    data, ...
                    'stat_false_by_plane', ...
                    m, p);

            iscell_false = ...
                get_gcamp_plane_or_empty( ...
                    data, ...
                    'iscell_false_by_plane', ...
                    m, p);

            already_has_raw = ...
                gcamp_presence_all( ...
                    saved_presence, ...
                    raw_fields, ...
                    p);

            already_has_true_masks = ...
                gcamp_presence_all( ...
                    saved_presence, ...
                    true_mask_fields, ...
                    p);

            if isempty(stat_false)

                % stat_false is known and empty: there are no rejected ROIs.
                % False masks are therefore not required.
                already_has_false_masks = ...
                    saved_presence.stat_false_by_plane(p);

            else

                already_has_false_masks = ...
                    gcamp_presence_all( ...
                        saved_presence, ...
                        false_mask_fields, ...
                        p);
            end

            if already_has_raw && ...
                    already_has_true_masks && ...
                    already_has_false_masks

                fprintf('  Raw data      : available.\n');
                fprintf('  True masks    : available.\n');
                fprintf('  Rejected masks: available or not required.\n');
                fprintf('  Action        : no recalculation required.\n');
            end

            % =====================================================
            % Mean image and dimensions
            % =====================================================

            meanImg_plane = [];

            if nargin >= 3 && ...
                    ~isempty(meanImgs_gcamp) && ...
                    m <= numel(meanImgs_gcamp) && ...
                    ~isempty(meanImgs_gcamp{m}) && ...
                    p <= numel(meanImgs_gcamp{m}) && ...
                    ~isempty(meanImgs_gcamp{m}{p})

                meanImg_plane = ...
                    meanImgs_gcamp{m}{p};
            end

            imgSize_ref = [];

            fprintf('\n  Reference image\n');

            if ~isempty(meanImg_plane)

                imgSize_ref = size(meanImg_plane);
                imgSize_ref = imgSize_ref(1:2);

                fprintf('    Status: mean image available.\n');
                fprintf('    Size  : %d x %d pixels\n', ...
                    imgSize_ref(1), ...
                    imgSize_ref(2));

                if ~saved_presence.imageHeight_by_plane(p)

                    data.gcamp_plane. ...
                        imageHeight_by_plane{m}{p} = ...
                        imgSize_ref(1);

                    saved_presence.imageHeight_by_plane(p) = ...
                        true;

                    has_new_data_for_acquisition = true;
                end

                if ~saved_presence.imageWidth_by_plane(p)

                    data.gcamp_plane. ...
                        imageWidth_by_plane{m}{p} = ...
                        imgSize_ref(2);

                    saved_presence.imageWidth_by_plane(p) = ...
                        true;

                    has_new_data_for_acquisition = true;
                end

            else

                fprintf('    Status: no mean image available.\n');
            end

            % =====================================================
            % Build masks for accepted GCaMP ROIs
            % =====================================================

            fprintf('\n  Accepted GCaMP masks\n');

            if already_has_true_masks

                fprintf('    Status: existing accepted-cell masks reused.\n');

            elseif ~isempty(stat) && ~isempty(iscell_cells)

                try
                    valid_cells = ...
                        1:size(iscell_cells, 1);

                    [~, ...
                        outlines_gcampx_plane, ...
                        outlines_gcampy_plane, ...
                        ~, ~, ~, ...
                        gcamp_mask_plane, ...
                        gcamp_props_plane] = ...
                        load_calcium_mask( ...
                            iscell_cells, ...
                            stat, ...
                            valid_cells, ...
                            imgSize_ref);

                    true_mask_values = { ...
                        gcamp_props_plane, ...
                        gcamp_mask_plane, ...
                        outlines_gcampx_plane, ...
                        outlines_gcampy_plane ...
                    };

                    for i_mask = 1:numel(true_mask_fields)

                        current_field = ...
                            true_mask_fields{i_mask};

                        if ~saved_presence.(current_field)(p)

                            data.gcamp_plane.(current_field){m}{p} = ...
                                true_mask_values{i_mask};

                            saved_presence.(current_field)(p) = ...
                                true;

                            has_new_data_for_acquisition = ...
                                true;
                        end
                    end

                    fprintf('    Status: accepted-cell masks created.\n');
                    fprintf('    Masks : %d\n', ...
                        get_mask_count(gcamp_mask_plane));

                catch ME

                    warning( ...
                        'process_gcamp_cells:TrueMaskFailed', ...
                        ['Acquisition %d/%d | %s | Plane %d/%d | ' ...
                        'accepted-cell mask creation failed: %s'], ...
                        m, numAcquisitions, ...
                        tseries_name, ...
                        p, nPlanes, ...
                        ME.message);

                    for i_mask = 1:numel(true_mask_fields)

                        current_field = ...
                            true_mask_fields{i_mask};

                        if ~saved_presence.(current_field)(p)

                            data.gcamp_plane.(current_field){m}{p} = [];
                            saved_presence.(current_field)(p) = true;
                            has_new_data_for_acquisition = true;
                        end
                    end

                    fprintf('    Status: mask creation failed; empty values stored.\n');
                end

            else

                for i_mask = 1:numel(true_mask_fields)

                    current_field = ...
                        true_mask_fields{i_mask};

                    if ~saved_presence.(current_field)(p)

                        data.gcamp_plane.(current_field){m}{p} = [];
                        saved_presence.(current_field)(p) = true;
                        has_new_data_for_acquisition = true;
                    end
                end

                fprintf('    Status: no accepted ROI data available.\n');
            end

            % =====================================================
            % Build masks for rejected GCaMP ROIs
            % =====================================================

            fprintf('\n  Rejected GCaMP masks\n');

            if already_has_false_masks

                fprintf('    Status: existing rejected-cell masks reused.\n');

            elseif ~isempty(stat_false) && ...
                    ~isempty(iscell_false)

                try
                    valid_cells_false = ...
                        1:size(iscell_false, 1);

                    [~, ...
                        outlines_gcampx_false_plane, ...
                        outlines_gcampy_false_plane, ...
                        ~, ~, ~, ...
                        gcamp_mask_false_plane, ...
                        gcamp_props_false_plane] = ...
                        load_calcium_mask( ...
                            iscell_false, ...
                            stat_false, ...
                            valid_cells_false, ...
                            imgSize_ref);

                    false_mask_values = { ...
                        gcamp_props_false_plane, ...
                        gcamp_mask_false_plane, ...
                        outlines_gcampx_false_plane, ...
                        outlines_gcampy_false_plane ...
                    };

                    for i_mask = 1:numel(false_mask_fields)

                        current_field = ...
                            false_mask_fields{i_mask};

                        if ~saved_presence.(current_field)(p)

                            data.gcamp_plane.(current_field){m}{p} = ...
                                false_mask_values{i_mask};

                            saved_presence.(current_field)(p) = ...
                                true;

                            has_new_data_for_acquisition = ...
                                true;
                        end
                    end

                    fprintf('    Status: rejected-cell masks created.\n');
                    fprintf('    Masks : %d\n', ...
                        get_mask_count(gcamp_mask_false_plane));

                catch ME

                    warning( ...
                        'process_gcamp_cells:FalseMaskFailed', ...
                        ['Acquisition %d/%d | %s | Plane %d/%d | ' ...
                        'rejected-cell mask creation failed: %s'], ...
                        m, numAcquisitions, ...
                        tseries_name, ...
                        p, nPlanes, ...
                        ME.message);

                    for i_mask = 1:numel(false_mask_fields)

                        current_field = ...
                            false_mask_fields{i_mask};

                        if ~saved_presence.(current_field)(p)

                            data.gcamp_plane.(current_field){m}{p} = [];
                            saved_presence.(current_field)(p) = true;
                            has_new_data_for_acquisition = true;
                        end
                    end

                    fprintf('    Status: mask creation failed; empty values stored.\n');
                end

            else

                for i_mask = 1:numel(false_mask_fields)

                    current_field = ...
                        false_mask_fields{i_mask};

                    if ~saved_presence.(current_field)(p)

                        data.gcamp_plane.(current_field){m}{p} = [];
                        saved_presence.(current_field)(p) = true;
                        has_new_data_for_acquisition = true;
                    end
                end

                fprintf('    Status: no rejected ROI data available.\n');
            end

            % =====================================================
            % Plane summary
            % =====================================================

            fprintf('\n  Plane summary\n');
            fprintf('    Plane         : %d/%d\n', p, nPlanes);
            fprintf('    Raw data      : %s\n', ...
                logical_status( ...
                    gcamp_presence_all( ...
                        saved_presence, ...
                        raw_fields, ...
                        p)));

            fprintf('    Accepted masks: %s\n', ...
                logical_status( ...
                    gcamp_presence_all( ...
                        saved_presence, ...
                        true_mask_fields, ...
                        p)));

            if isempty(stat_false)

                rejected_ready = ...
                    saved_presence.stat_false_by_plane(p);

            else

                rejected_ready = ...
                    gcamp_presence_all( ...
                        saved_presence, ...
                        false_mask_fields, ...
                        p);
            end

            fprintf('    Rejected masks: %s\n', ...
                logical_status(rejected_ready));
        end

        % =========================================================
        % Save acquisition
        % =========================================================

        save_gcamp_fields_if_needed( ...
            filePath_gcamp, ...
            data, ...
            fields_gcamp_saved, ...
            m, ...
            has_new_data_for_acquisition, ...
            tseries_name);

        fprintf('\nAcquisition summary\n');
        fprintf('  TSeries : %s\n', tseries_name);
        fprintf('  Planes  : %d\n', nPlanes);

        if has_new_data_for_acquisition
            fprintf('  Status  : GCaMP data updated.\n');
        else
            fprintf('  Status  : existing GCaMP data retained.\n');
        end
    end

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('GCAMP CELL PROCESSING COMPLETED\n');
    fprintf('Acquisitions: %d\n', numAcquisitions);
    fprintf('============================================================\n');

    gcamp_plane = data.gcamp_plane;
end


% =====================================================================
% Helpers
% =====================================================================

function [tf, missing] = gcamp_group_already_complete( ...
    data, m, nPlanes)

    core_required_fields = { ...
        'F_gcamp_by_plane', ...
        'F_deconv_gcamp_by_plane', ...
        'stat_by_plane', ...
        'iscell_gcamp_by_plane', ...
        'iscell_idx_gcamp_by_plane', ...
        'stat_false_by_plane', ...
        'iscell_false_by_plane', ...
        'gcamp_props_by_plane', ...
        'gcamp_mask_by_plane', ...
        'outlines_gcampx_by_plane', ...
        'outlines_gcampy_by_plane', ...
        'imageHeight_by_plane', ...
        'imageWidth_by_plane' ...
    };

    false_mask_fields = { ...
        'gcamp_props_false_by_plane', ...
        'gcamp_mask_false_by_plane', ...
        'outlines_gcampx_false_by_plane', ...
        'outlines_gcampy_false_by_plane' ...
    };

    tf = true;

    missing = struct( ...
        'plane', {}, ...
        'field', {});

    if nPlanes == 0
        tf = false;
        return;
    end

    for p = 1:nPlanes

        % ---------------------------------------------------------
        % Fields that are always required.
        % Presence is defined by the existence of the data slot,
        % NOT by ~isempty(value). This is important because [] can be
        % a legitimate saved result (0 cells / 0 rejected ROIs).
        % ---------------------------------------------------------

        for i = 1:numel(core_required_fields)

            fieldName = ...
                core_required_fields{i};

            if ~gcamp_field_slot_exists( ...
                    data, ...
                    fieldName, ...
                    m, ...
                    p)

                tf = false;

                missing(end + 1).plane = p; %#ok<AGROW>
                missing(end).field = fieldName;
            end
        end

        % ---------------------------------------------------------
        % Rejected masks.
        %
        % If stat_false is present and empty, there are no rejected ROIs
        % and the four false-mask fields are not required.
        %
        % If stat_false is absent, its content is unknown, so the false
        % mask fields are also requested from results_gcamp.mat when they
        % are absent. After stat_false is recovered, the plane processing
        % decides whether they are actually necessary.
        % ---------------------------------------------------------

        stat_false_known = ...
            gcamp_field_slot_exists( ...
                data, ...
                'stat_false_by_plane', ...
                m, ...
                p);

        if stat_false_known

            stat_false = ...
                get_gcamp_plane_or_empty( ...
                    data, ...
                    'stat_false_by_plane', ...
                    m, ...
                    p);

            false_masks_required = ...
                ~isempty(stat_false);

        else

            false_masks_required = ...
                true;
        end

        if false_masks_required

            for i = 1:numel(false_mask_fields)

                fieldName = ...
                    false_mask_fields{i};

                if ~gcamp_field_slot_exists( ...
                        data, ...
                        fieldName, ...
                        m, ...
                        p)

                    tf = false;

                    missing(end + 1).plane = p; %#ok<AGROW>
                    missing(end).field = fieldName;
                end
            end
        end
    end
end


function presence = get_gcamp_saved_presence( ...
    data, fields, m, nPlanes)

    presence = struct();

    for f = 1:numel(fields)

        fieldName = ...
            fields{f};

        presence.(fieldName) = ...
            false( ...
                nPlanes, ...
                1);

        for p = 1:nPlanes

            presence.(fieldName)(p) = ...
                gcamp_field_slot_exists( ...
                    data, ...
                    fieldName, ...
                    m, ...
                    p);
        end
    end
end


function tf = gcamp_presence_all( ...
    presence, fieldNames, p)

    tf = true;

    for i = 1:numel(fieldNames)

        fieldName = ...
            fieldNames{i};

        if ~isfield(presence, fieldName) || ...
                numel(presence.(fieldName)) < p || ...
                ~presence.(fieldName)(p)

            tf = false;
            return;
        end
    end
end


function data = init_gcamp_plane_struct_if_needed( ...
    data, numAcquisitions, fields)

    if nargin < 1 || isempty(data)
        data = struct();
    end

    if ~isfield(data, 'gcamp_plane') || ...
            ~isstruct(data.gcamp_plane) || ...
            isempty(data.gcamp_plane)

        data.gcamp_plane = struct();
    end

    for f = 1:numel(fields)

        fieldName = fields{f};

        if ~isfield(data.gcamp_plane, fieldName) || ...
                ~iscell(data.gcamp_plane.(fieldName))

            data.gcamp_plane.(fieldName) = ...
                cell(numAcquisitions, 1);

        elseif numel(data.gcamp_plane.(fieldName)) < ...
                numAcquisitions

            old_values = ...
                data.gcamp_plane.(fieldName);

            new_values = ...
                cell(numAcquisitions, 1);

            new_values(1:numel(old_values)) = ...
                old_values(:);

            data.gcamp_plane.(fieldName) = ...
                new_values;
        end
    end
end


function data = ensure_gcamp_plane_cell( ...
    data, fieldName, m, nPlanes)

    if ~isfield(data.gcamp_plane, fieldName)

        data.gcamp_plane.(fieldName) = ...
            cell(m, 1);
    end

    if numel(data.gcamp_plane.(fieldName)) < m

        new_values = cell(m, 1);

        new_values(1:numel( ...
            data.gcamp_plane.(fieldName))) = ...
            data.gcamp_plane.(fieldName)(:);

        data.gcamp_plane.(fieldName) = ...
            new_values;
    end

    if isempty(data.gcamp_plane.(fieldName){m}) || ...
            ~iscell(data.gcamp_plane.(fieldName){m})

        data.gcamp_plane.(fieldName){m} = ...
            cell(nPlanes, 1);

    elseif numel(data.gcamp_plane.(fieldName){m}) ~= ...
            nPlanes

        old_values = ...
            data.gcamp_plane.(fieldName){m};

        new_values = ...
            cell(nPlanes, 1);

        nCopy = min( ...
            numel(old_values), ...
            nPlanes);

        new_values(1:nCopy) = ...
            old_values(1:nCopy);

        data.gcamp_plane.(fieldName){m} = ...
            new_values;
    end
end


function out = coerce_to_plane_cell( ...
    value, nPlanes)

    out = cell(nPlanes, 1);

    if isempty(value)
        return;
    end

    if iscell(value)

        nCopy = min( ...
            numel(value), ...
            nPlanes);

        out(1:nCopy) = ...
            value(1:nCopy);

    elseif nPlanes >= 1

        out{1} = value;
    end
end


function tf = gcamp_field_slot_exists( ...
    data, fieldName, m, p)

    tf = ...
        isfield(data, 'gcamp_plane') && ...
        isfield(data.gcamp_plane, fieldName) && ...
        numel(data.gcamp_plane.(fieldName)) >= m && ...
        ~isempty(data.gcamp_plane.(fieldName){m}) && ...
        iscell(data.gcamp_plane.(fieldName){m}) && ...
        numel(data.gcamp_plane.(fieldName){m}) >= p;
end


function tf = gcamp_field_has_value( ...
    data, fieldName, m, p)

    tf = ...
        gcamp_field_slot_exists( ...
            data, fieldName, m, p) && ...
        ~isempty(data.gcamp_plane.(fieldName){m}{p});
end


function value = get_gcamp_plane_or_empty( ...
    data, fieldName, m, p)

    value = [];

    if gcamp_field_slot_exists( ...
            data, fieldName, m, p)

        value = ...
            data.gcamp_plane.(fieldName){m}{p};
    end
end


function data = merge_loaded_gcamp_into_data( ...
    data, loaded, fields_gcamp, m, nPlanes)

    for f = 1:numel(fields_gcamp)

        fieldName = fields_gcamp{f};

        if ~isfield(loaded, fieldName)
            continue;
        end

        loaded_field = coerce_to_plane_cell( ...
            loaded.(fieldName), ...
            nPlanes);

        if ~isfield(data.gcamp_plane, fieldName) || ...
                numel(data.gcamp_plane.(fieldName)) < m || ...
                isempty(data.gcamp_plane.(fieldName){m}) || ...
                ~iscell(data.gcamp_plane.(fieldName){m})

            data.gcamp_plane.(fieldName){m} = ...
                loaded_field;

            continue;
        end

        for p = 1:nPlanes

            if ~gcamp_field_slot_exists( ...
                    data, fieldName, m, p)

                data.gcamp_plane.(fieldName){m}{p} = ...
                    loaded_field{p};
            end
        end
    end
end


function root_folder_m = extract_gcamp_root_folder( ...
    gcamp_output_folders, m)

    root_folder_m = '';

    if isempty(gcamp_output_folders) || ...
            m > numel(gcamp_output_folders) || ...
            isempty(gcamp_output_folders{m})

        return;
    end

    this_entry = gcamp_output_folders{m};

    if iscell(this_entry)

        if ~isempty(this_entry) && ...
                ~isempty(this_entry{1})

            root_folder_m = ...
                fileparts(char(string(this_entry{1})));
        end

    elseif ischar(this_entry) || ...
            isstring(this_entry)

        root_folder_m = ...
            char(string(this_entry));
    end
end


function data = assign_empty_true_gcamp_masks_if_missing( ...
    data, m, p)

    fields = { ...
        'outlines_gcampx_by_plane', ...
        'outlines_gcampy_by_plane', ...
        'gcamp_mask_by_plane', ...
        'gcamp_props_by_plane' ...
    };

    for i = 1:numel(fields)

        fieldName = fields{i};

        if ~gcamp_field_slot_exists( ...
                data, fieldName, m, p) || ...
                isempty(data.gcamp_plane.(fieldName){m}{p})

            data.gcamp_plane.(fieldName){m}{p} = [];
        end
    end
end


function data = assign_empty_false_gcamp_masks_if_missing( ...
    data, m, p)

    fields = { ...
        'outlines_gcampx_false_by_plane', ...
        'outlines_gcampy_false_by_plane', ...
        'gcamp_mask_false_by_plane', ...
        'gcamp_props_false_by_plane' ...
    };

    for i = 1:numel(fields)

        fieldName = fields{i};

        if ~gcamp_field_slot_exists( ...
                data, fieldName, m, p) || ...
                isempty(data.gcamp_plane.(fieldName){m}{p})

            data.gcamp_plane.(fieldName){m}{p} = [];
        end
    end
end


function save_gcamp_fields_if_needed( ...
    filePath_gcamp, ...
    data, ...
    fields_gcamp, ...
    m, ...
    has_new_data_for_acquisition, ...
    tseries_name)

    fprintf('\nGCaMP results\n');

    if ~has_new_data_for_acquisition

        fprintf('  TSeries: %s\n', tseries_name);
        fprintf('  Status : no new data.\n');
        fprintf('  Action : results_gcamp.mat unchanged.\n');

        return;
    end

    saveStruct = struct();

    for f = 1:numel(fields_gcamp)

        fieldName = fields_gcamp{f};

        if isfield(data, 'gcamp_plane') && ...
                isfield(data.gcamp_plane, fieldName) && ...
                numel(data.gcamp_plane.(fieldName)) >= m

            saveStruct.(fieldName) = ...
                data.gcamp_plane.(fieldName){m};
        end
    end

    try
        if exist(filePath_gcamp, 'file') == 2

            save( ...
                filePath_gcamp, ...
                '-struct', ...
                'saveStruct', ...
                '-append');

        else

            save( ...
                filePath_gcamp, ...
                '-struct', ...
                'saveStruct');
        end

        fprintf('  TSeries: %s\n', tseries_name);
        fprintf('  Status : results_gcamp.mat updated.\n');
        fprintf('  File   : %s\n', filePath_gcamp);

    catch ME

        warning( ...
            'process_gcamp_cells:SaveFailed', ...
            'TSeries %s | unable to save results_gcamp.mat: %s', ...
            tseries_name, ME.message);

        fprintf('  TSeries: %s\n', tseries_name);
        fprintf('  Status : save failed.\n');
    end
end


function acquisition_name = get_acquisition_name( ...
    gcamp_planes, ...
    gcamp_output_folders, ...
    m)

    acquisition_name = sprintf( ...
        'Acquisition_%d', m);

    candidate_path = '';

    if ~isempty(gcamp_planes) && ...
            ~isempty(gcamp_planes{1})

        candidate_path = ...
            char(string(gcamp_planes{1}));
    end

    if isempty(candidate_path)

        root_folder_m = extract_gcamp_root_folder( ...
            gcamp_output_folders, m);

        candidate_path = root_folder_m;
    end

    if isempty(candidate_path)
        return;
    end

    acquisition_name = find_tseries_name_in_path( ...
        candidate_path);
end


function tseries_name = find_tseries_name_in_path( ...
    path_value)

    tseries_name = 'TSeries_unknown';

    if isempty(path_value)
        return;
    end

    path_value = char(string(path_value));

    while ~isempty(path_value)

        [parent_path, current_name] = ...
            fileparts(path_value);

        if startsWith( ...
                current_name, ...
                'TSeries-', ...
                'IgnoreCase', true)

            tseries_name = current_name;
            return;
        end

        if isempty(parent_path) || ...
                strcmp(parent_path, path_value)

            break;
        end

        path_value = parent_path;
    end
end


function count = get_mask_count(mask_value)

    count = 0;

    if isempty(mask_value)
        return;
    end

    if iscell(mask_value)

        count = numel(mask_value);

    elseif ndims(mask_value) == 3

        count = size(mask_value, 1);

    elseif ismatrix(mask_value)

        count = 1;
    end
end


function text_value = logical_status(tf)

    if tf
        text_value = 'available';
    else
        text_value = 'missing';
    end
end