function selected_groups = process_selected_groups( ...
        selected_groups, ...
        include_electroporated, ...
        automatic_selection, ...
        cellpose_mode)

    if nargin < 1 || isempty(selected_groups)
        return;
    end

    if nargin < 2
        include_electroporated = true;
    end

    if nargin < 4 || isempty(cellpose_mode)
        cellpose_mode = 'interactive';
    end

    type_names = fieldnames(selected_groups);

    for t = 1:numel(type_names)

        current_type = type_names{t};

        numSelectedGroups = ...
            numel(selected_groups.(current_type));

        current_automatic_selection = ...
            automatic_selection.(current_type);

        fprintf('\n');
        fprintf('============================================================\n');
        fprintf('PROCESSING TYPE: %s\n', current_type);
        fprintf('NUMBER OF ANIMALS: %d\n', numSelectedGroups);
        fprintf('CELLPOSE MODE: %s\n', cellpose_mode);
        fprintf('============================================================\n');

        %% =========================================================
        % General processing for all animals
        % ==========================================================

        for k = 1:numSelectedGroups

            current_animal = ...
                selected_groups.(current_type)(k).animal;

            current_line = ...
                selected_groups.(current_type)(k).line;

            current_dates = ...
                selected_groups.(current_type)(k).dates;

            fprintf('\n');
            fprintf('------------------------------------------------------------\n');
            fprintf('Animal %d/%d\n', k, numSelectedGroups);
            fprintf('Type  : %s\n', current_type);
            fprintf('Animal: %s\n', ...
                char(string(current_animal)));
            fprintf('------------------------------------------------------------\n');

            paths = ...
                selected_groups.(current_type)(k).paths;

            gcamp_output_folders = ...
                paths.gcamp_output;

            gcamp_root_folders = ...
                paths.gcamp_root;

            current_ages = ...
                selected_groups.(current_type)(k).ages;

            current_suite2p_group = ...
                paths.suite2p;

            current_TSeries_group = ...
                paths.TSeries;

            date_group_paths = ...
                paths.date;

            data = ...
                selected_groups.(current_type)(k).data;

            metadata = ...
                selected_groups.(current_type)(k).metadata;

            sampling_rate_group = ...
                metadata.gcamp_plane.SamplingRatePlane;

            %% -----------------------------------------------------
            % Mean images
            % ------------------------------------------------------

            meanImgs_gcamp = save_mean_images( ...
                'GCaMP', ...
                current_animal, ...
                current_ages, ...
                current_dates, ...
                gcamp_output_folders, ...
                current_suite2p_group(:, 1));

            data.gcamp_plane.meanImgs_gcamp = ...
                meanImgs_gcamp;

            % ======================================================
            % Electroporated : colonne 2 ou 3
            % ======================================================

            electroporated_column = [];

            for c = [2 3]

                if c > size(current_suite2p_group, 2)
                    continue;
                end

                current_column = ...
                    current_suite2p_group(:, c);

                has_electroporated_data = ...
                    any(cellfun( ...
                        @(x) ~isempty(x) && ...
                        (~ischar(x) || ~isempty(strtrim(x))), ...
                        current_column));

                if has_electroporated_data

                    electroporated_column = c;
                    break;
                end
            end

            if ~isempty(electroporated_column)

                if electroporated_column == 2
                    channel_name = 'Red';
                else
                    channel_name = 'Blue';
                end

                meanImgs_electroporated = save_mean_images( ...
                    channel_name, ...
                    current_animal, ...
                    current_ages, ...
                    current_dates, ...
                    gcamp_output_folders, ...
                    current_suite2p_group(:, electroporated_column));

            else

                meanImgs_electroporated = {};
            end

            data.electroporated_plane.meanImgs_electroporated = ...
                meanImgs_electroporated;

            %% -----------------------------------------------------
            % ZSeries reconstruction
            % ------------------------------------------------------

            if isfield(paths, 'ZSeries') && ...
                    ~isempty(paths.ZSeries)

                zseries = ...
                    load_or_process_zseries( ...
                        paths.ZSeries, ...
                        gcamp_root_folders, ...
                        metadata.ZSeries, ...
                        paths.output_folders, ...
                        current_automatic_selection, ...
                        current_line, ...
                        current_animal, ...
                        current_dates, ...
                        current_ages);

                data.ZSeries = ...
                    zseries;

            else

                data.ZSeries = ...
                    struct();
            end

            %% -----------------------------------------------------
            % Motion energy
            % ------------------------------------------------------

            avg_block = 5;

            motion = load_or_process_movie( ...
                current_TSeries_group(:, 1), ...
                gcamp_output_folders, ...
                avg_block, ...
                sampling_rate_group, ...
                current_animal, ...
                data);

            data.motion = ...
                motion;

            %% -----------------------------------------------------
            % Whisker stimulation
            % ------------------------------------------------------

            data = load_or_process_stims( ...
                date_group_paths, ...
                current_TSeries_group(:, 1), ...
                data);

            %% -----------------------------------------------------
            % GCaMP cells
            % ------------------------------------------------------

            gcamp_plane = process_gcamp_cells( ...
                gcamp_output_folders, ...
                current_suite2p_group(:, 1), ...
                meanImgs_gcamp, ...
                data);

            data.gcamp_plane = ...
                gcamp_plane;

            selected_groups.(current_type)(k).data = ...
                data;
        end

        %% =========================================================
        % Cellpose preparation
        % ==========================================================

        processing_cache = ...
            cell(numSelectedGroups, 1);

        for k = 1:numSelectedGroups

            current_animal = ...
                selected_groups.(current_type)(k).animal;

            fprintf('\n');
            fprintf('------------------------------------------------------------\n');
            fprintf('Cellpose preparation\n');
            fprintf('Type  : %s\n', current_type);
            fprintf('Animal: %s (%d/%d)\n', ...
                char(string(current_animal)), ...
                k, ...
                numSelectedGroups);
            fprintf('Mode  : %s\n', cellpose_mode);
            fprintf('------------------------------------------------------------\n');

            paths = ...
                selected_groups.(current_type)(k).paths;

            data = ...
                selected_groups.(current_type)(k).data;

            metadata = ...
                selected_groups.(current_type)(k).metadata;

            [processing_cache{k}, data] = ...
                process_electroporated_pass1( ...
                    paths.gcamp_root, ...
                    paths.gcamp_output, ...
                    include_electroporated, ...
                    paths.date, ...
                    paths.TSeries, ...
                    paths.suite2p, ...
                    metadata, ...
                    data, ...
                    cellpose_mode);

            selected_groups.(current_type)(k).data = ...
                data;
        end

        %% =========================================================
        % Electroporated ROI extraction
        % ==========================================================

        for k = 1:numSelectedGroups

            current_animal = ...
                selected_groups.(current_type)(k).animal;

            current_line = ...
                selected_groups.(current_type)(k).line;

            current_dates = ...
                selected_groups.(current_type)(k).dates;

            current_ages = ...
                selected_groups.(current_type)(k).ages;

            fprintf('\n');
            fprintf('------------------------------------------------------------\n');
            fprintf('Electroporated ROI extraction\n');
            fprintf('Type  : %s\n', current_type);
            fprintf('Animal: %s (%d/%d)\n', ...
                char(string(current_animal)), ...
                k, ...
                numSelectedGroups);
            fprintf('------------------------------------------------------------\n');

            paths = ...
                selected_groups.(current_type)(k).paths;

            data = ...
                selected_groups.(current_type)(k).data;

            metadata = ...
                selected_groups.(current_type)(k).metadata;

            % ======================================================
            % LOAD ONLY
            %
            % Les données ont déjà été chargées par PASS 1.
            % Aucun recalcul ROI.
            % ======================================================

            if strcmpi(cellpose_mode, 'load_only')

                fprintf( ...
                    ['LOAD ONLY: existing Electroporated ROI data ' ...
                     'retained.\n']);

                electroporated_plane = ...
                    data.electroporated_plane;

            else

                [electroporated_plane, data] = ...
                    process_electroporated_pass2( ...
                        processing_cache{k}, ...
                        paths.gcamp_output, ...
                        data.gcamp_plane.meanImgs_gcamp, ...
                        data);

                data.electroporated_plane = ...
                    electroporated_plane;
            end

            %% -----------------------------------------------------
            % Combined
            % ------------------------------------------------------

            combined_plane = ...
                combined_gcamp_electroporated_cells( ...
                    paths.gcamp_output, ...
                    data, ...
                    include_electroporated);

            data.combined_plane = ...
                combined_plane;

            selected_groups.(current_type)(k).data = ...
                data;

            %% -----------------------------------------------------
            % Mean image overview
            %
            % IMPORTANT :
            % exécuté AUSSI en load_only.
            % ------------------------------------------------------

            save_mean_image_overviews( ...
                current_line, ...
                current_animal, ...
                current_dates, ...
                current_ages, ...
                current_automatic_selection, ...
                paths.suite2p, ...
                paths.gcamp_root, ...
                paths.output_folders, ...
                data.gcamp_plane.meanImgs_gcamp, ...
                data.electroporated_plane.meanImgs_electroporated, ...
                data.electroporated_plane.alignedImgs_electroporated, ...
                metadata.gcamp_plane, ...
                metadata.electroporated_plane);
        end
    end
end