function selected_groups = process_selected_groups( ...
        selected_groups, include_blue_cells)

    if nargin < 1 || isempty(selected_groups)
        return;
    end

    if nargin < 2
        include_blue_cells = true;
    end

    type_names = fieldnames(selected_groups);

    for t = 1:numel(type_names)

        current_type = type_names{t};

        numSelectedGroups = ...
            numel(selected_groups.(current_type));

        fprintf('\n');
        fprintf('============================================================\n');
        fprintf('PROCESSING TYPE: %s\n', current_type);
        fprintf('NUMBER OF ANIMALS: %d\n', numSelectedGroups);
        fprintf('============================================================\n');

        %% =========================================================
        % General processing for all animals
        % ==========================================================

        for k = 1:numSelectedGroups

            current_animal = ...
                selected_groups.(current_type)(k).animal;

            fprintf('\n');
            fprintf('------------------------------------------------------------\n');
            fprintf('Animal %d/%d\n', k, numSelectedGroups);
            fprintf('Type  : %s\n', current_type);
            fprintf('Animal: %s\n', ...
                char(string(current_animal)));
            fprintf('------------------------------------------------------------\n');

            paths = ...
                selected_groups.(current_type)(k).paths;

            gcamp_output_folders = ...
                paths.gcamp_output;

            current_ages = ...
                selected_groups.(current_type)(k).ages;

            current_suite2p_group = ...
                paths.suite2p;

            current_TSeries_group = ...
                paths.TSeries;

            date_group_paths = ...
                paths.date;

            data = ...
                selected_groups.(current_type)(k).data;

            metadata = ...
                selected_groups.(current_type)(k).metadata;

            sampling_rate_group = ...
                metadata.SamplingRatePlane;

            %% -----------------------------------------------------
            % Mean images
            % ------------------------------------------------------

            meanImgs_gcamp = save_mean_images( ...
                'GCaMP', ...
                current_animal, ...
                current_ages, ...
                gcamp_output_folders, ...
                current_suite2p_group(:, 1));

            meanImgs_blue = save_mean_images( ...
                'Electroporated', ...
                current_animal, ...
                current_ages, ...
                gcamp_output_folders, ...
                current_suite2p_group(:, 3));

            data.meanImgs_gcamp = ...
                meanImgs_gcamp;

            data.meanImgs_blue = ...
                meanImgs_blue;

            %% -----------------------------------------------------
            % Motion energy
            % ------------------------------------------------------

            avg_block = 5;

            motion = load_or_process_movie( ...
                current_TSeries_group(:, 1), ...
                gcamp_output_folders, ...
                avg_block, ...
                sampling_rate_group, ...
                current_animal, ...
                data);

            data.motion = motion;

            %% -----------------------------------------------------
            % Whisker stimulation
            % ------------------------------------------------------

            data = load_or_process_stims( ...
                date_group_paths, ...
                current_TSeries_group(:, 1), ...
                data);

            %% -----------------------------------------------------
            % GCaMP cells
            % ------------------------------------------------------

            gcamp_plane = process_gcamp_cells( ...
                gcamp_output_folders, ...
                current_suite2p_group(:, 1), ...
                meanImgs_gcamp, ...
                data);

            data.gcamp_plane = ...
                gcamp_plane;

            %% -----------------------------------------------------
            % Save current animal data
            % ------------------------------------------------------

            selected_groups.(current_type)(k).data = ...
                data;
        end

        %% =========================================================
        % Cellpose preparation for all animals
        % ==========================================================

        blue_processing_cache = ...
            cell(numSelectedGroups, 1);

        for k = 1:numSelectedGroups

            current_animal = ...
                selected_groups.(current_type)(k).animal;

            fprintf('\n');
            fprintf('------------------------------------------------------------\n');
            fprintf('Cellpose preparation\n');
            fprintf('Type  : %s\n', current_type);
            fprintf('Animal: %s (%d/%d)\n', ...
                char(string(current_animal)), ...
                k, ...
                numSelectedGroups);
            fprintf('------------------------------------------------------------\n');

            paths = ...
                selected_groups.(current_type)(k).paths;

            data = ...
                selected_groups.(current_type)(k).data;

            [blue_processing_cache{k}, data] = ...
                process_blue_cells_pass1( ...
                    paths.gcamp_output, ...
                    include_blue_cells, ...
                    paths.date, ...
                    paths.TSeries(:, 3), ...
                    paths.suite2p(:, 1), ...
                    paths.suite2p(:, 2), ...
                    paths.suite2p(:, 3), ...
                    paths.suite2p(:, 4), ...
                    data);

            selected_groups.(current_type)(k).data = ...
                data;
        end

        %% =========================================================
        % Blue ROI extraction for all animals
        % ==========================================================

        for k = 1:numSelectedGroups

            current_animal = ...
                selected_groups.(current_type)(k).animal;

            fprintf('\n');
            fprintf('------------------------------------------------------------\n');
            fprintf('Electroporated ROI extraction\n');
            fprintf('Type  : %s\n', current_type);
            fprintf('Animal: %s (%d/%d)\n', ...
                char(string(current_animal)), ...
                k, ...
                numSelectedGroups);
            fprintf('------------------------------------------------------------\n');

            paths = ...
                selected_groups.(current_type)(k).paths;

            data = ...
                selected_groups.(current_type)(k).data;

            [blue_plane, data] = ...
                process_blue_cells_pass2( ...
                    blue_processing_cache{k}, ...
                    paths.gcamp_output, ...
                    data.meanImgs_gcamp, ...
                    data);

            data.blue_plane = ...
                blue_plane;

            %% -----------------------------------------------------
            % Combined GCaMP + electroporated cells
            % ------------------------------------------------------

            combined_plane = ...
                combined_gcamp_blue_cells( ...
                    paths.gcamp_output, ...
                    data, ...
                    include_blue_cells);

            data.combined_plane = ...
                combined_plane;

            %% -----------------------------------------------------
            % Save current animal data
            % ------------------------------------------------------

            selected_groups.(current_type)(k).data = ...
                data;
        end
    end
end