function data = run_gcamp_peak_detection( ...
    current_type, ...
    current_line, ...
    animal, ...
    current_ages, ...
    gcamp_output_folders, ...
    metadata, ...
    sampling_rate_group, ...
    synchronous_frames_group, ...
    data, ...
    meanImgs_gcamp, ...
    current_gcamp_TSeries_path, ...
    include_electroporated, ...
    peak_detection_mode, ...
    current_automatic_selection, ...
    current_output_folder)

    numFolders = numel(gcamp_output_folders);

    % ==========================================================
    % Defaults
    % ==========================================================
    if nargin < 12 || isempty(include_electroporated)
        include_electroporated = '1';
    end

    if nargin < 13 || isempty(peak_detection_mode)
        peak_detection_mode = 'global';
    end

    include_electroporated = ...
        char(string(include_electroporated));

    process_electroporated_combined = ...
        strcmp(include_electroporated, '1');

    % ==========================================================
    % Detection fields GCaMP
    % ==========================================================
    fields_detect_gcamp = { ...
        'F0_gcamp_by_plane', ...
        'noise_est_gcamp_by_plane', ...
        'DF_gcamp_by_plane', ...
        'DF_raw_gcamp_by_plane', ...
        'valid_gcamp_cells_by_plane', ...
        'Raster_gcamp_by_plane', ...
        'Acttmp2_gcamp_by_plane', ...
        'MAct_gcamp_by_plane', ...
        'thresholds_gcamp_by_plane', ...
        'bad_segs_gcamp_plane', ...
        'opts_detection_gcamp_by_plane', ...
        'isort1_gcamp_by_plane', ...
        'isort2_gcamp_by_plane', ...
        'Sm_gcamp_by_plane' ...
    };

    % ==========================================================
    % Detection fields electroporated
    % ==========================================================
    fields_detect_electroporated = { ...
        'F0_electroporated_by_plane', ...
        'noise_est_electroporated_by_plane', ...
        'DF_electroporated_by_plane', ...
        'DF_raw_electroporated_by_plane', ...
        'valid_electroporated_cells_by_plane', ...
        'Raster_electroporated_by_plane', ...
        'Acttmp2_electroporated_by_plane', ...
        'MAct_electroporated_by_plane', ...
        'thresholds_electroporated_by_plane', ...
        'bad_segs_electroporated_plane', ...
        'opts_detection_electroporated_by_plane', ...
        'isort1_electroporated_by_plane', ...
        'isort2_electroporated_by_plane', ...
        'Sm_electroporated_by_plane' ...
    };

    % ==========================================================
    % Detection fields combined
    % ==========================================================
    fields_detect_combined = { ...
        'F0_combined_by_plane', ...
        'noise_est_combined_by_plane', ...
        'DF_combined_by_plane', ...
        'DF_raw_combined_by_plane', ...
        'valid_combined_cells_by_plane', ...
        'Raster_combined_by_plane', ...
        'Acttmp2_combined_by_plane', ...
        'MAct_combined_by_plane', ...
        'thresholds_combined_by_plane', ...
        'bad_segs_combined_plane', ...
        'opts_detection_combined_by_plane', ...
        'isort1_combined_by_plane', ...
        'isort2_combined_by_plane', ...
        'Sm_combined_by_plane' ...
    };

    % ==========================================================
    % Motion
    % ==========================================================
    fields_motion_group = { ...
        'speed_active_group', ...
        'bad_frames_group', ...
        'bad_segs_group', ...
        'deviation_group', ...
        'focus_segs_group', ...
        'motion_energy_group' ...
    };

    % ==========================================================
    % Initialize branches
    % ==========================================================
    data = init_detection_branch_if_needed( ...
        data, ...
        'gcamp_plane', ...
        numFolders, ...
        fields_detect_gcamp);

    if process_electroporated_combined

        data = init_detection_branch_if_needed( ...
            data, ...
            'electroporated_plane', ...
            numFolders, ...
            fields_detect_electroporated);

        data = init_detection_branch_if_needed( ...
            data, ...
            'combined_plane', ...
            numFolders, ...
            fields_detect_combined);
    end

    data = init_motion_group_if_needed( ...
        data, ...
        numFolders, ...
        fields_motion_group);

    % ==========================================================
    % Existing-detection mode
    % ==========================================================
    processing_mode = ...
        lower(strtrim(char(string(peak_detection_mode))));

    global_existing_detection_action = '';

    switch processing_mode

        case 'viewer'

            global_existing_detection_action = ...
                'viewer';

        case 'load_only'

            global_existing_detection_action = ...
                'load_only';

        otherwise

            processing_mode = ...
                'global';
    end

    % ==========================================================
    % RECORDINGS
    % ==========================================================
    for m = 1:numFolders

        has_new_gcamp_group = false;
        has_new_electroporated_group = false;
        has_new_combined_group = false;
        has_new_motion_group = false;

        age_m = ...
            current_ages{m};

        sampling_rate_m = ...
            sampling_rate_group{m};

        sync_frames_m = ...
            synchronous_frames_group{m};

        metadata_m = ...
            get_metadata_for_record( ...
                metadata, ...
                m);

        [record_label_m, date_m] = ...
            make_record_label( ...
                animal, ...
                metadata_m, ...
                m);

        % ======================================================
        % Number of planes
        % ======================================================
        if ~isfield(metadata_m, 'NumPlanes') || ...
                isempty(metadata_m.NumPlanes)

            error( ...
                'Metadata missing NumPlanes for group %d.', ...
                m);
        end

        nPlanes = ...
            max( ...
                1, ...
                round(double(metadata_m.NumPlanes)));

        % ======================================================
        % Initialize plane slots
        % ======================================================
        for f = 1:numel(fields_detect_gcamp)

            data = ensure_branch_plane_cell( ...
                data, ...
                'gcamp_plane', ...
                fields_detect_gcamp{f}, ...
                m, ...
                nPlanes);
        end

        if process_electroporated_combined

            for f = 1:numel(fields_detect_electroporated)

                data = ensure_branch_plane_cell( ...
                    data, ...
                    'electroporated_plane', ...
                    fields_detect_electroporated{f}, ...
                    m, ...
                    nPlanes);
            end

            for f = 1:numel(fields_detect_combined)

                data = ensure_branch_plane_cell( ...
                    data, ...
                    'combined_plane', ...
                    fields_detect_combined{f}, ...
                    m, ...
                    nPlanes);
            end
        end

        % ======================================================
        % Mean images
        % ======================================================
        if m <= numel(meanImgs_gcamp) && ...
                ~isempty(meanImgs_gcamp{m})

            meanImgs_m = ...
                meanImgs_gcamp{m};

        else

            meanImgs_m = ...
                cell(nPlanes, 1);
        end

        % ======================================================
        % GCaMP TSeries
        % ======================================================
        if m <= numel(current_gcamp_TSeries_path) && ...
                ~isempty(current_gcamp_TSeries_path{m})

            TSeries_m = ...
                current_gcamp_TSeries_path{m};

        else

            TSeries_m = '';
        end

        % ======================================================
        % Stim frames
        % ======================================================
        stim_frames_m = [];

        if isfield(data, 'stim') && ...
                isfield(data.stim, 'stim_frames_log_group') && ...
                isfield(data.stim, 'stim_protocol_group') && ...
                numel(data.stim.stim_frames_log_group) >= m && ...
                numel(data.stim.stim_protocol_group) >= m

            stim_frames_tmp = ...
                data.stim.stim_frames_log_group{m};

            stim_protocol_tmp = ...
                data.stim.stim_protocol_group{m};

            if ~isempty(stim_frames_tmp) && ...
                    ~isempty(stim_protocol_tmp)

                stim_frames_tmp = ...
                    stim_frames_tmp(:);

                stim_protocol_tmp = ...
                    stim_protocol_tmp(:);

                n = ...
                    min( ...
                        numel(stim_frames_tmp), ...
                        numel(stim_protocol_tmp));

                stim_frames_tmp = ...
                    stim_frames_tmp(1:n);

                stim_protocol_tmp = ...
                    stim_protocol_tmp(1:n);

                stim_frames_m = ...
                    stim_frames_tmp( ...
                        stim_protocol_tmp == 0);
            end
        end

        % ======================================================
        % Recording output folder
        % ======================================================
        current_output_folders = [];

        if m <= numel(gcamp_output_folders)

            current_output_folders = ...
                gcamp_output_folders{m};
        end

        if ischar(current_output_folders) || ...
                isstring(current_output_folders)

            current_output_folders = ...
                cellstr(current_output_folders);
        end

        if isempty(current_output_folders) || ...
                ~iscell(current_output_folders)

            fprintf( ...
                ['%s: aucun dossier de sortie GCaMP, ' ...
                 'enregistrement ignoré.\n'], ...
                record_label_m);

            continue;
        end

        valid_output_index = ...
            find( ...
                ~cellfun(@isempty, current_output_folders), ...
                1, ...
                'first');

        if isempty(valid_output_index)

            fprintf( ...
                ['%s: tous les dossiers de sortie des plans sont ' ...
                 'vides, enregistrement ignoré.\n'], ...
                record_label_m);

            continue;
        end

        first_output_folder = ...
            current_output_folders{valid_output_index};

        if isstring(first_output_folder)
            first_output_folder = char(first_output_folder);
        end

        if ~ischar(first_output_folder) || ...
                isempty(strtrim(first_output_folder))

            fprintf( ...
                '%s: dossier de sortie GCaMP invalide.\n', ...
                record_label_m);

            continue;
        end

        outdir_m = ...
            fileparts(first_output_folder);

        if isempty(outdir_m)
            outdir_m = first_output_folder;
        end

        if exist(outdir_m, 'dir') ~= 7
            mkdir(outdir_m);
        end

        % ======================================================
        % Results paths
        % ======================================================
        filePath_gcamp = ...
            fullfile( ...
                outdir_m, ...
                'results_gcamp.mat');

        filePath_electroporated = ...
            fullfile( ...
                outdir_m, ...
                'results_electroporated.mat');

        filePath_combined = ...
            fullfile( ...
                outdir_m, ...
                'results_combined.mat');

        filePath_motion = ...
            fullfile( ...
                outdir_m, ...
                'results_motion.mat');

        % ======================================================
        % Old motion filename migration
        % ======================================================
        oldMotionPath = ...
            fullfile( ...
                outdir_m, ...
                'results_movie.mat');

        if exist(oldMotionPath, 'file') == 2 && ...
                exist(filePath_motion, 'file') ~= 2

            movefile( ...
                oldMotionPath, ...
                filePath_motion);

            fprintf( ...
                '%s: renamed results_movie.mat -> results_motion.mat\n', ...
                record_label_m);
        end

        % ======================================================
        % Load GCaMP detection if memory incomplete
        % ======================================================
        missing_gcamp = ...
            branch_has_missing_fields( ...
                data, ...
                'gcamp_plane', ...
                fields_detect_gcamp, ...
                m, ...
                nPlanes);

        if missing_gcamp

            if exist(filePath_gcamp, 'file') == 2

                fprintf( ...
                    ['%s : chargement de results_gcamp.mat ' ...
                     '(mémoire incomplète).\n'], ...
                    record_label_m);

                loaded_gcamp = ...
                    load(filePath_gcamp);

                data = ...
                    merge_loaded_branch_into_data( ...
                        data, ...
                        'gcamp_plane', ...
                        loaded_gcamp, ...
                        fields_detect_gcamp, ...
                        m, ...
                        nPlanes);

            else

                fprintf( ...
                    '%s : results_gcamp.mat absent.\n', ...
                    record_label_m);
            end

        else

            fprintf( ...
                ['%s : données GCaMP déjà complètes en mémoire, ' ...
                 'pas de reload.\n'], ...
                record_label_m);
        end

        % ======================================================
        % Electroporated + combined detections
        % ======================================================
        if process_electroporated_combined

            missing_electroporated = ...
                branch_has_missing_fields( ...
                    data, ...
                    'electroporated_plane', ...
                    fields_detect_electroporated, ...
                    m, ...
                    nPlanes);

            if missing_electroporated

                if exist(filePath_electroporated, 'file') == 2

                    fprintf( ...
                        ['%s : chargement de ' ...
                         'results_electroporated.mat.\n'], ...
                        record_label_m);

                    loaded_electroporated = ...
                        load(filePath_electroporated);

                    data = ...
                        merge_loaded_branch_into_data( ...
                            data, ...
                            'electroporated_plane', ...
                            loaded_electroporated, ...
                            fields_detect_electroporated, ...
                            m, ...
                            nPlanes);

                else

                    fprintf( ...
                        '%s : results_electroporated.mat absent.\n', ...
                        record_label_m);
                end
            end

            missing_combined = ...
                branch_has_missing_fields( ...
                    data, ...
                    'combined_plane', ...
                    fields_detect_combined, ...
                    m, ...
                    nPlanes);

            if missing_combined

                if exist(filePath_combined, 'file') == 2

                    fprintf( ...
                        ['%s : chargement de ' ...
                         'results_combined.mat.\n'], ...
                        record_label_m);

                    loaded_combined = ...
                        load(filePath_combined);

                    data = ...
                        merge_loaded_branch_into_data( ...
                            data, ...
                            'combined_plane', ...
                            loaded_combined, ...
                            fields_detect_combined, ...
                            m, ...
                            nPlanes);

                else

                    fprintf( ...
                        '%s : results_combined.mat absent.\n', ...
                        record_label_m);
                end
            end
        end

        % ======================================================
        % Motion
        % ======================================================
        missing_motion = ...
            motion_group_has_missing_fields( ...
                data, ...
                fields_motion_group, ...
                m);

        if missing_motion

            if exist(filePath_motion, 'file') == 2

                loaded_motion = ...
                    load(filePath_motion);

                data = ...
                    merge_loaded_motion_group_into_data( ...
                        data, ...
                        loaded_motion, ...
                        fields_motion_group, ...
                        m);
            end
        end

        speed_active_group = ...
            get_motion_group_or_empty( ...
                data, ...
                'speed_active_group', ...
                m);

        bad_frames_group = ...
            get_motion_group_or_empty( ...
                data, ...
                'bad_frames_group', ...
                m);

        bad_segs_group = ...
            get_motion_group_or_empty( ...
                data, ...
                'bad_segs_group', ...
                m);

        deviation_group = ...
            get_motion_group_or_empty( ...
                data, ...
                'deviation_group', ...
                m);

        focus_segs_group = ...
            get_motion_group_or_empty( ...
                data, ...
                'focus_segs_group', ...
                m);

        motion_energy_group = ...
            get_motion_group_or_empty( ...
                data, ...
                'motion_energy_group', ...
                m);

        % ======================================================
        % Motion reference ops
        % ======================================================
        ops_motion_ref = [];

        for pp = 1:nPlanes

            ops_motion_ref = ...
                get_branch_plane_or_empty( ...
                    data, ...
                    'gcamp_plane', ...
                    'ops_suite2p_by_plane', ...
                    m, ...
                    pp);

            if isempty(ops_motion_ref) && ...
                    process_electroporated_combined

                ops_motion_ref = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'electroporated_plane', ...
                        'ops_suite2p_electroporated_by_plane', ...
                        m, ...
                        pp);
            end

            if ~isempty(ops_motion_ref)
                break;
            end
        end

        motion_group_incomplete = ...
            isempty(bad_frames_group) || ...
            isempty(bad_segs_group) || ...
            isempty(deviation_group) || ...
            isempty(focus_segs_group) || ...
            isempty(motion_energy_group);

        if motion_group_incomplete

            if ~isempty(ops_motion_ref) && ...
                    isfield(ops_motion_ref, 'corrXY') && ...
                    ~isempty(ops_motion_ref.corrXY)

                corrXY = ...
                    ops_motion_ref.corrXY(:);

                N = ...
                    numel(corrXY);

                rolling_median = ...
                    movmedian( ...
                        corrXY, ...
                        300);

                deviation_group = ...
                    corrXY - rolling_median;

                sigma_dev = ...
                    std( ...
                        deviation_group( ...
                            deviation_group < 0), ...
                        'omitnan');

                seuil_bad = ...
                    -3 * sigma_dev;

                bad_frames_logical = ...
                    deviation_group < seuil_bad;

                bad_frames_logical = ...
                    conv( ...
                        double(bad_frames_logical), ...
                        [1 1 1], ...
                        'same') > 0;

                bad_frames_group = ...
                    find(bad_frames_logical);

                bad_frames_group = ...
                    bad_frames_group(:).';

                bad_segs_group = ...
                    badframes_to_segments( ...
                        bad_frames_group, ...
                        N);

                focus_segs_group = ...
                    bad_segs_group;

                deviation_group = ...
                    deviation_group(:).';

                data.motion.bad_frames_group{m} = ...
                    bad_frames_group;

                data.motion.bad_segs_group{m} = ...
                    bad_segs_group;

                data.motion.deviation_group{m} = ...
                    deviation_group;

                data.motion.focus_segs_group{m} = ...
                    focus_segs_group;

                if ~isempty(motion_energy_group)

                    data.motion.motion_energy_group{m} = ...
                        motion_energy_group;
                end

                has_new_motion_group = true;

            else

                warning( ...
                    ['%s: impossible de calculer deviation group : ' ...
                     'corrXY manquant.'], ...
                    record_label_m);
            end
        end

        % ======================================================
        % PLANES
        % ======================================================
        for p = 1:nPlanes

            % ==================================================
            % Plane output folder
            % ==================================================
            gcamp_output_folder_p = '';

            if m <= numel(gcamp_output_folders)

                current_recording_outputs = ...
                    gcamp_output_folders{m};

                if ischar(current_recording_outputs) || ...
                        isstring(current_recording_outputs)

                    current_recording_outputs = ...
                        cellstr(current_recording_outputs);
                end

                if iscell(current_recording_outputs) && ...
                        p <= numel(current_recording_outputs) && ...
                        ~isempty(current_recording_outputs{p})

                    gcamp_output_folder_p = ...
                        current_recording_outputs{p};
                end
            end

            if isstring(gcamp_output_folder_p)
                gcamp_output_folder_p = char(gcamp_output_folder_p);
            end

            if isempty(gcamp_output_folder_p) || ...
                    ~ischar(gcamp_output_folder_p)

                fprintf( ...
                    '%s - plane %d: output folder absent.\n', ...
                    record_label_m, ...
                    p);

                continue;
            end

            if exist(gcamp_output_folder_p, 'dir') ~= 7
                mkdir(gcamp_output_folder_p);
            end

            % ==================================================
            % IMPORTANT:
            %
            % Si electroporated actif :
            % on charge UNIQUEMENT COMBINED.
            %
            % GCaMP =
            %   combined hors electroporated_indices
            %
            % Electroporated =
            %   combined aux electroporated_indices
            % ==================================================
            if process_electroporated_combined

                F_in = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'combined_plane', ...
                        'F_combined_by_plane', ...
                        m, ...
                        p);

                masks_in = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'combined_plane', ...
                        'mask_combined_by_plane', ...
                        m, ...
                        p);

                electroporated_indices_in = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'combined_plane', ...
                        'electroporated_indices_combined_by_plane', ...
                        m, ...
                        p);

                if isempty(F_in)

                    fprintf( ...
                        ['%s - plane %d: combined unavailable, ' ...
                         'plane skipped.\n'], ...
                        record_label_m, ...
                        p);

                    continue;
                end

                % --------------------------------------------------
                % Common Suite2p information comes from GCaMP
                % --------------------------------------------------
                stat_in = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'gcamp_plane', ...
                        'stat_by_plane', ...
                        m, ...
                        p);

                iscell_idx = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'gcamp_plane', ...
                        'iscell_idx_gcamp_by_plane', ...
                        m, ...
                        p);

                ops_in = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'gcamp_plane', ...
                        'ops_suite2p_by_plane', ...
                        m, ...
                        p);

                cell_type = ...
                    'combined';

                % --------------------------------------------------
                % Existing detection = COMBINED
                % --------------------------------------------------
                has_detection_plane = ...
                    has_existing_detection_new( ...
                        data, ...
                        'combined_plane', ...
                        'DF_combined_by_plane', ...
                        m, ...
                        p);

            % ==================================================
            % GCaMP-only mode
            % ==================================================
            else

                F_in = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'gcamp_plane', ...
                        'F_gcamp_by_plane', ...
                        m, ...
                        p);

                masks_in = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'gcamp_plane', ...
                        'gcamp_mask_by_plane', ...
                        m, ...
                        p);

                electroporated_indices_in = [];

                stat_in = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'gcamp_plane', ...
                        'stat_by_plane', ...
                        m, ...
                        p);

                iscell_idx = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'gcamp_plane', ...
                        'iscell_idx_gcamp_by_plane', ...
                        m, ...
                        p);

                ops_in = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        'gcamp_plane', ...
                        'ops_suite2p_by_plane', ...
                        m, ...
                        p);

                cell_type = ...
                    'gcamp';

                has_detection_plane = ...
                    has_existing_detection_new( ...
                        data, ...
                        'gcamp_plane', ...
                        'DF_gcamp_by_plane', ...
                        m, ...
                        p);
            end

            if isempty(F_in)

                fprintf( ...
                    '%s - plane %d: no signal data available.\n', ...
                    record_label_m, ...
                    p);

                continue;
            end

            % ==================================================
            % Viewer / Load-only decision
            % ==================================================
            viewer_mode_requested_plane = false;
            load_only_plane = false;

            if has_detection_plane

                if isempty(global_existing_detection_action)

                    global_existing_detection_action = ...
                        ask_existing_detection_action_global( ...
                            record_label_m);
                end

                switch global_existing_detection_action

                    case 'viewer'

                        viewer_mode_requested_plane = true;

                    case 'load_only'

                        load_only_plane = true;
                end
            end

            % ==================================================
            % Mean image
            % ==================================================
            if numel(meanImgs_m) >= p

                meanImg = ...
                    meanImgs_m{p};

            else

                meanImg = [];
            end
            
            % ==================================================
            % Load saved detection corresponding to data passed
            %
            % Combined mode -> combined saved detection
            % GCaMP-only   -> GCaMP saved detection
            % ==================================================
            Acttmp2_saved = [];
            Raster_saved = [];
            thresholds_saved = [];
            valid_cells_saved = [];
            DF_sg_saved = [];
            DF_raw_saved = [];
            F0_saved = [];
            noise_est_saved = [];

            if process_electroporated_combined

                detection_branch = ...
                    'combined_plane';

                valid_field = ...
                    'valid_combined_cells_by_plane';

                Acttmp2_field = ...
                    'Acttmp2_combined_by_plane';

                Raster_field = ...
                    'Raster_combined_by_plane';

                thresholds_field = ...
                    'thresholds_combined_by_plane';

                DF_field = ...
                    'DF_combined_by_plane';

                DF_raw_field = ...
                    'DF_raw_combined_by_plane';

                F0_field = ...
                    'F0_combined_by_plane';

                noise_field = ...
                    'noise_est_combined_by_plane';

            else

                detection_branch = ...
                    'gcamp_plane';

                valid_field = ...
                    'valid_gcamp_cells_by_plane';

                Acttmp2_field = ...
                    'Acttmp2_gcamp_by_plane';

                Raster_field = ...
                    'Raster_gcamp_by_plane';

                thresholds_field = ...
                    'thresholds_gcamp_by_plane';

                DF_field = ...
                    'DF_gcamp_by_plane';

                DF_raw_field = ...
                    'DF_raw_gcamp_by_plane';

                F0_field = ...
                    'F0_gcamp_by_plane';

                noise_field = ...
                    'noise_est_gcamp_by_plane';
            end

            viewer_mode = ...
                viewer_mode_requested_plane && ...
                has_existing_detection_new( ...
                    data, ...
                    detection_branch, ...
                    DF_field, ...
                    m, ...
                    p);

            if viewer_mode || ...
                    load_only_plane

                valid_cells_saved = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        detection_branch, ...
                        valid_field, ...
                        m, ...
                        p);

                Acttmp2_saved = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        detection_branch, ...
                        Acttmp2_field, ...
                        m, ...
                        p);

                Raster_saved = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        detection_branch, ...
                        Raster_field, ...
                        m, ...
                        p);

                thresholds_saved = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        detection_branch, ...
                        thresholds_field, ...
                        m, ...
                        p);

                DF_sg_saved = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        detection_branch, ...
                        DF_field, ...
                        m, ...
                        p);

                DF_raw_saved = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        detection_branch, ...
                        DF_raw_field, ...
                        m, ...
                        p);

                F0_saved = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        detection_branch, ...
                        F0_field, ...
                        m, ...
                        p);

                noise_est_saved = ...
                    get_branch_plane_or_empty( ...
                        data, ...
                        detection_branch, ...
                        noise_field, ...
                        m, ...
                        p);
               
                if load_only_plane

                    fprintf( ...
                        ['%s - plane %d: existing detection loaded only; ' ...
                         'preview checked/created.\n'], ...
                        record_label_m, ...
                        p);

                    continue;
                end
            end

            % ==================================================
            % Prepare F
            % ==================================================
            if viewer_mode
            
                % ==========================================================
                % En viewer, les données sauvegardées DF/F0/Raster/etc.
                % ne contiennent QUE les cellules qui avaient été validées.
                %
                % Il faut donc réduire F aux mêmes cellules pour que :
                %
                %   size(F_view,1) == size(DF_sg_saved,1)
                %
                % valid_cells_saved reste exprimé dans le référentiel
                % COMBINED ORIGINAL.
                % ==========================================================
            
                viewer_original_indices = ...
                    round(double(valid_cells_saved(:)));
            
                viewer_original_indices = ...
                    viewer_original_indices( ...
                        isfinite(viewer_original_indices) & ...
                        viewer_original_indices >= 1 & ...
                        viewer_original_indices <= size(F_in,1));
            
                % ----------------------------------------------------------
                % Vérification cohérence
                % ----------------------------------------------------------
                viewer_saved_nCells = ...
                    size(DF_sg_saved,1);
            
                if isempty(viewer_original_indices) || ...
                        numel(viewer_original_indices) ~= viewer_saved_nCells
            
                    warning( ...
                        ['%s - plane %d: valid_cells sauvegardé incompatible ' ...
                         'avec DF sauvegardé. Viewer impossible.'], ...
                        record_label_m, ...
                        p);
            
                    viewer_mode = false;
            
                else
            
                    % ------------------------------------------------------
                    % F réduit exactement aux cellules présentes dans
                    % les matrices de détection sauvegardées
                    % ------------------------------------------------------
                    F_view = ...
                        F_in( ...
                            viewer_original_indices, ...
                            :);
            
                    % ------------------------------------------------------
                    % Masks : même réduction
                    % ------------------------------------------------------
                    if ~isempty(masks_in) && ...
                            ndims(masks_in) >= 3 && ...
                            size(masks_in,1) >= max(viewer_original_indices)
            
                        masks_in = ...
                            masks_in( ...
                                viewer_original_indices, ...
                                :, ...
                                :);
                    end
            
                    % ------------------------------------------------------
                    % Remapper les cellules electroporated dans le
                    % référentiel LOCAL du viewer.
                    %
                    % Exemple :
                    %   valid original = [2 5 8 10]
                    %   electroporated original = [8 10]
                    %
                    % devient dans le viewer :
                    %   electroporated = [3 4]
                    % ------------------------------------------------------
                    if process_electroporated_combined && ...
                            ~isempty(electroporated_indices_in)
            
                        electroporated_original = ...
                            round(double( ...
                                electroporated_indices_in(:)));
            
                        electroporated_original = ...
                            electroporated_original( ...
                                isfinite(electroporated_original));
            
                        electroporated_indices_in = ...
                            find( ...
                                ismember( ...
                                    viewer_original_indices, ...
                                    electroporated_original));
                    else
            
                        electroporated_indices_in = [];
                    end
            
                    fprintf( ...
                        ['%s - plane %d: viewer chargé avec %d cellules ' ...
                         'validées sur %d cellules COMBINED originales.\n'], ...
                        record_label_m, ...
                        p, ...
                        numel(viewer_original_indices), ...
                        size(F_in,1));
                end
            
            end
            
            if ~viewer_mode
                F_nostims = ...
                    F_in;

                first_stim_frame = [];

                if ~isempty(stim_frames_m)

                    stim_tmp = ...
                        double(stim_frames_m(:));

                    stim_tmp = ...
                        stim_tmp(isfinite(stim_tmp));

                    if ~isempty(stim_tmp)

                        first_stim_frame = ...
                            min(stim_tmp);
                    end
                end

                if ~isempty(first_stim_frame) && ...
                        isfinite(first_stim_frame)

                    first_stim_frame_global = ...
                        round(first_stim_frame);

                    first_stim_frame_plane = ...
                        ceil( ...
                            first_stim_frame_global / ...
                            nPlanes);

                    if first_stim_frame_plane > 1 && ...
                            first_stim_frame_plane <= size(F_in, 2)

                        last_frame = ...
                            first_stim_frame_plane - 1;

                        F_nostims = ...
                            F_in(:, 1:last_frame);
                    end
                end

                nT = ...
                    size(F_nostims, 2);

                bad_frames = ...
                    bad_frames_group;

                bad_segs = ...
                    bad_segs_group;

                deviation = ...
                    deviation_group;

                focus_segs = ...
                    focus_segs_group;

                motion_energy = ...
                    motion_energy_group;

                if ~isempty(motion_energy)

                    motion_energy = ...
                        motion_energy( ...
                            1:min( ...
                                nT, ...
                                numel(motion_energy)));
                end

                if ~isempty(bad_frames)

                    bad_frames = ...
                        bad_frames(:).';

                    bad_frames = ...
                        bad_frames( ...
                            bad_frames >= 1 & ...
                            bad_frames <= nT);
                end

                if ~isempty(deviation)

                    deviation = ...
                        deviation(:).';

                    deviation = ...
                        deviation( ...
                            1:min( ...
                                nT, ...
                                numel(deviation)));
                end

                if ~isempty(bad_frames)

                    bad_segs = ...
                        badframes_to_segments( ...
                            bad_frames, ...
                            nT);

                    focus_segs = ...
                        bad_segs;

                    F_clean = ...
                        F_nostims;

                    F_clean(:, bad_frames) = ...
                        NaN;

                    F_clean = ...
                        fillmissing( ...
                            F_clean, ...
                            'linear', ...
                            2, ...
                            'EndValues', ...
                            'nearest');

                    F_nostims = ...
                        F_clean;

                else

                    bad_segs = [];
                    focus_segs = [];
                end

                F_view = ...
                    F_nostims;
            end

            if viewer_mode

                bad_frames = ...
                    bad_frames_group;

                bad_segs = ...
                    bad_segs_group;

                deviation = ...
                    deviation_group;

                focus_segs = ...
                    focus_segs_group;

                motion_energy = ...
                    motion_energy_group;
            end

            if isempty(F_view)
                continue;
            end

            % ==================================================
            % Peak tuner
            %
            % IMPORTANT:
            %
            % F_view est COMBINED lorsque electroporated actif.
            %
            % Le GUI reçoit electroporated_indices_in et construit :
            %
            % combined:
            %   1:size(F_view,1)
            %
            % electroporated:
            %   electroporated_indices_in
            %
            % gcamp:
            %   complement de electroporated_indices_in
            %
            % selected_signal retourne le choix de la checkbox.
            % ==================================================
            [ ...
                F0, ...
                noise_est, ...
                valid_cells, ...
                DF_sg, ...
                DF_raw, ...
                Raster, ...
                Acttmp2, ...
                MAct, ...
                thresholds, ...
                bad_segs_det, ...
                opts_det, ...
                has_new, ...
                request_reprocess, ...
                selected_signal ...
            ] = ...
                peak_detection_tuner( ...
                    current_type, ...
                    current_line, ...
                    animal, ...
                    date_m, ...
                    age_m, ...
                    p, ...
                    F_view, ...
                    sampling_rate_m, ...
                    sync_frames_m, ...
                    viewer_mode, ...
                    DF_sg_saved, ...
                    DF_raw_saved, ...
                    F0_saved, ...
                    noise_est_saved, ...
                    Acttmp2_saved, ...
                    Raster_saved, ...
                    thresholds_saved, ...
                    valid_cells_saved, ...
                    cell_type, ...
                    ops_in, ...
                    iscell_idx, ...
                    stat_in, ...
                    masks_in, ...
                    electroporated_indices_in, ...
                    meanImg, ...
                    TSeries_m, ...
                    deviation, ...
                    bad_frames, ...
                    focus_segs, ...
                    motion_energy, ...
                    metadata_m, ...
                    stim_frames_m, ...
                    gcamp_output_folder_p, ...
                    current_output_folder);

            % ==================================================
            % Reprocess
            % ==================================================
            if request_reprocess

                if process_electroporated_combined

                    branches_to_clear = { ...
                        'gcamp', ...
                        'electroporated', ...
                        'combined'};

                else

                    branches_to_clear = { ...
                        'gcamp'};
                end

                data = ...
                    clear_detection_outputs_for_plane_in_data( ...
                        data, ...
                        m, ...
                        p, ...
                        branches_to_clear, ...
                        fields_detect_gcamp, ...
                        fields_detect_electroporated, ...
                        fields_detect_combined);

                has_new_gcamp_group = true;

                has_new_electroporated_group = ...
                    process_electroporated_combined;

                has_new_combined_group = ...
                    process_electroporated_combined;

                fprintf( ...
                    ['%s - plane %d: résultats effacés. ' ...
                     'Relance DF_peak_detection.\n'], ...
                    record_label_m, ...
                    p);

                continue;
            end

            if viewer_mode
                continue;
            end

            if ~has_new

                fprintf( ...
                    '%s - plane %d: no new outputs.\n', ...
                    record_label_m, ...
                    p);

                continue;
            end
            
            % ==================================================
            % Create preview after NEW peak detection only
            %
            % Jamais en viewer mode.
            % Jamais en load_only.
            % ==================================================
            try
            
                create_random_peak_preview( ...
                    valid_cells, ...
                    DF_sg, ...
                    Acttmp2, ...
                    thresholds, ...
                    gcamp_output_folder_p, ...
                    current_automatic_selection, ...
                    current_output_folder, ...
                    current_line, ...
                    animal, ...
                    date_m, ...
                    age_m, ...
                    p - 1);
            
            catch ME
            
                warning( ...
                    ['%s - plane %d: impossible de créer la ' ...
                     'preview de la nouvelle détection : %s'], ...
                    record_label_m, ...
                    p, ...
                    ME.message);
            end

            % ==================================================
            % selected_signal = population affichée uniquement
            %
            % IMPORTANT:
            % Lorsque electroporated est actif, les sorties du GUI
            % sont toujours exprimées dans le référentiel COMBINED.
            % La checkbox ne décide donc jamais de la branche sauvée.
            % ==================================================
            if isempty(selected_signal)

                if process_electroporated_combined
                    selected_signal = 'combined';
                else
                    selected_signal = 'gcamp';
                end
            end

            selected_signal = ...
                lower( ...
                    char(string(selected_signal)));

            if process_electroporated_combined

                % ==================================================
                % COMBINED = référentiel maître
                % ==================================================
                has_new_combined_group = true;

                [ ...
                    isort1_combined, ...
                    isort2_combined, ...
                    Sm_combined ...
                ] = ...
                    compute_sort_outputs_from_df( ...
                        DF_sg, ...
                        ops_in);

                data.combined_plane. ...
                    F0_combined_by_plane{m}{p} = ...
                    F0;

                data.combined_plane. ...
                    noise_est_combined_by_plane{m}{p} = ...
                    noise_est;

                data.combined_plane. ...
                    valid_combined_cells_by_plane{m}{p} = ...
                    valid_cells;

                data.combined_plane. ...
                    DF_combined_by_plane{m}{p} = ...
                    DF_sg;

                data.combined_plane. ...
                    DF_raw_combined_by_plane{m}{p} = ...
                    DF_raw;

                data.combined_plane. ...
                    Raster_combined_by_plane{m}{p} = ...
                    Raster;

                data.combined_plane. ...
                    Acttmp2_combined_by_plane{m}{p} = ...
                    Acttmp2;

                data.combined_plane. ...
                    MAct_combined_by_plane{m}{p} = ...
                    MAct;

                data.combined_plane. ...
                    thresholds_combined_by_plane{m}{p} = ...
                    thresholds;

                data.combined_plane. ...
                    bad_segs_combined_plane{m}{p} = ...
                    bad_segs_det;

                data.combined_plane. ...
                    opts_detection_combined_by_plane{m}{p} = ...
                    opts_det;

                data.combined_plane. ...
                    isort1_combined_by_plane{m}{p} = ...
                    isort1_combined;

                data.combined_plane. ...
                    isort2_combined_by_plane{m}{p} = ...
                    isort2_combined;

                data.combined_plane. ...
                    Sm_combined_by_plane{m}{p} = ...
                    Sm_combined;

                % ==================================================
                % Toujours propager COMBINED -> GCaMP + electroporated
                %
                % Une modification faite depuis n'importe quelle vue
                % du GUI est donc sauvée dans les trois branches.
                % ==================================================
                [ ...
                    data, ...
                    has_new_gcamp_group, ...
                    has_new_electroporated_group ...
                ] = ...
                    reconstruct_gcamp_electroporated_from_combined( ...
                        data, ...
                        m, ...
                        p, ...
                        valid_cells, ...
                        F0, ...
                        noise_est, ...
                        DF_sg, ...
                        DF_raw, ...
                        Raster, ...
                        Acttmp2, ...
                        thresholds, ...
                        bad_segs_det, ...
                        opts_det, ...
                        electroporated_indices_in, ...
                        sync_frames_m, ...
                        ops_in);

                fprintf( ...
                    ['%s - plane %d: sélection %s propagée vers ' ...
                     'combined, GCaMP et electroporated.\n'], ...
                    record_label_m, ...
                    p, ...
                    upper(selected_signal));

            else

                % ==================================================
                % Vrai mode GCaMP-only
                % ==================================================
                has_new_gcamp_group = true;

                [ ...
                    isort1_plane, ...
                    isort2_plane, ...
                    Sm_plane ...
                ] = ...
                    compute_sort_outputs_from_df( ...
                        DF_sg, ...
                        ops_in);

                data.gcamp_plane. ...
                    F0_gcamp_by_plane{m}{p} = ...
                    F0;

                data.gcamp_plane. ...
                    noise_est_gcamp_by_plane{m}{p} = ...
                    noise_est;

                data.gcamp_plane. ...
                    valid_gcamp_cells_by_plane{m}{p} = ...
                    valid_cells;

                data.gcamp_plane. ...
                    DF_gcamp_by_plane{m}{p} = ...
                    DF_sg;

                data.gcamp_plane. ...
                    DF_raw_gcamp_by_plane{m}{p} = ...
                    DF_raw;

                data.gcamp_plane. ...
                    Raster_gcamp_by_plane{m}{p} = ...
                    Raster;

                data.gcamp_plane. ...
                    Acttmp2_gcamp_by_plane{m}{p} = ...
                    Acttmp2;

                data.gcamp_plane. ...
                    MAct_gcamp_by_plane{m}{p} = ...
                    MAct;

                data.gcamp_plane. ...
                    thresholds_gcamp_by_plane{m}{p} = ...
                    thresholds;

                data.gcamp_plane. ...
                    bad_segs_gcamp_plane{m}{p} = ...
                    bad_segs_det;

                data.gcamp_plane. ...
                    opts_detection_gcamp_by_plane{m}{p} = ...
                    opts_det;

                data.gcamp_plane. ...
                    isort1_gcamp_by_plane{m}{p} = ...
                    isort1_plane;

                data.gcamp_plane. ...
                    isort2_gcamp_by_plane{m}{p} = ...
                    isort2_plane;

                data.gcamp_plane. ...
                    Sm_gcamp_by_plane{m}{p} = ...
                    Sm_plane;
            end
        end

        % ======================================================
        % SAVE RECORDING
        % ======================================================
        if has_new_gcamp_group

            save_branch_fields( ...
                filePath_gcamp, ...
                data, ...
                'gcamp_plane', ...
                fields_detect_gcamp, ...
                m);
        end

        if process_electroporated_combined && ...
                has_new_electroporated_group

            save_branch_fields( ...
                filePath_electroporated, ...
                data, ...
                'electroporated_plane', ...
                fields_detect_electroporated, ...
                m);
        end

        if process_electroporated_combined && ...
                has_new_combined_group

            save_branch_fields( ...
                filePath_combined, ...
                data, ...
                'combined_plane', ...
                fields_detect_combined, ...
                m);
        end

        if has_new_motion_group

            save_motion_group_fields( ...
                filePath_motion, ...
                data, ...
                fields_motion_group, ...
                m);
        end
    end
end
% =========================================================
% ==================== UTILITAIRES ========================
% =========================================================

function data = init_detection_branch_if_needed(data, branchName, numFolders, fields)
    if ~isfield(data, branchName) || ~isstruct(data.(branchName)) || isempty(data.(branchName))
        data.(branchName) = struct();
    end

    for f = 1:numel(fields)
        fieldName = fields{f};
        if ~isfield(data.(branchName), fieldName) || ~iscell(data.(branchName).(fieldName))
            tmp = cell(numFolders,1);
            [tmp{:}] = deal([]);
            data.(branchName).(fieldName) = tmp;
        elseif numel(data.(branchName).(fieldName)) < numFolders
            old = data.(branchName).(fieldName);
            tmp = cell(numFolders,1);
            tmp(1:numel(old)) = old(:);
            data.(branchName).(fieldName) = tmp;
        end
    end
end

function data = ensure_branch_plane_cell(data, branchName, fieldName, m, nPlanes)
    if ~isfield(data.(branchName), fieldName)
        data.(branchName).(fieldName) = cell(m,1);
    end
    if numel(data.(branchName).(fieldName)) < m
        tmp = cell(m,1);
        tmp(1:numel(data.(branchName).(fieldName))) = data.(branchName).(fieldName)(:);
        data.(branchName).(fieldName) = tmp;
    end
    if isempty(data.(branchName).(fieldName){m}) || ~iscell(data.(branchName).(fieldName){m})
        data.(branchName).(fieldName){m} = cell(nPlanes,1);
    elseif numel(data.(branchName).(fieldName){m}) ~= nPlanes
        old = data.(branchName).(fieldName){m};
        new = cell(nPlanes,1);
        n = min(numel(old), nPlanes);
        new(1:n) = old(1:n);
        data.(branchName).(fieldName){m} = new;
    end
end

function out = coerce_to_plane_cell(val, nPlanes)
    if isempty(val)
        out = cell(nPlanes,1);
    elseif iscell(val)
        out = cell(nPlanes,1);
        nCopy = min(numel(val), nPlanes);
        out(1:nCopy) = val(1:nCopy);
    else
        out = cell(nPlanes,1);
        if nPlanes >= 1
            out{1} = val;
        end
    end
end
function data = init_motion_group_if_needed(data, numFolders, fields_motion_group)

    if ~isfield(data,'motion') || ~isstruct(data.motion)
        data.motion = struct();
    end

    for f = 1:numel(fields_motion_group)
        fn = fields_motion_group{f};

        if ~isfield(data.motion, fn) || ~iscell(data.motion.(fn))
            data.motion.(fn) = cell(numFolders,1);

        elseif numel(data.motion.(fn)) < numFolders
            old = data.motion.(fn);
            tmp = cell(numFolders,1);
            tmp(1:numel(old)) = old(:);
            data.motion.(fn) = tmp;
        end
    end
end

function data = merge_loaded_motion_group_into_data(data, loaded, fields_motion_group, m)

    for f = 1:numel(fields_motion_group)

        fn = fields_motion_group{f};

        if ~isfield(loaded, fn)
            continue;
        end

        if ~isfield(data.motion, fn) || numel(data.motion.(fn)) < m
            data.motion.(fn) = cell(m,1);
        end

        if isempty(data.motion.(fn){m})
            data.motion.(fn){m} = loaded.(fn);
        end
    end
end

function v = get_motion_group_or_empty(data, fieldName, m)

    v = [];

    if isfield(data,'motion') && ...
       isfield(data.motion, fieldName) && ...
       numel(data.motion.(fieldName)) >= m

        v = data.motion.(fieldName){m};
    end
end

function save_motion_group_fields(filePath_motion, data, fields_motion_group, m)

    saveStruct = struct();

    for f = 1:numel(fields_motion_group)
        fn = fields_motion_group{f};

        if isfield(data,'motion') && ...
           isfield(data.motion, fn) && ...
           numel(data.motion.(fn)) >= m

            saveStruct.(fn) = data.motion.(fn){m};
        end
    end

    outdir = fileparts(filePath_motion);
    if ~exist(outdir,'dir')
        mkdir(outdir);
    end

    if exist(filePath_motion,'file') == 2
        save(filePath_motion, '-struct', 'saveStruct', '-append');
    else
        save(filePath_motion, '-struct', 'saveStruct');
    end
end

function segs = badframes_to_segments(bad_frames, T)
    if isempty(bad_frames) || T<=0
        segs = zeros(0,2);
        return;
    end

    if islogical(bad_frames)
        bf = bad_frames(:).';
        if numel(bf) ~= T
            bf = bf(1:min(end,T));
            if numel(bf) < T, bf(end+1:T) = false; end
        end
        idx = find(bf);
    else
        idx = bad_frames(:).';
        idx = idx(isfinite(idx));
        idx = unique(round(idx));
        idx = idx(idx>=1 & idx<=T);
    end

    if isempty(idx)
        segs = zeros(0,2);
        return;
    end

    d = diff(idx);
    cuts = [1 find(d>1)+1 numel(idx)+1];

    segs = zeros(numel(cuts)-1,2);
    for k = 1:numel(cuts)-1
        a = idx(cuts(k));
        b = idx(cuts(k+1)-1);
        segs(k,:) = [a b];
    end
end

function [user_segs, user_frames] = enter_observed_deviations(tifPath, T)

    if nargin < 1
        error('Usage: [user_segs,user_frames] = enter_observed_deviations(tifPath,T)');
    end
    if nargin < 2, T = []; end

    if ~exist(tifPath,'file')
        error('TIFF introuvable : %s', tifPath);
    end

    fprintf('\n=== OUVRIR MANUELLEMENT DANS FIJI ===\n');
    fprintf('Fichier TIFF :\n%s\n\n', tifPath);
    fprintf('Ouvre ce fichier dans Fiji, observe les déviations,\n');
    fprintf('puis reviens ici pour entrer les frames correspondantes.\n\n');

    fprintf('Entrée attendue (FRAMES uniquement) :\n');
    fprintf('  ex: 120:140\n');
    fprintf('      [120:140 300:320]\n');
    fprintf('[] si aucune déviation.\n\n');

    x = input('Frames observées = ');

    if isempty(x)
        fprintf('Aucune déviation saisie.\n');
        user_segs = zeros(0,2);
        user_frames = [];
        return;
    end

    if ~isnumeric(x) || ~isvector(x)
        error('Entrée invalide: entrer UNIQUEMENT un vecteur de frames.');
    end

    fr = round(x(:).');
    fr = fr(isfinite(fr));

    if ~isempty(T)
        fr = fr(fr>=1 & fr<=T);
    else
        fr = fr(fr>=1);
    end

    fr = unique(fr);

    user_segs = frames_to_segments(fr);
    user_frames = fr;

    fprintf('\n=== Enregistré ===\n');
    fprintf('Segments détectés: %d\n', size(user_segs,1));
    if ~isempty(user_segs)
        disp(user_segs);
    end
end

function segs = frames_to_segments(fr)
    if isempty(fr)
        segs = zeros(0,2);
        return;
    end
    d = diff(fr);
    cuts = [1 find(d>1)+1 numel(fr)+1];
    segs = zeros(numel(cuts)-1,2);
    for k = 1:numel(cuts)-1
        segs(k,:) = [fr(cuts(k)) fr(cuts(k+1)-1)];
    end
end

function segTable = sort_segments_by_deviation(bad_segs, deviation)

    if nargin < 2
        error('Usage: segTable = sort_segments_by_deviation(bad_segs, deviation)');
    end

    deviation = deviation(:).';
    T = numel(deviation);

    if isempty(bad_segs)
        segTable = table([], [], [], [], ...
            'VariableNames', {'StartFrame','EndFrame','FrameExtent','ValMaxDeviation'});
        disp(segTable);
        return;
    end

    if size(bad_segs,2) ~= 2
        error('bad_segs doit être une matrice Nx2 [start end].');
    end

    N = size(bad_segs,1);

    startF = nan(N,1);
    endF   = nan(N,1);
    extent = nan(N,1);
    valMax = nan(N,1);

    for k = 1:N
        a = round(bad_segs(k,1));
        b = round(bad_segs(k,2));

        if a > b
            tmp = a; a = b; b = tmp;
        end

        a = max(1, min(T, a));
        b = max(1, min(T, b));

        startF(k) = a;
        endF(k)   = b;
        extent(k) = b - a + 1;

        segVals = deviation(a:b);
        segVals = segVals(isfinite(segVals));

        if isempty(segVals)
            valMax(k) = NaN;
        else
            valMax(k) = min(segVals);
        end
    end

    segTable = table(startF, endF, extent, valMax, ...
        'VariableNames', {'StartFrame','EndFrame','FrameExtent','ValMaxDeviation'});

    segTable = sortrows(segTable, 'ValMaxDeviation', 'ascend');
end


function v = get_branch_plane_or_empty(data, branchName, fieldName, m, p)
    v = [];
    if isfield(data, branchName) && isfield(data.(branchName), fieldName) && ...
       numel(data.(branchName).(fieldName)) >= m && ...
       ~isempty(data.(branchName).(fieldName){m}) && iscell(data.(branchName).(fieldName){m}) && ...
       numel(data.(branchName).(fieldName){m}) >= p
        v = data.(branchName).(fieldName){m}{p};
    end
end

function tf = has_existing_detection_new(data, branchName, fieldName, m, p)
    tf = false;
    if isfield(data, branchName) && isfield(data.(branchName), fieldName) && ...
       numel(data.(branchName).(fieldName)) >= m && ...
       ~isempty(data.(branchName).(fieldName){m}) && iscell(data.(branchName).(fieldName){m}) && ...
       numel(data.(branchName).(fieldName){m}) >= p && ...
       ~isempty(data.(branchName).(fieldName){m}{p})
        tf = true;
    end
end

function data = merge_loaded_branch_into_data(data, branchName, loaded, fieldsToLoad, m, nPlanes)
    for k = 1:numel(fieldsToLoad)
        fn = fieldsToLoad{k};
        if ~isfield(loaded, fn)
            continue;
        end

        loadedField = coerce_to_plane_cell(loaded.(fn), nPlanes);
        data = ensure_branch_plane_cell(data, branchName, fn, m, nPlanes);

        for p = 1:nPlanes
            if numel(loadedField) >= p
                if isempty(data.(branchName).(fn){m}{p})
                    data.(branchName).(fn){m}{p} = loadedField{p};
                end
            end
        end
    end
end

function save_branch_fields(filePath, data, branchName, saveFields, m)
    saveStruct = struct();
    for k = 1:numel(saveFields)
        fieldName = saveFields{k};
        if isfield(data, branchName) && isfield(data.(branchName), fieldName) && ...
           numel(data.(branchName).(fieldName)) >= m
            saveStruct.(fieldName) = data.(branchName).(fieldName){m};
        end
    end

    outdir = fileparts(filePath);
    if ~exist(outdir, 'dir')
        mkdir(outdir);
    end

    if exist(filePath, 'file') == 2
        save(filePath, '-struct', 'saveStruct', '-append');
    else
        save(filePath, '-struct', 'saveStruct');
    end
end

function [ ...
        data, ...
        has_new_gcamp_group, ...
        has_new_electroporated_group ...
    ] = ...
    reconstruct_gcamp_electroporated_from_combined( ...
        data, ...
        m, ...
        p, ...
        valid_combined, ...
        F0_combined, ...
        noise_est_combined, ...
        DF_sg_combined, ...
        DF_raw_combined, ...
        Raster_combined, ...
        Acttmp2_combined, ...
        thresholds_combined, ...
        bad_segs_combined, ...
        opts_det_combined, ...
        electroporated_indices_combined, ...
        synchronous_frames, ...
        ops_in)

    % ==========================================================
    % Les sorties reçues sont déjà réduites aux cellules valides.
    % valid_combined contient leurs indices dans F_combined initial.
    %
    % combined est construit comme :
    %   [GCaMP non appariées ; electroporated]
    %
    % electroporated_indices_combined identifie donc directement
    % les lignes electroporated dans le référentiel combined.
    % ==========================================================

    has_new_gcamp_group = true;
    has_new_electroporated_group = true;

    valid_combined = ...
        round(double(valid_combined(:)));

    electroporated_indices_combined = ...
        normalize_indices_local( ...
            electroporated_indices_combined);

    % ==========================================================
    % GCAMP
    % ==========================================================
    [out_gcamp, has_gcamp] = ...
        reconstruct_gcamp_from_combined_outputs( ...
            valid_combined, ...
            F0_combined, ...
            noise_est_combined, ...
            DF_sg_combined, ...
            DF_raw_combined, ...
            Raster_combined, ...
            Acttmp2_combined, ...
            thresholds_combined, ...
            bad_segs_combined, ...
            opts_det_combined, ...
            electroporated_indices_combined, ...
            synchronous_frames);

    if has_gcamp

        [isort1, isort2, Sm] = ...
            compute_sort_outputs_from_df( ...
                out_gcamp.DF_sg, ...
                ops_in);

    else

        isort1 = [];
        isort2 = [];
        Sm = [];
    end

    % Toujours écraser, même si plus aucune cellule GCaMP valide.
    data.gcamp_plane.F0_gcamp_by_plane{m}{p} = ...
        out_gcamp.F0;

    data.gcamp_plane.noise_est_gcamp_by_plane{m}{p} = ...
        out_gcamp.noise_est;

    data.gcamp_plane.valid_gcamp_cells_by_plane{m}{p} = ...
        out_gcamp.valid_cells;

    data.gcamp_plane.DF_gcamp_by_plane{m}{p} = ...
        out_gcamp.DF_sg;

    data.gcamp_plane.DF_raw_gcamp_by_plane{m}{p} = ...
        out_gcamp.DF_raw;

    data.gcamp_plane.Raster_gcamp_by_plane{m}{p} = ...
        out_gcamp.Raster;

    data.gcamp_plane.Acttmp2_gcamp_by_plane{m}{p} = ...
        out_gcamp.Acttmp2;

    data.gcamp_plane.MAct_gcamp_by_plane{m}{p} = ...
        out_gcamp.MAct;

    data.gcamp_plane.thresholds_gcamp_by_plane{m}{p} = ...
        out_gcamp.thresholds;

    data.gcamp_plane.bad_segs_gcamp_plane{m}{p} = ...
        out_gcamp.bad_segs;

    data.gcamp_plane.opts_detection_gcamp_by_plane{m}{p} = ...
        out_gcamp.opts_det;

    data.gcamp_plane.isort1_gcamp_by_plane{m}{p} = ...
        isort1;

    data.gcamp_plane.isort2_gcamp_by_plane{m}{p} = ...
        isort2;

    data.gcamp_plane.Sm_gcamp_by_plane{m}{p} = ...
        Sm;

    % ==========================================================
    % ELECTROPORATED
    % ==========================================================
    [out_electroporated, has_electroporated] = ...
        reconstruct_electroporated_from_combined_outputs( ...
            valid_combined, ...
            F0_combined, ...
            noise_est_combined, ...
            DF_sg_combined, ...
            DF_raw_combined, ...
            Raster_combined, ...
            Acttmp2_combined, ...
            thresholds_combined, ...
            bad_segs_combined, ...
            opts_det_combined, ...
            electroporated_indices_combined, ...
            synchronous_frames);

    if has_electroporated

        [isort1, isort2, Sm] = ...
            compute_sort_outputs_from_df( ...
                out_electroporated.DF_sg, ...
                ops_in);

    else

        isort1 = [];
        isort2 = [];
        Sm = [];
    end

    % Toujours écraser, même si plus aucune cellule electroporated valide.
    data.electroporated_plane. ...
        F0_electroporated_by_plane{m}{p} = ...
        out_electroporated.F0;

    data.electroporated_plane. ...
        noise_est_electroporated_by_plane{m}{p} = ...
        out_electroporated.noise_est;

    data.electroporated_plane. ...
        valid_electroporated_cells_by_plane{m}{p} = ...
        out_electroporated.valid_cells;

    data.electroporated_plane. ...
        DF_electroporated_by_plane{m}{p} = ...
        out_electroporated.DF_sg;

    data.electroporated_plane. ...
        DF_raw_electroporated_by_plane{m}{p} = ...
        out_electroporated.DF_raw;

    data.electroporated_plane. ...
        Raster_electroporated_by_plane{m}{p} = ...
        out_electroporated.Raster;

    data.electroporated_plane. ...
        Acttmp2_electroporated_by_plane{m}{p} = ...
        out_electroporated.Acttmp2;

    data.electroporated_plane. ...
        MAct_electroporated_by_plane{m}{p} = ...
        out_electroporated.MAct;

    data.electroporated_plane. ...
        thresholds_electroporated_by_plane{m}{p} = ...
        out_electroporated.thresholds;

    data.electroporated_plane. ...
        bad_segs_electroporated_plane{m}{p} = ...
        out_electroporated.bad_segs;

    data.electroporated_plane. ...
        opts_detection_electroporated_by_plane{m}{p} = ...
        out_electroporated.opts_det;

    data.electroporated_plane. ...
        isort1_electroporated_by_plane{m}{p} = ...
        isort1;

    data.electroporated_plane. ...
        isort2_electroporated_by_plane{m}{p} = ...
        isort2;

    data.electroporated_plane. ...
        Sm_electroporated_by_plane{m}{p} = ...
        Sm;
end


function [out, ok] = ...
    reconstruct_gcamp_from_combined_outputs( ...
        valid_combined, ...
        F0_combined, ...
        noise_est_combined, ...
        DF_sg_combined, ...
        DF_raw_combined, ...
        Raster_combined, ...
        Acttmp2_combined, ...
        thresholds_combined, ...
        bad_segs_combined, ...
        opts_det_combined, ...
        electroporated_indices_combined, ...
        synchronous_frames)

    out = make_empty_reconstructed_outputs( ...
        DF_sg_combined, ...
        bad_segs_combined, ...
        opts_det_combined);

    ok = false;

    if isempty(valid_combined)
        return;
    end

    valid_combined = ...
        valid_combined(:);

    is_gcamp_valid = ...
        ~ismember( ...
            valid_combined, ...
            electroporated_indices_combined);

    row_keep = ...
        find(is_gcamp_valid);

    if isempty(row_keep)
        return;
    end

    valid_gcamp_combined = ...
        valid_combined(row_keep);

    % Comme combined = [GCaMP ; electroporated],
    % les indices Combined des GCaMP correspondent aux indices
    % locaux de la population GCaMP.
    out.valid_cells = ...
        valid_gcamp_combined(:);

    out.F0 = ...
        safe_take_rows( ...
            F0_combined, ...
            row_keep);

    out.noise_est = ...
        safe_take_rows( ...
            noise_est_combined, ...
            row_keep);

    out.DF_sg = ...
        safe_take_rows( ...
            DF_sg_combined, ...
            row_keep);

    out.DF_raw = ...
        safe_take_rows( ...
            DF_raw_combined, ...
            row_keep);

    out.Raster = ...
        safe_take_rows( ...
            Raster_combined, ...
            row_keep);

    out.Acttmp2 = ...
        safe_take_cells( ...
            Acttmp2_combined, ...
            row_keep);

    out.thresholds = ...
        safe_take_rows( ...
            thresholds_combined, ...
            row_keep);

    out.MAct = ...
        recompute_mact_from_raster( ...
            out.Raster, ...
            synchronous_frames);

    ok = true;
end


function [out, ok] = ...
    reconstruct_electroporated_from_combined_outputs( ...
        valid_combined, ...
        F0_combined, ...
        noise_est_combined, ...
        DF_sg_combined, ...
        DF_raw_combined, ...
        Raster_combined, ...
        Acttmp2_combined, ...
        thresholds_combined, ...
        bad_segs_combined, ...
        opts_det_combined, ...
        electroporated_indices_combined, ...
        synchronous_frames)

    out = make_empty_reconstructed_outputs( ...
        DF_sg_combined, ...
        bad_segs_combined, ...
        opts_det_combined);

    ok = false;

    if isempty(valid_combined) || ...
            isempty(electroporated_indices_combined)

        return;
    end

    valid_combined = ...
        valid_combined(:);

    electroporated_indices_combined = ...
        electroporated_indices_combined(:);

    is_electroporated_valid = ...
        ismember( ...
            valid_combined, ...
            electroporated_indices_combined);

    row_keep = ...
        find(is_electroporated_valid);

    if isempty(row_keep)
        return;
    end

    valid_electroporated_combined = ...
        valid_combined(row_keep);

    % Conversion Combined -> indice local electroporated.
    [tf_map, local_idx] = ...
        ismember( ...
            valid_electroporated_combined, ...
            electroporated_indices_combined);

    out.valid_cells = ...
        local_idx(tf_map);

    out.valid_cells = ...
        out.valid_cells(:);

    out.F0 = ...
        safe_take_rows( ...
            F0_combined, ...
            row_keep);

    out.noise_est = ...
        safe_take_rows( ...
            noise_est_combined, ...
            row_keep);

    out.DF_sg = ...
        safe_take_rows( ...
            DF_sg_combined, ...
            row_keep);

    out.DF_raw = ...
        safe_take_rows( ...
            DF_raw_combined, ...
            row_keep);

    out.Raster = ...
        safe_take_rows( ...
            Raster_combined, ...
            row_keep);

    out.Acttmp2 = ...
        safe_take_cells( ...
            Acttmp2_combined, ...
            row_keep);

    out.thresholds = ...
        safe_take_rows( ...
            thresholds_combined, ...
            row_keep);

    out.MAct = ...
        recompute_mact_from_raster( ...
            out.Raster, ...
            synchronous_frames);

    ok = true;
end


function out = ...
    make_empty_reconstructed_outputs( ...
        DF_reference, ...
        bad_segs, ...
        opts_det)

    nFrames = 0;

    if ~isempty(DF_reference) && ...
            ndims(DF_reference) == 2

        nFrames = ...
            size(DF_reference,2);
    end

    out = struct( ...
        'F0', zeros(0,nFrames), ...
        'noise_est', zeros(0,1), ...
        'valid_cells', zeros(0,1), ...
        'DF_sg', zeros(0,nFrames), ...
        'DF_raw', zeros(0,nFrames), ...
        'Raster', false(0,nFrames), ...
        'Acttmp2', {cell(0,1)}, ...
        'MAct', zeros(1,0), ...
        'thresholds', zeros(0,1), ...
        'bad_segs', bad_segs, ...
        'opts_det', opts_det);
end


function indices = normalize_indices_local(indices)

    if isempty(indices)

        indices = ...
            zeros(0,1);

        return;
    end

    indices = ...
        round(double(indices(:)));

    indices = ...
        indices( ...
            isfinite(indices) & ...
            indices >= 1);

    indices = ...
        unique( ...
            indices, ...
            'stable');
end


function MAct = recompute_mact_from_raster(Raster, synchronous_frames)
    if isempty(Raster)
        MAct = zeros(1,0);
        return;
    end

    Nz = size(Raster, 2);
    if Nz > synchronous_frames
        MAct = zeros(1, Nz - synchronous_frames);
        for i = 1:(Nz - synchronous_frames)
            MAct(i) = sum(max(Raster(:, i:i+synchronous_frames), [], 2));
        end
    else
        MAct = zeros(1,0);
    end
end

function out = safe_take_rows(x, idx)
    if isempty(x)
        out = x;
        return;
    end
    if isvector(x)
        out = x(idx);
    else
        out = x(idx, :);
    end
end

function out = safe_take_cells(x, idx)
    if isempty(x)
        out = {};
        return;
    end
    if ~iscell(x)
        out = {};
        return;
    end
    out = x(idx);
end

function [isort1_out, isort2_out, Sm_out] = compute_sort_outputs_from_df(DF_in, ops_in)
    isort1_out = [];
    isort2_out = [];
    Sm_out     = [];

    if isempty(DF_in)
        return;
    end

    try
        [isort1_out, isort2_out, Sm_out] = ...
            raster_processing(double(DF_in), ops_in);
    catch ME
        warning('compute_sort_outputs_from_df:raster_processing', ...
            'raster_processing failed (%s).', ME.message);
        isort1_out = [];
        isort2_out = [];
        Sm_out     = [];
    end
end

function [label, date_name] = make_record_label(animal, metadata_m, m)

    animal_name = char(string(animal));
    date_name = '';

    if isfield(metadata_m, 'DateName') && ~isempty(metadata_m.DateName)
        date_name = char(string(metadata_m.DateName));
    end

    if ~isempty(animal_name) && ~isempty(date_name)
        label = sprintf('%s - %s', animal_name, date_name);
    elseif ~isempty(animal_name)
        label = animal_name;
    elseif ~isempty(date_name)
        label = date_name;
    else
        label = sprintf('Record %d', m);
    end
end

function [viewer_mode, skip_plane] = ask_viewer(has_detection, record_label, p, cell_type)

    viewer_mode = false;
    skip_plane  = false;

    if ~has_detection
        return;
    end

    if nargin < 2 || isempty(record_label)
        record_label = 'record';
    end

    if nargin < 3 || isempty(p)
        p = 0;
    end

    if nargin < 4 || isempty(cell_type)
        cell_type = 'plane';
    end

    plane_label = sprintf('plane %d', p);

    msg = sprintf(['%s - %s\n\n' ...
                   'Existing %s detection found.\n\n' ...
                   'What do you want to do?'], ...
                   record_label, plane_label, cell_type);

    answer = questdlg( ...
        msg, ...
        'Existing detection', ...
        'Viewer', ...
        'Load only', ...
        'Load only');

    switch answer
        case 'Viewer'
            viewer_mode = true;
            skip_plane  = false;

        otherwise
            viewer_mode = false;
            skip_plane  = true;
    end
end

function action = ask_existing_detection_action_global(record_label)

    if nargin < 1 || isempty(record_label)
        record_label = 'record';
    end

    msg = sprintf([ ...
        '%s\n\n' ...
        'Existing peak detection was found.\n\n' ...
        'What do you want to do for all existing detections?'], ...
        record_label);

    answer = questdlg( ...
        msg, ...
        'Existing detection - global mode', ...
        'Viewer', ...
        'Load only', ...
        'Load only');

    switch answer
        case 'Viewer'
            action = 'viewer';

        otherwise
            action = 'load_only';
    end
end

function metadata_m = get_metadata_for_record(metadata, idx)

    metadata_m = struct();

    if isempty(metadata) || ~isstruct(metadata)
        return;
    end

    fields = fieldnames(metadata);

    for f = 1:numel(fields)

        field = fields{f};
        value = metadata.(field);

        if iscell(value)

            if numel(value) >= idx
                metadata_m.(field) = value{idx};
            else
                metadata_m.(field) = [];
            end

        else
            metadata_m.(field) = value;
        end
    end
end

function tf = branch_has_missing_fields(data, branchName, fieldsToCheck, m, nPlanes)

    tf = true;

    if ~isfield(data, branchName) || ~isstruct(data.(branchName))
        return;
    end

    for f = 1:numel(fieldsToCheck)

        fieldName = fieldsToCheck{f};

        if ~isfield(data.(branchName), fieldName) || ...
                numel(data.(branchName).(fieldName)) < m || ...
                isempty(data.(branchName).(fieldName){m}) || ...
                ~iscell(data.(branchName).(fieldName){m})

            return;
        end

        for p = 1:nPlanes
            if numel(data.(branchName).(fieldName){m}) < p || ...
                    isempty(data.(branchName).(fieldName){m}{p})
                return;
            end
        end
    end

    tf = false;
end


function tf = motion_group_has_missing_fields(data, fields_motion_group, m)

    tf = true;

    if ~isfield(data, 'motion') || ~isstruct(data.motion)
        return;
    end

    for f = 1:numel(fields_motion_group)

        fn = fields_motion_group{f};

        if ~isfield(data.motion, fn) || ...
                numel(data.motion.(fn)) < m || ...
                isempty(data.motion.(fn){m})

            return;
        end
    end

    tf = false;
end

function data = clear_detection_outputs_for_plane_in_data( ...
    data, m, p, branches_to_clear, ...
    fields_detect_gcamp, ...
    fields_detect_electroporated, ...
    fields_detect_combined)

    for b = 1:numel(branches_to_clear)

        switch branches_to_clear{b}

            case 'gcamp'

                branchName = ...
                    'gcamp_plane';

                fields = ...
                    fields_detect_gcamp;

            case 'electroporated'

                branchName = ...
                    'electroporated_plane';

                fields = ...
                    fields_detect_electroporated;

            case 'combined'

                branchName = ...
                    'combined_plane';

                fields = ...
                    fields_detect_combined;

            otherwise

                continue;
        end

        for f = 1:numel(fields)

            fn = ...
                fields{f};

            if isfield(data, branchName) && ...
                    isfield(data.(branchName), fn) && ...
                    numel(data.(branchName).(fn)) >= m && ...
                    iscell(data.(branchName).(fn){m}) && ...
                    numel(data.(branchName).(fn){m}) >= p

                data.(branchName).(fn){m}{p} = [];
            end
        end
    end
end
