function visualize_data(selected_groups, results_analysis_all)

% visualize_data
% Lance les analyses/visualisations pour chaque groupe sélectionné.
%
% Outputs
%   selected_groups       : structure mise à jour avec data et results_analysis
%   results_analysis_all  : cell array contenant les results_analysis par groupe

    nGroups = length(selected_groups);

    for k = 1:nGroups

        fprintf('\n==============================\n');
        fprintf('Visualisation group %d / %d\n', k, nGroups);
        fprintf('Animal: %s\n', char(string(selected_groups(k).animal_group)));
        fprintf('==============================\n');

        gcamp_root_folders   = selected_groups(k).gcamp_root_folders;
        current_animal_group = selected_groups(k).animal_group;
        current_ani_path_group = selected_groups(k).animal_path;
        current_ages_group   = selected_groups(k).ages;    
        data                 = selected_groups(k).data;
        
        results_analysis = results_analysis_all{k};
        % ======================================================
        % Plots
        % ======================================================
        plot_all_pairwise_corr_types( ...
            current_ages_group, ...
            data, ...
            gcamp_root_folders, ...
            current_animal_group);

        plot_frequency_boxplot( ...
            results_analysis, ...
            gcamp_root_folders, ...
            current_animal_group, ...
            current_ages_group);

        plot_gcamp_histograms( ...
            results_analysis, ...
            gcamp_root_folders, ...
            current_animal_group, ...
            current_ages_group);

        plot_basic_metrics_boxplots_by_age( ...
            current_ages_group, ...
            results_analysis, ...
            current_ani_path_group, ...
            current_animal_group);
    end
end