function visualize_data( ...
        selected_groups, ...
        automatic_selection, ...
        include_blue_cells, ...
        results_table, ...
        output_folders)
    
    %==============================================================
    % 1) Overview général et légende commune
    %==============================================================
    [~, ~, ~, legend_table] = ...
        plot_selected_groups_overview( ...
            selected_groups, ...
            include_blue_cells, ...
            automatic_selection, ...
            output_folders);

    %==============================================================
    % 2) Comparaison statistique entre types
    %==============================================================
    type_names = fieldnames(selected_groups);

    valid_types = type_names( ...
        cellfun(@(type_name) ...
            ~isempty(selected_groups.(type_name)), ...
            type_names));

    if any(automatic_selection) && ...
            ~include_blue_cells && ...
            numel(valid_types) >= 2

        compare_groups_barplots( ...
            results_table, ...
            3, ...
            'gcamp_plane', ...
            legend_table);
    end

    %==============================================================
    % 3) Métriques principales par type
    %==============================================================
    % plot_basic_metrics_by_type( ...
    %     selected_groups, ...
    %     4, ...
    %     legend_table, ...
    %     output_folders);

    %==============================================================
    % 4) Figures individuelles par animal
    %==============================================================
    for t = 1:numel(type_names)

        current_type = type_names{t};

        for k = 1:numel(selected_groups.(current_type))

            animal_struct = selected_groups.(current_type)(k);

            fprintf('\n==============================\n');
            fprintf('Visualisation\n');
            fprintf('Type: %s\n', current_type);
            fprintf('Animal %d / %d: %s\n', ...
                k, ...
                numel(selected_groups.(current_type)), ...
                char(string(animal_struct.animal)));
            fprintf('==============================\n');

            gcamp_root_folders = animal_struct.paths.gcamp_root;
            current_animal = animal_struct.animal;
            current_ages_group = animal_struct.ages;
            results_analysis = animal_struct.results_analysis;

            plot_all_pairwise_corr_types( ...
                current_ages_group, ...
                results_analysis, ...
                gcamp_root_folders, ...
                current_animal);

            plot_frequency_boxplot( ...
                include_blue_cells, ...
                results_analysis, ...
                gcamp_root_folders, ...
                current_animal, ...
                current_ages_group);

            plot_gcamp_histograms( ...
                results_analysis, ...
                gcamp_root_folders, ...
                current_animal, ...
                current_ages_group);
        end
    end
end