function [selected_groups, metadata_table] = create_metadata(selected_groups)

    metadata_table = table();

    if nargin < 1 || isempty(selected_groups)
        return;
    end

    save_to_excel = true;
    force_rebuild_metadata = true;

    type_names = fieldnames(selected_groups);

    for t = 1:numel(type_names)

        current_type = type_names{t};

        for k = 1:numel(selected_groups.(current_type))

            fprintf('\n==============================\n');
            fprintf('Metadata extraction\n');
            fprintf('Type: %s\n', current_type);
            fprintf('Animal %d / %d: %s\n', ...
                k, ...
                numel(selected_groups.(current_type)), ...
                string(selected_groups.(current_type)(k).animal));
            fprintf('==============================\n');

            % ==========================================================
            % Structure metadata
            %
            % metadata.gcamp_plane
            % metadata.electroporated_plane
            % metadata.ZSeries
            % ==========================================================

            selected_groups.(current_type)(k).metadata = ...
                empty_metadata_container();

            if ~isfield(selected_groups.(current_type)(k), 'paths') || ...
                    ~isstruct(selected_groups.(current_type)(k).paths)

                fprintf('Aucun champ paths disponible -> skip animal.\n');
                continue;
            end

            current_paths = ...
                selected_groups.(current_type)(k).paths;

            % ==========================================================
            % Dossier animal
            % ==========================================================

            if isfield(current_paths, 'animal') && ...
                    ~isempty(current_paths.animal)

                current_ani_path_group = ...
                    current_paths.animal;

            else

                current_ani_path_group = '';
            end

            % ==========================================================
            % TSeries
            %
            % 1 = GCaMP
            % 2 = Red
            % 3 = Blue
            % 4 = Green
            % ==========================================================

            if isfield(current_paths, 'TSeries') && ...
                    ~isempty(current_paths.TSeries)

                current_TSeries_group = ...
                    force_4col( ...
                        current_paths.TSeries);

            else

                current_TSeries_group = ...
                    cell(0,4);
            end

            % ==========================================================
            % XML
            %
            % 1 = GCaMP
            % 2 = Red
            % 3 = Blue
            % 4 = Green
            % 5 = ZSeries
            % ==========================================================

            if isfield(current_paths, 'xml') && ...
                    ~isempty(current_paths.xml)

                current_xml_group = ...
                    force_5col( ...
                        current_paths.xml);

            else

                current_xml_group = ...
                    cell( ...
                        size(current_TSeries_group,1), ...
                        5);
            end

            % ==========================================================
            % Nombre de recordings
            % ==========================================================

            nRecordings = max([ ...
                size(current_TSeries_group,1), ...
                size(current_xml_group,1), ...
                numel_safe_field( ...
                    selected_groups.(current_type)(k), ...
                    'dates')]);

            if nRecordings == 0

                fprintf('Aucun recording disponible -> skip animal.\n');
                continue;
            end

            current_TSeries_group = ...
                resize_4col( ...
                    current_TSeries_group, ...
                    nRecordings);

            current_xml_group = ...
                resize_5col( ...
                    current_xml_group, ...
                    nRecordings);

            % ==========================================================
            % Canal électroporé
            % ==========================================================

            electroporated_column_by_group = ...
                find_electroporated_column_from_tseries( ...
                    current_TSeries_group, ...
                    nRecordings);

            % ==========================================================
            % GCaMP root
            % ==========================================================

            if isfield(current_paths, 'gcamp_root') && ...
                    ~isempty(current_paths.gcamp_root)

                this_group_folders = ...
                    current_paths.gcamp_root;

            else

                this_group_folders = ...
                    cell(nRecordings,1);
            end

            if isrow(this_group_folders)
                this_group_folders = this_group_folders(:);
            end

            if numel(this_group_folders) < nRecordings

                tmp = ...
                    cell(nRecordings,1);

                tmp(1:numel(this_group_folders)) = ...
                    this_group_folders(:);

                this_group_folders = ...
                    tmp;
            end

            % ==========================================================
            % Fichiers Excel groupés
            % ==========================================================

            group_output_path_gcamp = '';
            group_output_path_electroporated = '';

            if save_to_excel && ...
                    ~isempty(current_ani_path_group)

                group_output_path_gcamp = ...
                    fullfile( ...
                        current_ani_path_group, ...
                        'metadata_results_group_gcamp.xlsx');

                group_output_path_electroporated = ...
                    fullfile( ...
                        current_ani_path_group, ...
                        'metadata_results_group_electroporated.xlsx');
            end

            [ ...
                group_table_gcamp, ...
                group_file_existed_gcamp ...
            ] = ...
                load_existing_group_table( ...
                    group_output_path_gcamp, ...
                    save_to_excel);

            [ ...
                group_table_electroporated, ...
                group_file_existed_electroporated ...
            ] = ...
                load_existing_group_table( ...
                    group_output_path_electroporated, ...
                    save_to_excel);

            group_table_modified_gcamp = false;
            group_table_modified_electroporated = false;

            % ==========================================================
            % BOUCLE RECORDINGS
            % ==========================================================

            for idx = 1:nRecordings

                % ======================================================
                % Date
                % ======================================================

                date = '';

                if isfield( ...
                        selected_groups.(current_type)(k), ...
                        'dates') && ...
                        numel( ...
                            selected_groups.(current_type)(k).dates) >= idx && ...
                        ~isempty( ...
                            selected_groups.(current_type)(k).dates{idx})

                    date = ...
                        selected_groups.(current_type)(k).dates{idx};
                end

                % ======================================================
                % Dossier output GCaMP
                % ======================================================

                this_folder = '';

                if idx <= numel(this_group_folders) && ...
                        ~isempty(this_group_folders{idx})

                    this_folder = ...
                        this_group_folders{idx};
                end

                % ======================================================
                % XML GCaMP
                % ======================================================

                gcamp_xml_file = ...
                    current_xml_group{idx,1};

                % ======================================================
                % XML électroporé
                % ======================================================

                electroporated_xml_file = '';

                electroporated_column = ...
                    electroporated_column_by_group(idx);

                if isfinite(electroporated_column)

                    electroporated_xml_file = ...
                        current_xml_group{ ...
                            idx, ...
                            electroporated_column};
                end

                % ======================================================
                % XML ZSeries
                % ======================================================

                zseries_xml_file = ...
                    current_xml_group{idx,5};

                % ======================================================
                % Affichage
                % ======================================================

                fprintf( ...
                    '\nRecording %d/%d\n', ...
                    idx, ...
                    nRecordings);

                fprintf( ...
                    'GCaMP XML: %s\n', ...
                    display_path(gcamp_xml_file));

                if isfinite(electroporated_column)

                    fprintf( ...
                        'Electroporated channel: column %d\n', ...
                        electroporated_column);

                    fprintf( ...
                        'Electroporated XML: %s\n', ...
                        display_path( ...
                            electroporated_xml_file));

                else

                    fprintf( ...
                        'Electroporated channel: none\n');
                end

                fprintf( ...
                    'ZSeries XML: %s\n', ...
                    display_path( ...
                        zseries_xml_file));

                % ======================================================
                % GCaMP metadata
                % ======================================================

                [ ...
                    selected_groups.(current_type)(k). ...
                        metadata.gcamp_plane, ...
                    rowTable_gcamp ...
                ] = ...
                    process_one_metadata_branch( ...
                        selected_groups.(current_type)(k). ...
                            metadata.gcamp_plane, ...
                        gcamp_xml_file, ...
                        date, ...
                        this_folder, ...
                        idx, ...
                        'gcamp', ...
                        save_to_excel, ...
                        force_rebuild_metadata);

                % ======================================================
                % Electroporated metadata
                % ======================================================

                if ~isempty(electroporated_xml_file)

                    [ ...
                        selected_groups.(current_type)(k). ...
                            metadata.electroporated_plane, ...
                        rowTable_electroporated ...
                    ] = ...
                        process_one_metadata_branch( ...
                            selected_groups.(current_type)(k). ...
                                metadata.electroporated_plane, ...
                            electroporated_xml_file, ...
                            date, ...
                            this_folder, ...
                            idx, ...
                            'electroporated', ...
                            save_to_excel, ...
                            force_rebuild_metadata);

                else

                    rowTable_electroporated = ...
                        table();
                end

                % ======================================================
                % ZSeries metadata
                % ======================================================

                if ~isempty(zseries_xml_file) && ...
                        exist(zseries_xml_file, 'file') == 2

                    zmeta = ...
                        find_zseries_metadata( ...
                            zseries_xml_file);

                    zmeta.Date = ...
                        date;

                    z_fields = ...
                        fieldnames(zmeta);

                    for f = 1:numel(z_fields)

                        fn = ...
                            z_fields{f};

                        if ~isfield( ...
                                selected_groups.(current_type)(k). ...
                                    metadata.ZSeries, ...
                                fn)

                            selected_groups.(current_type)(k). ...
                                metadata.ZSeries.(fn) = {};
                        end

                        selected_groups.(current_type)(k). ...
                            metadata.ZSeries.(fn){idx,1} = ...
                                zmeta.(fn);
                    end

                else

                    fprintf( ...
                        'ZSeries metadata rec %d: XML unavailable.\n', ...
                        idx);
                end

                % ======================================================
                % Tableau global GCaMP
                % ======================================================

                if ~isempty(rowTable_gcamp) && ...
                        height(rowTable_gcamp) >= 1

                    metadata_table = ...
                        append_metadata_summary( ...
                            metadata_table, ...
                            rowTable_gcamp, ...
                            current_type, ...
                            selected_groups.(current_type)(k), ...
                            'gcamp_plane');
                end

                % ======================================================
                % Tableau global Electroporated
                % ======================================================

                if ~isempty(rowTable_electroporated) && ...
                        height(rowTable_electroporated) >= 1

                    metadata_table = ...
                        append_metadata_summary( ...
                            metadata_table, ...
                            rowTable_electroporated, ...
                            current_type, ...
                            selected_groups.(current_type)(k), ...
                            'electroporated_plane');
                end

                % ======================================================
                % Excel groupé GCaMP
                % ======================================================

                if ~isempty(rowTable_gcamp) && ...
                        height(rowTable_gcamp) >= 1

                    [ ...
                        group_table_gcamp, ...
                        modified ...
                    ] = ...
                        add_metadata_row_if_new_date( ...
                            group_table_gcamp, ...
                            rowTable_gcamp);

                    group_table_modified_gcamp = ...
                        group_table_modified_gcamp || ...
                        modified;
                end

                % ======================================================
                % Excel groupé électroporé
                % ======================================================

                if ~isempty(rowTable_electroporated) && ...
                        height(rowTable_electroporated) >= 1

                    [ ...
                        group_table_electroporated, ...
                        modified ...
                    ] = ...
                        add_metadata_row_if_new_date( ...
                            group_table_electroporated, ...
                            rowTable_electroporated);

                    group_table_modified_electroporated = ...
                        group_table_modified_electroporated || ...
                        modified;
                end
            end

            % ==========================================================
            % Sauvegarde Excel groupée
            % ==========================================================

            if save_to_excel

                save_group_metadata_table( ...
                    group_table_gcamp, ...
                    group_output_path_gcamp, ...
                    group_file_existed_gcamp, ...
                    group_table_modified_gcamp);

                selected_groups.(current_type)(k). ...
                    metadata.gcamp_plane.source_file = ...
                    group_output_path_gcamp;

                save_group_metadata_table( ...
                    group_table_electroporated, ...
                    group_output_path_electroporated, ...
                    group_file_existed_electroporated, ...
                    group_table_modified_electroporated);

                selected_groups.(current_type)(k). ...
                    metadata.electroporated_plane.source_file = ...
                    group_output_path_electroporated;
            end
        end
    end
end


%% ========================================================================
% TRAITEMENT D'UNE BRANCHE
% ========================================================================

function [metadata_branch, rowTable] = ...
        process_one_metadata_branch( ...
            metadata_branch, ...
            xml_file, ...
            date, ...
            this_folder, ...
            idx, ...
            branch_name, ...
            save_to_excel, ...
            force_rebuild_metadata)

    rowTable = table();

    if isempty(xml_file) || ...
            exist(xml_file, 'file') ~= 2

        fprintf( ...
            '%s metadata rec %d: XML unavailable.\n', ...
            branch_name, ...
            idx);

        return;
    end

    % ==============================================================
    % Fichier Excel individuel
    % ==============================================================

    output_path_single = '';

    if ~isempty(this_folder)

        if ~exist(this_folder, 'dir')
            mkdir(this_folder);
        end

        switch lower(branch_name)

            case 'gcamp'

                output_path_single = ...
                    fullfile( ...
                        this_folder, ...
                        'metadata_results_gcamp.xlsx');

            case 'electroporated'

                output_path_single = ...
                    fullfile( ...
                        this_folder, ...
                        'metadata_results_electroporated.xlsx');
        end
    end

    loaded_from_single_file = false;

    % ==============================================================
    % Reconstruction forcée
    % ==============================================================

    if force_rebuild_metadata && ...
            ~isempty(output_path_single) && ...
            exist(output_path_single, 'file') == 2

        fprintf( ...
            '%s metadata rec %d: deleting old Excel -> rebuild from XML\n', ...
            branch_name, ...
            idx);

        delete(output_path_single);
    end

    % ==============================================================
    % Lecture Excel
    % ==============================================================

    if save_to_excel && ...
            ~isempty(output_path_single) && ...
            exist(output_path_single, 'file') == 2

        try

            rowTable = ...
                readtable( ...
                    output_path_single, ...
                    'VariableNamingRule', ...
                    'preserve');

            rowTable = ...
                normalize_metadata_table( ...
                    rowTable);

            if height(rowTable) > 1
                rowTable = rowTable(1,:);
            end

            if ~isempty(rowTable) && ...
                    isempty_value(rowTable.Date{1}) && ...
                    ~isempty(date)

                rowTable.Date{1} = ...
                    date;
            end

            loaded_from_single_file = true;

            fprintf( ...
                '%s metadata rec %d loaded from Excel\n', ...
                branch_name, ...
                idx);

        catch ME

            warning( ...
                'Impossible de relire %s : %s', ...
                output_path_single, ...
                ME.message);

            try
                delete(output_path_single);
            catch
            end

            rowTable = table();
        end
    end

    % ==============================================================
    % Extraction XML
    % ==============================================================

    if ~loaded_from_single_file

        meta_xml = ...
            find_key_value( ...
                xml_file);

        meta_xml.Date = ...
            date;

        rowTable = ...
            struct2table( ...
                meta_xml, ...
                'AsArray', ...
                true);

        rowTable = ...
            normalize_metadata_table( ...
                rowTable);

        if save_to_excel && ...
                ~isempty(output_path_single)

            writetable( ...
                rowTable, ...
                output_path_single, ...
                'FileType', ...
                'spreadsheet');

            fprintf( ...
                '%s metadata rec %d saved -> %s\n', ...
                branch_name, ...
                idx, ...
                output_path_single);
        end
    end

    if isempty(rowTable) || ...
            height(rowTable) < 1

        return;
    end

    metadata_branch = ...
        add_row_to_metadata_struct( ...
            metadata_branch, ...
            rowTable, ...
            idx);
end


%% ========================================================================
% INITIALISATION
% ========================================================================

function metadata = empty_metadata_container()

    metadata = struct();

    metadata.gcamp_plane = ...
        empty_metadata_struct();

    metadata.electroporated_plane = ...
        empty_metadata_struct();

    metadata.ZSeries = ...
        empty_zseries_metadata_struct();
end


function metadata = empty_metadata_struct()

    fields = ...
        metadata_field_list();

    metadata = struct();

    for i = 1:numel(fields)

        metadata.(fields{i}) = {};
    end

    metadata.source_file = '';
end


function metadata = empty_zseries_metadata_struct()

    fields = { ...
        'Date', ...
        'RecordingTime', ...
        'NumSlices', ...
        'ZStart_um', ...
        'ZEnd_um', ...
        'ZStep_um', ...
        'ZSpan_um', ...
        'ZDirection', ...
        'ZPositions', ...
        'PositionX_um', ...
        'PositionY_um', ...
        'PixelsPerLine', ...
        'LinesPerFrame', ...
        'ImageSize', ...
        'PixelSizeX_um', ...
        'PixelSizeY_um', ...
        'PixelSize_um', ...
        'OpticalZoom', ...
        'ObjectiveLens', ...
        'LaserWavelength_nm', ...
        'LaserPowerByPlane_Pockels', ...
        'LaserPowerMin_Pockels', ...
        'LaserPowerMax_Pockels', ...
        'LaserPowerGradient_Pockels_per_um', ...
        'PMTGain_Electroporated'};

    metadata = struct();

    for i = 1:numel(fields)

        metadata.(fields{i}) = {};
    end
end


%% ========================================================================
% TABLE GLOBAL
% ========================================================================

function metadata_table = ...
        append_metadata_summary( ...
            metadata_table, ...
            rowTable, ...
            current_type, ...
            current_group, ...
            branch_name)

    current_mtor = '';

    if isfield(current_group, 'line')

        current_mtor = ...
            current_group.line;
    end

    current_animal = '';

    if isfield(current_group, 'animal')

        current_animal = ...
            current_group.animal;
    end

    summary_row = ...
        table( ...
            string(current_type), ...
            string(current_mtor), ...
            string(current_animal), ...
            string(branch_name), ...
            string(get_metadata_value( ...
                rowTable, ...
                'Date')), ...
            get_metadata_value( ...
                rowTable, ...
                'NumPlanes'), ...
            get_metadata_value( ...
                rowTable, ...
                'OpticalZoom'), ...
            get_metadata_value( ...
                rowTable, ...
                'SamplingRatePlane'), ...
            get_metadata_value( ...
                rowTable, ...
                'TimeMinutes'), ...
            'VariableNames', { ...
                'Type', ...
                'mTOR', ...
                'Animal', ...
                'Branch', ...
                'Date', ...
                'NumPlanes', ...
                'OpticalZoom', ...
                'SamplingRate_Hz', ...
                'RecordingDuration_min'});

    if isempty(metadata_table)

        metadata_table = ...
            summary_row;

    else

        metadata_table = ...
            [ ...
                metadata_table; ...
                summary_row ...
            ];
    end
end


%% ========================================================================
% FICHIER GROUPÉ
% ========================================================================

function [group_table, existed] = ...
        load_existing_group_table( ...
            group_output_path, ...
            save_to_excel)

    group_table = ...
        table();

    existed = ...
        save_to_excel && ...
        ~isempty(group_output_path) && ...
        exist(group_output_path, 'file') == 2;

    if ~existed
        return;
    end

    try

        group_table = ...
            readtable( ...
                group_output_path, ...
                'VariableNamingRule', ...
                'preserve');

        group_table = ...
            normalize_metadata_table( ...
                group_table);

    catch ME

        warning( ...
            'Impossible de relire %s : %s', ...
            group_output_path, ...
            ME.message);

        group_table = table();
        existed = false;
    end
end


function [group_table, modified] = ...
        add_metadata_row_if_new_date( ...
            group_table, ...
            rowTable)

    modified = false;

    rowTable = ...
        normalize_metadata_table( ...
            rowTable);

    if isempty(group_table)

        group_table = ...
            rowTable;

        modified = true;

        return;
    end

    group_table = ...
        normalize_metadata_table( ...
            group_table);

    % ==========================================================
    % Date du nouveau recording
    % ==========================================================

    current_date = ...
        get_metadata_value( ...
            rowTable, ...
            'Date');

    current_date = ...
        unwrap_metadata_value( ...
            current_date);

    if isempty_value(current_date)
        return;
    end

    % ==========================================================
    % Comparaison aux dates existantes
    % ==========================================================

    existing_dates = ...
        strings( ...
            height(group_table), ...
            1);

    for i = 1:height(group_table)

        value = ...
            group_table.Date{i};

        value = ...
            unwrap_metadata_value( ...
                value);

        if ~isempty_value(value)

            existing_dates(i) = ...
                string(value);
        end
    end

    if any( ...
            existing_dates == ...
            string(current_date))

        return;
    end

    % ==========================================================
    % Ajouter ligne
    % ==========================================================

    group_table = ...
        [ ...
            group_table; ...
            rowTable ...
        ];

    modified = true;
end


function save_group_metadata_table( ...
        group_table, ...
        output_path, ...
        file_existed, ...
        modified)

    if isempty(output_path) || ...
            isempty(group_table)

        return;
    end

    output_folder = ...
        fileparts( ...
            output_path);

    if ~exist(output_folder, 'dir')

        mkdir(output_folder);
    end

    if ~file_existed || ...
            modified

        group_table = ...
            normalize_metadata_table( ...
                group_table);

        writetable( ...
            group_table, ...
            output_path, ...
            'FileType', ...
            'spreadsheet');

        fprintf( ...
            'Grouped metadata saved -> %s\n', ...
            output_path);
    end
end


%% ========================================================================
% METADATA FIELDS
% ========================================================================

function fields = metadata_field_list()

    fields = { ...
        'Date', ...
        'RecordingTime', ...
        'ActiveMode', ...
        'BitDepth', ...
        'SamplingRate', ...
        'FramePeriod', ...
        'SamplingRatePlane', ...
        'InterplaneDelay_s', ...
        'PixelsPerLine', ...
        'LinesPerFrame', ...
        'ImageSize', ...
        'DwellTime_us', ...
        'ScanLinePeriod_s', ...
        'SamplesPerPixel', ...
        'OpticalZoom', ...
        'ObjectiveLens', ...
        'ObjectiveLensMag', ...
        'ObjectiveLensNA', ...
        'PixelSizeX_um', ...
        'PixelSizeY_um', ...
        'PixelSize_um', ...
        'PositionX_um', ...
        'PositionY_um', ...
        'PositionZ', ...
        'NumPlanes', ...
        'ZStep_um', ...
        'ZMin_um', ...
        'ZMax_um', ...
        'LaserWavelength_nm', ...
        'LaserPower_Pockels', ...
        'LaserPowerByPlane_Pockels', ...
        'PMTGain_Red', ...
        'PMTGain_Green', ...
        'PMTGain_Blue', ...
        'TimeMinutes', ...
        'NumFrames', ...
        'ChannelNames', ...
        'NumChannels', ...
        'BidirectionalZ'};
end


%% ========================================================================
% NORMALISATION TABLE
% ========================================================================

function T = normalize_metadata_table(T)

    expected_fields = ...
        metadata_field_list();

    T = ...
        remove_unused_metadata_columns( ...
            T);

    if isempty(T)

        T = ...
            cell2table( ...
                cell( ...
                    0, ...
                    numel(expected_fields)), ...
                'VariableNames', ...
                expected_fields);

        return;
    end

    nRows = ...
        height(T);

    for i = 1:numel(expected_fields)

        field = ...
            expected_fields{i};

        if ~any(strcmp( ...
                T.Properties.VariableNames, ...
                field))

            T.(field) = ...
                cell(nRows,1);
        end
    end

    current_fields = ...
        T.Properties.VariableNames;

    for i = 1:numel(current_fields)

        field = ...
            current_fields{i};

        if ~any(strcmp( ...
                expected_fields, ...
                field))

            T(:,field) = [];
        end
    end

    T = ...
        T(:,expected_fields);

    for i = 1:numel(expected_fields)

        field = ...
            expected_fields{i};

        if ~iscell(T.(field))

            T.(field) = ...
                num2cell( ...
                    T.(field));
        end
    end
end


%% ========================================================================
% ADD ROW
% ========================================================================

function metadata = ...
        add_row_to_metadata_struct( ...
            metadata, ...
            T, ...
            idx)

    wanted_fields = ...
        metadata_field_list();

    T = ...
        normalize_metadata_table( ...
            T);

    for i = 1:numel(wanted_fields)

        field = ...
            wanted_fields{i};

        if ~isfield(metadata, field)

            metadata.(field) = {};
        end

        if isempty(T) || ...
                height(T) < 1

            metadata.(field){idx,1} = [];

        else

            metadata.(field){idx,1} = ...
                T.(field){1};
        end
    end
end


%% ========================================================================
% REMOVE UNUSED
% ========================================================================

function T = remove_unused_metadata_columns(T)

    remove_fields = { ...
        'RastersPerFrame', ...
        'LaserPower_1040', ...
        'LaserPowerByPlane_1040', ...
        'PMTGainByPlane_Red', ...
        'PMTGainByPlane_Green', ...
        'PMTGainByPlane_Blue'};

    for i = 1:numel(remove_fields)

        field = ...
            remove_fields{i};

        if any(strcmp( ...
                T.Properties.VariableNames, ...
                field))

            T(:,field) = [];
        end
    end
end


%% ========================================================================
% DÉTECTION CANAL ÉLECTROPORÉ
% ========================================================================

function electroporated_column_by_group = ...
        find_electroporated_column_from_tseries( ...
            TSeries_group, ...
            nRecordings)

    electroporated_column_by_group = ...
        nan(nRecordings,1);

    TSeries_group = ...
        resize_4col( ...
            TSeries_group, ...
            nRecordings);

    for idx = 1:nRecordings

        % Colonne 2 prioritaire puis 3.
        for col = [2 3]

            if isempty(TSeries_group{idx,col})
                continue;
            end

            electroporated_column_by_group(idx) = ...
                col;

            break;
        end
    end
end


%% ========================================================================
% HELPERS
% ========================================================================

function tf = isempty_value(x)

    if isempty(x)

        tf = true;

    elseif isstring(x)

        tf = ...
            all(strlength(x) == 0);

    elseif ischar(x)

        tf = ...
            isempty(strtrim(x));

    elseif iscell(x)

        tf = ...
            isempty(x) || ...
            isempty_value(x{1});

    elseif ismissing(x)

        tf = true;

    else

        tf = false;
    end
end


function value = unwrap_metadata_value(value)

    while iscell(value)

        if isempty(value)

            value = [];
            return;
        end

        value = ...
            value{1};
    end
end


function value = get_metadata_value(T, field)

    value = [];

    if isempty(T) || ...
            height(T) < 1

        return;
    end

    if ~any(strcmp( ...
            T.Properties.VariableNames, ...
            field))

        return;
    end

    value = ...
        T.(field);

    if iscell(value)

        if isempty(value)
            return;
        end

        value = ...
            value{1};

        value = ...
            unwrap_metadata_value( ...
                value);

    else

        value = ...
            value(1);
    end
end


%% ========================================================================
% MATRICES
% ========================================================================

function C4 = force_4col(C)

    if isempty(C)

        C4 = ...
            cell(0,4);

        return;
    end

    nRows = ...
        size(C,1);

    nCols = ...
        size(C,2);

    C4 = ...
        cell(nRows,4);

    C4(:,1:min(4,nCols)) = ...
        C(:,1:min(4,nCols));
end


function C5 = force_5col(C)

    if isempty(C)

        C5 = ...
            cell(0,5);

        return;
    end

    nRows = ...
        size(C,1);

    nCols = ...
        size(C,2);

    C5 = ...
        cell(nRows,5);

    C5(:,1:min(5,nCols)) = ...
        C(:,1:min(5,nCols));
end


function C = resize_4col(C, nRows)

    C = ...
        force_4col(C);

    out = ...
        cell(nRows,4);

    nCopy = ...
        min( ...
            size(C,1), ...
            nRows);

    if nCopy > 0

        out(1:nCopy,:) = ...
            C(1:nCopy,:);
    end

    C = ...
        out;
end


function C = resize_5col(C, nRows)

    C = ...
        force_5col(C);

    out = ...
        cell(nRows,5);

    nCopy = ...
        min( ...
            size(C,1), ...
            nRows);

    if nCopy > 0

        out(1:nCopy,:) = ...
            C(1:nCopy,:);
    end

    C = ...
        out;
end


function n = numel_safe_field(S, field)

    n = 0;

    if isfield(S, field) && ...
            ~isempty(S.(field))

        n = ...
            numel(S.(field));
    end
end


function txt = display_path(path)

    if isempty(path)

        txt = ...
            '<none>';

    else

        txt = ...
            path;
    end
end