function [selected_groups, metadata_table] = create_metadata(selected_groups)

    metadata_table = table();

    if nargin < 1 || isempty(selected_groups)
        return;
    end

    save_to_excel = true;

    type_names = fieldnames(selected_groups);

    for t = 1:numel(type_names)

        current_type = type_names{t};

        for k = 1:numel(selected_groups.(current_type))

            fprintf('\n==============================\n');
            fprintf('Metadata extraction\n');
            fprintf('Type: %s\n', current_type);
            fprintf('Animal %d / %d: %s\n', ...
                k, ...
                numel(selected_groups.(current_type)), ...
                char(string( ...
                    selected_groups.(current_type)(k).animal)));
            fprintf('==============================\n');

            % ==========================================================
            % Réinitialiser metadata
            %
            % Structure :
            %
            % metadata.gcamp_plane
            % metadata.electroporated_plane
            % ==========================================================

            selected_groups.(current_type)(k).metadata = ...
                empty_metadata_container();

            if ~isfield(selected_groups.(current_type)(k), 'paths') || ...
                    ~isstruct(selected_groups.(current_type)(k).paths)

                fprintf('Aucun champ paths disponible -> skip animal.\n');
                continue;
            end

            current_paths = ...
                selected_groups.(current_type)(k).paths;

            % ==========================================================
            % Dossier animal
            % ==========================================================

            if isfield(current_paths, 'animal') && ...
                    ~isempty(current_paths.animal)

                current_ani_path_group = ...
                    force_char_path( ...
                        current_paths.animal);

            else

                current_ani_path_group = '';
            end

            % ==========================================================
            % TSeries
            %
            % Colonnes :
            %   1 = GCaMP
            %   2 = canal électroporé potentiel
            %   3 = canal électroporé potentiel
            %   4 = Green
            %
            % Suite2p n'est PAS nécessaire ici.
            % ==========================================================

            if isfield(current_paths, 'TSeries') && ...
                    ~isempty(current_paths.TSeries)

                current_TSeries_group = ...
                    force_4col( ...
                        current_paths.TSeries);

            else

                current_TSeries_group = ...
                    cell(0,4);
            end

            % ==========================================================
            % XML
            % ==========================================================

            if isfield(current_paths, 'xml') && ...
                    ~isempty(current_paths.xml)

                current_xml_group = ...
                    force_4col( ...
                        current_paths.xml);

            else

                current_xml_group = ...
                    cell( ...
                        size(current_TSeries_group,1), ...
                        4);
            end

            % ==========================================================
            % Nombre d'enregistrements
            %
            % IMPORTANT :
            % aucune dépendance à Suite2p.
            % ==========================================================

            nRecordings = max([ ...
                size(current_TSeries_group,1), ...
                size(current_xml_group,1), ...
                numel_safe_field( ...
                    selected_groups.(current_type)(k), ...
                    'dates')]);

            if nRecordings == 0

                fprintf('Aucun recording disponible -> skip animal.\n');
                continue;
            end

            current_TSeries_group = ...
                resize_4col( ...
                    current_TSeries_group, ...
                    nRecordings);

            current_xml_group = ...
                resize_4col( ...
                    current_xml_group, ...
                    nRecordings);

            % ==========================================================
            % Déterminer le canal électroporé
            %
            % IMPORTANT :
            % cette détection repose uniquement sur les TSeries.
            % Elle fonctionne donc même si Suite2p n'existe pas encore.
            %
            % Priorité :
            %   colonne 2
            %   puis colonne 3
            % ==========================================================

            electroporated_column_by_group = ...
                find_electroporated_column_from_tseries( ...
                    current_TSeries_group, ...
                    nRecordings);

            % ==========================================================
            % GCaMP root
            %
            % Peut être totalement vide.
            % Les metadata seront quand même extraites depuis XML.
            % ==========================================================

            if isfield(current_paths, 'gcamp_root') && ...
                    ~isempty(current_paths.gcamp_root)

                this_group_folders = ...
                    current_paths.gcamp_root;

            else

                this_group_folders = ...
                    cell(nRecordings,1);
            end

            if isrow(this_group_folders)
                this_group_folders = this_group_folders(:);
            end

            if numel(this_group_folders) < nRecordings

                tmp = cell(nRecordings,1);

                tmp(1:numel(this_group_folders)) = ...
                    this_group_folders(:);

                this_group_folders = tmp;
            end

            % ==========================================================
            % Fichiers Excel groupés
            % ==========================================================

            group_output_path_gcamp = '';
            group_output_path_electroporated = '';

            if save_to_excel && ...
                    ~isempty(current_ani_path_group)

                group_output_path_gcamp = ...
                    fullfile( ...
                        current_ani_path_group, ...
                        'metadata_results_group_gcamp.xlsx');

                group_output_path_electroporated = ...
                    fullfile( ...
                        current_ani_path_group, ...
                        'metadata_results_group_electroporated.xlsx');
            end

            % ==========================================================
            % Charger fichiers groupés existants
            % ==========================================================

            [ ...
                group_table_gcamp, ...
                group_file_existed_gcamp ...
            ] = ...
                load_existing_group_table( ...
                    group_output_path_gcamp, ...
                    save_to_excel);

            [ ...
                group_table_electroporated, ...
                group_file_existed_electroporated ...
            ] = ...
                load_existing_group_table( ...
                    group_output_path_electroporated, ...
                    save_to_excel);

            group_table_modified_gcamp = false;
            group_table_modified_electroporated = false;

            % ==========================================================
            % BOUCLE RECORDINGS
            % ==========================================================

            for idx = 1:nRecordings

                % ======================================================
                % Date
                % ======================================================

                date_name = '';

                if isfield( ...
                        selected_groups.(current_type)(k), ...
                        'dates') && ...
                        numel( ...
                            selected_groups.(current_type)(k).dates) >= idx && ...
                        ~isempty( ...
                            selected_groups.(current_type)(k).dates{idx})

                    date_name = ...
                        force_char_path( ...
                            selected_groups. ...
                                (current_type)(k).dates{idx});
                end

                % ======================================================
                % GCaMP root du recording
                %
                % Peut être vide.
                % ======================================================

                this_folder = '';

                if idx <= numel(this_group_folders) && ...
                        ~isempty(this_group_folders{idx})

                    this_folder = ...
                        force_char_path( ...
                            this_group_folders{idx});
                end

                % ======================================================
                % XML GCaMP = colonne 1
                % ======================================================

                gcamp_xml_file = ...
                    get_matrix_path( ...
                        current_xml_group, ...
                        idx, ...
                        1);

                % ======================================================
                % XML électroporé
                % ======================================================

                electroporated_xml_file = '';

                electroporated_column = NaN;

                if idx <= numel(electroporated_column_by_group)

                    electroporated_column = ...
                        electroporated_column_by_group(idx);
                end

                if isfinite(electroporated_column) && ...
                        electroporated_column >= 1 && ...
                        electroporated_column <= 4

                    electroporated_xml_file = ...
                        get_matrix_path( ...
                            current_xml_group, ...
                            idx, ...
                            electroporated_column);
                end

                fprintf('\nRecording %d/%d\n', ...
                    idx, ...
                    nRecordings);

                fprintf( ...
                    'GCaMP XML: %s\n', ...
                    display_path(gcamp_xml_file));

                if isfinite(electroporated_column)

                    fprintf( ...
                        'Electroporated channel: column %d\n', ...
                        electroporated_column);

                    fprintf( ...
                        'Electroporated XML: %s\n', ...
                        display_path(electroporated_xml_file));

                else

                    fprintf( ...
                        'Electroporated channel: none\n');
                end

                % ======================================================
                % GCaMP
                % ======================================================

                [ ...
                    selected_groups.(current_type)(k).metadata.gcamp_plane, ...
                    rowTable_gcamp ...
                ] = ...
                    process_one_metadata_branch( ...
                        selected_groups.(current_type)(k). ...
                            metadata.gcamp_plane, ...
                        gcamp_xml_file, ...
                        date_name, ...
                        this_folder, ...
                        idx, ...
                        'gcamp', ...
                        save_to_excel);

                % ======================================================
                % Electroporated
                % ======================================================

                if ~isempty(electroporated_xml_file)

                    [ ...
                        selected_groups.(current_type)(k). ...
                            metadata.electroporated_plane, ...
                        rowTable_electroporated ...
                    ] = ...
                        process_one_metadata_branch( ...
                            selected_groups.(current_type)(k). ...
                                metadata.electroporated_plane, ...
                            electroporated_xml_file, ...
                            date_name, ...
                            this_folder, ...
                            idx, ...
                            'electroporated', ...
                            save_to_excel);

                else

                    rowTable_electroporated = table();
                end

                % ======================================================
                % Tableau global : GCaMP
                % ======================================================

                if ~isempty(rowTable_gcamp) && ...
                        height(rowTable_gcamp) >= 1

                    metadata_table = ...
                        append_metadata_summary( ...
                            metadata_table, ...
                            rowTable_gcamp, ...
                            current_type, ...
                            selected_groups.(current_type)(k), ...
                            'gcamp_plane');
                end

                % ======================================================
                % Tableau global : Electroporated
                % ======================================================

                if ~isempty(rowTable_electroporated) && ...
                        height(rowTable_electroporated) >= 1

                    metadata_table = ...
                        append_metadata_summary( ...
                            metadata_table, ...
                            rowTable_electroporated, ...
                            current_type, ...
                            selected_groups.(current_type)(k), ...
                            'electroporated_plane');
                end

                % ======================================================
                % Ajouter GCaMP au fichier groupé
                % ======================================================

                if ~isempty(rowTable_gcamp) && ...
                        height(rowTable_gcamp) >= 1

                    [ ...
                        group_table_gcamp, ...
                        modified ...
                    ] = ...
                        add_metadata_row_if_new_date( ...
                            group_table_gcamp, ...
                            rowTable_gcamp);

                    group_table_modified_gcamp = ...
                        group_table_modified_gcamp || modified;
                end

                % ======================================================
                % Ajouter electroporated au fichier groupé
                % ======================================================

                if ~isempty(rowTable_electroporated) && ...
                        height(rowTable_electroporated) >= 1

                    [ ...
                        group_table_electroporated, ...
                        modified ...
                    ] = ...
                        add_metadata_row_if_new_date( ...
                            group_table_electroporated, ...
                            rowTable_electroporated);

                    group_table_modified_electroporated = ...
                        group_table_modified_electroporated || modified;
                end
            end

            % ==========================================================
            % Sauvegarde groupée GCaMP
            % ==========================================================

            if save_to_excel

                save_group_metadata_table( ...
                    group_table_gcamp, ...
                    group_output_path_gcamp, ...
                    group_file_existed_gcamp, ...
                    group_table_modified_gcamp);

                selected_groups.(current_type)(k). ...
                    metadata.gcamp_plane.source_file = ...
                    group_output_path_gcamp;

                % ======================================================
                % Sauvegarde groupée Electroporated
                % ======================================================

                save_group_metadata_table( ...
                    group_table_electroporated, ...
                    group_output_path_electroporated, ...
                    group_file_existed_electroporated, ...
                    group_table_modified_electroporated);

                selected_groups.(current_type)(k). ...
                    metadata.electroporated_plane.source_file = ...
                    group_output_path_electroporated;
            end
        end
    end
end


%% ========================================================================
% TRAITEMENT D'UNE BRANCHE
% ========================================================================

function [metadata_branch, rowTable] = ...
        process_one_metadata_branch( ...
            metadata_branch, ...
            xml_file, ...
            date_name, ...
            this_folder, ...
            idx, ...
            branch_name, ...
            save_to_excel)

    rowTable = table();

    % ==============================================================
    % XML absent
    % ==============================================================

    if isempty(xml_file) || ...
            exist(xml_file, 'file') ~= 2

        fprintf( ...
            '%s metadata rec %d: XML unavailable.\n', ...
            branch_name, ...
            idx);

        return;
    end

    % ==============================================================
    % Fichier local
    %
    % Facultatif :
    % si gcamp_root est vide, aucune sauvegarde locale par recording.
    % ==============================================================

    output_path_single = '';

    if ~isempty(this_folder)

        if ~exist(this_folder, 'dir')
            mkdir(this_folder);
        end

        switch lower(branch_name)

            case 'gcamp'

                output_path_single = ...
                    fullfile( ...
                        this_folder, ...
                        'metadata_results_gcamp.xlsx');

            case 'electroporated'

                output_path_single = ...
                    fullfile( ...
                        this_folder, ...
                        'metadata_results_electroporated.xlsx');
        end
    end

    loaded_from_single_file = false;

    % ==============================================================
    % Charger Excel existant
    % ==============================================================

    if save_to_excel && ...
            ~isempty(output_path_single) && ...
            exist(output_path_single, 'file') == 2

        try

            rowTable = ...
                readtable( ...
                    output_path_single, ...
                    'VariableNamingRule', ...
                    'preserve');

            rowTable = ...
                normalize_metadata_table( ...
                    rowTable);

            if height(rowTable) > 1
                rowTable = rowTable(1,:);
            end

            if ~isempty(rowTable) && ...
                    isempty_value( ...
                        rowTable.DateName{1}) && ...
                    ~isempty(date_name)

                rowTable.DateName{1} = ...
                    date_name;
            end

            loaded_from_single_file = true;

            fprintf( ...
                '%s metadata rec %d loaded from Excel\n', ...
                branch_name, ...
                idx);

        catch ME

            warning( ...
                'Impossible de relire %s : %s', ...
                output_path_single, ...
                ME.message);

            try
                delete(output_path_single);
            catch
            end

            rowTable = table();
        end
    end

    % ==============================================================
    % Lire XML
    % ==============================================================

    if ~loaded_from_single_file

        meta_xml = ...
            find_key_value( ...
                xml_file);

        meta_xml.DateName = ...
            date_name;

        rowTable = ...
            struct2table( ...
                meta_xml, ...
                'AsArray', ...
                true);

        rowTable = ...
            normalize_metadata_table( ...
                rowTable);

        if save_to_excel && ...
                ~isempty(output_path_single)

            writetable( ...
                rowTable, ...
                output_path_single, ...
                'FileType', ...
                'spreadsheet');

            fprintf( ...
                '%s metadata rec %d saved -> %s\n', ...
                branch_name, ...
                idx, ...
                output_path_single);
        end
    end

    if isempty(rowTable) || ...
            height(rowTable) < 1

        return;
    end

    % ==============================================================
    % Ajouter à la branche metadata
    % ==============================================================

    metadata_branch = ...
        add_row_to_metadata_struct( ...
            metadata_branch, ...
            rowTable, ...
            idx);
end


%% ========================================================================
% INITIALISATION
% ========================================================================

function metadata = empty_metadata_container()

    metadata = struct();

    metadata.gcamp_plane = ...
        empty_metadata_struct();

    metadata.electroporated_plane = ...
        empty_metadata_struct();
end


function metadata = empty_metadata_struct()

    fields = ...
        metadata_field_list();

    metadata = struct();

    for i = 1:numel(fields)

        metadata.(fields{i}) = {};
    end

    metadata.source_file = '';
end


%% ========================================================================
% TABLE GLOBAL
% ========================================================================

function metadata_table = ...
        append_metadata_summary( ...
            metadata_table, ...
            rowTable, ...
            current_type, ...
            current_group, ...
            branch_name)

    current_mtor = '';

    if isfield(current_group, 'line')

        current_mtor = ...
            char(string( ...
                current_group.line));
    end

    current_animal = '';

    if isfield(current_group, 'animal')

        current_animal = ...
            char(string( ...
                current_group.animal));
    end

    summary_row = ...
        table( ...
            string(current_type), ...
            string(current_mtor), ...
            string(current_animal), ...
            string(branch_name), ...
            string(get_metadata_value( ...
                rowTable, ...
                'DateName')), ...
            get_metadata_value( ...
                rowTable, ...
                'NumPlanes'), ...
            get_metadata_value( ...
                rowTable, ...
                'OpticalZoom'), ...
            get_metadata_value( ...
                rowTable, ...
                'SamplingRatePlane'), ...
            get_metadata_value( ...
                rowTable, ...
                'TimeMinutes'), ...
            'VariableNames', { ...
                'Type', ...
                'mTOR', ...
                'Animal', ...
                'Branch', ...
                'Date', ...
                'NumPlanes', ...
                'OpticalZoom', ...
                'SamplingRate_Hz', ...
                'RecordingDuration_min'});

    if isempty(metadata_table)

        metadata_table = ...
            summary_row;

    else

        metadata_table = ...
            [ ...
                metadata_table; ...
                summary_row ...
            ];
    end
end


%% ========================================================================
% FICHIER GROUPÉ
% ========================================================================

function [group_table, existed] = ...
        load_existing_group_table( ...
            group_output_path, ...
            save_to_excel)

    group_table = table();

    existed = ...
        save_to_excel && ...
        ~isempty(group_output_path) && ...
        exist(group_output_path, 'file') == 2;

    if ~existed
        return;
    end

    try

        group_table = ...
            readtable( ...
                group_output_path, ...
                'VariableNamingRule', ...
                'preserve');

        group_table = ...
            normalize_metadata_table( ...
                group_table);

    catch ME

        warning( ...
            'Impossible de relire %s : %s', ...
            group_output_path, ...
            ME.message);

        group_table = table();
        existed = false;
    end
end


function [group_table, modified] = ...
        add_metadata_row_if_new_date( ...
            group_table, ...
            rowTable)

    modified = false;

    rowTable = ...
        normalize_metadata_table( ...
            rowTable);

    if isempty(group_table)

        group_table = ...
            rowTable;

        modified = true;
        return;
    end

    group_table = ...
        normalize_metadata_table( ...
            group_table);

    current_date = ...
        get_metadata_value( ...
            rowTable, ...
            'DateName');

    if isempty_value(current_date)
        return;
    end

    date_col = ...
        group_table.DateName;

    if ~iscell(date_col)
        date_col = num2cell(date_col);
    end

    idx_same_date = ...
        strcmp( ...
            string(date_col), ...
            string(current_date));

    if any(idx_same_date)
        return;
    end

    group_table = ...
        [ ...
            group_table; ...
            rowTable ...
        ];

    modified = true;
end


function save_group_metadata_table( ...
        group_table, ...
        output_path, ...
        file_existed, ...
        modified)

    if isempty(output_path) || ...
            isempty(group_table)

        return;
    end

    output_folder = ...
        fileparts( ...
            output_path);

    if ~exist(output_folder, 'dir')
        mkdir(output_folder);
    end

    if ~file_existed || modified

        group_table = ...
            normalize_metadata_table( ...
                group_table);

        writetable( ...
            group_table, ...
            output_path, ...
            'FileType', ...
            'spreadsheet');

        fprintf( ...
            'Grouped metadata saved -> %s\n', ...
            output_path);
    end
end


%% ========================================================================
% METADATA FIELDS
% ========================================================================

function fields = metadata_field_list()

    fields = { ...
        'DateName', ...
        'RecordingTime', ...
        'ActiveMode', ...
        'BitDepth', ...
        'SamplingRate', ...
        'FramePeriod', ...
        'SamplingRatePlane', ...
        'InterplaneDelay_s', ...
        'PixelsPerLine', ...
        'LinesPerFrame', ...
        'ImageSize', ...
        'DwellTime_us', ...
        'ScanLinePeriod_s', ...
        'SamplesPerPixel', ...
        'OpticalZoom', ...
        'ObjectiveLens', ...
        'ObjectiveLensMag', ...
        'ObjectiveLensNA', ...
        'PixelSizeX_um', ...
        'PixelSizeY_um', ...
        'PixelSize_um', ...
        'PositionX_um', ...
        'PositionY_um', ...
        'PositionZ', ...
        'NumPlanes', ...
        'ZStep_um', ...
        'ZMin_um', ...
        'ZMax_um', ...
        'LaserWavelength_nm', ...
        'LaserPower_Pockels', ...
        'LaserPowerByPlane_Pockels', ...
        'PMTGain_Red', ...
        'PMTGain_Green', ...
        'PMTGain_Blue', ...
        'TimeMinutes', ...
        'NumFrames', ...
        'ChannelNames', ...
        'NumChannels', ...
        'BidirectionalZ'};
end


%% ========================================================================
% NORMALISATION TABLE
% ========================================================================

function T = normalize_metadata_table(T)

    expected_fields = ...
        metadata_field_list();

    T = ...
        remove_unused_metadata_columns( ...
            T);

    if isempty(T)

        T = ...
            cell2table( ...
                cell( ...
                    0, ...
                    numel(expected_fields)), ...
                'VariableNames', ...
                expected_fields);

        return;
    end

    nRows = ...
        height(T);

    for i = 1:numel(expected_fields)

        field = ...
            expected_fields{i};

        if ~any(strcmp( ...
                T.Properties.VariableNames, ...
                field))

            T.(field) = ...
                cell(nRows,1);
        end
    end

    current_fields = ...
        T.Properties.VariableNames;

    for i = 1:numel(current_fields)

        field = ...
            current_fields{i};

        if ~any(strcmp( ...
                expected_fields, ...
                field))

            T(:,field) = [];
        end
    end

    T = ...
        T(:,expected_fields);

    for i = 1:numel(expected_fields)

        field = ...
            expected_fields{i};

        if ~iscell(T.(field))

            T.(field) = ...
                num2cell( ...
                    T.(field));
        end
    end
end


%% ========================================================================
% ADD ROW
% ========================================================================

function metadata = ...
        add_row_to_metadata_struct( ...
            metadata, ...
            T, ...
            idx)

    wanted_fields = ...
        metadata_field_list();

    T = ...
        normalize_metadata_table( ...
            T);

    for i = 1:numel(wanted_fields)

        field = ...
            wanted_fields{i};

        if ~isfield(metadata, field)
            metadata.(field) = {};
        end

        if isempty(T) || ...
                height(T) < 1

            metadata.(field){idx,1} = [];

        else

            metadata.(field){idx,1} = ...
                T.(field){1};
        end
    end
end


%% ========================================================================
% REMOVE UNUSED
% ========================================================================

function T = remove_unused_metadata_columns(T)

    remove_fields = { ...
        'RastersPerFrame', ...
        'LaserPower_1040', ...
        'LaserPowerByPlane_1040', ...
        'PMTGainByPlane_Red', ...
        'PMTGainByPlane_Green', ...
        'PMTGainByPlane_Blue'};

    for i = 1:numel(remove_fields)

        field = ...
            remove_fields{i};

        if any(strcmp( ...
                T.Properties.VariableNames, ...
                field))

            T(:,field) = [];
        end
    end
end


%% ========================================================================
% DÉTECTION CANAL ÉLECTROPORÉ SANS SUITE2P
% ========================================================================

function electroporated_column_by_group = ...
        find_electroporated_column_from_tseries( ...
            TSeries_group, ...
            nRecordings)

    electroporated_column_by_group = ...
        nan(nRecordings,1);

    TSeries_group = ...
        resize_4col( ...
            TSeries_group, ...
            nRecordings);

    for idx = 1:nRecordings

        % ======================================================
        % Colonne 2 prioritaire, puis colonne 3.
        %
        % Aucune vérification Suite2p ici :
        % create_metadata doit fonctionner avant Suite2p.
        % ======================================================

        for col = [2 3]

            current_path = ...
                get_matrix_path( ...
                    TSeries_group, ...
                    idx, ...
                    col);

            if isempty(current_path)
                continue;
            end

            electroporated_column_by_group(idx) = col;
            break;
        end
    end
end


%% ========================================================================
% HELPERS
% ========================================================================

function tf = isempty_value(x)

    if isempty(x)

        tf = true;

    elseif isstring(x)

        tf = ...
            all(strlength(x) == 0);

    elseif ischar(x)

        tf = ...
            isempty(strtrim(x));

    elseif iscell(x)

        tf = ...
            isempty(x) || ...
            isempty_value(x{1});

    elseif ismissing(x)

        tf = true;

    else

        tf = false;
    end
end


function path_char = force_char_path(path_in)

    path_char = ...
        path_in;

    if isempty(path_char)

        path_char = '';
        return;
    end

    if istable(path_char)
        path_char = path_char{1,1};
    end

    if iscell(path_char)

        if isempty(path_char)
            path_char = '';
            return;
        end

        path_char = path_char{1};
    end

    if isstring(path_char)
        path_char = char(path_char);
    end

    if iscategorical(path_char)
        path_char = char(path_char);
    end

    if ~ischar(path_char)

        error( ...
            'Chemin invalide : type %s', ...
            class(path_char));
    end
end


function value = get_metadata_value(T, field)

    value = [];

    if isempty(T) || ...
            height(T) < 1

        return;
    end

    if ~any(strcmp( ...
            T.Properties.VariableNames, ...
            field))

        return;
    end

    current_value = ...
        T.(field);

    if iscell(current_value)

        if ~isempty(current_value)

            value = ...
                current_value{1};
        end

    else

        value = ...
            current_value(1);
    end
end


function C4 = force_4col(C)

    if isempty(C)

        C4 = ...
            cell(0,4);

        return;
    end

    if ~iscell(C)

        if isstring(C)

            C = ...
                cellstr(C);

        elseif ischar(C)

            C = ...
                {C};

        else

            C = ...
                num2cell(C);
        end
    end

    nRows = ...
        size(C,1);

    nCols = ...
        size(C,2);

    C4 = ...
        cell(nRows,4);

    C4(:,1:min(4,nCols)) = ...
        C(:,1:min(4,nCols));
end


function C = resize_4col(C, nRows)

    C = ...
        force_4col(C);

    out = ...
        cell(nRows,4);

    nCopy = ...
        min( ...
            size(C,1), ...
            nRows);

    if nCopy > 0

        out(1:nCopy,:) = ...
            C(1:nCopy,:);
    end

    C = out;
end


function path = get_matrix_path(C, row, col)

    path = '';

    if isempty(C) || ...
            row > size(C,1) || ...
            col > size(C,2)

        return;
    end

    value = ...
        C{row,col};

    while iscell(value)

        if isempty(value)
            value = '';
            break;
        end

        value = value{1};
    end

    if isempty(value)
        return;
    end

    path = ...
        force_char_path( ...
            value);
end


function n = numel_safe_field(S, field)

    n = 0;

    if isfield(S, field) && ...
            ~isempty(S.(field))

        n = ...
            numel(S.(field));
    end
end


function txt = display_path(path)

    if isempty(path)

        txt = '<none>';

    else

        txt = path;
    end
end