function create_ppt_from_figs(selected_groups, DF_groups, gcamp_output_folders_groups, daytime)

    % Importer la bibliothèque pour PowerPoint
    import mlreportgen.ppt.*;
    
    % Définir le chemin de sauvegarde du fichier PowerPoint
    pptFileName = fullfile('D:\Imaging\Outputs\Presentations', sprintf('AnalysisFigures_%s.pptx', daytime));
    
    % Créer et ouvrir une présentation PowerPoint
    ppt = Presentation(pptFileName);
    open(ppt);
    
    % Ajouter une diapositive de titre initiale
    slide = add(ppt, 'Title Slide');
    replace(slide, 'Title', 'Analysis Results');
    replace(slide, 'Subtitle', 'Generated by MATLAB');
    
    % Parcourir les chemins des groupes et ajouter les figures
    for k = 1:length(selected_groups)
        
        % Add a slide with the name of the animal
        slide = add(ppt, 'Title Slide');
        current_animal_group = selected_groups(k).animal_group;
        figure_name = current_animal_group;      
        replace(slide, 'Title', figure_name);              
        
        % Add a Slide with a Table
        tableSlide = add(ppt,'Title and Table');
        replace(tableSlide,'Title','Parameters');
               
        current_ani_path_group = selected_groups(k).path;
        current_ages_group = selected_groups(k).ages;
        current_env_group = selected_groups(k).env;
 
        gcamp_output_folders = gcamp_output_folders_groups{k};
        DF = DF_groups{k};
        [all_recording_time, all_optical_zoom, all_depth, all_duration_minutes] = find_recording_infos(gcamp_output_folders,current_env_group);

        % Nouvelle table
        paramTable = Table();
        colSpecs(1) = ColSpec('2in'); % Age
        colSpecs(2) = ColSpec('2in'); % Recording time
        colSpecs(3) = ColSpec('2in'); % Depth
        colSpecs(4) = ColSpec('2in'); % Optical zoom
        colSpecs(5) = ColSpec('2in');
        paramTable.ColSpecs = colSpecs;
        
        % Créer la ligne d'en-tête
        headerRow = TableRow();
        headerRow.Style = {Bold(true)};
        append(headerRow, TableEntry(Paragraph('Animal Age')));
        append(headerRow, TableEntry(Paragraph('Recording time')));
        append(headerRow, TableEntry(Paragraph('Depth')));
        append(headerRow, TableEntry(Paragraph('Optical zoom')));
        append(headerRow, TableEntry(Paragraph('Number of cells')));
        append(paramTable, headerRow);
        
        % Boucle sur chaque path pour remplir les lignes
        for path_idx = 1:length(gcamp_output_folders)
            ani_age = current_ages_group{path_idx};
            ani_DF = DF{path_idx};
            num_cells = size(ani_DF, 1);
            recording_time = all_recording_time{path_idx};
            depth = all_depth{path_idx};
            optical_zoom = all_optical_zoom{path_idx};
        
            % Créer une nouvelle ligne pour chaque enregistrement
            row = TableRow();
            append(row, TableEntry(Paragraph(string(ani_age))));
            append(row, TableEntry(Paragraph(string(recording_time))));
            append(row, TableEntry(Paragraph(string(depth))));
            append(row, TableEntry(Paragraph(string(optical_zoom))));
            append(row, TableEntry(Paragraph(string(num_cells))));
            
            append(paramTable, row);
        end
        
        % Remplacer la table sur la slide
        replace(tableSlide, 'Table', paramTable);



        % Recherche des fichiers PNG dans le dossier actuel
        png_files = dir(fullfile(current_ani_path_group, '*.png'));
        
        for file_idx = 1:length(png_files)
            figure_path = fullfile(png_files(file_idx).folder, png_files(file_idx).name);
            
            % Ajouter une diapositive pour chaque figure
            slide = add(ppt, 'Title and Picture');
            
            % Ajouter un titre à la diapositive (le nom du fichier image sans extension)
            [~, figure_name, ~] = fileparts(png_files(file_idx).name);
            
            % Enlever les underscores et remplacer par des espaces
            figure_name = strrep(figure_name, '_', ' ');
            
            % Remplacer le titre de la diapositive par le nom de la figure
            replace(slide, 'Title', figure_name);
            
            % Ajouter l'image sur la diapositive
            img = Picture(figure_path);
            replace(slide, 'Picture', img); % Remplace le contenu par l'image
        end

        for path_idx = 1:length(gcamp_output_folders)
            figure_folder = gcamp_output_folders{path_idx};
            
            % Recherche des fichiers PNG dans le dossier actuel
            png_files = dir(fullfile(figure_folder, '*.png'));
            
            for file_idx = 1:length(png_files)
                figure_path = fullfile(png_files(file_idx).folder, png_files(file_idx).name);
                
                % Ajouter une diapositive pour chaque figure
                slide = add(ppt, 'Title and Picture');
                
                % Ajouter un titre à la diapositive (le nom du fichier image sans extension)
                [~, figure_name, ~] = fileparts(png_files(file_idx).name);
                
                % Enlever les underscores et remplacer par des espaces
                figure_name = strrep(figure_name, '_', ' ');
                
                % Remplacer le titre de la diapositive par le nom de la figure
                replace(slide, 'Title', figure_name);
                
                % Ajouter l'image sur la diapositive
                img = Picture(figure_path);
                replace(slide, 'Picture', img); % Remplace le contenu par l'image
            end
        end
    end
    
    % Sauvegarder et fermer la présentation
    close(ppt);
    fprintf('PowerPoint presentation saved as %s\n', pptFileName);

end
