function group = finalize_single_animal_processing( ...
        group, ...
        include_electroporated, ...
        current_automatic_selection, ...
        skip_planes_by_recording)

    if nargin < 4 || isempty(skip_planes_by_recording)
        skip_planes_by_recording = {};
    end

    current_animal = ...
        group.animal;

    current_line = ...
        group.line;

    current_dates = ...
        group.dates;

    current_ages = ...
        group.ages;

    paths = ...
        group.paths;

    data = ...
        group.data;

    metadata = ...
        group.metadata;

    %% ============================================================
    % Combined population
    % =============================================================

    combined_plane = ...
        combined_gcamp_electroporated_cells( ...
            paths.gcamp_output, ...
            data, ...
            include_electroporated, ...
            skip_planes_by_recording);

    data.combined_plane = ...
        combined_plane;

    %% ============================================================
    % Mean image overview
    % =============================================================

    meanImgs_electroporated = {};
    alignedImgs_electroporated = {};

    if isfield(data, 'electroporated_plane') && ...
            isstruct(data.electroporated_plane)

        if isfield( ...
                data.electroporated_plane, ...
                'meanImgs_electroporated')

            meanImgs_electroporated = ...
                data.electroporated_plane.meanImgs_electroporated;
        end

        if isfield( ...
                data.electroporated_plane, ...
                'alignedImgs_electroporated')

            alignedImgs_electroporated = ...
                data.electroporated_plane.alignedImgs_electroporated;
        end
    end

    save_mean_image_overviews( ...
        current_line, ...
        current_animal, ...
        current_dates, ...
        current_ages, ...
        current_automatic_selection, ...
        paths.suite2p, ...
        paths.gcamp_root, ...
        paths.output_folders, ...
        data.gcamp_plane.meanImgs_gcamp, ...
        meanImgs_electroporated, ...
        alignedImgs_electroporated, ...
        metadata.gcamp_plane, ...
        metadata.electroporated_plane);

    group.data = ...
        data;
end
