function [suite2p_folders, TSeriesPaths, ZSeriesPaths, xml_paths_all, ...
    true_xml_paths, lastFolderNames, Fallmat_paths] = ...
    find_suite2p_folders(selectedFolders)

    labels = {'Gcamp', 'Red', 'Blue', 'Green'};

    suite2p_folders = cell(0,4);
    TSeriesPaths    = cell(0,4);
    ZSeriesPaths    = cell(0,1);
    Fallmat_paths   = cell(0,4);

    true_xml_paths  = cell(0,4);
    lastFolderNames = cell(0,4);
    xml_paths_all   = cell(0,5);

    output_idx = 0;

    for idx = 1:numel(selectedFolders)

        selectedFolder = ...
            selectedFolders{idx};

        if ~isfolder(selectedFolder)

            warning( ...
                'Folder does not exist: %s', ...
                selectedFolder);

            continue;
        end

        % ==========================================================
        % Chercher les TSeries
        % ==========================================================

        TSeriesFoldersList = ...
            dir( ...
                fullfile( ...
                    selectedFolder, ...
                    'TSeries*'));

        TSeriesFoldersList = ...
            TSeriesFoldersList( ...
                [TSeriesFoldersList.isdir]);

        if isempty(TSeriesFoldersList)

            fprintf( ...
                'No TSeries folders found in: %s\n', ...
                selectedFolder);

            continue;
        end

        % ==========================================================
        % Chercher les ZSeries
        % ==========================================================

        ZSeriesFoldersList = ...
            dir( ...
                fullfile( ...
                    selectedFolder, ...
                    'ZSeries*'));

        ZSeriesFoldersList = ...
            ZSeriesFoldersList( ...
                [ZSeriesFoldersList.isdir]);

        % ==========================================================
        % Identifier tous les TSeries GCaMP
        % ==========================================================

        gcamp_paths = {};

        all_paths = ...
            cell( ...
                numel(TSeriesFoldersList), ...
                1);

        for i = 1:numel(TSeriesFoldersList)

            folderName = ...
                TSeriesFoldersList(i).name;

            fullPath = ...
                fullfile( ...
                    selectedFolder, ...
                    folderName);

            all_paths{i} = ...
                fullPath;

            if contains( ...
                    lower(folderName), ...
                    'gcamp')

                gcamp_paths{end+1,1} = ...
                    fullPath;
            end
        end

        if isempty(gcamp_paths)

            warning( ...
                'No GCaMP TSeries found in: %s', ...
                selectedFolder);

            continue;
        end

        % ==========================================================
        % Sélection manuelle si plusieurs TSeries GCaMP existent
        % ==========================================================

        if numel(gcamp_paths) > 1

            fprintf('\n');

            fprintf( ...
                'Plusieurs TSeries GCaMP trouvés dans :\n%s\n', ...
                selectedFolder);

            for ii = 1:numel(gcamp_paths)

                fprintf( ...
                    '    %d) %s\n', ...
                    ii, ...
                    gcamp_paths{ii});
            end

            selected_gcamp_path = ...
                select_one_gcamp_tseries( ...
                    selectedFolder, ...
                    gcamp_paths);

            if isempty(selected_gcamp_path)

                fprintf( ...
                    [ ...
                    'Aucun TSeries GCaMP sélectionné pour :\n' ...
                    '%s\n'], ...
                    selectedFolder);

                continue;
            end

            gcamp_paths = ...
                {selected_gcamp_path};
        end

        % ==========================================================
        % UNE LIGNE PAR TSERIES GCAMP
        % ==========================================================

        for g = 1:numel(gcamp_paths)

            output_idx = ...
                output_idx + 1;

            gcamp_path = ...
                gcamp_paths{g};

            TSeriesPaths{output_idx,1} = ...
                gcamp_path;

            % ======================================================
            % Numéro final du GCaMP
            %
            % Exemple :
            %
            % TSeries-06112026-1010-gcamp-001
            %
            % -> 001
            % ======================================================

            [~, gcamp_name] = ...
                fileparts( ...
                    gcamp_path);

            gcamp_num = ...
                regexp( ...
                    gcamp_name, ...
                    '-(\d+)$', ...
                    'tokens', ...
                    'once');

            if ~isempty(gcamp_num)

                gcamp_num = ...
                    gcamp_num{1};

            else

                gcamp_num = '';
            end

            % ======================================================
            % Matcher le ZSeries
            %
            % Même logique que les canaux électroporés :
            % association par numéro final.
            %
            % Exemple :
            %
            % TSeries-...-gcamp-001
            %              ↕
            % ZSeries-...-001
            %
            % Une seule colonne :
            %
            % ZSeriesPaths{output_idx,1}
            % ======================================================

            matched_zseries_path = '';

            if ~isempty(gcamp_num)

                for z = 1:numel(ZSeriesFoldersList)

                    zseries_name = ...
                        ZSeriesFoldersList(z).name;

                    zseries_num = ...
                        regexp( ...
                            zseries_name, ...
                            '-(\d+)$', ...
                            'tokens', ...
                            'once');

                    if isempty(zseries_num)
                        continue;
                    end

                    if strcmp( ...
                            zseries_num{1}, ...
                            gcamp_num)

                        matched_zseries_path = ...
                            fullfile( ...
                                selectedFolder, ...
                                zseries_name);

                        fprintf( ...
                            'ZSeries matched: %s\n', ...
                            zseries_name);

                        break;
                    end
                end
            end

            ZSeriesPaths{output_idx,1} = ...
                matched_zseries_path;

            if isempty(matched_zseries_path)

                fprintf( ...
                    'No ZSeries matched for GCaMP %s\n', ...
                    gcamp_name);
            end

            % ======================================================
            % Matcher les autres canaux
            %
            % Colonnes :
            %   1 = GCaMP
            %   2 = Red
            %   3 = Blue
            %   4 = Green
            % ======================================================

            for k = 2:numel(labels)

                matched_path = '';

                for i = 1:numel(all_paths)

                    this_path = ...
                        all_paths{i};

                    [~, this_name] = ...
                        fileparts( ...
                            this_path);

                    this_name_lower = ...
                        lower( ...
                            this_name);

                    % ==============================================
                    % Vérifier le label
                    % ==============================================

                    switch lower(labels{k})

                        case 'red'

                            label_match = ...
                                contains( ...
                                    this_name_lower, ...
                                    'red');

                        case 'blue'

                            label_match = ...
                                ~isempty( ...
                                    regexp( ...
                                        this_name_lower, ...
                                        'blue-\d+$', ...
                                        'once')) && ...
                                ~contains( ...
                                    this_name_lower, ...
                                    'blue-transfert') && ...
                                ~contains( ...
                                    this_name_lower, ...
                                    'blue_transfert');

                        case 'green'

                            label_match = ...
                                contains( ...
                                    this_name_lower, ...
                                    'green');

                        otherwise

                            label_match = ...
                                false;
                    end

                    if ~label_match
                        continue;
                    end

                    % ==============================================
                    % Numéro final du TSeries
                    % ==============================================

                    this_num = ...
                        regexp( ...
                            this_name, ...
                            '-(\d+)$', ...
                            'tokens', ...
                            'once');

                    if isempty(this_num)
                        continue;
                    end

                    % ==============================================
                    % Même numéro que GCaMP
                    % ==============================================

                    if strcmp( ...
                            this_num{1}, ...
                            gcamp_num)

                        matched_path = ...
                            this_path;

                        fprintf( ...
                            '%s matched: %s\n', ...
                            labels{k}, ...
                            this_name);

                        break;
                    end
                end

                TSeriesPaths{output_idx,k} = ...
                    matched_path;
            end

            % ======================================================
            % Blue / Green sous-dossiers
            % ======================================================

            blue_path = ...
                TSeriesPaths{output_idx,3};

            if ~isempty(blue_path)

                blueFolder = ...
                    fullfile( ...
                        blue_path, ...
                        'Blue');

                greenFolder = ...
                    fullfile( ...
                        blue_path, ...
                        'Green');

                % ==================================================
                % BLUE
                % ==================================================

                if ~exist( ...
                        blueFolder, ...
                        'dir')

                    tiffFiles = ...
                        dir( ...
                            fullfile( ...
                                blue_path, ...
                                '*Ch3*.tif'));

                    if ~isempty(tiffFiles)

                        mkdir( ...
                            blueFolder);

                        for j = 1:numel(tiffFiles)

                            movefile( ...
                                fullfile( ...
                                    blue_path, ...
                                    tiffFiles(j).name), ...
                                fullfile( ...
                                    blueFolder, ...
                                    tiffFiles(j).name));
                        end
                    end
                end

                if exist( ...
                        blueFolder, ...
                        'dir')

                    blueFiles = ...
                        dir( ...
                            fullfile( ...
                                blueFolder, ...
                                '*.tif'));

                else

                    blueFiles = [];
                end

                if exist( ...
                        blueFolder, ...
                        'dir') && ...
                        ~isempty(blueFiles)

                    TSeriesPaths{output_idx,3} = ...
                        blueFolder;

                else

                    TSeriesPaths{output_idx,3} = '';
                end

                % ==================================================
                % GREEN
                % ==================================================

                if ~exist( ...
                        greenFolder, ...
                        'dir')

                    tiffFiles = ...
                        dir( ...
                            fullfile( ...
                                blue_path, ...
                                '*Ch2*.tif'));

                    if ~isempty(tiffFiles)

                        mkdir( ...
                            greenFolder);

                        for j = 1:numel(tiffFiles)

                            movefile( ...
                                fullfile( ...
                                    blue_path, ...
                                    tiffFiles(j).name), ...
                                fullfile( ...
                                    greenFolder, ...
                                    tiffFiles(j).name));
                        end
                    end
                end

                if exist( ...
                        greenFolder, ...
                        'dir')

                    greenFiles = ...
                        dir( ...
                            fullfile( ...
                                greenFolder, ...
                                '*.tif'));

                else

                    greenFiles = [];
                end

                if exist( ...
                        greenFolder, ...
                        'dir') && ...
                        ~isempty(greenFiles)

                    TSeriesPaths{output_idx,4} = ...
                        greenFolder;

                else

                    TSeriesPaths{output_idx,4} = '';
                end
            end

            % ======================================================
            % Initialiser les 4 colonnes de la ligne
            % ======================================================

            for j = 1:4

                if size(TSeriesPaths,2) < j || ...
                        isempty(TSeriesPaths{output_idx,j})

                    TSeriesPaths{output_idx,j} = '';

                    lastFolderNames{output_idx,j} = '';
                    xml_paths_all{output_idx,j} = {};
                    true_xml_paths{output_idx,j} = '';

                    suite2p_folders{output_idx,j} = {};
                    Fallmat_paths{output_idx,j} = {};
                end
            end

            % ======================================================
            % Noms TSeries
            % ======================================================

            for j = 1:4

                currentPath = ...
                    TSeriesPaths{output_idx,j};

                if isempty(currentPath)

                    lastFolderNames{output_idx,j} = '';

                    continue;
                end

                [~, lastFolderName] = ...
                    fileparts( ...
                        currentPath);

                lastFolderNames{output_idx,j} = ...
                    lastFolderName;
            end

            % ======================================================
            % XML PAR CANAL
            % ======================================================

            for j = 1:4

                currentPath = ...
                    TSeriesPaths{output_idx,j};

                if isempty(currentPath)

                    xml_paths_all{output_idx,j} = {};
                    true_xml_paths{output_idx,j} = '';

                    continue;
                end

                [ ...
                    xml_list_tmp, ...
                    xml_path ...
                ] = ...
                    processEnvFile( ...
                        currentPath);

                xml_paths_all{output_idx,j} = ...
                    xml_list_tmp;

                true_xml_paths{output_idx,j} = ...
                    xml_path;
            end
            
            % ======================================================
            % XML ZSERIES
            %
            % Colonne :
            %   5 = ZSeries
            % ======================================================
            
            currentZSeriesPath = ...
                ZSeriesPaths{output_idx,1};
            
            if isempty(currentZSeriesPath)
            
                xml_paths_all{output_idx,5} = {};
                true_xml_paths{output_idx,5} = '';
            
            else
            
                [ ...
                    xml_list_tmp, ...
                    xml_path ...
                ] = ...
                    processEnvFile( ...
                        currentZSeriesPath);
            
                xml_paths_all{output_idx,5} = ...
                    xml_list_tmp;
            
                true_xml_paths{output_idx,5} = ...
                    xml_path;
            
                if ~isempty(xml_path)
            
                    fprintf( ...
                        'ZSeries XML found: %s\n', ...
                        xml_path);
                end
            end

            % ======================================================
            % Suite2p / Fall.mat
            % ======================================================

            for j = 1:4

                currentPath = ...
                    TSeriesPaths{output_idx,j};

                if isempty(currentPath)

                    suite2p_folders{output_idx,j} = {};
                    Fallmat_paths{output_idx,j} = {};

                    continue;
                end

                planeFolders = ...
                    process_TSeries( ...
                        currentPath);

                if isempty(planeFolders)

                    fprintf( ...
                        [ ...
                        'TSeries conservé sans suite2p | ' ...
                        '%s | %s\n'], ...
                        labels{j}, ...
                        currentPath);

                    suite2p_folders{output_idx,j} = {};
                    Fallmat_paths{output_idx,j} = {};

                    continue;
                end

                currentFallPaths = {};
                currentSuite2pPaths = {};

                for p = 1:numel(planeFolders)

                    planePath = ...
                        planeFolders{p};

                    fall_mat_path = ...
                        fullfile( ...
                            planePath, ...
                            'Fall.mat');

                    ops_npy_path = ...
                        fullfile( ...
                            planePath, ...
                            'ops.npy');

                    if exist( ...
                            fall_mat_path, ...
                            'file') == 2

                        currentFallPaths{end+1} = ...
                            fall_mat_path; %#ok<AGROW>
                    end

                    if exist( ...
                            ops_npy_path, ...
                            'file') == 2

                        currentSuite2pPaths{end+1} = ...
                            planePath; %#ok<AGROW>
                    end
                end

                Fallmat_paths{output_idx,j} = ...
                    currentFallPaths(:).';

                suite2p_folders{output_idx,j} = ...
                    currentSuite2pPaths(:).';
            end

            fprintf( ...
                'Recording added: %s\n', ...
                gcamp_path);
        end
    end
end


% ========================================================================
% PROCESS XML
% ========================================================================

function [xml_paths_all, xml_path] = ...
        processEnvFile(TSeriesPath)

    xml_paths_all = {};
    xml_path = '';

    if isempty(TSeriesPath) || ...
            ~(ischar(TSeriesPath) || ...
              isstring(TSeriesPath))

        return;
    end

    TSeriesPath = ...
        char(TSeriesPath);

    [parent_folder, current_name] = ...
        fileparts(TSeriesPath);

    if strcmpi(current_name, 'Blue') || ...
            strcmpi(current_name, 'Green')

        tseries_root = ...
            parent_folder;

        preferred_channel_folder = ...
            TSeriesPath;

    else

        tseries_root = ...
            TSeriesPath;

        preferred_channel_folder = ...
            '';
    end

    search_folders = {};

    search_folders{end+1} = ...
        fullfile(TSeriesPath, 'raw_data');

    search_folders{end+1} = ...
        TSeriesPath;

    if ~isempty(preferred_channel_folder)

        search_folders{end+1} = ...
            fullfile(tseries_root, 'raw_data');

        search_folders{end+1} = ...
            tseries_root;

    else

        search_folders{end+1} = ...
            fullfile(tseries_root, 'Blue', 'raw_data');

        search_folders{end+1} = ...
            fullfile(tseries_root, 'Blue');

        search_folders{end+1} = ...
            fullfile(tseries_root, 'Green', 'raw_data');

        search_folders{end+1} = ...
            fullfile(tseries_root, 'Green');
    end

    search_folders = ...
        unique( ...
            search_folders, ...
            'stable');

    for i = 1:numel(search_folders)

        current_folder = ...
            search_folders{i};

        if ~isfolder(current_folder)
            continue;
        end

        xml_files = ...
            dir( ...
                fullfile( ...
                    current_folder, ...
                    '*.xml'));

        if isempty(xml_files)
            continue;
        end

        xml_paths_all = ...
            cell( ...
                numel(xml_files), ...
                1);

        for j = 1:numel(xml_files)

            xml_paths_all{j} = ...
                fullfile( ...
                    current_folder, ...
                    xml_files(j).name);
        end

        xml_path = ...
            xml_paths_all{1};

        fprintf( ...
            'XML found: %s\n', ...
            xml_path);

        return;
    end

    fprintf( ...
        'No XML found for TSeries:\n%s\n', ...
        TSeriesPath);

    fprintf( ...
        'Searched folders:\n');

    for i = 1:numel(search_folders)

        fprintf( ...
            '    %s\n', ...
            search_folders{i});
    end

    xml_paths_all = ...
        {''};

    xml_path = '';
end


% ========================================================================
% PROCESS TSERIES
% ========================================================================

function dataFolders = ...
        process_TSeries(TSeriesPath)

    suite2pOldFolder = ...
        fullfile( ...
            TSeriesPath, ...
            'suite2p');

    suite2pNewFolder = ...
        fullfile( ...
            TSeriesPath, ...
            'suite2p_new');

    if isfolder(suite2pNewFolder)

        suite2pFolder = ...
            suite2pNewFolder;

    else

        suite2pFolder = ...
            suite2pOldFolder;
    end

    if ~isfolder(suite2pFolder)

        dataFolders = {};

        return;
    end

    planeFolders = ...
        dir( ...
            fullfile( ...
                suite2pFolder, ...
                'plane*'));

    planeFolders = ...
        planeFolders( ...
            [planeFolders.isdir]);

    if isempty(planeFolders)

        fprintf( ...
            'No plane folder found in %s.\n', ...
            suite2pFolder);

        dataFolders = {};

        return;
    end

    dataFolders = ...
        cell( ...
            1, ...
            numel(planeFolders));

    for k = 1:numel(planeFolders)

        dataFolders{k} = ...
            fullfile( ...
                suite2pFolder, ...
                planeFolders(k).name);
    end
end


% ========================================================================
% SELECT GCAMP TSERIES
% ========================================================================

function selected_path = ...
        select_one_gcamp_tseries( ...
            parent_folder, ...
            available_gcamp_paths)

    selected_path = '';

    if isempty(available_gcamp_paths)
        return;
    end

    if numel(available_gcamp_paths) == 1

        selected_path = ...
            available_gcamp_paths{1};

        return;
    end

    while true

        chosen_folder = ...
            uigetdir( ...
                parent_folder, ...
                sprintf( ...
                    [ ...
                    'Plusieurs TSeries GCaMP trouvés - ' ...
                    'sélectionnez le TSeries à utiliser']));

        if isequal( ...
                chosen_folder, ...
                0)

            choice = ...
                questdlg( ...
                    [ ...
                    'Aucun dossier sélectionné. ' ...
                    'Voulez-vous ignorer cette date ?'], ...
                    'Sélection TSeries', ...
                    'Ignorer la date', ...
                    'Réessayer', ...
                    'Ignorer la date');

            if strcmp( ...
                    choice, ...
                    'Réessayer')

                continue;
            end

            selected_path = '';

            return;
        end

        chosen_folder_normalized = ...
            normalize_folder_path( ...
                chosen_folder);

        available_normalized = ...
            cellfun( ...
                @normalize_folder_path, ...
                available_gcamp_paths, ...
                'UniformOutput', ...
                false);

        matched_idx = ...
            find( ...
                strcmpi( ...
                    available_normalized, ...
                    chosen_folder_normalized), ...
                1);

        if ~isempty(matched_idx)

            selected_path = ...
                available_gcamp_paths{matched_idx};

            fprintf( ...
                'TSeries GCaMP sélectionné :\n%s\n', ...
                selected_path);

            return;
        end

        uiwait( ...
            warndlg( ...
                sprintf( ...
                    [ ...
                    'Le dossier sélectionné ne correspond pas à un ' ...
                    'TSeries GCaMP valide trouvé dans cette date.\n\n' ...
                    'Dossier sélectionné :\n%s'], ...
                    chosen_folder), ...
                'TSeries invalide', ...
                'modal'));
    end
end


% ========================================================================
% NORMALIZE PATH
% ========================================================================

function path_out = ...
        normalize_folder_path(path_in)

    if isempty(path_in)

        path_out = '';

        return;
    end

    path_out = ...
        char( ...
            string( ...
                path_in));

    path_out = ...
        strrep( ...
            path_out, ...
            '/', ...
            '\');

    while numel(path_out) > 3 && ...
            path_out(end) == '\'

        path_out(end) = [];
    end
end