function [selected_groups, selected_groups_reloaded] = ...
    load_last_selected_groups( ...
        root_folders, ...
        choices, ...
        group_order, ...
        selection_mode, ...
        age_group, ...
        include_electroporated)

    %==============================================================%
    % Initialisation
    %==============================================================%

    selected_groups = ...
        struct();


    selected_groups_reloaded = ...
        false;


    if isempty(choices) || ...
            isempty(root_folders) || ...
            ~isstruct(selection_mode) || ...
            ~isstruct(age_group)

        return;
    end


    %==============================================================%
    % Vérifier s'il existe au moins une présélection
    %
    % Si tous les types sont en mode manuel :
    % retour immédiat.
    %==============================================================%

    mode_names = ...
        fieldnames(selection_mode);


    is_preselected = ...
        false;


    for i = 1:numel(mode_names)

        if strcmpi( ...
                selection_mode.(mode_names{i}), ...
                'preselected')

            is_preselected = ...
                true;

            break;
        end
    end


    if ~is_preselected
        return;
    end


    %==============================================================%
    % Electroporated / non-electroporated
    %==============================================================%

    if include_electroporated

        electroporated_name = ...
            'electroporated';

    else

        electroporated_name = ...
            'non-electroporated';
    end


    %==============================================================%
    % Boucle sur les groupes sélectionnés
    %==============================================================%

    for i = 1:numel(choices)

        choice = ...
            choices(i);


        if choice > numel(group_order)
            continue;
        end


        current_type = ...
            group_order{choice};


        %----------------------------------------------------------%
        % Uniquement pour les présélections
        %----------------------------------------------------------%

        if ~isfield( ...
                selection_mode, ...
                current_type)

            continue;
        end


        current_selection_mode = ...
            selection_mode.(current_type);


        if ~strcmpi( ...
                current_selection_mode, ...
                'preselected')

            continue;
        end


        %----------------------------------------------------------%
        % Age group
        %----------------------------------------------------------%

        if ~isfield( ...
                age_group, ...
                current_type) || ...
                isempty(age_group.(current_type))

            fprintf( ...
                ['Impossible de rechercher selected_groups pour %s : ' ...
                 'age_group absent.\n'], ...
                current_type);

            continue;
        end


        current_age_group = ...
            age_group.(current_type);


        %----------------------------------------------------------%
        % Root folder
        %----------------------------------------------------------%

        if i > numel(root_folders) || ...
                isempty(root_folders{i})

            warning( ...
                'load_last_selected_groups:MissingRootFolder', ...
                'Root folder absent pour %s.', ...
                current_type);

            continue;
        end


        current_root_folder = ...
            root_folders{i};


        %==========================================================%
        % Nom du fichier attendu
        %==============================================================%

        file_name = ...
            sprintf( ...
                'selected_groups_%s_preselected_%s.mat', ...
                char(string(current_age_group)), ...
                electroporated_name);


        selected_groups_path = ...
            fullfile( ...
                current_root_folder, ...
                file_name);


        %----------------------------------------------------------%
        % Aucun fichier existant
        %----------------------------------------------------------%

        if exist( ...
                selected_groups_path, ...
                'file') ~= 2

            fprintf( ...
                ['Aucun selected_groups précédent trouvé pour :\n' ...
                 '  %s | %s | %s\n'], ...
                current_type, ...
                char(string(current_age_group)), ...
                electroporated_name);

            continue;
        end


        %==========================================================%
        % Informations sur le fichier
        %==========================================================%

        file_info = ...
            dir( ...
                selected_groups_path);


        if isempty(file_info)

            saved_date = ...
                '';

        else

            saved_date = ...
                file_info.date;
        end


        %==========================================================%
        % Demander à l'utilisateur
        %==========================================================%

        answer = ...
            questdlg( ...
                sprintf( ...
                    [ ...
                    'Un selected_groups enregistré existe pour :\n\n' ...
                    'Type : %s\n' ...
                    'Age group : %s\n' ...
                    'Mode : preselected\n' ...
                    'Cellules : %s\n\n' ...
                    'Dernière sauvegarde : %s\n\n' ...
                    'Voulez-vous le charger ?' ...
                    ], ...
                    current_type, ...
                    char(string(current_age_group)), ...
                    electroporated_name, ...
                    saved_date), ...
                'Load selected_groups', ...
                'Yes', ...
                'No', ...
                'Yes');


        if isempty(answer) || ...
                ~strcmpi( ...
                    answer, ...
                    'Yes')

            fprintf( ...
                'Ancien selected_groups non chargé pour %s.\n', ...
                current_type);

            continue;
        end


        %==========================================================%
        % Charger le fichier
        %==========================================================%

        loaded_data = ...
            load( ...
                selected_groups_path, ...
                'selected_groups');


        if ~isfield( ...
                loaded_data, ...
                'selected_groups') || ...
                ~isstruct(loaded_data.selected_groups)

            warning( ...
                'load_last_selected_groups:InvalidFile', ...
                ['Le fichier ne contient pas de structure ', ...
                 'selected_groups valide :\n%s'], ...
                selected_groups_path);

            continue;
        end


        loaded_selected_groups = ...
            loaded_data.selected_groups;


        %----------------------------------------------------------%
        % Vérifier que le type est présent
        %----------------------------------------------------------%

        if ~isfield( ...
                loaded_selected_groups, ...
                current_type)

            warning( ...
                'load_last_selected_groups:MissingType', ...
                ['Le fichier existe mais ne contient pas ', ...
                 'selected_groups.%s.'], ...
                current_type);

            continue;
        end


        %==========================================================%
        % Récupérer le type correspondant
        %==========================================================%

        selected_groups.(current_type) = ...
            loaded_selected_groups.(current_type);


        %==========================================================%
        % Flag : au moins un selected_groups a été rechargé
        %==========================================================%

        selected_groups_reloaded = ...
            true;


        fprintf( ...
            ['Dernier selected_groups chargé :\n' ...
             '%s\n'], ...
            selected_groups_path);
    end
end