function [group, processing_cache] = ...
        process_single_animal_base( ...
            group, ...
            include_electroporated, ...
            current_automatic_selection, ...
            processing_mode)

    if nargin < 4 || isempty(processing_mode)
        processing_mode = 'interactive';
    end

    current_animal = ...
        group.animal;

    current_line = ...
        group.line;

    current_dates = ...
        group.dates;

    current_ages = ...
        group.ages;

    paths = ...
        group.paths;

    data = ...
        group.data;

    metadata = ...
        group.metadata;

    gcamp_output_folders = ...
        paths.gcamp_output;

    gcamp_root_folders = ...
        paths.gcamp_root;

    current_suite2p_group = ...
        paths.suite2p;

    current_TSeries_group = ...
        paths.TSeries;

    date_group_paths = ...
        paths.date;

    sampling_rate_group = ...
        metadata.gcamp_plane.SamplingRatePlane;

    fprintf('\n');
    fprintf('------------------------------------------------------------\n');
    fprintf('Animal processing\n');
    fprintf('Animal: %s\n', char(string(current_animal)));
    fprintf('Mode  : %s\n', processing_mode);
    fprintf('------------------------------------------------------------\n');

    %% ============================================================
    % Mean GCaMP images
    % =============================================================

    meanImgs_gcamp = ...
        save_mean_images( ...
            'GCaMP', ...
            current_animal, ...
            current_ages, ...
            current_dates, ...
            gcamp_output_folders, ...
            current_suite2p_group(:, 1));

    if ~isfield(data, 'gcamp_plane') || ...
            ~isstruct(data.gcamp_plane)

        data.gcamp_plane = ...
            struct();
    end

    data.gcamp_plane.meanImgs_gcamp = ...
        meanImgs_gcamp;

    %% ============================================================
    % Electroporated mean images
    % =============================================================

    electroporated_column = ...
        find_electroporated_suite2p_column( ...
            current_suite2p_group);

    if ~isempty(electroporated_column)

        if electroporated_column == 2
            channel_name = 'Red';
        else
            channel_name = 'Blue';
        end

        meanImgs_electroporated = ...
            save_mean_images( ...
                channel_name, ...
                current_animal, ...
                current_ages, ...
                current_dates, ...
                gcamp_output_folders, ...
                current_suite2p_group(:, electroporated_column));

    else

        meanImgs_electroporated = {};
    end

    if ~isfield(data, 'electroporated_plane') || ...
            ~isstruct(data.electroporated_plane)

        data.electroporated_plane = ...
            struct();
    end

    data.electroporated_plane.meanImgs_electroporated = ...
        meanImgs_electroporated;

    %% ============================================================
    % ZSeries
    % =============================================================

    if isfield(paths, 'ZSeries') && ...
            ~isempty(paths.ZSeries)

        zseries = ...
            load_or_process_zseries( ...
                paths.ZSeries, ...
                gcamp_root_folders, ...
                metadata.ZSeries, ...
                paths.output_folders, ...
                current_automatic_selection, ...
                processing_mode, ...
                data, ...
                current_line, ...
                current_animal, ...
                current_dates, ...
                current_ages);

        data.ZSeries = ...
            zseries;

    else

        data.ZSeries = ...
            struct();
    end

    %% ============================================================
    % Motion
    %
    % load_only now means:
    %   - load/reuse existing motion information;
    %   - never ask for Fiji/direct-computation strategy;
    %   - never calculate a missing motion-energy trace.
    % =============================================================

    avg_block = 5;

    [motion, camFolders] = ...
        load_or_process_movie( ...
            current_TSeries_group(:, 1), ...
            gcamp_output_folders, ...
            avg_block, ...
            sampling_rate_group, ...
            current_animal, ...
            data, ...
            processing_mode);

    data.motion = ...
        motion;

    paths.camera = ...
        camFolders;

    %% ============================================================
    % Stimulation
    % =============================================================

    data = ...
        load_or_process_stims( ...
            date_group_paths, ...
            current_TSeries_group(:, 1), ...
            data);

    %% ============================================================
    % GCaMP cells
    % =============================================================

    gcamp_plane = ...
        process_gcamp_cells( ...
            gcamp_output_folders, ...
            current_suite2p_group(:, 1), ...
            meanImgs_gcamp, ...
            data);

    data.gcamp_plane = ...
        gcamp_plane;

    %% ============================================================
    % Electroporated preparation
    % =============================================================

    [processing_cache, data] = ...
        process_electroporated_pass1( ...
            paths.gcamp_root, ...
            paths.gcamp_output, ...
            include_electroporated, ...
            paths.date, ...
            paths.TSeries, ...
            paths.suite2p, ...
            metadata, ...
            data, ...
            processing_mode);

    % ============================================================
    % LOAD_ONLY : PASS 2 uniquement pour les plans dont le masque final
    % est disponible et dont les ROI sont absentes/obsoletes.
    % Aucun fallback ni interface pour les autres plans.
    % ============================================================

    if strcmpi(processing_mode, 'load_only')

        [electroporated_plane, data] = ...
            process_electroporated_pass2( ...
                processing_cache, ...
                paths.gcamp_output, ...
                data.gcamp_plane.meanImgs_gcamp, ...
                data, ...
                false);

        data.electroporated_plane = ...
            electroporated_plane;
    end

    group.data = ...
        data;

    group.paths = ...
        paths;
end
