function [group, processing_cache] = ...
        process_single_animal_base( ...
            group, ...
            include_electroporated, ...
            automatic_selection, ...
            processing_mode)

    if nargin < 4 || isempty(processing_mode)
        processing_mode = 'interactive';
    end

    animal = ...
        group.animal;

    line = ...
        group.line;

    dates = ...
        group.dates;

    ages = ...
        group.ages;

    paths = ...
        group.paths;

    data = ...
        group.data;

    metadata = ...
        group.metadata;

    gcamp_output_folders = ...
        paths.gcamp_output;

    gcamp_root_folders = ...
        paths.gcamp_root;

    suite2p_folders = ...
        paths.suite2p;

    TSeries_folders = ...
        paths.TSeries;

    date_folders = ...
        paths.date;

    % ============================================================
    % Base unique des recordings
    %
    % paths.TSeries(:,1) = reference canonique GCaMP.
    % Toutes les donnees indexees par acquisition utilisent le meme m.
    % ============================================================

    gcamp_TSeries_folders = ...
        TSeries_folders(:, 1);

    gcamp_suite2p_folders = ...
        suite2p_folders(:, 1);

    numAcquisitions = ...
        size(gcamp_TSeries_folders, 1);

    fprintf('\n');
    fprintf('------------------------------------------------------------\n');
    fprintf('Animal processing\n');
    fprintf('Animal: %s\n', char(string(animal)));
    fprintf('Mode  : %s\n', processing_mode);
    fprintf('------------------------------------------------------------\n');

    %% ============================================================
    % Mean GCaMP images
    % =============================================================

    meanImgs_gcamp = ...
        save_mean_images( ...
            'GCaMP', ...
            animal, ...
            ages, ...
            dates, ...
            numAcquisitions, ...
            gcamp_output_folders, ...
            gcamp_suite2p_folders);

    if ~isfield(data, 'gcamp_plane') || ...
            ~isstruct(data.gcamp_plane)

        data.gcamp_plane = ...
            struct();
    end

    data.gcamp_plane.meanImgs_gcamp = ...
        meanImgs_gcamp;

    %% ============================================================
    % Electroporated mean images
    % =============================================================

    electroporated_column = ...
        find_electroporated_suite2p_column( ...
            suite2p_folders);

    if ~isempty(electroporated_column)

        if electroporated_column == 2
            channel_name = 'Red';
        else
            channel_name = 'Blue';
        end

        meanImgs_electroporated = ...
            save_mean_images( ...
                channel_name, ...
                animal, ...
                ages, ...
                dates, ...
                numAcquisitions, ...
                gcamp_output_folders, ...
                suite2p_folders(:, electroporated_column));

    else

        meanImgs_electroporated = {};
    end

    if ~isfield(data, 'electroporated_plane') || ...
            ~isstruct(data.electroporated_plane)

        data.electroporated_plane = ...
            struct();
    end

    data.electroporated_plane.meanImgs_electroporated = ...
        meanImgs_electroporated;

    %% ============================================================
    % ZSeries
    % =============================================================

    if isfield(paths, 'ZSeries') && ...
            ~isempty(paths.ZSeries)

        zseries = ...
            load_or_process_zseries( ...
                paths.ZSeries, ...
                gcamp_root_folders, ...
                metadata.ZSeries, ...
                paths.output_folders, ...
                automatic_selection, ...
                processing_mode, ...
                data, ...
                line, ...
                animal, ...
                dates, ...
                ages);

        data.ZSeries = ...
            zseries;

    else

        data.ZSeries = ...
            struct();
    end

    %% ============================================================
    % GCaMP cells
    % =============================================================

    gcamp_plane = ...
        process_gcamp_cells( ...
            numAcquisitions, ...
            gcamp_output_folders, ...
            gcamp_suite2p_folders, ...
            meanImgs_gcamp, ...
            data);

    data.gcamp_plane = ...
        gcamp_plane;

    %% ============================================================
    % Motion
    %
    % L'association recording <-> TSeries est deja centralisee dans
    % folder_selection. Ici, l'indice m est utilise directement.
    %
    % La fonction motion reçoit les metadata complets.
    % Pour chaque acquisition, elle calcule elle-même :
    %
    %   sampling_rate_motion = SamplingRatePlane * NumPlanes
    %
    % Cette fréquence globale est utilisée pour la camera / motion.
    % =============================================================

    avg_block = 5;

    [motion, camFolders] = ...
        load_or_process_motion( ...
            gcamp_TSeries_folders, ...
            gcamp_root_folders, ...
            numAcquisitions, ...
            avg_block, ...
            metadata, ...
            animal, ...
            data, ...
            processing_mode);

    data.motion = ...
        motion;

    paths.camera = ...
        camFolders;

    %% ============================================================
    % Stimulation
    %
    % Aucun realignement local : date_folders{m}, TSeries_folders{m}
    % et data.stim.*{m} correspondent deja au meme recording.
    % =============================================================

    data = ...
        load_or_process_stims( ...
            date_folders, ...
            gcamp_TSeries_folders, ...
            numAcquisitions, ...
            data);

    %% ============================================================
    % Electroporated preparation
    % =============================================================

    [processing_cache, data] = ...
        process_electroporated_pass1( ...
            numAcquisitions, ...
            paths.gcamp_root, ...
            paths.gcamp_output, ...
            include_electroporated, ...
            paths.date, ...
            paths.TSeries, ...
            paths.suite2p, ...
            metadata, ...
            data, ...
            processing_mode);

    % ============================================================
    % LOAD_ONLY : PASS 2 uniquement pour les plans dont le masque final
    % est disponible et dont les ROI sont absentes/obsoletes.
    % Aucun fallback ni interface pour les autres plans.
    % ============================================================

    if strcmpi(processing_mode, 'load_only')

        [electroporated_plane, data] = ...
            process_electroporated_pass2( ...
                processing_cache, ...
                numAcquisitions, ...
                paths.gcamp_output, ...
                data.gcamp_plane.meanImgs_gcamp, ...
                data, ...
                false);

        data.electroporated_plane = ...
            electroporated_plane;
    end

    group.data = ...
        data;

    group.paths = ...
        paths;
end
