function update_cell_selection_summary( ...
        fig, valid_cells)
%UPDATE_CELL_SELECTION_SUMMARY
%
% Ajoute ou remplace une ligne dans le tableau récapitulatif de
% sélection des cellules.
%
% Une ligne correspond à :
%
%   type × animal × date × enregistrement × plan
%   × type de cellules × version
%
% Le tableau contient :
%
%   - statistiques globales
%   - statistiques cellules GCaMP
%   - statistiques cellules électroporées
%
% Le tableau est enregistré au niveau LINE :
%
%   ...\Summary plots\
%       <mode>\
%       Development|Adult\
%       line\
%           cell_selection_summary.xlsx
%
% Exemple :
%
%   output_folder =
%       ...\Automatic\Adult\mtor46\2469\15-06-2026
%
% donne :
%
%   ...\Automatic\Adult\mtor46\cell_selection_summary.xlsx


    %==============================================================
    % APPDATA
    %==============================================================

    output_folder = get_appdata_or_default( ...
        fig, ...
        'output_folder', ...
        '');

    gcamp_output_folder = get_appdata_or_default( ...
        fig, ...
        'gcamp_output_folder', ...
        '');

    gcamp_TSeries_path = get_appdata_or_default( ...
        fig, ...
        'gcamp_TSeries_path', ...
        '');

    type_name = get_appdata_or_default( ...
        fig, ...
        'type', ...
        '');

    line_name = get_appdata_or_default( ...
        fig, ...
        'line', ...
        '');

    animal = get_appdata_or_default( ...
        fig, ...
        'animal', ...
        '');

    date_name = get_appdata_or_default( ...
        fig, ...
        'date', ...
        '');

    age = get_appdata_or_default( ...
        fig, ...
        'age', ...
        '');

    plane = get_appdata_or_default( ...
        fig, ...
        'plane', ...
        NaN);

    cell_type = get_appdata_or_default( ...
        fig, ...
        'cell_type', ...
        '');

    initial_cell_count = get_appdata_or_default( ...
        fig, ...
        'initial_cell_count', ...
        NaN);

    opts = get_appdata_or_default( ...
        fig, ...
        'opts', ...
        struct());

    bad_segs = get_appdata_or_default( ...
        fig, ...
        'bad_segs', ...
        []);

    total_frame_count = get_appdata_or_default( ...
        fig, ...
        'total_frame_count', ...
        NaN);

    fs = get_appdata_or_default( ...
        fig, ...
        'fs', ...
        NaN);

    electroporated_indices = get_appdata_or_default( ...
        fig, ...
        'electroporated_indices', ...
        []);

    comment = get_appdata_or_default( ...
        fig, ...
        'comment', ...
        '');


    %==============================================================
    % NORMALISATION TEXTES
    %==============================================================

    output_folder = normalize_text_value( ...
        output_folder);

    gcamp_output_folder = normalize_text_value( ...
        gcamp_output_folder);

    gcamp_TSeries_path = normalize_text_value( ...
        gcamp_TSeries_path);

    type_name = normalize_text_value( ...
        type_name);

    line_name = normalize_text_value( ...
        line_name);

    animal = normalize_text_value( ...
        animal);

    date_name = normalize_text_value( ...
        date_name);

    age = normalize_text_value( ...
        age);

    cell_type = normalize_text_value( ...
        cell_type);

    comment = normalize_text_value( ...
        comment);


    %==============================================================
    % NORMALISATION NUMÉRIQUE
    %==============================================================

    plane = normalize_numeric_scalar( ...
        plane, ...
        NaN);

    initial_cell_count = normalize_numeric_scalar( ...
        initial_cell_count, ...
        NaN);

    fs = normalize_numeric_scalar( ...
        fs, ...
        NaN);

    total_frame_count = normalize_numeric_scalar( ...
        total_frame_count, ...
        NaN);


    %==============================================================
    % OUTPUT FOLDER
    %==============================================================

    if isempty(output_folder)

        warning( ...
            ['output_folder vide : le tableau récapitulatif ' ...
             'ne peut pas être enregistré.']);

        return;
    end


    %==============================================================
    % DOSSIER LINE
    %
    % output_folder :
    %
    %   ...\line\animal\date
    %
    % summary_root :
    %
    %   ...\line
    %==============================================================

    summary_root = ...
        fileparts( ...
            fileparts( ...
                output_folder));


    if isempty(summary_root)

        warning( ...
            ['Impossible de déterminer le dossier LINE à partir de : ' ...
             '%s'], ...
            output_folder);

        return;
    end


    if exist(summary_root,'dir') ~= 7

        try

            mkdir(summary_root);

        catch ME

            warning( ...
                ['Impossible de créer le dossier du tableau : ' ...
                 '%s'], ...
                ME.message);

            return;
        end
    end


    %==============================================================
    % RÉFÉRENTIEL COMPLET DU PLAN
    %
    % Source unique de vérité :
    %   valid_cells = indices des cellules conservées.
    %
    % Les cellules exclues sont toujours déduites automatiquement comme
    % le complément de valid_cells dans 1:initial_cell_count.
    %==============================================================

    if isfinite(initial_cell_count)

        initial_cell_count = ...
            max( ...
                0, ...
                round(initial_cell_count));

    else

        % Fallback robuste : dans le tuner, DF_sg conserve toujours
        % toutes les cellules du plan.
        DF_sg = get_appdata_or_default( ...
            fig, ...
            'DF_sg', ...
            []);

        if isnumeric(DF_sg) && ...
                ~isempty(DF_sg)

            initial_cell_count = ...
                size(DF_sg,1);

        else

            % Dernier fallback si la fonction est appelée hors tuner.
            tmp_valid = ...
                round( ...
                    double( ...
                        valid_cells(:)));

            tmp_valid = ...
                tmp_valid( ...
                    isfinite(tmp_valid) & ...
                    tmp_valid >= 1);

            if isempty(tmp_valid)

                initial_cell_count = 0;

            else

                initial_cell_count = ...
                    max(tmp_valid);
            end
        end
    end


    %==============================================================
    % INDICES VALIDES
    %==============================================================

    valid_indices = ...
        normalize_cell_indices( ...
            valid_cells, ...
            initial_cell_count);

    selected_cell_count = ...
        numel(valid_indices);

    excluded_cell_count = ...
        max( ...
            0, ...
            initial_cell_count - ...
            selected_cell_count);


    if initial_cell_count > 0

        selection_rate_pct = ...
            100 * ...
            selected_cell_count / ...
            initial_cell_count;

    else

        selection_rate_pct = ...
            NaN;
    end


    %==============================================================
    % INDICES DE POPULATION
    %
    % Dans le référentiel Combined :
    %
    %   Electroporated = electroporated_indices
    %   GCaMP          = toutes les autres cellules
    %==============================================================

    electroporated_indices = ...
        normalize_cell_indices( ...
            electroporated_indices, ...
            initial_cell_count);

    all_indices = ...
        (1:initial_cell_count).';

    gcamp_indices = ...
        setdiff( ...
            all_indices, ...
            electroporated_indices, ...
            'stable');


    %==============================================================
    % COMPTAGES PAR POPULATION
    %==============================================================

    initial_electroporated_count = ...
        numel(electroporated_indices);

    initial_gcamp_count = ...
        numel(gcamp_indices);

    selected_electroporated_count = ...
        numel( ...
            intersect( ...
                valid_indices, ...
                electroporated_indices));

    selected_gcamp_count = ...
        numel( ...
            intersect( ...
                valid_indices, ...
                gcamp_indices));

    excluded_electroporated_count = ...
        max( ...
            0, ...
            initial_electroporated_count - ...
            selected_electroporated_count);

    excluded_gcamp_count = ...
        max( ...
            0, ...
            initial_gcamp_count - ...
            selected_gcamp_count);


    %==============================================================
    % TAUX DE SÉLECTION PAR POPULATION
    %==============================================================

    if initial_gcamp_count > 0

        gcamp_selection_rate_pct = ...
            100 * ...
            selected_gcamp_count / ...
            initial_gcamp_count;

    else

        gcamp_selection_rate_pct = ...
            NaN;
    end


    if initial_electroporated_count > 0

        electroporated_selection_rate_pct = ...
            100 * ...
            selected_electroporated_count / ...
            initial_electroporated_count;

    else

        electroporated_selection_rate_pct = ...
            NaN;
    end


    %==============================================================
    % NOM DE L'ENREGISTREMENT
    %==============================================================

    recording = '';


    if ~isempty(gcamp_TSeries_path)

        current_path = ...
            remove_trailing_filesep( ...
                gcamp_TSeries_path);

        [parent_path, current_name, current_extension] = ...
            fileparts( ...
                current_path);


        if isempty(current_extension)

            recording = ...
                current_name;

        else

            parent_path = ...
                remove_trailing_filesep( ...
                    parent_path);

            [~, recording] = ...
                fileparts( ...
                    parent_path);
        end
    end


    %==============================================================
    % VERSION
    %==============================================================

    version = '';


    if ~isempty(gcamp_output_folder)

        current_output_path = ...
            remove_trailing_filesep( ...
                gcamp_output_folder);

        [parent_path, last_folder] = ...
            fileparts( ...
                current_output_path);


        if startsWith( ...
                string(last_folder), ...
                "v", ...
                'IgnoreCase', ...
                true)

            version = ...
                last_folder;


        elseif ~isempty( ...
                regexp( ...
                    last_folder, ...
                    '^plane\d+$', ...
                    'once'))

            parent_path = ...
                remove_trailing_filesep( ...
                    parent_path);

            [~, version] = ...
                fileparts( ...
                    parent_path);

        else

            version = ...
                last_folder;
        end
    end


    %==============================================================
    % OPTIONS DE DÉTECTION
    %==============================================================

    window_size_s = ...
        get_struct_numeric_value( ...
            opts, ...
            'window_size_s');

    window_size_frames = ...
        get_struct_numeric_value( ...
            opts, ...
            'window_size');

    savgol_window_ms = ...
        get_struct_numeric_value( ...
            opts, ...
            'savgol_win_ms');

    savgol_window_frames = ...
        get_struct_numeric_value( ...
            opts, ...
            'savgol_win');

    savgol_polynomial = ...
        get_struct_numeric_value( ...
            opts, ...
            'savgol_poly');

    refractory_period_ms = ...
        get_struct_numeric_value( ...
            opts, ...
            'refrac_ms');

    refractory_period_frames = ...
        get_struct_numeric_value( ...
            opts, ...
            'refrac_fr');

    prominence_factor = ...
        get_struct_numeric_value( ...
            opts, ...
            'prominence_factor');

    minimum_peak_count = ...
        get_struct_numeric_value( ...
            opts, ...
            'min_n_peaks_cutoff');

    minimum_mask_area_um2 = ...
        get_struct_numeric_value( ...
            opts, ...
            'min_mask_um2');

    minimum_mask_connectivity = ...
        get_struct_numeric_value( ...
            opts, ...
            'min_mask_connectivity');


    detection_threshold_sigma = ...
        3.09;


    %==============================================================
    % BAD SEGMENTS
    %
    % bad_segs est l'unique representation persistante des artefacts
    % motion pour le plan courant. Le nombre de mauvaises frames est
    % deduit directement de l'union des segments [debut fin].
    %==============================================================

    bad_frame_count = ...
        count_bad_frames_from_segments( ...
            bad_segs, ...
            total_frame_count);


    if isfinite(total_frame_count) && ...
            total_frame_count > 0

        bad_frames_pct = ...
            100 * ...
            bad_frame_count / ...
            total_frame_count;

    else

        bad_frames_pct = ...
            NaN;
    end


    %==============================================================
    % NOUVELLE LIGNE
    %==============================================================

    new_row = table( ...
        string(type_name), ...
        string(line_name), ...
        string(animal), ...
        string(date_name), ...
        string(age), ...
        string(recording), ...
        double(plane), ...
        string(version), ...
        string(cell_type), ...
        string(comment), ...
        double(detection_threshold_sigma), ...
        double(window_size_s), ...
        double(window_size_frames), ...
        double(savgol_window_ms), ...
        double(savgol_window_frames), ...
        double(savgol_polynomial), ...
        double(refractory_period_ms), ...
        double(refractory_period_frames), ...
        double(prominence_factor), ...
        double(minimum_peak_count), ...
        double(minimum_mask_area_um2), ...
        double(minimum_mask_connectivity), ...
        double(initial_cell_count), ...
        double(selected_cell_count), ...
        double(excluded_cell_count), ...
        double(selection_rate_pct), ...
        double(initial_gcamp_count), ...
        double(selected_gcamp_count), ...
        double(excluded_gcamp_count), ...
        double(gcamp_selection_rate_pct), ...
        double(initial_electroporated_count), ...
        double(selected_electroporated_count), ...
        double(excluded_electroporated_count), ...
        double(electroporated_selection_rate_pct), ...
        double(total_frame_count), ...
        double(bad_frame_count), ...
        double(bad_frames_pct), ...
        'VariableNames', { ...
            'Type', ...
            'Line', ...
            'Animal', ...
            'Date', ...
            'Age', ...
            'Recording', ...
            'Plane', ...
            'Version', ...
            'CellType', ...
            'Comment', ...
            'DetectionThreshold_sigma', ...
            'WindowSize_s', ...
            'WindowSize_frames', ...
            'SavGolWindow_ms', ...
            'SavGolWindow_frames', ...
            'SavGolPolynomial', ...
            'RefractoryPeriod_ms', ...
            'RefractoryPeriod_frames', ...
            'ProminenceFactor', ...
            'MinimumPeakCount', ...
            'MinimumMaskArea_um2', ...
            'MinimumMaskConnectivity', ...
            'InitialCells', ...
            'SelectedCells', ...
            'ExcludedCells', ...
            'SelectionRate_pct', ...
            'InitialGCaMPCells', ...
            'SelectedGCaMPCells', ...
            'ExcludedGCaMPCells', ...
            'GCaMPSelectionRate_pct', ...
            'InitialElectroporatedCells', ...
            'SelectedElectroporatedCells', ...
            'ExcludedElectroporatedCells', ...
            'ElectroporatedSelectionRate_pct', ...
            'TotalFrames', ...
            'BadFrames', ...
            'BadFrames_pct'});


    %==============================================================
    % CHEMIN DU TABLEAU
    %==============================================================

    summary_path = ...
        fullfile( ...
            summary_root, ...
            'cell_selection_summary.xlsx');


    old_table = ...
        table();


    %==============================================================
    % LECTURE TABLE EXISTANTE
    %==============================================================

    if exist(summary_path,'file') == 2

        try

            old_table = ...
                readtable( ...
                    summary_path, ...
                    'VariableNamingRule', ...
                    'preserve', ...
                    'TextType', ...
                    'string');

            old_table = ...
                normalize_selection_summary_table( ...
                    old_table);

        catch ME

            warning( ...
                ['Impossible de relire le tableau existant. ' ...
                 'Le tableau sera reconstruit : %s'], ...
                ME.message);

            old_table = ...
                table();
        end
    end


    %==============================================================
    % SUPPRIMER ANCIENNE LIGNE IDENTIQUE
    %==============================================================

    if ~isempty(old_table)

        old_table = ...
            normalize_selection_summary_table( ...
                old_table);


        same_row = ...
            strcmpi( ...
                string(old_table.Type), ...
                string(new_row.Type)) & ...
            strcmpi( ...
                string(old_table.Line), ...
                string(new_row.Line)) & ...
            strcmpi( ...
                string(old_table.Animal), ...
                string(new_row.Animal)) & ...
            strcmpi( ...
                string(old_table.Date), ...
                string(new_row.Date)) & ...
            strcmpi( ...
                string(old_table.Recording), ...
                string(new_row.Recording)) & ...
            numeric_values_equal( ...
                old_table.Plane, ...
                new_row.Plane) & ...
            strcmpi( ...
                string(old_table.Version), ...
                string(new_row.Version)) & ...
            strcmpi( ...
                string(old_table.CellType), ...
                string(new_row.CellType));


        old_table(same_row,:) = [];
    end


    %==============================================================
    % AJOUT
    %==============================================================

    new_row = ...
        normalize_selection_summary_table( ...
            new_row);


    if isempty(old_table)

        selection_table = ...
            new_row;

    else

        old_table = ...
            normalize_selection_summary_table( ...
                old_table);

        selection_table = ...
            [ ...
                old_table; ...
                new_row ...
            ];
    end


    %==============================================================
    % TRI
    %==============================================================

    try

        selection_table = ...
            sortrows( ...
                selection_table, ...
                { ...
                    'Type', ...
                    'Line', ...
                    'Animal', ...
                    'Date', ...
                    'Recording', ...
                    'Plane', ...
                    'Version', ...
                    'CellType' ...
                });

    catch ME

        warning( ...
            'Le tableau n''a pas pu être trié : %s', ...
            ME.message);
    end


    %==============================================================
    % SAUVEGARDE
    %==============================================================

    try

        writetable( ...
            selection_table, ...
            summary_path);

    catch ME

        warning( ...
            ['Impossible d''enregistrer le tableau de sélection : ' ...
             '%s'], ...
            ME.message);

        return;
    end


    %==============================================================
    % AFFICHAGE
    %==============================================================

    fprintf('\n');
    fprintf('Cell selection summary updated:\n');
    fprintf('%s\n', summary_path);

    fprintf( ...
        ['  %s | %s | %s | %s | %s | plane %g | %s\n' ...
         '  TOTAL          : %d / %d kept (%.1f%%)\n' ...
         '  GCaMP          : %d / %d kept (%.1f%%)\n' ...
         '  Electroporated : %d / %d kept (%.1f%%)\n' ...
         '  Bad frames     : %d / %g (%.2f%%)\n' ...
         '  Comment        : %s\n'], ...
        type_name, ...
        line_name, ...
        animal, ...
        date_name, ...
        recording, ...
        plane, ...
        version, ...
        selected_cell_count, ...
        initial_cell_count, ...
        selection_rate_pct, ...
        selected_gcamp_count, ...
        initial_gcamp_count, ...
        gcamp_selection_rate_pct, ...
        selected_electroporated_count, ...
        initial_electroporated_count, ...
        electroporated_selection_rate_pct, ...
        bad_frame_count, ...
        total_frame_count, ...
        bad_frames_pct, ...
        comment);
end


%======================================================================
% APPDATA
%======================================================================

function value = get_appdata_or_default( ...
        fig, field_name, default_value)

    value = ...
        default_value;

    if nargin < 3

        default_value = [];
        value = default_value;
    end

    if isempty(fig) || ...
            ~isgraphics(fig) || ...
            ~isappdata(fig,field_name)

        return;
    end

    current_value = ...
        getappdata( ...
            fig, ...
            field_name);

    if ~isempty(current_value)

        value = ...
            current_value;
    end
end


%======================================================================
% STRUCT NUMERIC VALUE
%======================================================================

function value = get_struct_numeric_value( ...
        input_struct, field_name)

    value = ...
        NaN;

    if isempty(input_struct) || ...
            ~isstruct(input_struct) || ...
            ~isfield(input_struct,field_name)

        return;
    end

    value = ...
        normalize_numeric_scalar( ...
            input_struct.(field_name), ...
            NaN);
end


%======================================================================
% NORMALIZE TEXT
%======================================================================

function value = normalize_text_value(value)

    if isempty(value)

        value = '';
        return;
    end

    if iscell(value)

        value = ...
            value{1};
    end

    if iscategorical(value)

        value = ...
            string(value);
    end

    value = ...
        string(value);

    if isempty(value) || ...
            ismissing(value(1))

        value = '';
        return;
    end

    value = ...
        char( ...
            value(1));
end


%======================================================================
% NORMALIZE NUMERIC
%======================================================================

function value = normalize_numeric_scalar( ...
        value, default_value)

    if nargin < 2

        default_value = ...
            NaN;
    end

    if isempty(value)

        value = ...
            default_value;

        return;
    end

    if iscell(value)

        value = ...
            value{1};
    end

    if islogical(value)

        value = ...
            double(value);
    end

    if ischar(value) || ...
            isstring(value) || ...
            iscategorical(value)

        value = ...
            str2double( ...
                string(value));
    end

    if ~isnumeric(value) || ...
            isempty(value)

        value = ...
            default_value;

        return;
    end

    value = ...
        double( ...
            value(1));
end


%======================================================================
% REMOVE TRAILING FILESEP
%======================================================================

function path_value = remove_trailing_filesep( ...
        path_value)

    path_value = ...
        normalize_text_value( ...
            path_value);

    while numel(path_value) > 3 && ...
            ( ...
                path_value(end) == '\' || ...
                path_value(end) == '/' ...
            )

        path_value(end) = [];
    end
end




%======================================================================
% NORMALIZE CELL INDICES
%======================================================================

function indices = normalize_cell_indices( ...
        indices, nCells)

    if isempty(indices)

        indices = ...
            zeros(0,1);

        return;
    end

    indices = ...
        round( ...
            double( ...
                indices(:)));

    indices = ...
        indices( ...
            isfinite(indices) & ...
            indices >= 1 & ...
            indices <= nCells);

    indices = ...
        unique( ...
            indices, ...
            'stable');
end


%======================================================================
% NUMERIC COMPARISON
%======================================================================

function comparison = numeric_values_equal( ...
        first_values, second_value)

    first_values = ...
        double(first_values);

    second_value = ...
        double(second_value);

    comparison = ...
        first_values == ...
        second_value;

    comparison = ...
        comparison | ...
        ( ...
            isnan(first_values) & ...
            isnan(second_value) ...
        );
end


%======================================================================
% NORMALIZE SUMMARY TABLE
%======================================================================

function output_table = normalize_selection_summary_table( ...
        input_table)

    expected_names = { ...
        'Type', ...
        'Line', ...
        'Animal', ...
        'Date', ...
        'Age', ...
        'Recording', ...
        'Plane', ...
        'Version', ...
        'CellType', ...
        'Comment', ...
        'DetectionThreshold_sigma', ...
        'WindowSize_s', ...
        'WindowSize_frames', ...
        'SavGolWindow_ms', ...
        'SavGolWindow_frames', ...
        'SavGolPolynomial', ...
        'RefractoryPeriod_ms', ...
        'RefractoryPeriod_frames', ...
        'ProminenceFactor', ...
        'MinimumPeakCount', ...
        'MinimumMaskArea_um2', ...
        'MinimumMaskConnectivity', ...
        'InitialCells', ...
        'SelectedCells', ...
        'ExcludedCells', ...
        'SelectionRate_pct', ...
        'InitialGCaMPCells', ...
        'SelectedGCaMPCells', ...
        'ExcludedGCaMPCells', ...
        'GCaMPSelectionRate_pct', ...
        'InitialElectroporatedCells', ...
        'SelectedElectroporatedCells', ...
        'ExcludedElectroporatedCells', ...
        'ElectroporatedSelectionRate_pct', ...
        'TotalFrames', ...
        'BadFrames', ...
        'BadFrames_pct'};


    text_names = { ...
        'Type', ...
        'Line', ...
        'Animal', ...
        'Date', ...
        'Age', ...
        'Recording', ...
        'Version', ...
        'CellType', ...
        'Comment'};


    numeric_names = ...
        setdiff( ...
            expected_names, ...
            text_names, ...
            'stable');


    if isempty(input_table)

        output_table = ...
            create_empty_selection_summary_table();

        return;
    end


    output_table = ...
        input_table;

    number_of_rows = ...
        height(output_table);


    %==============================================================
    % AJOUTER COLONNES ABSENTES
    %
    % Permet notamment de relire les anciens fichiers Excel
    % créés avant l'ajout des colonnes Electroporated / GCaMP.
    %==============================================================

    for i = 1:numel(expected_names)

        current_name = ...
            expected_names{i};

        if ismember( ...
                current_name, ...
                output_table.Properties.VariableNames)

            continue;
        end


        if ismember( ...
                current_name, ...
                text_names)

            output_table.(current_name) = ...
                strings( ...
                    number_of_rows, ...
                    1);

        else

            output_table.(current_name) = ...
                nan( ...
                    number_of_rows, ...
                    1);
        end
    end


    %==============================================================
    % TEXTES
    %==============================================================

    for i = 1:numel(text_names)

        current_name = ...
            text_names{i};

        current_values = ...
            output_table.(current_name);


        if iscell(current_values)

            current_values = ...
                string(current_values);

        elseif iscategorical(current_values)

            current_values = ...
                string(current_values);

        elseif ischar(current_values)

            current_values = ...
                string( ...
                    cellstr( ...
                        current_values));

        else

            current_values = ...
                string(current_values);
        end


        current_values( ...
            ismissing(current_values)) = ...
            "";


        output_table.(current_name) = ...
            reshape( ...
                current_values, ...
                [], ...
                1);
    end


    %==============================================================
    % NUMÉRIQUES
    %==============================================================

    for i = 1:numel(numeric_names)

        current_name = ...
            numeric_names{i};

        current_values = ...
            output_table.(current_name);


        if isnumeric(current_values) || ...
                islogical(current_values)

            current_values = ...
                double(current_values);

        elseif iscell(current_values)

            current_values = ...
                str2double( ...
                    string(current_values));

        elseif isstring(current_values) || ...
                ischar(current_values) || ...
                iscategorical(current_values)

            current_values = ...
                str2double( ...
                    string(current_values));

        else

            current_values = ...
                nan( ...
                    number_of_rows, ...
                    1);
        end


        output_table.(current_name) = ...
            reshape( ...
                current_values, ...
                [], ...
                1);
    end


    output_table = ...
        output_table(:,expected_names);
end


%======================================================================
% EMPTY SUMMARY TABLE
%======================================================================

function empty_table = create_empty_selection_summary_table()

    empty_table = table( ...
        strings(0,1), ... % Type
        strings(0,1), ... % Line
        strings(0,1), ... % Animal
        strings(0,1), ... % Date
        strings(0,1), ... % Age
        strings(0,1), ... % Recording
        nan(0,1), ...     % Plane
        strings(0,1), ... % Version
        strings(0,1), ... % CellType
        strings(0,1), ... % Comment
        nan(0,1), ...     % DetectionThreshold_sigma
        nan(0,1), ...     % WindowSize_s
        nan(0,1), ...     % WindowSize_frames
        nan(0,1), ...     % SavGolWindow_ms
        nan(0,1), ...     % SavGolWindow_frames
        nan(0,1), ...     % SavGolPolynomial
        nan(0,1), ...     % RefractoryPeriod_ms
        nan(0,1), ...     % RefractoryPeriod_frames
        nan(0,1), ...     % ProminenceFactor
        nan(0,1), ...     % MinimumPeakCount
        nan(0,1), ...     % MinimumMaskArea_um2
        nan(0,1), ...     % MinimumMaskConnectivity
        nan(0,1), ...     % InitialCells
        nan(0,1), ...     % SelectedCells
        nan(0,1), ...     % ExcludedCells
        nan(0,1), ...     % SelectionRate_pct
        nan(0,1), ...     % InitialGCaMPCells
        nan(0,1), ...     % SelectedGCaMPCells
        nan(0,1), ...     % ExcludedGCaMPCells
        nan(0,1), ...     % GCaMPSelectionRate_pct
        nan(0,1), ...     % InitialElectroporatedCells
        nan(0,1), ...     % SelectedElectroporatedCells
        nan(0,1), ...     % ExcludedElectroporatedCells
        nan(0,1), ...     % ElectroporatedSelectionRate_pct
        nan(0,1), ...     % TotalFrames
        nan(0,1), ...     % BadFrames
        nan(0,1), ...     % BadFrames_pct
        'VariableNames', { ...
            'Type', ...
            'Line', ...
            'Animal', ...
            'Date', ...
            'Age', ...
            'Recording', ...
            'Plane', ...
            'Version', ...
            'CellType', ...
            'Comment', ...
            'DetectionThreshold_sigma', ...
            'WindowSize_s', ...
            'WindowSize_frames', ...
            'SavGolWindow_ms', ...
            'SavGolWindow_frames', ...
            'SavGolPolynomial', ...
            'RefractoryPeriod_ms', ...
            'RefractoryPeriod_frames', ...
            'ProminenceFactor', ...
            'MinimumPeakCount', ...
            'MinimumMaskArea_um2', ...
            'MinimumMaskConnectivity', ...
            'InitialCells', ...
            'SelectedCells', ...
            'ExcludedCells', ...
            'SelectionRate_pct', ...
            'InitialGCaMPCells', ...
            'SelectedGCaMPCells', ...
            'ExcludedGCaMPCells', ...
            'GCaMPSelectionRate_pct', ...
            'InitialElectroporatedCells', ...
            'SelectedElectroporatedCells', ...
            'ExcludedElectroporatedCells', ...
            'ElectroporatedSelectionRate_pct', ...
            'TotalFrames', ...
            'BadFrames', ...
            'BadFrames_pct'});
end


%======================================================================
% BAD SEGMENTS -> NOMBRE DE FRAMES
%======================================================================

function bad_frame_count = count_bad_frames_from_segments( ...
        bad_segs, total_frame_count)

    bad_frame_count = ...
        0;


    if isempty(bad_segs)
        return;
    end


    if ~isnumeric(bad_segs)
        return;
    end


    bad_segs = ...
        double(bad_segs);


    if isvector(bad_segs) && ...
            numel(bad_segs) == 2

        bad_segs = ...
            reshape( ...
                bad_segs, ...
                1, ...
                2);
    end


    if size(bad_segs,2) < 2
        return;
    end


    bad_segs = ...
        bad_segs(:,1:2);


    %==============================================================
    % NORMALISATION DES BORNES
    %==============================================================

    valid_rows = ...
        all( ...
            isfinite(bad_segs), ...
            2);

    bad_segs = ...
        bad_segs(valid_rows,:);


    if isempty(bad_segs)
        return;
    end


    bad_segs = ...
        round(bad_segs);


    swap_rows = ...
        bad_segs(:,1) > ...
        bad_segs(:,2);


    if any(swap_rows)

        tmp = ...
            bad_segs(swap_rows,1);

        bad_segs(swap_rows,1) = ...
            bad_segs(swap_rows,2);

        bad_segs(swap_rows,2) = ...
            tmp;
    end


    bad_segs(:,1) = ...
        max( ...
            1, ...
            bad_segs(:,1));


    if isfinite(total_frame_count) && ...
            total_frame_count > 0

        total_frame_count = ...
            round(total_frame_count);

        bad_segs(:,2) = ...
            min( ...
                total_frame_count, ...
                bad_segs(:,2));
    end


    bad_segs = ...
        bad_segs( ...
            bad_segs(:,1) <= bad_segs(:,2), ...
            :);


    if isempty(bad_segs)
        return;
    end


    %==============================================================
    % FUSION DES SEGMENTS
    %
    % Evite tout double comptage si deux segments se chevauchent ou sont
    % adjacents.
    %==============================================================

    bad_segs = ...
        sortrows( ...
            bad_segs, ...
            [1 2]);


    merged = ...
        bad_segs(1,:);


    for k = 2:size(bad_segs,1)

        if bad_segs(k,1) <= ...
                merged(end,2) + 1

            merged(end,2) = ...
                max( ...
                    merged(end,2), ...
                    bad_segs(k,2));

        else

            merged(end+1,:) = ...
                bad_segs(k,:); %#ok<AGROW>
        end
    end


    bad_frame_count = ...
        sum( ...
            merged(:,2) - ...
            merged(:,1) + ...
            1);
end
