function update_cell_selection_summary( ...
        fig, valid_cells, invalid_cells)
%UPDATE_CELL_SELECTION_SUMMARY
%
% Ajoute ou remplace une ligne dans le tableau récapitulatif de
% sélection des cellules.
%
% Une ligne correspond à :
%
%   type × animal × date × enregistrement × plan
%   × type de cellules × version
%
% Les informations générales sont récupérées depuis les appdata de
% la figure peak_detection_tuner.
%
% Le tableau est enregistré dans :
%
%   output_folder\cell_selection_summary.xlsx
%
% Ce fichier est autonome : les helpers nécessaires sont définis
% à la fin du fichier.

    %==============================================================
    % Récupération des appdata
    %==============================================================
    output_folder = get_appdata_or_default( ...
        fig, ...
        'output_folder', ...
        '');

    gcamp_output_folder = get_appdata_or_default( ...
        fig, ...
        'gcamp_output_folder', ...
        '');

    gcamp_TSeries_path = get_appdata_or_default( ...
        fig, ...
        'gcamp_TSeries_path', ...
        '');

    type_name = get_appdata_or_default( ...
        fig, ...
        'type', ...
        '');

    line_name = get_appdata_or_default( ...
        fig, ...
        'line', ...
        '');

    animal = get_appdata_or_default( ...
        fig, ...
        'animal', ...
        '');

    date_name = get_appdata_or_default( ...
        fig, ...
        'date', ...
        '');

    age = get_appdata_or_default( ...
        fig, ...
        'age', ...
        '');

    plane = get_appdata_or_default( ...
        fig, ...
        'plane', ...
        NaN);

    cell_type = get_appdata_or_default( ...
        fig, ...
        'cell_type', ...
        '');

    initial_cell_count = get_appdata_or_default( ...
        fig, ...
        'initial_cell_count', ...
        NaN);

    opts = get_appdata_or_default( ...
        fig, ...
        'opts', ...
        struct());

    bad_frames = get_appdata_or_default( ...
        fig, ...
        'bad_frames', ...
        []);
    
    total_frame_count = get_appdata_or_default( ...
        fig, ...
        'total_frame_count', ...
        NaN);

    fs = get_appdata_or_default( ...
        fig, ...
        'fs', ...
        NaN);

    %==============================================================
    % Normalisation des textes
    %==============================================================
    output_folder = normalize_text_value( ...
        output_folder);

    gcamp_output_folder = normalize_text_value( ...
        gcamp_output_folder);

    gcamp_TSeries_path = normalize_text_value( ...
        gcamp_TSeries_path);

    type_name = normalize_text_value( ...
        type_name);

    line_name = normalize_text_value( ...
        line_name);

    animal = normalize_text_value( ...
        animal);

    date_name = normalize_text_value( ...
        date_name);

    age = normalize_text_value( ...
        age);

    cell_type = normalize_text_value( ...
        cell_type);

    %==============================================================
    % Normalisation des valeurs numériques
    %==============================================================
    plane = normalize_numeric_scalar( ...
        plane, ...
        NaN);

    initial_cell_count = normalize_numeric_scalar( ...
        initial_cell_count, ...
        NaN);
    
    fs = normalize_numeric_scalar( ...
        fs, ...
        NaN);

    total_frame_count = normalize_numeric_scalar( ...
        total_frame_count, ...
        NaN);

    %==============================================================
    % Vérification du dossier de sortie
    %==============================================================
    if isempty(output_folder)

        warning( ...
            ['output_folder vide : le tableau récapitulatif ' ...
             'ne peut pas être enregistré.']);

        return;
    end

    if exist(output_folder, 'dir') ~= 7

        try
            mkdir(output_folder);

        catch ME

            warning( ...
                ['Impossible de créer le dossier de sortie : ' ...
                 '%s'], ...
                ME.message);

            return;
        end
    end

    %==============================================================
    % Calcul du nombre de cellules
    %==============================================================
    selected_cell_count = count_selected_cells( ...
        valid_cells);

    invalid_cell_count = count_selected_cells( ...
        invalid_cells);

    if isfinite(initial_cell_count)

        initial_cell_count = max( ...
            0, ...
            round(initial_cell_count));

        excluded_cell_count = max( ...
            0, ...
            initial_cell_count - selected_cell_count);

    elseif invalid_cell_count > 0

        excluded_cell_count = invalid_cell_count;

        initial_cell_count = ...
            selected_cell_count + excluded_cell_count;

    else

        initial_cell_count = selected_cell_count;
        excluded_cell_count = 0;
    end

    if initial_cell_count > 0

        selection_rate_pct = ...
            100 * selected_cell_count / initial_cell_count;

    else

        selection_rate_pct = NaN;
    end

    %==============================================================
    % Nom de l'enregistrement
    %==============================================================
    recording = '';

    if ~isempty(gcamp_TSeries_path)

        current_path = remove_trailing_filesep( ...
            gcamp_TSeries_path);

        [parent_path, current_name, current_extension] = ...
            fileparts(current_path);

        if isempty(current_extension)

            recording = current_name;

        else

            % Si gcamp_TSeries_path correspond par erreur à un fichier,
            % utiliser le nom de son dossier parent.
            parent_path = remove_trailing_filesep( ...
                parent_path);

            [~, recording] = fileparts( ...
                parent_path);
        end
    end

    %==============================================================
    % Nom de la version
    %==============================================================
    version = '';

    if ~isempty(gcamp_output_folder)

        current_output_path = remove_trailing_filesep( ...
            gcamp_output_folder);

        [parent_path, last_folder] = fileparts( ...
            current_output_path);

        % Cas 1 :
        % gcamp_output_folder pointe directement vers v1_xx_xx...
        if startsWith( ...
                string(last_folder), ...
                "v", ...
                'IgnoreCase', true)

            version = last_folder;

        % Cas 2 :
        % gcamp_output_folder se termine par plane0, plane1...
        elseif ~isempty( ...
                regexp( ...
                    last_folder, ...
                    '^plane\d+$', ...
                    'once'))

            parent_path = remove_trailing_filesep( ...
                parent_path);

            [~, version] = fileparts( ...
                parent_path);

        % Cas 3 :
        % utiliser simplement le dernier dossier
        else

            version = last_folder;
        end
    end

    %==============================================================
    % Options finales de détection
    %==============================================================
    window_size_s = get_struct_numeric_value( ...
        opts, ...
        'window_size_s');

    window_size_frames = get_struct_numeric_value( ...
        opts, ...
        'window_size');

    savgol_window_ms = get_struct_numeric_value( ...
        opts, ...
        'savgol_win_ms');

    savgol_window_frames = get_struct_numeric_value( ...
        opts, ...
        'savgol_win');

    savgol_polynomial = get_struct_numeric_value( ...
        opts, ...
        'savgol_poly');

    refractory_period_ms = get_struct_numeric_value( ...
        opts, ...
        'refrac_ms');

    refractory_period_frames = get_struct_numeric_value( ...
        opts, ...
        'refrac_fr');

    prominence_factor = get_struct_numeric_value( ...
        opts, ...
        'prominence_factor');

    minimum_peak_count = get_struct_numeric_value( ...
        opts, ...
        'min_n_peaks_cutoff');

    minimum_mask_area_um2 = get_struct_numeric_value( ...
        opts, ...
        'min_mask_um2');

    minimum_mask_connectivity = get_struct_numeric_value( ...
        opts, ...
        'min_mask_connectivity');

    % Valeur actuellement utilisée dans detect_peaks_cell_core :
    %
    %   threshold = 3.09 * sigma
    detection_threshold_sigma = 3.09;
    
    %==============================================================
    % Pourcentage total de bad frames
    %==============================================================
    bad_frame_count = count_bad_frames( ...
        bad_frames, ...
        total_frame_count);
    
    if isfinite(total_frame_count) && ...
            total_frame_count > 0
    
        bad_frames_pct = ...
            100 * bad_frame_count / total_frame_count;
    
    else
    
        bad_frames_pct = NaN;
    end

    %==============================================================
    % Création de la nouvelle ligne
    %==============================================================
    new_row = table( ...
    string(type_name), ...
    string(line_name), ...
    string(animal), ...
    string(date_name), ...
    string(age), ...
    string(recording), ...
    double(plane), ...
    string(version), ...
    string(cell_type), ...
    double(detection_threshold_sigma), ...
    double(window_size_s), ...
    double(window_size_frames), ...
    double(savgol_window_ms), ...
    double(savgol_window_frames), ...
    double(savgol_polynomial), ...
    double(refractory_period_ms), ...
    double(refractory_period_frames), ...
    double(prominence_factor), ...
    double(minimum_peak_count), ...
    double(minimum_mask_area_um2), ...
    double(minimum_mask_connectivity), ...
    double(initial_cell_count), ...
    double(selected_cell_count), ...
    double(excluded_cell_count), ...
    double(selection_rate_pct), ...
    double(total_frame_count), ...
    double(bad_frame_count), ...
    double(bad_frames_pct), ...
    'VariableNames', { ...
        'Type', ...
        'Line', ...
        'Animal', ...
        'Date', ...
        'Age', ...
        'Recording', ...
        'Plane', ...
        'Version', ...
        'CellType', ...
        'DetectionThreshold_sigma', ...
        'WindowSize_s', ...
        'WindowSize_frames', ...
        'SavGolWindow_ms', ...
        'SavGolWindow_frames', ...
        'SavGolPolynomial', ...
        'RefractoryPeriod_ms', ...
        'RefractoryPeriod_frames', ...
        'ProminenceFactor', ...
        'MinimumPeakCount', ...
        'MinimumMaskArea_um2', ...
        'MinimumMaskConnectivity', ...
        'InitialCells', ...
        'SelectedCells', ...
        'ExcludedCells', ...
        'SelectionRate_pct', ...
        'TotalFrames', ...
        'BadFrames', ...
        'BadFrames_pct'});

    %==============================================================
    % Chemin du tableau
    %==============================================================
    summary_path = fullfile( ...
        output_folder, ...
        'cell_selection_summary.xlsx');

    old_table = table();

    %==============================================================
    % Lecture du tableau existant
    %==============================================================
    if exist(summary_path, 'file') == 2

        try

            old_table = readtable( ...
                summary_path, ...
                'VariableNamingRule', ...
                'preserve', ...
                'TextType', ...
                'string');

            old_table = normalize_selection_summary_table( ...
                old_table);

        catch ME

            warning( ...
                ['Impossible de relire le tableau existant. ' ...
                 'Le tableau sera reconstruit : %s'], ...
                ME.message);

            old_table = table();
        end
    end

    %==============================================================
    % Suppression de l'ancienne ligne correspondant au même élément
    %==============================================================
    %
    % Une nouvelle validation dans la même version remplace la ligne
    % précédente.
    %
    % Une version différente produit une nouvelle ligne.
    %==============================================================
    if ~isempty(old_table)

        old_table = normalize_selection_summary_table( ...
            old_table);

        same_row = ...
            strcmpi( ...
                string(old_table.Type), ...
                string(new_row.Type)) & ...
            strcmpi( ...
                string(old_table.Line), ...
                string(new_row.Line)) & ...
            strcmpi( ...
                string(old_table.Animal), ...
                string(new_row.Animal)) & ...
            strcmpi( ...
                string(old_table.Date), ...
                string(new_row.Date)) & ...
            strcmpi( ...
                string(old_table.Recording), ...
                string(new_row.Recording)) & ...
            numeric_values_equal( ...
                old_table.Plane, ...
                new_row.Plane) & ...
            strcmpi( ...
                string(old_table.Version), ...
                string(new_row.Version)) & ...
            strcmpi( ...
                string(old_table.CellType), ...
                string(new_row.CellType));

        old_table(same_row, :) = [];
    end

    %==============================================================
    % Ajout de la nouvelle ligne
    %==============================================================
    new_row = normalize_selection_summary_table( ...
        new_row);

    if isempty(old_table)

        selection_table = new_row;

    else

        old_table = normalize_selection_summary_table( ...
            old_table);

        selection_table = [ ...
            old_table; ...
            new_row];
    end

    %==============================================================
    % Tri du tableau
    %==============================================================
    try

        selection_table = sortrows( ...
            selection_table, ...
            { ...
                'Type', ...
                'Line', ...
                'Animal', ...
                'Date', ...
                'Recording', ...
                'Plane', ...
                'Version', ...
                'CellType' ...
            });

    catch ME

        warning( ...
            'Le tableau n''a pas pu être trié : %s', ...
            ME.message);
    end

    %==============================================================
    % Sauvegarde
    %==============================================================
    try

        writetable( ...
            selection_table, ...
            summary_path);

    catch ME

        warning( ...
            ['Impossible d''enregistrer le tableau de sélection : ' ...
             '%s'], ...
            ME.message);

        return;
    end

    %==============================================================
    % Affichage
    %==============================================================
    fprintf('\n');
    fprintf('Cell selection summary updated:\n');
    fprintf('%s\n', summary_path);

    fprintf( ...
        ['  %s | %s | %s | %s | %s | plane %g | %s | ' ...
         '%d / %d cells kept (%.1f%%) | ' ...
         '%d / %g bad frames (%.2f%%)\n'], ...
        type_name, ...
        line_name, ...
        animal, ...
        date_name, ...
        recording, ...
        plane, ...
        version, ...
        selected_cell_count, ...
        initial_cell_count, ...
        selection_rate_pct, ...
        bad_frame_count, ...
        total_frame_count, ...
        bad_frames_pct);
end


%======================================================================
% HELPER : récupérer un appdata ou une valeur par défaut
%======================================================================
function value = get_appdata_or_default( ...
        fig, field_name, default_value)

    value = default_value;

    if nargin < 3
        default_value = [];
        value = default_value;
    end

    if isempty(fig)
        return;
    end

    if ~isgraphics(fig)
        return;
    end

    if ~isappdata(fig, field_name)
        return;
    end

    current_value = getappdata( ...
        fig, ...
        field_name);

    if ~isempty(current_value)
        value = current_value;
    end
end


%======================================================================
% HELPER : récupérer une option numérique dans une structure
%======================================================================
function value = get_struct_numeric_value( ...
        input_struct, field_name)

    value = NaN;

    if isempty(input_struct) || ...
            ~isstruct(input_struct)

        return;
    end

    if ~isfield(input_struct, field_name)
        return;
    end

    current_value = input_struct.(field_name);

    value = normalize_numeric_scalar( ...
        current_value, ...
        NaN);
end


%======================================================================
% HELPER : normaliser un texte
%======================================================================
function value = normalize_text_value(value)

    if isempty(value)
        value = '';
        return;
    end

    if iscell(value)

        if isempty(value)
            value = '';
            return;
        end

        value = value{1};
    end

    if iscategorical(value)
        value = string(value);
    end

    value = string(value);

    if isempty(value)
        value = '';
        return;
    end

    value = value(1);

    if ismissing(value)
        value = '';
        return;
    end

    value = char(value);
end


%======================================================================
% HELPER : normaliser une valeur numérique scalaire
%======================================================================
function value = normalize_numeric_scalar( ...
        value, default_value)

    if nargin < 2
        default_value = NaN;
    end

    if isempty(value)
        value = default_value;
        return;
    end

    if iscell(value)

        if isempty(value)
            value = default_value;
            return;
        end

        value = value{1};
    end

    if islogical(value)
        value = double(value);
    end

    if ischar(value) || ...
            isstring(value) || ...
            iscategorical(value)

        value = str2double( ...
            string(value));
    end

    if ~isnumeric(value) || isempty(value)
        value = default_value;
        return;
    end

    value = double(value(1));

    if isempty(value)
        value = default_value;
    end
end


%======================================================================
% HELPER : retirer les séparateurs finaux d'un chemin
%======================================================================
function path_value = remove_trailing_filesep(path_value)

    path_value = normalize_text_value( ...
        path_value);

    while numel(path_value) > 3 && ...
            (path_value(end) == '\' || ...
             path_value(end) == '/')

        path_value(end) = [];
    end
end


%======================================================================
% HELPER : compter les cellules sélectionnées
%======================================================================
function number_of_cells = count_selected_cells(cell_selection)

    if isempty(cell_selection)
        number_of_cells = 0;
        return;
    end

    if islogical(cell_selection)

        number_of_cells = nnz( ...
            cell_selection);

    elseif isnumeric(cell_selection)

        number_of_cells = numel( ...
            cell_selection);

    elseif iscell(cell_selection)

        number_of_cells = numel( ...
            cell_selection);

    else

        number_of_cells = numel( ...
            cell_selection);
    end
end


%======================================================================
% HELPER : comparaison numérique avec gestion des NaN
%======================================================================
function comparison = numeric_values_equal( ...
        first_values, second_value)

    first_values = double( ...
        first_values);

    second_value = double( ...
        second_value);

    comparison = ...
        first_values == second_value;

    comparison = comparison | ...
        (isnan(first_values) & isnan(second_value));
end


%======================================================================
% HELPER : normalisation du tableau
%======================================================================
function output_table = normalize_selection_summary_table( ...
        input_table)

    expected_names = { ...
        'Type', ...
        'Line', ...
        'Animal', ...
        'Date', ...
        'Age', ...
        'Recording', ...
        'Plane', ...
        'Version', ...
        'CellType', ...
        'DetectionThreshold_sigma', ...
        'WindowSize_s', ...
        'WindowSize_frames', ...
        'SavGolWindow_ms', ...
        'SavGolWindow_frames', ...
        'SavGolPolynomial', ...
        'RefractoryPeriod_ms', ...
        'RefractoryPeriod_frames', ...
        'ProminenceFactor', ...
        'MinimumPeakCount', ...
        'MinimumMaskArea_um2', ...
        'MinimumMaskConnectivity', ...
        'InitialCells', ...
        'SelectedCells', ...
        'ExcludedCells', ...
        'SelectionRate_pct', ...
        'TotalFrames', ...
        'BadFrames', ...
        'BadFrames_pct'};

    text_names = { ...
        'Type', ...
        'Line', ...
        'Animal', ...
        'Date', ...
        'Age', ...
        'Recording', ...
        'Version', ...
        'CellType'};

    numeric_names = { ...
        'Plane', ...
        'DetectionThreshold_sigma', ...
        'WindowSize_s', ...
        'WindowSize_frames', ...
        'SavGolWindow_ms', ...
        'SavGolWindow_frames', ...
        'SavGolPolynomial', ...
        'RefractoryPeriod_ms', ...
        'RefractoryPeriod_frames', ...
        'ProminenceFactor', ...
        'MinimumPeakCount', ...
        'MinimumMaskArea_um2', ...
        'MinimumMaskConnectivity', ...
        'InitialCells', ...
        'SelectedCells', ...
        'ExcludedCells', ...
        'SelectionRate_pct', ...
        'TotalFrames', ...
        'BadFrames', ...
        'BadFrames_pct'};

    if isempty(input_table)

        output_table = create_empty_selection_summary_table();
        return;
    end

    output_table = input_table;
    number_of_rows = height(output_table);

    %==============================================================
    % Ajouter les colonnes absentes
    %==============================================================
    for i = 1:numel(expected_names)

        current_name = expected_names{i};

        if ismember( ...
                current_name, ...
                output_table.Properties.VariableNames)

            continue;
        end

        if ismember(current_name, text_names)

            output_table.(current_name) = ...
                strings(number_of_rows, 1);

        else

            output_table.(current_name) = ...
                nan(number_of_rows, 1);
        end
    end

    %==============================================================
    % Normaliser les colonnes texte
    %==============================================================
    for i = 1:numel(text_names)

        current_name = text_names{i};

        current_values = ...
            output_table.(current_name);

        if iscell(current_values)
            current_values = string(current_values);

        elseif iscategorical(current_values)
            current_values = string(current_values);

        elseif ischar(current_values)
            current_values = string( ...
                cellstr(current_values));

        else
            current_values = string(current_values);
        end

        current_values(ismissing(current_values)) = "";

        output_table.(current_name) = ...
            reshape(current_values, [], 1);
    end

    %==============================================================
    % Normaliser les colonnes numériques
    %==============================================================
    for i = 1:numel(numeric_names)

        current_name = numeric_names{i};

        current_values = ...
            output_table.(current_name);

        if isnumeric(current_values) || ...
                islogical(current_values)

            current_values = double( ...
                current_values);

        elseif iscell(current_values)

            current_values = str2double( ...
                string(current_values));

        elseif isstring(current_values) || ...
                ischar(current_values) || ...
                iscategorical(current_values)

            current_values = str2double( ...
                string(current_values));

        else

            current_values = nan( ...
                number_of_rows, ...
                1);
        end

        output_table.(current_name) = ...
            reshape(current_values, [], 1);
    end

    %==============================================================
    % Retirer les anciennes colonnes non utilisées et remettre l'ordre
    %==============================================================
    output_table = output_table(:, expected_names);
end


%======================================================================
% HELPER : créer un tableau vide correctement typé
%======================================================================
function empty_table = create_empty_selection_summary_table()

    empty_table = table( ...
        strings(0, 1), ... % Type
        strings(0, 1), ... % Line
        strings(0, 1), ... % Animal
        strings(0, 1), ... % Date
        strings(0, 1), ... % Age
        strings(0, 1), ... % Recording
        nan(0, 1), ...     % Plane
        strings(0, 1), ... % Version
        strings(0, 1), ... % CellType
        nan(0, 1), ...     % DetectionThreshold_sigma
        nan(0, 1), ...     % WindowSize_s
        nan(0, 1), ...     % WindowSize_frames
        nan(0, 1), ...     % SavGolWindow_ms
        nan(0, 1), ...     % SavGolWindow_frames
        nan(0, 1), ...     % SavGolPolynomial
        nan(0, 1), ...     % RefractoryPeriod_ms
        nan(0, 1), ...     % RefractoryPeriod_frames
        nan(0, 1), ...     % ProminenceFactor
        nan(0, 1), ...     % MinimumPeakCount
        nan(0, 1), ...     % MinimumMaskArea_um2
        nan(0, 1), ...     % MinimumMaskConnectivity
        nan(0, 1), ...     % InitialCells
        nan(0, 1), ...     % SelectedCells
        nan(0, 1), ...     % ExcludedCells
        nan(0, 1), ...     % SelectionRate_pct
        nan(0, 1), ...     % TotalFrames
        nan(0, 1), ...     % BadFrames
        nan(0, 1), ...     % BadFrames_pct
        'VariableNames', { ...
            'Type', ...
            'Line', ...
            'Animal', ...
            'Date', ...
            'Age', ...
            'Recording', ...
            'Plane', ...
            'Version', ...
            'CellType', ...
            'DetectionThreshold_sigma', ...
            'WindowSize_s', ...
            'WindowSize_frames', ...
            'SavGolWindow_ms', ...
            'SavGolWindow_frames', ...
            'SavGolPolynomial', ...
            'RefractoryPeriod_ms', ...
            'RefractoryPeriod_frames', ...
            'ProminenceFactor', ...
            'MinimumPeakCount', ...
            'MinimumMaskArea_um2', ...
            'MinimumMaskConnectivity', ...
            'InitialCells', ...
            'SelectedCells', ...
            'ExcludedCells', ...
            'SelectionRate_pct', ...
            'TotalFrames', ...
            'BadFrames', ...
            'BadFrames_pct'});
end


%======================================================================
% HELPER : compter les bad frames
%======================================================================
function bad_frame_count = count_bad_frames( ...
        bad_frames, total_frame_count)

    bad_frame_count = 0;

    if isempty(bad_frames)
        return;
    end

    if iscell(bad_frames)

        try
            bad_frames = cell2mat(bad_frames);
        catch
            return;
        end
    end

    if islogical(bad_frames)

        bad_frame_count = nnz(bad_frames);
        return;
    end

    if ~isnumeric(bad_frames)
        return;
    end

    bad_frames = double(bad_frames(:));
    bad_frames = bad_frames(isfinite(bad_frames));

    if isempty(bad_frames)
        return;
    end

    if isfinite(total_frame_count) && ...
            numel(bad_frames) == total_frame_count && ...
            all(ismember(bad_frames, [0, 1]))

        bad_frame_count = nnz(bad_frames);
        return;
    end

    bad_frames = round(bad_frames);
    bad_frames = bad_frames(bad_frames >= 1);

    if isfinite(total_frame_count)
        bad_frames = bad_frames( ...
            bad_frames <= total_frame_count);
    end

    bad_frame_count = numel(unique(bad_frames));
end
