function [results_analysis, results_table] = compute_export_basic_metrics( ...
    current_type, ...
    current_animal_group, ...
    current_ages, ...
    gcamp_root_folders, ...
    date_group_paths, ...
    data, ...
    metadata, ...
    include_electroporated_cells)

%COMPUTE_EXPORT_BASIC_METRICS
%
% Activité :
%   PAR PLAN
%
% Pearson :
%   PAR PLAN
%
% Coupling :
%   PAR PLAN
%
% SCE :
%   plans concaténés, donc niveau recording.
%
%
% Coupling sauvegardé :
%
%   coupling_*_by_plane
%   coupling_pvalue_*_by_plane
%
% Aucun lag ni valeur brute de shuffle n'est sauvegardé.


    %==============================================================%
    % Initialisation
    %==============================================================%

    nRec = ...
        numel(gcamp_root_folders);


    synchronous_frames_group = ...
        cell(nRec, 1);


    if nargin < 8 || ...
            isempty(include_electroporated_cells)

        include_electroporated_cells = ...
            '1';
    end


    include_electroporated_cells = ...
        char(string(include_electroporated_cells));


    process_electroporated = ...
        strcmp( ...
            include_electroporated_cells, ...
            '1');


    current_type = ...
        string(current_type);


    current_animal_group = ...
        string(current_animal_group);


    results_analysis = ...
        init_empty_results_analysis( ...
            nRec);


    results_table = ...
        init_results_table();


    %==============================================================%
    % Boucle recordings
    %==============================================================%

    for m = 1:nRec

        date_name = ...
            get_date_name_from_path( ...
                date_group_paths, ...
                m);


        age_label = ...
            get_age_for_recording( ...
                current_ages, ...
                m);


        age_number = ...
            extract_age_number( ...
                age_label);


        session_id = ...
            current_animal_group + ...
            "_" + ...
            date_name + ...
            "_rec" + ...
            string(m);


        try

            %======================================================%
            % Metadata
            %======================================================%

            metadata_m = ...
                get_metadata_for_record( ...
                    metadata, ...
                    m);


            if ~isfield(metadata_m, 'gcamp_plane') || ...
                    isempty(metadata_m.gcamp_plane)

                error( ...
                    'GCaMP metadata missing for rec %d.', ...
                    m);
            end


            metadata_gcamp_m = ...
                metadata_m.gcamp_plane;


            %======================================================%
            % Sampling rate
            %======================================================%

            if ~isfield( ...
                    metadata_gcamp_m, ...
                    'SamplingRatePlane') || ...
                    isempty(metadata_gcamp_m.SamplingRatePlane)

                error( ...
                    ['SamplingRatePlane missing in GCaMP metadata ' ...
                     'for rec %d.'], ...
                    m);
            end


            sampling_rate = ...
                parse_numeric_vector( ...
                    metadata_gcamp_m.SamplingRatePlane);


            if isempty(sampling_rate)

                error( ...
                    'SamplingRatePlane invalid for rec %d.', ...
                    m);
            end


            sampling_rate = ...
                sampling_rate(1);


            if ~isfinite(sampling_rate) || ...
                    sampling_rate <= 0

                error( ...
                    'SamplingRatePlane invalid for rec %d.', ...
                    m);
            end


            %======================================================%
            % SCE synchrony window
            %======================================================%

            synchronous_frames = ...
                max( ...
                    1, ...
                    round( ...
                        0.2 * ...
                        sampling_rate));


            synchronous_frames_group{m} = ...
                synchronous_frames;


            fprintf( ...
                ['Rec %d: SamplingRatePlane = %.4f Hz | ' ...
                 'synchronous_frames = %d\n'], ...
                m, ...
                sampling_rate, ...
                synchronous_frames);


            %======================================================%
            % Activity
            %======================================================%

            metrics = ...
                compute_all_basic_metrics( ...
                    data, ...
                    m, ...
                    sampling_rate, ...
                    include_electroporated_cells);


            if ~metrics.valid

                warning( ...
                    ['Skipping rec %d (%s) - ' ...
                     'données GCaMP invalides.'], ...
                    m, ...
                    gcamp_root_folders{m});

                continue;
            end


            %======================================================%
            % Network
            %======================================================%

            network_metrics = ...
                load_or_process_network_metrics_for_session( ...
                    gcamp_root_folders, ...
                    data, ...
                    m, ...
                    sampling_rate, ...
                    include_electroporated_cells);


            %======================================================%
            % SCE
            %======================================================%

            sce_metrics = ...
                load_or_process_sce_for_session( ...
                    current_animal_group, ...
                    date_group_paths, ...
                    gcamp_root_folders, ...
                    synchronous_frames_group, ...
                    data, ...
                    m, ...
                    sampling_rate);


            %======================================================%
            % GCaMP Pearson
            %======================================================%

            metrics.gcamp_plane.correlations = ...
                struct();


            metrics.gcamp_plane.correlations. ...
                cross_corr_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                cross_corr_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.correlations. ...
                max_corr_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                max_corr_gcamp_gcamp_by_plane;


            %======================================================%
            % GCaMP coupling
            %======================================================%

            metrics.gcamp_plane.coupling = ...
                struct();


            metrics.gcamp_plane.coupling. ...
                coupling_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                coupling_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                coupling_pvalue_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                coupling_pvalue_gcamp_gcamp_by_plane;


            %======================================================%
            % SCE
            %======================================================%

            metrics.gcamp_plane.SCEs = ...
                sce_metrics;


            %======================================================%
            % Electroporated
            %======================================================%

            if process_electroporated

                metrics.electroporated_plane.correlations = ...
                    struct();


                metrics.electroporated_plane.correlations. ...
                    cross_corr_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    cross_corr_gcamp_mtor_by_plane;


                metrics.electroporated_plane.correlations. ...
                    cross_corr_mtor_mtor_by_plane = ...
                    network_metrics. ...
                    cross_corr_mtor_mtor_by_plane;


                metrics.electroporated_plane.correlations. ...
                    max_corr_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    max_corr_gcamp_mtor_by_plane;


                metrics.electroporated_plane.correlations. ...
                    max_corr_mtor_mtor_by_plane = ...
                    network_metrics. ...
                    max_corr_mtor_mtor_by_plane;


                metrics.electroporated_plane.coupling = ...
                    struct();


                metrics.electroporated_plane.coupling. ...
                    coupling_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    coupling_gcamp_mtor_by_plane;


                metrics.electroporated_plane.coupling. ...
                    coupling_pvalue_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    coupling_pvalue_gcamp_mtor_by_plane;
            end


            %======================================================%
            % Stockage
            %======================================================%

            results_analysis = ...
                store_metrics_in_results_analysis( ...
                    results_analysis, ...
                    metrics, ...
                    m, ...
                    process_electroporated);


            %======================================================%
            % Table
            %======================================================%

            results_table = ...
                append_all_metrics_to_results_table( ...
                    results_table, ...
                    metrics, ...
                    current_type, ...
                    current_animal_group, ...
                    age_label, ...
                    age_number, ...
                    date_name, ...
                    session_id, ...
                    m, ...
                    process_electroporated);


        catch ME

            fprintf( ...
                'Error processing folder %s: %s\n', ...
                gcamp_root_folders{m}, ...
                ME.message);
        end
    end


    %==============================================================%
    % Tri
    %==============================================================%

    if ~isempty(results_table)

        results_table = ...
            sortrows( ...
                results_table, ...
                { ...
                    'Type', ...
                    'Animal', ...
                    'AgeNumber', ...
                    'RecordingIndex', ...
                    'Plane', ...
                    'Branch', ...
                    'Metric' ...
                });
    end
end


%==================================================================%
% INITIALISATION RESULTS_ANALYSIS
%==================================================================%

function results_analysis = ...
    init_empty_results_analysis( ...
        nRec)

    results_analysis = ...
        struct( ...
            'gcamp_plane', struct(), ...
            'electroporated_plane', struct());


    %==============================================================%
    % GCaMP activity
    %==============================================================%

    results_analysis.gcamp_plane.activity = ...
        struct();


    results_analysis.gcamp_plane.activity.ActiveCellsNumber = ...
        cell(nRec,1);


    results_analysis.gcamp_plane.activity.FrequencyPerCell = ...
        cell(nRec,1);


    results_analysis.gcamp_plane.activity.InterEventIntervals_ms = ...
        cell(nRec,1);


    results_analysis.gcamp_plane.activity.BurstRate_per_min = ...
        cell(nRec,1);


    results_analysis.gcamp_plane.activity.BurstFraction = ...
        cell(nRec,1);


    results_analysis.gcamp_plane.activity.BurstSize = ...
        cell(nRec,1);


    %==============================================================%
    % GCaMP Pearson
    %==============================================================%

    results_analysis.gcamp_plane.correlations = ...
        struct();


    results_analysis.gcamp_plane.correlations. ...
        cross_corr_gcamp_gcamp_by_plane = ...
        cell(nRec,1);


    results_analysis.gcamp_plane.correlations. ...
        max_corr_gcamp_gcamp_by_plane = ...
        cell(nRec,1);


    %==============================================================%
    % GCaMP coupling
    %==============================================================%

    results_analysis.gcamp_plane.coupling = ...
        struct();


    results_analysis.gcamp_plane.coupling. ...
        coupling_gcamp_gcamp_by_plane = ...
        cell(nRec,1);


    results_analysis.gcamp_plane.coupling. ...
        coupling_pvalue_gcamp_gcamp_by_plane = ...
        cell(nRec,1);


    %==============================================================%
    % SCEs
    %==============================================================%

    results_analysis.gcamp_plane.SCEs = ...
        struct();


    sce_fields = { ...
        'Race_gcamp', ...
        'TRace_gcamp', ...
        'sces_distances_gcamp', ...
        'RasterRace_gcamp', ...
        'sce_n_cells_threshold', ...
        'Threshold', ...
        'Frequency', ...
        'CellParticipation_percent', ...
        'Duration_ms', ...
        'Number', ...
        'RecordingDuration_min', ...
        'InterSCEIntervals_ms', ...
        'MeanCellParticipation_percent', ...
        'MedianCellParticipation_percent', ...
        'MeanDuration_ms', ...
        'MedianDuration_ms' ...
    };


    for i = 1:numel(sce_fields)

        results_analysis.gcamp_plane.SCEs.( ...
            sce_fields{i}) = ...
            cell(nRec,1);
    end


    %==============================================================%
    % Electroporated activity
    %==============================================================%

    results_analysis.electroporated_plane.activity = ...
        struct();


    results_analysis.electroporated_plane.activity.ActiveCellsNumber = ...
        cell(nRec,1);


    results_analysis.electroporated_plane.activity.FrequencyPerCell = ...
        cell(nRec,1);


    results_analysis.electroporated_plane.activity.InterEventIntervals_ms = ...
        cell(nRec,1);


    results_analysis.electroporated_plane.activity.BurstRate_per_min = ...
        cell(nRec,1);


    results_analysis.electroporated_plane.activity.BurstFraction = ...
        cell(nRec,1);


    results_analysis.electroporated_plane.activity.BurstSize = ...
        cell(nRec,1);


    %==============================================================%
    % Electroporated Pearson
    %==============================================================%

    results_analysis.electroporated_plane.correlations = ...
        struct();


    results_analysis.electroporated_plane.correlations. ...
        cross_corr_gcamp_mtor_by_plane = ...
        cell(nRec,1);


    results_analysis.electroporated_plane.correlations. ...
        cross_corr_mtor_mtor_by_plane = ...
        cell(nRec,1);


    results_analysis.electroporated_plane.correlations. ...
        max_corr_gcamp_mtor_by_plane = ...
        cell(nRec,1);


    results_analysis.electroporated_plane.correlations. ...
        max_corr_mtor_mtor_by_plane = ...
        cell(nRec,1);


    %==============================================================%
    % Electroporated coupling
    %==============================================================%

    results_analysis.electroporated_plane.coupling = ...
        struct();


    results_analysis.electroporated_plane.coupling. ...
        coupling_gcamp_mtor_by_plane = ...
        cell(nRec,1);


    results_analysis.electroporated_plane.coupling. ...
        coupling_pvalue_gcamp_mtor_by_plane = ...
        cell(nRec,1);
end


%==================================================================%
% STOCKAGE
%==================================================================%

function results_analysis = ...
    store_metrics_in_results_analysis( ...
        results_analysis, ...
        metrics, ...
        m, ...
        process_electroporated)

    %==============================================================%
    % GCaMP activity
    %==============================================================%

    A = ...
        metrics.gcamp_plane.activity;


    results_analysis.gcamp_plane.activity.ActiveCellsNumber{m} = ...
        normalize_values_by_plane(A.nCells_by_plane);


    results_analysis.gcamp_plane.activity.FrequencyPerCell{m} = ...
        normalize_values_by_plane(A.freq_by_plane);


    results_analysis.gcamp_plane.activity.InterEventIntervals_ms{m} = ...
        normalize_values_by_plane(A.intervals_ms_by_plane);


    results_analysis.gcamp_plane.activity.BurstRate_per_min{m} = ...
        normalize_values_by_plane(A.burst_rate_by_plane);


    results_analysis.gcamp_plane.activity.BurstFraction{m} = ...
        normalize_values_by_plane(A.burst_fraction_by_plane);


    results_analysis.gcamp_plane.activity.BurstSize{m} = ...
        normalize_values_by_plane(A.burst_size_by_plane);


    %==============================================================%
    % GCaMP Pearson
    %==============================================================%

    C = ...
        metrics.gcamp_plane.correlations;


    results_analysis.gcamp_plane.correlations. ...
        cross_corr_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.cross_corr_gcamp_gcamp_by_plane);


    results_analysis.gcamp_plane.correlations. ...
        max_corr_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.max_corr_gcamp_gcamp_by_plane);


    %==============================================================%
    % GCaMP coupling
    %==============================================================%

    C = ...
        metrics.gcamp_plane.coupling;


    results_analysis.gcamp_plane.coupling. ...
        coupling_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.coupling_gcamp_gcamp_by_plane);


    results_analysis.gcamp_plane.coupling. ...
        coupling_pvalue_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.coupling_pvalue_gcamp_gcamp_by_plane);


    %==============================================================%
    % SCE
    %==============================================================%

    S = ...
        metrics.gcamp_plane.SCEs;


    results_analysis.gcamp_plane.SCEs.Race_gcamp{m} = ...
        S.Race_gcamp;


    results_analysis.gcamp_plane.SCEs.TRace_gcamp{m} = ...
        S.TRace_gcamp;


    results_analysis.gcamp_plane.SCEs.sces_distances_gcamp{m} = ...
        S.sces_distances_gcamp;


    results_analysis.gcamp_plane.SCEs.RasterRace_gcamp{m} = ...
        S.RasterRace_gcamp;


    results_analysis.gcamp_plane.SCEs.sce_n_cells_threshold{m} = ...
        S.sce_n_cells_threshold;


    results_analysis.gcamp_plane.SCEs.Threshold{m} = ...
        S.sce_n_cells_threshold;


    results_analysis.gcamp_plane.SCEs.Frequency{m} = ...
        S.sce_frequency_per_min;


    results_analysis.gcamp_plane.SCEs.CellParticipation_percent{m} = ...
        S.cell_participation_percent;


    results_analysis.gcamp_plane.SCEs.Duration_ms{m} = ...
        S.duration_ms;


    results_analysis.gcamp_plane.SCEs.Number{m} = ...
        S.number;


    results_analysis.gcamp_plane.SCEs.RecordingDuration_min{m} = ...
        S.recording_duration_min;


    results_analysis.gcamp_plane.SCEs.InterSCEIntervals_ms{m} = ...
        S.inter_sce_intervals_ms;


    results_analysis.gcamp_plane.SCEs. ...
        MeanCellParticipation_percent{m} = ...
        S.mean_cell_participation_percent;


    results_analysis.gcamp_plane.SCEs. ...
        MedianCellParticipation_percent{m} = ...
        S.median_cell_participation_percent;


    results_analysis.gcamp_plane.SCEs.MeanDuration_ms{m} = ...
        S.mean_duration_ms;


    results_analysis.gcamp_plane.SCEs.MedianDuration_ms{m} = ...
        S.median_duration_ms;


    %==============================================================%
    % Sans électroporées
    %==============================================================%

    if ~process_electroporated
        return;
    end


    %==============================================================%
    % Electroporated activity
    %==============================================================%

    A = ...
        metrics.electroporated_plane.activity;


    results_analysis.electroporated_plane.activity.ActiveCellsNumber{m} = ...
        normalize_values_by_plane(A.nCells_by_plane);


    results_analysis.electroporated_plane.activity.FrequencyPerCell{m} = ...
        normalize_values_by_plane(A.freq_by_plane);


    results_analysis.electroporated_plane.activity.InterEventIntervals_ms{m} = ...
        normalize_values_by_plane(A.intervals_ms_by_plane);


    results_analysis.electroporated_plane.activity.BurstRate_per_min{m} = ...
        normalize_values_by_plane(A.burst_rate_by_plane);


    results_analysis.electroporated_plane.activity.BurstFraction{m} = ...
        normalize_values_by_plane(A.burst_fraction_by_plane);


    results_analysis.electroporated_plane.activity.BurstSize{m} = ...
        normalize_values_by_plane(A.burst_size_by_plane);


    %==============================================================%
    % Electroporated Pearson
    %==============================================================%

    C = ...
        metrics.electroporated_plane.correlations;


    results_analysis.electroporated_plane.correlations. ...
        cross_corr_gcamp_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.cross_corr_gcamp_mtor_by_plane);


    results_analysis.electroporated_plane.correlations. ...
        cross_corr_mtor_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.cross_corr_mtor_mtor_by_plane);


    results_analysis.electroporated_plane.correlations. ...
        max_corr_gcamp_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.max_corr_gcamp_mtor_by_plane);


    results_analysis.electroporated_plane.correlations. ...
        max_corr_mtor_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.max_corr_mtor_mtor_by_plane);


    %==============================================================%
    % Electroporated coupling
    %==============================================================%

    C = ...
        metrics.electroporated_plane.coupling;


    results_analysis.electroporated_plane.coupling. ...
        coupling_gcamp_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.coupling_gcamp_mtor_by_plane);


    results_analysis.electroporated_plane.coupling. ...
        coupling_pvalue_gcamp_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.coupling_pvalue_gcamp_mtor_by_plane);
end


%==================================================================%
% RESULTS TABLE
%==================================================================%

function results_table = ...
    append_all_metrics_to_results_table( ...
        results_table, ...
        metrics, ...
        current_type, ...
        current_animal_group, ...
        age_label, ...
        age_number, ...
        date_name, ...
        session_id, ...
        m, ...
        process_electroporated)

    %==============================================================%
    % GCaMP activity
    %==============================================================%

    A = ...
        metrics.gcamp_plane.activity;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "ActiveCellsNumber", ...
        A.nCells_by_plane, ...
        "cells");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "FrequencyPerCell", ...
        A.freq_by_plane, ...
        "events/min");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "InterEventIntervals", ...
        A.intervals_ms_by_plane, ...
        "ms");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "BurstRate", ...
        A.burst_rate_by_plane, ...
        "bursts/min");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "BurstFraction", ...
        A.burst_fraction_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "BurstSize", ...
        A.burst_size_by_plane, ...
        "events/burst");


    %==============================================================%
    % GCaMP Pearson
    %==============================================================%

    C = ...
        metrics.gcamp_plane.correlations;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.correlations", ...
        "MaxPearsonCorrelation_GCaMP_GCaMP", ...
        C.max_corr_gcamp_gcamp_by_plane, ...
        "correlation");


    %==============================================================%
    % GCaMP coupling
    %==============================================================%

    C = ...
        metrics.gcamp_plane.coupling;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "Coupling_GCaMP_GCaMP", ...
        C.coupling_gcamp_gcamp_by_plane, ...
        "correlation");


    results_table = ...
        append_significant_fraction_by_plane( ...
            results_table, ...
            current_type, ...
            current_animal_group, ...
            age_label, ...
            age_number, ...
            date_name, ...
            session_id, ...
            m, ...
            "gcamp_plane.coupling", ...
            "SignificantCouplingFraction_GCaMP_GCaMP", ...
            C.coupling_pvalue_gcamp_gcamp_by_plane);


    %==============================================================%
    % SCE
    %==============================================================%

    S = ...
        metrics.gcamp_plane.SCEs;


    results_table = append_session_value( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.SCEs", ...
        "Frequency", ...
        S.sce_frequency_per_min, ...
        "SCEs/min");


    results_table = append_session_value( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.SCEs", ...
        "CellParticipation", ...
        S.cell_participation_percent, ...
        "%");


    results_table = append_session_value( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.SCEs", ...
        "Duration", ...
        S.duration_ms, ...
        "ms");


    %==============================================================%
    % Sans électroporées
    %==============================================================%

    if ~process_electroporated
        return;
    end


    %==============================================================%
    % Electroporated activity
    %==============================================================%

    A = ...
        metrics.electroporated_plane.activity;


    if A.valid

        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "ActiveCellsNumber", ...
            A.nCells_by_plane, ...
            "cells");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "FrequencyPerCell", ...
            A.freq_by_plane, ...
            "events/min");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "InterEventIntervals", ...
            A.intervals_ms_by_plane, ...
            "ms");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "BurstRate", ...
            A.burst_rate_by_plane, ...
            "bursts/min");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "BurstFraction", ...
            A.burst_fraction_by_plane, ...
            "fraction");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "BurstSize", ...
            A.burst_size_by_plane, ...
            "events/burst");
    end


    %==============================================================%
    % Electroporated Pearson
    %==============================================================%

    C = ...
        metrics.electroporated_plane.correlations;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.correlations", ...
        "MaxPearsonCorrelation_GCaMP_mTOR", ...
        C.max_corr_gcamp_mtor_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.correlations", ...
        "MaxPearsonCorrelation_mTOR_mTOR", ...
        C.max_corr_mtor_mtor_by_plane, ...
        "correlation");


    %==============================================================%
    % Electroporated coupling
    %==============================================================%

    C = ...
        metrics.electroporated_plane.coupling;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.coupling", ...
        "Coupling_GCaMP_mTOR", ...
        C.coupling_gcamp_mtor_by_plane, ...
        "correlation");


    results_table = ...
        append_significant_fraction_by_plane( ...
            results_table, ...
            current_type, ...
            current_animal_group, ...
            age_label, ...
            age_number, ...
            date_name, ...
            session_id, ...
            m, ...
            "electroporated_plane.coupling", ...
            "SignificantCouplingFraction_GCaMP_mTOR", ...
            C.coupling_pvalue_gcamp_mtor_by_plane);
end


%==================================================================%
% FRACTION DE COUPLINGS SIGNIFICATIFS
%==================================================================%

function results_table = ...
    append_significant_fraction_by_plane( ...
        results_table, ...
        current_type, ...
        animal_id, ...
        age_label, ...
        age_number, ...
        date_name, ...
        session_id, ...
        recording_index, ...
        branch_name, ...
        metric_name, ...
        pvalues_by_plane)

    pvalues_by_plane = ...
        normalize_values_by_plane( ...
            pvalues_by_plane);


    for p = 1:numel(pvalues_by_plane)

        values = ...
            pvalues_by_plane{p};


        if isempty(values) || ...
                ~isnumeric(values)

            continue;
        end


        values = ...
            double(values(:));


        values = ...
            values(isfinite(values));


        n_values = ...
            numel(values);


        if n_values == 0
            continue;
        end


        fraction_significant = ...
            mean( ...
                values < 0.05);


        row = ...
            make_results_row( ...
                current_type, ...
                animal_id, ...
                age_label, ...
                age_number, ...
                date_name, ...
                session_id, ...
                recording_index, ...
                p - 1, ...
                branch_name, ...
                metric_name, ...
                fraction_significant, ...
                n_values, ...
                "fraction");


        results_table = ...
            [ ...
                results_table; ...
                row ...
            ]; %#ok<AGROW>
    end
end


%==================================================================%
% TABLE VIDE
%==================================================================%

function results_table = ...
    init_results_table()

    results_table = ...
        table( ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            'VariableNames', { ...
                'Type', ...
                'Animal', ...
                'Age', ...
                'AgeNumber', ...
                'Date', ...
                'SessionID', ...
                'RecordingIndex', ...
                'Plane', ...
                'Branch', ...
                'Metric', ...
                'Value', ...
                'N', ...
                'Unit'});
end


%==================================================================%
% AJOUT PAR PLAN
%==================================================================%

function results_table = ...
    append_values_by_plane( ...
        results_table, ...
        current_type, ...
        animal_id, ...
        age_label, ...
        age_number, ...
        date_name, ...
        session_id, ...
        recording_index, ...
        branch_name, ...
        metric_name, ...
        values_by_plane, ...
        unit_name)

    values_by_plane = ...
        normalize_values_by_plane( ...
            values_by_plane);


    for p = 1:numel(values_by_plane)

        [metric_value, n_values] = ...
            summarize_numeric_values( ...
                values_by_plane{p});


        if ~isfinite(metric_value)
            continue;
        end


        row = ...
            make_results_row( ...
                current_type, ...
                animal_id, ...
                age_label, ...
                age_number, ...
                date_name, ...
                session_id, ...
                recording_index, ...
                p - 1, ...
                branch_name, ...
                metric_name, ...
                metric_value, ...
                n_values, ...
                unit_name);


        results_table = ...
            [ ...
                results_table; ...
                row ...
            ]; %#ok<AGROW>
    end
end


%==================================================================%
% AJOUT SESSION
%==================================================================%

function results_table = ...
    append_session_value( ...
        results_table, ...
        current_type, ...
        animal_id, ...
        age_label, ...
        age_number, ...
        date_name, ...
        session_id, ...
        recording_index, ...
        branch_name, ...
        metric_name, ...
        values, ...
        unit_name)

    [metric_value, n_values] = ...
        summarize_numeric_values( ...
            values);


    if ~isfinite(metric_value)
        return;
    end


    row = ...
        make_results_row( ...
            current_type, ...
            animal_id, ...
            age_label, ...
            age_number, ...
            date_name, ...
            session_id, ...
            recording_index, ...
            NaN, ...
            branch_name, ...
            metric_name, ...
            metric_value, ...
            n_values, ...
            unit_name);


    results_table = ...
        [ ...
            results_table; ...
            row ...
        ];
end


%==================================================================%
% ROW
%==================================================================%

function row = ...
    make_results_row( ...
        current_type, ...
        animal_id, ...
        age_label, ...
        age_number, ...
        date_name, ...
        session_id, ...
        recording_index, ...
        plane_number, ...
        branch_name, ...
        metric_name, ...
        metric_value, ...
        n_values, ...
        unit_name)

    row = ...
        table( ...
            string(current_type), ...
            string(animal_id), ...
            string(age_label), ...
            double(age_number), ...
            string(date_name), ...
            string(session_id), ...
            double(recording_index), ...
            double(plane_number), ...
            string(branch_name), ...
            string(metric_name), ...
            double(metric_value), ...
            double(n_values), ...
            string(unit_name), ...
            'VariableNames', { ...
                'Type', ...
                'Animal', ...
                'Age', ...
                'AgeNumber', ...
                'Date', ...
                'SessionID', ...
                'RecordingIndex', ...
                'Plane', ...
                'Branch', ...
                'Metric', ...
                'Value', ...
                'N', ...
                'Unit'});
end


%==================================================================%
% NORMALISATION
%==================================================================%

function values_by_plane = ...
    normalize_values_by_plane( ...
        values)

    if isempty(values)

        values_by_plane = ...
            {};


    elseif iscell(values)

        values_by_plane = ...
            values(:).';


    elseif isnumeric(values) || ...
            islogical(values)

        values_by_plane = ...
            {values};


    else

        values_by_plane = ...
            {};
    end
end


%==================================================================%
% RÉSUMÉ
%==================================================================%

function [mean_value, n_values] = ...
    summarize_numeric_values( ...
        values)

    mean_value = ...
        NaN;


    n_values = ...
        0;


    if isempty(values)
        return;
    end


    if iscell(values)

        combined = [];


        for i = 1:numel(values)

            current = ...
                values{i};


            if isnumeric(current) || ...
                    islogical(current)

                combined = ...
                    [ ...
                        combined; ...
                        double(current(:)) ...
                    ]; %#ok<AGROW>
            end
        end


        values = ...
            combined;
    end


    if ~(isnumeric(values) || ...
            islogical(values))

        return;
    end


    values = ...
        double(values(:));


    values = ...
        values(isfinite(values));


    n_values = ...
        numel(values);


    if n_values > 0

        mean_value = ...
            mean( ...
                values, ...
                'omitnan');
    end
end


%==================================================================%
% DATE
%==================================================================%

function date_name = ...
    get_date_name_from_path( ...
        date_group_paths, ...
        m)

    date_name = ...
        "";


    if isempty(date_group_paths) || ...
            numel(date_group_paths) < m || ...
            isempty(date_group_paths{m})

        return;
    end


    [~, current_date] = ...
        fileparts( ...
            date_group_paths{m});


    date_name = ...
        string(current_date);
end


%==================================================================%
% AGE
%==================================================================%

function age_label = ...
    get_age_for_recording( ...
        current_ages, ...
        m)

    age_label = ...
        "";


    if isempty(current_ages)
        return;
    end


    if iscell(current_ages)

        if numel(current_ages) >= m

            age_label = ...
                string(current_ages{m});
        end


    elseif isstring(current_ages)

        if numel(current_ages) >= m

            age_label = ...
                current_ages(m);


        elseif isscalar(current_ages)

            age_label = ...
                current_ages;
        end


    elseif ischar(current_ages)

        age_label = ...
            string(current_ages);


    elseif isnumeric(current_ages)

        if numel(current_ages) >= m

            age_label = ...
                "P" + ...
                string(current_ages(m));


        elseif isscalar(current_ages)

            age_label = ...
                "P" + ...
                string(current_ages);
        end
    end
end


function age_number = ...
    extract_age_number( ...
        age_label)

    age_number = ...
        NaN;


    if strlength(string(age_label)) == 0
        return;
    end


    token = ...
        regexp( ...
            char(string(age_label)), ...
            '[-+]?\d*\.?\d+', ...
            'match', ...
            'once');


    if ~isempty(token)

        age_number = ...
            str2double(token);
    end
end


%==================================================================%
% METADATA
%==================================================================%

function metadata_m = ...
    get_metadata_for_record( ...
        metadata, ...
        idx)

    metadata_m = ...
        struct();


    if isempty(metadata) || ...
            ~isstruct(metadata)

        return;
    end


    fields = ...
        fieldnames(metadata);


    for f = 1:numel(fields)

        field = ...
            fields{f};


        value = ...
            metadata.(field);


        if isstruct(value)

            metadata_m.(field) = ...
                get_metadata_for_record( ...
                    value, ...
                    idx);


        elseif iscell(value)

            if numel(value) >= idx

                metadata_m.(field) = ...
                    value{idx};

            else

                metadata_m.(field) = ...
                    [];
            end


        else

            metadata_m.(field) = ...
                value;
        end
    end
end


%==================================================================%
% NUMERIC PARSING
%==================================================================%

function v = ...
    parse_numeric_vector( ...
        x)

    v = [];


    if isempty(x)
        return;
    end


    if isnumeric(x)

        v = ...
            double(x(:).');


        v = ...
            v(isfinite(v));

        return;
    end


    if isstring(x)

        x = ...
            cellstr(x);
    end


    if ischar(x)

        v = ...
            sscanf( ...
                x, ...
                '%f').';


        v = ...
            double(v(:).');


        v = ...
            v(isfinite(v));

        return;
    end


    if iscell(x)

        tmp = [];


        for i = 1:numel(x)

            vi = ...
                parse_numeric_vector( ...
                    x{i});


            if ~isempty(vi)

                tmp = ...
                    [ ...
                        tmp, ...
                        vi ...
                    ]; %#ok<AGROW>
            end
        end


        v = ...
            tmp;


        v = ...
            v(isfinite(v));
    end
end