function [results_analysis, results_table] = compute_export_basic_metrics( ...
    current_type, ...
    current_animal_group, ...
    current_ages, ...
    gcamp_root_folders, ...
    date_group_paths, ...
    synchronous_frames_group, ...
    data, ...
    metadata, ...
    include_blue_cells)

%COMPUTE_EXPORT_BASIC_METRICS
%
% Fonction d'orchestration.
%
% Pour chaque recording :
%   1) récupère les métadonnées ;
%   2) calcule les métriques d'activité ;
%   3) charge ou calcule les métriques réseau ;
%   4) charge ou calcule les SCEs ;
%   5) assemble toutes les métriques ;
%   6) remplit results_analysis ;
%   7) construit results_table.


    %==============================================================%
    % Initialisation
    %==============================================================%
    nRec = ...
        numel(gcamp_root_folders);


    if nargin < 9 || ...
            isempty(include_blue_cells)

        include_blue_cells = ...
            '1';
    end


    include_blue_cells = ...
        char(string(include_blue_cells));


    process_blue = ...
        strcmp( ...
            include_blue_cells, ...
            '1');


    current_type = ...
        string(current_type);


    current_animal_group = ...
        string(current_animal_group);


    results_analysis = ...
        init_empty_results_analysis( ...
            nRec);


    results_table = ...
        init_results_table();


    %==============================================================%
    % Boucle recordings
    %==============================================================%
    for m = 1:nRec

        date_name = ...
            get_date_name_from_path( ...
                date_group_paths, ...
                m);


        age_label = ...
            get_age_for_recording( ...
                current_ages, ...
                m);


        age_number = ...
            extract_age_number( ...
                age_label);


        session_id = ...
            current_animal_group + ...
            "_" + ...
            date_name + ...
            "_rec" + ...
            string(m);


        try

            %======================================================%
            % Sampling rate
            %======================================================%
            sampling_rate = ...
                get_metadata_value( ...
                    metadata, ...
                    'SamplingRatePlane', ...
                    m);


            sampling_rate = ...
                parse_numeric_vector( ...
                    sampling_rate);


            if isempty(sampling_rate)

                error( ...
                    'SamplingRatePlane vide pour rec %d', ...
                    m);
            end


            sampling_rate = ...
                sampling_rate(1);


            %======================================================%
            % 1) Activity metrics
            %======================================================%
            metrics = ...
                compute_all_basic_metrics( ...
                    data, ...
                    m, ...
                    sampling_rate, ...
                    include_blue_cells);


            %======================================================%
            % Recording invalide
            %======================================================%
            if ~metrics.valid

                warning( ...
                    ['Skipping rec %d (%s) - ' ...
                     'données GCaMP invalides.'], ...
                    m, ...
                    gcamp_root_folders{m});

                continue;
            end


            %======================================================%
            % 2) Network correlations + coupling
            %======================================================%
            network_metrics = ...
                load_or_process_network_metrics_for_session( ...
                    gcamp_root_folders, ...
                    data, ...
                    m, ...
                    sampling_rate, ...
                    include_blue_cells);


            %======================================================%
            % 3) SCEs
            %======================================================%
            sce_metrics = ...
                load_or_process_sce_for_session( ...
                    current_animal_group, ...
                    date_group_paths, ...
                    gcamp_root_folders, ...
                    synchronous_frames_group, ...
                    data, ...
                    m, ...
                    sampling_rate);


            %======================================================%
            % 4) Assemble GCaMP correlations
            %======================================================%
            metrics.gcamp_plane.correlations = ...
                struct();


            metrics.gcamp_plane.correlations. ...
                cross_corr_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                cross_corr_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.correlations. ...
                max_corr_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                max_corr_gcamp_gcamp_by_plane;


            %======================================================%
            % 5) Assemble GCaMP functional coupling
            %======================================================%
            metrics.gcamp_plane.coupling = ...
                struct();


            metrics.gcamp_plane.coupling. ...
                population_corr_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                population_corr_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                peak_coupling_fraction_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                peak_coupling_fraction_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                peak_coupling_shuffle_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                peak_coupling_shuffle_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                peak_coupling_excess_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                peak_coupling_excess_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                peak_coupling_ratio_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                peak_coupling_ratio_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                max_lagged_corr_gcamp_gcamp_population_by_plane = ...
                network_metrics. ...
                max_lagged_corr_gcamp_gcamp_population_by_plane;


            metrics.gcamp_plane.coupling. ...
                lag_to_gcamp_gcamp_population_ms_by_plane = ...
                network_metrics. ...
                lag_to_gcamp_gcamp_population_ms_by_plane;


            %======================================================%
            % 6) Assemble SCEs
            %======================================================%
            metrics.gcamp_plane.SCEs = ...
                sce_metrics;


            %======================================================%
            % 7) Assemble blue/mTOR metrics
            %======================================================%
            if process_blue

                %--------------------------------------------------%
                % Correlations
                %--------------------------------------------------%
                metrics.blue_plane.correlations = ...
                    struct();


                metrics.blue_plane.correlations. ...
                    cross_corr_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    cross_corr_gcamp_mtor_by_plane;


                metrics.blue_plane.correlations. ...
                    cross_corr_mtor_mtor_by_plane = ...
                    network_metrics. ...
                    cross_corr_mtor_mtor_by_plane;


                metrics.blue_plane.correlations. ...
                    max_corr_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    max_corr_gcamp_mtor_by_plane;


                metrics.blue_plane.correlations. ...
                    max_corr_mtor_mtor_by_plane = ...
                    network_metrics. ...
                    max_corr_mtor_mtor_by_plane;


                metrics.blue_plane.correlations. ...
                    median_corr_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    median_corr_gcamp_mtor_by_plane;


                %--------------------------------------------------%
                % Coupling
                %--------------------------------------------------%
                metrics.blue_plane.coupling = ...
                    struct();


                metrics.blue_plane.coupling. ...
                    population_corr_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    population_corr_gcamp_mtor_by_plane;


                metrics.blue_plane.coupling. ...
                    peak_coupling_fraction_by_plane = ...
                    network_metrics. ...
                    peak_coupling_fraction_by_plane;


                metrics.blue_plane.coupling. ...
                    peak_coupling_shuffle_by_plane = ...
                    network_metrics. ...
                    peak_coupling_shuffle_by_plane;


                metrics.blue_plane.coupling. ...
                    peak_coupling_excess_by_plane = ...
                    network_metrics. ...
                    peak_coupling_excess_by_plane;


                metrics.blue_plane.coupling. ...
                    peak_coupling_ratio_by_plane = ...
                    network_metrics. ...
                    peak_coupling_ratio_by_plane;


                metrics.blue_plane.coupling. ...
                    max_lagged_corr_gcamp_population_by_plane = ...
                    network_metrics. ...
                    max_lagged_corr_gcamp_population_by_plane;


                metrics.blue_plane.coupling. ...
                    lag_to_gcamp_population_ms_by_plane = ...
                    network_metrics. ...
                    lag_to_gcamp_population_ms_by_plane;
            end


            %======================================================%
            % 8) Stockage dans results_analysis
            %======================================================%
            results_analysis = ...
                store_metrics_in_results_analysis( ...
                    results_analysis, ...
                    metrics, ...
                    m, ...
                    process_blue);


            %======================================================%
            % 9) Export table longue
            %======================================================%
            results_table = ...
                append_all_metrics_to_results_table( ...
                    results_table, ...
                    metrics, ...
                    current_type, ...
                    current_animal_group, ...
                    age_label, ...
                    age_number, ...
                    date_name, ...
                    session_id, ...
                    m, ...
                    process_blue);


        catch ME

            fprintf( ...
                'Error processing rec %d: %s\n', ...
                m, ...
                ME.message);
        end
    end


    %==============================================================%
    % Tri final
    %==============================================================%
    if ~isempty(results_table)

        results_table = ...
            sortrows( ...
                results_table, ...
                { ...
                    'Type', ...
                    'Animal', ...
                    'AgeNumber', ...
                    'RecordingIndex', ...
                    'Plane', ...
                    'Branch', ...
                    'Metric' ...
                });
    end
end


function results_analysis = ...
    init_empty_results_analysis( ...
        nRec)

    results_analysis = ...
        struct( ...
            'gcamp_plane', struct(), ...
            'blue_plane', struct());


    %==============================================================%
    % GCaMP activity
    %==============================================================%
    results_analysis.gcamp_plane.activity = ...
        struct();


    results_analysis.gcamp_plane.activity.FrequencyPerCell = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.activity.InterEventIntervals_ms = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.activity.BurstRate_per_min = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.activity.BurstFraction = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.activity.BurstSize = ...
        cell(nRec, 1);


    %==============================================================%
    % GCaMP correlations
    %==============================================================%
    results_analysis.gcamp_plane.correlations = ...
        struct();


    results_analysis.gcamp_plane.correlations. ...
        cross_corr_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.correlations. ...
        max_corr_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    %==============================================================%
    % GCaMP functional coupling
    %==============================================================%
    results_analysis.gcamp_plane.coupling = ...
        struct();


    results_analysis.gcamp_plane.coupling. ...
        population_corr_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_fraction_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_shuffle_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_excess_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_ratio_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        max_lagged_corr_gcamp_gcamp_population_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        lag_to_gcamp_gcamp_population_ms_by_plane = ...
        cell(nRec, 1);


    %==============================================================%
    % GCaMP SCEs
    %==============================================================%
    results_analysis.gcamp_plane.SCEs = ...
        struct();


    results_analysis.gcamp_plane.SCEs.Race_gcamp = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.TRace_gcamp = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.sces_distances_gcamp = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.RasterRace_gcamp = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.sce_n_cells_threshold = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.Threshold = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.Frequency = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.CellParticipation_percent = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.Duration_ms = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.Number = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.RecordingDuration_min = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.InterSCEIntervals_ms = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs. ...
        MeanCellParticipation_percent = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs. ...
        MedianCellParticipation_percent = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.MeanDuration_ms = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.MedianDuration_ms = ...
        cell(nRec, 1);


    %==============================================================%
    % Blue/mTOR activity
    %==============================================================%
    results_analysis.blue_plane.activity = ...
        struct();


    results_analysis.blue_plane.activity.FrequencyPerCell = ...
        cell(nRec, 1);


    results_analysis.blue_plane.activity.InterEventIntervals_ms = ...
        cell(nRec, 1);


    results_analysis.blue_plane.activity.BurstRate_per_min = ...
        cell(nRec, 1);


    results_analysis.blue_plane.activity.BurstFraction = ...
        cell(nRec, 1);


    results_analysis.blue_plane.activity.BurstSize = ...
        cell(nRec, 1);


    %==============================================================%
    % Blue/mTOR correlations
    %==============================================================%
    results_analysis.blue_plane.correlations = ...
        struct();


    results_analysis.blue_plane.correlations. ...
        cross_corr_gcamp_mtor_by_plane = ...
        cell(nRec, 1);


    results_analysis.blue_plane.correlations. ...
        cross_corr_mtor_mtor_by_plane = ...
        cell(nRec, 1);


    results_analysis.blue_plane.correlations. ...
        max_corr_gcamp_mtor_by_plane = ...
        cell(nRec, 1);


    results_analysis.blue_plane.correlations. ...
        max_corr_mtor_mtor_by_plane = ...
        cell(nRec, 1);


    results_analysis.blue_plane.correlations. ...
        median_corr_gcamp_mtor_by_plane = ...
        cell(nRec, 1);


    %==============================================================%
    % Blue/mTOR coupling
    %==============================================================%
    results_analysis.blue_plane.coupling = ...
        struct();


    results_analysis.blue_plane.coupling. ...
        population_corr_gcamp_mtor_by_plane = ...
        cell(nRec, 1);


    results_analysis.blue_plane.coupling. ...
        peak_coupling_fraction_by_plane = ...
        cell(nRec, 1);


    results_analysis.blue_plane.coupling. ...
        peak_coupling_shuffle_by_plane = ...
        cell(nRec, 1);


    results_analysis.blue_plane.coupling. ...
        peak_coupling_excess_by_plane = ...
        cell(nRec, 1);


    results_analysis.blue_plane.coupling. ...
        peak_coupling_ratio_by_plane = ...
        cell(nRec, 1);


    results_analysis.blue_plane.coupling. ...
        max_lagged_corr_gcamp_population_by_plane = ...
        cell(nRec, 1);


    results_analysis.blue_plane.coupling. ...
        lag_to_gcamp_population_ms_by_plane = ...
        cell(nRec, 1);
end


function results_analysis = ...
    store_metrics_in_results_analysis( ...
        results_analysis, ...
        metrics, ...
        m, ...
        process_blue)

    %==============================================================%
    % GCaMP activity
    %==============================================================%
    A = ...
        metrics.gcamp_plane.activity;


    results_analysis.gcamp_plane.activity.FrequencyPerCell{m} = ...
        A.freq_by_plane;


    results_analysis.gcamp_plane.activity.InterEventIntervals_ms{m} = ...
        A.intervals_ms_by_plane;


    results_analysis.gcamp_plane.activity.BurstRate_per_min{m} = ...
        A.burst_rate_by_plane;


    results_analysis.gcamp_plane.activity.BurstFraction{m} = ...
        A.burst_fraction_by_plane;


    results_analysis.gcamp_plane.activity.BurstSize{m} = ...
        A.burst_size_by_plane;


    %==============================================================%
    % GCaMP correlations
    %==============================================================%
    C = ...
        metrics.gcamp_plane.correlations;


    results_analysis.gcamp_plane.correlations. ...
        cross_corr_gcamp_gcamp_by_plane{m} = ...
        C.cross_corr_gcamp_gcamp_by_plane;


    results_analysis.gcamp_plane.correlations. ...
        max_corr_gcamp_gcamp_by_plane{m} = ...
        C.max_corr_gcamp_gcamp_by_plane;


    %==============================================================%
    % GCaMP functional coupling
    %==============================================================%
    C = ...
        metrics.gcamp_plane.coupling;


    results_analysis.gcamp_plane.coupling. ...
        population_corr_gcamp_gcamp_by_plane{m} = ...
        C.population_corr_gcamp_gcamp_by_plane;


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_fraction_gcamp_gcamp_by_plane{m} = ...
        C.peak_coupling_fraction_gcamp_gcamp_by_plane;


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_shuffle_gcamp_gcamp_by_plane{m} = ...
        C.peak_coupling_shuffle_gcamp_gcamp_by_plane;


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_excess_gcamp_gcamp_by_plane{m} = ...
        C.peak_coupling_excess_gcamp_gcamp_by_plane;


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_ratio_gcamp_gcamp_by_plane{m} = ...
        C.peak_coupling_ratio_gcamp_gcamp_by_plane;


    results_analysis.gcamp_plane.coupling. ...
        max_lagged_corr_gcamp_gcamp_population_by_plane{m} = ...
        C.max_lagged_corr_gcamp_gcamp_population_by_plane;


    results_analysis.gcamp_plane.coupling. ...
        lag_to_gcamp_gcamp_population_ms_by_plane{m} = ...
        C.lag_to_gcamp_gcamp_population_ms_by_plane;


    %==============================================================%
    % GCaMP SCEs
    %==============================================================%
    S = ...
        metrics.gcamp_plane.SCEs;


    results_analysis.gcamp_plane.SCEs.Race_gcamp{m} = ...
        S.Race_gcamp;


    results_analysis.gcamp_plane.SCEs.TRace_gcamp{m} = ...
        S.TRace_gcamp;


    results_analysis.gcamp_plane.SCEs.sces_distances_gcamp{m} = ...
        S.sces_distances_gcamp;


    results_analysis.gcamp_plane.SCEs.RasterRace_gcamp{m} = ...
        S.RasterRace_gcamp;


    results_analysis.gcamp_plane.SCEs.sce_n_cells_threshold{m} = ...
        S.sce_n_cells_threshold;


    results_analysis.gcamp_plane.SCEs.Threshold{m} = ...
        S.sce_n_cells_threshold;


    results_analysis.gcamp_plane.SCEs.Frequency{m} = ...
        S.sce_frequency_per_min;


    results_analysis.gcamp_plane.SCEs.CellParticipation_percent{m} = ...
        S.cell_participation_percent;


    results_analysis.gcamp_plane.SCEs.Duration_ms{m} = ...
        S.duration_ms;


    results_analysis.gcamp_plane.SCEs.Number{m} = ...
        S.number;


    results_analysis.gcamp_plane.SCEs.RecordingDuration_min{m} = ...
        S.recording_duration_min;


    results_analysis.gcamp_plane.SCEs.InterSCEIntervals_ms{m} = ...
        S.inter_sce_intervals_ms;


    results_analysis.gcamp_plane.SCEs. ...
        MeanCellParticipation_percent{m} = ...
        S.mean_cell_participation_percent;


    results_analysis.gcamp_plane.SCEs. ...
        MedianCellParticipation_percent{m} = ...
        S.median_cell_participation_percent;


    results_analysis.gcamp_plane.SCEs.MeanDuration_ms{m} = ...
        S.mean_duration_ms;


    results_analysis.gcamp_plane.SCEs.MedianDuration_ms{m} = ...
        S.median_duration_ms;


    %==============================================================%
    % Sans blue : arrêt ici
    %==============================================================%
    if ~process_blue
        return;
    end


    %==============================================================%
    % Blue activity
    %==============================================================%
    A = ...
        metrics.blue_plane.activity;


    results_analysis.blue_plane.activity.FrequencyPerCell{m} = ...
        A.freq_by_plane;


    results_analysis.blue_plane.activity.InterEventIntervals_ms{m} = ...
        A.intervals_ms_by_plane;


    results_analysis.blue_plane.activity.BurstRate_per_min{m} = ...
        A.burst_rate_by_plane;


    results_analysis.blue_plane.activity.BurstFraction{m} = ...
        A.burst_fraction_by_plane;


    results_analysis.blue_plane.activity.BurstSize{m} = ...
        A.burst_size_by_plane;


    %==============================================================%
    % Blue correlations
    %==============================================================%
    C = ...
        metrics.blue_plane.correlations;


    results_analysis.blue_plane.correlations. ...
        cross_corr_gcamp_mtor_by_plane{m} = ...
        C.cross_corr_gcamp_mtor_by_plane;


    results_analysis.blue_plane.correlations. ...
        cross_corr_mtor_mtor_by_plane{m} = ...
        C.cross_corr_mtor_mtor_by_plane;


    results_analysis.blue_plane.correlations. ...
        max_corr_gcamp_mtor_by_plane{m} = ...
        C.max_corr_gcamp_mtor_by_plane;


    results_analysis.blue_plane.correlations. ...
        max_corr_mtor_mtor_by_plane{m} = ...
        C.max_corr_mtor_mtor_by_plane;


    results_analysis.blue_plane.correlations. ...
        median_corr_gcamp_mtor_by_plane{m} = ...
        C.median_corr_gcamp_mtor_by_plane;


    %==============================================================%
    % Blue coupling
    %==============================================================%
    C = ...
        metrics.blue_plane.coupling;


    results_analysis.blue_plane.coupling. ...
        population_corr_gcamp_mtor_by_plane{m} = ...
        C.population_corr_gcamp_mtor_by_plane;


    results_analysis.blue_plane.coupling. ...
        peak_coupling_fraction_by_plane{m} = ...
        C.peak_coupling_fraction_by_plane;


    results_analysis.blue_plane.coupling. ...
        peak_coupling_shuffle_by_plane{m} = ...
        C.peak_coupling_shuffle_by_plane;


    results_analysis.blue_plane.coupling. ...
        peak_coupling_excess_by_plane{m} = ...
        C.peak_coupling_excess_by_plane;


    results_analysis.blue_plane.coupling. ...
        peak_coupling_ratio_by_plane{m} = ...
        C.peak_coupling_ratio_by_plane;


    results_analysis.blue_plane.coupling. ...
        max_lagged_corr_gcamp_population_by_plane{m} = ...
        C.max_lagged_corr_gcamp_population_by_plane;


    results_analysis.blue_plane.coupling. ...
        lag_to_gcamp_population_ms_by_plane{m} = ...
        C.lag_to_gcamp_population_ms_by_plane;
end


function results_table = ...
    append_all_metrics_to_results_table( ...
        results_table, ...
        metrics, ...
        current_type, ...
        current_animal_group, ...
        age_label, ...
        age_number, ...
        date_name, ...
        session_id, ...
        m, ...
        process_blue)

    %==============================================================%
    % GCaMP activity
    %==============================================================%
    A = ...
        metrics.gcamp_plane.activity;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "ActiveCellsNumber", ...
        A.nCells_by_plane, ...
        "cells");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "FrequencyPerCell", ...
        A.freq_by_plane, ...
        "events/min");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "InterEventIntervals", ...
        A.intervals_ms_by_plane, ...
        "ms");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "BurstRate", ...
        A.burst_rate_by_plane, ...
        "bursts/min");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "BurstFraction", ...
        A.burst_fraction_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "BurstSize", ...
        A.burst_size_by_plane, ...
        "events/burst");


    %==============================================================%
    % GCaMP correlations
    %==============================================================%
    C = ...
        metrics.gcamp_plane.correlations;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.correlations", ...
        "PairwiseCorrelation_GCaMP_GCaMP", ...
        C.max_corr_gcamp_gcamp_by_plane, ...
        "correlation");


    %==============================================================%
    % GCaMP functional coupling
    %==============================================================%
    C = ...
        metrics.gcamp_plane.coupling;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "PopulationCorrelation_GCaMP_GCaMP", ...
        C.population_corr_gcamp_gcamp_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "PeakCouplingFraction_GCaMP_GCaMP", ...
        C.peak_coupling_fraction_gcamp_gcamp_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "PeakCouplingShuffle_GCaMP_GCaMP", ...
        C.peak_coupling_shuffle_gcamp_gcamp_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "PeakCouplingExcess_GCaMP_GCaMP", ...
        C.peak_coupling_excess_gcamp_gcamp_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "PeakCouplingRatio_GCaMP_GCaMP", ...
        C.peak_coupling_ratio_gcamp_gcamp_by_plane, ...
        "ratio");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "MaxLaggedCorrelation_GCaMP_GCaMP", ...
        C.max_lagged_corr_gcamp_gcamp_population_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "LagToGCaMPPopulation_GCaMP_GCaMP", ...
        C.lag_to_gcamp_gcamp_population_ms_by_plane, ...
        "ms");


    %==============================================================%
    % SCEs
    %==============================================================%
    S = ...
        metrics.gcamp_plane.SCEs;


    results_table = append_session_value( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.SCEs", ...
        "Frequency", ...
        S.sce_frequency_per_min, ...
        "SCEs/min");


    results_table = append_session_value( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.SCEs", ...
        "CellParticipation", ...
        S.cell_participation_percent, ...
        "%");


    results_table = append_session_value( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.SCEs", ...
        "Duration", ...
        S.duration_ms, ...
        "ms");


    %==============================================================%
    % Sans blue
    %==============================================================%
    if ~process_blue
        return;
    end


    %==============================================================%
    % Blue activity
    %==============================================================%
    A = ...
        metrics.blue_plane.activity;


    if A.valid

        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "blue_plane.activity", ...
            "ActiveCellsNumber", ...
            A.nCells_by_plane, ...
            "cells");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "blue_plane.activity", ...
            "FrequencyPerCell", ...
            A.freq_by_plane, ...
            "events/min");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "blue_plane.activity", ...
            "InterEventIntervals", ...
            A.intervals_ms_by_plane, ...
            "ms");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "blue_plane.activity", ...
            "BurstRate", ...
            A.burst_rate_by_plane, ...
            "bursts/min");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "blue_plane.activity", ...
            "BurstFraction", ...
            A.burst_fraction_by_plane, ...
            "fraction");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "blue_plane.activity", ...
            "BurstSize", ...
            A.burst_size_by_plane, ...
            "events/burst");
    end


    %==============================================================%
    % Blue correlations
    %==============================================================%
    C = ...
        metrics.blue_plane.correlations;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "blue_plane.correlations", ...
        "PairwiseCorrelation_GCaMP_mTOR", ...
        C.max_corr_gcamp_mtor_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "blue_plane.correlations", ...
        "PairwiseCorrelation_mTOR_mTOR", ...
        C.max_corr_mtor_mtor_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "blue_plane.correlations", ...
        "MedianCorrelation_GCaMP_mTOR", ...
        C.median_corr_gcamp_mtor_by_plane, ...
        "correlation");


    %==============================================================%
    % Blue coupling
    %==============================================================%
    C = ...
        metrics.blue_plane.coupling;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "blue_plane.coupling", ...
        "PopulationCorrelation_GCaMP_mTOR", ...
        C.population_corr_gcamp_mtor_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "blue_plane.coupling", ...
        "PeakCouplingFraction_GCaMP_mTOR", ...
        C.peak_coupling_fraction_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "blue_plane.coupling", ...
        "PeakCouplingShuffle_GCaMP_mTOR", ...
        C.peak_coupling_shuffle_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "blue_plane.coupling", ...
        "PeakCouplingExcess_GCaMP_mTOR", ...
        C.peak_coupling_excess_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "blue_plane.coupling", ...
        "PeakCouplingRatio_GCaMP_mTOR", ...
        C.peak_coupling_ratio_by_plane, ...
        "ratio");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "blue_plane.coupling", ...
        "MaxLaggedCorrelation_GCaMP_mTOR", ...
        C.max_lagged_corr_gcamp_population_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "blue_plane.coupling", ...
        "LagToGCaMPPopulation_GCaMP_mTOR", ...
        C.lag_to_gcamp_population_ms_by_plane, ...
        "ms");
end


function results_table = init_results_table()

    results_table = ...
        table( ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            'VariableNames', { ...
                'Type', ...
                'Animal', ...
                'Age', ...
                'AgeNumber', ...
                'Date', ...
                'SessionID', ...
                'RecordingIndex', ...
                'Plane', ...
                'Branch', ...
                'Metric', ...
                'Value', ...
                'N', ...
                'Unit'});
end


function results_table = append_values_by_plane( ...
    results_table, ...
    current_type, ...
    animal_id, ...
    age_label, ...
    age_number, ...
    date_name, ...
    session_id, ...
    recording_index, ...
    branch_name, ...
    metric_name, ...
    values_by_plane, ...
    unit_name)

    values_by_plane = ...
        normalize_values_by_plane( ...
            values_by_plane);


    for p = 1:numel(values_by_plane)

        [metric_value, n_values] = ...
            summarize_numeric_values( ...
                values_by_plane{p});


        if ~isfinite(metric_value)
            continue;
        end


        row = ...
            make_results_row( ...
                current_type, ...
                animal_id, ...
                age_label, ...
                age_number, ...
                date_name, ...
                session_id, ...
                recording_index, ...
                p - 1, ...
                branch_name, ...
                metric_name, ...
                metric_value, ...
                n_values, ...
                unit_name);


        results_table = ...
            [ ...
                results_table; ...
                row ...
            ]; %#ok<AGROW>
    end
end


function results_table = append_session_value( ...
    results_table, ...
    current_type, ...
    animal_id, ...
    age_label, ...
    age_number, ...
    date_name, ...
    session_id, ...
    recording_index, ...
    branch_name, ...
    metric_name, ...
    values, ...
    unit_name)

    [metric_value, n_values] = ...
        summarize_numeric_values( ...
            values);


    if ~isfinite(metric_value)
        return;
    end


    row = ...
        make_results_row( ...
            current_type, ...
            animal_id, ...
            age_label, ...
            age_number, ...
            date_name, ...
            session_id, ...
            recording_index, ...
            NaN, ...
            branch_name, ...
            metric_name, ...
            metric_value, ...
            n_values, ...
            unit_name);


    results_table = ...
        [ ...
            results_table; ...
            row ...
        ];
end


function row = make_results_row( ...
    current_type, ...
    animal_id, ...
    age_label, ...
    age_number, ...
    date_name, ...
    session_id, ...
    recording_index, ...
    plane_number, ...
    branch_name, ...
    metric_name, ...
    metric_value, ...
    n_values, ...
    unit_name)

    row = ...
        table( ...
            string(current_type), ...
            string(animal_id), ...
            string(age_label), ...
            double(age_number), ...
            string(date_name), ...
            string(session_id), ...
            double(recording_index), ...
            double(plane_number), ...
            string(branch_name), ...
            string(metric_name), ...
            double(metric_value), ...
            double(n_values), ...
            string(unit_name), ...
            'VariableNames', { ...
                'Type', ...
                'Animal', ...
                'Age', ...
                'AgeNumber', ...
                'Date', ...
                'SessionID', ...
                'RecordingIndex', ...
                'Plane', ...
                'Branch', ...
                'Metric', ...
                'Value', ...
                'N', ...
                'Unit'});
end


function values_by_plane = ...
    normalize_values_by_plane( ...
        values)

    if isempty(values)

        values_by_plane = ...
            {};


    elseif iscell(values)

        values_by_plane = ...
            values(:).';


    elseif isnumeric(values) || ...
            islogical(values)

        values_by_plane = ...
            {values};


    else

        values_by_plane = ...
            {};
    end
end


function [mean_value, n_values] = ...
    summarize_numeric_values( ...
        values)

    mean_value = ...
        NaN;


    n_values = ...
        0;


    if isempty(values)
        return;
    end


    if iscell(values)

        combined = [];


        for i = 1:numel(values)

            current = ...
                values{i};


            if isnumeric(current) || ...
                    islogical(current)

                combined = ...
                    [ ...
                        combined; ...
                        double(current(:)) ...
                    ]; %#ok<AGROW>
            end
        end


        values = ...
            combined;
    end


    if ~(isnumeric(values) || ...
            islogical(values))

        return;
    end


    values = ...
        double(values(:));


    values = ...
        values(isfinite(values));


    n_values = ...
        numel(values);


    if n_values > 0

        mean_value = ...
            mean( ...
                values, ...
                'omitnan');
    end
end


function date_name = ...
    get_date_name_from_path( ...
        date_group_paths, ...
        m)

    date_name = ...
        "";


    if isempty(date_group_paths) || ...
            numel(date_group_paths) < m || ...
            isempty(date_group_paths{m})

        return;
    end


    [~, current_date] = ...
        fileparts( ...
            date_group_paths{m});


    date_name = ...
        string(current_date);
end


function age_label = ...
    get_age_for_recording( ...
        current_ages, ...
        m)

    age_label = ...
        "";


    if isempty(current_ages)
        return;
    end


    if iscell(current_ages)

        if numel(current_ages) >= m

            age_label = ...
                string( ...
                    current_ages{m});
        end


    elseif isstring(current_ages)

        if numel(current_ages) >= m

            age_label = ...
                current_ages(m);

        elseif isscalar(current_ages)

            age_label = ...
                current_ages;
        end


    elseif ischar(current_ages)

        age_label = ...
            string(current_ages);


    elseif isnumeric(current_ages)

        if numel(current_ages) >= m

            age_label = ...
                "P" + ...
                string( ...
                    current_ages(m));

        elseif isscalar(current_ages)

            age_label = ...
                "P" + ...
                string(current_ages);
        end
    end
end


function age_number = ...
    extract_age_number( ...
        age_label)

    age_number = ...
        NaN;


    if strlength( ...
            string(age_label)) == 0

        return;
    end


    token = ...
        regexp( ...
            char(string(age_label)), ...
            '[-+]?\d*\.?\d+', ...
            'match', ...
            'once');


    if ~isempty(token)

        age_number = ...
            str2double(token);
    end
end


function value = ...
    get_metadata_value( ...
        metadata, ...
        fieldName, ...
        m)

    value = [];


    if isempty(metadata) || ...
            ~isstruct(metadata) || ...
            ~isfield(metadata, fieldName)

        return;
    end


    x = ...
        metadata.(fieldName);


    if iscell(x)

        if numel(x) >= m

            value = ...
                x{m};
        end


    elseif numel(x) >= m && ...
            ~isscalar(x)

        value = ...
            x(m);


    else

        value = ...
            x;
    end
end


function v = ...
    parse_numeric_vector(x)

    v = [];


    if isempty(x)
        return;
    end


    if isnumeric(x)

        v = ...
            double(x(:).');


        v = ...
            v(isfinite(v));

        return;
    end


    if isstring(x)

        x = ...
            cellstr(x);
    end


    if ischar(x)

        v = ...
            sscanf( ...
                x, ...
                '%f').';


        v = ...
            double(v(:).');


        v = ...
            v(isfinite(v));

        return;
    end


    if iscell(x)

        tmp = [];


        for i = 1:numel(x)

            vi = ...
                parse_numeric_vector( ...
                    x{i});


            if ~isempty(vi)

                tmp = ...
                    [ ...
                        tmp, ...
                        vi ...
                    ]; %#ok<AGROW>
            end
        end


        v = ...
            tmp;


        v = ...
            v(isfinite(v));
    end
end