function [results_analysis, results_table] = compute_export_basic_metrics( ...
    current_type, ...
    current_animal_group, ...
    current_ages, ...
    gcamp_root_folders, ...
    date_group_paths, ...
    data, ...
    metadata, ...
    include_electroporated_cells)

%COMPUTE_EXPORT_BASIC_METRICS
%
% Fonction d'orchestration.
%
% Pour chaque recording :
%   1) récupère les métadonnées ;
%   2) calcule les métriques d'activité PAR PLAN ;
%   3) charge ou calcule les métriques réseau PAR PLAN ;
%   4) charge ou calcule les SCEs sur les plans concaténés ;
%   5) assemble toutes les métriques ;
%   6) remplit results_analysis ;
%   7) construit results_table.
%
% Organisation :
%
%   Activité :
%       results_analysis....activity.metric{m}{p}
%
%   Corrélations :
%       results_analysis....correlations.metric{m}{p}
%
%   Coupling :
%       results_analysis....coupling.metric{m}{p}
%
% avec :
%       m = recording
%       p = plan
%
% Les SCEs constituent volontairement une exception :
% les différents plans sont concaténés avant calcul.
% Les métriques SCE restent donc définies au niveau du recording.


    %==============================================================%
    % Initialisation
    %==============================================================%
    nRec = ...
        numel(gcamp_root_folders);

    synchronous_frames_group = ...
        cell(nRec, 1);

    if nargin < 8 || ...
            isempty(include_electroporated_cells)

        include_electroporated_cells = ...
            '1';
    end


    include_electroporated_cells = ...
        char(string(include_electroporated_cells));


    process_electroporated = ...
        strcmp( ...
            include_electroporated_cells, ...
            '1');


    current_type = ...
        string(current_type);


    current_animal_group = ...
        string(current_animal_group);


    results_analysis = ...
        init_empty_results_analysis( ...
            nRec);


    results_table = ...
        init_results_table();


    %==============================================================%
    % Boucle recordings
    %==============================================================%
    for m = 1:nRec

        date_name = ...
            get_date_name_from_path( ...
                date_group_paths, ...
                m);


        age_label = ...
            get_age_for_recording( ...
                current_ages, ...
                m);


        age_number = ...
            extract_age_number( ...
                age_label);


        session_id = ...
            current_animal_group + ...
            "_" + ...
            date_name + ...
            "_rec" + ...
            string(m);


        try

            %======================================================%
            % Metadata du recording
            %
            % Même organisation que run_gcamp_peak_detection :
            %
            % metadata
            %   -> metadata_m
            %       -> gcamp_plane
            %======================================================%
            metadata_m = ...
                get_metadata_for_record( ...
                    metadata, ...
                    m);
            
            
            %======================================================%
            % GCaMP metadata = référence
            %======================================================%
            if ~isfield(metadata_m, 'gcamp_plane') || ...
                    isempty(metadata_m.gcamp_plane)
            
                error( ...
                    'GCaMP metadata missing for rec %d.', ...
                    m);
            end
            
            
            metadata_gcamp_m = ...
                metadata_m.gcamp_plane;
            
            
            %======================================================%
            % SamplingRatePlane
            %======================================================%
            if ~isfield(metadata_gcamp_m, ...
                    'SamplingRatePlane') || ...
                    isempty(metadata_gcamp_m.SamplingRatePlane)
            
                error( ...
                    ['SamplingRatePlane missing in GCaMP metadata ' ...
                     'for rec %d.'], ...
                    m);
            end
            
            
            sampling_rate = ...
                parse_numeric_vector( ...
                    metadata_gcamp_m.SamplingRatePlane);
            
            
            if isempty(sampling_rate)
            
                error( ...
                    'SamplingRatePlane invalid for rec %d.', ...
                    m);
            end
            
            
            sampling_rate = ...
                sampling_rate(1);
            
            
            if ~isfinite(sampling_rate) || ...
                    sampling_rate <= 0
            
                error( ...
                    'SamplingRatePlane invalid for rec %d.', ...
                    m);
            end
            
            
            %======================================================%
            % Fenêtre de synchronie
            %
            % 200 ms, identique à run_peak.
            %======================================================%
            synchronous_frames = ...
                max( ...
                    1, ...
                    round( ...
                        0.2 * sampling_rate));
            
            
            synchronous_frames_group{m} = ...
                synchronous_frames;
            
            
            fprintf( ...
                ['Rec %d: SamplingRatePlane = %.4f Hz | ' ...
                 'synchronous_frames = %d\n'], ...
                m, ...
                sampling_rate, ...
                synchronous_frames);


            %======================================================%
            % 1) Activity metrics PAR PLAN
            %
            % compute_all_basic_metrics doit retourner :
            %
            %   nCells_by_plane
            %   freq_by_plane
            %   intervals_ms_by_plane
            %   burst_rate_by_plane
            %   burst_fraction_by_plane
            %   burst_size_by_plane
            %
            % chaque champ étant une cellule {p}.
            %======================================================%
            metrics = ...
                compute_all_basic_metrics( ...
                    data, ...
                    m, ...
                    sampling_rate, ...
                    include_electroporated_cells);


            %======================================================%
            % Recording invalide
            %======================================================%
            if ~metrics.valid

                warning( ...
                    ['Skipping rec %d (%s) - ' ...
                     'données GCaMP invalides.'], ...
                    m, ...
                    gcamp_root_folders{m});

                continue;
            end


            %======================================================%
            % 2) Network correlations + coupling PAR PLAN
            %======================================================%
            network_metrics = ...
                load_or_process_network_metrics_for_session( ...
                    gcamp_root_folders, ...
                    data, ...
                    m, ...
                    sampling_rate, ...
                    include_electroporated_cells);


            %======================================================%
            % 3) SCEs
            %
            % IMPORTANT :
            % Les plans sont volontairement concaténés pour les SCEs.
            % Ces métriques restent donc au niveau du recording.
            %======================================================%
            sce_metrics = ...
                load_or_process_sce_for_session( ...
                    current_animal_group, ...
                    date_group_paths, ...
                    gcamp_root_folders, ...
                    synchronous_frames_group, ...
                    data, ...
                    m, ...
                    sampling_rate);


            %======================================================%
            % 4) Assemble GCaMP correlations PAR PLAN
            %======================================================%
            metrics.gcamp_plane.correlations = ...
                struct();


            metrics.gcamp_plane.correlations. ...
                cross_corr_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                cross_corr_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.correlations. ...
                max_corr_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                max_corr_gcamp_gcamp_by_plane;


            %======================================================%
            % 5) Assemble GCaMP functional coupling PAR PLAN
            %======================================================%
            metrics.gcamp_plane.coupling = ...
                struct();


            metrics.gcamp_plane.coupling. ...
                population_corr_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                population_corr_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                peak_coupling_fraction_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                peak_coupling_fraction_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                peak_coupling_shuffle_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                peak_coupling_shuffle_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                peak_coupling_excess_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                peak_coupling_excess_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                peak_coupling_ratio_gcamp_gcamp_by_plane = ...
                network_metrics. ...
                peak_coupling_ratio_gcamp_gcamp_by_plane;


            metrics.gcamp_plane.coupling. ...
                max_lagged_corr_gcamp_gcamp_population_by_plane = ...
                network_metrics. ...
                max_lagged_corr_gcamp_gcamp_population_by_plane;


            metrics.gcamp_plane.coupling. ...
                lag_to_gcamp_gcamp_population_ms_by_plane = ...
                network_metrics. ...
                lag_to_gcamp_gcamp_population_ms_by_plane;


            %======================================================%
            % 6) SCEs concaténés
            %======================================================%
            metrics.gcamp_plane.SCEs = ...
                sce_metrics;


            %======================================================%
            % 7) Electroporated / mTOR PAR PLAN
            %======================================================%
            if process_electroporated

                %--------------------------------------------------%
                % Correlations
                %--------------------------------------------------%
                metrics.electroporated_plane.correlations = ...
                    struct();


                metrics.electroporated_plane.correlations. ...
                    cross_corr_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    cross_corr_gcamp_mtor_by_plane;


                metrics.electroporated_plane.correlations. ...
                    cross_corr_mtor_mtor_by_plane = ...
                    network_metrics. ...
                    cross_corr_mtor_mtor_by_plane;


                metrics.electroporated_plane.correlations. ...
                    max_corr_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    max_corr_gcamp_mtor_by_plane;


                metrics.electroporated_plane.correlations. ...
                    max_corr_mtor_mtor_by_plane = ...
                    network_metrics. ...
                    max_corr_mtor_mtor_by_plane;


                metrics.electroporated_plane.correlations. ...
                    median_corr_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    median_corr_gcamp_mtor_by_plane;


                %--------------------------------------------------%
                % Coupling
                %--------------------------------------------------%
                metrics.electroporated_plane.coupling = ...
                    struct();


                metrics.electroporated_plane.coupling. ...
                    population_corr_gcamp_mtor_by_plane = ...
                    network_metrics. ...
                    population_corr_gcamp_mtor_by_plane;


                metrics.electroporated_plane.coupling. ...
                    peak_coupling_fraction_by_plane = ...
                    network_metrics. ...
                    peak_coupling_fraction_by_plane;


                metrics.electroporated_plane.coupling. ...
                    peak_coupling_shuffle_by_plane = ...
                    network_metrics. ...
                    peak_coupling_shuffle_by_plane;


                metrics.electroporated_plane.coupling. ...
                    peak_coupling_excess_by_plane = ...
                    network_metrics. ...
                    peak_coupling_excess_by_plane;


                metrics.electroporated_plane.coupling. ...
                    peak_coupling_ratio_by_plane = ...
                    network_metrics. ...
                    peak_coupling_ratio_by_plane;


                metrics.electroporated_plane.coupling. ...
                    max_lagged_corr_gcamp_population_by_plane = ...
                    network_metrics. ...
                    max_lagged_corr_gcamp_population_by_plane;


                metrics.electroporated_plane.coupling. ...
                    lag_to_gcamp_population_ms_by_plane = ...
                    network_metrics. ...
                    lag_to_gcamp_population_ms_by_plane;
            end


            %======================================================%
            % 8) Stockage
            %======================================================%
            results_analysis = ...
                store_metrics_in_results_analysis( ...
                    results_analysis, ...
                    metrics, ...
                    m, ...
                    process_electroporated);


            %======================================================%
            % 9) Export table
            %======================================================%
            results_table = ...
                append_all_metrics_to_results_table( ...
                    results_table, ...
                    metrics, ...
                    current_type, ...
                    current_animal_group, ...
                    age_label, ...
                    age_number, ...
                    date_name, ...
                    session_id, ...
                    m, ...
                    process_electroporated);


        catch ME

            fprintf( ...
                'Error processing rec %d: %s\n', ...
                m, ...
                ME.message);
        end
    end


    %==============================================================%
    % Tri final
    %==============================================================%
    if ~isempty(results_table)

        results_table = ...
            sortrows( ...
                results_table, ...
                { ...
                    'Type', ...
                    'Animal', ...
                    'AgeNumber', ...
                    'RecordingIndex', ...
                    'Plane', ...
                    'Branch', ...
                    'Metric' ...
                });
    end
end


%==================================================================%
% INITIALISATION RESULTS_ANALYSIS
%==================================================================%
function results_analysis = ...
    init_empty_results_analysis( ...
        nRec)

    results_analysis = ...
        struct( ...
            'gcamp_plane', struct(), ...
            'electroporated_plane', struct());


    %==============================================================%
    % GCaMP activity
    %==============================================================%
    results_analysis.gcamp_plane.activity = ...
        struct();


    results_analysis.gcamp_plane.activity.ActiveCellsNumber = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.activity.FrequencyPerCell = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.activity.InterEventIntervals_ms = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.activity.BurstRate_per_min = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.activity.BurstFraction = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.activity.BurstSize = ...
        cell(nRec, 1);


    %==============================================================%
    % GCaMP correlations
    %==============================================================%
    results_analysis.gcamp_plane.correlations = ...
        struct();


    results_analysis.gcamp_plane.correlations. ...
        cross_corr_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.correlations. ...
        max_corr_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    %==============================================================%
    % GCaMP coupling
    %==============================================================%
    results_analysis.gcamp_plane.coupling = ...
        struct();


    results_analysis.gcamp_plane.coupling. ...
        population_corr_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_fraction_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_shuffle_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_excess_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_ratio_gcamp_gcamp_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        max_lagged_corr_gcamp_gcamp_population_by_plane = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.coupling. ...
        lag_to_gcamp_gcamp_population_ms_by_plane = ...
        cell(nRec, 1);


    %==============================================================%
    % SCEs
    %
    % Contrairement aux autres métriques, les SCEs sont calculées
    % après concaténation des plans.
    % Donc une entrée par recording, pas une entrée par plan.
    %==============================================================%
    results_analysis.gcamp_plane.SCEs = ...
        struct();


    results_analysis.gcamp_plane.SCEs.Race_gcamp = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.TRace_gcamp = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.sces_distances_gcamp = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.RasterRace_gcamp = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.sce_n_cells_threshold = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.Threshold = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.Frequency = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.CellParticipation_percent = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.Duration_ms = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.Number = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.RecordingDuration_min = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.InterSCEIntervals_ms = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs. ...
        MeanCellParticipation_percent = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs. ...
        MedianCellParticipation_percent = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.MeanDuration_ms = ...
        cell(nRec, 1);


    results_analysis.gcamp_plane.SCEs.MedianDuration_ms = ...
        cell(nRec, 1);


    %==============================================================%
    % Electroporated activity
    %==============================================================%
    results_analysis.electroporated_plane.activity = ...
        struct();


    results_analysis.electroporated_plane.activity.ActiveCellsNumber = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.activity.FrequencyPerCell = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.activity.InterEventIntervals_ms = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.activity.BurstRate_per_min = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.activity.BurstFraction = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.activity.BurstSize = ...
        cell(nRec, 1);


    %==============================================================%
    % Electroporated correlations
    %==============================================================%
    results_analysis.electroporated_plane.correlations = ...
        struct();


    results_analysis.electroporated_plane.correlations. ...
        cross_corr_gcamp_mtor_by_plane = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.correlations. ...
        cross_corr_mtor_mtor_by_plane = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.correlations. ...
        max_corr_gcamp_mtor_by_plane = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.correlations. ...
        max_corr_mtor_mtor_by_plane = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.correlations. ...
        median_corr_gcamp_mtor_by_plane = ...
        cell(nRec, 1);


    %==============================================================%
    % Electroporated coupling
    %==============================================================%
    results_analysis.electroporated_plane.coupling = ...
        struct();


    results_analysis.electroporated_plane.coupling. ...
        population_corr_gcamp_mtor_by_plane = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.coupling. ...
        peak_coupling_fraction_by_plane = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.coupling. ...
        peak_coupling_shuffle_by_plane = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.coupling. ...
        peak_coupling_excess_by_plane = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.coupling. ...
        peak_coupling_ratio_by_plane = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.coupling. ...
        max_lagged_corr_gcamp_population_by_plane = ...
        cell(nRec, 1);


    results_analysis.electroporated_plane.coupling. ...
        lag_to_gcamp_population_ms_by_plane = ...
        cell(nRec, 1);
end


%==================================================================%
% STOCKAGE
%==================================================================%
function results_analysis = ...
    store_metrics_in_results_analysis( ...
        results_analysis, ...
        metrics, ...
        m, ...
        process_electroporated)

    %==============================================================%
    % GCaMP activity PAR PLAN
    %==============================================================%
    A = ...
        metrics.gcamp_plane.activity;


    results_analysis.gcamp_plane.activity.ActiveCellsNumber{m} = ...
        normalize_values_by_plane( ...
            A.nCells_by_plane);


    results_analysis.gcamp_plane.activity.FrequencyPerCell{m} = ...
        normalize_values_by_plane( ...
            A.freq_by_plane);


    results_analysis.gcamp_plane.activity.InterEventIntervals_ms{m} = ...
        normalize_values_by_plane( ...
            A.intervals_ms_by_plane);


    results_analysis.gcamp_plane.activity.BurstRate_per_min{m} = ...
        normalize_values_by_plane( ...
            A.burst_rate_by_plane);


    results_analysis.gcamp_plane.activity.BurstFraction{m} = ...
        normalize_values_by_plane( ...
            A.burst_fraction_by_plane);


    results_analysis.gcamp_plane.activity.BurstSize{m} = ...
        normalize_values_by_plane( ...
            A.burst_size_by_plane);


    %==============================================================%
    % GCaMP correlations PAR PLAN
    %==============================================================%
    C = ...
        metrics.gcamp_plane.correlations;


    results_analysis.gcamp_plane.correlations. ...
        cross_corr_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.cross_corr_gcamp_gcamp_by_plane);


    results_analysis.gcamp_plane.correlations. ...
        max_corr_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.max_corr_gcamp_gcamp_by_plane);


    %==============================================================%
    % GCaMP coupling PAR PLAN
    %==============================================================%
    C = ...
        metrics.gcamp_plane.coupling;


    results_analysis.gcamp_plane.coupling. ...
        population_corr_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.population_corr_gcamp_gcamp_by_plane);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_fraction_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.peak_coupling_fraction_gcamp_gcamp_by_plane);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_shuffle_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.peak_coupling_shuffle_gcamp_gcamp_by_plane);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_excess_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.peak_coupling_excess_gcamp_gcamp_by_plane);


    results_analysis.gcamp_plane.coupling. ...
        peak_coupling_ratio_gcamp_gcamp_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.peak_coupling_ratio_gcamp_gcamp_by_plane);


    results_analysis.gcamp_plane.coupling. ...
        max_lagged_corr_gcamp_gcamp_population_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.max_lagged_corr_gcamp_gcamp_population_by_plane);


    results_analysis.gcamp_plane.coupling. ...
        lag_to_gcamp_gcamp_population_ms_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.lag_to_gcamp_gcamp_population_ms_by_plane);


    %==============================================================%
    % SCEs CONCATÉNÉS
    %==============================================================%
    S = ...
        metrics.gcamp_plane.SCEs;


    results_analysis.gcamp_plane.SCEs.Race_gcamp{m} = ...
        S.Race_gcamp;


    results_analysis.gcamp_plane.SCEs.TRace_gcamp{m} = ...
        S.TRace_gcamp;


    results_analysis.gcamp_plane.SCEs.sces_distances_gcamp{m} = ...
        S.sces_distances_gcamp;


    results_analysis.gcamp_plane.SCEs.RasterRace_gcamp{m} = ...
        S.RasterRace_gcamp;


    results_analysis.gcamp_plane.SCEs.sce_n_cells_threshold{m} = ...
        S.sce_n_cells_threshold;


    results_analysis.gcamp_plane.SCEs.Threshold{m} = ...
        S.sce_n_cells_threshold;


    results_analysis.gcamp_plane.SCEs.Frequency{m} = ...
        S.sce_frequency_per_min;


    results_analysis.gcamp_plane.SCEs.CellParticipation_percent{m} = ...
        S.cell_participation_percent;


    results_analysis.gcamp_plane.SCEs.Duration_ms{m} = ...
        S.duration_ms;


    results_analysis.gcamp_plane.SCEs.Number{m} = ...
        S.number;


    results_analysis.gcamp_plane.SCEs.RecordingDuration_min{m} = ...
        S.recording_duration_min;


    results_analysis.gcamp_plane.SCEs.InterSCEIntervals_ms{m} = ...
        S.inter_sce_intervals_ms;


    results_analysis.gcamp_plane.SCEs. ...
        MeanCellParticipation_percent{m} = ...
        S.mean_cell_participation_percent;


    results_analysis.gcamp_plane.SCEs. ...
        MedianCellParticipation_percent{m} = ...
        S.median_cell_participation_percent;


    results_analysis.gcamp_plane.SCEs.MeanDuration_ms{m} = ...
        S.mean_duration_ms;


    results_analysis.gcamp_plane.SCEs.MedianDuration_ms{m} = ...
        S.median_duration_ms;


    %==============================================================%
    % Sans electroporated
    %==============================================================%
    if ~process_electroporated
        return;
    end


    %==============================================================%
    % Electroporated activity PAR PLAN
    %==============================================================%
    A = ...
        metrics.electroporated_plane.activity;


    results_analysis.electroporated_plane.activity.ActiveCellsNumber{m} = ...
        normalize_values_by_plane( ...
            A.nCells_by_plane);


    results_analysis.electroporated_plane.activity.FrequencyPerCell{m} = ...
        normalize_values_by_plane( ...
            A.freq_by_plane);


    results_analysis.electroporated_plane.activity.InterEventIntervals_ms{m} = ...
        normalize_values_by_plane( ...
            A.intervals_ms_by_plane);


    results_analysis.electroporated_plane.activity.BurstRate_per_min{m} = ...
        normalize_values_by_plane( ...
            A.burst_rate_by_plane);


    results_analysis.electroporated_plane.activity.BurstFraction{m} = ...
        normalize_values_by_plane( ...
            A.burst_fraction_by_plane);


    results_analysis.electroporated_plane.activity.BurstSize{m} = ...
        normalize_values_by_plane( ...
            A.burst_size_by_plane);


    %==============================================================%
    % Electroporated correlations PAR PLAN
    %==============================================================%
    C = ...
        metrics.electroporated_plane.correlations;


    results_analysis.electroporated_plane.correlations. ...
        cross_corr_gcamp_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.cross_corr_gcamp_mtor_by_plane);


    results_analysis.electroporated_plane.correlations. ...
        cross_corr_mtor_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.cross_corr_mtor_mtor_by_plane);


    results_analysis.electroporated_plane.correlations. ...
        max_corr_gcamp_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.max_corr_gcamp_mtor_by_plane);


    results_analysis.electroporated_plane.correlations. ...
        max_corr_mtor_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.max_corr_mtor_mtor_by_plane);


    results_analysis.electroporated_plane.correlations. ...
        median_corr_gcamp_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.median_corr_gcamp_mtor_by_plane);


    %==============================================================%
    % Electroporated coupling PAR PLAN
    %==============================================================%
    C = ...
        metrics.electroporated_plane.coupling;


    results_analysis.electroporated_plane.coupling. ...
        population_corr_gcamp_mtor_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.population_corr_gcamp_mtor_by_plane);


    results_analysis.electroporated_plane.coupling. ...
        peak_coupling_fraction_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.peak_coupling_fraction_by_plane);


    results_analysis.electroporated_plane.coupling. ...
        peak_coupling_shuffle_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.peak_coupling_shuffle_by_plane);


    results_analysis.electroporated_plane.coupling. ...
        peak_coupling_excess_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.peak_coupling_excess_by_plane);


    results_analysis.electroporated_plane.coupling. ...
        peak_coupling_ratio_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.peak_coupling_ratio_by_plane);


    results_analysis.electroporated_plane.coupling. ...
        max_lagged_corr_gcamp_population_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.max_lagged_corr_gcamp_population_by_plane);


    results_analysis.electroporated_plane.coupling. ...
        lag_to_gcamp_population_ms_by_plane{m} = ...
        normalize_values_by_plane( ...
            C.lag_to_gcamp_population_ms_by_plane);
end


%==================================================================%
% RESULTS TABLE
%==================================================================%
function results_table = ...
    append_all_metrics_to_results_table( ...
        results_table, ...
        metrics, ...
        current_type, ...
        current_animal_group, ...
        age_label, ...
        age_number, ...
        date_name, ...
        session_id, ...
        m, ...
        process_electroporated)

    %==============================================================%
    % GCaMP activity PAR PLAN
    %==============================================================%
    A = ...
        metrics.gcamp_plane.activity;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "ActiveCellsNumber", ...
        A.nCells_by_plane, ...
        "cells");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "FrequencyPerCell", ...
        A.freq_by_plane, ...
        "events/min");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "InterEventIntervals", ...
        A.intervals_ms_by_plane, ...
        "ms");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "BurstRate", ...
        A.burst_rate_by_plane, ...
        "bursts/min");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "BurstFraction", ...
        A.burst_fraction_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.activity", ...
        "BurstSize", ...
        A.burst_size_by_plane, ...
        "events/burst");


    %==============================================================%
    % GCaMP correlations PAR PLAN
    %==============================================================%
    C = ...
        metrics.gcamp_plane.correlations;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.correlations", ...
        "PairwiseCorrelation_GCaMP_GCaMP", ...
        C.max_corr_gcamp_gcamp_by_plane, ...
        "correlation");


    %==============================================================%
    % GCaMP coupling PAR PLAN
    %==============================================================%
    C = ...
        metrics.gcamp_plane.coupling;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "PopulationCorrelation_GCaMP_GCaMP", ...
        C.population_corr_gcamp_gcamp_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "PeakCouplingFraction_GCaMP_GCaMP", ...
        C.peak_coupling_fraction_gcamp_gcamp_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "PeakCouplingShuffle_GCaMP_GCaMP", ...
        C.peak_coupling_shuffle_gcamp_gcamp_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "PeakCouplingExcess_GCaMP_GCaMP", ...
        C.peak_coupling_excess_gcamp_gcamp_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "PeakCouplingRatio_GCaMP_GCaMP", ...
        C.peak_coupling_ratio_gcamp_gcamp_by_plane, ...
        "ratio");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "MaxLaggedCorrelation_GCaMP_GCaMP", ...
        C.max_lagged_corr_gcamp_gcamp_population_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.coupling", ...
        "LagToGCaMPPopulation_GCaMP_GCaMP", ...
        C.lag_to_gcamp_gcamp_population_ms_by_plane, ...
        "ms");


    %==============================================================%
    % SCEs
    %
    % VOLONTAIREMENT au niveau du recording.
    % Plane = NaN.
    %==============================================================%
    S = ...
        metrics.gcamp_plane.SCEs;


    results_table = append_session_value( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.SCEs", ...
        "Frequency", ...
        S.sce_frequency_per_min, ...
        "SCEs/min");


    results_table = append_session_value( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.SCEs", ...
        "CellParticipation", ...
        S.cell_participation_percent, ...
        "%");


    results_table = append_session_value( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "gcamp_plane.SCEs", ...
        "Duration", ...
        S.duration_ms, ...
        "ms");


    %==============================================================%
    % Sans électroporées
    %==============================================================%
    if ~process_electroporated
        return;
    end


    %==============================================================%
    % Electroporated activity PAR PLAN
    %==============================================================%
    A = ...
        metrics.electroporated_plane.activity;


    if A.valid

        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "ActiveCellsNumber", ...
            A.nCells_by_plane, ...
            "cells");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "FrequencyPerCell", ...
            A.freq_by_plane, ...
            "events/min");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "InterEventIntervals", ...
            A.intervals_ms_by_plane, ...
            "ms");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "BurstRate", ...
            A.burst_rate_by_plane, ...
            "bursts/min");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "BurstFraction", ...
            A.burst_fraction_by_plane, ...
            "fraction");


        results_table = append_values_by_plane( ...
            results_table, current_type, current_animal_group, ...
            age_label, age_number, date_name, session_id, m, ...
            "electroporated_plane.activity", ...
            "BurstSize", ...
            A.burst_size_by_plane, ...
            "events/burst");
    end


    %==============================================================%
    % Electroporated correlations PAR PLAN
    %==============================================================%
    C = ...
        metrics.electroporated_plane.correlations;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.correlations", ...
        "PairwiseCorrelation_GCaMP_mTOR", ...
        C.max_corr_gcamp_mtor_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.correlations", ...
        "PairwiseCorrelation_mTOR_mTOR", ...
        C.max_corr_mtor_mtor_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.correlations", ...
        "MedianCorrelation_GCaMP_mTOR", ...
        C.median_corr_gcamp_mtor_by_plane, ...
        "correlation");


    %==============================================================%
    % Electroporated coupling PAR PLAN
    %==============================================================%
    C = ...
        metrics.electroporated_plane.coupling;


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.coupling", ...
        "PopulationCorrelation_GCaMP_mTOR", ...
        C.population_corr_gcamp_mtor_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.coupling", ...
        "PeakCouplingFraction_GCaMP_mTOR", ...
        C.peak_coupling_fraction_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.coupling", ...
        "PeakCouplingShuffle_GCaMP_mTOR", ...
        C.peak_coupling_shuffle_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.coupling", ...
        "PeakCouplingExcess_GCaMP_mTOR", ...
        C.peak_coupling_excess_by_plane, ...
        "fraction");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.coupling", ...
        "PeakCouplingRatio_GCaMP_mTOR", ...
        C.peak_coupling_ratio_by_plane, ...
        "ratio");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.coupling", ...
        "MaxLaggedCorrelation_GCaMP_mTOR", ...
        C.max_lagged_corr_gcamp_population_by_plane, ...
        "correlation");


    results_table = append_values_by_plane( ...
        results_table, current_type, current_animal_group, ...
        age_label, age_number, date_name, session_id, m, ...
        "electroporated_plane.coupling", ...
        "LagToGCaMPPopulation_GCaMP_mTOR", ...
        C.lag_to_gcamp_population_ms_by_plane, ...
        "ms");
end


%==================================================================%
% TABLE VIDE
%==================================================================%
function results_table = init_results_table()

    results_table = ...
        table( ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            string.empty(0,1), ...
            nan(0,1), ...
            nan(0,1), ...
            string.empty(0,1), ...
            'VariableNames', { ...
                'Type', ...
                'Animal', ...
                'Age', ...
                'AgeNumber', ...
                'Date', ...
                'SessionID', ...
                'RecordingIndex', ...
                'Plane', ...
                'Branch', ...
                'Metric', ...
                'Value', ...
                'N', ...
                'Unit'});
end


%==================================================================%
% AJOUT PAR PLAN
%==================================================================%
function results_table = append_values_by_plane( ...
    results_table, ...
    current_type, ...
    animal_id, ...
    age_label, ...
    age_number, ...
    date_name, ...
    session_id, ...
    recording_index, ...
    branch_name, ...
    metric_name, ...
    values_by_plane, ...
    unit_name)

    values_by_plane = ...
        normalize_values_by_plane( ...
            values_by_plane);


    for p = 1:numel(values_by_plane)

        [metric_value, n_values] = ...
            summarize_numeric_values( ...
                values_by_plane{p});


        if ~isfinite(metric_value)
            continue;
        end


        row = ...
            make_results_row( ...
                current_type, ...
                animal_id, ...
                age_label, ...
                age_number, ...
                date_name, ...
                session_id, ...
                recording_index, ...
                p - 1, ...
                branch_name, ...
                metric_name, ...
                metric_value, ...
                n_values, ...
                unit_name);


        results_table = ...
            [ ...
                results_table; ...
                row ...
            ]; %#ok<AGROW>
    end
end


%==================================================================%
% AJOUT GLOBAL RECORDING
% Utilisé volontairement pour les SCEs.
%==================================================================%
function results_table = append_session_value( ...
    results_table, ...
    current_type, ...
    animal_id, ...
    age_label, ...
    age_number, ...
    date_name, ...
    session_id, ...
    recording_index, ...
    branch_name, ...
    metric_name, ...
    values, ...
    unit_name)

    [metric_value, n_values] = ...
        summarize_numeric_values( ...
            values);


    if ~isfinite(metric_value)
        return;
    end


    row = ...
        make_results_row( ...
            current_type, ...
            animal_id, ...
            age_label, ...
            age_number, ...
            date_name, ...
            session_id, ...
            recording_index, ...
            NaN, ...
            branch_name, ...
            metric_name, ...
            metric_value, ...
            n_values, ...
            unit_name);


    results_table = ...
        [ ...
            results_table; ...
            row ...
        ];
end


%==================================================================%
% CONSTRUCTION ROW
%==================================================================%
function row = make_results_row( ...
    current_type, ...
    animal_id, ...
    age_label, ...
    age_number, ...
    date_name, ...
    session_id, ...
    recording_index, ...
    plane_number, ...
    branch_name, ...
    metric_name, ...
    metric_value, ...
    n_values, ...
    unit_name)

    row = ...
        table( ...
            string(current_type), ...
            string(animal_id), ...
            string(age_label), ...
            double(age_number), ...
            string(date_name), ...
            string(session_id), ...
            double(recording_index), ...
            double(plane_number), ...
            string(branch_name), ...
            string(metric_name), ...
            double(metric_value), ...
            double(n_values), ...
            string(unit_name), ...
            'VariableNames', { ...
                'Type', ...
                'Animal', ...
                'Age', ...
                'AgeNumber', ...
                'Date', ...
                'SessionID', ...
                'RecordingIndex', ...
                'Plane', ...
                'Branch', ...
                'Metric', ...
                'Value', ...
                'N', ...
                'Unit'});
end


%==================================================================%
% NORMALISATION PAR PLAN
%==================================================================%
function values_by_plane = ...
    normalize_values_by_plane( ...
        values)

    if isempty(values)

        values_by_plane = ...
            {};


    elseif iscell(values)

        values_by_plane = ...
            values(:).';


    elseif isnumeric(values) || ...
            islogical(values)

        values_by_plane = ...
            {values};


    else

        values_by_plane = ...
            {};
    end
end


%==================================================================%
% RÉSUMÉ NUMÉRIQUE
%==================================================================%
function [mean_value, n_values] = ...
    summarize_numeric_values( ...
        values)

    mean_value = ...
        NaN;


    n_values = ...
        0;


    if isempty(values)
        return;
    end


    if iscell(values)

        combined = [];


        for i = 1:numel(values)

            current = ...
                values{i};


            if isnumeric(current) || ...
                    islogical(current)

                combined = ...
                    [ ...
                        combined; ...
                        double(current(:)) ...
                    ]; %#ok<AGROW>
            end
        end


        values = ...
            combined;
    end


    if ~(isnumeric(values) || ...
            islogical(values))

        return;
    end


    values = ...
        double(values(:));


    values = ...
        values(isfinite(values));


    n_values = ...
        numel(values);


    if n_values > 0

        mean_value = ...
            mean( ...
                values, ...
                'omitnan');
    end
end


%==================================================================%
% DATE
%==================================================================%
function date_name = ...
    get_date_name_from_path( ...
        date_group_paths, ...
        m)

    date_name = ...
        "";


    if isempty(date_group_paths) || ...
            numel(date_group_paths) < m || ...
            isempty(date_group_paths{m})

        return;
    end


    [~, current_date] = ...
        fileparts( ...
            date_group_paths{m});


    date_name = ...
        string(current_date);
end


%==================================================================%
% AGE
%==================================================================%
function age_label = ...
    get_age_for_recording( ...
        current_ages, ...
        m)

    age_label = ...
        "";


    if isempty(current_ages)
        return;
    end


    if iscell(current_ages)

        if numel(current_ages) >= m

            age_label = ...
                string( ...
                    current_ages{m});
        end


    elseif isstring(current_ages)

        if numel(current_ages) >= m

            age_label = ...
                current_ages(m);

        elseif isscalar(current_ages)

            age_label = ...
                current_ages;
        end


    elseif ischar(current_ages)

        age_label = ...
            string(current_ages);


    elseif isnumeric(current_ages)

        if numel(current_ages) >= m

            age_label = ...
                "P" + ...
                string( ...
                    current_ages(m));

        elseif isscalar(current_ages)

            age_label = ...
                "P" + ...
                string(current_ages);
        end
    end
end


function age_number = ...
    extract_age_number( ...
        age_label)

    age_number = ...
        NaN;


    if strlength( ...
            string(age_label)) == 0

        return;
    end


    token = ...
        regexp( ...
            char(string(age_label)), ...
            '[-+]?\d*\.?\d+', ...
            'match', ...
            'once');


    if ~isempty(token)

        age_number = ...
            str2double(token);
    end
end


%==================================================================%
% METADATA DU RECORDING
%==================================================================%
function metadata_m = ...
    get_metadata_for_record( ...
        metadata, ...
        idx)

    metadata_m = ...
        struct();

    if isempty(metadata) || ...
            ~isstruct(metadata)

        return;
    end

    fields = ...
        fieldnames(metadata);

    for f = 1:numel(fields)

        field = ...
            fields{f};

        value = ...
            metadata.(field);

        %==========================================================%
        % Sous-structure
        %
        % Exemple :
        %   metadata.gcamp_plane
        %   metadata.electroporated_plane
        %==========================================================%
        if isstruct(value)

            metadata_m.(field) = ...
                get_metadata_for_record( ...
                    value, ...
                    idx);

        %==========================================================%
        % Champ indexé par recording
        %==========================================================%
        elseif iscell(value)

            if numel(value) >= idx

                metadata_m.(field) = ...
                    value{idx};

            else

                metadata_m.(field) = [];
            end

        %==========================================================%
        % Champ global
        %==========================================================%
        else

            metadata_m.(field) = ...
                value;
        end
    end
end

%==================================================================%
% NUMERIC PARSING
%==================================================================%
function v = ...
    parse_numeric_vector(x)

    v = [];


    if isempty(x)
        return;
    end


    if isnumeric(x)

        v = ...
            double(x(:).');


        v = ...
            v(isfinite(v));

        return;
    end


    if isstring(x)

        x = ...
            cellstr(x);
    end


    if ischar(x)

        v = ...
            sscanf( ...
                x, ...
                '%f').';


        v = ...
            double(v(:).');


        v = ...
            v(isfinite(v));

        return;
    end


    if iscell(x)

        tmp = [];


        for i = 1:numel(x)

            vi = ...
                parse_numeric_vector( ...
                    x{i});


            if ~isempty(vi)

                tmp = ...
                    [ ...
                        tmp, ...
                        vi ...
                    ]; %#ok<AGROW>
            end
        end


        v = ...
            tmp;


        v = ...
            v(isfinite(v));
    end
end