function network_metrics = ...
    load_or_process_network_metrics_for_session( ...
        gcamp_root_folders, ...
        data, ...
        m, ...
        sampling_rate, ...
        include_electroporated)

%LOAD_OR_PROCESS_NETWORK_METRICS_FOR_SESSION
%
% Charge ou calcule les métriques réseau d'un recording.
%
% GCaMP :
%
%   Pearson :
%       cross_corr_gcamp_gcamp_by_plane
%       max_corr_gcamp_gcamp_by_plane
%
%   Coupling :
%       coupling_gcamp_gcamp_by_plane
%       coupling_pvalue_gcamp_gcamp_by_plane
%
%
% mTOR :
%
%   Pearson :
%       cross_corr_gcamp_mtor_by_plane
%       max_corr_gcamp_mtor_by_plane
%       cross_corr_mtor_mtor_by_plane
%       max_corr_mtor_mtor_by_plane
%
%   Coupling :
%       coupling_gcamp_mtor_by_plane
%       coupling_pvalue_gcamp_mtor_by_plane
%
%
% Aucun lag ni résultat brut de shuffle n'est sauvegardé.


    %==============================================================%
    % Options
    %==============================================================%

    if nargin < 5 || ...
            isempty(include_electroporated)

        include_electroporated = ...
            '1';
    end


    include_electroporated = ...
        char(string(include_electroporated));


    process_electroporated = ...
        strcmp( ...
            include_electroporated, ...
            '1');


    %==============================================================%
    % Initialisation
    %==============================================================%

    network_metrics = ...
        empty_network_metrics();


    %==============================================================%
    % Vérification dossier
    %==============================================================%

    if isempty(gcamp_root_folders) || ...
            m > numel(gcamp_root_folders) || ...
            isempty(gcamp_root_folders{m})

        fprintf( ...
            ['Session %d: gcamp_root_folders vide, ' ...
             'skip network metrics.\n'], ...
            m);

        return;
    end


    %==============================================================%
    % Fichier
    %==============================================================%

    filePath = ...
        fullfile( ...
            gcamp_root_folders{m}, ...
            'results_network.mat');


    %==============================================================%
    % Nombre de plans
    %==============================================================%

    DFg_planes = ...
        get_planes_or_error_nested( ...
            data, ...
            'gcamp_plane', ...
            m, ...
            'DF_gcamp_by_plane');


    nPlanes = ...
        numel(DFg_planes);


    %==============================================================%
    % Préallocation
    %==============================================================%

    network_metrics = ...
        initialize_network_metrics_planes( ...
            nPlanes);


    %==============================================================%
    % Champs GCaMP requis
    %==============================================================%

    required_fields = { ...
        ...
        'cross_corr_gcamp_gcamp_by_plane', ...
        'max_corr_gcamp_gcamp_by_plane', ...
        ...
        'coupling_gcamp_gcamp_by_plane', ...
        'coupling_pvalue_gcamp_gcamp_by_plane' ...
    };


    %==============================================================%
    % Champs mTOR requis
    %==============================================================%

    if process_electroporated

        required_fields = ...
            [ ...
                required_fields, ...
                { ...
                    'cross_corr_gcamp_mtor_by_plane', ...
                    'cross_corr_mtor_mtor_by_plane', ...
                    ...
                    'max_corr_gcamp_mtor_by_plane', ...
                    'max_corr_mtor_mtor_by_plane', ...
                    ...
                    'coupling_gcamp_mtor_by_plane', ...
                    'coupling_pvalue_gcamp_mtor_by_plane' ...
                } ...
            ];
    end


    %==============================================================%
    % Charger fichier existant
    %==============================================================%

    if exist(filePath, 'file') == 2

        loaded = ...
            load(filePath);


        complete_file = ...
            true;


        %----------------------------------------------------------%
        % Champs requis
        %----------------------------------------------------------%

        for i = 1:numel(required_fields)

            if ~isfield( ...
                    loaded, ...
                    required_fields{i})

                complete_file = ...
                    false;

                break;
            end
        end


        %----------------------------------------------------------%
        % Nombre de plans
        %----------------------------------------------------------%

        if complete_file

            for i = 1:numel(required_fields)

                current_field = ...
                    loaded.( ...
                        required_fields{i});


                if ~iscell(current_field) || ...
                        numel(current_field) ~= nPlanes

                    complete_file = ...
                        false;

                    break;
                end
            end
        end


        %----------------------------------------------------------%
        % Fichier compatible
        %----------------------------------------------------------%

        if complete_file

            network_metrics = ...
                copy_network_metrics_from_struct( ...
                    loaded, ...
                    network_metrics, ...
                    nPlanes);


            fprintf( ...
                'Loading existing network metrics: %s\n', ...
                filePath);

            return;
        end


        fprintf( ...
            ['Existing network file incomplete or obsolete; ' ...
             'network metrics will be recomputed.\n']);
    end


    %==============================================================%
    % Calcul
    %==============================================================%

    fprintf( ...
        'Computing network metrics by plane for session %d\n', ...
        m);


    coupling_metrics = ...
        compute_gcamp_mtor_coupling_by_plane( ...
            data, ...
            m, ...
            sampling_rate);


    %==============================================================%
    % GCaMP-GCaMP Pearson
    %==============================================================%

    network_metrics. ...
        cross_corr_gcamp_gcamp_by_plane = ...
        coupling_metrics. ...
        cross_corr_gcamp_gcamp_by_plane;


    network_metrics. ...
        max_corr_gcamp_gcamp_by_plane = ...
        coupling_metrics. ...
        max_corr_gcamp_gcamp_by_plane;


    %==============================================================%
    % GCaMP-GCaMP coupling
    %==============================================================%

    network_metrics. ...
        coupling_gcamp_gcamp_by_plane = ...
        coupling_metrics. ...
        coupling_gcamp_gcamp_by_plane;


    network_metrics. ...
        coupling_pvalue_gcamp_gcamp_by_plane = ...
        coupling_metrics. ...
        coupling_pvalue_gcamp_gcamp_by_plane;


    %==============================================================%
    % mTOR
    %==============================================================%

    if process_electroporated

        %----------------------------------------------------------%
        % Pearson GCaMP-mTOR
        %----------------------------------------------------------%

        network_metrics. ...
            cross_corr_gcamp_mtor_by_plane = ...
            coupling_metrics. ...
            cross_corr_gcamp_mtor_by_plane;


        network_metrics. ...
            max_corr_gcamp_mtor_by_plane = ...
            coupling_metrics. ...
            max_corr_gcamp_mtor_by_plane;


        %----------------------------------------------------------%
        % Pearson mTOR-mTOR
        %----------------------------------------------------------%

        network_metrics. ...
            cross_corr_mtor_mtor_by_plane = ...
            coupling_metrics. ...
            cross_corr_mtor_mtor_by_plane;


        network_metrics. ...
            max_corr_mtor_mtor_by_plane = ...
            coupling_metrics. ...
            max_corr_mtor_mtor_by_plane;


        %----------------------------------------------------------%
        % Coupling mTOR-GCaMP
        %----------------------------------------------------------%

        network_metrics. ...
            coupling_gcamp_mtor_by_plane = ...
            coupling_metrics. ...
            coupling_gcamp_mtor_by_plane;


        network_metrics. ...
            coupling_pvalue_gcamp_mtor_by_plane = ...
            coupling_metrics. ...
            coupling_pvalue_gcamp_mtor_by_plane;
    end


    %==============================================================%
    % Normaliser nombre de plans
    %==============================================================%

    network_metrics = ...
        normalize_network_metrics_planes( ...
            network_metrics, ...
            nPlanes);


    %==============================================================%
    % Sauvegarde
    %==============================================================%

    save( ...
        filePath, ...
        '-struct', ...
        'network_metrics');


    fprintf( ...
        'Network metrics saved -> %s\n', ...
        filePath);
end


function metrics = ...
    empty_network_metrics()

    metrics = ...
        struct( ...
            ...
            'cross_corr_gcamp_gcamp_by_plane', {{}}, ...
            'cross_corr_gcamp_mtor_by_plane', {{}}, ...
            'cross_corr_mtor_mtor_by_plane', {{}}, ...
            ...
            'max_corr_gcamp_gcamp_by_plane', {{}}, ...
            'max_corr_gcamp_mtor_by_plane', {{}}, ...
            'max_corr_mtor_mtor_by_plane', {{}}, ...
            ...
            'coupling_gcamp_gcamp_by_plane', {{}}, ...
            'coupling_pvalue_gcamp_gcamp_by_plane', {{}}, ...
            ...
            'coupling_gcamp_mtor_by_plane', {{}}, ...
            'coupling_pvalue_gcamp_mtor_by_plane', {{}});
end


function metrics = ...
    initialize_network_metrics_planes( ...
        nPlanes)

    metrics = ...
        empty_network_metrics();


    fields = ...
        fieldnames(metrics);


    for i = 1:numel(fields)

        metrics.(fields{i}) = ...
            cell( ...
                1, ...
                nPlanes);
    end
end


function metrics = ...
    normalize_network_metrics_planes( ...
        metrics, ...
        nPlanes)

    fields = ...
        fieldnames(metrics);


    for i = 1:numel(fields)

        field_name = ...
            fields{i};


        metrics.(field_name) = ...
            ensure_plane_cell( ...
                metrics.(field_name), ...
                nPlanes);
    end
end


function output = ...
    copy_network_metrics_from_struct( ...
        loaded, ...
        output, ...
        nPlanes)

    fields = ...
        fieldnames(output);


    for i = 1:numel(fields)

        field_name = ...
            fields{i};


        if isfield( ...
                loaded, ...
                field_name)

            output.(field_name) = ...
                ensure_plane_cell( ...
                    loaded.(field_name), ...
                    nPlanes);
        end
    end
end


function c = ...
    ensure_plane_cell( ...
        c, ...
        nPlanes)

    if isempty(c)

        c = ...
            cell( ...
                1, ...
                nPlanes);

        return;
    end


    if ~iscell(c)

        c = ...
            {c};
    end


    c = ...
        c(:).';


    if numel(c) > nPlanes

        c = ...
            c(1:nPlanes);


    elseif numel(c) < nPlanes

        c = ...
            [ ...
                c, ...
                cell( ...
                    1, ...
                    nPlanes - numel(c)) ...
            ];
    end
end


function planes = ...
    get_planes_or_error_nested( ...
        data, ...
        branchName, ...
        m, ...
        fieldName)

    if ~isfield(data, branchName) || ...
            ~isstruct(data.(branchName))

        error( ...
            'Session %d: branche "%s" manquante.', ...
            m, ...
            branchName);
    end


    branch = ...
        data.(branchName);


    if ~isfield(branch, fieldName) || ...
            numel(branch.(fieldName)) < m || ...
            isempty(branch.(fieldName){m})

        error( ...
            'Session %d: champ "%s.%s" manquant ou vide.', ...
            m, ...
            branchName, ...
            fieldName);
    end


    planes = ...
        branch.(fieldName){m};


    if ~iscell(planes) || ...
            isempty(planes)

        error( ...
            ['Session %d: "%s.%s{%d}" doit être ' ...
             'une cell non vide de plans.'], ...
            m, ...
            branchName, ...
            fieldName, ...
            m);
    end
end