function network_metrics = ...
    load_or_process_network_metrics_for_session( ...
        gcamp_root_folders, ...
        data, ...
        m, ...
        sampling_rate, ...
        include_electroporated)

%LOAD_OR_PROCESS_NETWORK_METRICS_FOR_SESSION
%
% Charge ou calcule les métriques réseau d'un recording.
%
% GCaMP :
%
%   Pearson :
%       cross_corr_gcamp_gcamp_by_plane
%       max_corr_gcamp_gcamp_by_plane
%
%   Coupling :
%       coupling_gcamp_gcamp_by_plane
%       coupling_pvalue_gcamp_gcamp_by_plane
%
%
% mTOR :
%
%   Pearson :
%       cross_corr_gcamp_mtor_by_plane
%       max_corr_gcamp_mtor_by_plane
%       cross_corr_mtor_mtor_by_plane
%       max_corr_mtor_mtor_by_plane
%
%   Coupling :
%       coupling_gcamp_mtor_by_plane
%       coupling_pvalue_gcamp_mtor_by_plane
%
%
% Aucun lag ni résultat brut de shuffle n'est sauvegardé.


    %==============================================================%
    % Options
    %==============================================================%

    if nargin < 5 || ...
            isempty(include_electroporated)

        include_electroporated = ...
            '1';
    end


    include_electroporated = ...
        char(string(include_electroporated));


    process_electroporated = ...
        strcmp( ...
            include_electroporated, ...
            '1');


    %==============================================================%
    % Initialisation
    %==============================================================%

    network_metrics = ...
        empty_network_metrics();


    %==============================================================%
    % Vérification dossier
    %==============================================================%

    if isempty(gcamp_root_folders) || ...
            m > numel(gcamp_root_folders) || ...
            isempty(gcamp_root_folders{m})

        fprintf( ...
            ['Session %d: gcamp_root_folders vide, ' ...
             'skip network metrics.\n'], ...
            m);

        return;
    end


    %==============================================================%
    % Fichier
    %==============================================================%

    filePath = ...
        fullfile( ...
            gcamp_root_folders{m}, ...
            'results_network.mat');


    %==============================================================%
    % Nombre de plans
    %==============================================================%

    DFg_planes = ...
        get_planes_or_error_nested( ...
            data, ...
            'gcamp_plane', ...
            m, ...
            'DF_gcamp_by_plane');


    DFb_planes = get_planes_optional_nested( ...
        data, 'electroporated_plane', m, 'DF_electroporated_by_plane');

    nPlanes = max(numel(DFg_planes), numel(DFb_planes));
    cache_version = 'source_shuffle_fdr_1000_v2';


    %==============================================================%
    % Préallocation
    %==============================================================%

    network_metrics = ...
        initialize_network_metrics_planes( ...
            nPlanes);


    %==============================================================%
    % Champs GCaMP requis
    %==============================================================%

    required_fields = { ...
        ...
        'cross_corr_gcamp_gcamp_by_plane', ...
        'max_corr_gcamp_gcamp_by_plane', ...
        ...
        'coupling_gcamp_gcamp_by_plane', ...
        'coupling_pvalue_gcamp_gcamp_by_plane', ...
        'coupling_qvalue_gcamp_gcamp_by_plane' ...
    };


    %==============================================================%
    % Champs mTOR requis
    %==============================================================%

    if process_electroporated

        required_fields = ...
            [ ...
                required_fields, ...
                { ...
                    'cross_corr_gcamp_mtor_by_plane', ...
                    'cross_corr_mtor_mtor_by_plane', ...
                    ...
                    'max_corr_gcamp_mtor_by_plane', ...
                    'max_corr_mtor_mtor_by_plane', ...
                    ...
                    'coupling_gcamp_mtor_by_plane', ...
                    'coupling_pvalue_gcamp_mtor_by_plane', ...
                    'coupling_qvalue_gcamp_mtor_by_plane' ...
                } ...
            ];
    end


    %==============================================================%
    % Chargement : ne jamais reutiliser un cache simplement parce que
    % ses champs existent. Verifier version, plans et dimensions reelles.
    %==============================================================%
    if exist(filePath, 'file') == 2
        try
            loaded = load(filePath);
            cache_ok = network_cache_compatible( ...
                loaded, required_fields, nPlanes, DFg_planes, ...
                DFb_planes, process_electroporated, ...
                sampling_rate, cache_version);
            if cache_ok
                network_metrics = copy_network_metrics_from_struct( ...
                    loaded, network_metrics, nPlanes);
                fprintf('Network: cache valide charge : %s\n', filePath);
                return;
            end
            fprintf('Network: cache incomplet/ancien ou vide : recalcul complet (%s).\n', filePath);
        catch ME
            warning('Network: impossible de lire/valider le cache %s : %s. Recalcul.', ...
                filePath, ME.message);
        end
    end

    %==============================================================%
    % Calcul
    %==============================================================%

    fprintf( ...
        'Computing network metrics by plane for session %d\n', ...
        m);


    coupling_metrics = ...
        compute_gcamp_mtor_coupling_by_plane( ...
            data, ...
            m, ...
            sampling_rate);


    %==============================================================%
    % GCaMP-GCaMP Pearson
    %==============================================================%

    network_metrics. ...
        cross_corr_gcamp_gcamp_by_plane = ...
        coupling_metrics. ...
        cross_corr_gcamp_gcamp_by_plane;


    network_metrics. ...
        max_corr_gcamp_gcamp_by_plane = ...
        coupling_metrics. ...
        max_corr_gcamp_gcamp_by_plane;


    %==============================================================%
    % GCaMP-GCaMP coupling
    %==============================================================%

    network_metrics. ...
        coupling_gcamp_gcamp_by_plane = ...
        coupling_metrics. ...
        coupling_gcamp_gcamp_by_plane;


    network_metrics. ...
        coupling_pvalue_gcamp_gcamp_by_plane = ...
        coupling_metrics. ...
        coupling_pvalue_gcamp_gcamp_by_plane;

    network_metrics.coupling_qvalue_gcamp_gcamp_by_plane = ...
        coupling_metrics.coupling_qvalue_gcamp_gcamp_by_plane;


    %==============================================================%
    % mTOR
    %==============================================================%

    if process_electroporated

        %----------------------------------------------------------%
        % Pearson GCaMP-mTOR
        %----------------------------------------------------------%

        network_metrics. ...
            cross_corr_gcamp_mtor_by_plane = ...
            coupling_metrics. ...
            cross_corr_gcamp_mtor_by_plane;


        network_metrics. ...
            max_corr_gcamp_mtor_by_plane = ...
            coupling_metrics. ...
            max_corr_gcamp_mtor_by_plane;


        %----------------------------------------------------------%
        % Pearson mTOR-mTOR
        %----------------------------------------------------------%

        network_metrics. ...
            cross_corr_mtor_mtor_by_plane = ...
            coupling_metrics. ...
            cross_corr_mtor_mtor_by_plane;


        network_metrics. ...
            max_corr_mtor_mtor_by_plane = ...
            coupling_metrics. ...
            max_corr_mtor_mtor_by_plane;


        %----------------------------------------------------------%
        % Coupling mTOR-GCaMP
        %----------------------------------------------------------%

        network_metrics. ...
            coupling_gcamp_mtor_by_plane = ...
            coupling_metrics. ...
            coupling_gcamp_mtor_by_plane;


        network_metrics. ...
            coupling_pvalue_gcamp_mtor_by_plane = ...
            coupling_metrics. ...
            coupling_pvalue_gcamp_mtor_by_plane;

        network_metrics.coupling_qvalue_gcamp_mtor_by_plane = ...
            coupling_metrics.coupling_qvalue_gcamp_mtor_by_plane;
    end


    %==============================================================%
    % Normaliser nombre de plans
    %==============================================================%

    network_metrics = ...
        normalize_network_metrics_planes( ...
            network_metrics, ...
            nPlanes);


    %==============================================================%
    % Sauvegarde
    %==============================================================%

    % Refuser de sauver un resultat vide si les DF existent.
    to_save = network_metrics;
    to_save.network_cache_version = cache_version;
    to_save.network_sampling_rate = sampling_rate;
    if ~network_cache_compatible( ...
            to_save, required_fields, nPlanes, DFg_planes, ...
            DFb_planes, process_electroporated, sampling_rate, cache_version)
        error('Network: calcul vide ou dimensions incoherentes (rec %d). Aucun cache ecrase.', m);
    end

    % Un echec d'ecriture ne doit pas effacer les resultats en memoire.
    try
        save(filePath, '-struct', 'to_save');
        fprintf('Network metrics saved -> %s\n', filePath);
    catch ME
        warning('Network: resultats calcules, mais sauvegarde impossible : %s', ME.message);
    end
end


function metrics = ...
    empty_network_metrics()

    metrics = ...
        struct( ...
            ...
            'cross_corr_gcamp_gcamp_by_plane', {{}}, ...
            'cross_corr_gcamp_mtor_by_plane', {{}}, ...
            'cross_corr_mtor_mtor_by_plane', {{}}, ...
            ...
            'max_corr_gcamp_gcamp_by_plane', {{}}, ...
            'max_corr_gcamp_mtor_by_plane', {{}}, ...
            'max_corr_mtor_mtor_by_plane', {{}}, ...
            ...
            'coupling_gcamp_gcamp_by_plane', {{}}, ...
            'coupling_pvalue_gcamp_gcamp_by_plane', {{}}, ...
            'coupling_qvalue_gcamp_gcamp_by_plane', {{}}, ...
            ...
            'coupling_gcamp_mtor_by_plane', {{}}, ...
            'coupling_pvalue_gcamp_mtor_by_plane', {{}}, ...
            'coupling_qvalue_gcamp_mtor_by_plane', {{}});
end


function metrics = ...
    initialize_network_metrics_planes( ...
        nPlanes)

    metrics = ...
        empty_network_metrics();


    fields = ...
        fieldnames(metrics);


    for i = 1:numel(fields)

        metrics.(fields{i}) = ...
            cell( ...
                1, ...
                nPlanes);
    end
end


function metrics = ...
    normalize_network_metrics_planes( ...
        metrics, ...
        nPlanes)

    fields = ...
        fieldnames(metrics);


    for i = 1:numel(fields)

        field_name = ...
            fields{i};


        metrics.(field_name) = ...
            ensure_plane_cell( ...
                metrics.(field_name), ...
                nPlanes);
    end
end


function output = ...
    copy_network_metrics_from_struct( ...
        loaded, ...
        output, ...
        nPlanes)

    fields = ...
        fieldnames(output);


    for i = 1:numel(fields)

        field_name = ...
            fields{i};


        if isfield( ...
                loaded, ...
                field_name)

            output.(field_name) = ...
                ensure_plane_cell( ...
                    loaded.(field_name), ...
                    nPlanes);
        end
    end
end


function c = ...
    ensure_plane_cell( ...
        c, ...
        nPlanes)

    if isempty(c)

        c = ...
            cell( ...
                1, ...
                nPlanes);

        return;
    end


    if ~iscell(c)

        c = ...
            {c};
    end


    c = ...
        c(:).';


    if numel(c) > nPlanes

        c = ...
            c(1:nPlanes);


    elseif numel(c) < nPlanes

        c = ...
            [ ...
                c, ...
                cell( ...
                    1, ...
                    nPlanes - numel(c)) ...
            ];
    end
end


function planes = ...
    get_planes_or_error_nested( ...
        data, ...
        branchName, ...
        m, ...
        fieldName)

    if ~isfield(data, branchName) || ...
            ~isstruct(data.(branchName))

        error( ...
            'Session %d: branche "%s" manquante.', ...
            m, ...
            branchName);
    end


    branch = ...
        data.(branchName);


    if ~isfield(branch, fieldName) || ...
            numel(branch.(fieldName)) < m || ...
            isempty(branch.(fieldName){m})

        error( ...
            'Session %d: champ "%s.%s" manquant ou vide.', ...
            m, ...
            branchName, ...
            fieldName);
    end


    planes = ...
        branch.(fieldName){m};


    if ~iscell(planes)
        planes = {planes};
    end
    if isempty(planes)
        error('Session %d: %s.%s{%d} ne contient aucun plan.', ...
            m, branchName, fieldName, m);
    end
end

function planes = get_planes_optional_nested(data, branch_name, m, field_name)
    planes = {};
    if ~isstruct(data) || ~isfield(data,branch_name) || ...
            ~isstruct(data.(branch_name))
        return;
    end
    b = data.(branch_name);
    if ~isfield(b,field_name) || ~iscell(b.(field_name)) || ...
            numel(b.(field_name)) < m || isempty(b.(field_name){m})
        return;
    end
    planes = b.(field_name){m};
    if ~iscell(planes), planes = {planes}; end
end


function ok = network_cache_compatible(cached, required_fields, nPlanes, ...
        DFg_planes, DFb_planes, include_mtor, sampling_rate, version)
    ok = false;
    if ~isstruct(cached) || ~isfield(cached,'network_cache_version') || ...
            ~strcmp(char(string(cached.network_cache_version)),version) || ...
            ~isfield(cached,'network_sampling_rate') || ...
            ~isnumeric(cached.network_sampling_rate) || ...
            ~isscalar(cached.network_sampling_rate) || ...
            abs(cached.network_sampling_rate - sampling_rate) > ...
                1e-6 * max(1,abs(sampling_rate))
        return;
    end
    for f = 1:numel(required_fields)
        name = required_fields{f};
        if ~isfield(cached,name) || ~iscell(cached.(name)) || ...
                numel(cached.(name)) ~= nPlanes
            return;
        end
    end

    for p = 1:nPlanes
        DFg = [];
        DFb = [];
        if p <= numel(DFg_planes), DFg = DFg_planes{p}; end
        if p <= numel(DFb_planes), DFb = DFb_planes{p}; end
        if isempty(DFg) || size(DFg,2) < 3
            continue;
        end
        nG = size(DFg,1);
        if ~cache_matrix(cached.cross_corr_gcamp_gcamp_by_plane{p},nG,nG) || ...
                ~cache_vector(cached.max_corr_gcamp_gcamp_by_plane{p},nG)
            return;
        end
        if nG >= 2 && ...
                (~cache_vector(cached.coupling_gcamp_gcamp_by_plane{p},nG) || ...
                 ~cache_vector(cached.coupling_pvalue_gcamp_gcamp_by_plane{p},nG) || ...
                 ~cache_vector(cached.coupling_qvalue_gcamp_gcamp_by_plane{p},nG))
            return;
        end
        if ~include_mtor || isempty(DFb) || size(DFb,2) < 3
            continue;
        end
        nM = size(DFb,1);
        if ~cache_matrix(cached.cross_corr_gcamp_mtor_by_plane{p},nG,nM) || ...
                ~cache_matrix(cached.cross_corr_mtor_mtor_by_plane{p},nM,nM) || ...
                ~cache_vector(cached.max_corr_gcamp_mtor_by_plane{p},nM) || ...
                ~cache_vector(cached.max_corr_mtor_mtor_by_plane{p},nM) || ...
                ~cache_vector(cached.coupling_gcamp_mtor_by_plane{p},nM) || ...
                ~cache_vector(cached.coupling_pvalue_gcamp_mtor_by_plane{p},nM) || ...
                ~cache_vector(cached.coupling_qvalue_gcamp_mtor_by_plane{p},nM)
            return;
        end
    end
    ok = true;
end

function ok = cache_matrix(value,nRows,nCols)
    ok = isnumeric(value) && isequal(size(value),[nRows,nCols]);
end

function ok = cache_vector(value,nElements)
    ok = isnumeric(value) && numel(value) == nElements;
end
